### ISSUE TITLE
PostgREST with  Nginx

### ISSUE THREAD

**Issue by guiuprado** [PostgREST/postgrest#1028]
Hello everybody! If anybody have envolves with this type off task would be helpful some suggestions.

I have setup a environment with using 3 equal database. The environment was build using a Nginx + Upstream pointing to a PostgREST setter like a service on Linux CentOS 7x64.

All is great but I'm worried if I need to setup more environments with services configurations and ports to set on Nginx and PostgREST.

So anyone know some other way for exemple using tools like passenger (ruby) or php-fpm, equivalent for Haskell.

Using tools like that will make more easy the management.

PS.
In a quick search I find this links.
https://hackage.haskell.org/package/ngx-export
https://github.com/lyokha/nginx-haskell-module

**Comment by begriffs** [comment]
> All is great but I'm worried if I need to setup more environments with services configurations and ports to set on Nginx and PostgREST.

Can you explain a little more about your concern?

**Comment by guiuprado** [comment]
When an environment is configurated we basically use Ngnix to expose PostgREST hiding the IP and Port. So, we create a linux service because we want PostgREST start automatically. 

 

For each API we expose we need to create manually these settings: 

 

1) Create a service file on systemd 

/usr/systemd/system/postgrest-env1.service 

[Unit] 

Description=PostgREST Http RESTfull  
After=pgbouncer.service 
  

[Service] 

Type=simple 
EnvironmentFile=-/opt/postgrest 
ExecStart=/opt/postgrest/postgrest /opt/postgrest/config/cognatis.billing.conf 

 
[Install] 

WantedBy=multi-user.target 

 

2) Create a configuration on Nginx to point the PostgREST port: 

/etc/nginx/conf.d/postgrest-env1.conf 

upstream postgrest-env1 { 

  server localhost:65000; 

  keepalive 64; 

} 

 

3) Create a configuration on Nginx to expose URL a point to upstream: 

   location /postgrest/env1/api/ { 

      default_type  application/json; 

      proxy_hide_header Content-Location; 

      add_header Content-Location  /postgrest/env1/api/$upstream_http_content_location; 

      proxy_set_header  Connection ""; 

      proxy_http_version 1.1; 

      proxy_pass http://postgrest-env1/; 

   } 

 

4) Configure PostgREST files.  

   ##production 

  db-uri = "host='xxx.xxx.xxx.xxx' user='xxx' port='xxx' dbname='xxxx' password='xxxx'"   

  db-schema = "default" 

  db-anon-role = "swichter" 

  db-pool = 50  

  server-host = "*4" 

  server-port = 65000   

  jwt-secret = "@/opt/postgrest/config/postgrest-env1.key"   

  secret-is-base64 = true  

 

For each service we want to setup we always need to configurated all these things. It's not a problem at all, but if we can avoid some steps this make simple to scale and maintain PostgREST deployments. Working with a Haskell module in Nginx or Apache it's possible to avoid the step 1, 2 and 3, making the configuration of the module on Nginx base config file and let him create the instances of the PostgREST on ports they want to, like passenger [ruby, python and nodejs](https://www.phusionpassenger.com/library/config/nginx/reference/) or php-frm. 

I found some Haskell modules for Ngnix describe on fist post, but before more reach (https://www.yesodweb.com/book/deploying-your-webapp) I start to think it's not possible work in Haskell like the other deployment scenarios.

**Comment by monacoremo** [comment]
Configuation with env variables should make this easier. Not a core PostgREST issue, closing for now.
