### ISSUE TITLE
The docker-compose.yml file can not work now , please emerge a rigth one.

### ISSUE THREAD

**Issue by chaim1986** [PostgREST/postgrest#1029]
Since 0.4.3 the docker hub have changed to postgrest/postgrest , the docker-compose.yml file in “docker” directory can not work now.
I think it will be very nice to update the README  and give a example to start postgrest.

----a worked docker-compose 

version: '2'
services:
  postgrest:
       image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: wlc1986
      POSTGRES_USER: postgres
    stdin_open: true
    tty: true
    ports:
    - 5432:5432/tcp
    volumes:
     - ./postgres-data:/var/lib/postgresql/data
  postgrest:
    image: postgrest/postgrest
    environment:
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_SCHEMA: api
      PGRST_DB_URI: postgres://postgres:wlc1986@postgres/postgres
      PGRST_SERVER_PROXY_URI: http://192.168.89.99:3000
      PGRST_JWT_SECRET: g+59lPOa245dQ+p5Efi5uH9Rdjr6rOWEj6x9guvkrtI=
    links:
    - postgres:postgres
    ports:
    - 3000:3000/tcp

**Comment by begriffs** [comment]
Yeah the change to the new docker hub repo wasn't announced very well. We did change the link in our docker badge at the top of the readme but not much else. Also other people's postgrest docker files around github point at our old repo.

Would really like it if there was a way to automatically redirect from docker hub itself. So anyone visiting that repo would get a big message to see the new one, or perhaps would even just auto redirect there. Do you know if this is possible?

**Comment by chaim1986** [comment]
Maybe there isn't a way to redirect to the new repo automatically now... 
So I think it will be very nice enough to update the section of 'Usage' in README.md , and show a right docker-compose file (as my first comment.).  or just update the 'docker-compose.yml' in the docker directory

**Comment by steve-chavez** [comment]
Closing, seems this was solved quite a while ago.
