### ISSUE TITLE
Troube installing v0.4.3.0

### ISSUE THREAD

**Issue by waghanza** [PostgREST/postgrest#1030]
Hi,

I'm using **Haskell** `8.0.2` and I'm facing this on `cabal install postgrest.cabal`

```
Preprocessing library postgrest-0.4.3.0...
[ 3 of 14] Compiling PostgREST.Types  ( src/PostgREST/Types.hs, dist/build/PostgREST/Types.o )
[ 4 of 14] Compiling PostgREST.Parsers ( src/PostgREST/Parsers.hs, dist/build/PostgREST/Parsers.o )
[ 5 of 14] Compiling PostgREST.Error  ( src/PostgREST/Error.hs, dist/build/PostgREST/Error.o )
[ 6 of 14] Compiling PostgREST.DbStructure ( src/PostgREST/DbStructure.hs, dist/build/PostgREST/DbStructure.o )
[ 7 of 14] Compiling PostgREST.Auth   ( src/PostgREST/Auth.hs, dist/build/PostgREST/Auth.o )

src/PostgREST/Auth.hs:54:9: error:
    Variable not in scope:
      validateJWSJWT
        :: ((StringOrURI -> Bool) -> JWTValidationSettings)
           -> JWK -> a1 -> ExceptT JWTError IO a0

src/PostgREST/Auth.hs:58:47: error:
    • Variable not in scope: jwtClaimsSet :: a1 -> ClaimsSet
    • Perhaps you meant ‘jwtClaims’ (line 46)

src/PostgREST/Auth.hs:92:24: error:
    • Couldn't match expected type ‘Base64Octets -> OctKeyParameters’
                  with actual type ‘OctKeyParameters’
    • The function ‘OctKeyParameters’ is applied to two arguments,
      but its type ‘Base64Octets -> OctKeyParameters’ has only one
      In the first argument of ‘OctKeyMaterial’, namely
        ‘(OctKeyParameters Oct (Base64Octets key))’
      In the expression:
        OctKeyMaterial (OctKeyParameters Oct (Base64Octets key))

src/PostgREST/Auth.hs:92:41: error:
    Data constructor not in scope: Oct :: Base64Octets
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
postgrest-0.4.3.0 failed during the building phase. The exception was:
ExitFailure 1
```

Has somebody face this problem ?

Regards,

**Comment by begriffs** [comment]
It looks as if you're using the wrong version of the `jose` library or something. We're currently using package versions pinned at Stackage's [LTS-9.6](https://www.stackage.org/lts-9.6), so compare the package versions there with what cabal has installed locally.

If it turns out that this problem was a dependency version thing I'll tighten up the constraints in our cabal file. Even though we rely on Stackage snapshots for building, I want to ensure it also builds cleanly for vanilla Cabal.

**Comment by waghanza** [comment]
@begriffs so quick ^^

In fact, I'm (still) building binaries to distribute into **debian** community, and for this I'm using the official cabal way and `stackage` is not supported ;-)

Are binaries (hosted on https://github.com per release built by `stackage` ?)

**Comment by begriffs** [comment]
Stackage doesn't build any binaries for us, it just has a server where they test the compatibility of package versions with one another, and publish "snapshots," each of which is recommendations for a set of dependency versions that appear to work properly together.

We make binaries with a continuous integration script that triggers for tagged versions in git. And I personally build it for a few extra platforms like FreeBSD that we haven't automated yet.

**Comment by begriffs** [comment]
Try running `cabal freeze` and paste the output it writes in `cabal.config` and we can see what dependency versions it is trying to use.

**Comment by waghanza** [comment]
sorry, I have removed my answer since I am not sure my affirmation is still actual

**Comment by waghanza** [comment]
@begriffs The result of `cabal freeze` is https://git.io/vbqol

It seems to be a problem with the JWT lib (I think)

**Comment by begriffs** [comment]
OK, I tried building the master branch on a fresh Debian 9.3 machine and it worked for me. This is what I did:

```bash
sudo apt-get update
sudo apt-get install ghc cabal-install git libpq-dev libgmp-dev happy zlib1g-dev

# ghc --version
# The Glorious Glasgow Haskell Compilation System, version 8.0.1

# cabal --version
# cabal-install version 1.24.0.1
# compiled using version 1.24.1.0 of the Cabal library

git clone https://github.com/begriffs/postgrest.git
cd postgrest

# git rev-parse HEAD
# 70ce1b9329642f4a216826df045844dd2adbc7d8

cabal update
cabal install --dependencies-only

cabal build
```

Could you see if the build problem has gone away for you with postgrest 0.4.4?

**Comment by steve-chavez** [comment]
New releases will be buildable with `cabal`, pinned package versions were missing previously(like jose) which caused some errors. Made this change in https://github.com/PostgREST/postgrest/pull/1177.
