### ISSUE TITLE
Failed to query the database.

### ISSUE THREAD

**Issue by bylee5** [PostgREST/postgrest#1052]
I built from source.
I run the server like:
$ stack exec postgrest -- tutorial.conf
$ cat tutorial.conf
db-uri = "postgres://bylee:bylee@localhost:5432/agens"
db-schema = "public"
db-anon-role = "bylee"

The error is like:
$ stack exec postgrest -- tutorial.conf 
Listening on port 3000
Attempting to connect to the database...
Failed to query the database. Retrying.
{"hint":null,"details":null,"code":"42601","message":"syntax error at or near \"match\""}
Attempting to connect to the database...
Failed to query the database. Retrying.
{"hint":null,"details":null,"code":"42601","message":"syntax error at or near \"match\""}
Attempting to connect to the database...
Failed to query the database. Retrying.
{"hint":null,"details":null,"code":"42601","message":"syntax error at or near \"match\""}
Attempting to connect to the database...
Failed to query the database. Retrying.
{"hint":null,"details":null,"code":"42601","message":"syntax error at or near \"match\""}
Attempting to connect to the database...
Failed to query the database. Retrying.
{"hint":null,"details":null,"code":"42601","message":"syntax error at or near \"match\""}

Can you help me?

**Comment by ruslantalpa** [comment]
What postgresql version are you using?

**Comment by bylee5** [comment]
I am using version 9.6.2.

**Comment by ruslantalpa** [comment]
i see the word `match` in this query https://github.com/begriffs/postgrest/blob/516976e32fa3d8b8e8cc6b6e02bc02ee1e4964ca/src/PostgREST/DbStructure.hs#L669-L735

try running it directly in your db and check if it gives you an error.

**Comment by bylee5** [comment]
@ruslantalpa thank you. I checked a same error.

**Comment by ruslantalpa** [comment]
the postgres code is being tested agains pg 9.6 (and was also running on pg 9.3) so a query givving you an error is odd. My guess is you are using the clinet version 9.6 (psql) but the server you are connecting to is older.
try running the query `select version()`.

**Comment by steve-chavez** [comment]
According to:

> My PostgreSQL seems to have encountered this problem because some user-defined keywords have been added. After modifying that file, I connected to DB normally.

This is already solved so closing.
