### ISSUE TITLE
"WITH local check option" where user_id is in a different table

### ISSUE THREAD

**Issue by ACPK** [PostgREST/postgrest#1056]
How would I add  "WITH local check option"  to a table where the user_id is in a different table. The issue is that I need to grab the user_id via a left_join.

**Comment by steve-chavez** [comment]
Probably not an issue anymore, but you can use [RLS](https://www.postgresql.org/docs/11/ddl-rowsecurity.html)(ctrl+f WITH CHECK) instead of `WITH LOCAL check` on the view, it's more flexible.
