### ISSUE TITLE
Support for empty JSON input to rpc function

### ISSUE THREAD

**Issue by pauldzy** [PostgREST/postgrest#1058]
Hello,

PostgREST is great.  

I have a function with JSON parameters that I would like to expose through the rpc interface.  These parameters are optional and various js apis submit them as an empty parameter such as /rpc/myfunction?myjson=&otherparam=1 

PostgREST seems to currently pass this empty parameter as an empty string to a JSON constructor such that the result is 
{"hint":null,"details":"The input string ended unexpectedly.","code":"22P02","message":"invalid input syntax for type json"}

It would be swell if the empty condition was detected and then passed as NULL or perhaps '{}'::JSON.  I think the former is better.

Thanks,
Paul

**Comment by NikolayS** [comment]
You can achieve what you want using POST instead of GET, and using `Prefer: params=single-object` header in your requests.

From the docs:

> You can also call a function that takes a single parameter of type json by sending the header Prefer: params=single-object with your request. That way the JSON request body will be used as the single argument.

Example:
```plpgsql
create or replace function v2.jsonparamed(in param jsonb, out result jsonb) as $$
begin
  result := json_build_object(
    'status', 'ok',
    'orig_params', param
  );
end;
$$ language plpgsql;
```

Then calls like these will work:
```http
POST /rpc/jsonparamed HTTP/1.1
Host: localhost:7777
Content-Type: application/json
Prefer: params=single-object
Cache-Control: no-cache

{"ids": [1212, 2434]}
```

with no params provided:
```http
POST /rpc/jsonparamed HTTP/1.1
Host: localhost:7777
Content-Type: application/json
Prefer: params=single-object
Cache-Control: no-cache
```

**Comment by pauldzy** [comment]
Thanks for the attention.
I am not able to prevent users from using GET so perhaps will just drop JSON and use a comma delimited string for the parameter. I think what you are saying is go all JSON or no JSON.  Mixing and matching scalars with JSON chunks is not supported.  Thanks again.

**Comment by steve-chavez** [comment]
I think in most cases is preferable to err on the invalid json `""`, would not like to give up on that strictness and let PostgreSQL do all the validation so for now I don't see this being implemented, but you have a couple of options:  

- As per Nikolay's suggestion you can have a single json param, but I'll add that you can also use `Prefer: params=single-object` with GET, so if you have:

```sql
create function api.fun(a json) returns json as $$ select a $$ language sql;
```

Then it can be called as `/fun?b=&c=4` and it will return a `{"b":"3","c":""}`. It'll not err on an empty param.

- You can have a `text` param and then transform it to `json`,  by using `nullif` you can avoid the error:

```sql
create function api.fun_two(myjson text, otherparam int) returns table(myjson json, otherparam int) as $$ 
  select nullif(trim(myjson), '')::json, otherparam 
$$ language sql;
```
