### ISSUE TITLE
Respond with HTTP 200 instead of 201 when no rows inserted

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#1070]
Currently this is happening with POST when the payload is `[]`, see: https://github.com/begriffs/postgrest/blob/108f3cd651a448fad065faf81a2090cee8a8d9fb/test/Feature/InsertSpec.hs#L129-L135

And when `Prefer: resolution=ignore-duplicates` is specified and all rows in the payload are duplicates: https://github.com/begriffs/postgrest/blob/108f3cd651a448fad065faf81a2090cee8a8d9fb/test/Feature/UpsertSpec.hs#L95-L101.

Also according to [RFC](https://tools.ietf.org/html/rfc7231#section-4.3.4), PUT should respond with 200 when the row is updated and with 201 when the row is inserted, currently it's always responding with 200.

These cases can be corrected by using the [xmax](https://www.postgresql.org/docs/10/static/ddl-system-columns.html) system column, as described [here](https://stackoverflow.com/questions/39058213/postgresql-upsert-differentiate-inserted-and-updated-rows-using-system-columns-x/39204667#39204667).

**Comment by steve-chavez** [comment]
The `xmax` trick wouldn't work with auto-updatable VIEWs since only TABLEs have them.

**Comment by wolfgangwalther** [comment]
[This](https://stackoverflow.com/a/34768232) could work for both tables and views, I think.

**Comment by taimoorzaeem** [comment]
@steve-chavez The design for this fix/feature seems rather vague. I am thinking of implementing it the following way:

- Add `inserted` and `updated` fields in `ResultSet` here.
https://github.com/PostgREST/postgrest/blob/57fa2719ddade4c25aa12acea355ca6ee93a466e/src/PostgREST/Query/Statements.hs#L37-L53

- Add the local GUCs `pgrst.inserted` and `pgrst.updated` in the query here and then read them with `AS` in `prepareWrite` statement.
https://github.com/PostgREST/postgrest/blob/57fa2719ddade4c25aa12acea355ca6ee93a466e/src/PostgREST/Query/QueryBuilder.hs#L85-L105

- Then, use `Hasql.decoders` to decode `pgrst.inserted` and `pgrst.updated` variables. Compare them and set `rsGucStatus` accordingly.

I am not very familiar with PostgreSQL IO yet, let me know other things that need to be changed for this fix.

**Comment by steve-chavez** [comment]
@taimoorzaeem Looks good. Go ahead :+1:

**Comment by taimoorzaeem** [comment]
@steve-chavez @wolfgangwalther  How do I add and increment local GUCs in the middle of the query? For example, consider this:

https://github.com/PostgREST/postgrest/blob/57fa2719ddade4c25aa12acea355ca6ee93a466e/src/PostgREST/Query/QueryBuilder.hs#L85-L105

To count the number of inserts and updates I would have to repeatedly read with something like `current_setting('pgrst.inserted',true)` and increment it with `set_config('pgrst.inserted', (current_setting('pgrst.inserted',true)::int + 1)::text,true)`. The same goes for updates. 

It seems too complicated to be added in this query. Besides I don't think we can use `set_config(..)` and `current_setting(..)` like that in an `INSERT` statement. How else can we handle this?

**Comment by laurenceisla** [comment]
@taimoorzaeem Yes, I see that it gets a bit complex for batch upserts. To answer your question, the `pgrst.inserted` would be added to this line: https://github.com/PostgREST/postgrest/blob/57fa2719ddade4c25aa12acea355ca6ee93a466e/src/PostgREST/Query/QueryBuilder.hs#L90

This is how it would look like (maybe nullif is not necessary, but [does some wonky things when testing](https://gist.github.com/steve-chavez/8d7033ea5655096903f3b52f8ed09a15)):
```sql
where coalesce(set_config('pgrst.inserted', (coalesce(nullif(current_setting('pgrst.inserted', true), '')::int, 0) + 1)::text, true),'0') <> '0'
```

The `pgrst.updated` should be added to: https://github.com/PostgREST/postgrest/blob/57fa2719ddade4c25aa12acea355ca6ee93a466e/src/PostgREST/Query/QueryBuilder.hs#L90
And it would look like:
```sql
where coalesce(set_config('pgrst.updated', (coalesce(nullif(current_setting('pgrst.updated', true), '')::int, 0) + 1)::text, true),'0') <> '0'
```
After that you'd follow the logic mentioned by Wolfgang: https://github.com/PostgREST/postgrest/issues/1070#issuecomment-740672760

As an example, using the `projects` table from the Spec test, the the end result would follow this structure:

```sql
insert into api.projects (id, name)
-- just an example of inserted values values (1-5 already exist)
select id,name from (select 2, 'Windows 11' union all
                     select 3, 'Android' union all
                     select 6, 'NixOS' union all
                     select 5, 'Old OS' union all
                     select 7, 'New OS') pgrst_values(id,name)
where coalesce(set_config('pgrst.inserted', (coalesce(nullif(current_setting('pgrst.inserted', true), '')::int, 0) + 1)::text, true),'0') <> '0'
on conflict (id)
  do update set name = excluded.name
  where coalesce(set_config('pgrst.updated', (coalesce(nullif(current_setting('pgrst.updated', true), '')::int, 0) + 1)::text, true),'0') <> '0'
returning 1;
```

---

As an alternative we could use a single config `pgrst.mutation` (instead of inserted and updated), wrap the insert in a `WITH` statement and then get the count() of every update/insert we get. The structure would be like:

```sql
WITH pgrst_insert as (
  insert into api.projects (id, name)
  -- just an example of inserted values values (1-5 already exist)
  select id,name from (select 2, 'Windows 11' union all
                       select 3, 'Android' union all
                       select 6, 'NixOS' union all
                       select 5, 'Old OS' union all
                       select 7, 'New OS') pgrst_values(id,name)
  where 'inserted' = set_config('pgrst.mutation', 'inserted', true)
  on conflict (id)
    do update set name = excluded.name
    where 'updated' = set_config('pgrst.mutation', 'updated', true)
  returning current_setting('pgrst.mutation') as mutation
)
select count(nullif(mutation, 'updated')) as rows_inserted,
       count(nullif(mutation, 'inserted')) as rows_updated,
       count(1) as rows_total
from pgrst_insert;
```

I'm not sure if we need the exact quantity of updates/inserts, if not, it could be more performant I think.

**Comment by steve-chavez** [comment]
> I'm not sure if we need the exact quantity of updates/inserts, if not, it could be more performant I think (won't need count and possibly the CTE).

Btw, to check if the queries are performant, there's a helper for pgbench tests https://github.com/PostgREST/postgrest/tree/main/test/pgbench

That isn't part of the test suite but it can be used to share results and see if a query is worth doing.

**Comment by laurenceisla** [comment]
OK, I think we do not need to know how many rows are inserted/updated, only if there was at least one insert. If that's so, the query gets simpler: we'll only need to return a flag when it's inserted and finally count if that flag is greater than 0 (it appears at least once). Finally, the query would look like:

```sql
WITH pgrst_insert as (
  insert into api.projects (id, name)
  -- just an example of inserted values values (1-5 already exist)
  select id,name from (select 2, 'Windows 11' union all
                       select 3, 'Android' union all
                       select 6, 'NixOS' union all
                       select 5, 'Old OS' union all
                       select 7, 'New OS') pgrst_values(id,name)
  where '1' = set_config('pgrst.inserted', '1', true)
  on conflict (id)
    do update set name = excluded.name
    where '0' = set_config('pgrst.inserted', '0', true)
  returning current_setting('pgrst.inserted') as inserted
)
select count(nullif(inserted, '0')) > 0 as inserted
from pgrst_insert;
```

**Comment by taimoorzaeem** [comment]
@laurenceisla @steve-chavez 
The problem I am facing is with `returning`
```sql
returning current_setting('pgrst.inserted') as inserted
```
Using `returning`, The value of of `pgrst.inserted` comes in the response body as `{"inserted": "0", ...}`. I am thinking of doing it with adding 1 to the `pgrst.inserted` on insert and subtracting 1 on update. If in the end result is `> 0` then it is an insert otherwise an update. This way we are only updating the `GUC` and no extra columns are being added to the result.

**Comment by laurenceisla** [comment]
@taimoorzaeem The `returningF` function could be modified to handle it (to not show the body) so that it doesn't show in the body directly. But your new approach seems good too. I'd say go for it if it works best for you.
