### ISSUE TITLE
ERROR: total size of jsonb array elements exceeds the maximum of 268435455 bytes

### ISSUE THREAD

**Issue by revs-subdu** [PostgREST/postgrest#1072]
Hi, 

I am facing this issue when I try to update row (of type jsonb). 
Is there any to fix this issue and increase its size?

We are using Postgres 10.
Thanks

**Comment by steve-chavez** [comment]
This is more of a PostgreSQL limitation than a PostgREST issue, saw you submitted this in [psql-bugs](https://www.postgresql.org/message-id/151933308143.1365.3106046996770708952%40wrigleys.postgresql.org), did you manage to work around this?

**Comment by Qu4tro** [comment]
I think this one should be closed.

**Comment by steve-chavez** [comment]
Closing. Nothing for us to do but to accept the pg limitation.

**Comment by sameertwans** [comment]
Any updates about this limitation
