### ISSUE TITLE
Get binary data with image/* Accept header that is used by browsers for img tags

### ISSUE THREAD

**Issue by christiaanwesterbeek** [PostgREST/postgrest#1077]
Thanks to #802 we can get binary output using the `Accept: application/octet-stream` header. Works fine. I can fetch my binary, which is an image using Postman:
![image](https://user-images.githubusercontent.com/465989/36872853-fcf80110-1da6-11e8-9eaf-712fd0569581.png)

But now, I want to get that image in an [img tag](https://github.com/begriffs/postgrest/issues/506#issuecomment-216045702) like so:

`<img src="http://server:3000/images?select=binary_data&id=eq.f6deb9ff-839f-426c-baa0-0f05ebbab691">`

But the result is a 200 with an empty response. Probably because the Accept header is not `application/octet-stream`, but `image/webp,image/apng,image/*,*/*;q=0.8`

![image](https://user-images.githubusercontent.com/465989/36873034-92c7b9ce-1da7-11e8-9b47-9a6a8d34253b.png)
![image](https://user-images.githubusercontent.com/465989/36873069-a955ae80-1da7-11e8-8bd9-f338a214b5d9.png)

I know I can use  a base64 data img src and I know about the pros and cons. In need the url's as img src. Later I'll setup a CDN to cache the images from the api. But for now;

What can I do to get binary output from the api with the image/* header that the browser is currently sending along with the img request?

**Comment by begriffs** [comment]
Regardless of whether it's a good idea to serve images from the database, and many people advise against it, this does seem like a postgrest bug. Your Accept header included `*/*` so the server is free to make a response with `application/octet-stream`. The blank response is odd.

**Comment by christiaanwesterbeek** [comment]
It would indeed be a very bad idea to serve every image for every person from the database, but I'm going to put a CDN in front of it, so it'll be every image just once within the expiration period from the database and the rest from the CDN.

> Your Accept header included */* so the server is free to make a response with application/octet-stream.

Would be great if it could. I'm sorry to say I have zero experience in Haskell. Otherwise, I'd give it a go. I'd need to find some free time first to learn the language.

> The blank response is odd.

Just did a retest right after each other.
![image](https://user-images.githubusercontent.com/465989/36909949-b6749b10-1e3f-11e8-86fd-4699c98b4cfa.png)
![image](https://user-images.githubusercontent.com/465989/36909970-c2b59f3c-1e3f-11e8-855d-ed4cedd43500.png)
![image](https://user-images.githubusercontent.com/465989/36910000-d8eb6728-1e3f-11e8-9b02-e902ec9f574c.png)

**Comment by begriffs** [comment]
> I'm going to put a CDN in front of it

Oops, I missed that in the first message. Seems fine then. Stored procedures allow you to set a sql variable btw that allows you to set response headers, so you can set the caching the way you need to.

> Would be great if it could. I'm sorry to say I have zero experience in Haskell.

I'll look into it over the weekend, it may not be so hard to fix.

**Comment by christiaanwesterbeek** [comment]
> Stored procedures allow you to set a sql variable btw that allows you to set response headers

Excellent

> I'll look into it over the weekend, it may not be so hard to fix.

You rock!

Btw, I'm using Postgrest on Heroku deployed with the buildpack.

**Comment by christiaanwesterbeek** [comment]
I'm now using Cloudfront as a CDN in front of the image api that I configured to change the accept header.

So the img tag causes a request to Cloudfront with Accept: image/*, etc. Cloudfront than alters it to application/octet-stream and calls the api that serves the binary. So, I'm good now.

Functionally this is not a requirement for me anymore...

**Comment by begriffs** [comment]
Glad you found a way to integrate it with the CDN. I was thinking about this feature more and running into a difficulty for the general solution. If a client specifies `*/*` for the accept header, most probably they want json, but RPC calls also support csv and octet-stream. I'm not sure how the accept header the browser sends should be enough of a hint in your case, unless we interpret `image/*` as a synonym for `application/octet-stream`.

**Comment by witsch** [comment]
> I suppose the occurrence of any of these literal values `image/*`, `video/*` and `audio/*` would be safe to assume binary for. Those could indeed be a synonym for `application/octet-stream`.

Would this be an acceptable compromise?  If so, I'd try to come up with a pull request...

**Comment by steve-chavez** [comment]
@witsch Yes, I think that would be good. PR whenever you're ready.

**Comment by steve-chavez** [comment]
Solved by https://github.com/PostgREST/postgrest/pull/1349.

Now it's possible to do:
```
raw-media-types = ["image/apng"]
```
And a request with `Accept: image/apng` should respond with the wanted media type.

**Comment by koturwaraditi** [comment]
I am also facing the same issue .. how I need to set the img inside the img src tag ?
In my case I want to calling the Api inside the img tag i.e <img src="http://ip/images?filename=example.png>
which will resize the image file and return the resized image as a response 

I have tested my api it is returning the data in the form of byte but when I am calling inside the img tag it is give me the empty response.

Can some one help me how can I return the image as a response and display it in the img tag

**Comment by steve-chavez** [comment]
@koturwaraditi Check http://postgrest.org/en/v7.0.0/how-tos/providing-images-for-img.html
