### ISSUE TITLE
Add headers to all responses through "response.headers" GUC

### ISSUE THREAD

**Issue by dday1058** [PostgREST/postgrest#1088]
Our development  is trying to add the response headers per latest rest  documentations.
Our client tools see no addition to the headers.

 pkg info | grep rest
postgrest-0.4.4.0              RESTful API for PostgreSQL

FreeBSD 11.1

i.e 

I am suspicious about your test for version_num and version ( 9.6.8 vs  9.6 )   I am not familiar enough with haskell to claim that definitively but if this version test fails that would explain the lack of the header.

Our values:

 SELECT current_setting('server_version_num')::integer, current_setting('server_version')
ace_db-> ;
 current_setting | current_setting
-----------------+-----------------
           90608 | 9.6.8

The response.headers variable is being setup by the ALTER role set "response.header" = .....

 select coalesce(nullif(current_setting('response.headers', true), ''), '[]') :: Text ;
                           coalesce
---------------------------------------------------------------
 [{"Cache-Control": "public"}, {"Cache-Control": "max-age=2"}]

I am thinking the header is not sent because the version comparison is failing ? 

Any suggestions/Comments ?

Thanks 

Dave

**Comment by steve-chavez** [comment]
I think the problem is that you're expecting that the ROLE settings will apply when pgrst changes ROLEs(with `set local role`) but per pg [set role docs](https://www.postgresql.org/docs/9.6/static/sql-alterrole.html) and [alter role docs](https://www.postgresql.org/docs/9.6/static/sql-alterrole.html):
> SET ROLE does not process session variables as specified by the role's ALTER ROLE settings; this only happens during login

> This only happens at login time; executing SET ROLE or SET SESSION AUTHORIZATION does not cause new configuration values to be set

Try with a function like this one https://github.com/begriffs/postgrest/blob/master/test/fixtures/schema.sql#L1328-L1330 and see if now you get the headers.

**Comment by dday1058** [comment]
Thanks we will try that out.  I do note that both the initial role and the role switched to,  both had this ALTER role setup.  It was my observation that the setting persisted from the role doing the role switch.

**Comment by steve-chavez** [comment]
Maybe this example will help understanding the problem:
```sql
set custom.value = 1;
select current_setting('custom.value')::integer = 1; -- true
create role temp;
alter role temp set custom.value = 2;
begin;
set local role temp;
select current_setting('custom.value')::integer = 2; -- false, I expected this to be true
select current_setting('custom.value')::integer = 1; -- true
commit;
```

**Comment by dday1058** [comment]
Steve,

Thanks for your comments.
I did try your first linked suggestion and it worked successfully.  
Your second comment seems to show that the switch from the initial role to the temp role inherits the setting of the custom.value from the original role.   i.e setting a role is not the same as loging in. 
So as long as the starting role had this option set I would have expected  that definition to be found.
I have confirmed this with experiments.  So perhaps I had a cockpit error in testing my original alter role accomodation variation.

So yes 0.4.4.0 does honor the response.headers option. So we can close this issue.

However we are having trouble understanding how to use this method  in practice outside of the alter role set option concept.. towit:
After our rest client is logged in and has his jwt for subsequent interactions, are not there a pool of connections to Postgres.  What keeps the "response.headers" option  setting current and valid on the entire pool.   ( Hence the desire to use the setup via the role method ) for subsequent rest actions.

We are dealing with a problem with windows browsers where we need to include a caching header directive in the rest response as standard material. Calling a fx to set this as part of each rest interaction seems awkward.   What am i missing.


Thanks

**Comment by steve-chavez** [comment]
Actually I've realized that if we would add the `response.headers` to all pgrst responses(probably just GET responses) it could be possible to use the `pre-request` function to set the `response.headers` conditionally(with the help of the `request.*` settings), this could be worth discussing.

**Comment by dday1058** [comment]
The use of the "pre-request" option had occurred to me after your prior rpc restriction note.. I suggested it to the developer,  I have not heard any feedback with regards to that experiment.  Our project  uses GET and POST techniques for table and view access, so I am curious to your GET option restriction.

Setting response.headers option based upon a claim in guc request.* options would certainly be nice from our perspective.   I am probably not the right person to discuss that it solves a larger/general REST problem correctly.  ( I'm the postgress guy stretching my skillset. )

**Comment by steve-chavez** [comment]
To do this, we'd have to make getting the GUC headers independent from the callProc statement. Right now this logic is in:
https://github.com/PostgREST/postgrest/blob/eebe319bfda43a55d904b366c2897a56aba898bf/src/PostgREST/Statements.hs#L157-L160

This logic could be added to each statement in `Statement.hs` or perhaps it also could be an independent statement(the cost of getting `current_setting` and decoding it seems negligible) for every request. This would be done before doing the main request statement(SELECT, INSERT, etc).

Tests would have to validate that the headers are indeed added for GET/HEAD/POST/PUT/PATCH.

**Comment by ruslantalpa** [comment]
Independent statement is bad because it’s a roundtrip to the db for nothing in most cases, i.e.  3-8ms wasted on every request for nothing. It needs to happen in the same query as the main select (the way it works now for RPC).

**Comment by steve-chavez** [comment]
@ruslantalpa Yeah, I agree. Now that I've noticed it'll be actually simpler to implement that way too. Just have a SqlFragment for getting the response.headers and add that for the other two statements(createWrite and createRead).

**Comment by steve-chavez** [comment]
I'm mostly focusing on refactoring right now. I want to implement #1106 but first I want to make sure I'm getting all the code paths right. So I'll leave this issue for anyone that'd like to solve it.

**Comment by Dansvidania** [comment]
I'd love to help on this. I'll try to study the code and see if my understanding is sufficient to try the patch

**Comment by steve-chavez** [comment]
@Dansvidania Cool! Just ping me If you have any questions.

**Comment by Dansvidania** [comment]
Hello @steve-chavez I have not had much time to work on this since. I am currently trying to figure out what would make good test cases for the change, and I hope I will be able to open a WIP pull request soon. Sorry for taking so long.

**Comment by steve-chavez** [comment]
Hey @Dansvidania, no problem regarding time.

Maybe a good test would be something like this [logic](https://github.com/PostgREST/postgrest/issues/1088#issuecomment-378639127) I commented previously, but done in a `pre-request` function. You could just remove the conditional and then test that all HTTP methods include the `Cache-Control` header. Testing a GET would be good enough for a WIP PR.

**Comment by steve-chavez** [comment]
@Dansvidania Are you still working on this? Can I help?

Adding this feature would solve some other issues we currently have. It'd be great to solve these for the new version.

**Comment by Dansvidania** [comment]
Hi @steve-chavez sorry for not letting you know but I have not had time to work on this because of some, still ongoing, issues.

If it is needed in the short term I do not think I can complete it.

**Comment by yevon** [comment]
> I note that when an exception happens, or you execute `RAISE EXCEPTION` (e.g. in an insert trigger function) - then the headers (e.g. `Location`) are not present in the HTTP response, even if you had explicitly set them in the `response.headers`. Is this expected?

I'm having exactly this problem. If you use the prerequest function for security validation, headers are not persisted after an exception.

**Comment by mdr1384** [comment]
> I'm having exactly this problem. If you use the prerequest function for security validation, headers are not persisted after an exception. How did you solve this @mdr1384 ?

@yevon - I didn't. It is still AFAIK an open issue, buried in a heap of other issues (unrelated to postgrest).

**Comment by yevon** [comment]
> > I'm having exactly this problem. If you use the prerequest function for security validation, headers are not persisted after an exception. How did you solve this @mdr1384 ?
> 
> @yevon - I didn't. It is still AFAIK an open issue, buried in a heap of other issues (unrelated to postgrest).

Thanks, I just opened an issue for being able to fully control http responses in case of an error: http code, body + headers after discussing this issue: https://github.com/PostgREST/postgrest/issues/2492
