### ISSUE TITLE
How to insert an entry by specifying not all attributes ?

### ISSUE THREAD

**Issue by Vladimir-Golub** [PostgREST/postgrest#1093]
How to insert a record with id (auto increment) PostgREST?
I have a function
```
        axios.post('http://localhost:3000/unitsmeasure', {
            id: 20,
            name: 'name'
        })
        .then(function (response) {
            console.log(response);
        })
        .catch(function (error) {
            console.log(error);
        });
```
It inserts an entry in the table. Its works.

But when I do not specify the id. It does not work. (id serial PRIMARY KEY).
```
        axios.post('http://localhost:3000/unitsmeasure', {
            name: 'name'
        })
        .then(function (response) {
            console.log(response);
        })
        .catch(function (error) {
            console.log(error);
        });
```
This does not work
`POST http://localhost:3000/unitsmeasure 401 (Unauthorized)`

SQL Code Table
```
CREATE TABLE "unitsmeasure" (
  "id" serial PRIMARY KEY,
  "name" varchar(100)
)
```

**Comment by Vladimir-Golub** [comment]
Create function 
```
	CREATE OR REPLACE FUNCTION views.insertname(fname varchar(20)) RETURNS VOID AS
$$
BEGIN
    INSERT INTO views.unitsmeasure (name) VALUES (fname);
END
$$
  LANGUAGE 'plpgsql';
```
How to create a query?

`http://localhost:3000/rpc/insertname` ?

**Comment by steve-chavez** [comment]
What's the error message on `POST http://localhost:3000/unitsmeasure 401 (Unauthorized)`?

Maybe the SEQUENCE privilege is missing, perhaps you need to run `GRANT USAGE on SEQUENCE unitsmeasure_id_seq TO $your_anonymous_role`.

There are docs on stored procedures and how to call them here https://postgrest.com/en/v4.4/api.html#stored-procedures.

**Comment by steve-chavez** [comment]
@Vladimir-Golub  Did the suggestion worked for you?

**Comment by steve-chavez** [comment]
Considering this resolved. Also for getting acquainted with PostgREST I suggest first using  `curl` or any http cli/gui, after that you can use your preferred lib with more confidence.
