### ISSUE TITLE
Requests with invalid JWT should not touch database

### ISSUE THREAD

**Issue by gavrilyak** [PostgREST/postgrest#1094]
### Environment

* Version of postgrest:
4.4
* Operating system:
Ubuntu 16.04
* Running in docker:
  * [x] yes
  * [ ] no

### Description of issue
When processing request with expired JWT postgrest connects to database and executes
 ```
BEGIN ISOLATION LEVEL READ COMMITTED READ ONLY
COMMIT
```
Expected behavior: postgrest should not connect to database at all

### Support level

In addition to free community support, are you interested in priority consulting time from [begriffs](https://begriffs.com/)?

* [ ] yes
* [x] no

**Comment by steve-chavez** [comment]
I'm now proposing we should rely on pg logging for auditing a particular PostgREST instance. See my comment on https://github.com/PostgREST/postgrest/issues/540#issuecomment-541387371.

So for this issue, how about if we instead [RAISE](https://www.postgresql.org/docs/12/plpgsql-errors-and-messages.html) a custom error message(maybe with a special code too) to PostgreSQL. Using `log_line_prefix/application_name`, as mentioned in https://github.com/PostgREST/postgrest/issues/540#issuecomment-540649767, would make this error ignorable or greppable and wouldn't get in the way of other applications using PG.

**Comment by steve-chavez** [comment]
Since every expired JWT could potentially touch the db, this carries a risk of DDoS. So this should definitely be fixed.
