### ISSUE TITLE
Add array index support to jsonb

### ISSUE THREAD

**Issue by PierreR** [PostgREST/postgrest#1099]
### Environment

* Version of postgrest: v0.4.4.0
* Operating system: RHEL 7.4
* Running in docker:
  * [ ] yes
  * [x] no

### Description of issue

I have this output where `ret` is of type `jsonb`:

http://nixpaste.lbr.uno/BJw5QeGX?json

In the example, I would like to be able to filter the output from all `ret` records that have a 'fun' equal to `
saltutils.find_job`.

### Support level

In addition to free community support, are you interested in priority consulting time from [begriffs](https://begriffs.com/)?

* [ ] yes
* [x] no

**Comment by PierreR** [comment]
Here is a short example of output limited to 2 records:
```
[
    {
        "jid": "20180425103258799624",
        "user": "pradermecker",
        "target": "[\"foreman.dev.srv.cirb.lan\"]",
        "ret": [
            {
                "id": "foreman.dev.srv.cirb.lan",
                "cmd": "_return",
                "fun": "saltutil.find_job",
                "jid": "20180425103258799624",
                "_stamp": "2018-04-25T08:33:05.086858",
                "return": {},
                "retcode": 0,
                "success": true,
                "fun_args": [
                    "20180425103253617442"
                ]
            }
        ]
    },
    {
        "jid": "20180425103253617442",
        "user": "pradermecker",
        "target": "foreman.dev.srv.cirb.lan",
        "ret": [
            {
                "id": "foreman.dev.srv.cirb.lan",
                "cmd": "_return",
                "fun": "pillar.item",
                "jid": "20180425103253617442",
                "_stamp": "2018-04-25T08:33:05.057591",
                "return": {
                    "puppet_server": "puppet3.prd.srv.cirb.lan"
                },
                "retcode": 0,
                "success": true,
                "fun_args": [
                    "puppet_server",
                    "delimiter=/"
                ]
            }
        ]
    }
]
```

**Comment by steve-chavez** [comment]
@PierreR Check #1128, see if you can [build the PR from source](https://postgrest.org/en/v5.0/install.html#build-from-source) and confirm it's good enough for your use case.

**Comment by PierreR** [comment]
@steve-chavez Thanks

I am trying to build on nixos and the two pain points are:
- configurator-ng-0.0.0.1
- hasql-transaction-0.5.2

FWIW the test suite of `critbit` is failing but it is easy enough to build without checking.

Is there any reason why the low version of  `hasql-transaction` is required ?

**Comment by steve-chavez** [comment]
@PierreR I build/exec on NixOS with:
```bash
stack build --nix --no-nix-pure --install-ghc && \
stack exec --nix --no-nix-pure postgrest config
```
Not ideal, but should work, I haven't gotten around to fixing the dependencies yet.

**Comment by PierreR** [comment]
@steve-chavez Given that `http://localhost:3000/test1?id=eq.2&select=info` return http://nixpaste.lbr.uno/BJw5QeGX?json, how can I get all the rows where `fun` is not "saltutil.find_job" ?

**Comment by PierreR** [comment]
Just deleted the above examples which were not good. I will try this again tomorrow.

**Comment by PierreR** [comment]
@steve-chavez it works nicely with test data. Thanks again.
Little question. In this call `http://localhost:3000/test1?info->0->>fun=neq.saltutil.find_job` the parser seems to be ok with the `.` between saltutil and find_job. Is that always the case ?

**Comment by steve-chavez** [comment]
Yes, filters accept any char after the dot `.`, only when using `and/or` you'd have to quote a value like that, e.g. `/test1?or=(info->0->>fun.neq."saltutil.find_job")`.

**Comment by steve-chavez** [comment]
@PierreR The feature is now merged in master, also added docs for this in http://postgrest.org/en/latest/api.html#vertical-filtering-columns (`latest` docs represent master not a released version). Consider supporting PostgREST on [Patreon](https://www.patreon.com/postgrest) so I can keep working on enhancements.
