### ISSUE TITLE
Feature request: Customizable OpenAPI title and description.

### ISSUE THREAD

**Issue by respondcreate** [PostgREST/postgrest#1100]
First off: thanks so much for open sourcing this great project! After taking a look through the docs and the code, it appears that there's no way to customize the OpenAPI title ([as defined here](https://github.com/begriffs/postgrest/blob/f9e770b583a4bea019e2618a1285c72597bc1c6e/src/PostgREST/OpenAPI.hs#L259)) or description ([as defined here](https://github.com/begriffs/postgrest/blob/f9e770b583a4bea019e2618a1285c72597bc1c6e/src/PostgREST/OpenAPI.hs#L260)). Ideally this would be done via an environment variables (for docker) or by overriding values in the .conf file. Example:

.conf:
```
openapi-title = "FooBar API"
openapi-description = "A RESTful API that serves FooBar data."
```

env variables:
```
# postgrest/docker/postgrest.conf
openapi-title = "$(PGRST_OPENAPI_TITLE)"
openapi-description = "$(PGRST_OPENAPI_DESCRIPTION)"
```

I don't have any experiencing writing Haskell but would be willing to scaffold in the above into the [docker .conf file](https://github.com/begriffs/postgrest/blob/3ccae4bb8ba52d27fbf18a4d7b6da721f07100ea/docker/postgrest.conf) if someone else could help me properly integrate them into [the config parser](https://github.com/begriffs/postgrest/blob/108f3cd651a448fad065faf81a2090cee8a8d9fb/src/PostgREST/Config.hs#L126). Once integrated there it should be pretty straight-forward integrating those new configs into [the OpenAPI spec here](https://github.com/begriffs/postgrest/blob/f9e770b583a4bea019e2618a1285c72597bc1c6e/src/PostgREST/OpenAPI.hs#L257).

Is my proposed change something you'd be willing to add into this stellar project?

**Comment by steve-chavez** [comment]
It'd be a reasonable addition, there's already a [server-proxy-uri config](https://github.com/begriffs/postgrest/blob/108f3cd651a448fad065faf81a2090cee8a8d9fb/src/PostgREST/Config.hs#L130) that's also related to OpenAPI, maybe it makes sense to add the `openapi-` prefix to that as well and deprecate the previous key.

I think it should be straightforward to add what you ask, follow the [encodeOpenAPI](https://github.com/begriffs/postgrest/blob/108f3cd651a448fad065faf81a2090cee8a8d9fb/src/PostgREST/App.hs#L317) function and see how it passes the [configProxyUri](https://github.com/begriffs/postgrest/blob/108f3cd651a448fad065faf81a2090cee8a8d9fb/src/PostgREST/Config.hs#L67) parameter, also check the [StructureSpec](https://github.com/begriffs/postgrest/blob/108f3cd651a448fad065faf81a2090cee8a8d9fb/test/Feature/StructureSpec.hs) to see how to include tests.

There are instructions on how to build and run the test suite in https://postgrest.com/en/v4.4/install.html#build-from-source.

**Comment by respondcreate** [comment]
Great! Thanks so much for the pointers, @steve-chavez !

**Comment by steve-chavez** [comment]
My bad, I forgot the description part was already implemented(in #885), you just need to do: 
```sql
comment on schema api is $$
FooBar API

A RESTful API that serves FooBar data
$$;
```
This will be included in the `description` part of the OpenAPI output, no need for new config values.
Now, the `title` part is still hardcoded to `PostgREST API`, what you can do is to split the comment by the newline, the same way it was done in #931 for table comments.

**Comment by SmallhillCZ** [comment]
+1

It looks really super simple to implement, but haskell is for me like wtf :(

**Comment by Keziake** [comment]
Can you please provide a way to override the hardcoded OpenAPI Title ?

**Comment by steve-chavez** [comment]
Done in https://github.com/PostgREST/postgrest/pull/2624
