### ISSUE TITLE
Feature request: option to change delimiter character for CSV output

### ISSUE THREAD

**Issue by nextstopsun** [PostgREST/postgrest#1102]
Now you can only output CSV as a comma-separated file, but in many cases semicolons, tabs and other characters are needed.
I would be great to have such an option.

**Comment by steve-chavez** [comment]
There's a media type for tabs, [text/tab-separated-values](https://www.iana.org/assignments/media-types/text/tab-separated-values), however there's no media type for other delimiters like semicolons, pipes and colons.

We could make a vendor media type for [delimiter-separated values](https://en.wikipedia.org/wiki/Delimiter-separated_values), with a parameter for specifying the delimiter, was thinking of `application/vnd.pgrst.dsv; delimiter=":";`, according to [RFC 2045](https://www.ietf.org/rfc/rfc2045.txt) we would have to quote the delimiters, not sure for now if we can have a `delimiter="\t"` for tabs, if we cannot, then maybe we'd have to support both the official tsv and vendored dsv media types.

**Comment by steve-chavez** [comment]
Better late than never: https://github.com/PostgREST/pg_csv/pull/2
