### ISSUE TITLE
test stored procedure not working as expected

### ISSUE THREAD

**Issue by glw** [PostgREST/postgrest#1107]
### Environment

* Version of postgrest: 0.4.2
* Operating system: Ubuntu 16.04
* Running in docker:
  * [ ] yes
  * [X] no

### Description of issue
Just testing a function on my local machine. I tried creating the test stored procedure as in the docs ```add_them``` ( https://postgrest.org/en/stable/api.html#stored-procedures ). Im getting an error instead of the suggested output.

```
$ curl -X POST \http://localhost:3000/rpc/add_them?a=1&b=2
```
output
```
{"details":"unexpected \"1\" expecting \"not\" or operator (eq, gt, ...)","message":"\"failed to parse filter (1)\" (line 1, column 1)"}
```

```
$ curl -X POST \http://localhost:3000/rpc/add_them
```
output
```
{"hint":"No function matches the given name and argument types. You might need to add explicit type casts.","details":null,"code":"42883","message":"function public.add_them() does not exist"}
```

**Comment by michelp** [comment]
PostgREST vertical filtering options require an operator, so `?a=eq.1&b=eq.2` is the right syntax.  There are many operators

https://postgrest.org/en/v4.4/api.html#horizontal-filtering-rows

**Comment by steve-chavez** [comment]
Also, specifying the arguments in the querystring as `?key=value` are only available for GET, for POST they are treated like filters.

**Comment by michelp** [comment]
Ah good point, my reading comprehension skills are obviously poor today. @glw, it works if you drop the `-X POST` as @steve-chavez pointed out.

**Comment by glw** [comment]
Hi guys thanks for the help.

Unfortunately, Im getting the same thing. I changed the command to:
```
$ curl http://localhost:3000/rpc/add_them
```

**Comment by michelp** [comment]
I run into this myself often, bash will interpret the '&' to run the curl as a background process.

**Comment by glw** [comment]
@michelp you're probably right, because all the other non-function requests I made went thru fine without quotes. 
@steve-chavez Im using Xfce

**Comment by steve-chavez** [comment]
Added an issue on the docs, I'll see how to include this as a note.

**Comment by ppKrauss** [comment]
Hi, I installed a fresh PostgREST and not working (!), using copy/paste of [the example](http://postgrest.org/en/v5.2/api.html#stored-procedures), but trying any of these requests fails:

1. `curl "http://osm.codes/sql/rpc/add_them?a=1&b=2"`
2. `curl --header "Content-Type: application/json"  --request POST --data '{"a": 1, "b": 2}' http://osm.codes/sql/rpc/add_them`
