### ISSUE TITLE
Hackage should use canonical repository URLs

### ISSUE THREAD

**Issue by ilovezfs** [PostgREST/postgrest#1108]
https://hackage.haskell.org/package/postgrest

says

homepage https://github.com/begriffs/postgrest
head: `git clone git://github.com/begriffs/postgrest.git`

But should be

homepage https://postgrest.org/
head `git clone https://github.com/PostgREST/postgrest.git` (also note https)

**Comment by steve-chavez** [comment]
Added the corrections in https://github.com/PostgREST/postgrest/pull/1177. Hackage will show these on the next release.
