### ISSUE TITLE
singular behavior inconsistent with v0.5.0.0

### ISSUE THREAD

**Issue by kaiwu** [PostgREST/postgrest#1112]
### Environment

* Version of postgrest: postgrest/postgrest:v0.5.0.0
* Operating system: docker-18.03.1-ce
* Running in docker:
  * [x] yes
  * [ ] no

### Description of issue

[doc](https://postgrest.org/en/v4.4/api.html#singular-or-plural) regarding `singular` become invalid
with the latest release

>This can be inconvenient for client code. 
>To return the first result as an object unenclosed by an array, 
>specify vnd.pgrst.object as part of the Accept header
>
>When a singular response is requested but no entries are found, the server responds with an 
>error message and 406 Not Acceptable status code rather than the usual empty array and 200 
> status:

### Actual

HTTP status 200 and the empty array was returned instead of 406, this behavior is not mentioned in the release note either

**Comment by steve-chavez** [comment]
I've tried the latest release and the singular feature is working as usual, the test suite is also green.

Include how you're making the request(say with `curl` or `httpie`) and the DDL for the table, view or function that you're targeting. That would allow me to reproduce the issue.

**Comment by kaiwu** [comment]
right, it was totally my fault, the `Accept` header didn't go through nginx, which the other day i added `proxy_pass_request_headers off;` to turn off some gzip side effects, so postgrest was unaware of this header.

i am sorry to waste your time
