### ISSUE TITLE
Error when UPSERT records with capitals in primary key field

### ISSUE THREAD

**Issue by wweultjes** [PostgREST/postgrest#1113]
### Environment

* 0.5.0.0:
* Linux:
* Running in docker:
  * [ X] yes
  * [ ] no

### Description of issue
I use the UPSERT method to POST a bulk of records. The following error message is returned:
"hint": "Perhaps you meant to reference the column \"dUnitTest.idUnitTest\" or the column \"*SELECT*.idUnitTest\".",
    "details": null,
    "code": "42703",
    "message": "column \"idunittest\" does not exist"

Our table looks like:
Table : dUnitTest
Fields: idUnitTest (PK)
           nameUnitTest

posted body:
[{
  "idUnitTest": 1,
  "nameUnitTest": "name of unittest 1"
}
,{
  "idUnitTest": 2,
  "nameUnitTest": "name of unittest 2"
})

using a table without capitals in de field with the primary doesn't throw an error.

It seems capitals in definitions are not handled correctly.

(Expected behavior vs actual behavior.)
I expect the same behavior with and without capitals in the primary key field.

**Comment by steve-chavez** [comment]
Reproduced:
```sql
create table "UnitTest"(
  "idUnitTest" integer primary key,
  "nameUnitTest" text
);
insert into "UnitTest" values (1, 'unit test 1'), (2, 'unit test 2');
```

```bash
curl "localhost:3000/UnitTest" -H "Content-Type: application/json" \
-H "Prefer: resolution=merge-duplicates" \
-H "Prefer: return=representation" \
-d @- << EOF
[
  {
  "idUnitTest": 1,
  "nameUnitTest": "name of unittest 1"
  },
  {
  "idUnitTest": 2,
  "nameUnitTest": "name of unittest 2"
  }
]
EOF

{"hint":"Perhaps you meant to reference the column \"UnitTest.idUnitTest\" or the column \"*SELECT*.idUnitTest\".","details":null,"code":"42703","message":"column \"idunittest\" does not exist"}
```

**Comment by steve-chavez** [comment]
Check #1114, see if you can fetch the PR and [build from source](https://postgrest.org/en/v4.4/install.html#build-from-source) to make sure this is fixed.

**Comment by steve-chavez** [comment]
@wweultjes Glad it's working ok, however I'd like to leave the issue open until I merge the fix on master branch(just in case another user hits the same problem), want to give the PR one last review before merging.
