### ISSUE TITLE
how can i use edbwrap  function or spi function?

### ISSUE THREAD

**Issue by mpls00** [PostgREST/postgrest#1116]
PostgreSQL version: EDB 10 or PG 10
* PostgREST version: 0.5
* Operating system: centos

code 1 is ::
CREATE OR REPLACE FUNCTION edbwrap_1(str text) RETURNS text AS $$
  BEGIN
    RETURN a1 || || now();
  END;
$$ LANGUAGE plpgsql;

http://localhost:3000/rpc/edbwrap_1?str=hello
return ok;

code 2 is ::
CREATE OR REPLACE FUNCTION edbwrap_2(str text) RETURNS text AS $$
  BEGIN
    RETURN a1 || || now();
  END;
$$ LANGUAGE plpgsql;

it is translated edbwrap format  but  it returns error.
error code({"hint":"No function matches the given name and argument types. You might need to add explicit type casts.","details":null,"code":"42883","message":"function enterprisedb.edbwrap_2() does not exist"})

code 2 format:
$__EDBwrapped__$
UTF8
d3VAPu7W9fNgrLjiCKtXqQLdLwfhOsHP/bJrqLlICTTGlqtTJCZucFb9pmEF69RcEbMqiGt0e/+s
PoBquPe9mV9Fh3BXW0U7YkAYhteR8GlCW6Hypj+Gu4c=
$__EDBwrapped__$
but  function edbwrap_2 is executed  successful in edb;
SPI function have the same question. 

edbwrap description ：
https://www.enterprisedb.com/docs/en/9.5/eeguide/EDB_Postgres_Enterprise_Guide.1.077.html

**Comment by steve-chavez** [comment]
The error when calling `edbwrap_2` might be due to a stale schema cache(PostgREST uses this to differentiate scalars from row functions), restart PostgREST and it should work, also see https://postgrest.org/en/v4.4/admin.html#schema-reloading for other options besides restarting.

**Comment by steve-chavez** [comment]
SPI functions should work fine, bear in mind that you have to name the functions arguments to be able to call them with PostgREST though, like:
```sql
create function execq(str text, num integer) returns integer as './execq.so' language c;
```

**Comment by mpls00** [comment]
thank steve-chavez

restart PostgREST and all is ok!!
