### ISSUE TITLE
Docker image compatible with ARM: is that possible?

### ISSUE THREAD

**Issue by cuducos** [PostgREST/postgrest#1117]
### Environment

* PostgreSQL version: `postgres:10.4`
* PostgREST version: `v0.5.0.0`
* Operating system: Raspbian GNU/Linux 9 (stretch)

<details>

```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

</details>

### Description of issue

Probably related to #846, but I would like to ask about the possibility of a Docker image ready for ARM processors. So far I think the PostgREST Docker image is not compatible:

```
pi@raspberrypi:~ $ docker pull postgrest/postgrest
Using default tag: latest
latest: Pulling from postgrest/postgrest
Digest: sha256:8c40ba14f6400a51be1ed78f83f472132a96ab955fe627ca385286378dd3f88b
Status: Image is up to date for postgrest/postgrest:latest
pi@raspberrypi:~ $ docker run postgrest/postgrest


standard_init_linux.go:190: exec user process caused "exec format error"
```

Also I see only `amd64` in the image inspector:

```
pi@raspberrypi:~ $ docker inspect postgrest/postgrest | grep Architecture
        "Architecture": "amd64",
```

Is this possible and in the radar for short term releases? Is there someway I could help in this particular issue?

**Comment by steve-chavez** [comment]
I've uploaded a PostgREST binary for ARMv7 here https://github.com/steve-chavez/postgrest/releases/download/v0.5.0.0/postgrest-v0.5.0.0-debian-armv7.tar.xz, maybe you can test it so I can later see how to create a docker image for that and make it an official release.

If you'd like to you can also build your own docker image with that binary by following this https://github.com/PostgREST/postgrest/blob/master/docker/Dockerfile.

Let me know how it goes, I don't own an ARM device so what I did was to use qemu and docker to build the binary, basically:

```bash
docker run --rm --privileged multiarch/qemu-user-static:register
docker run -it --rm multiarch/debian-debootstrap:armhf-stretch
```

**Comment by nicolastarzia** [comment]
Hey @steve-chavez,

Didn't work for me, I tried to build docker image with that binary, but, didn't work, can you help me?

I can see `arm` in the image inspector:
```
pi@raspberrypi:~/ $ docker inspect 6958 | grep Architecture
        "Architecture": "arm",
```

But my container log is:
```
pi@raspberrypi:~/ $ docker logs 6366
   /bin/sh: 1: exec: postgrest: not found
   /bin/sh: 1: exec: postgrest: not found
```
Maybe the postgrest it's differente architecture?

I changed this line in Dockerfile:
```
    curl -SLO https://github.com/steve-chavez/postgrest/releases/download/v0.5.0.0/postgrest-v0.5.0.0-debian-armv7.tar.xz && \
```

**Comment by steve-chavez** [comment]
@nicolastarzia Maybe you're missing a change to this line https://github.com/PostgREST/postgrest/blob/f6c1ff810e92321f2cd522058d5c6fd74cb64226/docker/Dockerfile#L17.

It should be like `tar -xJvf postgrest-v0.5.0.0-debian-armv7.tar.xz`.

The binary I built has this `file` output:
```
ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=6a252f9ae1e4c1025e70f773f47d1607ff68ef1d, stripped
```

**Comment by nicolastarzia** [comment]
Sorry, but I changed this line too.. 

Now I running docker build again, and send the log!

**Comment by steve-chavez** [comment]
@nicolastarzia Before creating the docker image would be better to see if the binary is working in your rpi, see if you can run `./postgrest`(it should show a help output) only requirement should be to `apt-get install libpq-dev`.

**Comment by cuducos** [comment]
Just a quick update:

I opened the issue a couple of days ago and since then I'm being idle because my memory card is corrupted so I cannot test it myself.

I already ordered a new one more than a week ago, but then a truck drivers strike has been delaying the delivery.

Many thanks @steve-chavez and @nicolastarzia for the inputs, I'm gonna get back to you as soon as my Raspberry Pi gets a new memory card : )

**Comment by marcellodgl** [comment]
Compiled version on Raspberry Jessie

[postgrest.tar.xz.zip](https://github.com/PostgREST/postgrest/files/2228431/postgrest.tar.xz.zip)

Marcello

**Comment by steve-chavez** [comment]
Thanks @marcellodgl, want to add that this binary(armv7) corresponds to the latest version(v5.0.0) on https://github.com/PostgREST/postgrest/commit/fa1e92fdf2d74d083eb4242de5051b0274799a17, and also that we confirmed it's working ok on Marcello's rpi, unlike my previously posted binary which presented some errors, so prefer this latest binary.

**Comment by pedroetb** [comment]
> Compiled version on Raspberry Jessie
> 
> [postgrest.tar.xz.zip](https://github.com/PostgREST/postgrest/files/2228431/postgrest.tar.xz.zip)
> 
> Marcello

I loaded your binary in my custom postgrest Dockerfile (same as original, but without installing postgrest) and I can confirm it is working on a RPI3.

**Comment by samkhawase** [comment]
@steve-chavez  Is there a new version of the RaspberryPi/Arm32 build? Could you please share your working recipe?
I tried building the latest postgREST branch using `arm32v7/debian` docker image but it failed with the following error:

```
--  While building package haskell-src-exts-1.18.2 using:
      /root/.stack/setup-exe-cache/arm-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/arm-linux/Cabal-1.24.2.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /app/postgrest/.stack-work/logs/haskell-src-exts-1.18.2.log

    Configuring haskell-src-exts-1.18.2...
    Building haskell-src-exts-1.18.2...
    Preprocessing library haskell-src-exts-1.18.2...
    [ 1 of 17] Compiling Language.Haskell.Exts.Syntax ( src/Language/Haskell/Exts/Syntax.hs, .stack-work/dist/arm-linux/Cabal-1.24.2.0/build/Language/Haskell/Exts/Syntax.o )
    `opt' failed in phase `LLVM Optimiser'. (Exit code: -9)
```

**Comment by samkhawase** [comment]
It takes ~3 hours to get to the error I posted above.  Here's the complete log: 
[docker.log](https://github.com/PostgREST/postgrest/files/3128250/docker.log)

I'm creating a base `arm32v7/debian` image with required dependencies using this 

[base Dockerfile](https://github.com/PostgREST/postgrest/files/3128253/Dockerfile.txt)

The final Dockerfile used to build postgREST is:
[Dockerfile](https://github.com/PostgREST/postgrest/files/3128257/Dockerfile.txt)

**Comment by steve-chavez** [comment]
@samkhawase No new version from my part.

> It takes ~3 hours to get to the error I posted above

Yeah, building through docker takes that long. I really don't want to go through that again.

That being said, I'm interested in offering official ARM binaries, but it'd be better to produce them natively.
I've been looking at https://cloud.drone.io, we could integrate that CI and produce the binaries on each release.

**Comment by samkhawase** [comment]
@steve-chavez Well that's a bummer ☹️ I'm not well versed with the Haskell/Stack build system, so I'm not sure how can I figure it out. It would be interesting to know if you can levarage https://cloud.drone.io to create Arm32/Arm64 binaries.

**Comment by hughjfchen** [comment]
Ok. So I bought an ARMv8 instance from scaleway, setup a build environment based on nix, build the postgrest 5.2.2 for aarch64 and push to my docker hub repository. You can pull it with following command:
`docker pull hughjfchen/hughjfchen:postgrest-aarch64-5.2.0`

**Comment by steve-chavez** [comment]
@hughjfchen Cool!

I think we should aim to integrate a Nix CI. Ideally we'd also offer static binaries for aarch32/64.

**Comment by fenggy** [comment]
Is there a solution now?

**Comment by samkhawase** [comment]
@hughjfchen Could you please share the build details? 
I have a scaleway Arm64 server and I could setup a CI build on it.

**Comment by hughjfchen** [comment]
> @hughjfchen Could you please share the build details?
> I have a scaleway Arm64 server and I could setup a CI build on it.

I've been building the postgrest docker images for aarch64 recently. You can use it by pulling the images from my docker.io repos:
`docker pull hughjfchen/hughjfchen:postgrest-aarch64-5.2.0`
or:
`docker pull hughjfchen/hughjfchen:postgrest-aarch64-6.0.2`

If you want to play around with my build process, I have a github repos which builds the above images with my home-made shell-script-based CI/CD framework. You can build on your scaleway arm64 instance with following steps:

1. make sure you have an account which can use `sudo` without password
2. clone my github repos with the command: `git clone https://github.com/hughjfchen/postgrest-docker`
3.build the images with one of the following commands:
`postgrest-docker/postgrest-6.0/DevOps/scaleway/test/cb.sh`, or
`postgrest-docker/postgrest-5.2/DevOps/scaleway/test/cb.sh`
4.once finished, you can find the nix derivation result under the `postgrest-docker/postgrest-6.0` or `postgrest-docker/postgrest-5.2` directory respectively.

**Comment by samkhawase** [comment]
> > @hughjfchen Could you please share the build details?
> > I have a scaleway Arm64 server and I could setup a CI build on it.
> 
> I've been building the postgrest docker images for aarch64 recently. You can use it by pulling the images from my docker.io repos:
> `docker pull hughjfchen/hughjfchen:postgrest-aarch64-5.2.0`
> or:
> `docker pull hughjfchen/hughjfchen:postgrest-aarch64-6.0.2`
> 
> If you want to play around with my build process, I have a github repos which builds the above images with my home-made shell-script-based CI/CD framework. You can build on your scaleway arm64 instance with following steps:
> 
>     1. make sure you have an account which can use `sudo` without password
> 
>     2. clone my github repos with the command: `git clone https://github.com/hughjfchen/postgrest-docker`
>        3.build the images with one of the following commands:
>        `postgrest-docker/postgrest-6.0/DevOps/scaleway/test/cb.sh`, or
>        `postgrest-docker/postgrest-5.2/DevOps/scaleway/test/cb.sh`
>        4.once finished, you can find the nix derivation result under the `postgrest-docker/postgrest-6.0` or `postgrest-docker/postgrest-5.2` directory respectively.

@steve-chavez Can we setup a CI, and add the ARM64 builds to the official releases?

**Comment by steve-chavez** [comment]
@samkhawase Sure, if you build an arm64 binary in your CI and share it here I could add it to https://github.com/PostgREST/postgrest/releases.

Is that what you had in mind?

**Comment by hughjfchen** [comment]
@steve-chavez I can provide the binary for arm64, however, since I build the binary with nix, it will depend on some nix derivations which need to be installed on the target environment. Is this acceptable? If yes, I can tar the binary and its dependencies up and you can add it to the release.

**Comment by steve-chavez** [comment]
@hughjfchen Could you make it a statically linked binary? You could try modifying this [nix expression for postgrest 6.0.1](https://github.com/clojurians-org/my-env/blob/master/nix.conf/postgrest-6.0.1/default.nix) which was shared in https://github.com/PostgREST/postgrest/issues/1295. That way it would run in any linux distro(I think most users aren't running nix).

**Comment by fenggy** [comment]
If there's an executable, that's great

**Comment by hughjfchen** [comment]
> @hughjfchen Could you make it a statically linked binary? You could try modifying this [nix expression for postgrest 6.0.1](https://github.com/clojurians-org/my-env/blob/master/nix.conf/postgrest-6.0.1/default.nix) which was shared in #1295. That way it would run in any linux distro(I think most users aren't running nix).

@steve-chavez , I've been trying to build postgrest statically with the nix expression you linked, however, I'd stuck at the following error:
`
building '/nix/store/5i4lphsaikc4mjzaklcnwhv033l6cyjb-bootstrap-tools.tar.xz.drv'...
warning: unable to download 'https://wdtz.org/files/wjzsj9cmdkc70f78yh072483x8656nci-stdenv-bootstrap-tools-aarch64-unknown-linux-musl/on-server/bootstrap-tools.tar.xz': SSL connect error (35); retrying in 257 ms
warning: unable to download 'https://wdtz.org/files/wjzsj9cmdkc70f78yh072483x8656nci-stdenv-bootstrap-tools-aarch64-unknown-linux-musl/on-server/bootstrap-tools.tar.xz': SSL connect error (35); retrying in 649 ms
warning: unable to download 'https://wdtz.org/files/wjzsj9cmdkc70f78yh072483x8656nci-stdenv-bootstrap-tools-aarch64-unknown-linux-musl/on-server/bootstrap-tools.tar.xz': SSL connect error (35); retrying in 1022 ms
warning: unable to download 'https://wdtz.org/files/wjzsj9cmdkc70f78yh072483x8656nci-stdenv-bootstrap-tools-aarch64-unknown-linux-musl/on-server/bootstrap-tools.tar.xz': SSL connect error (35); retrying in 2096 ms
error: unable to download 'https://wdtz.org/files/wjzsj9cmdkc70f78yh072483x8656nci-stdenv-bootstrap-tools-aarch64-unknown-linux-musl/on-server/bootstrap-tools.tar.xz': SSL connect error (35)
builder for '/nix/store/5i4lphsaikc4mjzaklcnwhv033l6cyjb-bootstrap-tools.tar.xz.drv' failed with exit code 1
`
Looks like my scaleway instance can't access the wdtz.org site due to some ssl problem. Do you guys meet such a problem before?

**Comment by steve-chavez** [comment]
@hughjfchen Looks like that url is defined here https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/linux/bootstrap-files/x86_64-musl.nix#L8.

Maybe it was a temporary issue? I'm able to download https://wdtz.org/files/gywxhjgl70sxippa0pxs0vj5qcgz1wi8-stdenv-bootstrap-tools/on-server/bootstrap-tools.tar.xz now.

**Comment by hughjfchen** [comment]
@steve-chavez , I fixed the 'unable to download' problem by upgrading nix to 2.3.3 which uses a newer version of libcurl. However, I'm now stuck at building the gnu coreutils which says a test case, test-init.sh, failed with an error: Segmentation fault. I don't know how to fix that. The only option which I can think about is try some binary cache from another nix store, maybe static-haskell-nix? Any suggestions?

**Comment by steve-chavez** [comment]
@hughjfchen On https://github.com/PostgREST/postgrest/issues/1295#issuecomment-517112721 it was mentioned that you could use `cachix use static-haskell-nix`. Maybe with that you can avoid building gnu coreutils locally.

**Comment by hughjfchen** [comment]
It took me 3 days to install `cachix` which builds everything from scratch. But unfortunately, I cannot use the `static-haskell-nix` binary cache because the `nix` version I'm using is not the same as the `static-haskell-nix` is using.

**Comment by steve-chavez** [comment]
> It took me 3 days to install cachix which builds everything from scratch.

@hughjfchen Argh, I'm really sorry for offering you terrible advice there.

I see you also reported the coreutils issue on https://github.com/NixOS/nix/issues/1973#issuecomment-601551473. Unfortunately, I can't be of further help on this. Solving the coreutils error might require patching upstream.

**Comment by hughjfchen** [comment]
@steve-chavez , No need to be sorry, it just looks like that ARM is still a "second tier" target platform for haskell and nix. As you said, I'd already reported the problem upstream. Let's see what'll happen next.
Back to this issue's original title, for a docker image, I think a binary statically linked to its haskell dependencies and dynamically linked to some system libraries, like glibc, libpq, is OK. This is the way I go with to build the docker images. You can pull the images from my docker hub repos and play around.

**Comment by hughjfchen** [comment]
dtzWill has been updated the upstream and I'm now rebuilding the static binary. Let's see if it can be built successfully.

**Comment by samkhawase** [comment]
Thanks @hughjfchen and @steve-chavez for your efforts to provide an ARM image. Can't wait to try it out!

**Comment by fenggy** [comment]
Thanks @hughjfchen and @steve-chavez

**Comment by hughjfchen** [comment]
Unfortunately, I haven't be able to get a fully statically linked binary for ARM platform, yet. I still stuck at building the coreutils and waiting for the upstream.

**Comment by andytango** [comment]
@steve-chavez 

[postgrest-armv7.tar.gz](https://github.com/PostgREST/postgrest/files/4751184/postgrest-armv7.tar.gz)

This does not appear to be statically linked (output from `ldd` below). 

I modified the Dockerfile in the the repository to use this binary instead of downloading one, and built an image from that. It appears to work without any issues. 

![image](https://user-images.githubusercontent.com/8215152/84130355-16c4a580-aa3b-11ea-9ddf-7e8605edd55e.png)

**Comment by steve-chavez** [comment]
I'm trying to run our nix static build setup on an AWS `t4g`(ARM) instance, but I'm getting an issue when trying to use `nix-shell`:

```bash
> nix-shell
Patchelfing /nix/store/d56lx3bxdvpxii0c85wv8yqya24sd3m2-ghc-8.6.5-binary/lib/ghc-8.6.5/bytestring-0.10.8.2/libHSbytestring-0.10.8.2-ghc8.6.5.so
Patchelfing /nix/store/d56lx3bxdvpxii0c85wv8yqya24sd3m2-ghc-8.6.5-binary/lib/ghc-8.6.5/transformers-0.5.6.2/libHStransformers-0.5.6.2-ghc8.6.5.so
running install tests
/nix/store/k832pghqg9z887j8py47ddhwzrn4yj1f-stdenv-linux/setup: line 1310:  3361 Segmentation fault      (core dumped) $out/bin/ghc --make main.hs
```

Seems related to:

- https://github.com/NixOS/nixpkgs/issues/97421
- https://github.com/NixOS/nixpkgs/issues/97407

**Comment by pixie79** [comment]
Would love to see this when it is ready, am happy to help test

**Comment by samkhawase** [comment]
I no longer run the ARM64 server since Scaleway shut that down, but can someone with an **M1 Macbook/Mac Mini** help us with the ARM/ARM64 builds?

**Comment by pixie79** [comment]
Github will build them for free - with github actions

**Comment by samkhawase** [comment]
Cool, time to play with GH Actions then :-)

**Comment by steve-chavez** [comment]
I successfully built the ARM binary on an AWS t4g instance(ubuntu) , but now I'm having trouble building it on Travis.

@samkhawase In case it helps, here are the steps I'm following: https://github.com/steve-chavez/postgrest/blob/travis-arm/.travis.yml#L82-L99.

Also AFAICT, stack doesn't work on ARM, right?

**Comment by steve-chavez** [comment]
Seems travis has an issue with ARM64. I keep getting a `No output has been received in the last 10m0s`. See: https://github.com/cilium/cilium/issues/10945. Some runs where I got this error:

- https://travis-ci.org/github/steve-chavez/postgrest/jobs/746506013
- https://travis-ci.org/github/steve-chavez/postgrest/jobs/746504263
- https://travis-ci.org/github/steve-chavez/postgrest/jobs/746477516

So it's definitely worth to look at another CI for automating the build.

Manually building the ARM64 works fine though. I'll upload the ubuntu build on our nightly release.

**Comment by steve-chavez** [comment]
Done. I uploaded `postgrest-nightly-2020-11-10-22-47-3830887-ubuntu-aarch64.tar.xz` on [nightly](https://github.com/PostgREST/postgrest/releases/tag/nightly).

The dependencies for the binary to run:
```
sudo apt -y install libpq5
sudo apt -y install libatomic1
```

I think it's fine to upload aarch64 binaries for different distros until the static binary works.

**Comment by fenggy** [comment]
Support,  hope  have different distros of mainstream version

**Comment by steve-chavez** [comment]
Note that the [above binary](https://github.com/PostgREST/postgrest/issues/1117#issuecomment-735334462) only works for ubuntu focal(20.04) and not for ubuntu bionic(18.04). It will give an error when tried on bionic:

```
$ ./postgrest
./postgrest: error while loading shared libraries: libffi.so.7: cannot open shared object file: No such file or directory
```

So now I've uploaded a binary for bionic - had several issues for building this one since its packages for ghc/cabal are outdated.
It's called `postgrest-nightly-2020-12-09-14-20-ebd474a-ubuntu-bionic-aarch64.tar.xz` under the [nightly page](https://github.com/PostgREST/postgrest/releases/tag/nightly).

Perhaps I'll switch to just building this one because I've noted that it also runs on focal.

**Comment by crrobinson14** [comment]
On my system (latest Dockerhub image of ubuntu:20.04) I got this while running the nightly aarch64 from `postgrest-nightly-2021-01-25-18-38-c93e8f9-ubuntu-aarch64.tar.xz`:

```
postgrest: error while loading shared libraries: libnuma.so.1: cannot open shared object file: No such file or directory
```

`apt install libnuma-dev` resolved this. Just reporting here for the record.

**Comment by steve-chavez** [comment]
I think we can do the docker release for ARM manually for now(not in CI).

Basically using [docker buildx build --platform linux/arm64](https://docs.docker.com/desktop/multi-arch/) and a custom Dockerfile using our ARM binary for Ubuntu(` postgrest-v8.0.0-ubuntu-aarch64.tar.xz`).

**Comment by steve-chavez** [comment]
There's now a PostgREST ARM Docker image for [v9.0.0](https://hub.docker.com/layers/postgrest/postgrest/v9.0.0/images/sha256-564c94132abf861adfd46a9473b90e4cf06881814799490660022e1c780eaa02) and [latest](https://hub.docker.com/layers/postgrest/postgrest/latest/images/sha256-564c94132abf861adfd46a9473b90e4cf06881814799490660022e1c780eaa02?context=explore).

**Comment by saxomagic** [comment]
@steve-chavez  thank you very, very much! It seems to be working fine. Another challenge though is PostgreSQL itself, for which there are ARM 64-bit docker images, but they do have issues still running on M1 chips:
https://github.com/docker/for-mac/issues/5830
https://github.com/docker/for-mac/issues/5407
https://github.com/docker/for-mac/issues/5590

The best workaround for now is the answer here:
https://stackoverflow.com/questions/65687712/postgres-errors-on-arm-based-m1-mac-w-big-sur

**Comment by albertobissacco** [comment]
@steve-chavez there will be made an armv7 version?

**Comment by maxgfr** [comment]
@hughjfchen Thanks ! It works for me

**Comment by laurenceisla** [comment]
@albertobissacco There is a new PostgREST armv7 Docker image for [v9.0.0](https://hub.docker.com/layers/postgrest/postgrest/v9.0.0/images/sha256-564c94132abf861adfd46a9473b90e4cf06881814799490660022e1c780eaa02) and [latest](https://hub.docker.com/layers/postgrest/postgrest/latest/images/sha256-564c94132abf861adfd46a9473b90e4cf06881814799490660022e1c780eaa02?context=explore) and a new binary in the [release page](https://github.com/PostgREST/postgrest/releases/tag/v9.0.0).
