### ISSUE TITLE
Bulk UPSERT Confusion

### ISSUE THREAD

**Issue by allochi** [PostgREST/postgrest#1118]
Hi,

I'm sorry if this is not the place to ask this question, I wouldn't have if there was a section about it in the documentation.

I'm trying to use Bulk UPSERT with a simple table

```sql
create table items (
	id serial primary key,
	name text
);
```

I then insert these records

```bash
curl -X "POST" "http://localhost:5200/items" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'[
  {
    "name": "iPad"
  },
  {
    "name": "iPhone"
  },
  {
    "name": "MacBook Pro"
  }
]'

```

When I try to UPSERT with this

```bash
## Upsert Items
curl -X "POST" "http://localhost:5200/items" \
     -H 'Prefer: resolution=merge-duplicates' \
     -H 'Content-Type: application/json' \
     -d $'[
  {
    "id": 1,
    "name": "iPad"
  },
  {
    "id": 2,
    "name": "iPhone"
  },
  {
    "id": 3,
    "name": "Macbook Pro"
  },
  {
    "id": null,
    "name": "PostgREST"
  }
]'
```

1. if I set `id` to null in the last item, I get error 400 `null value in column "id" violates not-null constraint`
2. if I don't include `id` in the last item, I get error 400 `"message":"All object keys must match"`

The only way I can get this to work is by providing a value for `id`, which I can't as `id` is auto-generated from a sequence, isn't the purpose of UPSERT is to INSERT a new record and in case of conflict with the primary key either update or ignore? how can I insert a new record in this case? 

Could you please advice on how this suppose to work? Thanks!

**Comment by steve-chavez** [comment]
One way to achieve what you want could be to define a trigger on your table that converts the null to the default, like:
```sql
CREATE OR REPLACE FUNCTION items_null_id_is_default() RETURNS TRIGGER AS $$
BEGIN
  NEW.id = coalesce(NEW.id, nextval('items_id_seq'));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER items_null_id_is_default BEFORE INSERT ON items FOR EACH ROW EXECUTE PROCEDURE items_null_id_is_default();
```
Then you could have the `{ "id": null, "name": "PostgREST"}` in UPSERT working, the trigger should have a slight overhead on the INSERT as there's no DML. Another option is to adjust your use case at the application level, UPSERT is better when you have natural keys(must specify all the ids).

**Comment by allochi** [comment]
@steve-chavez Thanks for your reply, it seems that UPSERT will not serve the purpose I want to use it for, so I will just create SQL functions for that.

I would expect UPSERT to check objects with an `id` for a conflict for `UPDATE`, and `INSERT` objects without `id`, but unfortunately it doesn't seems to be designed this way.

**Comment by steve-chavez** [comment]
@allochi It's a limitation for now, internally the UPSERT request is translated to:
```sql
INSERT INTO  "public"."items" ("id", "name") 
SELECT "id", "name" FROM json_populate_recordset (null:: "public"."items", 
'[ 
  { "id": 1, "name": "iPad" }, 
  { "id": 2, "name": "iPhone" }, 
  { "id": 3, "name": "Macbook Pro" }, 
  { "name": "PostgREST" } 
]') _  
ON CONFLICT(id) DO UPDATE SET "id" = EXCLUDED."id", "name" = EXCLUDED."name" 
RETURNING "public"."items".*
```
The undefined `id` attribute in the json is treated as a null, ideally PostgreSQL would turn that into a `DEFAULT` and it would use the sequence `nextval`(as possible when using VALUES) but it doesn't work that way, I can see how that's inconvenient maybe this could be raised on `psql-hackers` and see if it's possible to do. To fix that on PostgREST side we'd have to do extra json processing on the request body and that would greatly hurt performance, we already have an issue #690 on that.

I'll make sure to add a related note in the docs about this.

**Comment by allochi** [comment]
@steve-chavez thanks for the clarification.

I have already created a function to deal with my use case through RPC. But I would love to see PostgREST addresses this in the future. Thanks again!

**Comment by steve-chavez** [comment]
Docs on UPSERT are now available in https://postgrest.org/en/v5.0/api.html#upsert.

**Comment by allochi** [comment]
@steve-chavez Thanks a lot, I would also like to thank the team for a job well done on PostgREST.

**Comment by paulovieira** [comment]
This problem also got me confused! An unfortunatelly the error message doesn't help much (though now I can understand it).

When the table uses a surrogate key (that is, "id serial primary key") it's natural that people assume  that postgrest can make the upsert by ommiting the "id" key (in the POST'ed json). It's analogous to raw sql.

I'll make a pr to the docs to clarify this issue.

**Comment by geohuz** [comment]
I'm wondering if there is any other field missed in the json source the bulk insert can be successfully done. I recently hit a problem to sync a data from another api, I have carefully created the table on my side to include all the fields from the source, but there are several objects have missed fields other than the key fields still leaves me with the error: ""message":"All object keys must match". Is there any work around for this issue?

**Comment by steve-chavez** [comment]
@geohuz You can specify columns(http://postgrest.org/en/v7.0.0/api.html#specifying-columns) to bypass the "All object keys must match" validation.

**Comment by geohuz** [comment]
@steve-chavez Thank you so much!

**Comment by samirdamle** [comment]
As a workaround, I broke up the array of items into two separate arrays - one with null ids and the other with existing ids. 
Then I did two separate upserts and it worked.

`
const itemsToUpdate = items.filter(item => !!item.id )  // items with existing id
const itemsToCreate = items.filter(item => !item.id )   // items with null id

// do 2 separate upserts now for itemsToUpdate and itemsToCreate
`

**Comment by elyobo** [comment]
Still very confused after reading this thread, and the docs, as to whether bulk upsert is possible or not when there is a surrogate key involved. 

The docs now read as follows, which suggests that the PK(s) must be known to use upsert, but then suggests that it's possible with surrogate keys - although the phrasing makes this unclear whether it's specifically `ignore-duplicates` that can work with surrogate keys or whether it's the upsert functionality that can work with surrogate keys. I can't make out from the above whether it's meant to work, e.g. by specifying `null` values for the unknown PKs, or not.

> By default, upsert operates based on the primary key columns, you must specify all of them. You can also choose to ignore the duplicates with Prefer: resolution=ignore-duplicates. This works best when the primary key is natural, but it’s also possible to use it if the primary key is surrogate (example: “id serial primary key”). For more details read [this issue](https://github.com/PostgREST/postgrest/issues/1118).

**Comment by laurenceisla** [comment]
> although the phrasing makes this unclear whether it's specifically `ignore-duplicates` that can work with surrogate keys or whether it's the upsert functionality that can work with surrogate keys.

Yes, I agree here. It should be rephrased to mention that the Upsert itself *can* work with surrogate keys, but they are primarily designed for natural keys. I think the need for a trigger could be mentioned explicitly before linking to this issue. I'll be opening a PR with this clarification.

**Comment by ottobolyos** [comment]
Based on [this comment](https://github.com/PostgREST/postgrest/issues/1118#issuecomment-391379263), it looks like compount primary keys (created from multiple columns) are not supported right now, right?

I have table with `device_id` interger column and `ts` timestamp column which both are used as compound primary key. I wanted to use `Prefer: resolution=merge-duplicates` to upsert the data, however it fails with error `there is no unique or exclusion constraint matching the ON CONFLICT specification` even when there is no data in the table. :thinking:

**Comment by laurenceisla** [comment]
> Based on [this comment](https://github.com/PostgREST/postgrest/issues/1118#issuecomment-391379263), it looks like compount primary keys (created from multiple columns) are not supported right now, right?

They do work, according to our tests: https://github.com/PostgREST/postgrest/blob/a9d74eba2a3e4b75377d9bae1d621a6e4538fa1b/test/spec/Feature/Query/UpsertSpec.hs#L48-L59

The `first_name` and `last_name` are composite keys for the table.

If you still have the issue, [you can open a new Discussion](https://github.com/PostgREST/postgrest/discussions/new/choose) with a simple example that reproduces the error.

**Comment by sql-delete-imminent** [comment]
Notice the details in this https://stackdev.space/questions/creating-a-sql-function-that-transforms-json-keys-into-separate-attribute-columns answer
