### ISSUE TITLE
[Question] SIGHUP behavior to reload jwt-secret

### ISSUE THREAD

**Issue by sevagh** [PostgREST/postgrest#1119]
### Environment

* PostgreSQL version: 10
* PostgREST version: (if using docker, specify the image) 4.4
* Operating system: Linux

### Description of issue

(Expected behavior vs actual behavior)
I source my JWT secret from a file:

```
## choose a secret to enable JWT auth
## (use "@filename" to load from separate file)
jwt-secret = "@/secrest/jwt.secret"
```

When I change this file and send Postgrest a SIGHUP, it reloads itself:

```
Listening on port 3000
Attempting to connect to the database...
Connection successful
```

However I don't think it re-reads the contents of the JWT secret file. Is it supposed to?

My goal is to rotate the JWT signing key (for a sort of primitive "revocation" of pre-existing tokens).

**Comment by steve-chavez** [comment]
True, as it is now `SIGHUP` doesn't reload the configuration file, it only refreshes PostgREST schema cache, maybe a `SIGUSR1` would've been more appropriate for this since `SIGHUP` has a standard behavior. I'll make sure to add this for the next release.

**Comment by steve-chavez** [comment]
For anyone wanting to help with this one, #1289(an attempt on solving this) contains some additional hints on the implementation.
