### ISSUE TITLE
limit and offset in subqueries ?

### ISSUE THREAD

**Issue by cip123** [PostgREST/postgrest#1124]
### Environment

* PostgreSQL version: 9.6
* PostgREST version:   Docker 4.4.0
* Operating system: Debian

### Description of issue
Hello, we are using PostgREST in our project for some quite complex database views.  

From some point on, when we are using limit and offset (x-range headers or query parameters) with sub-selects we get very high response times. 

From what we have read, it seems like this is a known issue where postgres executes the subselects even for the records which are not requested. The solution would be to jiggle a little with the offset and limit, putting it in a subselect or a CTE table. 

Is there an internal GUC value or something similar that we can use in the database views in order to optimize the response times ? Does anybody have a hint on how to achieve this ?

Thanks

**Comment by steve-chavez** [comment]
Offsets on large data sets are expensive because of row rescans, maybe you can craft your queries based on keyset pagination, see this article for more info on that https://www.citusdata.com/blog/2016/03/30/five-ways-to-paginate/.

Also there was a related discussion in https://github.com/PostgREST/postgrest/issues/254.

**Comment by cip123** [comment]
Thanks for your answer. However, I would like to try the offset approach a little more before going the keyset pagination way mainly because of its limitations. 

So getting back to my question, I was thinking I could use the pre-request procedure to get the limit/offset values in a variable, and then use that variable in a subquery.  

I noticed that I can retrieve the headers using request.headers.XRange for example. Is there a solution for retrieving the query parameters also ?

**Comment by steve-chavez** [comment]
Saw your [SO question](https://stackoverflow.com/questions/50593323/postgrest-using-limit-and-offset-in-subqueries-or-cte), bear in mind that it's possible to use `limit/offset` in subqueries, for example you can do:
```http
GET /products?select=id,parts(*)&parts.offset=100&parts.limit=1000
```
This is documented in https://postgrest.org/en/v5.0/api.html#embedded-operations.

**Comment by cip123** [comment]
Thank you, I didn't mention in the question but my structure is a little more complicated than this and we can't allow our clients to do the join  by theirselves . We are just exposing the database views which the clients can filter both horizontally and vertically

**Comment by steve-chavez** [comment]
There's no out-of-the-box way to obtain the query parameters, recently there was a request for obtaining the uri as well so maybe it makes sense to add these capabilities, for now your best bet is to do it a the proxy level as I've shown above.

**Comment by cip123** [comment]
thanks Steve for your input. I will try your suggestions. One more question, if both the <code>Range</code> header and the <code>limit</code> and <code>offset</code> parameters are present, which one will take precedence?

**Comment by steve-chavez** [comment]
`Range` takes precedence over `limit/offset`, though bear in mind that they intersect, I recommend to just use one at a time, could be possible that I change this behavior to make `Range` override what `limit/offset` specifies if both are used at the same time.

**Comment by cip123** [comment]
We are using Kong at this moment, which is based on Nginx. We found the Nginx template location and added the proxy headers for offset and limit. Thanks
