### ISSUE TITLE
Recent set_schema change breaks postgis views/function

### ISSUE THREAD

**Issue by michelp** [PostgREST/postgrest#1125]
### Environment

* PostgreSQL version: (if using docker, specify the image)

mdillon/postgis:10

* PostgREST version: (if using docker, specify the image)

docker image tag v0.5.0.0-6bcbb12

* Operating system:

Ubuntu 18.04

### Description of issue

PostGIS install its functions and types into the public schema, but a recent postgrest change sets the search path explicitly to the configured api schema.  This breaks functions and views that use postgis functions.

(Expected behavior vs actual behavior)

That the public schema can be appended to the search path, perhaps by allowing search_path to be a configuration option.

(Steps to reproduce: Include a minimal SQL definition plus how you make the request to PostgREST and the response body)

```
fpx=# CREATE FUNCTION api.make_point(a double precision, b double precision)
RETURNS text AS $$
 SELECT ST_AsGeoJSON(ST_MakePoint(a, b));
$$ LANGUAGE SQL IMMUTABLE STRICT;
CREATE FUNCTION
fpx=#

Calling make point will return:

`{"hint":null,"details":null,"code":"42704","message":"type \"geometry\" does not exist"}`

**Comment by steve-chavez** [comment]
You can fix your function without explicit qualification by adding it a `search_path` like:
```sql
ALTER FUNCTION api.make_point(double precision, double precision) SET search_path = public;
```
This PostgreSQL feature is documented in https://www.postgresql.org/docs/9.5/static/sql-createfunction.html#SQL-CREATEFUNCTION-SECURITY.

Want to clarify that views will work normally, assuming that when you created them you were logged with a user that had `search_path=public`:
```sql
CREATE VIEW api.gis_sample AS SELECT ST_AsGeoJSON('LINESTRING(1 2 3, 4 5 6)')::json;
```
You can call that view normally with `GET /gis_sample` with no qualification despite that PostgREST does  a `set schema 'api'`.

This happens because views references are resolved at creation time and functions evaluate the references on execution, see this [answer on pgsql-general](https://www.postgresql.org/message-id/b42b73150611060853p63c8ee31l4ceac133b615e239%40mail.gmail.com).

**Comment by michelp** [comment]
Excellent! that works great, I like the explicit path.  This actually clarifies a few other weird things I've seen before so thank you!

**Comment by steve-chavez** [comment]
Yeah, I think not relying on the authenticator implicit `search_path` will be better in the long run, I'll make sure to add a note about this in the docs.

**Comment by steve-chavez** [comment]
Added a section for this in the docs https://postgrest.org/en/preview/api.html#explicit-qualification (preview, not yet released), @michelp what do you think, is it clear enough?

**Comment by michelp** [comment]
Looks good!  I got a report this also effect pgjwt users who install pgcrypto in public (uses public.hmac) so I'll make a new release with the alter tables in place and all should be good.  Thanks!

**Comment by mattaylor** [comment]
Using explict paths only addresses the issue of calling functions in external schemas. What about operators?
I am trying to use ltree with postgrest with tables that use ltree as a primary key and can't get around errors on embeded queries like "operator does not exist: public.ltree = public.ltree". 
Is there no way to add 'public' to the search path?

**Comment by mattaylor** [comment]
The only solution I have found to this issue is to install extensions like `ltree` into `pg_catalog` which is a fundamentally bad idea.

**Comment by steve-chavez** [comment]
@mattaylor We got a similar report related to `ltree`, not too long ago https://github.com/PostgREST/postgrest/issues/1183

The `pg_catalog` workaround won't be needed once we allow exposing multiple schemas https://github.com/PostgREST/postgrest/issues/1106.

**Comment by steve-chavez** [comment]
[v5.2.0](https://github.com/PostgREST/postgrest/releases/tag/v5.2.0) now contains an `db-extra-search-path` config which allows to use extensions on the public schema normally.
