### ISSUE TITLE
[Question] customize error messages

### ISSUE THREAD

**Issue by cip123** [PostgREST/postgrest#1127]
### Environment

* PostgreSQL version: 9.6
* PostgREST version: 4.4.9
* Operating system: Ubuntu

### Description of issue
Hello, is there a possibility to provide some custom error messages to the caller ? For example the body when we try to retrieve a table which does not exist we get
``
{
    "hint": null,
    "details": null,
    "code": "42P01",
    "message": "relation \"api_v1.categories\" does not exist"
}
``

Ideally we would like to style this response a little bit for example, ``{"message": "categories endpoint not found"}``. We tried to intercept the query in ``pre-request`` but there we couldn't identify the ``url`` or ``query-string`` of the original request. 

Is there any other way to do this ? 

Thanks

**Comment by steve-chavez** [comment]
For the url and querystring cases you can send both as headers through nginx:
```nginx
location /rest/ {
    proxy_pass http://postgrest/; # Reverse proxy to your PostgREST
    proxy_set_header X-Uri $uri;
    proxy_set_header X-Query-String $query_string;
    ## You can also get specific query params
    ## proxy_set_header X-Offset $arg_offset;
    ## proxy_set_header X-Limit $arg_limit;
}
```

And then you can obtain those in the `pre-request` function with `current_setting('request.header.x-uri', true)` as documented in https://postgrest.org/en/v5.0/api.html#accessing-request-headers-cookies.

**Comment by cip123** [comment]
Thanks, we were trying to avoid nginx route because we have a different setup and it adds another layer to our setup.

**Comment by cip123** [comment]
We ended up writing a Lua plugin (we are using Kong) that translates the error messages to the form we desire
