### ISSUE TITLE
candidates sql doesn't work when table name is quoted in view

### ISSUE THREAD

**Issue by gavrilyak** [PostgREST/postgrest#1129]
### Environment

* PostgreSQL version: docker, postgres:10.0
* PostgREST version: docker, postgrest/postgrest:v0.4.4.0

### Description of issue
candidates  [sql](https://github.com/PostgREST/postgrest/blob/30cf1d100a8b91f199be5ffb195811ce8bc5628d/src/PostgREST/DbStructure.hs#L746) can not find candidate columns from table when table name is quoted, like data."user" (as in [subzerocloud/postgrest-starter-kit](https://github.com/subzerocloud/postgrest-starter-kit/blob/master/db/src/libs/auth/data/user.sql)) or data."JobQueue". As a result quering with data embedding doesn't work for such table/view combination.

```
CREATE TABLE "Foo"(id int, name text);
CREATE VIEW foos as select id,name from "Foo"; 
CREATE TABLE bar(id int, foo_id int, name text);
CREATE VIEW bars as select id, foo_id, name from bar;


GET /bars?select=*,foos(*)
Could not find foreign keys between these entities, No relation found between foos and bars
```

Query performs correctly after performing 
```
ALTER TABLE "Foo" RENAME to foo
```

**Comment by steve-chavez** [comment]
Reproduced, formatting the test case a little bit:
```sql
CREATE TABLE "Foo"(
  id int primary key, 
  name text
); 

CREATE TABLE bar(
  id int primary key, 
  name text, 
  foo_id int references "Foo"(id)
);

CREATE VIEW foos as select id,name from "Foo"; 
CREATE VIEW bars as select id, foo_id, name from bar;

-- curl -s "http://localhost:3000/foos?select=*,bars(*)"
-- {"message":"Could not find foreign keys between these entities, No relation found between foos and bars"}

ALTER TABLE "Foo" RENAME to foo;

-- killall -s SIGHUP postgrest
-- curl -s "http://localhost:3000/foos?select=*,bars(*)"
-- []
```

**Comment by gavrilyak** [comment]
Oops, I missed 'references "Foo"(id)' in my test case, sorry. Thanks for fixing it.
