### ISSUE TITLE
PostgREST does not recognize jwt_claims

### ISSUE THREAD

**Issue by InigoReiriz** [PostgREST/postgrest#1135]
### Environment

* PostgreSQL version: postgres 9.5 (docker image)
* PostgREST version: postgrest/postgrest (docker image)
* Operating system: OS X

### Description of issue
Postgrest doesn't seem to recognize the jwt_claims and encode it as a jwt after hitting _http://localhost:3000/rpc/login_ endpoint. I expected the JWT token as a response from the server. I would be very grateful if you could give me a hint on the reason behind this behavior..

<img width="650" alt="screen shot 2018-06-24 at 19 20 04" src="https://user-images.githubusercontent.com/16237074/41821614-cfcb08da-77e3-11e8-9139-3a477127629b.png">

### Docker compose file

<img width="595" alt="screen shot 2018-06-24 at 19 27 25" src="https://user-images.githubusercontent.com/16237074/41821681-b01b69c0-77e4-11e8-9a5b-fd6029fa4cb3.png">

### Simplified init.sql file 

<img width="501" alt="screen shot 2018-06-24 at 19 36 56" src="https://user-images.githubusercontent.com/16237074/41821794-0396a1fe-77e6-11e8-9737-abc2808d599e.png">

<img width="672" alt="screen shot 2018-06-24 at 19 29 15" src="https://user-images.githubusercontent.com/16237074/41821728-f0c9ed34-77e4-11e8-8861-9ab95857fad7.png">

**Comment by tsingson** [comment]
```
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE OR REPLACE FUNCTION data.login(user_name TEXT,email TEXT,password TEXT)
  RETURNS public.SESSION AS $$
DECLARE usr RECORD;
  usr_api RECORD;
  result RECORD;
BEGIN

  EXECUTE format('')
  INTO usr
  USING user_name,email,password;

  IF usr IS NULL
  THEN RAISE EXCEPTION 'invalid email/password';
  ELSE EXECUTE format('select json_populate_record( null::settings.operator, $1) as r')
  INTO usr_api
  USING usr.j;

    result = (row_to_json(usr_api.r),auth.sign_jwt(auth.get_jwt_payload(usr.j)));
    RETURN result; END IF;
END
$$
STABLE
SECURITY DEFINER
LANGUAGE plpgsql;

```


look this:
```
  result = (row_to_json(usr_api.r),auth.sign_jwt(auth.get_jwt_payload(usr.j)));
```

sign_jwt() to build the jwt token .

**Comment by steve-chavez** [comment]
Your `login` function is missing the jwt generation, there's a `login` function example in the docs https://postgrest.org/en/v5.0/auth.html#logins.

**Comment by InigoReiriz** [comment]
@steve-chavez , yes, but where is the sign function defined ?

<img width="533" alt="screen shot 2018-06-24 at 20 08 04" src="https://user-images.githubusercontent.com/16237074/41822073-68116912-77ea-11e8-9146-297b7b304492.png">

**Comment by steve-chavez** [comment]
In the `pgjwt` extension, mentioned here https://postgrest.org/en/v5.0/auth.html#jwt-from-sql.
