### ISSUE TITLE
how to use dbpool  in postgrest

### ISSUE THREAD

**Issue by miaojianxin** [PostgREST/postgrest#1138]
i set dbpool=10 in the configfile
but when use curl to vist postgrest , i find  the connection from postgrest to postgresql  is  changed, not use the one connection all the time.

for example
 I use curl to visit postgrest (192.168.200.42:3000)
 curl -X POST "http://192.168.200.42:3000/rpc/select_with_define" -H "accept: application/json" -H "Content-Type: application/json"   -d "{ \"start_time\": \"2012-1-1\", \"end_time\": \"2019-1-1\",\"news_type\":\"ddd\",\"media_location\":\"ccc\"}"

netstat -anp|grep 5432 ,i got this:

netstat -anp|grep 5432
tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN      1059/postmaster     
tcp        0      0 192.168.200.42:55412    192.168.200.188:5432    ESTABLISHED 1031/./postgrest    

when i execute the curl again， the port （192.168.200.42:55412  this positon changed）,so it means the connection is a new connnection, and the old connnection is disconnected.

**Comment by steve-chavez** [comment]
There's a hardcoded timeout of 10 seconds for the pool([here](https://github.com/PostgREST/postgrest/blob/master/main/Main.hs#L172)), probably that's why you see new connections. Do you think this timeout should be configurable? Why would that be needed?

**Comment by miaojianxin** [comment]
ok， i understand， ten seconds is ok
