### ISSUE TITLE
Update stack.yaml to lts-12.0

### ISSUE THREAD

**Issue by mcarans** [PostgREST/postgrest#1144]
Currently the lts version is for ghc 8.0.2. [Alpine 3.8 has ghc 8.4.3](https://pkgs.alpinelinux.org/packages?name=ghc&branch=v3.8) which is in [lts-12.0](https://www.stackage.org/lts-12.0). 

Please update stack.yaml to use lts-12.0.

**Comment by steve-chavez** [comment]
Upgrading the lts is not a simple change, and I'm not sure is even possible without patching some of the libs(I remember one lib forcing an old version of a dependency when I tried), so this is not a priority for me, a PR would be welcome though.

**Comment by steve-chavez** [comment]
There are blocking issues for upgrading to GHC 8.4 https://github.com/PostgREST/postgrest/issues/1109. Let's continue the discussion there since what you're really after is GHC 8.4.3.
