### ISSUE TITLE
OpenAPI and materialized view : no column

### ISSUE THREAD

**Issue by lgall3t** [PostgREST/postgrest#1145]
### Environment

* PostgreSQL version: 9.5.4
* PostgREST version: 0.5.0.0
* Operating system: Centos 7, reproducible on Windows 7

### Description of issue

Hello,
I have a database with materialized views. I can make queries on those materialized view, it works fine. But, in OpenApi description on /, no column is displayed ; with Swagger-UI, I have only generic fields :
![swaggerui-mv](https://user-images.githubusercontent.com/41298220/42765999-97f11336-8919-11e8-8cff-2165bffddb3d.png)

The issue looks like #242, which is a closed bug because "OPTIONS no longer exists".

**Comment by steve-chavez** [comment]
Our query was missing a condition for materialized views, already added a patch in #1115.

**Comment by steve-chavez** [comment]
Most likely in the second half of next month, there are a couple bugs that need fixing. But you can [build from source](https://postgrest.org/en/v5.0/install.html#build-from-source) if you want the feature now, should be straightforward on Centos.
