### ISSUE TITLE
Question on the 'public user interface' documentation.

### ISSUE THREAD

**Issue by NickEmpetvee** [PostgREST/postgrest#1155]
Referencing this: https://postgrest.org/en/v5.0/auth.html#logins.

It's not clear to me if this SQL to create the `login(...)` function is supposed to be applied to the public or basic_auth schema. Could someone clarify?

**Comment by steve-chavez** [comment]
Should be in your exposed schema(the one you specify in `db-schema`, usually named `api`, better to have a dedicated schema for this rather than `public`). The `basic_auth` schema is internal, shouldn't be exposed.

**Comment by NickEmpetvee** [comment]
I appreciate the fast response. I'm just getting started with PostgREST and it seems awesome! Thanks.

**Comment by NickEmpetvee** [comment]
Would `jwt_token` as described here also get created on the exposed schema (which I've named "api")?

https://postgrest.org/en/v5.0/auth.html#jwt-from-sql
