### ISSUE TITLE
CONF file db-uri user/password situation

### ISSUE THREAD

**Issue by NickEmpetvee** [PostgREST/postgrest#1160]
Hi all,

PostgreSQL 10.x, PostgREST 0.5.x, Win81. Not using Docker.

I'm using the a URI like the below. The situation is that no matter what value I put in the `randomstring` section, PostgREST still works. It's not checking if I've provided a proper password. Any ideas on why this might be?

`db-uri = "postgres://dba_admin_xyz:randomstring@localhost/mypostgresdb"`

Thanks in advance!

**Comment by steve-chavez** [comment]
That depends on the [authentication method](https://www.postgresql.org/docs/10/static/auth-methods.html) you have on your `pg_hba.conf`, if you have something like:
```bash
# All unix socket
local   all all trust
# IPv4 local connections:
host    all all 127.0.0.1/32 trust
# IPv6 local connections:
host    all all ::1/128 trust
```
The `trust` there means no password required, `md5` would require one.

**Comment by NickEmpetvee** [comment]
That did the trick. Thanks @steve-chavez !
