### ISSUE TITLE
Querying data in schemas not specified in db-schema

### ISSUE THREAD

**Issue by NickEmpetvee** [PostgREST/postgrest#1163]
Hi guys. Would like to hear thoughts on how to best query data that's not in the exposed schema (db-schema). Is it best to create functions in the exposed schema that carry CRUD requests to the internal schemas?

Illustrating with an example, suppose the exposed schema is called 'api' and there's an internal schema in the database called 'Supply Chain' with tables named 'products', 'warehouses', 'inventory', 'stores', etc. I would want to access views, issue queries that joins the tables, and other things. What's the PostgREST paradigm for working with this? Would we even consider moving the supply chain tables to the exposed schema or is it best to keep the schema internal (keeping security in mind)?

From what I can tell, the exposed schema is minimal and the actual data should live in internal schemas. I'm not sure of the underlying reason for this but will prudently adhere to this guideline until I understand.

**Comment by daurnimator** [comment]
Normal practice is to create views in your api schema that query the other ones.
e.g. 

```sql
create view api.products as
    select * from internal_schema.products;
```

**Comment by NickEmpetvee** [comment]
@daurnimator, thank you. Then in your api schema, would you create functions for creates/updates/deletes for the other ones?

**Comment by NickEmpetvee** [comment]
The above and subsequent gitter conversation closed this.
