### ISSUE TITLE
How to access the authorization header value?

### ISSUE THREAD

**Issue by mdr1384** [PostgREST/postgrest#1168]
### Environment

* PostgreSQL version: 9.6.8
* PostgREST version: 0.5.0.0
* Operating system: FreeBSD

### Description of issue

Trouble accessing the `request.header.authorization` variable.  I can access every other header in the request, even application-specific ones like `postman-token`.  But for some reason I cannot access the `authorization` header.   I verified that it is being sent - it has to be since `request.jwt.claim.role` is working.  I need some way to access the entire token string -- I tried everything I could think of. Exactly what variables are set up anyway?  Is there a list somewhere?  Is there some other way to access the raw authorization token?

Schema:
```
CREATE OR REPLACE FUNCTION api.test1() RETURNS VOID AS $$
BEGIN
    RAISE WARNING 'request.header.authorization = %', current_setting('request.header.authorization');
EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'request.header.authorization = (no way)';
END;
BEGIN
    RAISE WARNING 'request.header = %', current_setting('request.header');
EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'request.header = (no way)';
END;
BEGIN
    RAISE WARNING 'request.headers = %', current_setting('request.headers');
EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'request.headers = (no way)';
END;
BEGIN
    RAISE WARNING 'request.jwt = %', current_setting('request.jwt');
EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'request.jwt = (no way)';
END;
BEGIN
    RAISE WARNING 'request = %', current_setting('request');
EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'request = (no way)';
END;

RAISE WARNING 'request.header.accept = %', current_setting('request.header.accept');
RAISE WARNING 'request.header.accept-encoding = %', current_setting('request.header.accept-encoding');
RAISE WARNING 'request.header.cache-control = %', current_setting('request.header.cache-control');
RAISE WARNING 'request.header.content-length = %', current_setting('request.header.content-length');
RAISE WARNING 'request.header.content-type = %', current_setting('request.header.content-type');
RAISE WARNING 'request.header.user-agent = %', current_setting('request.header.user-agent');
RAISE WARNING 'request.header.postman-token = %', current_setting('request.header.postman-token');
RAISE WARNING 'request.jwt.claim.role = %', current_setting('request.jwt.claim.role');
$$ LANGUAGE plpgsql;
```
Request:
```
GET
https://xxx.yyy/api/v1/rpc/test1
Request Headers:
   content-type:"application/json"
   cache-control:"no-cache"
   postman-token:"b12193c7-2e96-4674-96dc-87d9c2afde13"
   authorization:"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIiA6ICJyZXN0X3VzZXJfbWF4IiwgInJlZGNvbV9zaWdtYV9yZXN0X3VzZXJfaWQiIDogMSwgInJlZGNvbV9zaWdtYV9yZXN0X21vZGVfaWQiIDogMCwgInJlZGNvbV9zaWdtYV9yZXN0X3ZzX2lkIiA6IDAsICJqdGkiIDogImpWL1hqQTlwMzVkbWlwOGt3RmE2SUIydG9vWnFrT3Z2ZWtVbnc5OXpReHM9IiwgImlzcyIgOiAiZmxvcmlkYS5yZWRjb20uY29tIiwgImlhdCIgOiAxNTM0Mjc3MjY2LCAibmJmIiA6IDE1MzQyNzcyMzYsICJleHAiIDogMTUzNDU3NzI2Nn0.ci2vzUiez7kiIYbtThf9ySnksNk2-yp96bdm1_BfveY"
   user-agent:"PostmanRuntime/7.2.0"
   accept:"*/*"
   accept-encoding:"gzip, deflate"
   content-length:55
```
Output:
```
2018-08-14 ...  [3-1] WARNING:  request.header.authorization = (no way)
2018-08-14 ...  [4-1] WARNING:  request.header = (no way)
2018-08-14 ...  [5-1] WARNING:  request.headers = (no way)
2018-08-14 ...  [6-1] WARNING:  request.jwt = (no way)
2018-08-14 ...  [7-1] WARNING:  request = (no way)
2018-08-14 ...  [8-1] WARNING:  request.header.accept = */*
2018-08-14 ...  [9-1] WARNING:  request.header.accept-encoding = gzip, deflate
2018-08-14 ...  [10-1] WARNING:  request.header.cache-control = no-cache
2018-08-14 ...  [11-1] WARNING:  request.header.content-length = 55
2018-08-14 ...  [12-1] WARNING:  request.header.content-type = application/json
2018-08-14 ...  [13-1] WARNING:  request.header.user-agent = PostmanRuntime/7.2.0
2018-08-14 ...  [14-1] WARNING:  request.header.postman-token = 03d33f80-9d2d-4c83-8c47-22d5bb18c86b
2018-08-14 ...  [15-1] WARNING:  request.jwt.claim.role = rest_user_max
```

**Comment by steve-chavez** [comment]
All raw headers available besides `Cookie` and `Authorization`([code](https://github.com/PostgREST/postgrest/blob/master/src/PostgREST/ApiRequest.hs#L132)), those are processed and come conveniently as `request.cookie.*` and `request.jwt.claim.*` values. 

What's the use case for raw `Authorization`?

**Comment by mdr1384** [comment]
The API calls an external function, which verifies the user input prior to UPDATE/INSERT and updates associated data records. It function performs authorization (token signature verification) because it is used from multiple interfaces so I was hoping to just pass along the token, rather than re-implement the function.

**Comment by steve-chavez** [comment]
I'm not sure I follow. If that external API call verifies the signature and obtains the jwt claims why the need to go first through postgrest, you could make the client request first go to that external component and then send the claims to postgrest as headers.

**Comment by mdr1384** [comment]
The function is called from within a trigger on insert/update - it has to be atomic with each row change. I could take all the code (PHP) and try to re-implement it in SQL but it would take weeks probably. I was hoping I could just call the existing Python code directly using a plpython2u call. The function is extremely complex and does a lot of stuff for password requirement checking and auditing, so I really want to be able to call it from an update trigger:
```
CREATE OR REPLACE FUNCTION _api.handle_password_change(
        _jwt TEXT, _uid TEXT, _npw TEXT, _opw TEXT, _pws TEXT, _usr TEXT
    )
    RETURNS TEXT LANGUAGE plpython2u AS
$$
import subprocess
try:
    return subprocess.check_output([
            "/usr/local/bin/php",
            "/usr/local/www/portal/index.php",
            "controllers",
            "handle_password_change",
            _jwt, _uid, _npw, _opw, _pws, _usr
        ])
except:
    return '{"status": False, "strength": 0, "alerts": []}';
$$;

CREATE OR REPLACE FUNCTION _api.update_users()
    RETURNS TRIGGER LANGUAGE plpgsql AS
$$
...
result : = _api.handle_password_change(
    current_setting('request.jwt'),
    OLD.id,
    NEW.password,
    OLD.password,
    NEW,
    NEW
);
$$;

CREATE TRIGGER update_users_trigger
    INSTEAD OF  UPDATE ON api.users
    FOR EACH ROW EXECUTE PROCEDURE _api.update_users();
```

If it is a major issue, then I guess nevermind, I'll have to re-implement the function.

**Comment by steve-chavez** [comment]
It's actually just removing the `k /= hAuthorization` from this line https://github.com/PostgREST/postgrest/blob/master/src/PostgREST/ApiRequest.hs#L132.

You could have your own fork with that change for now.

**Comment by steve-chavez** [comment]
The cost in our case will be the overhead of adding one more transaction scoped GUC, but I haven't measured how meaningful this is as to oppose to the change. Do the PR, I'll see if I can add benchmarks for the next release.

**Comment by mdr1384** [comment]
Isn't the number of GUC's completely dependent on the number of headers the client puts in? If there is a performance hit then it seems to me that there is a DOS possibility...

**Comment by steve-chavez** [comment]
I'll have to measure that first, but it's possible. To avoid that we could have a config setting that whitelists the client headers, this setting could be like `request.allowedHeaders = [Authorization, Cookie, ..]`.

**Comment by steve-chavez** [comment]
I've noticed that our web server(Warp) already handles the overlarge headers issue. On https://hackage.haskell.org/package/warp-3.0.5/docs/Network-Wai-Handler-Warp.html#t:InvalidRequest, see `OverLargeHeader`.

Access to the `Authorization` header value can be added.
