### ISSUE TITLE
How can i remove the function name key of the json result when calling the rpc?

### ISSUE THREAD

**Issue by nengc** [PostgREST/postgrest#1171]
### Environment

* PostgreSQL version: 10.4
* PostgREST version: 0.5.0.0 (903a8d5)
* Operating system:windows 7

### Description of issue

As the title, when i use rpc to get a json object, how can i remove the function name key?

![image](https://user-images.githubusercontent.com/19792047/44257243-01670180-a23e-11e8-8e92-78d4eae49cea.png)

Thanks!

**Comment by steve-chavez** [comment]
The function name should be gone after [reloading postgrest schema cache](https://postgrest.org/en/v5.0/admin.html#schema-reloading), try restarting postgrest and making the request again.

**Comment by nengc** [comment]
Hi @steve-chavez ,I restart the postgrest container again ,but still not working. And the function as below

![image](https://user-images.githubusercontent.com/19792047/44315979-71060800-a45b-11e8-8c04-88f552ba0da3.png)
 
![image](https://user-images.githubusercontent.com/19792047/44316037-ed98e680-a45b-11e8-9ddb-86133d23a922.png)
Thanks!

**Comment by steve-chavez** [comment]
When doing `GET /rpc/bb` you're basically doing a ` SELECT * FROM "public"."bb"()` which will return rows with `bb` as the only column, similar case with all functions that return `setof <scalar>`, they'll return the name of the function as the only column.

For your case you could use `GET /rpc/bb?select=bb->user_id,bb->user_name` but I don't recommend that, it'd be better to change your function so you return a `setof "user"` then postgrest will convert that to json.

You can turn [database logging on](http://postgrest.org/en/v5.0/admin.html#database-logs) so you can see the queries postgrest generates and understand this better.

**Comment by nengc** [comment]
Hi @steve-chavez ,thanks again! And the "select" worked, but what my  purpose is to get dynamic columns, and neither need to set the out params nor return the default table type, so i convert the row to json. Are there any other methods to implement the function? I think it is a useful function!

**Comment by nengc** [comment]
Hi @steve-chavez ,I tested again, and found the solution in the end. And the code as below.
![image](https://user-images.githubusercontent.com/19792047/44563044-fb69a700-a78e-11e8-98bf-7f13d661df94.png)
![image](https://user-images.githubusercontent.com/19792047/44563145-7337d180-a78f-11e8-92ac-7f8df68b3aa7.png)

And when set the result type as "json" or "setof", the result will still have the function name key.
![image](https://user-images.githubusercontent.com/19792047/44563154-8054c080-a78f-11e8-8746-81fa432e3e62.png)
![image](https://user-images.githubusercontent.com/19792047/44563289-2a344d00-a790-11e8-89a2-709ffa1bbe6b.png)

And if any other simple methods exist? Thanks again!

**Comment by steve-chavez** [comment]
When the result is `json` or `json[]`(or any scalar) postgrest will omit the function name key(don't forget to restart or SIGHUP), I've tried your `dd` function(btw, please paste the sql code instead of images, that way I can copy it) and it outputs the json without the `dd` key, seems you missed the restart/SIGHUP.

**Comment by nengc** [comment]
@steve-chavez  Ah! It is weird. Now the name key disappeared.

![image](https://user-images.githubusercontent.com/19792047/44644446-b6e84080-aa06-11e8-9938-2f3d7354c2ff.png)

And a more question, the filed names are now "f1,f2...", how to get the original fields except for the "for 
 loop"?
`CREATE OR REPLACE FUNCTION "public"."cc"()
  RETURNS "pg_catalog"."_json" AS $BODY$
DECLARE v_rec record;
DECLARE	o_json json;
DECLARE arr json[];

BEGIN
   for v_rec in  (select * from "user") loop
			o_json := row_to_json(v_rec);
			select array_append (arr,o_json) into arr;
   end loop;
RETURN arr;

END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100`

**Comment by steve-chavez** [comment]
You can use `select into var json_agg(u) as "user" from "user" u` instead of `select into var json_agg(row(u.*)) as "user" from "user"` to get the original keys.

**Comment by nengc** [comment]
Thanks @steve-chavez , it works fine!

**Comment by steve-chavez** [comment]
Good, I'll close this then.
