### ISSUE TITLE
what the driver does  postgrest use when connect to the db？

### ISSUE THREAD

**Issue by miaojianxin** [PostgREST/postgrest#1173]
now， i use a graph database agensgraph which is based onpostgresql, it makes some change in the code of postgresql.
i want to use postgrest on this db, but you know, because the code changed,  the postgrest won't  be compatible with the changed agensgraph .

so i want to change the driver used in postgrest ,how can i do for this? thank you

**Comment by miaojianxin** [comment]
i know it ，and know how to be compatible  with  postgrest， thank you

**Comment by retseltony** [comment]
how do you connect i am the same problem

**Comment by steve-chavez** [comment]
I suggest to try the latest release(v5.1) and see if it works well with agensgraph.

**Comment by miaojianxin** [comment]
last time， it doesn't work because  one sql in postgrest use math as alias of table name， but match is reserves in agensgraph ，so the sql gets wrong，and the connect faild. when i use the source newest on github and compile a new postrest,  the new one workes well with agensgraph. that' s a good job
