### ISSUE TITLE
CRUD with PostgREST - Failing

### ISSUE THREAD

**Issue by NickEmpetvee** [PostgREST/postgrest#1174]
* PostgreSQL version: 10.x
* PostgREST version: 5
* Operating system: Win 8.1

My understanding is that with PostgREST, as long as the permissions are correct, you can handle CRUD by posting to the view in your public-facing schema and it will write to the underlying table even if it's in a different schema. That's not working for me. I'm able to post to a table on the exposed schema, but not to a view.

I'm trying to post data to the 'yz' view in schema 'api' in hopes that it'll update the underlying table and it's failing with "permission denied for relation yz". I've confirmed that 'yz' is updatable and inserts to it make their way back to the base.

'api.yz' is just a simple select on table 'abc.x'. The pg superuser owns schemas 'api' and 'abc'. 'abc' houses the application data.

I have a user called web_anon who's been granted usage on 'api'. In PostgREST, 'api' is my db-schema and web_anon is my db-anon-role. As the superuser owns the view and the underlying table, and since the view creator needs write privileges to the underlying table for PostgREST to handle CRUD, I'd expect permission to not be an issue.

Does anything stand out about what I'm doing wrong? Do I need to make 'provisioner' the owner of 'x' and 'api' schemas?

**Comment by steve-chavez** [comment]
Share a reproducible test case(your `postgrest.conf`, the schema, how you're making the request and the response), is not easy to track the problem in text form.

One suggestion that I can give you for now is that you check that your views are auto-updatable, see http://www.postgresqltutorial.com/postgresql-updatable-views/.

**Comment by NickEmpetvee** [comment]
Thank you. I'm pulling the information together. The views are definitely auto-updatable. I tested.

**Comment by steve-chavez** [comment]
If you want to do a PATCH with `web_anon` then you're missing a `GRANT UPDATE ON api.full_list TO web_anon`, try adding that.

Also, the connection user should be minimally privileged and using `postgres` is not recommended, you should create an `authenticator` user that has only permission to switch roles and permission for executing a `login` stored procedure.

**Comment by steve-chavez** [comment]
Also check https://github.com/subzerocloud/postgrest-starter-kit/tree/master/db/src

**Comment by NickEmpetvee** [comment]
Ok. FYI I got the same response with a POST when trying to add a new row as I did with a PATCH/update. Do I need to add another GRANT for POST?

I've created the following users based on the PostgREST docs: anon, authenticator, web_anon. Another user suggested I create a user called provisioner which I did. Can you advise which of these roles should own the api schema and the "hidden" schema?

The thing with the subzerocloud is that it's Docker from what I can well. We've had a lot of problems with Docker on windows.
