### ISSUE TITLE
how to filter inside an array

### ISSUE THREAD

**Issue by adren** [PostgREST/postgrest#1175]
### Environment

* PostgreSQL version: latest (10)
* PostgREST version: 0.5.0.0
* Operating system: Debian GNU/Linux

### Description of issue

I've got a response with a list of movies where an item is like this:

```
  {
    "id": 123456,
    "original_title": "The title",
    "prod_year": 2017,
    "prod_countries": [
      {
        "iso": "DE",
        "order": 1,
        "is_eur_coe": true,
        "is_eur_eur": true
      },
      {
        "iso": "US",
        "order": 2,
        "is_eur_coe": false,
        "is_eur_eur": false
      }
    ]
}
```

Is it possible to filter movies produced in Germany (i.e. when prod_countries array contains iso:DE value)?
Maybe with a combination of ->, ->> and cs operator I suppose but the is no sample in the doc...

**Comment by steve-chavez** [comment]
Master branch has the ability to filter by array index with `->`, there are some examples here http://postgrest.org/en/latest/api.html#vertical-filtering-columns, search for `jsonb`.

You could [build from source](http://postgrest.org/en/v5.0/install.html#build-from-source) if you want to try this now or wait for a new release(next few days).

**Comment by mgmgh** [comment]
For this kind of filter, I've logged the generated sql on the server and the good filter syntax is:
prod_countries=cs.[{"iso":"DE"}]
This generates this working sql where clause: "prod_countries" @> '[{"iso":"IT"}]'::unknown
which is index aware :-)

**Comment by steve-chavez** [comment]
@adren Check the recent docs on json operators here http://postgrest.org/en/v5.1/api.html#json-columns, this combined with cs will likely solve your problem. I'll close this for now, reopen if it's still an issue.
