### ISSUE TITLE
Function argument types aren't qualified correctly

### ISSUE THREAD

**Issue by hrdinka** [PostgREST/postgrest#1181]
### Environment

* PostgreSQL version: 10.5
* PostgREST version: 5.1.0
* Operating system: NixOS

### Description of issue

Types belonging to the `public` schema won't be prefixed correctly by the query builder. This Bug exists since the `set_schema` update introduced with v5.0.0.

Consider the following example.

We have `my_type` defined within `public`:

```sql
CREATE TYPE public.my_type AS
    enum ('something');
```

Schema `api` is exported by postgrest. Within this schema lives this function:

```sql
CREATE SCHEMA api;

CREATE FUNCTION api.test(my_arg public.my_type) RETURNS text AS $$
  SELECT 'foobar';
$$ LANGUAGE sql IMMUTABLE SET search_path = public, pg_temp;
```

The problem is that postgrest's query builder will cast all supplied arguments to the according type. For `my_arg` this is `public.my_type`. The query builder will however not cast to `public.my_type` but to `my_type` missing the qualifier. Since v5.0 the search path will be set to `api` and it therefore will look in `api` for this type.

Besides it failing with `type "my_type" does not exist` this opens up harder to find bugs if a different `my_type` is also defined within `api`.

Consider that the defined `search_path` only applies to the function body and not to the arguments. They are looked up within the scope of the calling transaction.

**Comment by steve-chavez** [comment]
Thank you for the thorough report. An immediate fix you could do is to empty the `search_path`  of your connection user(the one used in `db-uri`), like `ALTER ROLE authenticator SET search_path TO ''`, and then restart postgrest.

Also this is only happening for `public`, if the type is defined on another schema it'll work normally(if the role has access to that schema).

**Comment by hrdinka** [comment]
@steve-chavez thanks for your response! I will come back with a PR in the next few days.
