### ISSUE TITLE
operator searching with explicit qualification

### ISSUE THREAD

**Issue by sunbing81** [PostgREST/postgrest#1183]
With the explicit qualification, how can I use an operator that is not contained in pg_catalog or db_schema?

Say, if I install 'ltree' (which provides quite a number of operators) into the schema 'extensions', the following query will simply not run since it can not find the matching operator '=':

```sql
create table public.test (
  path extensions.ltree
);

create view api.test as select * from public.test;

set search_path to api;
select * from api.test where path = 'a.b.d';
```

Any one runs into the same situation?

**Comment by steve-chavez** [comment]
If your admin user(the one you use for creating your db schema) has the schema `extensions` in his `search_path`, then the view should work normally, since the view references are resolved at creation time. Try doing `set search_path to 'api, extensions, public'` and then recreate the view.

The other option would be to use the `=` as `operator(extensions.=)`.

**Comment by steve-chavez** [comment]
Just tried an example, I see what you mean now, though the view can be SELECTed normally the custom operators fail.
```sql
create extension ltree;

create table private.ltree_sample (
  path ltree
);

create view api.ltree_sample as select * from private.ltree_sample;

curl -s "localhost:3000/ltree_sample?path=eq.a.b.d"
{"hint":"No operator matches the given name and argument type(s). You might need to add explicit type casts.","details":null,"code":"42883","message":"operator does not exist: public.ltree = unknown"}
```
For now, the workaround that occurs to me is using the `operator(..)` syntax behind a stored procedure.

**Comment by sunbing81** [comment]
I think I'll go with the 'pg_catalog' solution for now. Thanks.

**Comment by steve-chavez** [comment]
[v5.2.0](https://github.com/PostgREST/postgrest/releases/tag/v5.2.0) now contains an `db-extra-search-path` config which allows to use extensions on the public schema normally.
