### ISSUE TITLE
Resource embedding error

### ISSUE THREAD

**Issue by NickEmpetvee** [PostgREST/postgrest#1184]
**Environment**
PostgreSQL version: 10
PostgREST version: 0.5.1.0
Operating system: Win81

From what I read [here](https://postgrest.org/en/v5.1/api.html#resource-embedding), resource embedding works with both views and tables unless I am misunderstanding.

I've exposed a map table as a view and its base tables individually as views. The views are in the exposed `api` schema and the tables are in a primary schema not visible to Postgrest.

I try to run this command: `curl http://localhost:14300/base_order?select=base_products(id,role_name)`.  It seems this doesn't work because even though the fkeys are present in the order table pointing to the id in the products table, they don't carry across in this case to the views generated from those tables.

Curl error: `{"message":"Could not find foreign keys between these entities, No relation found between base_order and base_products"}`

Maybe I'm just not understanding resource embedding but could use some help.

**Comment by steve-chavez** [comment]
Share the relevant table/views in your schema so I can reproduce the error, maybe it's a detection shortcoming(can happen if the view has UNIONs for example).

**Comment by NickEmpetvee** [comment]
Thank you so much @steve-chavez 

I've attached a file with the views in the exposed api schema and another file with the tables referenced in the appdata schema. The *_map view maps the other two views in that file together, and the same goes for the table file.

[tables.txt](https://github.com/PostgREST/postgrest/files/2426805/tables.txt)
[views.txt](https://github.com/PostgREST/postgrest/files/2426806/views.txt)

**Comment by NickEmpetvee** [comment]
Here's the SQL in case you prefer that. I've obfuscated the table names and view names slightly so let me know if they don't appropriately generate.

[views.sql.txt](https://github.com/PostgREST/postgrest/files/2426821/views.sql.txt)
[tables.sql.txt](https://github.com/PostgREST/postgrest/files/2426822/tables.sql.txt)

**Comment by steve-chavez** [comment]
I couldn't find the `base_order` nor the `base_products` views in those files, make sure you're sharing all that's needed to reproduce the error. Also sharing the SQL code is better, you can inline SQL in the comment by surrounding the code with [3 backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting).

**Comment by NickEmpetvee** [comment]
Hey Steve, the base_order / base_products was some experimental stuff. What I've shared here is what the actual tables will be. The same problem is happening in this case. Some details:

From a table perspective, `appdata.employee_location_map` ties `appdata.employee` to `appdata.location`. The FKEYS are `emp_id` and `location_id`.

From a view perspective:
- `appdata.employee_location_map` is exposed `api.base_employee_locations`
- `appdata.employee` is exposed as `api.base_employee`
- `appdata.location` is exposed as `api.base_location`

The SQL:

```
-- Table: appdata.location

-- DROP TABLE appdata.location;

CREATE TABLE appdata.location
(
    id integer NOT NULL DEFAULT nextval('appdata.location_id_seq'::regclass),
    location_name text COLLATE pg_catalog."default" NOT NULL,
    location_description text COLLATE pg_catalog."default" NOT NULL DEFAULT 'TBD'::text,
    CONSTRAINT location_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE appdata.location
    OWNER to provisioner;
    
    
-- Table: appdata.employee

-- DROP TABLE appdata.employee;

CREATE TABLE appdata.employee
(
    id integer NOT NULL DEFAULT nextval('appdata.employee_id_seq'::regclass),
    supervisor integer,
    employee_name text COLLATE pg_catalog."default" NOT NULL,
    no_dragging boolean NOT NULL DEFAULT false,
    archived boolean NOT NULL DEFAULT false,
    CONSTRAINT employee_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE appdata.employee
    OWNER to provisioner;
    
    
-- Table: appdata.employee_location_map

-- DROP TABLE appdata.employee_location_map;

CREATE TABLE appdata.employee_location_map
(
    map_id integer NOT NULL DEFAULT nextval('appdata.employee_location_map_id_seq'::regclass),
    emp_id integer NOT NULL,
    location_id integer NOT NULL,
    primary_location boolean NOT NULL DEFAULT false,
    CONSTRAINT employee_location_map_pkey PRIMARY KEY (map_id),
    CONSTRAINT emp_id_fkey FOREIGN KEY (emp_id)
        REFERENCES appdata.employee (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT location_id_fkey FOREIGN KEY (location_id)
        REFERENCES appdata.location (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE appdata.employee_location_map
    OWNER to provisioner;

-- View: api.base_location

-- DROP VIEW api.base_location;

CREATE OR REPLACE VIEW api.base_location AS
 SELECT location.id,
    location.location_name,
    location.location_description
   FROM appdata.location
  ORDER BY location.id;

ALTER TABLE api.base_location
    OWNER TO provisioner;

GRANT UPDATE, SELECT, INSERT ON TABLE api.base_location TO web_anon;
GRANT ALL ON TABLE api.base_location TO provisioner;


-- View: api.base_employee

-- DROP VIEW api.base_employee;

CREATE OR REPLACE VIEW api.base_employee AS
 SELECT employee.id AS node_id,
    employee.supervisor AS parent,
    employee.employee_name AS title,
    employee.no_dragging AS nodragging,
    employee.archived
   FROM appdata.employee
  WHERE employee.archived = false
  ORDER BY employee.supervisor NULLS FIRST, employee.employee_name;

ALTER TABLE api.base_employee
    OWNER TO provisioner;

GRANT UPDATE, SELECT, INSERT ON TABLE api.base_employee TO web_anon;
GRANT ALL ON TABLE api.base_employee TO provisioner;


-- View: api.base_employee_locations

-- DROP VIEW api.base_employee_locations;

CREATE OR REPLACE VIEW api.base_employee_locations AS
 SELECT employee_location_map.map_id,
    employee_location_map.emp_id,
    employee_location_map.location_id,
    employee_location_map.primary_location
   FROM appdata.employee_location_map;

ALTER TABLE api.base_employee_locations
    OWNER TO provisioner;

GRANT UPDATE, SELECT, INSERT ON TABLE api.base_employee_locations TO web_anon;
GRANT ALL ON TABLE api.base_employee_locations TO provisioner;

```

**Comment by steve-chavez** [comment]
What's the curl call that fails for this case?

**Comment by steve-chavez** [comment]
`curl http://localhost:14300/base_employee_locations?select=base_location(id,location_name)` is working for me, did you restarted postgrest after creating the views?

**Comment by NickEmpetvee** [comment]
I did now and it works. Did not realize that a _restart_ was needed! Wow. I just found the schema reloading part of the PostgREST documentation.

Well thank you for looking into it.
