### ISSUE TITLE
Unix socket listening support request

### ISSUE THREAD

**Issue by akemrir** [PostgREST/postgrest#1186]
### Environment

* PostgreSQL version: 10.5
* PostgREST version: 5.1.0 (3cef4b7)
* Operating system: Archlinux

### Description of issue

Right now the only way to send requests to PostgREST is to make tcp call over port.
There is no way to do it via unix socket. To utilize it with nginx for example.

There are many benchmarks proving that unix socket is more efficient than tcp connection.
Maybe this options could make it`s way into PostgREST?

For example with new listening option in configuration:
`server-unix-socket = unix:/tmp/socktest.sock`

**Comment by ruslantalpa** [comment]
nginx can very well be in front of postgrest as a reverse proxy, and as for efficiency ... optimising this is almost irrelevant, in the total time it takes to process a request, the tcp/http overhead between nginx/postgrest on the same box i would say is well under 1% (just a feeling). 
You will better spend your time optimising indexes on your db :)

**Comment by steve-chavez** [comment]
A single box with postgresql-unixsocket-postgrest-unixsocket-nginx looks like a solid production setup, would be interesting to benchmark it and see if the unix socket performance boost is really that negligible.

**Comment by ruslantalpa** [comment]
i benchmarked (in aws, on small boxes with limited resources) running a query on the db directly and trough postgrest. the entire postgrest in the chain adds 2ms, imagine how much of that time is the tcp overhead... and now think that an average query might be say 50-100ms, add in the network time (browser to postgrest) of 50-100ms then you end up optimising 0.2ms out of a 100ms request ...
in terms of CPU used on the box ... a few cents a month maybe?

this is really a feature for setups with really high loads that are trying to get the most throughput out of their hardware and in that case maybe they should sponsor it? :)

**Comment by steve-chavez** [comment]
Just saw how to implement this and I think it should be a really simple change!

Currently we use [runSettings](http://hackage.haskell.org/package/warp-1.2.1.1/docs/Network-Wai-Handler-Warp.html#v:runSettings) here https://github.com/PostgREST/postgrest/blob/master/main/Main.hs#L217.
There's another function [runSettingsSocket](http://hackage.haskell.org/package/warp-1.2.1.1/docs/Network-Wai-Handler-Warp.html#v:runSettingsSocket) that receives a Socket as a parameter. We could have a `server-socket` config and apply that function conditionally.

A PR would be welcomed :)

**Comment by Dansvidania** [comment]
Hello, I would like to work on this if its ok.

I am having some issues running the test suite, in particular to create the test database. Is there some documentation about it that I am missing?

Thanks in advance

**Comment by steve-chavez** [comment]
@Dansvidania You're most welcome to make a PR.

Could you try running the [test suite with docker](http://postgrest.org/en/v5.2/install.html#testing-with-docker)? I think it's the easiest way.

**Comment by Dansvidania** [comment]
Thanks a lot @steve-chavez that was exactly what I was looking for. 
I think I have the change done but I am having a hard time finding a way to include a test for the socket in the test suite. If it is not too much bother, do you have some advice?

**Comment by steve-chavez** [comment]
Closing since #1303 got this solved.
