### ISSUE TITLE
Consider supporting GRPC

### ISSUE THREAD

**Issue by just1689** [PostgREST/postgrest#1189]
### Consider supporting GRPC

A connection to be made to Postgrest and calls would be made over that connection. Removing the TCP connect time from the call could significantly reduce overhead and increase overall performance.

This would also allow for async responses rather than the blocking request/response pattern.

**Comment by michelp** [comment]
I presume you mean using grpc to call a postgres stored procedure.  I'm not a maintainer so you don't have to worry about my consideration, but I do have some thoughts on the idea.  Postgrest is about REST and the mapping of CRUD semantics from REST to SQL.  It does have an rpc feature but it blends with the REST pattern fairly well and much of what postgrest does is http specific (like setting headers in the config per-request).

It's totally valid to want to call a stored procedure from grpc, but it seems like something that would be possible using a simple service proxy that takes a grpc call and turns it into `PQexecParams` (or whatever the equivalent in your language binding to libpq is) using whatever grpc specific authentication token to verify and set the role.

As for async, there are asynchronous http clients in most languages where a callback (or continuation) is called/resumed when the server has sent the response.  So you can do this now with http.  The client blocking for the response is an implementation detail of the client, not the server, postgres will always block a database connection while it runs a query.

**Comment by michelp** [comment]
Here's some interesting ideas similar to what you're asking:

https://github.com/mustafaakin/gopqgen

https://github.com/otoolep/go-grpc-pg

**Comment by just1689** [comment]
Thanks @michelp 

Apologies, I was thinking in a different direction. I would like to call Postgrest over GRPC it's regular table api. I had not considered Stored Procs etc.

For me it's more about reducing connection time. Opening a TCP connection is terribly expensive and chatty. At the same time, Postgrest makes a remarkably robust pg driver.

My thinking was more along the lines of:

Connect once

- Send request
- Received response
- Repeat arbitrarily 1000s times over

Disconnect on redeploy

Another way to describe it would be - I love Postgrest's API but would like to talk over GRPC instead of HTTP.

Thanks for sharing those links. I am tempted to take a crack at this myself.

Cheers
