### ISSUE TITLE
Feature Request: running GET requests in read/write transactions

### ISSUE THREAD

**Issue by leondutoit** [PostgREST/postgrest#1194]
### Environment

* PostgreSQL version: 10.5
* PostgREST version: 0.5.0.0
* Operating system: Mac OS High Sierra

### Description of issue

I have a table with a couple of row level security rules. One of them updates an audit table each time a successful select is performed. `postgrest` runs all GET requests in read-only transactions which prevents insert statements, so the GET request to the table fails. 

A suggestion to solve this problem has been to access the table via a wrapper function, but imho that is not exposing a very clean API.

Is it conceivable to allow GET requests in read/write transactions? Perhaps via a config option?

**Comment by ruslantalpa** [comment]
a better way to do this is at the proxy level
https://github.com/openresty/lua-nginx-module#log_by_lua

**Comment by ruslantalpa** [comment]
i don't see the problem with openresty since you anyway should have nginx in front nad openresty is nothing more then nginx + a lua module.
sure technically it's possible to implement this, but pg tries to follow the http semantics, and GET means no changes (read only)

**Comment by leondutoit** [comment]
I doubt that I can re-implement the audit log at the proxy level, since it contains data stored in the table, and is only updated when the row level security rule returns true. And even if it were possible I would not want to expose that data outside of the db.

I really don't mean to split hairs here, but does pg need to care that there is a side effect? It is still read-only on the resource being queried, so the GET semantics remain intact.

**Comment by ruslantalpa** [comment]
i understand the first part of your post and why nginx is not a ideal fit in this case (you'd have to inspect the result then log the row ids back) 
about the second part, it's read only because you "think of it" that way and you only update a log table, but just as well you could have changed the data itself if pgrst were to not enforce the readonly transaction.
i guess what i am saying is your particular usecase has to ignore the standard a bit (and that's not by default bad) but there are benefits in following them in a general purpose tool (maybe you could fork and change the lines to have all your transactions read/write)

**Comment by ruslantalpa** [comment]
specifically this function
https://github.com/PostgREST/postgrest/blob/27ca6b4e90b1f4a5d4550a8f049930109c93240d/src/PostgREST/App.hs#L105-L117

**Comment by leondutoit** [comment]
Right, I understand your point of view. Do you think it is feasible to set the transaction mode from a run-time config param, so that if I were to fork it, the fork would not diverge too much? (I do not have experience writing Haskell :))

**Comment by leondutoit** [comment]
Or I guess simply replacing `HT.Read` with `HT.Write` would be simple enough. Anyways, thanks for the discussion, feel free to close the issue.

**Comment by ruslantalpa** [comment]
writing the code for a confing param will me much harder. changing just that function will be easier and should have no problems (it's very unlikely the function will change)

**Comment by ruslantalpa** [comment]
👍

**Comment by eric-brechemier** [comment]
> A suggestion to solve this problem has been to access the table via a wrapper function, but imho that is not exposing a very clean API.

@leondutoit using only NGINX (not OpenResty), you can transparently access this function from a `GET` request instead of `POST`. Here is an example:

```
# publish /heartbeat as a GET API endpoint
location = /heartbeat {
  limit_except GET HEAD {
    deny all;
  }
  proxy_pass http://localhost:3000/rpc/heartbeat;
  proxy_method POST;
  proxy_set_header 'Content-Type' 'application/json';
  proxy_set_body '{}';
}
```

That is probably the simplest course of action in your case.

**Comment by ruslantalpa** [comment]
@eric-brechemier this solution only works for rpc functions, i don't think it works with regular endpoints

**Comment by eric-brechemier** [comment]
@ruslantalpa yes, I wrote this in the context of "[accessing] the table via a wrapper function".
