### ISSUE TITLE
 Explicit qualification issues, add extra config param for extensions schema

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#1200]
We had some issues with [Explicit qualification](http://postgrest.org/en/v5.1/api.html#explicit-qualification) lately: 

- PostGIS functions/types calls https://github.com/PostgREST/postgrest/issues/1125 (solvable by adding search_path)
- ltree operators https://github.com/PostgREST/postgrest/issues/1183 (solvable by adding extension to `pg_catalog` or wrapping access in a function)
- [Heroku postgres issue](https://help.heroku.com/OZ4RPNQS/how-do-i-resolve-function-get_xmlbinary-does-not-exist-errors-in-heroku-connect) reported on gitter (no option but to downgrade to v0.4.4.0)

Now, let's assume https://github.com/PostgREST/postgrest/issues/1106 is implemented. Users would do `db-schema = public, api` and this would solve the above issues without workarounds. But this would also have the unwanted side effect of exposing all the extensions(postgis, ltree, etc) internals. So I think that feature is not the solution, unless later we add a config for hiding a schema but this seems too complicated.

So, how about if instead we add an extra config param(say `db-ext-schema`) for an additional extension schema that only gets added to the `search_path` that PostgREST sets but doesn't get exposed?(we keep qualifying all db objects with the `db-schema`, like `api.table`, so is not possible to access `public.internal` through `GET /internal`)

This `db-ext-schema` would be `public` by default so most workflows will continue to work as usual.

Thoughts? Any feedback would be appreciated.

(Also considered just dropping the `set schema` change and not mess with the `search_path` but then we would have https://github.com/PostgREST/postgrest/issues/828 again)

**Comment by steve-chavez** [comment]
There was also a comment regarding `citext` problems on gitter chat. This limitation is really inconvenient so I'm going to go ahead and add the extra config.

**Comment by ruslantalpa** [comment]
another option would be, instead of introducing a new param, to have something like
`db-schema=api,public` where only the first schema is exposed, the others are added to the search path
but I am not sure if this is better or worse ...
for your option I would suggest naming the config param `db-search-path` with the default to `public`

**Comment by steve-chavez** [comment]
Thanks for the feedback Ruslan.

I'm thinking of reserving `db-schema` for only exposing schemas and to have more than one there when #1106 is completed, also seems error prone to depend on the order.

Could be confusing to have `db-search-path` when `db-schema` also adds it's contents to the `search_path` and also suggests you can add more than one schema there. The real issue here is about extensions and most users have that under `public` or a dedicated [extensions](https://stackoverflow.com/questions/12986368/installing-postgresql-extension-to-all-schemas/43937189#43937189) schema. I think it'll be better to be strict for now and only allow one schema there.

The best name I can come up for the setting is `db-extensions-schema` for now.

**Comment by ruslantalpa** [comment]
The new confing SHOULD allow adding more then one schema, the default being only public. The db-schema param shoul not be added to the searchpath since the entities are qualified (i think) so db-search-path makes sense since that is exactly what it is ‘controlling’

**Comment by steve-chavez** [comment]
If the `db-schema = api` is not added to search_path the computed columns added in `api` will not work, plus user would have to add `api` search_path's to all exposed functions, which is not reasonable since it's already exposing `api`, I'm sure other things probably will fail(custom operators?). I'd say the `db-schema` MUST be included in the search_path.

What use cases you have in mind for more than one schema in the new config param? I would not be opposed to this but I think only an extension schema is needed, also if we allow this a new name would be needed, perhaps `extra-search-path`?

**Comment by ruslantalpa** [comment]
Functions in the api schema do not rederence other functions there since all of them are ‘endpoint’ functions, not utility functions, computed columns ... have to look into that ... anyway, the need for the api schema in the search path is minimal, but its ok to add it to the searchpath as it is now and db-extra-search-path seems sugestive enough. 

Support for multiple schemas is just natural, it comes from how that db setting works, making it a single schema would be odd/counter intuitive
