### ISSUE TITLE
Integrate 3rd party authentication systems

### ISSUE THREAD

**Issue by itaied246** [PostgREST/postgrest#1201]
How can I integrate 3-rd party authentication systems?
I'm using firebase authentication to authenticate the users (through email and password / 3rd party provider).

Firebase don't give me a secret key, instead it is a complex JSON which can be validated using an `sdk`.

How do you think it is possible to integrate those two?

**Comment by michelp** [comment]
I have not tried this, but you could try writing a `pre-request` function in javascript using plv8, then you can use the firebase sdk in that function to do the access control check.

See http://postgrest.org/en/v5.0/install.html#configuration
