### ISSUE TITLE
db-uri param from file

### ISSUE THREAD

**Issue by msalvadores** [PostgREST/postgrest#1203]
`jwt-secret` can already be read from a file, it would be great to also enable this for the `db-uri` using the `@/path/to/file` notation. 

This feature request was suggested as part of PR #1198

**Comment by steve-chavez** [comment]
Should be a simple change. If you're willing to give it a shot, the logic for loading the secret for `jwt-secret` is [here](https://github.com/PostgREST/postgrest/blob/master/main/Main.hs#L262-L264), then you could add a [bash test](https://github.com/PostgREST/postgrest/blob/master/test/io-tests.sh#L176) similar to the ones used for `jwt-secret`.

Or you could make a small [donation](https://github.com/PostgREST/postgrest#supporting-development) and then I'll implement it myself :)

**Comment by msalvadores** [comment]
@steve-chavez  Thanks for the pointers to give it a shot. It will take some time to get to it but  I will see what I can do given that barely know any haskell.

**Comment by steve-chavez** [comment]
Already implemented in #1215 :).

**Comment by msalvadores** [comment]
Thanks!
