### ISSUE TITLE
postgREST doesn't work with PostgreSQL 32bit

### ISSUE THREAD

**Issue by veronika0693** [PostgREST/postgrest#1207]
### Environment

* PostgreSQL version: 9.5(32bit) 
* PostgREST version: 5.1.0
* Operating system: Win10 (64 bit)

### Description of issue
PostgreSQL 9.5(32 bit) have been installed on my computer, now i need to get DB data through http. I try to use PostgREST, but when i try to run it i have an error "Application can be running. Error 0xc000007b". I checked in my system all paths in environment variables and all system updates...

**Comment by veronika0693** [comment]
I use one more application, which needs PostgreSQL 32bit, that's why i can't upgrade it to 64bit.

**Comment by steve-chavez** [comment]
Closing until feedback is given, will reopen then.
