### ISSUE TITLE
filter on 2 criterias inside a json array

### ISSUE THREAD

**Issue by mgmgh** [PostgREST/postgrest#1213]
Hello,
I am looking for the right syntax do filter rows on *2* criterias inside an array.
Given this set of data (a list of movies):
  {
    "id": 123456,
    "original_title": "The title",
    "prod_year": 2017,
    "prod_countries": [
      {
        "iso": "DE",
        "order": 1,
        "is_eur_coe": true,
        "is_eur_eur": true
      },
      {
        "iso": "US",
        "order": 2,
        "is_eur_coe": false,
        "is_eur_eur": false
      }
    ]
}

I know that I can filter on an iso code with:
prod_countries=cs.[{"iso":"DE"}]

But how can I add a second ANDed filter ?
I want only the movies for country iso code='DE' and order=1
If I test with:
prod_countries=cs.[{"iso":"DE"},{"order":1}]
then all movies with order=1 (with any iso!) are also retrieved (it's an OR, not an AND !)
The same if I combine the 2 criterias with postrest's "and syntax" :-(

I use pg v10 and postgrest 5.1.0

**Comment by steve-chavez** [comment]
Does `order` represent the position of the value in the json array? If so maybe you use the [arrow operators](http://postgrest.org/en/v5.1/api.html#json-columns) like:
```http
GET /movies?prod_countries->0->>iso=eq.DE
```

**Comment by mgmgh** [comment]
In my sample, yes, it's an order for countries.
A film can be co-produced in/by many countries and here, I want to get films where the main (order==1) producing country is 'DE'.
But in reality (I simplified the returned json), I can't target a given element by its numeric index.
Each "main" object returned can have a liste of multiple attributes ("setof rows" in each row).
I tried to filter on my view directly in sql with no success, it seems that postgres[rt] doesn't have an operator for this :-(

**Comment by ruslantalpa** [comment]
By any chance, are those subobjects the result of “related objects” using the select parameter, i.e. the result you pasted does not come from a single view?

If they come from 2 views then you wont be able to filter like you want.

If they come from one view then you can try entering the same column/parameter twice like:
thecol=cs.xxx&thecol=cs.yyy

Notice it’s the same ‘thecol’

Check with your frontend lib if its able to sens the same get parameter twice with different values

**Comment by steve-chavez** [comment]
PostgreSQL 12 will add more powerful JSON path expressions https://www.postgresql.org/docs/12/functions-json.html.
