### ISSUE TITLE
not an issue - portability of this solution to other RDBMSs, like Oracle and Microsoft SQL Server

### ISSUE THREAD

**Issue by luciancapdefier** [PostgREST/postgrest#1214]
Hi all, I recently found this solution and find it very useful and interesting, congrats for taking it to this level!

My interest lies in understanding if there are similar solutions for other RDBMSs (Oracle and Microsoft SQL Server being of interest), or if this solution can consider a road-map in which several RDBMS type are supported - i imagine it wouldn't be difficult to isolate the specificity of Postgresql and replace it with any other (SQL statements for CRUD operations tent to be standard).

Thank you,

**Comment by steve-chavez** [comment]
There are no plans for supporting other RDBMSs. As mentioned by michelp, PostgREST is tightly knit to PostgreSQL and porting would require significant effort(feasible, but not without funding or perhaps a commercial version).

Now, there are [foreign data wrappers](https://wiki.postgresql.org/wiki/Foreign_data_wrappers) for both [SQL Server](https://github.com/tds-fdw/tds_fdw) and [Oracle](https://github.com/virtdb/virtdb-fdw). You could connect those RDBMSs to PostgreSQL and then expose a REST API with PostgREST as usual.

**Comment by steve-chavez** [comment]
Moving this to postgrest-docs https://github.com/PostgREST/postgrest-docs/issues/223.

**Comment by steve-chavez** [comment]
Just uploaded an old project of mine that implements a PostgREST-like api for MS SQL Server: https://github.com/steve-chavez/mssqlREST. Not suited for a public API, but could serve as a guide to implementing your own solution. The [auth](https://github.com/steve-chavez/mssqlREST#authentication) section might be of interest.
