### ISSUE TITLE
Order filter with in subqueries.

### ISSUE THREAD

**Issue by Srikanth4** [PostgREST/postgrest#1217]
### Environment

* PostgreSQL version: (if using docker, specify the image)
* PostgREST version:5.1
* Operating system: Windows

### I am trying to fetch data by doing two level sub queries: 
`/entertainment?select=*,actors(*, movies(*))&actors.order=last_name,first_name 
`
In this query, how can I sort / order movies based on title ?

expecting responsebody as:

```
entertainment: {
 actors: [
    name: 'abc',
    movies: [
                   {
                     a,
                   },{
                       b
                    }
                ]
          ]
    }
```

**Comment by steve-chavez** [comment]
As Ruslan mentioned it'll be like:
```http
GET /entertainment?select=*,actors(*, movies(*))&actors.movies.order=title 
```
