### ISSUE TITLE
postgrest error on rpc call to a function uses geomerty

### ISSUE THREAD

**Issue by rrguez** [PostgREST/postgrest#1220]
### Environment

* PostgreSQL version: (if using docker, specify the image)
* PostgREST version: (if using docker, specify the image)
* Operating system:

### Description of issue

(Expected behavior vs actual behavior)

(Steps to reproduce: Include a minimal SQL definition plus how you make the request to PostgREST and the response body)

**Comment by steve-chavez** [comment]
Try the latest version https://github.com/PostgREST/postgrest/releases/tag/v5.2.0, it should fix your problem.

**Comment by steve-chavez** [comment]
Considering this resolved. Reopen if not.
