### ISSUE TITLE
OpenApi not showing GET method for immutable functions

### ISSUE THREAD

**Issue by apanagio** [PostgREST/postgrest#1222]
### Environment

* PostgreSQL version: "PostgreSQL 11.1 (Ubuntu 11.1-1.pgdg18.10+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 8.2.0-7ubuntu1) 8.2.0, 64-bit"
* PostgREST version: 5.1.0 (3cef4b7)
* Operating system: ubuntu linux 18.10

### Description of issue

I have an immutable function that i can call with the get method. However the GET method doesn't show up within the openapi specification (using swagger-ui)

here is the declaration of the function:
```
CREATE OR REPLACE FUNCTION public.whoami(
	)
    RETURNS name
    LANGUAGE 'sql'

    COST 100
    IMMUTABLE STRICT 
AS $BODY$select current_user$BODY$;

**Comment by maxwell-clarke-intranel** [comment]
I am also having this issue

**Comment by steve-chavez** [comment]
Thanks for the report. Actually GET is not being showed for any function. [Here](https://github.com/PostgREST/postgrest/blob/master/src/PostgREST/OpenAPI.hs#L237) is why RPCs are only showing POST, we would need to add GET in a way similar to [this](https://github.com/PostgREST/postgrest/blob/master/src/PostgREST/OpenAPI.hs#L215).
