### ISSUE TITLE
OpenAPI: Incorrect externalDocs URL

### ISSUE THREAD

**Issue by necab0** [PostgREST/postgrest#1223]
### Environment

* PostgreSQL version: 9.5.15
* PostgREST version: 5.1.0 (3cef4b7)
* Operating system: Ubuntu 16.04.2 LTS (Vagrant)

### Description of issue

Since the v5.1 release of PostgREST the generation of OpenAPI's [externalDocumentationObject](https://swagger.io/specification/#externalDocumentationObject) URL field seems to be broken. 

Expected OpenAPI spec:
```json
{
    "swagger": "2.0",
        "info": {
            "version": "5.1.0 (3cef4b7)",
        },
        "externalDocs": {
            "url": "https://postgrest.org/en/v5.1/api.html",
            "description": "PostgREST Documentation"
        }
}
```

Actual OpenAPI spec:
```json
{
    "swagger": "2.0",
        "info": {
            "version": "5.1.0 (3cef4b7)",
        },
        "externalDocs": {
            "url": "https://postgrest.org/en/v1/api.html",
            "description": "PostgREST Documentation"
        }
}
```

### Additional information:
This is also the case for today's `v5.2` release (I chose `v5.1` for this issue because the documentation for `v5.2` does not seem to be available at `https://postgrest.org/en/v5.2/api.html` yet).
My uneducated guess is this being an issue with the change of the versioning scheme i.e. `0.5.0.0` --> `5.1.0`.

For comparison purposes, here is the correctly generated output when using `v5.0`:
```json
{
    "swagger": "2.0",
        "info": {
            "version": "0.5.0.0 (903a8d5)",
        },
        "externalDocs": {
            "url": "https://postgrest.org/en/v5.0/api.html",
            "description": "PostgREST Documentation"
        }
}
```

Related issue that might be helpful in tracking this down: #933

**Comment by steve-chavez** [comment]
Thank you for the thorough report. I think the fix is to correct this function https://github.com/PostgREST/postgrest/blob/master/src/PostgREST/Config.hs#L114-L115. Then a test on https://github.com/PostgREST/postgrest/blob/master/test/Feature/StructureSpec.hs would clear this out.

**Comment by marfel** [comment]
Bug still persists for release v5.2.0. Please fix this, I feel stupid presenting the swagger UI to external users like this...

**Comment by steve-chavez** [comment]
Fix already merged in master, if the fix is needed right away you can [build from source](http://postgrest.org/en/v5.2/install.html#build-from-source).

Consider [supporting PostgREST development](http://postgrest.org/en/v5.2/#supporting-development) if you wish quicker bug fixes.
