### ISSUE TITLE
select in GET api unexpectedly exposure column

### ISSUE THREAD

**Issue by TonnyLTP** [PostgREST/postgrest#1224]
### Environment

* PostgREST version: PostgREST 5.2.0 (1e732ac)
* Operating system: Mac

### Description of issue

From http://postgrest.org/en/v5.1/api.html#resource-embedding, select with foreign key is very useful to find data, but unexpectedly exposure some important columns.

GET /books?select=users(password)

What's the best way to hide columns? here a VIEW with limited columns is not enough. using Nginx to watch the parameters?

**Comment by ruslantalpa** [comment]
It’s not about hiding the columns, it’s about setting the correct permissions.
In your example, the user making the request should not have select privilege to the password column.
He will be able to access that url but the response will be an error/access denied.

**Comment by steve-chavez** [comment]
As Ruslan mentioned you only need to grant column privileges, like:
```sql
GRANT SELECT(id, full_name) on users TO web_user -- doesn't include the password col
```

**Comment by steve-chavez** [comment]
The GRANT should fix your problem. Considering this resolved.
