### ISSUE TITLE
Enhancement: Function to expose database / table model

### ISSUE THREAD

**Issue by cpheimbach** [PostgREST/postgrest#1226]
### Environment

* PostgreSQL version: 10+
* PostgREST version: docker-compose: postgrest/postgrest
* Operating system:

### Description of issue

I find it silly to have to rewrite the database layout / model when building an admin frontend because IMHO that's already done when the tables were defined. Maybe this is naive but my ambition is to offer a SQL function that enables an autogenerated form for each table/endpoint. I'd like to propose the following gist for a review for the community: 

https://gist.github.com/cpheimbach/9de745cfb95222f8e218ec7aba8c1d57

Let me know if that's a valuable approach and if you are interested to integrate this or mention it for the project. 

Apologies if that here is the wrong place to discuss. I'm happy to move the conversation where it best suits.

**Comment by steve-chavez** [comment]
We do have queries for getting the schema metadata in [DbStructure](https://github.com/PostgREST/postgrest/blob/master/src/PostgREST/DbStructure.hs) and some of this info is exposed at the root url(`GET /`) , the output is in OpenAPI JSON format.

Now, the problem with that format is that is not easily consumable. We used to have a raw JSON output up until [v0.3.2.0](https://github.com/PostgREST/postgrest/releases/tag/v0.3.2.0). I think the best would be to bring back that format, this is already being discussed at #790.
