### ISSUE TITLE
FreeBSD port

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#1227]
Doing manual releases gets tedious quickly(also my FreeBSD disk partition got damaged recently, cannot boot into it :crying_cat_face:). 

We could try to automate FreeBSD releases with [Cirrus CI](https://cirrus-ci.org/), which recently announced support for FreeBSD https://forums.freebsd.org/threads/cirrus-ci-free-freebsd-ci-testing-for-open-source-projects.68560/.

**Comment by steve-chavez** [comment]
Made some progress on this at https://github.com/steve-chavez/postgrest/blob/cirrus-2/.cirrus.yml

Unfortunately the updated GHC broke the build again. I'm leaving the link here in case someone wants to pick it up.

**Comment by steve-chavez** [comment]
It would be even better if someone can help creating a FreeBSD port. There was an [initiative](https://twitter.com/postgrest_org/status/1189898706826473472) but it didn't got finished.

**Comment by dwagin** [comment]
Main problem FreeBSD ports don't support building via stack, it support only cabal.
But my attempts compile from sources using cabal = failed.

**Comment by steve-chavez** [comment]
@dwagin Oh, I didn't know that. Maybe the archlinux package PKGBUILD can be of help: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/postgrest. Looks like it only uses `runhaskell`.

**Comment by steve-chavez** [comment]
@dwagin Building with cabal is now possible!

I've added a CI for FreeBSD that has the steps to build postgrest. See here: https://github.com/PostgREST/postgrest/blob/master/.cirrus.yml#L30-L34.

The CI will also ensure that we keep building successfully on FreeBSD.

It'd be great if you could help us with a FreeBSD port!

**Comment by dwagin** [comment]
@steve-chavez I think I'm making some progress.
Which architectures are suitable for postgrest? i386, amd64?

**Comment by dwagin** [comment]
[hs-postgrest-7.0.0.log](https://github.com/PostgREST/postgrest/files/4606749/hs-postgrest-7.0.0.log)

**Comment by steve-chavez** [comment]
@dwagin Great news!

I think amd64 would be good enough.

In case you're wondering, here's a complete list of what platforms GHC supports: https://gitlab.haskell.org/ghc/ghc/-/wikis/platforms.

**Comment by dwagin** [comment]
[FreeBSD Bugzilla – Bug 246383 Submitted](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246383).

**Comment by steve-chavez** [comment]
@dwagin Nice! Let me know when the patch is merged and I'll include the FreeBSD port on the install page: http://postgrest.org/en/v7.0.0/install.html.

**Comment by dwagin** [comment]
Hi @steve-chavez, hs-postgrest ([FreshPorts](https://www.freshports.org/www/hs-postgrest)) commited.

**Comment by steve-chavez** [comment]
@dwagin Awesome! I'll add that to the install docs!

The command would be `pkg install hs-postgrest` right?

**Comment by dwagin** [comment]
> The command would be `pkg install hs-postgrest` right?

Yes

**Comment by steve-chavez** [comment]
@dwagin Added `hs-postgrest` to the [install page](http://postgrest.org/en/v7.0.0/install.html#installation)!
