### ISSUE TITLE
Wrong HTTP status code returned for GET request with selecting count and "Prefer: count=exact" header set

### ISSUE THREAD

**Issue by temni** [PostgREST/postgrest#1231]
### Environment

* PostgreSQL version: 10.5
* PostgREST version: PostgREST 5.1.0
* Operating system: CentOS Linux 7 (Core)

### Description of issue
In request I am trying to select the count of rows in a table.
I also pass the header "Prefer: count=exact".
Response code is HTTP/1.1 206 Partial Content.
Array of the single  element is being returned.

$ curl  -v "http://localhost:3000/event?select=count" -H "Prefer: count=exact"
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /event?select=count HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.57.0
> Accept: */*
> Prefer: count=exact
>
< HTTP/1.1 206 Partial Content
< Transfer-Encoding: chunked
< Date: Fri, 18 Jan 2019 15:41:19 GMT
< Server: postgrest/5.1.0 (UNKNOWN)
< Content-Type: application/json; charset=utf-8
< Content-Range: 0-0/22140
< Content-Location: /event?select=count
[{"count":22140}]

If I omit this header everything is ok:
curl  -v "http://localhost:3000/event?select=count"
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /event?select=count HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.57.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Date: Fri, 18 Jan 2019 15:44:30 GMT
< Server: postgrest/5.1.0 (UNKNOWN)
< Content-Type: application/json; charset=utf-8
< Content-Range: 0-0/*
< Content-Location: /event?select=count

(Expected behavior vs actual behavior)
I expect this header to not influence the response code because the only element is always expected.

**Comment by wolfgangwalther** [comment]
We are translating our request properly to SQL, but this is just how postgres works. I don't think this is a bug.

I also fail to see what we could do about this. Preventing this is nearly impossible, because a user could define their own real or computed column `count`, so we must allow that.

We already have documentation in place on how to receive counts.

**Comment by temni** [comment]
@wolfgangwalther @steve-chavez  thanks for your replies, yes, we have changed our system's behavior accordingly.
