### ISSUE TITLE
Ignore extra information on JSON

### ISSUE THREAD

**Issue by allochi** [PostgREST/postgrest#1234]
### Environment

* PostgreSQL version: 11.1
* PostgREST version: 5.1
* Operating system: Debian 8 and MacOS 10.14

### Description of issue

I'm not sure if this has been raised before, I tried my best to find out but couldn't find anything.

I wonder if there is a header that tells PostgREST to ignore any extra properties in a json that doesn't match the table columns, and continue the INSERT or UPDATE with the matching ones.

PostgREST usual those and returns an error as its default behaviour, that is the correct behaviour, but in some cases, we may need to use the matching properties, ignore the rest, and continue executing the INSERT or UPDATE.

For example, in my current project I have a table similar to this:
```sql
create table datasets(
  id serial primary key,
  source text,
  publication_date timestamp,
  figure bigint
)
```

I allow data from multiple sources to be stored in this table, each source may have some extra fields that I don't want, for example:
```json
{
  "source": "Natural Disaster Prevention and Control (NDPC)",
  "publication_date": "...",
  "figure": 1100,
  "location": "...",
  "comment": "...",
  "lat": "...",
  "lon": "...",
}
```

Usually, if it was few records, I would clean up the data and reformat it, but in my case I have thousands of records coming from hundred of different sources in different formats.

Thanks in advance.

**Comment by steve-chavez** [comment]
I made a proposal for https://github.com/PostgREST/postgrest/issues/690#issuecomment-378363946 that would also solve your problem. With that you could use a `columns` query arg for specifying INSERT columns and ignore the rest:

```http
POST /datasets?columns=source,publication_date,figure
```

**Comment by steve-chavez** [comment]
@allochi If you're interested in prioritizing this feature, you could consider sponsoring development(see our our new [Patreon tiers](https://www.patreon.com/postgrest))

**Comment by steve-chavez** [comment]
RPC ignoring keys not in the function arguments is a code side-effect that could change in new releases. I recommend using the new `?columns` query arg whenever you want to make sure extra keys are ignored.
