### ISSUE TITLE
smallint gets the string in OpenGraph API description

### ISSUE THREAD

**Issue by Rembane** [PostgREST/postgrest#1238]
### Environment

* PostgreSQL version: 11.1
* PostgREST version: 5.2.0 (1e732ac)
* Operating system: `Linux FancyHostname 4.20.6-arch1-1-ARCH #1 SMP PREEMPT Thu Jan 31 08:22:01 UTC 2019 x86_64 GNU/Linux`

### Description of issue

The format `smallint` gets type `string`, but it should get type `integer`. This bug occurs in the API in the API description. In the actual API it works fine.

### How to reproduce

Use this sql code: 
```sql
CREATE TABLE smallint_test (
    some_number smallint
);
```

Using the defaults in the config go to: http://localhost:3000/

The response should be contain this: 
```json
{ "smallint_test":{"properties":{"some_number":{"format":"smallint","type":"string"}},"type":"object"} }
```

Do especially note `"type":"string"` for `some_number`, where it should be `"type":"integer"` instead.

**Comment by steve-chavez** [comment]
Same thing occurs for `double precision`, it would be a matter of adding more lines to this function https://github.com/PostgREST/postgrest/blob/master/src/PostgREST/OpenAPI.hs#L36-L41
