### ISSUE TITLE
Feature Request: Materialized view inspection / resource embedding

### ISSUE THREAD

**Issue by bolerodan** [PostgREST/postgrest#1239]
### Environment

* PostgreSQL version: 11
* PostgREST version: 5.2.0
* Operating system: Linux

### Description of issue

The ability to have Postgrest inspect Materialized Views, so that one could resource embed much like regular views can now. 

@steve-chavez in Gitter mentioned the following

> c.relkind in ('v', 'm') to our query https://github.com/PostgREST/postgrest/blob/master/src/PostgREST/DbStructure.hs#L722

**Comment by vitorbaptista** [comment]
@bolerodan @steve-chavez Any updates on this? Is this just a one-line change (plus some tests I imagine), or is there something else I'm missing?

**Comment by steve-chavez** [comment]
@vitorbaptista Yes, one line change plus tests.

If you're interested in a PR, you could reuse a fixture we have: 

https://github.com/PostgREST/postgrest/blob/1f513f24a58f77a3fc2b76f872aee50038a9a80d/test/fixtures/schema.sql#L1575-L1576

And then add the tests under this section:

https://github.com/PostgREST/postgrest/blob/1f513f24a58f77a3fc2b76f872aee50038a9a80d/test/Feature/QuerySpec.hs#L332

**Comment by bolerodan** [comment]
Just an update on this, I managed to change the line in dbStructure to have `c.relkind in ('v', 'm')`  and rebuilt it.

I can now see materialized views in the schema, and even query off them as the root table. Unfortunately I cannot seem to get embedding working. Infact it doesn't give me an error ,just an empty list in the embedded response, and I have no experience within Haskell (although I would love to learn).

**Comment by vitorbaptista** [comment]
@bolerodan As I'm currently blocked because of this issue, I took the liberty of sending a PR at https://github.com/PostgREST/postgrest/pull/1256.

**Comment by bolerodan** [comment]
Fantastic! Thanks! This greatly helps us too.
