### ISSUE TITLE
convert empty string to null

### ISSUE THREAD

**Issue by pixie79** [PostgREST/postgrest#1240]
Hi,

Would it be possible for postgrest to convert empty string values to null, (or have it as a configuration value) ?

Thanks

Mark

**Comment by steve-chavez** [comment]
This would be better handled at the db level, you can use pg [NULLIF](https://www.postgresql.org/docs/11/functions-conditional.html#FUNCTIONS-NULLIF) on empty strings in a BEFORE INSERT TRIGGER.

**Comment by steve-chavez** [comment]
We're trying to move away from processing the payload https://github.com/PostgREST/postgrest/pull/1241, so there are no plans for supporting this.

The TRIGGER is your best bet. Also more in line with the database as source of truth philosophy.
