### ISSUE TITLE
websearch_to_tsquery support

### ISSUE THREAD

**Issue by energyaccessexplorer** [PostgREST/postgrest#1243]
Starting on PostgreSQL 11 there is a new function `websearch_to_tsquery` (a combination of `{plain,phrase}to_tsquery`) See: [textsearch-controls](https://www.postgresql.org/docs/current/textsearch-controls.html#TEXTSEARCH-PARSING-QUERIES) and [textsearch](https://www.postgresql.org/docs/current/functions-textsearch.html#TEXTSEARCH-FUNCTIONS-TABLE)... at the end of the section and the 7th row, respectively.

This is yet not supported by PostgREST. Reference: [Types.hs](https://github.com/PostgREST/postgrest/blob/master/src/PostgREST/Types.hs#L237)

On the side: as temporary workaround, is there a way to "expose" those not-yet-implemented functions on the API without creating custom views?

Thank you!

**Comment by steve-chavez** [comment]
[Stored procedures](http://postgrest.org/en/v5.2/api.html#stored-procedures) is another option. But you could apply the following patch and generate a binary by [building from source](http://postgrest.org/en/v5.2/install.html#build-from-source).
```patch
diff --git a/src/PostgREST/Types.hs b/src/PostgREST/Types.hs
index 1325382..800e0e0 100644
--- a/src/PostgREST/Types.hs
+++ b/src/PostgREST/Types.hs
@@ -238,7 +238,8 @@ ftsOperators :: M.HashMap Operator SqlFragment
 ftsOperators = M.fromList [
   ("fts", "@@ to_tsquery"),
   ("plfts", "@@ plainto_tsquery"),
-  ("phfts", "@@ phraseto_tsquery")
+  ("phfts", "@@ phraseto_tsquery"),
+  ("wfts", "@@ websearch_to_tsquery")
   ]
 
 data OpExpr = OpExpr Bool Operation deriving (Eq, Show)
```
Then you could use `wtfs` as:
```http
GET /tsearch?text_search_vector=wfts.impossible%20or%20possible
```

**Comment by energyaccessexplorer** [comment]
@steve-chavez Yep! I already built it myself as `webfts`. (Now I'm learning how to re-compile it [offtopic]). Thank you!
