### ISSUE TITLE
handling the @ in the connection user

### ISSUE THREAD

**Issue by vbrinza** [PostgREST/postgrest#1244]
### Environment

* PostgreSQL version: 10
* PostgREST version: 5.1.0
* Operating system: Azure PostgreSQL

### Description of issue

I expect it to handle the usernames as provided by Azure PostgreSQL format 'username@hostname'.
Now to overcome this issue I have to use 'username%40hostname' instead.

Ex usage for Docker:
env:
- name: PGRST_DB_URI
  value: "postgres://username%40hostname:password@dns_name:5432/db_name"

**Comment by ruslantalpa** [comment]
not an issue, the connection string is a URI so it must obey some rules.
You are basically expecting something like `john@doe` to be a valid "name" for a email user, i.e. you want this email to be valid `john@doe@gmail.com` which it obviously is not, it's kind of the same thing with the connection string
and btw, this is not a PostgREST thing, this is the way connection string is specified for PostgreSQL, the client does not matter (try connecting with psql)

**Comment by steve-chavez** [comment]
Just to be clear here, `@` should be urlencoded as `%40` when used in the connection string.

PostgREST depends on `libpq`, which defines the structure of the connection URI here: https://www.postgresql.org/docs/12/libpq-connect.html#id-1.7.3.8.3.6.
