### ISSUE TITLE
KeepAlive

### ISSUE THREAD

**Issue by rastogi-nitin** [PostgREST/postgrest#1245]
### Environment

* PostgreSQL 9.6.9 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18), 64-bit
* postgrest-v0.5.0.0
* Operating system: Red Hat 4.4.7-18

### Description of issue

(Keep Alive)

(It appears like, to enable keepalive, the only option is, fronting the Postgrest with Nginx. We are making 1000s of call via scripted processes, and the connection is closed every time for a new call. Can we keep the connection alive any other way?)

**Comment by ruslantalpa** [comment]
are you sending a keep-alive header? 
post a detailed curl request with detailed http traffic output

**Comment by wolfgangwalther** [comment]
Since there was no feedback here and it has been a while I'm closing this.
