### ISSUE TITLE
add transaction id param to input

### ISSUE THREAD

**Issue by QiV** [PostgREST/postgrest#1246]
### Environment

* PostgreSQL version: any
* PostgREST version: latest
* Operating system: mac, linux

### Description of issue

Expected to have transaction id as an input param to any request. 

1. start a transaction outside of postgrest
2. pass the transaction id through any header (eg X-TransactionID: XXXX)
3. do not start a new transaction inside postgrest.

Optionally it would be great to think about a rollback to savepoint functionality through header too(eg X-SAVEPOINT: XXXX)

**Comment by steve-chavez** [comment]
What's the motivation for this feature?

**Comment by QiV** [comment]
Motivation is to use postgrest as an underlying api layer for the backend.
```js
const {transactionID} = await db.query('BEGIN')
try {
  const someResultsFromDB = await db.query('INSERT/UPDATE/DELETE as superuser')
  ... lots of logic
  const anotherResults = await postgrest('POST', 'users', params, {jwt, transactionID})
  ... lots of logic
  await db.query('COMMIT')
} catch (e) {
  await db.query('ROLLBACK')
}
```

my point is to let postgrest to execute the code under specific transaction

**Comment by steve-chavez** [comment]
@QiV If you already have a connection to the database why go through PostgREST? In your example you can just change the POST for an INSERT.

**Comment by QiV** [comment]
you are right, i can just make a dumb insert/select, but i want to use postgrest for sugar: setting local vars, switching roles, aggregating  joins into jsons with columns names.
without postgrest i have to wrap my queries with extra statements, but the aim is to write less code and get more efficient result.
when i`m writing something like this just to get the same result as just hitting /rest/users/2
```sql
WITH pg_source AS ( select * from api._users($1) WHERE id=$2 )
SELECT coalesce(json_agg(_postgrest_t),'[]')::character varying AS body
FROM ( SELECT * FROM pg_source) _postgrest_t
```
i have a strong feeling that i`m doing something wrong... api._users is just a function to reflect api.users view, but with argument instead of request.user_id()

I like postgrest, but without transactions it does not seem to be a solution for production(

**Comment by steve-chavez** [comment]
> I like postgrest, but without transactions

PostgREST already opens a transaction for you. Instead of opening another connection to the db in js why don't you just create a stored procedure that does all the operations you want to do?

You can even code your stored procedure in js with https://plv8.github.io

Also have a look at https://github.com/PostgREST/postgrest/issues/286.

**Comment by QiV** [comment]
thanks for plv8!) I'll give it a try.
actually i wrote procedures and i was happy with them, but every time i had to change any logic inside it - it was a pain( i don't have any free instruments for debugging psql, and for me, as a frontend developer, it is super challenging. the only way for me was writing pgtap tests, but they don't cover cases when you don't have enough expertise in sql at all( that was a reason, i moved the code to higher level to get more simple debugging.

**Comment by steve-chavez** [comment]
plv8 is your best bet. Leaving transactions open to the client raise many concerns for me(locking, bad perf, etc) so I don't think this can be supported. SAVEPOINT would also be better handled with stored procs.

Also, another option if you want to copy part of postgrest transaction logic, by enabling [pg logging](http://postgrest.org/en/v5.2/admin.html#database-logs) you can get the SET LOCALs(which are few) that postgrest does.
