### ISSUE TITLE
Embed resource from another schema table

### ISSUE THREAD

**Issue by fusionbeam** [PostgREST/postgrest#1247]
### Environment

* PostgreSQL version: postgres:11 (docker)
* PostgREST version: postgrest/postgrest:v5.2.0
* Operating system: MacOS

### Description of issue

Perhaps this is more a feature request than a bug.
I've noticed that Postgrest gives a 'No relationship found error' if a foreign key references a table from another schema. 
Is Postgrest any close to support this feature? I am aware that it would imply to load the schema of the referenced table and so on. Still, maybe if the embedding url specified the embedded columns this would be an easy addition.

Thanks.

**Comment by steve-chavez** [comment]
This already works. Create a view of the table in the unexposed schema in your `api` schema. Example:

```sql
create table private.people(
  id int primary key,
  name text
);
insert into private.people values(1, 'Pedro');

create table api.details(
  id int,
  phone text,
  person_id int references private.people(id)
);
insert into api.details values(1, '888-8888', 1);

create view api.people as
select id, name from private.people;

curl  "http://localhost:3000/details?select=id,phone,person:people(id,name)"
[{"id":1,"phone":"888-8888","person":{"id":1,"name":"Pedro"}}]
```

**Comment by BrandonChubb** [comment]
I think you wanted:
curl 'http://localhost:3000/details?select=id,phone,private:people(id,name)'
(not person:people but private:people)

**Comment by BrandonChubb** [comment]
What does the "person" accomplish in this example curl command "person:people"?  Is a colon and period interchangable in this situation?

**Comment by steve-chavez** [comment]
@BrandonChubb In that case person is just an alias. Not interchangeable with a period since that's used for the feature introduced in https://github.com/PostgREST/postgrest/pull/918

**Comment by steve-chavez** [comment]
Moving the issue to docs https://github.com/PostgREST/postgrest-docs/issues/219.
