### ISSUE TITLE
Swagger ui fails to load application on AWS

### ISSUE THREAD

**Issue by monemihir** [PostgREST/postgrest#1248]
### Environment

* PostgreSQL version: 10.0
* PostgREST version: docker image = postgrest/postgrest:latest
* Operating system: Ubuntu 18.04 x64

### Description of issue

I am running in AWS with a public load balancer fwding back to the postgrest instance

I am using the docker-compose file as mentioned in the documentation. However, the swagger ui always fails to load with a CORS error.

```
Errors
Hide
 
Fetch error
Failed to fetch http://localhost:3000
Fetch error
Possible cross-origin (CORS) issue? The URL origin (http://localhost:3000) does not match the page (<actual url removed for privacy>). Check the server returns the correct 'Access-Control-Allow-*' headers.
```

If I then manually copy the actual url (i.e the public facing url) into the bar at the top of the page and click "Explore" it works again.

Looking at the `curl` response by querying from localhost I get this from the swagger url

```
ubuntu@testvm:~/postgrest$ curl -I http://localhost:8080
HTTP/1.1 200 OK
Server: nginx/1.15.8
Date: Tue, 26 Feb 2019 03:25:37 GMT
Content-Type: text/html
Content-Length: 1435
Last-Modified: Tue, 26 Feb 2019 03:25:24 GMT
Connection: keep-alive
ETag: "5c74b1a4-59b"
Expires: Wed, 27 Feb 2019 03:25:37 GMT
Cache-Control: max-age=86400
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type
Accept-Ranges: bytes
```

This makes me believe that swagger is configured properly with cors support.

What am I missing?

**Comment by steve-chavez** [comment]
@monemihir Did you managed to solve the issue?

Would [server-proxy-uri](http://postgrest.org/en/v5.2/install.html#server-proxy-uri) help here?

**Comment by steve-chavez** [comment]
Assuming the issue was solved.

Also, it was more of a swagger-ui issue than postgrest.
