### ISSUE TITLE
Documentation inaccurate for ov operator

### ISSUE THREAD

**Issue by kairan77** [PostgREST/postgrest#1249]
### Environment

* PostgreSQL version: (if using docker, specify the image)
11.X
* PostgREST version: (if using docker, specify the image)
5.2
* Operating system:
WIN10
### Description of issue

The online documentation http://postgrest.org/en/v5.2/api.html states that the syntax for using the operator ov is:
     /api?a=ov.['x','y'] ,
however upon testing the working syntax is:
     /api?a=ov.{'x','y'}
(Expected behavior vs actual behavior)
correct the documentation? I figure curly bracket is inline with cs/cd hence more intuitive.

(Steps to reproduce: Include a minimal SQL definition plus how you make the request to PostgREST and the response body)

![ovdocumentation](https://user-images.githubusercontent.com/48101363/53587717-0d0c8b00-3bc6-11e9-995a-15314e4ab2b4.png)

**Comment by steve-chavez** [comment]
What's the type of `permissions`? Could you share a sample schema?

We have a test for `ov.[0, 4]` working: https://github.com/PostgREST/postgrest/blob/c9b2830e52184ad1abefa83619bb1b328213a14e/test/Feature/AndOrParamsSpec.hs#L103-L104

https://github.com/PostgREST/postgrest/blob/c9b2830e52184ad1abefa83619bb1b328213a14e/test/fixtures/schema.sql#L1225-L1228

**Comment by kairan77** [comment]
create table data.permission (
	uuid		int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	issue_date	timestamp default now(),
	title		text default ''
);

**Comment by kairan77** [comment]
create table data.department (
	uuid		int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	version		integer default 0,
	issue_date	timestamp default now(),
	last_modified timestamp default now(),
	title		text default '',
	dept_type	data.department_type default '',
	company		integer REFERENCES data.company(uuid) on delete cascade not null,
	members		integer[] default '{}',
	permissions	integer[] default '{}'
);

**Comment by kairan77** [comment]
is ov designed only for range and not meant to be used for int[]?

**Comment by steve-chavez** [comment]
> is ov designed only for range and not meant to be used for int[]?

It's fine to use `ov` for arrays, though seems the bracket notation `[]` only works for ranges, I see now why you got a syntax error.

@kairan77 Thanks a lot for reporting this, I'm going to clarify the usage of `ov` for `range`/`array` types in the docs.

**Comment by kairan77** [comment]
@steve-chavez Thank you, you guys did an amazing job bringing this productive tool alive.

**Comment by steve-chavez** [comment]
Moving the issue to https://github.com/PostgREST/postgrest-docs/issues/202. Next release will include the clarification.
