### ISSUE TITLE
JWSInvalidSignature : generate jwt using spring boot

### ISSUE THREAD

**Issue by HamzaAitOumghar** [PostgREST/postgrest#1254]
### Environment

* PostgreSQL version: 9.6
* PostgREST version: 5.2
* Operating system: windows 10

### Description of issue

when I'm generating a jwt using spring boot  , I have the InvalidSignature Issue 

my secret key : F194A9D75FF3A34338EEA1D8521BE64A51265C

example of a generated jwt : 

eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoicG9zdGdyZXMiLCJleHAiOjE1NTI5MDUwMzZ9.bLEObu-_TCVtPm9aFBP2Pf40KT7D7rpSHd6k1Zy0xb4 

the function that generate the token : 

```
 public String generateTokenForPostgREST(UserDetails userDetails) {
        Map<String, Object> claims = new HashMap<>();
        final Date createdDate = timeProvider.now();
        final Date expirationDate = new Date(createdDate.getTime() + expiration * 1000);

        claims.put(CLAIM_KEY_POSTGREST_ROLE,"postgres");

        return Jwts.builder()
                .setClaims(claims)
                .setExpiration(expirationDate)
                .signWith(SignatureAlgorithm.HS256,PostgREST_SECRET)
                .compact();
    }
```

**Comment by ruslantalpa** [comment]
your jwt is invalid, check it here https://jwt.io/ (there is no problem with postgrest)

**Comment by HamzaAitOumghar** [comment]
thanks for reply ! but why is invalid ?

**Comment by ruslantalpa** [comment]
invalid signature, that is not the correct secret for that particular jwt you'll have to figure out why is that. until you can generate a jwt with a particular secret and then validate it in this site, it will not work with postgrest (I don't know that you are doing wrong in your java code to get this)

**Comment by steve-chavez** [comment]
Considering this resolved. Reopen if not.
