### ISSUE TITLE
404 when PATCH/update didn't change anything

### ISSUE THREAD

**Issue by sevagh** [PostgREST/postgrest#1257]
Hello. I'm doing a PATCH to update a row that doesn't exist. There's a GitHub issue (https://github.com/PostgREST/postgrest/issues/182) and pull request/changelog entry from 2015 (https://github.com/PostgREST/postgrest/commit/709e70561f8b527998b8ed8ac0916e92b1a5e17b) that indicates a PATCH that didn't change any rows should return 404.

Right now in my tests, I'm getting `204` whether or not any rows were updated. Could it be that this "404 when no rows were updated" behavior got lost somewhere along the line?

I'm using `postgREST v0.5.1` and Postgres 9.

**Comment by steve-chavez** [comment]
Not sure why that behavior changed in https://github.com/PostgREST/postgrest/pull/763, maybe it was just something that slipped by.

I also think that 404 is the correct status code. Thanks for the report.
