### ISSUE TITLE
Bump Docker base container version

### ISSUE THREAD

**Issue by pixie79** [PostgREST/postgrest#1260]
Hi,

The base container image for docker has many known security issues. Whilst I appreciate probably none of the affected libs are actively used by postgrest like systemd, it might be better to update the base to either a newer debian version. Or probably better still switch to Alpine which is smaller and does not include these extras by default.

If you would like i am happy to submit a sample patch for an alpine base container instead?

Regards

Mark

**Comment by steve-chavez** [comment]
Regarding alpine, see https://github.com/PostgREST/postgrest/issues/1143.

About upgrading debian, I think that'd be good. You could open a PR and I'll review it.

**Comment by ruslantalpa** [comment]
I would say there is no point in having an "official" image until Haskell/ghc itself officially supports alpine.
This looks like the place it's tracked https://gitlab.haskell.org/ghc/ghc/issues/14502 and it won't be any time soon.

**Comment by steve-chavez** [comment]
Copy pasting.

Switching to `stretch-slim` would be a good idea. A while ago I got a `Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found` when trying to build the image. It seems debian changed jessie mirror urls recently:

  - https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository
  - https://stackoverflow.com/questions/55386246/w-failed-to-fetch-http-deb-debian-org-debian-dists-jessie-updates-main-binary
  - https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

**Comment by steve-chavez** [comment]
Closing since https://github.com/PostgREST/postgrest/pull/1297 got merged.
