### ISSUE TITLE
Make PostgREST aware of Container memory limits

### ISSUE THREAD

**Issue by fpusch** [PostgREST/postgrest#1263]
### Environment

* PostgreSQL version: Docker postgresql:10
* PostgREST version: Docker postgrest/postgrest:v5.2
* Operating system: Ubuntu 18.10

### Description of issue

When running inside Docker containers may be killed if their memory usage exceeds the limit set by the cgroup. This can cause the PostgREST docker container to be restarted, for example inside Kubernetes, when running with a memory limit set. I assume this is because the Haskell binary thinks it has all the memory of the host system available, when instead it only has `/sys/fs/cgroup/memory/memory.limit_in_bytes` available. This is annoying as queries that create large results can easily cause the container to be restarted where they normally should only finish slower due to limited memory amount.

### Possible Solution

Introduce a command line or configuration option that allows an upper memory limit to be set or better determine the available memory automatically by looking at `/sys/fs/cgroup/memory/memory.limit_in_bytes` when run inside a container.

Edit: If more detail is required let me know and I will write something up.

**Comment by steve-chavez** [comment]
I recommend using [max-rows](http://postgrest.org/en/v5.2/install.html#max-rows) for your problem. With this you can set a hard limit for every query(it'll actually append a SQL `LIMIT number`).

Having a memory limit wouldn't help much because, by design, PostgREST obtains the full resultset(delegating all json/csv generation to PostgreSQL) and then sends it to the client. Finishing slower, or returning the result in a streaming way would imply changing this design and it would cost a lot.

That being said, I'd be interested in knowing how much memory PostgREST is consuming for large resultsets, perhaps this can be optimized.

**Comment by fpusch** [comment]
Thanks for your answer, I understand that PostgREST retrieves all entries of the request from the database at once. In my experience the memory used by PostgREST pretty closely matches the size of the resulting file transferred. Hence the memory used increases when a larger result is transferred by that amount.

I kind of hoped there was a way to transfer the results in a streaming way, but if this would cost a lot in the implementation I understand that it is better to create multiple requests and stitch them together on the consuming end.

**Comment by steve-chavez** [comment]
Streaming was discussed previously https://github.com/PostgREST/postgrest/issues/278.

Also I haven't investigated much but maybe https://www.pipelinedb.com/ could help.

**Comment by fpusch** [comment]
Thanks for the pointers. I've given pipelinedb a look, sounds quite interesting. As per the discussion in #278, is there any intention to include the streaming / cursor feature? If I read the exchange correctly it could be possible and 'the ball is in Postgrest' court', but the issue is currently closed?

Nevertheless feel free to close this issue, as the streaming feature is besides the point of the container memory limits question here. It could however be a great feature addition in the future.
