### ISSUE TITLE
Stored Procedures RPC call receiving CSV upload doesn't work

### ISSUE THREAD

**Issue by dalthon** [PostgREST/postgrest#1264]
### Environment

* PostgreSQL version: postgres:11.0-alpine
* PostgREST version: postgrest/postgrest:v5.2.0-3900baa
* Operating system: macOS Mojave

### Description of issue

I'm not sure if it's not supported and I'm trying to do something wrong, but I was trying to call a stored procedure in a bulk way, like in the insert.

But it didn't worked as I expected. So, to reproduce it:

As described in [Stored Procedures doc](http://postgrest.org/en/v5.2/api.html#stored-procedures), I created the following `add_them` procedure:

```sql
CREATE FUNCTION add_them(a integer, b integer)
RETURNS integer AS $$
 SELECT a + b;
$$ LANGUAGE SQL;
```

Then tried to call it in a bulk, like on bulk inserts with this HTTP request:

```
POST /rpc/add_them HTTP/1.1
Host: 0.0.0.0:3000
Accept: application/json, application/vnd.pgrst.object+json
Content-Type: text/csv
cache-control: no-cache

a,b
1,2
3,4
5,6
```

Then I received this response:

```javascript
{
    "hint": null,
    "details": null,
    "code": "21000",
    "message": "more than one row returned by a subquery used as an expression"
}
```

Looking at postgres log, I saw this error message:

```
2019-03-28 14:20:50.294 UTC [281] ERROR:  more than one row returned by a subquery used as an expression
2019-03-28 14:20:50.294 UTC [281] STATEMENT:
	       WITH _args_record AS ( SELECT * FROM json_to_recordset($1) AS _("a" integer, "b" integer) ),
	       pg_source AS (
	         SELECT "public"."add_them"("a" := (SELECT "a" FROM _args_record), "b" := (SELECT "b" FROM _args_record))
	       )
	       SELECT
	         null::bigint AS total_result_set,
	         1 AS page_total,
	         (row_to_json(_postgrest_t)->'add_them')::character varying AS body,
	         coalesce(nullif(current_setting('response.headers', true), ''), '[]') AS response_headers
	       FROM (SELECT "pg_source".* FROM "pg_source"    ) _postgrest_t;
```

So looking at this quey on debug, I believe that the correct query should be this:

```sql
WITH _args_record AS ( SELECT * FROM json_to_recordset($1) AS _("a" integer, "b" integer) ),
pg_source AS (
  SELECT "public"."add_them"(_args_record."a", _args_record."b") FROM _args_record
)
SELECT
  null::bigint AS total_result_set,
  1 AS page_total,
  (row_to_json(_postgrest_t)->'add_them')::character varying AS body,
  coalesce(nullif(current_setting('response.headers', true), ''), '[]') AS response_headers
FROM (SELECT "pg_source".* FROM "pg_source") _postgrest_t;
```

Bulk operations are not supported or am I doing something wrong?

If it's not supported, I believe that doing this change I proposed we would support it, right?

**Comment by steve-chavez** [comment]
Yes, bulk operations on RPC are not supported. I considered that if you want a bulk on RPC you should have parameter types such as `json/jsonb` or `array` and process those inside the function instead of calling the function n times.

Btw, using json and the new [`?columns` query arg](https://github.com/PostgREST/postgrest/pull/1241) would be much more efficient for large payloads.

That being said I think we could accomodate the use case of bulk RPC. Your proposed query works but we need to aggregate and return a single result.

**Comment by dalthon** [comment]
I'm not sure if it really should return a single result, but an array of each stored procedure call instead.

Maybe, this behaviour could be set using a `Prefer` HTTP header.

Or maybe I'm too biased thinking about my use case and missing something.

**Comment by steve-chavez** [comment]
You can try https://github.com/PostgREST/postgrest/pull/1266 for now.
