### ISSUE TITLE
invalid SQL generated for bulk upsert with empty array 

### ISSUE THREAD

**Issue by robx** [PostgREST/postgrest#1265]
### Environment

* PostgreSQL version: 9.6.11
* PostgREST version: 5.2.0 (1e732ac)
* Operating system: Debian 9.8

### Description of issue

When upserting an empty array of items, PostgREST reports the error

    syntax error at or near "RETURNING"

while non-empty upserts or plain inserts are handled fine. This seems to be irrespective of table structure. E.g.:

```
$ curl -X POST -H 'Content-type: application/json' -d '[]' -H 'Prefer: resolution=merge-duplicates' localhost:3000/articles
{"hint":null,"details":null,"code":"42601","message":"syntax error at or near \"RETURNING\""}
```

while this succeeds:

```
$ curl -X POST -H 'Content-type: application/json' -d '[]' localhost:3000/articles
```

**Comment by steve-chavez** [comment]
:heavy_check_mark: Reproduced. 

Should be a simple fix,  `DO UPDATE SET <empty>` is not valid so in case there's no payload we'll do `DO NOTHING`.
