### ISSUE TITLE
Fail when function is called with mismatching arguments

### ISSUE THREAD

**Issue by marcelmeyer** [PostgREST/postgrest#1273]
### Environment

* PostgreSQL version: 9.6
* PostgREST version: 5.2
* Operating system:

### Description of issue
Consider this func:
```
create or replace function cx.test(
a int,
b int
) returns int as $$
begin
  return a + b;
end;
$$ language 'plpgsql';
```

Under 4.2, calling that func with this payload will fail:
```
curl -X POST \
  https://host/rpc/test \
  -d '{
    "a" : 5,
    "b": 6,
    "c": 0
}'
```

Respnose:
```"message": "function cx.test(a => unknown, b => unknown, c => unknown) does not exist"```

Under 5.2 it will called successfully.

Can we make 5.2 fail in the same strict and reasonable way that 4.2 used to?
I see this behaviour as ambiguous and will be difficult to troubleshoot.

Thanks,
Marcel

**Comment by steve-chavez** [comment]
I think we can default unknown columns to a `text` type. So the message now could be:
```
"message": "function cx.test(a => integer, b => integer, c => text) does not exist"
```

Going back to `a => unknown` type of errors is not possible, since `unknown` is a pseudo-type and now we cast all function arguments to its type. So, using `text` seems the best choice. 

What do you think?
