### ISSUE TITLE
Please a How-to for curl tests on Stored procedures

### ISSUE THREAD

**Issue by ppKrauss** [PostgREST/postgrest#1277]
### Environment

* PostgreSQL version: PostgreSQL 10.7
* PostgREST version:  this month https://hub.docker.com/r/postgrest/postgrest
* Operating system: UBUNTU 16 LTS

### Description of issue
Trying to reproduce [*stored procedures* of the Guide](http://postgrest.org/en/v5.2/api.html#stored-procedures), but it not works... It's very frustrating, because there are no "click here to test". The suggestion is to add in the guide and distribution some standard tests with standard tools like `curl`.

The installation is working for any other thing, like [this simple query](http://osm.codes/sql/brcodes_state?select=region,lexlabel),

    curl "http://osm.codes/sql/brcodes_state?select=region,lexlabel"

PS:  same when testing in the server side `curl "http://localhost:port/etc"`

But not works for stored procedures. Using copy/paste of [the SQL example](http://postgrest.org/en/v5.2/api.html#stored-procedures), but trying any of these requests fails:

1. `curl "http://osm.codes/sql/rpc/add_them?a=1&b=2"`
2. `curl --header "Content-Type: application/json"  --request POST --data '{"a": 1, "b": 2}' http://osm.codes/sql/rpc/add_them`

same error, 

     {"hint":"No function matches the given name and argument types. 
        You might need to add explicit type casts.","details":null,"code":"42883",
        "message":"function public.add_them() does not exist"}

PS: all same  when testing in the server side `curl "http://localhost:port/etc"`

**Comment by steve-chavez** [comment]
You need to reload the schema cache if you created the function after PostgREST was started.
Mentioned in the [docs](http://postgrest.org/en/v5.2/api.html#stored-procedures):


Whenever you create or change a function you must refresh PostgREST’s schema. See the section [Schema Reloading](http://postgrest.org/en/v5.2/admin.html#schema-reloading).

**Comment by ppKrauss** [comment]
Hi @steve-chavez, thanks (!). Can you help a bit more?  What the terminal (server side) simplest command to  start docker?

**Comment by steve-chavez** [comment]
Use `docker kill --signal=HUP <container id or name>` to reload. Or just restart the container.

**Comment by ppKrauss** [comment]
Ok (!), http://osm.codes/sql/rpc/test_add1_xy?x=1&y=2

**Comment by ppKrauss** [comment]
Reinforcing the the suggestion:

1. **Add `curl` examples** (perhaps a link to appendix to not polute) to avoid doubts and confusion in the interpretation of the guide. 
2. Alert at Guide: "if you using docker, must restart!"
3. A Guide complement with a list of frequent errors and mistakes.  The *"No function matches the given name and argument types"*  must related to the  **docker restart**.

**Comment by ppKrauss** [comment]
... Hi again @steve-chavez, is there a standard "adapted [daemonizing](http://postgrest.org/en/v5.2/admin.html#daemonizing) for docker"? <br/>Why daemonizing (or crontab with `docker kill --signal=HUP`)  is not automatic/parametrized in a docker?

**Comment by steve-chavez** [comment]
@ppKrauss Adding "clickable" curl examples for all of the API reference is not possible without telling the user to first run a sample pg schema. It's a bit hard to make it like that for now, however we could add a guide for curl and common mistakes. I'll take your suggestions and track that in https://github.com/PostgREST/postgrest-docs/issues/220.

Regarding docker, please open another issue in https://github.com/PostgREST/postgrest-docs.
