### ISSUE TITLE
Allow for specifying the connection pool timeout value

### ISSUE THREAD

**Issue by boblauer** [PostgREST/postgrest#1278]
### Environment

* PostgREST version: 5.2

### Description of issue

Currently the ttl value of a pooled connection is hard coded to 10 seconds:

https://github.com/PostgREST/postgrest/blob/0d6d112b38e7b51f31c5ba9cf25ad344cf801c96/main/Main.hs#L167

It would be great if this could be set by an environment variable.

**Comment by steve-chavez** [comment]
This has been requested before https://github.com/PostgREST/postgrest/issues/1138. I think we could add a config option for the timeout.
