### ISSUE TITLE
Comments appended

### ISSUE THREAD

**Issue by pixie79** [PostgREST/postgrest#1279]
Postgrest 5.1

Hi,

I am making heavy use of postgres comments and embedding them with json, however it appears that postgrest is then also appending new lines and text when ever it encounters a primary and foreign key.

Can this be disabled or switched off with a run time toggle as it is very annoying, especially as this is the method you state in the docs for applying comments.

Another idea might be to add your comment / link to a references additional field on the output rather than in the description field?

Thanks

Mark

**Comment by ruslantalpa** [comment]
Where exactly are the comments appended?
Provide some kind of sample/print screen

**Comment by steve-chavez** [comment]
Closing until feedback is given, will reopen then.
