### ISSUE TITLE
Complex view rules limited by a `WITH` statement used by PostgREST

### ISSUE THREAD

**Issue by vwwv** [PostgREST/postgrest#1283]
### Environment

* PostgreSQL version: `PostgreSQL 10.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9), 64-bit`
* PostgREST version: docker `postgrest/postgrest:latest  38d0146ad1e1`
* Operating system: Ubuntu AWS image

### Description of issue

Can not insert into views having complex insertion rules; Example:
Inserting to this through PostgREST would work:

```
create view foo as (...)
 
create rule insert_to_foo as to insert to foo do instead
  ( insert into table1 values ...
  );
``` 
But to this won't :

```
create view foo as (...)
 
create rule insert_to_foo as to insert to foo do instead
  ( insert into table2 values ...
  , insert into table1 values ...
  );
```

Postgresql will complain after a conflicting `with` statement, though none is used as part of the view.

**Comment by steve-chavez** [comment]
Could you share the exact error message? 

Also, could you please include a reproducible sample schema(runnable)?

**Comment by vwwv** [comment]
Sure, the error message:
```
{"hint":null,"details":null,"code":"0A000","message":"multi-statement DO INSTEAD rules are not supported for data-modifying statements in WITH"}
```
A running example:
```
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS __example_table__
  ( foo     INTEGER PRIMARY KEY 
  -- ...
  );

CREATE OR REPLACE VIEW example_table AS
    SELECT *
      FROM __example_table__
     where false
  ;

CREATE OR REPLACE RULE insert_example_table AS ON INSERT TO example_table DO INSTEAD
  ( delete from __example_table__ 
          where true

  ; INSERT INTO __example_table__ 
         select uuid_generate_v4()  as foo
      returning *
  );
```
inserting to `example_table` directly on PostgrSQL works fine, through PostgREST triggers the error mentioned before.

**Comment by steve-chavez** [comment]
I get a similar error: `WITH cannot be used in a query that is rewritten by rules into multiple queries`.

Instead of a RULE, could you use a INSTEAD OF TRIGGER? I don't get an error with the following:
```sql
CREATE OR REPLACE FUNCTION insert_example_table() RETURNS TRIGGER AS $$
BEGIN
  delete from __example_table__ where true;
  INSERT INTO __example_table__ select uuid_generate_v4() as foo;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER insert_example_table
INSTEAD OF INSERT ON example_table 
FOR EACH ROW
EXECUTE PROCEDURE insert_example_table();
```

**Comment by vwwv** [comment]
Thanks for the hint, I think that could work for me. I've also tried wrapping the views around stored procedures and that seems to prevent the error (without modifying the rules).

**Comment by steve-chavez** [comment]
The PostgreSQL wiki also recommends [using triggers instead of rules](https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_rules).

Changing the queries to not use WITH would be a major endeavour for us(not even sure if it's feasible). So the trigger or the stored procedured workaround is your best bet.

I'll make sure to document this limitation on the docs.
