### ISSUE TITLE
Reread configuration or crash on DB connection failure

### ISSUE THREAD

**Issue by leaveningagent** [PostgREST/postgrest#1285]
### Environment

* PostgreSQL version: Not relevant
* PostgREST version: 5.2.0
* Operating system: Not relevant

### Description of issue

Some operations team will rotate passwords on a schedule, with affected infrastructure detecting those changes by being disconnected and having to reconnect with the updated password (fetched from a central secure storage).

PostgREST will try to reconnect using the wrong password forever without either rereading the configuration or crashing. If PostgREST would crash, a `systemd` unit could refetch configuration from a central system whenever it gets started up which would allow for a password change to be discovered.

If PostgREST were to reload the configuration file on failure, another mechanism could update the configuration file on password change.

Expected behaviour would be for either PostgREST to crash on incorrect password (or have that be a configurable option) or reread the configuration.

**Comment by steve-chavez** [comment]
Simplest and correct behavior would be to quit retrying on wrong password.

Right now we only quit on incompatible PostgreSQL version.

https://github.com/PostgREST/postgrest/blob/bcc317db81243dcd5ce488f445e3bb5e9a0fa62e/main/Main.hs#L81-L85

**Comment by leaveningagent** [comment]
@steve-chavez I agree, that would be the behaviour I'd expect.
