### ISSUE TITLE
Is it possible to suppress POST/DELETE/PATCH operations from the OpenAPI spec?

### ISSUE THREAD

**Issue by cldellow** [PostgREST/postgrest#1290]
### Environment

* PostgreSQL version: 11.1 (Ubuntu 11.1-1.pgdg.16.04+1)
* PostgREST version: v5.2.0
* Operating system: Ubuntu 16.04.4

### Description of issue

This is more of a doc question than a bug report. I followed the tutorial at http://postgrest.org/en/v5.2/tutorials/tut0.html to create the `api` schema and the `todos` table.

The generated OpenAPI spec at http://localhost:3000/ includes verbs for POST, DELETE and PATCH, even though the `web_anon` role only has `SELECT` privileges on the `api.todos` table. Is that expected?

I checked versions 5.1.0, 0.5.0.0 and 0.4.4.0 and they behaved similarly. I ask because https://github.com/PostgREST/postgrest/issues/1208 and https://github.com/PostgREST/postgrest/issues/954 gave me some hope that there is the ability to omit operations based on the logged in user's permissions.

I can filter this in post-processing if needed, but thought I'd ask first to see if I was missing something. Thanks for any help you can give (and for making this package!)

**Comment by ruslantalpa** [comment]
Thia should be as you describe i think (from memory, will look later). Try restarting postgrest (it caches the schema)

**Comment by ruslantalpa** [comment]
Checked the code, the api will not show tables that are mot accessible bit if there is a select grant, it will display all verbs (so postprocessing needed). I would not spend time on automating postprocessing, when going live just take the output, manually edit it and serve it as a static file (and update it when you change the api)

**Comment by cldellow** [comment]
Thanks for having a look and the clarification, Rustlan. That's very helpful!
