### ISSUE TITLE
postgrest static build support

### ISSUE THREAD

**Issue by clojurians-org** [PostgREST/postgrest#1295]
currently the postgrest executable build can't run without the libpq reference.
 also it can't run on nixos naturally.

i try to build this project with nix's static build. and it's successfuly.
(reference: https://github.com/nh2/static-haskell-nix)
then we only need to copy the executable to any host, it can run on any linux platform.

this is the sample nix build script:
https://github.com/clojurians-org/nix-haskell-build/blob/master/postgrest/default.nix

**Comment by steve-chavez** [comment]
Thanks for the research on this one. Currently I build postgrest on NixOS with a custom shell.nix(see https://github.com/PostgREST/postgrest/pull/1298).

A static build for Windows would be really great(see https://github.com/PostgREST/postgrest/issues/365#issuecomment-413245048), have you tried using nix there? We could try to integrate your script on appveyor(our CI for producing Windows binaries) as a first step.

**Comment by clojurians-org** [comment]
i'm currently using nix static build(postgrest and postgres-websocket) for nixos and readhat system .
i didn't use windows os on my work.

**Comment by steve-chavez** [comment]
Just confirmed the hard way that [Docker is not deterministic](https://news.ycombinator.com/item?id=11773591). Our release pipeline failed with things like an [outdated package url on centos6](https://circleci.com/gh/PostgREST/postgrest/3314?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

@clojurians-org Having a static binary released with nix is looking really good now. Do you know of a CI service that provides nix natively?

**Comment by steve-chavez** [comment]
Found that Travis supports it https://docs.travis-ci.com/user/languages/nix/ and there's a docker image available for CircleCI https://hub.docker.com/r/nixorg/nix/.

**Comment by clojurians-org** [comment]
you can reference hnix project:
https://github.com/haskell-nix/hnix/blob/master/.travis.yml

**Comment by steve-chavez** [comment]
@clojurians-org Could you build a static binary for our latest commit https://github.com/PostgREST/postgrest/commit/dd86fe372c623a6563bd8edf315ac0cfdbfd4571 and share it here?(as tar.gz)

**Comment by clojurians-org** [comment]
[postgrest-v6.0.0-static.tar.gz](https://github.com/PostgREST/postgrest/files/3328699/postgrest-v6.0.0-static.tar.gz)

**Comment by clojurians-org** [comment]
attach my build script：
https://github.com/clojurians-org/my-env/blob/master/nix.conf/postgrest-6.0.0/default.nix

**Comment by steve-chavez** [comment]
@clojurians-org Thank you so much! The static binary is working great!

I've attached it to our latest release https://github.com/PostgREST/postgrest/releases/tag/v6.0.0

**Comment by ggPeti** [comment]
Hi there. Someone posted a shorter build definition which also doesn't use pkgsMusl, therefore is much quicker to build: https://github.com/NixOS/nixpkgs/issues/37442#issuecomment-505028634

**Comment by steve-chavez** [comment]
@clojurians-org Is there a way to use a cache when doing static builds? I'm trying to build https://github.com/PostgREST/postgrest/commit/47c0141c4967b4e5349b7ee462059d9263618fdf (v6.0.1) but it seems the build it's taking as long as when I did the build for v6.0.0.

**Comment by clojurians-org** [comment]
cachix use static-haskell-nix

**Comment by steve-chavez** [comment]
@clojurians-org Could you provide me the nix expression for our latest [6.0.1](https://github.com/PostgREST/postgrest/tree/47c0141c4967b4e5349b7ee462059d9263618fdf) version? I'd like to try building the binary myself.

**Comment by ggPeti** [comment]
Is there anything wrong with @Infinisil's version?

**Comment by steve-chavez** [comment]
@ggPeti Nothing wrong. But that's not a statically linked binary.

**Comment by clojurians-org** [comment]
i don't know whether the previous 6.0.0 nix script still working on 6.1.
i will test and build it on this weekend on my idle time.

**Comment by clojurians-org** [comment]
@steve-chavez 

the updated default.nix should work with some note.

i use jailbreak to loose jose's version dependency as the jose github don't have this version.
i fetch the latest jailbreak github repo, it still is v0.8.0.0, can't validated by cabal build.

https://github.com/clojurians-org/my-env/blob/master/nix.conf/postgrest-6.0.1/default.nix

**Comment by steve-chavez** [comment]
@clojurians-org Thank you! I was able to build the static binary and published it to https://github.com/PostgREST/postgrest/releases/tag/v6.0.1.

Regarding jose, I've requested the addition of the git tag https://github.com/frasertweedale/hs-jose/issues/83#issuecomment-520525508.

**Comment by clojurians-org** [comment]
i will handle it in three days

**Comment by monacoremo** [comment]
I contacted @nh2 for some insights on using his `static-haskell-nix` project and he generously offered to support us in getting static PostgREST builds to work. I'll open an issue on https://github.com/nh2/static-haskell-nix when I have a first draft for building a static 7.0.0

**Comment by monacoremo** [comment]
Got a first version working here: https://github.com/monacoremo/postgrest-static-test/tree/4788c6bdb398564083802c3eb79b18f1935e243f

[postgrest-7.0.0-static.tar.gz](https://github.com/PostgREST/postgrest/files/4515457/postgrest-7.0.0-static.tar.gz)

Note: not yet built with integer-simple, which could be an LGPL issue?

**Comment by monacoremo** [comment]
@steve-chavez building those static executables from scratch takes ages, but we could get pretty quick incremental builds if we set up cachix in CI. With CACHIX_SIGNING_KEY configured as an environment variable in CircleCI, we could run something like this:

```bash
cachix use postgrest # Use the binary cache
nix-build | cachix push postgrest # Build and push new binaries
```
