### ISSUE TITLE
Hasql got support for dynamic generation of statements

### ISSUE THREAD

**Issue by nikita-volkov** [PostgREST/postgrest#1309]
Since I know that you guys dynamically generate SQL a lot, I'm informing you that I've released an extension library for Hasql, that helps a great deal with that:

http://hackage.haskell.org/package/hasql-dynamic-statements

**Comment by steve-chavez** [comment]
@nikita-volkov Thanks for the heads up!

Now that hasql dynamic has come up, I'd like to ask you a question.

Right now we're dealing with pg 11 stored procedures and the `call` syntax is limited, so we cannot convert a stored procedure result to json in SQL. Example:

```sql
create procedure public.test_proc(inout a int, inout b int) language sql as $$
select 1, 2;
$$;

-- gives result as record
call test_proc(3, 4);
 a | b 
---+---
 1 | 2

-- can't get result as json
select row_to_json((call test_proc(3, 4)));
-- ERROR:  42601: syntax error at or near "test_proc
```
(More examples of `call` limits in https://github.com/PostgREST/postgrest/issues/1210#issuecomment-500529022)

That means we're going to have to decode and convert to JSON ourselves in Haskell.

So, my question is, is it possible to **decode results dynamically** with Hasql? Right now with hasql-dynamic-statements seems it's only possible to **encode parameters dynamically**.

**Comment by nikita-volkov** [comment]
How do you plan to determine the decoder?

**Comment by steve-chavez** [comment]
@nikita-volkov I was thinking to query postgres system catalogs(we already do that [here](https://github.com/PostgREST/postgrest/blob/master/src/PostgREST/DbStructure.hs#L178-L195)) to obtain the stored procedures parameters and with that determine the decoder.

**Comment by nikita-volkov** [comment]
Okay. Then it looks like you need to do it in two steps: first query for the procedure's properties, then execute a stored procedure with a decoder, which produces JSON with the structure of the decoder determined by these properties.

```haskell
module Statements where

{-|
This is where you query the system catalogues.
-}
selectStoredProcedureProperties :: Statement Text StoredProcedureProperties

{-|
Call a stored procedure, using the provided properties to derive a decoder,
which produces JSON.
-}
callStoredProcedure :: Text {-^ Name -} -> StoredProcedureProperties -> Statement Aeson.Value Aeson.Value


module Decoders where

{-|
Derive a decoder from properties.

You'll use this function inside `callStoredProcedure`.
-}
storedProcedureResult :: StoredProcedureProperties -> Decoder Aeson.Value
```

**Comment by steve-chavez** [comment]
@nikita-volkov Thanks for the pointers. I'll give it a shot.

**Comment by steve-chavez** [comment]
pg11 stored procedures had limitations regarding transaction blocks(which we use for all statements), so ultimately I've decided not to support CALLing stored procedures. More details in https://github.com/PostgREST/postgrest/issues/1210#issuecomment-503366482.

@nikita-volkov Thanks again for the heads up on hasql-dynamic-statements.
