### ISSUE TITLE
Set header in pre-request function

### ISSUE THREAD

**Issue by amanbolat** [PostgREST/postgrest#1318]
### Environment

* PostgreSQL version: 11
* PostgREST version: 5.2
* Operating system: MacOS

### Description of issue

I've created pre-request function:
```sql
CREATE OR REPLACE FUNCTION auth.authorize_request()
  RETURNS void
  LANGUAGE plpgsql
AS
$$
BEGIN
  SET LOCAL "response.headers" =
      '[{"Set-Cookie": "test=test; Expires=Wed, 21 Oct 2019 07:28:00 GMT; HttpOnly"}]';
END;
$$;
```

But it does't set response headers. If it's not possible to do in pre-request function how can i achieve it for every user request?

**Comment by steve-chavez** [comment]
For now it's not possible to do it for every request. Also discussed on https://github.com/PostgREST/postgrest/issues/1088.

**Comment by steve-chavez** [comment]
Continuing on #1088. This feature will be on the plans.
