### ISSUE TITLE
function not found

### ISSUE THREAD

**Issue by mariomuja** [PostgREST/postgrest#1328]
Please help me to find out why the function below cannot be found by postgrest. It is working fine, when I call the function from pgAdmin.

All other REST calls via postman to postgrest work fine. For example,
http://localhost:3000/dim_claim_motor?contract_id=eq.402898556

Only functions do not work. I have restarted the postgrest server with no success.

I can see the function in pgAdmin in the public schema.

### Environment
* PostgreSQL version: 9.6
* PostgREST version: 5.2
* Operating system: Windows

### Expected Behaviour
function found and executed

### Actual Behaviour
PostMan returning this response

{"hint":"No function matches the given name and argument types. You might need to add explicit type casts.","details":null,"code":"42883","message":"function public.add_them() does not exist"}

### Function Body
CREATE FUNCTION add_them(a integer, b integer)
RETURNS integer AS $$
 SELECT a + b;
$$ LANGUAGE SQL IMMUTABLE STRICT;

### Postman Request
POST http://localhost:3000/rpc/add_them

Thanks a lot for your help.

**Comment by steve-chavez** [comment]
> POST http://localhost:3000/rpc/add_them

You're calling the function with no arguments, that's why postgresql doesn't find it.

Try doing `GET http://localhost:3000/rpc/add_them?a=3&b=4`.

Or do the POST with a json body of `{"a": 3, "b": 4}`

**Comment by mariomuja** [comment]
Thanks! This works in the browser but from Postman I still get the same error.

In postman, I try a POST with this URL http://localhost:3000/rpc/add_them
and set the Body tab to "raw" with content type combobox set to JSON (application/json) and this Body text

{
    "x": 4,
    "y": 2
}

So, I think, I provide the arguments in postman but it does not work. Somehow, I make a failure in postman.

**Comment by mariomuja** [comment]
Changed POST to GET in postman and now it is working.

The documentation says "The API endpoint supports POST (and in some cases GET) to execute the function.".

It seems that I have one of the "some cases" :-) in which cases do I have to use POST and when is GET the right solution?

**Comment by mariomuja** [comment]
I copied/pasted the example code from this page in the docs
http://postgrest.org/en/v5.2/api.html#stored-procedures

**Comment by steve-chavez** [comment]
That's clarified below, in http://postgrest.org/en/v5.2/api.html#immutable-and-stable-functions

**Comment by mariomuja** [comment]
thanks a lot for your help; problem solved
