### ISSUE TITLE
JOIN on JSON doesn't work?

### ISSUE THREAD

**Issue by MarkLyck** [PostgREST/postgrest#1341]
### Environment

* PostgreSQL version: 10.8
* PostgREST version: 5.2
* Operating system: (Ubuntu 10.8-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0, 64-bit

### Description of issue

Can't find any methods or examples of a working INNER JOIN on a JSON field.

So I have a table (VIEW) called metrics with a JSON column with ids in it.

I need to JOIN the metrics table with my address table on an id in that JSON column.

My first attempted query looks like this: /metrics_latest?select=labels->>site_id:address(*)

That doesn't work. I'm getting an error of unexpected token ":" (basically you can't use JOIN when you are dealing with JSON data?)

I've also tried other ways of getting address appended like this:

/metrics_latest?select=*,address(*)&address.site_id=eq.10371 (just trying to get something to work even if it's hardcoded) but still nothing. (says there's no relation between metrics_latest and address)

I know the obvious thing is to ask why I have the ids inside JSON in the first place. I have my reasons, suggesting I put them on the top level of the row is not what I'm looking for.

Is there no way to do a JOIN on JSON data with PostgREST :(?

**Comment by steve-chavez** [comment]
PostgREST allows JOINs **only on foreign keys**(see [resource embedding](http://postgrest.org/en/v5.2/api.html#resource-embedding)). So, you'd need a **primary key** on a JSONB column to do that(JSON type on pg doesn't allow equality so it cannot be defined as PK).

(Actually a UNIQUE constraint can also be used as a foreign key but we don't support doing embedding with that, we only look for pks)

So it's possible to do the JOIN but on a JSONB column, without seeing a sample schema I'm not sure how useful is that though.

Another option would be to do the JOIN in a VIEW or stored procedure and request that through PostgREST.
