### ISSUE TITLE
In Kong Gateway , postgrest not working.

### ISSUE THREAD

**Issue by rca32** [PostgREST/postgrest#1346]
### Environment

* PostgreSQL version: 10
* PostgREST version: 5.2,6.0
* Operating system:cent7

### Description of issue
In Kong Gateway, postgrest is very unstable..

Attempting to connect to the database...
Listening on port 3000
postgrest6.0: Cannot decode byte '\xb8': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream

**Comment by steve-chavez** [comment]
What request did you try to get:
```
postgrest6.0: Cannot decode byte '\xb8': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
```

**Comment by rca32** [comment]
The above error occurs when ichange Kong's policy, such as deleting the GET URL path or adding the POST URL.

**Comment by james-callahan** [comment]
Do you mean that you are using Kong in front of PostgREST?
What is the service and route you've set up?

**Comment by rca32** [comment]
YES,  PostgREST <-> KONG <-> NGINIX  <-> Internet
The URL is typically a table name in Korean.
eg. http://domin/%EC%9D%B8%ED%8F%AC%EB%B9%85%EC%8A%A4%EC%9A%A9_%EC%B4%9D%EC%88%98%EC%9D%BC%EA%B0%80%EC%A0%95%EB%B3%B4

**Comment by rca32** [comment]
After replacing KONG with API Umbrella, the problem disappeared.
