### ISSUE TITLE
Postgrest slow

### ISSUE THREAD

**Issue by pixie79** [PostgREST/postgrest#1347]
Hi,

Sorry i do not have much to go on here. We have been using Postgrest for a while and everything initially was fine. However after a while with V5.2.0 we noticed calls started being very slow. We managed to fix this by enabling profiling and running with profiling turned on, everything was back to normal speed.
However, now trying 6.0.0 we are back to the same slow issue. I have tried enabling profiling but it appears that is not an option in the current stack version.

I have tried using stack 1.9 latest and the latest version 2 but both have the same issues of slowness. Likewise i have tried the latest ubuntu 19.04, Amazon Linux and the current docker version of 5.2.0 & 6.0.0. All of them are slow (over a second for a reply).

Any ideas why they could suddenly be slow again, for information we do also use SSO with Keycloak.

Thanks

Mark

**Comment by simian-loco** [comment]
Are the `duration` query logs in postgres slow too via `log_duration`?

**Comment by steve-chavez** [comment]
First step would be finding if the PostgreSQL queries are slow, as suggested by @simian-loco.

**Comment by steve-chavez** [comment]
For now, the issue is not actionable as we can't determine if indeed PostgREST is being slow.
We'd need a more isolated test, sample requests and a sample schema. I think It's likely that this is more related to the db performance.

I'll close but will reopen if feedback is given.
