### ISSUE TITLE
Issue with Foreign Data Wrapper extension(multicorn) when PostgREST discovers the database

### ISSUE THREAD

**Issue by Remi-C** [PostgREST/postgrest#1352]
### Environment

* PostgreSQL version: 
PostgreSQL 11.2 (Ubuntu 11.2-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0, 64-bit|
* PostgREST version: 
6.0
* Operating system:
Ubuntu 18.04
### Description of issue
Issue using postgREST with a database using the `multicorn` extension, which is a meta foreign data wrapper.
Regardless if a foreign table is in the postgREST exposed schema or not, postgREST crash-loop. 
 - use the postgres extension multicorn
 - create a foreign data wrapper using multicorn (so first a server then a fdw).
 - attempting to start postgREST results in a nasty infinite loop :
```
    Attempting to connect to the database...
    Failed to query the database. Retrying.
    {"hint":"No function matches the given name and argument types. You might need to add explicit type casts.","details":null,"code":"42883","message":"function multicorn_check_plpython3u() does not exist"}
```
    Of course the function public.multicorn_check_plpython3u() do exist and I use a super user to connect with postgREST to eliminate any chance of improper privilege.
   

The reason of the bug is that postgREST execute a bunch of SQL queries to discover the relations in the database:
[code here](https://github.com/PostgREST/postgrest/blob/master/src/PostgREST/DbStructure.hs)
One of this query calls `pg_relation_is_updatable(c.oid::regclass, FALSE)`,
which in turn calls the foreign data wrapper check function `multicorn_check_plpython3u()`.

This function is installed in  the `public` schema, but at this point, PostgREST can not access to the public schema.

The workaround I found for the moment is to either 
 - install `multicorn` in the `pg_catalog` schema (bad idea)
 - add to the `pg_catalog` the 3 multicorn check functions (`multicorn_check_plpython3u(), ...`)

It would be nice to have some control about what the search_path looks like during the postgREST discovery phase (another parameter?).

Issue was discussed with @ruslantalpa and @steve-chavez

**Comment by steve-chavez** [comment]
You know, I have used [tds_fdw](https://github.com/tds-fdw/tds_fdw) with postgrest before and it didn't pose an issue, so maybe it could be a bug in multicorn.

I'll try installing multicorn next and see what I can find.

**Comment by Remi-C** [comment]
You are perfectly right, I tried using postgres_fdw and no bug.
I have no idea why the issue happens only with multicorn :-/
Maybe having the workaround now is enough (adding the 3 multicorn functions to pg_catalog)?

**Comment by steve-chavez** [comment]
I knew I had seen a similar bug before, check https://github.com/PostgREST/postgrest/issues/1287.

And this was fixed in https://github.com/pramsey/pgsql-ogr-fdw/issues/163.

For now you can do the workaround, but it'll be better to report a reproducible test case to multicorn and have it fixed.

**Comment by Remi-C** [comment]
It's funny, I used to work a lot with pramsey stuff (postgis, pgpointcloud). 
I had tried the 'updateable' trick to no success.
It seems that the multicorn extension is not maintained anymore [here a bug report without answers](https://github.com/Kozea/Multicorn/issues/207).

**Comment by steve-chavez** [comment]
Hmm. We should definitely not patch postgrest to workaround a bug in multicorn.

What we could do is  to report the issue about `pg_relation_is_updatable` and maybe add a section on the docs about foreign data wrappers, there we could add a note about the multicorn workaround.

**Comment by steve-chavez** [comment]
I think that most FDWs should work correctly. Seeing that multicorn is unmaintained maybe reporting an issue will not be of much use. Also adding docs for a special case is probably not worth it.  

I'll close for now. If someone bumps into this, it can be searched on the issues.
