### ISSUE TITLE
Feature request: tsrange as array

### ISSUE THREAD

**Issue by alex-eri** [PostgREST/postgrest#1356]
### Environment

* PostgreSQL version: 11
* PostgREST version:  6.0.0 (dd86fe3)
* Operating system: Debian 9,10

### Description of issue

For now `tsrange` is an string 
```
"timerange":"[\"2019-07-24 20:41:35.188\",\"2019-07-24 20:41:35.188\"]"
```

Maybe better export it as array with range semantic like
```
[
  "2019-07-24T20:41:35.188",
  "2019-07-24T20:41:35.188",
  "[]"
]
```
Maybe as dict
```
{
  "lower": "2019-07-24T20:41:35.188",
  "upper": "2019-07-24T20:41:35.188",
  "lower_inc": true,
  "upper_inc": true
}
```

**Comment by steve-chavez** [comment]
You mean that the JSON response of a tsrange comes as a string?

**Comment by alex-eri** [comment]
@steve-chavez 

Schema
```
create table api.table_name
(
	tsr tsrange default tsrange((now())::timestamp without time zone, ((now() + '1 day'::interval))::timestamp without time zone, '[]'::text)
);

INSERT INTO api.table_name (tsr) VALUES ('["2019-07-22 19:53:39.214352","2019-07-23 19:53:39.214352"]');
INSERT INTO api.table_name (tsr) VALUES (DEFAULT);

grant select on table api.table_name to web_anon;
```

Result
```
[{"tsr":"[\"2019-07-22 19:53:39.214352\",\"2019-07-23 19:53:39.214352\"]"}, 
 {"tsr":"[\"2019-07-22 19:53:39.214352\",\"2019-07-23 19:53:39.214352\"]"}]
```

**Comment by steve-chavez** [comment]
@alex-eri Can be solved with pg [create cast](https://www.postgresql.org/docs/11/sql-createcast.html) like: 
```sql
create or replace function tsrange_to_json(tsrange) returns json as $$
  select json_build_object('lower', lower($1), 'upper', upper($1), 'lower_inc', lower_inc($1), 'upper_inc', upper_inc($1));
$$ language sql;

create cast (tsrange as json) with function tsrange_to_json(tsrange) as assignment;
```

Then in pgrst call it like:

```
GET /table_name?select=tsr::json
```

**Comment by alex-eri** [comment]
I solved for now as aliased columns in view.

```
SELECT upper(trs) as start, lower (trs) as finish...
```

**Comment by steve-chavez** [comment]
@alex-eri Good. Though the `create cast` will work for every `tsrange` type.

Then this is solved in pg only. I'll close and later I'll add a how-to for this in the docs.

**Comment by geohuz** [comment]
I've managed to make a cast type to work with tsrange array, but I'm stuck on put the data, the body is like:

```
{
    "time_range": [
       {"start": "0001-01-01T19:30:00", "end": "0001-01-01T20:30:00"}
    ]
}
```

and I've got errors:
```
{
    "hint": "You will need to rewrite or cast the expression.",
    "details": null,
    "code": "42804",
    "message": "column \"time_range\" is of type tsrange[] but expression is of type json"
}
```

I have made a updatable view trigger function, any suggestion to fix the issue?

**Comment by steve-chavez** [comment]
@geohuz For inserting the tsrange, you could specify the literal representation:

```bash
curl -d '{"room": 123, "during": "[2010-01-01 14:30, 2010-01-01 15:30)"}' -H "Content-Type: application/json" localhost:3000/reservation 
```

(table taken from http://postgrest.org/en/v7.0.0/how-tos/casting-type-to-custom-json.html)

Casting the json back to tsrange in a view could work, I can't help with your description though. Can you share the VIEW definition?

**Comment by geohuz** [comment]
Ok, let me elabrate my problem into detail, I'm using a tsrange array type to store array of tsrange, so I create a cast fucntion like below:

```
CREATE OR REPLACE FUNCTION tsrangearray_to_json(
	tsrange[])
    RETURNS json
    LANGUAGE 'sql'

    COST 100
    VOLATILE 
AS $BODY$ 
select 
     json_agg(json_build_object(	
 	      'start', lower(n)
    	  ,'end', upper(n)	
		))
from unnest($1) as n
;
$BODY$;
```

So the cast function helps me to get a tsrange[] field like this:

```
 "time_range": [
            {
                "start": "0001-01-01T14:30:00",
                "end": "0001-01-01T15:30:00"
            },
            {
                "start": "0001-01-01T16:30:00",
                "end": "0001-01-01T18:30:00"
            }
        ],
```
But then I  need to put the modified data back into db, so finally I made another cast function to cast json to tsrange array, like this:

```
CREATE OR REPLACE FUNCTION data.json_to_tsrangearray(
	json)
    RETURNS tsrange[]
    LANGUAGE 'sql'

    COST 100
    VOLATILE 
AS $BODY$ 

select array_agg(tm_range) 
from (select 
json_array_elements_text($1)::tsrange tm_range) t1;
$BODY$;
```
The view I use is a complex sql join so can't be directly updated so I have to create a instead of trigger, so now I can do sth like this in my trigger:

```
update table
SET 
time_range = NEW.time_range::tsrange[]
where id = NEW.id;
```

That works for me but I'm not sure I'm doing correctly or there is a better way, it seems like if I use direct updatable view so I can update the view without creating another cast?
