### ISSUE TITLE
Time part format in datetime field

### ISSUE THREAD

**Issue by morfair** [PostgREST/postgrest#1359]
In my python's code if got date field like:

```
'eventdate': '2019-06-22 20:25:36'
```

PostgREST return error:
```
{"hint":null,"details":null,"code":"22009","message":"time zone displacement out of range: \"2019-06-22+20:25:36\""}
```
It looks right, but how to send time part right?

Sorry for my English.

**Comment by steve-chavez** [comment]
Error message comes from PostgreSQL. Casting the value works for me though:
```sql
select '2019-06-22 20:25:36'::timestamptz;
```

I suggest first trying curl or httpie and see if it works, then make sure the python code is indeed sending that date format.

**Comment by steve-chavez** [comment]
Assuming it was fixed. I suggest having a look at python libs for postgrest such as https://github.com/Kong/py-postgrest.

**Comment by morfair** [comment]
I fixed this by applying method .isoformat() on datetime variable.
