### ISSUE TITLE
Feature: OpenAPI authentication 

### ISSUE THREAD

**Issue by Fohlen** [PostgREST/postgrest#1365]
Dear `PostgREST` team. I just so recently started out using this amazing software.

I noticed that in the generated `OpenAPI` document, the authentication method is not marked.
This should be [Bearer Authentication](https://swagger.io/docs/specification/authentication/bearer-authentication/) and it is well supported via OpenAPI authentication spec.

It would be good to include this because:

- it makes generating client stubs easier
- using the `Swagger UI` will include a `login` button for protected routes

I hope this could be added to your considered list of features.

**Comment by bwbroersma** [comment]
See https://github.com/PostgREST/postgrest/issues/1082 & patches are welcome :)

Do you have any idea how to detect that authentication is needed / or what kind of hinting syntax (e.g. via the SQL comment) would you recommend?

**Comment by Fohlen** [comment]
@bwbroersma nice!
Well the obvious answer would be: any privilege that is not granted to the user specified as `web_anon` but to any user that PostgreSQL can authenticate as, produces a privileged route.
However, evaluating the privileges is [not an easy task](https://stackoverflow.com/a/22738217).

**Comment by steve-chavez** [comment]
Let's continue this on #1082.
