### ISSUE TITLE
No response body when doing upsert

### ISSUE THREAD

**Issue by fbaldo31** [PostgREST/postgrest#1366]
### Environment

* PostgreSQL version: 10 (postgresql-10-rhel7)
* PostgREST version: 5.2.0
* Operating system: rhel7

### Description of issue

No response body when doing upsert but got 200 statusCode

Steps to reproduce: I have follow the documentation on Upsert [http://postgrest.org/en/v5.2/api.html?highlight=upsert#upsert](http://postgrest.org/en/v5.2/api.html?highlight=upsert#upsert)

And to get the excpected response body (so one object with the 'id' column) i have added to the url `?select=id&Accept=application/vnd.pgrst.object+json`

But the response body is still blank

**Comment by steve-chavez** [comment]
You need to use `Prefer: return=representation` as mentioned in http://postgrest.org/en/v5.2/api.html#insertions-updates.
