### ISSUE TITLE
New container image failure (v6.0.1) : Error parsing config file

### ISSUE THREAD

**Issue by lofk** [PostgREST/postgrest#1367]
### Environment

* PostgreSQL version: postgres:11.3
* PostgREST version: latest (v6.0.1)
* Operating system:
Mac OS
### Description of issue
When starting the containers, the postgREST container fails with the logs below : 
```
postgrest_1        | Error parsing config file:
postgrest_1        | 	expected a list
```

**Comment by bwbroersma** [comment]
The problem is https://github.com/PostgREST/postgrest/blob/47c0141c4967b4e5349b7ee462059d9263618fdf/docker/postgrest.conf#L20

**Comment by steve-chavez** [comment]
For now I'll remove that config option because seems our config lib doesn't support passing a list through env vars, see https://github.com/robx/configurator-pg/issues/3.

**Comment by steve-chavez** [comment]
I've pushed new tags. `v6.0.1-53b606e` and `latest` in https://hub.docker.com/r/postgrest/postgrest/tags.

Try `docker pull postgrest/postgrest:latest`. That should fix it.
