### ISSUE TITLE
`killall` command not found when using Docker.

### ISSUE THREAD

**Issue by svilensabev** [PostgREST/postgrest#1390]
### Environment

* PostgreSQL version: 10.8-alpine
* PostgREST version: v6.0.2
* Operating system: Ubuntu 18.04

### Description of issue

Schema reload command is giving error when using PostgREST via Docker.

According to docs, the following command has to be used to do schema reloading

```
killall -SIGUSR1 postgrest
```

but it hits an error `killall: command not found`

---

It would be great to have this command pre-installed in docker image [here](https://github.com/PostgREST/postgrest/blob/v6.0.2/docker/Dockerfile#L12) 

Thanks for the great work.

**Comment by steve-chavez** [comment]
Also if you don't have `killall` in your system you can use `pkill`.

**Comment by ppKrauss** [comment]
Hi, @steve-chavez  `docker kill --signal=SIGUSR1 <container_id>`  is not working. Step-by-step:

1. `psql databaseName`; `CRETE TABLE public.new_table (...)` .. populate table
2. testing `http://mydomain:3000/new_table` say <br/>*"code": "42P01", "message": "relation \"public.new_table \" does not exist"*
3. `sudo docker container ls` shows the CONTAINER ID
4. `docker kill --signal=SIGUSR1 <container_id>` was fine, no error message
5. testing again  `http://mydomain:3000/new_table` but ... <br/>say again (!) *"code": "42P01", "message": "relation \"public.new_table \" does not exist"*

So, seems the problem the first hypothesis at item 1, the name of the database... So, **how to check the database used in docker configuration?**

**Comment by ppKrauss** [comment]
I am also adding a suggestion to [enhance online documentation on Schema Reloading](http://postgrest.org/en/v6.0/admin.html#schema-reloading), it need some explicit clues **for "docker dummy users"**. See [Steps 2 and 3 above](https://github.com/PostgREST/postgrest/issues/1390#issuecomment-559811969).

**Comment by steve-chavez** [comment]
@ppKrauss Hey! In that case the issue is not really about schema reloading(a simple `/table` request should work even with a stale schema cache) but more about pointing postgrest to another database.

To check the container configuration you can do:
```
docker inspect -f "{{.Config.Env}}" postgrest/postgrest
```

See more details in http://postgrest.org/en/v6.0/install.html#docker.

**Comment by ppKrauss** [comment]
Hi @steve-chavez ,
> To check the container configuration you can do:
> 
> ```
> docker inspect -f "{{.Config.Env}}" postgrest/postgrest
> ```

It not shows the database name,
```
[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PGRST_DB_URI= PGRST_DB_SCHEMA=public PGRST_DB_ANON_ROLE= PGRST_DB_POOL=100 PGRST_DB_EXTRA_SEARCH_PATH=public PGRST_SERVER_HOST=*4 PGRST_SERVER_PORT=3000 PGRST_SERVER_PROXY_URI= PGRST_JWT_SECRET= PGRST_SECRET_IS_BASE64=false PGRST_JWT_AUD= PGRST_MAX_ROWS= PGRST_PRE_REQUEST= PGRST_ROLE_CLAIM_KEY=.role PGRST_ROOT_SPEC= PGRST_RAW_MEDIA_TYPES=]
```
The PGRST_DB_URI is empty.

**Comment by steve-chavez** [comment]
@ppKrauss In that case what you could do is:

```bash
## get the container id
docker ps

## print the env var in the container
sudo docker exec <container_id> bash -c 'echo "$PGRST_DB_URI"'
```
