### ISSUE TITLE
Handling multiple foreign keys to the same foreign table

### ISSUE THREAD

**Issue by chocobloc** [PostgREST/postgrest#1394]
### Environment:
* PostgreSQL version: 10.3
* PostgREST version: 0.4.4.0
* Operating system: Windows 10

### Description of issue
Consider a table orders, which references the order_status table twice (previous status,current status).

(...It's just an example to illustrate my observations)

The following native sql query:
"SELECT order_uid, prev_stat_uid, curr_stat_uid from orders where order_uid = 1260065;"

would deliver as result:
{
order_uid: 1260065,
prev_stat_uid: 4,
curr_stat_uid: 6
}

However the result of the following query will return the same value for both status fields, eg:

http://127.0.0.1:3020/orders?order_uid=eq.1260065&select=order_uid,curr_stat_uid:order_status(stat_uid,stat_name),prev_stat_uid:order_status(stat_uid,stat_name)

will return

[
    {
        "order_uid": 1260065,
        "curr_stat_uid": {
            "stat_uid": 4,
            "stat_name": "In process"
        },
        "prev_stat_uid": {
            "stat_uid": 4,
            "stat_name": "In process"
        }
    }
]

My observation is, postgrest doesn't "assume" any request could reference a foreign table more than once. Would you concur with it?
If so, is there a chance Postgrest could also handle tables with more than one foreign key referencing the same foreign table? 

Thanks and kind regards,

**Comment by ruslantalpa** [comment]
the format for your select parameter is wrong

`A:B` means `SELECT B AS A`, it does not mean `SELECT from table B where the foreign key is A`

example of what you need
https://github.com/PostgREST/postgrest/blob/master/test/Feature/QuerySpec.hs#L298-L300

you want it like this
`select=order_uid,current_state:curr_stat_uid(...),previous_state:prev_stat_uid(...)`

**Comment by steve-chavez** [comment]
@chocobloc I think Ruslan answer fixes your issue. Though we definitely need a doc reference on `Resource embedding disambiguation` that mentions these capabilities.

I'll make sure to document that for the next release. I'll close this, will reopen if there are more doubts.

**Comment by chocobloc** [comment]
Sorry for not getting to you earlier. 
Based on your Ruslan's answer I'm now (successfully) using this: 
http://127.0.0.1:3020/orders?order_uid=eq.1260065&select=order:order_uid,status:curr_stat_uid(name:stat_name),previous_status:prev_stat_uid(name:stat_name)
