### ISSUE TITLE
I can still access the API even without passing JWT

### ISSUE THREAD

**Issue by allochi** [PostgREST/postgrest#1404]
### Environment

* PostgreSQL version: 11
* PostgREST version: 6.02
* Operating system: ubuntu

### Description of issue

I provided a `jwt-secret` in the configuration file, run the server and called the API without passing header `Authorization: Bearer ....`, I can still `GET` data, no error is thrown, I remember from my previous installation that unless I pass the header all communications are blocked unless a proper JWT is passed. I followed the documentations step by step, even same role names.

I also tried the latest docker image. In an older instance `Server: postgrest/0.4.3.0` it works as expected, no JWT no access.

Am I missing something?

**Comment by steve-chavez** [comment]
If no JWT token is sent, the [db-anon-role](http://postgrest.org/en/v6.0/configuration.html#db-anon-role) is assumed(which could have SELECT privileges).
Check http://postgrest.org/en/v6.0/auth.html for more info.

**Comment by allochi** [comment]
Humm, then it's my mistake, I should not include `db-anon-role` in the configuration file, only in the `role` JWT.

Thanks a lot that was helpful.
