### ISSUE TITLE
OpenAPI generated specs do not support type: array, and use format: ARRAY instead

### ISSUE THREAD

**Issue by synerscope** [PostgREST/postgrest#1405]
When generating an OpenAPI spec, array-valued types are annotated as having *type: string* with *format: array*. The OpenAPI specification supports using *type: array* with an *items* subkey to set the type of the items in the array.

This breaks my code when I generate (using openapi-generator) a client that needs to parse array return values, as it postgrest itself correctly returns an array typed object, but the spec indicates it should be interpreted as a string.  I have validated that the generated client code works if I patch the generated openapi spec before generation and replace all format: ARRAY, type: string entries with type: array and then items: - string.

I believe this is the code responsible, but do not know how to get the internal type of the items contained in the array to make the fix.

https://github.com/PostgREST/postgrest/blob/9847e60dcace57b9ae2f4fbba4ba9bcabceae4c6/src/PostgREST/OpenAPI.hs#L81-L87

**Comment by steve-chavez** [comment]
I've fiddled with the [Data.Swagger](http://hackage.haskell.org/package/swagger2-2.4/docs/Data-Swagger.html#t:SwaggerItems) types and this works for getting the string array items:

```patch
diff --git a/src/PostgREST/OpenAPI.hs b/src/PostgREST/OpenAPI.hs
index 1c3c875..97658e7 100644
--- a/src/PostgREST/OpenAPI.hs
+++ b/src/PostgREST/OpenAPI.hs
@@ -85,6 +85,9 @@ makeProperty pks c = (colName c, Inline s)
         & format ?~ colType c
         & maxLength .~ (fromIntegral <$> colMaxLen c)
         & type_ ?~ toSwaggerType (colType c)
+        & items ?~ (SwaggerItemsObject $ Inline (mempty
+          & type_ ?~ SwaggerString
+        ))
 
 makeProcSchema :: ProcDescription -> Schema
 makeProcSchema pd =
```

That logic should probably be moved to the `toSwaggerType` function. For starters that function could only pattern match the `text[]` type and output something similar to the above.

Open a PR if you'd like to give it a shot. Then we'd see how to add a test.

**Comment by ntgx** [comment]
I was facing a similar issue with arrays when generating types using [openapi-typescript](https://github.com/drwpow/openapi-typescript), and I was able to confirm adding `"items": { "type": "[arrayType]" }` to the generated property fixes the issue.  @synerscope @steve-chavez was there a PR created already with your suggested fix above? I could create it but I have very little experience with haskell 🙈

**Comment by dshukertjr** [comment]
Hey @steve-chavez ! I was wondering if this issue is something we might want to look at. 

Being able to get the openAPI spect from Postgrest is very helpful for anyone trying to integrate with Supabase. At the moment, this array type is the only type that the type cannot be properly obtained using it.
