### ISSUE TITLE
Unable to embed through association table and truncated embed name issue

### ISSUE THREAD

**Issue by bolerodan** [PostgREST/postgrest#1406]
### Environment

* PostgreSQL version:  11.5
* PostgREST version: 6.0.2
* Operating system: Ubuntu 18

### Description of issue

I've been using postgREST for the last year and everything seems to be fine, I even have another case in production where many to many embedding works fine (without needing to specify the joiner table) so Im not sure whats up.
```
--

CREATE TABLE public.smallmolecule (
    smallmolecule_id integer NOT NULL,
    name text
);

CREATE TABLE public.smallmolecule_family (
    smallmolecule_family_id integer NOT NULL,
    name text
);

CREATE TABLE public.smallmolecule_is_family (
    smallmolecule_family_id integer references smallmolecule_family(smallmolecule_family_id),
    smallmolecule_id integer references smallmolecule(smallmolecule_id)
);
```

This is a many to many. Smallmolecules can have many  families, and families can have many smallmolecules

I am unable to embedd the table `smallmolecule` when starting from `smallmolecule_family`. It ends up embedding `smallmolecule_is_family`
Request
`curl  -X GET "http://127.0.0.1:4000/smallmolecule_family?select=*,smallmolecule(*)"`
Response

```
[
  {
    "smallmolecule_family_id": 1,
    "name": "polyketide",
    "smallmolecule": [
      {
        "smallmolecule_family_id": 1,
        "smallmolecule_id": 1
      }
    ]
  }
]
```

However I expect smallmolecule to be embedded there, not the association "middle" table.
I can get to the smallmolecule table by nesting `smallmolecule_id(*)` within my first embed

Request
`curl  -X GET "http://127.0.0.1:4000/smallmolecule_family?select=*,smallmolec(*,smallmolecule_id(*))"`

Response:

```
[
  {
    "smallmolecule_family_id": 1,
    "name": "polyketide",
    "smallmolec": [
      {
        "smallmolecule_family_id": 1,
        "smallmolecule_id": {
          "smallmolecule_id": 1,
          "name": "dan"
        }
      }
    ]
  }
]
```
Another interesting thing, I can omit several characters out of the embedable resource name, for example, I turned `smallmolecule` into `smallmolec`

Request
`curl  -X GET "http://127.0.0.1:4000/smallmolecule_family?select=*,smallmolec(*)"`

Response

```
[
  {
    "smallmolecule_family_id": 1,
    "name": "polyketide",
    "smallmolec": [
      {
        "smallmolecule_family_id": 1,
        "smallmolecule_id": 1
      }
    ]
  }
]
```

Yet this still successfully embeds. How does it know to embed the table `smallmolecule_is_family` from `smallmolecule` when it should be the `smallmolecule` table that is embedded.

I hope this is a silly mistake somewhere on my end.

**Comment by steve-chavez** [comment]
@bolerodan I've reproduced your issue. You can get your desired result(the m2m relationship join) by doing:

```http
GET /smallmolecule_family?select=*,smallmolecule!smallmolecule_is_family(*)
```
(Make sure you single quote `'` the url in the curl call, otherwise the `!` trips out the shell interpreter)

> I hope this is a silly mistake somewhere on my end

Not your fault. Resource embedding actually does some kind of [AUTO JOIN](https://dba.stackexchange.com/questions/15147/why-arent-primary-key-foreign-key-matches-used-for-joins)(or a [KEY JOIN](http://www.sqlines.com/sybase-asa/key_join)) and this can get ambiguous. PostgREST has evolved to include some undocumented rules(like the duck typing you discovered) to help in disambiguation.

This will improve in the next release. In #1401, I added an error in case of ambiguity. Master branch would report this error for `/smallmolecule_family?select=*,smallmolecule(*)"` :

```json
{
    "details": [
        {
            "cardinality": "one-to-many",
            "source": "test.smallmolecule_is_family[smallmolecule_family_id]",
            "target": "test.smallmolecule_family[smallmolecule_family_id]"
        },
        {
            "cardinality": "many-to-many",
            "junction": "test.smallmolecule_is_family[smallmolecule_id][smallmolecule_family_id]",
            "source": "test.smallmolecule[smallmolecule_id]",
            "target": "test.smallmolecule_family[smallmolecule_family_id]"
        }
    ],
    "hint": "Disambiguate by choosing a relationship from the `details` key",
    "message": "More than one relationship was found for smallmolecule_family and smallmolecule"
}
```

**Comment by bolerodan** [comment]
Thanks @steve-chavez I just tested this and it works perfectly. I had no idea you could specify specific tables to join on. Thats a really powerful feature and I guess is used to avoid ambiguous joins if a table has many relationships or "paths".

The error reporting is going to be super helpful too that is much appreciated.

Thanks for your time.

**Comment by steve-chavez** [comment]
We'll keep improving on this(#1412) so it's clear that more than one relationship was detected. For now I'll close since the issue was solved.
