### ISSUE TITLE
Set permissions on unix socket

### ISSUE THREAD

**Issue by dafvid** [PostgREST/postgrest#1408]
### Environment

* PostgreSQL version: 11.5
* PostgREST version: 6.0.2
* Operating system: FreeBSD 12.0-RELEASE-p7

### Description of issue
I am using an unix socket to connect to the server with the option 'server-unix-socket'.
The created unix socket gets the default permissions of 755 but I need 660 since the web server needs to be able to use the socket. Please add the ability to set the socket permissions. And preferably the user/group of the socket as well.

**Comment by steve-chavez** [comment]
Hey @Dansvidania, perhaps you may have some advice for the unix socket permissions?

**Comment by Dansvidania** [comment]
From a first attempt at researching the issue, I have not -yet- found a way to assign a custom permission set to the socket created in the Network.Socket API. I need to investigate this further.

I apologize as I momentarily do not have access to a UNIX system and cannot verify this myself; this might be a stupid question, but is specifying a custom owner and group possible? 

unless Postgrest code runs as root, I do not think we can change the ownership of the socket to an arbitrary user:group pair (referencing [this for example](https://askubuntu.com/questions/95985/is-it-possible-to-change-ownership-of-a-file-without-root-access?rq=1) )

**Comment by steve-chavez** [comment]
@Dansvidania I think you're right. Maybe we shouldn't try messing with permissions.

I had a look at this SO question: https://stackoverflow.com/questions/20171747/how-to-create-unix-domain-socket-with-a-specific-permissions-in-c.

@dafvid Can you try creating a dir with your desired permissions and pointing postgrest to create the socket file inside that dir?

**Comment by dafvid** [comment]
@steve-chavez well I already do that actually. But that only solves the problem with the group membership. I need both read and write for the group.

My setup is this. I run postgrest with a postgrest user. That user and the www user are both in the www group. I run nginx with the www user. That allows the web server to read/write over the socket. I really don't want everyone to be able to read the socket.

It's true you need to run as root to change user so that wasn't perhaps such a good idea. But the postgrest user should be able to set group permissions to groups i belongs to. 

Looking at `man chgrp`: 
> The user invoking chgrp must belong to the specified group and be the owner of the file, or be the super-user.

But creating the socket in a dir with the correct group owner solves that part anyway so maybe that's the way to go.

As for socket permissions I looked at this https://github.com/grafana/grafana/issues/8358#issuecomment-303499537
and this
http://hackage.haskell.org/package/unix-2.7.2.2/docs/System-Posix-Files.html#g:2

Maybe it's possible to set permissions after socket creation? I still need the correct permissions and I don't want to change my umask or the umask of the postgrest process/daemon.

**Comment by Dansvidania** [comment]
@dafvid Changing the file permission should be possible, I apologise for this massive oversight :)

@steve-chavez what do you think would be the best way to go about this? is an optional ```server-unix-socket-mode``` config option acceptable?

**Comment by steve-chavez** [comment]
@Dansvidania That sounds good! I was thinking of just changing the default but a `server-unix-socket-mode` would be most flexible.

**Comment by steve-chavez** [comment]
Solved in #1415!
