### ISSUE TITLE
Allow casting on horizontal filtering

### ISSUE THREAD

**Issue by roymfibo** [PostgREST/postgrest#1409]
### Environment

* PostgreSQL version: 10.6
* PostgREST version: 6.0.2
* Operating system: Not sure since I can't find the docker file but it's linux distribution on AWS ECS

### Description of issue

I'm trying to filters rows based on timestamp column I have called: `log_datetime`
I wish to use the ilike operator so I use:
`audit_logs?log_datetime::text=ilike.*2019-11-26*`
And it fails with:
```{"hint":"No operator matches the given name and argument type(s). You might need to add explicit type casts.","details":null,"code":"42883","message":"operator does not exist: timestamp without time zone ~~* unknown"}```

As if it wasn't able to cast to `text` and the `ilike` failed since this operator doesn't support `timestamp`.

I even tried:
`audit_logs?date(log_datetime)=ilike.*2019-11-26*`

But with no luck.

**Comment by steve-chavez** [comment]
It's not possible to cast the column in the filter as `log_datetime::text=ilike.*2019-11-26*`. Though it could be added.

For now, you could create a computed column that returns the `log_datetime` as `text`. Or maybe you could make an equivalent request without using `ilike` and instead use `gt/lt`:
```http
GET /audit_logs?log_datetime=gt.2019-11-26&log_datetime=lt.2019-11-27
```

**Comment by roymfibo** [comment]
and `date(...)` can't be considered a computed function like I've used?

**Comment by steve-chavez** [comment]
What would we gain by supporting that? `select date(now()) ilike '2019-11-10'` still results in an error.

A computed column is like the one shown here http://postgrest.org/en/v6.0/api.html#computed-columns. You'd instead cast your `log_datetime` as text inside there.

But really comparing dates with `like` is frowned upon, it'd be better to use comparison operators. Check https://stackoverflow.com/a/4799730/4692662.

**Comment by roymfibo** [comment]
I see, well it'll be nice to support the column cast then :)

**Comment by ruslantalpa** [comment]
In filters it is always a bad idea to apply a transformations (cast in this case) to a column, you basically eliminate any chance of pg using an index. So no, this is a bad feature

**Comment by steve-chavez** [comment]
@ruslantalpa True. That's a good reason for not supporting cast. We should encourage index usage.

**Comment by steve-chavez** [comment]
I'll close since the original issue can be solved with comparison operators or a computed column.

We should document that we don't allow this kind of flexibility to ensure index usage(maybe on https://github.com/PostgREST/postgrest-docs/issues/272).

**Comment by dsokal-kf** [comment]
That is interesting, I casts are bypassed as expected for gt&lt:
```
GET /audit_logs?log_datetime%3A%3Adate=gt.2022-12-06
```
But they do not work with equality:
```
GET /audit_logs?log_datetime%3A%3Adate=eq.2022-12-06
```
