### ISSUE TITLE
Example of making a select when executing a post

### ISSUE THREAD

**Issue by kevin4dhd** [PostgREST/postgrest#1410]
Hi, I'm a little new at PostgRes, I'm looking for a post and get later.

![image](https://user-images.githubusercontent.com/22886367/68608698-8791e800-0481-11ea-924b-4a5189f09927.png)

I was reading the documentation and I found this, 'return = representation'

The specific documentation that I can also add 'Vertical Fitering' along with this, I have tried several ways but I don't get any results, I would like to know what is the correct way to merge 'return = representation + select', and also if it is possible to do a selec join with a table that has foreign key, I await your response, thanks.

And sorry for bad English, I speak Spanish.

**Comment by kevin4dhd** [comment]
I just realized that the select should be added to the post URL, doing that already works correctly.

**Comment by steve-chavez** [comment]
Here's an example for that http://postgrest.org/en/latest/api.html#embedding-after-insertions-updates-deletions.

Those docs are in master though. Hoping to do a new release soon.
