### ISSUE TITLE
postgrest.exe: error 0x0000013?

### ISSUE THREAD

**Issue by win32nipuh** [PostgREST/postgrest#1416]
I have downloaded the latest release zip and run the postgrest.exe, received: 
The application was unable to start correctly(0x0000013) .
What is wrong? How to run the postgrest on Windows?

**Comment by steve-chavez** [comment]
@win32nipuh Check the comment on https://github.com/PostgREST/postgrest/issues/1373#issuecomment-536567474 for a solution. Let's continue on #1373 since it's the same underlying problem.
