### ISSUE TITLE
No way to URL-encode the CSV request?

### ISSUE THREAD

**Issue by ppKrauss** [PostgREST/postgrest#1418]
It is not a bug, is ignorance or perhaps a suggestion... Suppose PostgREST at port 3000, it:

* returns JSON, `curl http://my.domain:3000/test_t1` <br>or  `curl --header "Accept: application/json" http://my.domain:3000/test_t1`

* returns CSV, `curl --header "Accept: text/csv" http://my.domain:3000/test_t1`

But navigating by browser (Firefox, etc.) or  loading dataset by a tool like [Orange](https://orange.biolab.si/) or Power BI, it is not possible (or a very advanted-user task) to apply `Accept: text/csv`, it is more simple to do something  `curl http://my.domain:3000/test_t1?_I_need_CSV=please`.  

How to do something like "_I_need_CSV=please", by URL, with no extra HTTP  header for content negotiation?

-----

PS: hum... a clue [at Guide's alternate-url-structure](http://postgrest.org/en/v6.0/admin.html#alternate-url-structure), perhaps a solution is to implement it at NGINX.

**Comment by steve-chavez** [comment]
Nginx should definitely be used in case there are shortcomings in HTTP clients. Btw, I opened a similar issue on the docs https://github.com/PostgREST/postgrest-docs/issues/157.

It'd be great to have a [how-to](http://postgrest.org/en/v6.0/#how-to-guides) for doing that.

**Comment by ppKrauss** [comment]
... Hum, is not working:

The NGINX config, 
```nginx
server {
    root /var/www/myServce/html;
    index index.php index.html index.htm;
    server_name myServce.etc;
    location ~ ^/_sql.csv/(.+) {
	  proxy_set_header Host $host;
	  proxy_set_header Accept 'text/csv';
	  proxy_pass  http://localhost:3000/$1;
    }
    location / {
        try_files $uri $uri/ =404;
    }
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php7.2-fpm.sock;
        fastcgi_read_timeout 900;
    }
}
```
The test:

* STANDARD ROOT IS WORKING:  `curl  http://myServce.etc:3000/` returns  JSON.

* TRY-CSV ROOT IS NOT WORKING:  `curl   http://myServce.etc/_sql.csv/` returns 404 Not Found.

* STANDARD SELECT IS WORKING:  `curl  http://myServce.etc:3000/t?limit=10` returns  JSON.

* TRY-CSV SELECT IS NOT WORKING:  `http://myServce.etc.com:3000/t?limit=10`  returns  502 Bad Gateway.

**Comment by ppKrauss** [comment]
@steve-chavez , about [this](#issuecomment-559868867) and other NGINX problems, clues and explanations: the ideal is not only explain, but to offer a repository of tested scripts.  Can  https://github.com/PostgREST create a git for **complete examples**?

**Comment by ppKrauss** [comment]
Near perfect solution (!),

Solution that is working, 

```nginx
    location /_sql.csv/ {
       proxy_set_header Host $host;
       # add_header Content-Disposition 'attachment; filename="$request_filename.csv"';
       proxy_set_header Accept 'text/csv';
       proxy_pass http://localhost:3000/;
    }
```

The solution created other [open problem on filename extension](https://stackoverflow.com/q/59112021/287948).

**Comment by steve-chavez** [comment]
@ppKrauss How about if you try it like this:

```nginx
http {
  upstream postgrest {
    server localhost:3000;
  }

  server {
    location /api/ {
      proxy_pass http://postgrest/;

      location ~ ^/api/(.*)\.csv$ {
        proxy_set_header Accept 'text/csv';
        proxy_pass  http://postgrest/$1;
      }
    }
  }
}
```

Then you could access the csv at `localhost:3000/api/table.csv` and the normal json at `localhost:3000/api/table`.

The git repo under the postgrest org is a good idea, I'll see about creating it and adding this example.

**Comment by ppKrauss** [comment]
Thanks @steve-chavez, good clues and solutions (!), I am trying to use it, but it is not the solution for the exposed problem: I need to return the `.csv` for a request that not have final suffix `.csv`.  The API request only **standard PostgREST** queries, no extension after query. 

For exemple: `http://myServce.etc/_sql.csv/t?limit=10`  <br/>(it is **not** `myServce.etc/_sql.csv/t?limit=10.csv`)

**Comment by steve-chavez** [comment]
See a solution in https://github.com/PostgREST/postgrest/issues/1425#issuecomment-576794939.
