### ISSUE TITLE
[PaaS Deployment] Scalingo one-click button

### ISSUE THREAD

**Issue by brandon-welsch** [PostgREST/postgrest#1420]
Hello. I'm a developer at Scalingo, [Scalingo](https://scalingo.com/) is a European and Heroku compatible PaaS.

And today I come to you because we want to make the project easily deployable on Scalingo via a one-click button.

Would you agree that we could propose our file additions as well as documentation about the deployment with us?

**Comment by steve-chavez** [comment]
@brandon-welsch Hey there,

Does Scaling allow creating multiple database roles on a free tier PostgreSQL?

**Comment by brandon-welsch** [comment]
@steve-chavez Hi, thanks for your answer.

Yes, it's possible to create multiple roles on a free tier PostgreSQL database.

**Comment by brandon-welsch** [comment]
Hello, I haven't heard from you since, is it possible to make this one-click?

**Comment by steve-chavez** [comment]
@brandon-welsch Sorry for the late reply. I didn't had the time to review Scalingo yet. Having multiple roles in the free tier would definitely give us a better demo than Heroku.

> is it possible to make this one-click?

Yes. However this brand exposure would be similar to what we offer on our [Sponsor level on Patreon](https://www.patreon.com/postgrest). If Scalingo would be willing to support us, I could add the one-click button in our [README](https://github.com/PostgREST/postgrest#sponsors) and [docs](http://postgrest.org/en/v6.0/#sponsors). 

Let me know if you're interested in this. You can also contact me privately(email on profile).

**Comment by brentybh** [comment]
> @steve-chavez Hi, thanks for your answer.
> 
> Yes, it's possible to create multiple roles on a free tier PostgreSQL database.

I tried it but it seems not possible to create custom roles with the default user...
