### ISSUE TITLE
Workaround for GET /rpc/function to STABLE function while setting response headers

### ISSUE THREAD

**Issue by francois** [PostgREST/postgrest#1422]
### Environment

* PostgreSQL version:  PostgreSQL 12.1 on x86_64-apple-darwin18.7.0, compiled by Apple clang version 11.0.0 (clang-1100.0.33.12), 64-bit
* PostgREST version: PostgREST 6.0.2 (UNKNOWN)
* Operating system: Mac OS X Mojave (10.14.6 (18G103))

### Description of issue

I wanted to serve IMG blobs straight from the database. I created the following function to be called from `/rpc/get_blob?blob_slug=aslug`

```sql
CREATE OR REPLACE FUNCTION api.get_blob(blob_slug text) RETURNS bytea AS $$
DECLARE
  res RECORD;
  headers TEXT;
BEGIN
  SELECT content_type, bytes INTO res
  FROM public.blobs
  WHERE blobs.blob_slug = $1;

  headers := CONCAT(
    '[{"Cache-Control": "public"}, {"Cache-Control": "max-age=259200", "Content-Type": "', res.content_type, '"}]'
  );

  SET LOCAL "response.headers" = headers;

  RETURN res.bytes;
END
$$ LANGUAGE 'plpgsql' STABLE;
```

PostgREST returns a 400 Bad Request when calling the function:

```
$ curl -sv -HAccept:"image/webp,*/*" 'http://localhost:3000/rpc/get_blob?blob_slug=cffikqsz' | strings
> GET /rpc/get_blob?blob_slug=cffikqsz HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.54.0
> Accept:image/webp,*/*
>
< HTTP/1.1 400 Bad Request
< Transfer-Encoding: chunked
< Date: Sun, 01 Dec 2019 02:27:53 GMT
< Server: postgrest/6.0.2 (UNKNOWN)
< Content-Type: application/json; charset=utf-8
<
{ [114 bytes data]
{"hint":null,"details":null,"code":"0A000","message":"SET is not allowed in a non-volatile function"}
```

I wanted to be able to set the `Content-Type` header so that the browser would be correctly informed of the actual content of the response's body. Notice the `Accept` header in curl above: this is the same header that Firefox sends. If I remove `SET LOCAL` in the function, the response becomes:

```
$ curl -sv -HAccept:"image/webp,*/*" 'http://localhost:3000/rpc/get_blob?blob_slug=cffikqsz' | strings
> GET /rpc/get_blob?blob_slug=cffikqsz HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.54.0
> Accept:image/webp,*/*
>
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Date: Sun, 01 Dec 2019 02:30:43 GMT
< Server: postgrest/6.0.2 (UNKNOWN)
< Content-Type: image/webp; charset=utf-8
< Content-Range: 0-0/*
<
{ [769 bytes data]
```

Now, the server is lying about the body's actual Content-Type. The original is an `image/gif`. The response says `image/webp`. PostgREST's configuration includes:

```
raw-media-types="image/png, image/jpg, image/webp, image/gif"
```

Are there any workarounds to `SET LOCAL` from within `STABLE` functions?

**Comment by steve-chavez** [comment]
Try using `perform` instead of `set local`. I've tried the following and it works:
```sql
CREATE OR REPLACE FUNCTION xyz() RETURNS text AS $$
BEGIN
  perform set_config('response.headers', '[{"Cache-Control": "public"}, {"Cache-Control": "max-age=259200"}]', false);
  return 'xyz'::text;
END $$ LANGUAGE 'plpgsql' STABLE;
```

Also note that `Content-Type` cannot be overridden through `response.headers`.  You can only add additional media types through the `raw-media-types` config.

**Comment by francois** [comment]
Ah... since I can't set `Content-Type`, this solution is not useful for me. I will stand up a sister webapp to handle blob storage and will put an nginx in front to manage dispatching to both endpoints. Thanks!

**Comment by steve-chavez** [comment]
If you specify `image/webp` on the `raw-media-types` and request `Accept: image/webp` then postgrest will set up the `Content-Type: image/webp`

**Comment by francois** [comment]
I understand, but images will be JPG. Firefox requests image/webp, */*. I haven’t investigated other browsers. Thanks!
