### ISSUE TITLE
CSV need extension

### ISSUE THREAD

**Issue by ppKrauss** [PostgREST/postgrest#1425]
CSV file, to correct and a friendly interface, needs `.csv` extension.

### Environment

* PostgreSQL version: 12
* PostgREST version: docker, last image
* Operating system: UBUNTU 18 LTS

### Description of issue

On `Accept 'text/csv';`  is expected to download a filename with `.csv` extesion.

Using Firefox or Chorme, the filename is the table name (independent of the query select part), that is good and corret, but need also the file extension  `.csv`.

See more details at issue #1418 

### To test solution
If PostgREST is working fine (apply bug correction), this NGINX endpoint definition must work fine.
 
```nginx
    location /_sql.csv/ {
       proxy_set_header Host $host;
       proxy_set_header Accept 'text/csv';
       proxy_pass http://localhost:3000/;
    }
```

**Comment by steve-chavez** [comment]
This is an ideal use case for proxy(Nginx, OpenResty, Caddy, etc). We should keep working on the #1418 direction.

Handling these special cases in postgrest itself would break its composability and would go against the [one thing well](http://postgrest.org/en/v6.0/#one-thing-well) principle.

**Comment by steve-chavez** [comment]
Hmm.. now that I've noticed. This could be handled at the SQL level. Once https://github.com/PostgREST/postgrest/issues/1088 is implemented, you could add the `Content-Disposition` header in the `pre-request` function.

That plus adding a GUC that gives the path of the request(also requested in https://gitter.im/begriffs/postgrest?at=5dcb6b6e5eb2e813db145584).

**Comment by steve-chavez** [comment]
With #1435, this now can be solved without Nginx by using the `pre-request` function. You can do something like:
```sql
create or replace function custom_headers() returns void as $$
declare
  req_accept text := current_setting('request.header.accept', true);
  req_path   text := current_setting('request.path', true);
begin
  if req_accept = 'text/csv' and 
     req_path similar to '/(items|projects)' -- if only certain paths are needed
    then perform set_config('response.headers',
           format('[{"Content-Disposition": "attachment; filename=%s.csv"}]', trim('/' from req_path)), false);
  end if;
end; $$ language plpgsql;
```
