### ISSUE TITLE
Inconsistent rpc result after creating a new function

### ISSUE THREAD

**Issue by fstn** [PostgREST/postgrest#1426]
Version: `"version":"6.0.2 (713b214)","title":"PostgREST API"`

Call a new proc stock:

`
    [
        {
            "companies_by_userid2": [
                {
                    "companyid": "44054450913",
                    "createdat": "2019-12-04T21:05:35.666205+00:00",
                    "facebookurl": "https://www.facebook.com/century21",
                    "companywebsite": null,
                    "facebookhandle": "@century21"
                }
            ]
        }
    ]
`

and after a restart I got:
`
    [
        {
            "companyid": "44054450913",
            "createdat": "2019-12-04T21:05:35.666205+00:00",
            "facebookurl": "https://www.facebook.com/century21",
            "companywebsite": null,
            "facebookhandle": "@century21"
        }
    ]
`

anyway to get a consistent result without companies_by_userid2.

**Comment by steve-chavez** [comment]
That's because of the [schema cache](http://postgrest.org/en/v6.0/admin.html#schema-reloading), it will be consistent(and remain like that for future runs) once you refresh the cache.
