### ISSUE TITLE
keyset pagination for the lazy

### ISSUE THREAD

**Issue by sunbing81** [PostgREST/postgrest#1431]
### Environment

* PostgreSQL version: not relevant
* PostgREST version: not relevant
* Operating system: not relevant

### Description of issue

To make keyset pagination on multiple columns work on postgrest, the lexical ordering must be manually implemented by plain logic operations:
1. `(x, y) > (a,b)` <=> `x=a AND y>b OR x>a`;
2. `(x, y, z) > (a,b,c)` <=> `x=a AND (y=b AND z>c OR y>b) OR x>a`.

If any column should be ordered descendantly, just change the relevant `>` to `<` in the right side.

Assuming the keyset for pagination is `(x, y, z)`, in which `x, y` are ordered descendantly, the query for posgrest is:
```
GET /api/entity?or=(and(x.eq.a,or(and(y.eq.b,z.gt.c),y.lt.b)),x.lt.a)&order=x.desc,y.desc,z
```

`or=(and(x.eq.a,or(and(y.eq.b,z.gt.c),y.lt.b)),x.lt.a)&order=x.desc,y.desc,z` looks very painful, so I wonder if syntax sugar could be provided in PostgREST, to allow that to be written as something like `keyset=(x.desc,y.desc,z).follow.(a,b,c)`.

**Comment by wolfgangwalther** [comment]
I feel like it's very unlikely that something like this is included in PostgREST. We currently only map some of the postgres operators more or less 1-to-1 to query syntax. The query syntax is clearly flexible enough to handle the request, so this does not seem to warrant the addition of a custom operator alias.

**Comment by steve-chavez** [comment]
I agree with @wolfgangwalther. Our syntax is still evolving and implementing shortcuts would lead us to trouble in the future. 

@sunbing81 I believe this one should be implemented on a client-side library.
