### ISSUE TITLE
Bug in `allSourceColumns` with subqueries (EXISTS/COUNT) column

### ISSUE THREAD

**Issue by benny-medflyt** [PostgREST/postgrest#1433]
Hi, thanks for the great work on PostgREST.

There seems to be a bug in the `allSourceColumns` function when one of the view columns is an `EXISTS` expression (or `COUNT` or `IN` subquery).

Starting from a blank database, I create a table and two views:

```sql
CREATE TABLE tbl( id INT );

CREATE VIEW good_view AS SELECT id, TRUE AS foo FROM tbl;

CREATE VIEW bad_view AS SELECT id, EXISTS(SELECT 1) AS foo FROM tbl;
```

When I run the huge SQL query found in `allSourceColumns` here:
<https://github.com/PostgREST/postgrest/blob/663faa1f82c90c9e486a9471c39cdefc11e7c869/src/PostgREST/DbStructure.hs#L722>

```sql
      with
      views as (
        select
          n.nspname   as view_schema,
          c.relname   as view_name,
          r.ev_action as view_definition
        from pg_class c
        join pg_namespace n on n.oid = c.relnamespace
        join pg_rewrite r on r.ev_class = c.oid
        where (c.relkind in ('v', 'm')) and n.nspname = 'public'
      ),
      removed_subselects as(
        ...
        ...
```

I get this result:

| table_schema | table_name | table_column_name | view_schema | view_name | view_column_name |
| -------------|------------|-------------------|-------------|-----------|------------------|
| public       | tbl        | id                | public      | good_view | id               |

Notice that "good_view" shows up as expected. but "bad_view" is missing. Lots of other complex views seem to work great, but as soon as a view has an `EXISTS` as one of its columns then the view completely disappears from the results.

I have tested this on PostgreSQL versions 9.6.15, 10.11 and 12.1

**Comment by steve-chavez** [comment]
@benny-medflyt Hey there.

I've ran the `allSourceColumns` query on `pg 11.4` and it shows both of your views(bad_view and good_view).

Note that query has a haskell variable embedded on it(`subselectRegex`) so it's not directly pastable, So maybe your tests on other pg versions were not entirely correct. 

What was the version you used when you encountered the issue?

**Comment by steve-chavez** [comment]
I can also get both `bad_view` and `good_view` on pg 12.1.

**Comment by benny-medflyt** [comment]
Thank you! the problem was indeed that i didn't notice that "subselectRegex" is a variable! I've put in the correct regex and it works!

(I am using this amazing query in another project: <https://github.com/MedFlyt/mfsqlchecker>)
