### ISSUE TITLE
Feature request: conf file augmentation

### ISSUE THREAD

**Issue by H20-17** [PostgREST/postgrest#1437]
For the conf file I would like a new paramater to be added, called something like:
_jwt-secret-file_. The value of the parameter should be a path to a file that contains only the secret.

The only reason for this is so we can have a slighitly more convenient way of sharing the secret between applications. The way it is now , if you want to share the secret between postgrest and some other app and use only one file, that file has to be the postgrest.conf file and apps besides postgrest shouldn't have to read it in (it's not their configuration file).

**Comment by steve-chavez** [comment]
`jwt-secret` already supports specifying a file, like `jwt-secret=@filename`. See http://postgrest.org/en/v6.0/configuration.html#jwt-secret.

**Comment by H20-17** [comment]
Thanks. Failed to see this. My bad. Closing this issue then.
