### ISSUE TITLE
Support scram-sha-256 authentication in docker image

### ISSUE THREAD

**Issue by mxk** [PostgREST/postgrest#1443]
### Environment

* PostgreSQL version: postgres:12 (ec5d6d5f5b34)
* PostgREST version: postgrest/postgrest:latest (68733fd099f0)

### Description of issue

When scram-sha-256 authentication is enabled on the server, PostgREST fails to connect with the following error: `{"details":"SCRAM authentication requires libpq version 10 or above\n","code":"","message":"Database connection error"}`

**Comment by steve-chavez** [comment]
It would be a matter of upgrading the Dockerfile [libpq](https://github.com/PostgREST/postgrest/blob/master/docker/Dockerfile#L7).

Seems debian stretch doesn't have libpq > 10 in its repos https://packages.debian.org/stretch/libpq-dev.
Debian buster does have it https://packages.debian.org/buster/libpq-dev.
