### ISSUE TITLE
Request for advice on integration with dex oidc provider

### ISSUE THREAD

**Issue by u24b6** [PostgREST/postgrest#1446]
I am looking to integrate postgrest with the dex oidc provider, but the supported scopes for dex do not include custom data from what I can tell. Is there any way that I can use a stored procedure to infer a user's role based on the groups claim or username?

https://github.com/dexidp/dex/blob/master/Documentation/custom-scopes-claims-clients.md

Thanks for your input.

**Comment by steve-chavez** [comment]
Check the [role-claim-key](http://postgrest.org/en/v6.0/configuration.html#role-claim-key) config option.

**Comment by steve-chavez** [comment]
@u24b6 Did my suggestion helped?

**Comment by u24b6** [comment]
Yes that should be suitable.
