### ISSUE TITLE
Custom function fails as relation doesnot exist 42P01

### ISSUE THREAD

**Issue by linux-devil** [PostgREST/postgrest#1447]
I am trying to write a custom function in postgres as :

`CREATE OR REPLACE FUNCTION public.find_closest(featurecollection json) RETURNS table(device_id integer, latitude double precision, longitude double precision)
as $$
  SELECT deviceid, latitude, longitude
  FROM tc_positions
  WHERE ST_Distance_Sphere(ST_MakePoint(tc_positions.longitude, tc_positions.latitude),ST_MakePoint((featurecollection->'features'->>'lon')::double precision,(featurecollection->'features'->>'lat')::double precision)) <= 2 * 1609.34
  and devicetime >= timestamp '2020-01-30T13:56:02' and devicetime < timestamp '2020-01-30T15:56:02';
$$ LANGUAGE SQL;
`

This creates table into postgres public schema. 

But whenever I try to use post request as following : 
`curl -X POST \
  http://localhost:3000/find_closest \
  -H 'Content-Type: application/json' \
  -H 'Prefer: params=single-object' \
  -d '{"type":"featurecollection","features":{"lat":12.976178,"lon":77.6434156}}'
`
It says:
`{
    "hint": null,
    "details": null,
    "code": "42P01",
    "message": "relation \"public.find_closest\" does not exist"
}`

I can see relation in the schema , not sure what is wrong . Also normal select queries to rest of the table works absolutely fine.

**Comment by nerfpops** [comment]
It might work if you change `http://localhost:3000/find_closest` to `http://localhost:3000/rpc/find_closest`

**Comment by linux-devil** [comment]
Wow , thank you @nerfpops  . Sorry for being ignorant , wish I was able to catch it in a doc somewhere.
