### ISSUE TITLE
set the request's mode to 'no-cors' to fetch the resource with CORS disabled

### ISSUE THREAD

**Issue by DavidMcGaha** [PostgREST/postgrest#1448]
### Environment

* PostgreSQL version: 11.2
* PostgREST version: 6.0.2
* Operating system: Centos 7 (postgrest) /Windows 2008 R2 (web server)

### Description of issue

I am PostgREST out. I am running 2 instances from command line and it will work for several hours or just an hour (some random amount of time) then it quits working and gives error about adding “Access-Control-Allow-*” to headers and I am just not understanding how to do that. Or, why it is doing this. Any suggestions?

It is on a Centos 7 server with a remote db (11.2) and web server is a different server(Windows IIS)

This is the response header when working 

(Steps to reproduce: Include a minimal SQL definition plus how you make the request to PostgREST and the response body)

HTTP/1.1 200 OK
Transfer-Encoding: chunked
Date: Fri, 07 Feb 2020 21:28:31 GMT
Server: postgrest/6.0.2 (713b214)
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Content-Range: 0-0/*
Content-Location: /last_run
Access-Control-Allow-Origin: http://test.globitech.com
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Encoding, Content-Location, Content-Range, Content-Type, Date, Location, Server, Transfer-Encoding, Range-Unit

This is after it has quit working...

1.	Request URL: 
http://tribbles.globitech.com:3002/last_run
2.	Referrer Policy: 
no-referrer-when-downgrade
2.	Response Headersview parsed
1.	HTTP/1.1 500 Internal Server Error Transfer-Encoding: chunked Date: Mon, 10 Feb 2020 14:55:10 GMT Server: postgrest/6.0.2 (713b214) Content-Type: text/plain; charset=utf-8
3.	Request Headersview parsed
1.	GET /last_run HTTP/1.1 Host: tribbles.globitech.com:3002 Connection: keep-alive User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 Accept: */* Origin: http://test.globitech.com Referer: http://test.globitech.com/tencor2/tencor.html Accept-Encoding: gzip, deflate Accept-Language: en-US,en;q=0.9

Errors in console
Access to fetch at 'http://tribbles.globitech.com:3002/last_run' from origin 'http://test.globitech.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
tencor.js:196 GET http://tribbles.globitech.com:3002/last_run net::ERR_FAILED
GetData @ tencor.js:196
(anonymous) @ tencor.js:2
tencor.js:196 Fetch failed loading: GET "http://tribbles.globitech.com:3002/last_run".

**Comment by DavidMcGaha** [comment]
As more info, both instances just ran for exactly 86400 seconds (24 hours exactly).

**Comment by steve-chavez** [comment]
So the root cause of the error was not CORS but that the postgrest instance behind the IIS proxy stopped running?

Make sure you have postgrest set up as a daemon. See http://postgrest.org/en/v6.0/admin.html#daemonizing.

**Comment by DavidMcGaha** [comment]
Well, I don't know. Still no resolved. It is not running behind and IIS proxy, but the postgrest instance(s) stopped running(at 24 hours on the nose). Could it be because I am not daemonizing them that they are dying at 24 hours?

**Comment by steve-chavez** [comment]
Not sure, but setting it as a daemon is what's usually done for production, definitely try that. After that check if the error the persists.
