### ISSUE TITLE
OpenAPI output that doesn't consider role privileges

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#1449]
Basically, users would like to get all the schema info through OpenAPI without caring for privileges. This was also discussed in https://github.com/PostgREST/postgrest/issues/1060 and we get this question on gitter chat from time to time. The workaround is cumbersome — adding a hardcoded high privileged JWT for the root endpoint. 

I propose we include a config option called `openapi-follows-acl`, default to true to avoid a breaking change. When this is false we'll use our schema cache info without considering privileges.

**Comment by mxk** [comment]
There has also been a request (#804) to disable OpenAPI interface altogether. If the ACL change gets implemented, it would be nice to have a third option for turning the interface off completely.

**Comment by steve-chavez** [comment]
There's no direct way like a `disable-openapi=true`, but right now the openapi output can be disabled with the undocumented(shows in postgrest --help though) `root-spec` config.

```
root-spec = "any_function"
```

The <any_function> can reply with any value(like null) to void the openapi output.

**Comment by steve-chavez** [comment]
This one should be basically scoped to these lines:

https://github.com/PostgREST/postgrest/blob/5c75f0dcc295e6bd847af6d9703fad5b9c3d76c9/src/PostgREST/App.hs#L460-L467

Instead of `accessibleTables`, use `dbStructure dbTables` conditionally - if `openapi-follows-acl=false`(the new config, which should be added in `Config.hs`). Same for accessible procs.

Then add tests similar to these:

https://github.com/PostgREST/postgrest/blob/5c75f0dcc295e6bd847af6d9703fad5b9c3d76c9/test/Feature/OpenApiSpec.hs#L152-L154

https://github.com/PostgREST/postgrest/blob/5c75f0dcc295e6bd847af6d9703fad5b9c3d76c9/test/Feature/OpenApiSpec.hs#L474-L476

Only tthat they should test the opposite if `openapi-follows-acl=false` - `it "includes privileged table for anonymous`.
