### ISSUE TITLE
Issue with PUT /{ressource} when some view columns are computed

### ISSUE THREAD

**Issue by FGRibreau** [PostgREST/postgrest#1452]
### Environment

* PostgreSQL version: 12
* PostgREST+ version: 6.0.2.5 (6da7006)
* Operating system: (docker)

### Description of issue

(Expected behavior vs actual behavior)

I edited the postgrest-starterkit to demonstrate the issue, see this PR: https://github.com/subzerocloud/subzero-starter-kit/pull/16/files

We either got 'View columns that are not columns of their base relation are not updatable.' or 'You must specify all columns in the payload when using PUT'.

**Comment by steve-chavez** [comment]
I see what you mean, the PUT restriction only considers the non-generated/computed table columns.

I think right now PUT is too restrictive to be useful(I prefer to use `resolution=merge-duplicates` because of that), so I can lift that restriction.
