### ISSUE TITLE
Windows Embbeded

### ISSUE THREAD

**Issue by herodem** [PostgREST/postgrest#1460]
I have a problem to run postgrest on Windows Embbeded Standard os.

Error message:
The procedure entry point _create_locale could not be located in the dynamic link library msvcrt.dll

Postgresql version: PostgreSQL 12.2, compiled by Visual C++ build 1914, 64-bit
Postgrest version: 6.0.2

**Comment by steve-chavez** [comment]
Could you try [building postgrest from source](http://postgrest.org/en/latest/install.html#build-source)?

**Comment by steve-chavez** [comment]
I believe this is the same issue as #1373. Let's continue there.
