### ISSUE TITLE
Large Location header on POST response

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#1461]
When there' no PK detected on a relation, and the relation columns have huge amounts of data(`text`/`bytea`) the `Location` header included in a response to a POST request can exceed proxies header limit size(4K, 8K, etc). An example in https://github.com/PostgREST/postgrest/issues/1427#issuecomment-595409551 shows: 

```http
POST /resource

HTTP/1.1 201 Created
Location: /loc_test?port_id=eq.206&name=eq.Loc%20header%20test&...(2k+ chars)
```
Proposed solution: don't reply with a Location header when the created row cannot be identified with a PK or a UNIQUE column(right now we only consider the PK). 

I also think that this goes more in line with [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6.3.2), which says:

>The primary resource created by the request is **identified** by either a Location header field in the response or, if no Location field is received, by the effective request URI.

We cannot **identify** the row when there's no pk or unique constraint.

For fixing this now, users can override the `Location` header with a trigger as shown in https://github.com/PostgREST/postgrest/issues/1427#issuecomment-594242147.

**Comment by neonerd** [comment]
I've also encountered this bug when POSTing to a VIEW of a table that has a "json" type column, the redirect URL returned in Location header seemed to be invalid (as it was trying to do a very convoluted eq.{json_value} filtering).

I'd just like to add here that this is a bit of a problem when using the private / public schema approach suggested in documentation, with only VIEWs in public schema exposed by PostgreSQL, as these don't seem to be inheriting PKs from their parent tables.

If we lose the Location: {url} redirect after POST for every VIEW, how do you then propose to do operations that require to further use the created object? (i.e. I create a new user by POSTing to a view and want to use his auto-generated ID, etc.)
