### ISSUE TITLE
No way to change RPC return template?

### ISSUE THREAD

**Issue by ppKrauss** [PostgREST/postgrest#1466]
The JSON return template for [rpc](http://postgrest.org/en/v6.0/api.html#stored-procedures) of a function that returns JSON is <br/> &nbsp; `[{"functionName":R}]` <br/>but sometimes we need only `R`.

Is it possible, by `postgrest.conf`  or another simple adaptation of PostgREST?

PS: on my [`GET /rpc/add_them?a=1&b=2`](http://postgrest.org/en/v6.0/api.html#immutable-and-stable-functions) it is returning `[{"add_them":3}]`.

**Comment by steve-chavez** [comment]
Reload the schema cache http://postgrest.org/en/v6.0/admin.html#schema-reloading.

**Comment by ppKrauss** [comment]
Hi @steve-chavez 
> 
> Reload the schema cache http://postgrest.org/en/v6.0/admin.html#schema-reloading.

How to `killall -SIGUSR1 postgrest` (error "postgrest: no process found") for a Docker process? 

Documentation (your  link) need some alert about Docker's Schema Reloading

**Comment by jpagex** [comment]
You can run either `docker kill -s SIGUSR1 CONTAINER` or `docker-compose kill -s SIGUSR1 SERVICE`.

**Comment by ppKrauss** [comment]
Reopening for v7.  The `SETOF JSONb` is with a bug. Example:

```sql
CREATE or replace FUNCTION API.uri_dispatcher(uri text DEFAULT '') RETURNS JSONb AS $f$
  SELECT '[{"id":1,"test":"t1"},{"id":2,"test":"t2"}]'::jsonb
$f$ language SQL immutable;

CREATE or replace FUNCTION API.uri_dispatcher_tuple(uri text DEFAULT '') RETURNS SETOF JSONb AS $f$
  SELECT '[{"id":1,"test":"t1"},{"id":2,"test":"t2"}]'::jsonb
$f$ language SQL immutable;
```
1. when create functions the return is ugly, with function names.
2. after something as docker's  SIGUSR1  the `rpc/uri_dispatcher` return expected JSON, clean.<br/>**But** `rpc/uri_dispatcher_tuple` not.
