### ISSUE TITLE
Add PostgREST to stackage?

### ISSUE THREAD

**Issue by robx** [PostgREST/postgrest#1474]
Not sure whether this is a net win for you, but: Now would be a great time to get PostgREST (back?) into stackage. Potential benefits would be:

- easier inclusion in some distributions, e.g. I remember Guix/Nix tracking stackage
- stackage would help ensure dependency upgrades don't break the postgrest build (and/or you'd have stackage maintainers poking you when updates cause trouble)

I just checked, and currently the PostgREST hackage release builds fine with stackage, following the instructions here: https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package (except tests need to be disabled since they require a running database).

**Comment by steve-chavez** [comment]
> I just checked, and currently the PostgREST hackage release builds fine with stackage

@robx Yes, thanks to you! Without your help I wouldn't been able to keep up with dependencies and GHC upgrades on this new release.

> Now would be a great time to get PostgREST (back?) into stackage

I think that would be good. Though right now I'm not finished with latest release stuff(docs, binaries). Once I'm done with that I'll check the stackage procedure.

**Comment by steve-chavez** [comment]
@robx Could you help me with maintaining the stackage package? Maybe you could add yourself as a maintainer on https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml .

**Comment by steve-chavez** [comment]
Also, do you think upgrading to stackage `lts-15.8` would cause issues? In https://github.com/PostgREST/postgrest/pull/1483 we're trying to make pgrst work better with Nix and `lts-15.8` is better supported by nixpkgs.

**Comment by robx** [comment]
> @robx Could you help me with maintaining the stackage package? Maybe you could add yourself as a maintainer on https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml .

Sure, in process!

**Comment by robx** [comment]
> Also, do you think upgrading to stackage `lts-15.8` would cause issues? In #1483 we're trying to make pgrst work better with Nix and `lts-15.8` is better supported by nixpkgs.

I'll give it a shot. I remember we had trouble a while back because newer stackage versions pulled in newer GHC which gave memory trouble, but I think that's the only argument against.

**Comment by steve-chavez** [comment]
Thanks a lot for taking care of this @robx.

Since you'll be helping us maintain PostgREST, begriffs has sent you an invitation to the postgrest github org.

Thanks again and Welcome!

(p.s. If you have anything you'd like to tell me privately, you can contact me at my email(on profile) or at gitter chat http://gitter.im/steve-chavez)

**Comment by robx** [comment]
Thanks!
