### ISSUE TITLE
Option "openapi-server-proxy-uri" missing in v7.0.0

### ISSUE THREAD

**Issue by brentybh** [PostgREST/postgrest#1500]
### Environment

* PostgREST version: v7.0.0

#### Expected behavior: v7.0.0 Changed
#1413, Change `server-proxy-uri` config option to openapi-server-proxy-uri - @steve-chavez

#### Actual
Config option `openapi-server-proxy-uri` is not effective.
`server-proxy-uri` is effective.
Thus same behaviour as before.

@brentybh You're right. This somehow slipped by during a rebase https://github.com/PostgREST/postgrest/blame/master/src/PostgREST/Config.hs#L157.

And now we have `server-proxy-uri` https://github.com/PostgREST/postgrest/blob/master/src/PostgREST/Config.hs#L157.

Could you open an issue for this?  Maybe we can release a 7.0.1 with some bug fixes.

_Originally posted by @steve-chavez in https://github.com/PostgREST/postgrest/pull/1441#issuecomment-618523688_

**Comment by pascal-de-ladurantaye** [comment]
+1
It seems to be completely broken if trying to use this option as an environment variable in a docker deployment.
PGRST_SERVER_PROXY_URI does not work on tag `v7.0.0` but works on `v6.0.2`
PGRST_OPENAPI_SERVER_PROXY_URI does not work on tag `v7.0.0`

For now, I had to revert our deployment to `v6.0.2`
