### ISSUE TITLE
Accept-Profile resolves to resource in incorrect schema

### ISSUE THREAD

**Issue by W1M0R** [PostgREST/postgrest#1519]
### Environment

* PostgreSQL version: postgres:12
* PostgREST version: postgrest/postgrest:v7.0.0
* Operating system: Alpine 3.10
* Environment Variables: PGRST_DB_SCHEMA="public,private"

### Description of issue

I have two schemas: `public` and `private`. The `public` schema contains a view called `users` and the `private` schema contains a table called `users`. To return the `private` `users` table I would expect to construct a get request for the `/users` endpoint using the `Accept-Profile: private` header. However, when I do this, I get the `public` `users` view instead. Also, inspecting the response header indicates `Content-Profile: private`, as if to say the data returned indeed comes from the `private` schema, however, looking at the actual data, this is definitely not the case. A workaround could be to change my PGRST_DB_SCHEMA variable to "private,public".

Shouldn't Accept-Profile force the request to first try and operate on the schema provided, instead of providing the first schema matched?

Also, if it is by design that the first schema matched should service the query, shouldn't the Content-Profile response header then indicate the correct schema used?

**Comment by steve-chavez** [comment]
It looks like a bug. Can you share a sample schema so I can reproduce the issue?

**Comment by W1M0R** [comment]
You can try:

```sql
create table private.users(
  id uuid unique not null default public.gen_random_uuid(),
  tag text unique not null,
  created_on timestamp with time zone default current_timestamp,
  primary key (id)
);

create view private.vw_users as select t.id as user_id, t.tag as user_tag from private.users as t;

create view public.users as select * from private.vw_users;
```

**Comment by dzelge** [comment]
My rough guess is that postgrest expands the SEARCH_PATH also for a list of schemas. 
The docs state that this is been done for a single entry in the conf ```db-schema```. 

```
This schema gets added to the search_path of every request.
```

**Comment by steve-chavez** [comment]
@W1M0R Could you include the requests(`curl`, `httpie`, etc) and the unexpected responses?

I'm trying to reproduce but I get the expected responses:
```bash
# insert into private.users(tag) values('user-1'), ('user-2');

curl -H "Accept-Profile: private" l:3000/users
[{"id":"d2eadd5e-ec6f-429d-8e32-48e5fe908170","tag":"user-1","created_on":"2020-05-12T12:02:11.927321-05:00"},
 {"id":"d9148f48-cce3-405a-be23-7bffdcbffbaa","tag":"user-2","created_on":"2020-05-12T12:02:11.927321-05:00"}]

curl -H "Accept-Profile: public" l:3000/users
[{"user_id":"d2eadd5e-ec6f-429d-8e32-48e5fe908170","user_tag":"user-1"},
 {"user_id":"d9148f48-cce3-405a-be23-7bffdcbffbaa","user_tag":"user-2"}]   
```

**Comment by steve-chavez** [comment]
@dzelge Just to clarify, the `search_path` is only expanded for a single schema. Even when `db-schema` contains a list of schemas. This is mentioned in the [db-schema docs](http://postgrest.org/en/v7.0.0/configuration.html#db-schema)(last part):
```
Only the chosen schema gets added to the search_path of every request.
```

**Comment by W1M0R** [comment]
@steve-chavez Thanks for the feedback. I am iterating quickly on my side, and don't have an example ready for you, however, your results indicate that I must have had an issue on my side. I tried to duplicate it again, but couldn't. Really sorry for wasting your time.

**Comment by steve-chavez** [comment]
@W1M0R No problem.

I thought there could be a bug because you use the `public` schema for your API and there might be a weird interaction with [db-extra-search-path](http://postgrest.org/en/v7.0.0/configuration.html#db-extra-search-path)(this includes the `public` schema on the `search_path` by default). But I didn't find any issue when doing some tests.

I'll close for now. If you still find the issue, comment here and I'll reopen.
