### ISSUE TITLE
No OpenAPI documentation for user-defined types as function parameters

### ISSUE THREAD

**Issue by W1M0R** [PostgREST/postgrest#1520]
### Environment

Environment
PostgreSQL version: postgres:12
PostgREST version: postgrest/postgrest:v7.0.0
Operating system: Alpine 3.10

### Description of issue

When a function takes a user-defined type, I would expect the OpenAPI documentation to show the input model with the relevant field comments. Instead, using the Swagger UI, it shows that the model is of type 'string' instead of the user-defined type.

Swagger UI output for function argument type (model):

```
description: Bla
credentials* | string($credentials)
```

The example schema is:

```sql
create type v1.credentials as (
  tag text,
  password text
);
comment on type v1.credentials is 'Bla';
comment on column v1.credentials.tag is 'Bla bla';
comment on column v1.credentials.password is 'Bla bla';
create function v1.login(credentials v1.credentials) returns json language sql volatile security definer as $$select json_build_object('token','bla');$$;
comment on function v1.login(v1.credentials) is 'Bla';
```

**Comment by nerfpops** [comment]
I think this might be related to #1377

**Comment by steve-chavez** [comment]
@nerfpops True, it's the same underlying problem.

@W1M0R Let's continue the issue on #1377.
