### ISSUE TITLE
How do you install postgREST? 

### ISSUE THREAD

**Issue by baditaflorin** [PostgREST/postgrest#1527]
### Environment

* PostgreSQL version: 12
* PostgREST version: 7.0.0
* Operating system:
Linux Mint 19.3

### Description of issue
```
wget https://github.com/PostgREST/postgrest/releases/tag/v7.0.0
tar xfJ postgrest-v7.0.0-ubuntui386.tar.xz
~/Desktop/ONERECORD/API_RESEARCH$ ls
postgrest  postgrest-v7.0.0-ubuntui386.tar.xz
~/Desktop/ONERECORD/API_RESEARCH$ ./postgrest 
bash: ./postgrest: No such file or directory
~/Desktop/ONERECORD/API_RESEARCH$ . postgrest
bash: .: postgrest: cannot execute binary file
```
(Expected behavior vs actual behavior)

Expected to be able to run the file.

(Steps to reproduce: Include a minimal SQL definition plus how you make the request to PostgREST and the response body)

**Comment by gamesbook** [comment]
I downloaded the `postgrest-v7.0.0-ubuntu.tar.xz` but when I try:

```
~/Desktop$./postgrest 
```

I get:

```
./postgrest: error while loading shared libraries: libpq.so.5: cannot open shared object file: No such file or directory
```
(running Mint 19.1)

**Comment by steve-chavez** [comment]
@baditaflorin @gamesbook Try the previous version static bin:

https://github.com/PostgREST/postgrest/releases/download/v6.0.2/postgrest-v6.0.2-linux-x64-static.tar.xz

**Comment by steve-chavez** [comment]
New version is already available: https://github.com/PostgREST/postgrest/releases/download/v7.0.1/postgrest-v7.0.1-linux-x64-static.tar.xz.

Will make clear in the docs that this binary should be preferred now.
