### ISSUE TITLE
Git revision shows as 'UNKNOWN' in help text

### ISSUE THREAD

**Issue by monacoremo** [PostgREST/postgrest#1530]
With the static builds, the Git revision is shown as UNKNOWN:

```
Usage: postgrest FILENAME
  PostgREST 7.0.1 (UNKNOWN) / create a REST API to an existing Postgres database
```

This is because we don't include the .git directory in the source files and `gitrev` cannot find the reference. We could try to
* work around this by including parts of the .git directory (probably quite messy)
* find another way to pass the revision into the build process, or
* remove showing the revision from the help text and remove the dependency on `gitrev`

**Comment by steve-chavez** [comment]
The original motivation from https://github.com/PostgREST/postgrest/pull/1022:

> When people submit a bug report for a custom binary they built off master it would be helpful to know exactly which git hash they built from

Until now, I've seen most users reporting issues with official pgrst releases, whether from Docker or binary. I think there were some custom binaries but I don't see a major issue in letting the user get the git sha manually.

The sha is nice to have but if it causes issues I don't see a strong reason for not to remove it.

> remove showing the revision from the help text and remove the dependency on gitrev

Would LGTM!

**Comment by monacoremo** [comment]
I'll submit a PR that patches it out!
