### ISSUE TITLE
Horizontal Filtering over POST-Request

### ISSUE THREAD

**Issue by MHC2000** [PostgREST/postgrest#1540]
### Environment

* PostgreSQL version: 11
* PostgREST version: 7.0.1
* Operating system:

### Description of issue

Hello,

is it possible to do horizontal filtering over a POST request (instead of GET)?

Sometimes some of our user filters are too long for a GET-Request and I get 414 or 502 due too long urls (already expanded the buffers of nginx but this didn't help).

Because the filters are dynamic it's not possible to use specialized views for alle of our tables (the filters are generated through a search field in our frontend and the amount of columns and filter isn't limited).

A workaround could be to generate a general filter function which takes the column filters and receive the results from the function but maybe there is an easier way over POST requests and also don't want to loose the benefits of the PostgREST API for filtering and sorting the data directly without the overhead of a custom function.

Regards

**Comment by steve-chavez** [comment]
@MHC2000 Hey there.

POST maps to [insertions](http://postgrest.org/en/v7.0.0/api.html#insertions-updates). I'm not sure if we could change that to include the filters in the payload. It looks hard from a glimpse.

Are you certain you cannot bypass the url length limit with Nginx? What settings have you tried?

Also, I could be of further help If you provide a sample URL.

**Comment by MHC2000** [comment]
@steve-chavez thanks for your reply.
That's what I was expecting, that POST is linked directly to Insert. Just came up with the idea when I read about a feature in other Restful-Apis (JIRA) where you can use POST as a bypass queries for a search, if the GET URL is getting too long.

I've tried to increase following Nginx parameters to allow longer URLs
> client_header_buffer_size 5120k;
> large_client_header_buffers 16 5120k;

**Comment by steve-chavez** [comment]
@MHC2000 Could you share a sample URL? I'm thinking what kind of filter could grow that much. Maybe a client adds a long list to an `in` operator?

**Comment by MHC2000** [comment]
@steve-chavez sadly I can't provide a sample, too much internal information included.
but you were right, the client summed up a lot of bloat. I managed to write the queries more compact, so the normal user won't run in the url length limitation so easily anymore and I will add a filter limitation to the client. 
So it's not an urgent issue for me anymore.
thanks for the help
