### ISSUE TITLE
Composite type filtering 

### ISSUE THREAD

**Issue by jamesmstone** [PostgREST/postgrest#1543]
### Environment

* PostgreSQL version: `12.2` (docker)
* PostgREST version: `7.0` (docker)
* Operating system:  docker

### Description of the feature request / issue

Is it possible to vertically filter ( and I guess also horizontally - although not needed for my use case ) on Composite Types: [Postgres Docs](https://www.postgresql.org/docs/current/rowtypes.html)

Imagine you have the following schema

```
CREATE TYPE complex AS (
    r       double precision,
    i       double precision
);

CREATE TABLE fav_numbers (
    num      complex,
    person     text
);

INSERT INTO fav_numbers VALUES (ROW(0.5, 0.5), 'A'),  (ROW(0.6, 0.6), 'B');
```

I am trying to filter `/fav_numbers` `where i > 0.5`

An example SQL query that would match looks like this:

`SELECT num, person from fav_numbers where i > 0.5`

I first tried the following request but it returns all rows:

`/fav_numbers?num.i=gt.0.5`

In a way, this is a bit like resource embedding

**Comment by jamesmstone** [comment]
I guess another thing to consider with this is ordering composite type by sub field

**Comment by steve-chavez** [comment]
Hey @jamesmstone.

> SELECT num, person from fav_numbers where i > 0.5

Hmm.. that one works for you? I had to do this:

(also according to pg [ROWTYPES-ACCESSING docs](https://www.postgresql.org/docs/13/rowtypes.html#ROWTYPES-ACCESSING))
```sql
SELECT num, person from fav_numbers where (num).i > 0.5;

-- this one also works
SELECT num, person from fav_numbers where num > '(0.5, 0)'::complex;
```

Thought the latter SQL statement would work through pgrst, but unfortunately it doesn't:
```
curl 'localhost:3000/fav_numbers?num=gt.(0,5,0)'
{"hint":null,"details":null,"code":"0A000","message":"input of anonymous composite types is not implemented"}
```
We would need to cast the filter to `::complex` internally for that to work.

> I guess another thing to consider with this is ordering composite type by sub field

That one also works in pg by using the `(column)` special syntax:

```sql
SELECT "test"."fav_numbers".* FROM "test"."fav_numbers" ORDER BY (num).r;
```

For now I'm thinking the solution would be to allow the special syntax in our Parsers. So the requests would be like this:

```bash
curl 'localhost:3000/fav_numbers?(num).i=gt.0.5'
curl 'localhost:3000/fav_numbers?order=(num).i'
```

**Comment by steve-chavez** [comment]
Regarding vertical filtering, that could also work with the same syntax:

```bash
curl 'localhost:3000/fav_numbers?select=(num).i'
```

This is more of a tentative solution, I'm not sure if it's possible to interpret this unambiguously in our parsers.

**Comment by jamesmstone** [comment]
> Hmm.. that one works for you? I had to do this:

Oops sorry, you are right. This is not my actual use case. So I didn't actually test that query.

> What do you think?

Personally, any syntax would suit me. I do however like the idea of using `(column)`  syntax you suggest as it matches what Postgres uses.


With vertical filtering, what area do you think this might conflict with?

**Comment by jamesmstone** [comment]
I am really keen to get this into Postgrest, to the point where I am willing to learn Haskell. Would you a) be open to an PR for this (from a complete Haskell novice) and 
b) be open to giving suggestions on where to add this?


From what I can tell thus far, I would need to modify this file https://github.com/PostgREST/postgrest/blob/master/src/PostgREST/Parsers.hs


I would also want to add some tests here...
https://github.com/PostgREST/postgrest/blob/master/test/Feature/QuerySpec.hs

**Comment by steve-chavez** [comment]
> a) be open to an PR for this (from a complete Haskell novice) and
> b) be open to giving suggestions on where to add this?

@jamesmstone Sure, go for it! You got the modules right. It'd be happy to review a PR. 

I'm not sure if it'd be straightforward to include the parens `(column)` as a valid field name because we have rules like this:
https://github.com/PostgREST/postgrest/blob/24064f86265b54701fa3c508099e211fb52b0887/src/PostgREST/Parsers.hs#L183

So for starters, you might want to use a different character. Here's a list of [url-safe chars](https://perishablepress.com/stop-using-unsafe-characters-in-urls/#character-encoding-chart). You could do a draft PR with a different char and then we can go from there and try to make parens work.

If you choose this route, you'd have to also work on `Private/QueryFragment.hs`. The `JsonPath` feature might help to see how this is done. Look [here](https://github.com/PostgREST/postgrest/blob/24064f86265b54701fa3c508099e211fb52b0887/src/PostgREST/Parsers.hs#L109-L125) and [here](https://github.com/PostgREST/postgrest/blob/24064f86265b54701fa3c508099e211fb52b0887/src/PostgREST/Private/QueryFragment.hs#L162-L169]).

**Comment by jamesmstone** [comment]
Hi @steve-chavez , 

Sorry for messing you around with this. I haven't had the time to really focus on this. If you would like to, please feel free to implement this yourself. 

If I get anytime I will let you know

**Comment by nerfpops** [comment]
+1 for this feature! Ideally one could query fav_numbers via `num.i` as opposed to `(num).i`, but I'm sure getting rid of the parentheses is hard.

**Comment by yyqgituser** [comment]
> I first tried the following request but it returns all rows:
> 
> `/fav_numbers?num.i=gt.0.5`

Is it possible to just reject the query by returning some error message? 'returning all rows' is some sort of confusion. Actually I found that any random string with '.' in it lead to return all rows.

**Comment by steve-chavez** [comment]
> /fav_numbers?num.i=gt.0.5

@yyqgituser Ah, I see what you mean. The `num.i=gt.0.5` filter gets silently ignored there. I think that would be a bug. Could you open a new issue for this one?

**Comment by jim-pendergraft** [comment]
Doesn't ->> already accomplish what the . operator on the LHS of a filter expression would do? If so, then an error on the LHS dot, maybe that refers to using ->> instead, would take care of this.

**Comment by steve-chavez** [comment]
> Doesn't ->> already accomplish what the . operator on the LHS of a filter expression would do?

@jim-pendergraft No, the dot is for [embedded filters](https://postgrest.org/en/v7.0.0/api.html#embedded-filters) and `->>` is for json columns.

The problem is that `num.i` is being interpreted as `num=resource i=column`. If the resource doesn't exist, the filter is silently dropped. That needs to be corrected here:

https://github.com/PostgREST/postgrest/blob/3a466aea9a8a4440dde056f8b372aae3f1bb2c54/src/PostgREST/DbRequestBuilder.hs#L277

**Comment by yyqgituser** [comment]
> Could you open a new issue for this one?

Sure, new issue created: https://github.com/PostgREST/postgrest/issues/1771

**Comment by Remi-C** [comment]
Hey folks, just to let you know I'm with you here 👀 .
We have a very complex database (500 tables, 200M rows, many many relations), 
and of course we use a bunch of composite keys. 
I have been thinking about a workaround but nothing pretty comes to mind.
I could cast composite key back and forth to text, but that would be ugly and I would loose the benefits of the relational model.
Thanks for your work folks, PostgREST is amazing, we were able to prototype an API soooo quick!

**Comment by steve-chavez** [comment]
Hey @Remi-C, thanks for the kind words.

A workaround would be to use a [computed column](https://postgrest.org/en/v7.0.0/api.html#computed-columns). Using [OP's schema](https://postgrest.org/en/v7.0.0/api.html#computed-columns), it would be like this:

```sql
create or replace function imaginary(fav_numbers) returns double precision as $$
  select $1.num.i;
$$ language sql;
```

Then you can use that computed column as a filter:

```bash
curl 'localhost:3000/fav_numbers?imaginary=gt.0.5

[{"num":{"r":0.6,"i":0.6},"person":"B"},
 {"num":{"r":0.3,"i":1},"person":"C"},
 {"num":{"r":0.4,"i":1.1},"person":"D"}] 
```

**Comment by steve-chavez** [comment]
It seems hard to implement my previous suggestion at the parsers level:

> curl 'localhost:3000/fav_numbers?(num).i=gt.0.5'
> curl 'localhost:3000/fav_numbers?order=(num).i'

Maybe we can resort to a new arrow operator instead, so:

```http
GET /fav_numbers?num->>>i=gt.0.5
```

That would be translated internally to `(num).i > 0.5`)

**Comment by wolfgangwalther** [comment]
For better visibility:

In https://github.com/PostgREST/postgrest/issues/1414#issuecomment-1003562226 I suggested to use the following:

Make a request with 

```http
GET /fav_numbers?num->i=gt.0.5
```

and turn that into

```sql
SELECT num, person from fav_numbers where to_json(num)->i > 0.5
```

**Comment by steve-chavez** [comment]
@wolfgangwalther Oh, I thought we would need to somehow identify on the schema cache what columns we need to call `to_json` on. But as you mentioned on https://github.com/PostgREST/postgrest/issues/1414#issuecomment-1003562226:

> Wrap all other usages of col->field and col->>field into a to_json(col)->'field' construct. When using those on a regular json column, this will be a no-op, since it's already json

So we'd just change change our translation from `col->field` to `to_json(col)->field`. Amazing, this solves the issue and only requires a minimal change :boom:
