### ISSUE TITLE
Error 502 on post

### ISSUE THREAD

**Issue by Abaru66** [PostgREST/postgrest#1545]
### Environment

* PostgreSQL version: docker image: marketplace.gcr.io/google/postgresql9
* PostgREST version: docker image postgrest/postgrest:latest

### Description of issue
Post on table with long content (base64 img) is ok on db but return http error 502
No error in postgrest log

**Comment by steve-chavez** [comment]
Hmm.. more context is needed. Could you share a sample schema(the table DDL)? 

The 502 responses for POST only happen for this table?

**Comment by steve-chavez** [comment]
Could be related to https://github.com/PostgREST/postgrest/issues/1461. The table that holds the images has a PK?

**Comment by Abaru66** [comment]
The ddl of the table:
CREATE TABLE "public"."piatti" (
    "id" integer DEFAULT nextval('piatto_seq') NOT NULL,
    "nome" text NOT NULL,
    "img" text NOT NULL,
    "id_tipo_piatto" integer NOT NULL,
    "id_albergo" integer,
    "prezzo" money,
    CONSTRAINT "PK_piatto" PRIMARY KEY ("id"),
    CONSTRAINT "FK_120" FOREIGN KEY (id_tipo_piatto) REFERENCES tipi_piatto(id) NOT DEFERRABLE
) WITH (oids = false);

CREATE INDEX "fkIdx_120" ON "public"."piatti" USING btree ("id_tipo_piatto");

The base64 image is stored in img column, something like: data:image/jpeg;base64,/9j/4AAQSkZJR....

The log on postgrest docker image refer no problem:
10.44.1.22 - - [17/Jun/2020:16:09:56 +0000] "POST /piatti HTTP/1.1" 201 - "http://localhost:8100/app/tabs/dashboard-admin/ristorazione/piatti" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36"

Thanks a lot!

**Comment by Abaru66** [comment]
perhaps something related to the internal nginx configuration?

**Comment by Abaru66** [comment]
I have done some test and found that when I use in post length >3600 byte I get the 502 error

**Comment by steve-chavez** [comment]
> post length >3600 

@Abaru66 Can you retry that POST with the `Prefer: return=minimal` header?. For docs on minimal, see http://postgrest.org/en/v7.0.0/api.html#insertions-updates.

**Comment by wolfgangwalther** [comment]
@Abaru66 Did Steve's suggestion help?

**Comment by wolfgangwalther** [comment]
Telling from the log, postgrest returned 201, while nginx returned 502. This seems to be a proxy issue. If anything comes up that suggests otherwise, feel free to reopen.
