### ISSUE TITLE
Broken link to documentation in externalDocs

### ISSUE THREAD

**Issue by sirviot** [PostgREST/postgrest#1553]
### Environment

* PostgreSQL version: latest docker image 
* PostgREST version: latest docker image

#### Expected behavior:

Link in externalDocs points to a working documentation for PostgREST

With Docker image `postgrest/postgrest:v7.0.1` should produce link to version 7.0.1 documentation. 

#### Actual behavior:

Link in externalDocs points to "This page does not exist yet"

With Docker image `postgrest/postgrest:v7.0.1` produces url `https://postgrest.org/en/v7.0/api.html` that is non existing.

### Steps to reproduce:

* Create docker-compose.yml as in <http://postgrest.org/en/v7.0.0/install.html#docker>
* Run `docker-compose up`
* Open <http://localhost:3000>
* Scroll down to externalDocs and find the url that should point to documentation but doesn't

**Comment by sirviot** [comment]
It seems that this was fixed in #1232 but is broken again.

**Comment by steve-chavez** [comment]
Sorry for the late reply here @sirviot.

You're right. I can add some redirects(v7.0 -> v7.0.0 and  v7.0.1 -> v7.0.0) on readthedocs to fix this one.

Made a mistake when creating a branch on postgrest-docs with the minor version included.
I'll add this on the [Release Checklist](https://github.com/PostgREST/postgrest/wiki/Release-Checklist) to ensure the error doesn't happen again.

**Comment by steve-chavez** [comment]
Fixed, now https://postgrest.org/en/v7.0/api.html redirects to https://postgrest.org/en/v7.0.0/api.html. Make sure to refresh the page.
