### ISSUE TITLE
Change db-schema at runtime

### ISSUE THREAD

**Issue by nerfpops** [PostgREST/postgrest#1556]
Say you have a multitenant architecture like this:

```
database
├── tenant1_schema
│   ├── invoice
│   ├── ledger
│   └── account
├── tenant2_schema
│   ├── invoice
│   ├── ledger
│   └── account
```

db-schema would then be "tenant1_schema, tenant2_schema".

Currently, for Postgrest to see a new schema, eg. when a new customer creates tenant3_schema, the schema must be added to db-schema and Postgrest restartet, causing downtime unless loadbalanced.

I would like to propose that db-schema could point to a Postgres function, that returns the schemas, and if a function is provided, that it's evaluated whenever `killall -SIGUSR1 postgrest` is called. I think Postgrest would fully support multitenant architectures like the one above if this was implemented.

**Comment by steve-chavez** [comment]
With the new SIGUSR2(#1544), it's now possible to add schemas(tenants) without needing to restart postgrest!

However for a full reload(db-schema update + schema cache reload) you'll need to send a SIGUSR2 + SIGUSR1.
Maybe SIGUSR2 can be improved to detect if `db-schema` is modified and then do the reload, avoiding the need for the extra SIGUSR1.

What do you think? SIGUSR2 would suffice?

(Related: https://github.com/PostgREST/postgrest/issues/1521)

**Comment by nerfpops** [comment]
Wow, that's awesome! SIGUSR2 + 1 is excellent as well. Thanks!
