### ISSUE TITLE
Suggestion: quoted role names option

### ISSUE THREAD

**Issue by michi-zuri** [PostgREST/postgrest#1561]
### Problem I'm trying to solve

I'd like to use orcid.org for authentication with their implicit jwt. Their iD has a format consisting of 15 digits followed by either a digit or the letter X. It contains also three dashes to aid readability. To be able to use thei iD as role name I would have to drop the dashes and prepend the string with an underscore, or place the whole string in quotes. Quoted names of objects, including roles, can contain pretty much anything and still be valid object names in postgresql.

### Suggestion

Add a config option to always quote the role value in the jwt.

**Comment by wolfgangwalther** [comment]
The `SET ROLE` command used to change to the user in the JWT already uses quoted role names like this:

```
SET LOCAL "role" = 'web_anon';
```

I guess you would just need to create those roles with `CREATE ROLE "123-123-123X"`, of course using quotes, and... it should work? Are you getting any errors?

**Comment by michi-zuri** [comment]
Hi @wolfgangwalther you are right, it does actually work perfectly fine as is. I had some trouble debugging, but this was not the problem. Sorry for the false alarm.

**Comment by steve-chavez** [comment]
@michi-zuri Is this good to close?

(Accidentally hit the close before)

**Comment by michi-zuri** [comment]
@steve-chavez yes (thank you :)

For the curious: I read somewhere that if you create a role with quotes, you always have to use the quotes to refer to those, and in fact assuming these 4 users are created: 
```
CREATE ROLE "_USER_1"; -- always use quotes to access this object
CREATE ROLE "_user_2";  -- optionally use quotes to access this object
CREATE ROLE _user_3; -- optionally use quotes to access this object
CREATE ROLE 4th_user; -- syntax error: name must not start with digit
CREATE ROLE "4th_user³"; -- OK: quotes are obligatory, can contain pretty much anything 
```
this gives an error:
```
SET ROLE _USER_1; -- ERROR:  role "_user_1" does not exist
SET ROLE "_USER_1"; -- OK (confirming what I have read)
```
on the other hand, this is fine:
```
SET ROLE _USER_2; -- OK: interpreted as SET ROLE "_user_2";
SET ROLE _user_2; -- OK: interpreted as SET ROLE "_user_2";
```
but this doesn't work, because quoted names are case sensitive:
```
SET ROLE "_USER_3"; -- ERROR:  role "_USER_3" does not exist
SET ROLE "_user_3"; -- OK: equivalent to SET ROLE _user_3 ;
SET ROLE _user_3 ; -- OK: equivalent to SET ROLE "_user_3";
SET ROLE _USER_3 ; -- OK: equivalent to SET ROLE "_user_3";
```
and names that contain anything other than digits, lowercase letters and underscore must be called in quotes:
```
SET ROLE 4th_user³; SYNTAX ERROR: must not start name with digit, (besides: ³ is not allowed)
SET ROLE "4th_user³"; OK
```

### Take home message: 
**If you create roles in your database with unquoted names, always assume lowercase letters for your sanity.**

Pleas note: I'm assuming there is no difference between `SET ROLE` and `SET "role" =` in terms of functionality.
