### ISSUE TITLE
Health endpoint

### ISSUE THREAD

**Issue by pixie79** [PostgREST/postgrest#1565]
Hi,

Can i check is the a health endpoint for postgrest that ideally lets us know it is up and can connect to the DB behind ok.

I would like to use this to poll from a load balancer?

Thanks

Mark

**Comment by wolfgangwalther** [comment]
I didn't try it myself, but I would try a `HEAD` request to the root endpoint. If the database is not available I would expect it to return some kind of error code and if everything is ok, I would expect it to return some `2xx` response.

**Comment by steve-chavez** [comment]
@pixie79 Did Wolfgang's suggestion helped? I think that should be the way to go.


(We could add the `HEAD /` request as health endpoint in the docs).

**Comment by pixie79** [comment]
Hi,

sorry yes that did work 👍 
Thanks
