### ISSUE TITLE
JSON column representation

### ISSUE THREAD

**Issue by Lemonn** [PostgREST/postgrest#1566]
### Environment

* PostgreSQL version: PostgreSQL 12.2
* PostgREST version: PostgREST 7.0.1
* Operating system: Ubuntu 20.04

### Description of issue

When a Table whit a column of type JSON get used and if a JSON structure like the one below gets inserted into the JSON Column,

```sql
CREATE TABLE "public"."json_test" (
  "id" int4 NOT NULL DEFAULT nextval('json_test_id_seq'::regclass),
  "json" json NOT NULL,
  "test" varchar COLLATE "pg_catalog"."default" NOT NULL,
  CONSTRAINT "json_test_pkey" PRIMARY KEY ("id")
)
```

```json
{ "firstName": "Bidhan", "lastName": "Chatterjee", "age": 40, "email":"bidhan@example.com"}

```
the response body from Postgrest is the following.

```json
[{"id":1,"json":{ "firstName": "Bidhan", "lastName": "Chatterjee", "age": 40, "email":"bidhan@example.com"},"test":"testvalue"}]
```

But should it rather be an escaped JSON string, like this? 

```json
 [{"id":1,"json":"{ \"firstName\": \"Bidhan\", \"lastName\": \"Chatterjee\", \"age\": 40, \"email\":\"bidhan@example.com\"}","test":"testvalue"}]
```
Because if the sub-type ($json) is not supported the fallback would be a string representation which then fails because the JSON, inside the JSON, could not be parsed as a string.

**Comment by wolfgangwalther** [comment]
> But should it rather be an escaped JSON string, like this?

IMHO, that would be very inconvenient. I think it's an absolute positive, that JSON fields (as well as composite type fields) are returned as properly nested json objects.

> ```json
>  [{"id":1,"json":"{ \"firstName\": \"Bidhan\", \"lastName\": \"Chatterjee\", \"age\": 40, \"email\":\"bidhan@example.com\"}","test":"testvalue"}]
> ```
> 
> Because if the sub-type ($json) is not supported the fallback would be a string representation which then fails because the JSON, inside the JSON, could not be parsed as a string.

I guess you are talking about type support on the client side here? To parse any JSON response, you need a JSON parser in the first place. It's hard for me to imagine a JSON parser in any language that does not support nested objects? If that really exists, I guess that would just not be a properly implemented JSON parser at all.
Maybe I just misunderstand, though!

**Comment by Lemonn** [comment]
Yes client side, I use go-swagger to create my client. The problem here is not to parse the object, but rather generate
the client whit a generator without manual adjustment. If I have the internal JSON structure as a string the generator
works just fine and the logic which makes the API-call then could unwrap the JSON-string and handle it accordingly.
But if it is a JSON type instead the generated client needs to know something about the content of the JSON structure
or needs to pack it in some general wrapper, which needs adjustments on the auto generated client.

I'm not that deep into the topic, but as far as I understand the fallback for not supported string types is a string, 
which then fails, in this case, because it could not be interpreted as a string.

**Comment by wolfgangwalther** [comment]
I don't know go-swagger, but I see two things that might work for you:

- instead of a json field use a postgres composite type (https://www.postgresql.org/docs/current/sql-createtype.html). That would basically give structure to your nested field and maybe the generator can create some corresponding types with that knowledge?

- if that doesn't work you should easily be able to just cast your json to text in the request, like this: `GET /json_test?select=id,json::text,test` (see postgrest docs here: http://postgrest.org/en/latest/api.html#casting-columns). This would give you exactly the string you're looking for.

**Comment by Lemonn** [comment]
Thanks a lot for the hint, the cast is the perfect solution in my case, I totally overlooked that part of the documentation.
