### ISSUE TITLE
A question about GET request (HELP)

### ISSUE THREAD

**Issue by panlazy** [PostgREST/postgrest#1575]
### Environment

* PostgreSQL version: Lastest
* PostgREST version: Lastest
* Operating system: Arch Linux

### Description of issue

So, I want to get data by filtering foreign key of foreign key :D Let's see my request first:

`GET: http://localhost:3000/cart?orderid=eq.1&&order.user.userid=eq.1&select=*,products(*)
`

What I'm trying to do is GET cart rows of `orderid: 1` and filter it by `order.user.userid: 1` and list products rows in cart table. And this is what i want to get:

```json
[
  {
    "cartid": 1,
    "productid": 1,
    "orderid": 1,
    "date": "2020-08-16T00:16:38",
    "count": 5,
    "product": {
      "productid": 1,
      "categoryid": 1,
      "productname": "X",
      "productprice": 25,
      "productstock": 200
    }
  },
 {
    "cartid": 2,
    "productid": 2,
    "orderid": 1,
    "date": "2020-08-16T00:16:38",
    "count": 2,
    "product": {
      "productid": 2,
      "categoryid": 1,
      "productname": "Y",
      "productprice": 55,
      "productstock": 100
    }
  },
]
```

Instead I'm getting rows of `cart.orderid: 1` How can I achieve that?

**Comment by wolfgangwalther** [comment]
I understand you're trying to filter the rows from `cart` by the value of a joined column (`order.user.userid`). No matter whether that's 1 or 2 levels deep - this is currently not possible. See #1075.

You can create a `VIEW` that does this join already and has a `userid` column. Then you can filter on this.

Are you sure, though, that you want to apply the `userid` filter on the client-side in the request? Wouldn't you be better of by adding a RLS policy to the base table or a `WHERE` clause to the view to select rows based on the currently logged in user?

See here for details: http://postgrest.org/en/latest/auth.html#users-and-groups

**Comment by panlazy** [comment]
Thank you for quick reply!

> I understand you're trying to filter the rows from `cart` by the value of a joined column (`order.user.userid`). No matter whether that's 1 or 2 levels deep - this is currently not possible. See #1075.
> 
> You can create a `VIEW` that does this join already and has a `userid` column. Then you can filter on this.
> 

Yes, you are correct. Ill try to write a VIEW but I'm actually bad at this, don't remember much (thanks to NoSQL databases) :sweat_smile: Any documentation will be appreciated sir! 

> Are you sure, though, that you want to apply the `userid` filter on the client-side in the request? Wouldn't you be better of by adding a RLS policy to the base table or a `WHERE` clause to the view to select rows based on the currently logged in user?
> 
> See here for details: http://postgrest.org/en/latest/auth.html#users-and-groups

Reason why I'm trying to do this request is to be fastest as possible. It will be non-public project(localarea) I'm even not using JWT for authentication, a basic request will solve that for me, just want to get all the products of specific user's created order.

**Comment by panlazy** [comment]
Well, I've found a workaround so if anyone needs it I'm putting down here.

`http://localhost:3000/cart?select=*,product(*),order(totalprice, orderdate, user(userid, userfirstname, usersirname), customer(*))&orderid=eq.1&order.user.userid=eq.1`

It will filter cart table by `orderid` and `userid`, will give you `products` `order.totalprice` `order.orderdate` `user.userid` `user.userfirstname` `user.usersirname` and `customer`
