### ISSUE TITLE
text/plain requested but more than one column was selected

### ISSUE THREAD

**Issue by dmkuzsib** [PostgREST/postgrest#1584]
### Environment

* PostgreSQL version: 9.5
* PostgREST version: 6.0.1, 7.0.1
* Operating system: CentOS 6

### Description of issue

With header 'Accept: text/plain' set, request of output of a function returning  a set of values from single column, ends up with HTTP 406:

wget   -O- --header='Accept: text/plain'   http://127.0.0.1:5438/rpc/test
**HTTP request sent, awaiting response... 406 Not Acceptable**

when same URL is proxied by nginx and requested via Chrome, user sees this :
**{"message":"text/plain requested but more than one column was selected"}**

The pgrest log contains this:
GET /rpc/test HTTP/1.0" 406 - "" "Wget/1.12 (linux-gnu)

when header 'Accept: text/plain' _IS NOT_ set, the URL returns:
[{"test":"AAAAA\n"}]

### Function DDL SQL

CREATE OR REPLACE FUNCTION "api"."test" ()  RETURNS SETOF text
  IMMUTABLE
AS $dbvis$
begin
	 RETURN query select 'AAAAA'::text||chr(10);
end;
$dbvis$ LANGUAGE plpgsql

-- when return type is not "SETOF TEXT", but rather "TEXT",  the output is according the documentation.

**Comment by steve-chavez** [comment]
Can you try doing:
```
wget -O- --header='Accept: text/plain' http://127.0.0.1:5438/rpc/test?select=test
```
(Note the `select=test` at the end)

**Comment by steve-chavez** [comment]
Not to say this isn't a bug, I've been getting the same issue with a `SETOF bytea` and `application/octet-stream`.

Also a report on gitter chat with `setof jsonb`: https://gitter.im/begriffs/postgrest?at=5eff89e047fdfd21ed0031d1.

**Comment by dmkuzsib** [comment]
Yes, request of the URL suggested returns AAAAA terminated with new line.
Thanks for a workaround :)
D.

**Comment by dmkuzsib** [comment]
Great news, thanks!
When you expect to make a release with this bug fixed ?

Thanks!
