### ISSUE TITLE
postgrest: Cannot decode byte '\xfc': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream

### ISSUE THREAD

**Issue by frameworker2019** [PostgREST/postgrest#1585]
I cannot get run postgREST 7.0.1 with PG 12.3. I'm using the Docker-based installation, after starting the Docker I can see the following, private settings replaced by *:
```
Starting REST-API Service...
serving "token" at http://127.0.0.1:3001
tcp6       0      0 [::]:3001               [::]:*                  LISTEN
Connecting to database postgres://authenticator:****@*****:5433/***** ...
Attempting to connect to the database...
Listening on port 3000
postgrest: Cannot decode byte '\xfc': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
```
When I start the same Docker connecting to Postgres 11.3, the error message will not be displayed and subsequent requests could be delivered successfully:

Postgres will be installed by locale "German_Germany.1252", but this is also the case for the running PG11.3:
```
Starting REST-API Service...
serving "token" at http://127.0.0.1:3001
tcp6       0      0 [::]:3001               [::]:*                  LISTEN
Connecting to database postgres://authenticator:****@*****:5432/***** ...
Attempting to connect to the database...
Listening on port 3000
Connection successful
````

**Comment by steve-chavez** [comment]
Do both pg containers(11.3 and 12.3) have the same schema?

Also, can you provide a sample schema so we can reproduce the error?

**Comment by frameworker2019** [comment]
Yes, they points to the same database, Schema=public.
I can start with a simple "create database ptest;" for instance without any table created to produce the error start message.
So it doesn't matter whether I create a table or not. Subsequent calls doesn't work at all.
So what do you mean with "provide a sample schema"? The only thing which might be of interest is, that we're working with Windows 10 Enterprise LTSC Release.
Could be that a reason for? 
Because all databases will be created with UTF8 decoding (checked by \l) , I doesn't understand the error message on startup.

**Comment by wolfgangwalther** [comment]
Can you show the output of plsql's \l?

I'm just guessing here, but this sounds like the client encoding for this connection is not set to UTF8. This should default to the database encoding, but maybe something has gone wrong.

Can you try `ALTER DATABASE ptest SET client_encoding='UTF8';` on pg12?

**Comment by frameworker2019** [comment]
```
ptest=# \l
                                           Liste der Datenbanken
     Name     | Eigent³mer | Kodierung |    Sortierfolge     |     Zeichentyp      |  Zugriffsprivilegien
--------------+------------+-----------+---------------------+---------------------+-----------------------
 postgres     | postgres   | UTF8      | German_Germany.1252 | German_Germany.1252 |
 ptest        | postgres   | UTF8      | German_Germany.1252 | German_Germany.1252 |
 template0    | postgres   | UTF8      | German_Germany.1252 | German_Germany.1252 | =c/postgres          +
              |            |           |                     |                     | postgres=CTc/postgres
 template1    | postgres   | UTF8      | German_Germany.1252 | German_Germany.1252 | =c/postgres          +
              |            |           |                     |                     | postgres=CTc/postgres
(6 Zeilen)
```

But what about client encoding setting by starting the postgrest Binary inside the Docker?
There's not advice in the manual to do changes in the shell enviroment of the docker.

**Comment by frameworker2019** [comment]
> Can you show the output of plsql's \l?
> I'm just guessing here, but this sounds like the client encoding for this connection is not set to UTF8. This should default to the database encoding, but maybe something has gone wrong.
> Can you try ALTER DATABASE ptest SET client_encoding='UTF8'; on pg12?

Please keep in mind I have no problem to access the database via psql. I have problems to start the postgREST API software which obv. have a problem to connect.

**Comment by wolfgangwalther** [comment]
Citing the postgres manual at https://www.postgresql.org/docs/current/multibyte.html:

> On most modern operating systems, PostgreSQL can determine which character set is implied by the LC_CTYPE setting, and it will enforce that only the matching database encoding is used. On older systems it is your responsibility to ensure that you use the encoding expected by the locale you have selected. A mistake in this area is likely to lead to strange behavior of locale-dependent operations such as sorting.

While this doesn't apply directly, the mixture of UTF8 and German_Germany.1252 looks suspicious. Does psql show the same for the pg11 database?

Maybe you try creating the database like this:
```CREATE DATABASE ptest WITH ENCODING 'UTF8' LC_COLLATE='UTF8' LC_CTYPE='UTF8';```

> But what about client encoding setting by starting the postgrest Binary inside the Docker?
There's not advice in the manual to do changes in the shell enviroment of the docker.

Currently, postgrest does not set `client_encoding` at all. I guess that means, that the server-side setting is used. The server is using the database encoding as a default - but maybe that's somehow mixed up. There are many ways to change the client_encoding (see https://www.postgresql.org/docs/current/multibyte.html) - I suggested to use `ALTER DATABASE`, because it's the easiest one for you to test, without the need to change environment variables in the docker container or hi-jack the connection itself... so what was the result? Did it help?

**Comment by frameworker2019** [comment]
No, PG11 doesn't show this behavior as I told it above.
So, the combination of UTF8 and  German_Germany.1252  works definitively in PG11 with PostgrREST 6.0.2 and 7.0.1. 
So I'm expecting the same behavior in the most current versions without changes to encoding and collation.
The error comes directly when starting the postgrest binary inside the UNIX shell:

```
postgrest@3765b5900918:/usr/local/bin$  /usr/local/bin/postgrest /etc/postgrest.conf
Attempting to connect to the database...
Listening on port 3000
postgrest: Cannot decode byte '\xfc': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
^C
```

I will try to create a database with collation utf8...

**Comment by frameworker2019** [comment]
> Maybe you try creating the database like this:
> CREATE DATABASE ptest WITH ENCODING 'UTF8' LC_COLLATE='UTF8' LC_CTYPE='UTF8';

On a german system it seems  you cannot create a UTF8 collated database, based on a normal installation here I can choose between C, POSIX and German_Germany.1252

**Comment by wolfgangwalther** [comment]
> > Maybe you try creating the database like this:
> > CREATE DATABASE ptest WITH ENCODING 'UTF8' LC_COLLATE='UTF8' LC_CTYPE='UTF8';
> 
> On a german system it seems you cannot create a UTF8 collated database, based on a normal installation here I can choose between C, POSIX and German_Germany.1252

Sorry, both the LC_ settings should probably be something like `de_DE.UTF8`. Not sure whether that works on Windows at all, though.

Did you try the `ALTER DATABASE` for client_encoding? If that works, we should be able to just set the the client_encoding on connection to UTF-8 by default in postgrest...

**Comment by frameworker2019** [comment]
Yes, I've tried it. Doesn't help. For postgrest/postgrest:latest, so the UNIX box with postgrest, maybe the PGCLIENTENCODING environment variable is more relevant?
https://www.postgresql.org/docs/current/multibyte.html:
```
Using PGCLIENTENCODING. If the environment variable PGCLIENTENCODING is defined in the client's environment, that client encoding is automatically selected when a connection to the server is made. (This can subsequently be overridden using any of the other methods mentioned above.)
```
But I've tried it also to change PGCLIENTENCODING=UTF8 before starting the postgrest process. The error still remains.
We have to know how postgrest on UNIX opens its connection and whether PGCLIENTENCODING will be overridden or not.

**Comment by wolfgangwalther** [comment]
I can reproduce with a fresh install of PG 12.3 on Windows. However, doing the same with PG 12.4 works fine! Can you upgrade as well?

**Comment by frameworker2019** [comment]
Yes, we made the update already to 12.4. Investigations goes on here, it points out that if you running postgrest inside a docker container, the Docker Hyper V NAT must be registered in pg_hba.conf if your're using a Postgres installation on the host where the docker runs.
More tests are outstanding here to prove this workaround.

**Comment by frameworker2019** [comment]
The error occurs if the database cannot be reached due to TCP/IP timeouts when docker and the network of the host uses the same network segment. In such a case the "could not connect to server: Host is unreachable" will not be thrown. Instead the misleading encoding error appears.

The same error occurs also if the database user has no login rights for example.

I think for both cases the message "postgrest: Cannot decode byte '\xfc': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream" is not correct and leads the user in a  wrong direction.

**Comment by wolfgangwalther** [comment]
I can confirm. On my PG 12.3 installation I was missing the login rights for the postgrest user. After granting those permissions, everything worked.

The decoding error is caused by german umlauts or other "special characters" in the error messages. **When I set `lc_messages = 'English_UnitedStates.1252'` instead of `lc_messages = 'German_Germany.1252'` in `postgresql.conf`, I get proper error messages without decoding errors.** The issue is that postgres sends those error messages with ISO-8859-1 equivalent encoding instead of UTF8 - even when `client_encoding = 'UTF8'` is set. It seems like `client_encoding` only kicks in after the connection is successful.

When I connect to postgres under the same circumstances through pgjdbc, I get the following error message:

> FATAL: kein pg_hba.conf-Eintrag für Host »192.168.0.2«, Benutzer »postgres«, Datenbank »postgres«, SSL aus (pgjdbc: autodetected server-encoding to be ISO-8859-1, if the message is not readable, please check database logs and/or host, port, dbname, user, password, pg_hba.conf)

I was not able to reproduce with postgres running on linux (in a docker container) so far.

So pgjdbc seems to be able to detect the encoding properly. That makes me wonder: Can we do the same in PostgREST to display the real error messages? Or is this decoding error already happening in Hasql?

@steve-chavez any ideas?
