### ISSUE TITLE
Extra headers not included in non-200 HTTP status codes

### ISSUE THREAD

**Issue by agrrd** [PostgREST/postgrest#1594]
### Environment

* PostgreSQL version: 12
* PostgREST version: 7.0.1
* Operating system: Ubuntu 16.04

### Description of issue
I am trying to create a stored procedure that responds with a redirect 301 status error. By following [this section ](http://postgrest.org/en/v7.0.0/api.html?highlight=just_fail#errors-and-http-status-codes) I created the function described below. The expected behavior is that the HTTP response includes the Location header, but it is not being included.

```
CREATE OR REPLACE FUNCTION redirect ()
  RETURNS void
  LANGUAGE plpgsql
  AS $$
BEGIN
  --
  -- add http response header
  PERFORM
    set_config('response.headers', '[{"Location": "https://www.somesite.com"}]', FALSE);

  --
  -- raise error
  RAISE sqlstate 'PT301'
  USING message = 'Redirecting';
END
$$;
```
```
curl -v http://localhost:3000/rpc/redirect
*   Trying 127.0.0.1:3000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /rpc/redirect HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Redirecting
< Transfer-Encoding: chunked
< Date: Sun, 27 Sep 2020 00:28:47 GMT
< Server: postgrest/7.0.1 (UNKNOWN)
< Content-Type: application/json; charset=utf-8
< 
* Connection #0 to host localhost left intact
```

By removing the RAISE exception the extra header is included (200 status code)
```
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Date: Sun, 27 Sep 2020 00:40:25 GMT
< Server: postgrest/7.0.1 (UNKNOWN)
< Content-Type: application/json; charset=utf-8
< Content-Range: 0-0/*
< Location: https://www.somesite.com
```

**Comment by wolfgangwalther** [comment]
That's expected. When you raise an error nothing is returned from the query - so the custom headers you set are lost.

A `3xx` status code is not an error as well, so raising one seems the wrong thing to do. You can also set the status code via the GUC `response.status` - see http://postgrest.org/en/latest/api.html#setting-response-status-code.

**Comment by agrrd** [comment]
Setting the status code via the GUC as you suggested solves my problem. Thanks for responding.
