### ISSUE TITLE
NOW() works but TO_TIMESTAMP() does not

### ISSUE THREAD

**Issue by impala454** [PostgREST/postgrest#1597]
### Environment

* PostgreSQL version: `postgres:11`
* PostgREST version: `postgrest/postgrest:latest`
* Operating system: `Unraid`

### Description of issue

I'm not sure if this is supposed to work or not but I don't see why not.  If I am issuing a POST to my postgrest instance and use `NOW()` as the value for a `timestamp without time zone` column it works fine.  If I issue the same POST with `TO_TIMESTAMP(1601482798)` postgrest returns a failure code `22007` with message: ```invalid input syntax for type timestamp: \"TO_TIMESTAMP(\"1601482798\")\"```

Here's the table definition:

    CREATE TABLE public.weather_wind
    (
        datetime timestamp without time zone NOT NULL,
        speed double precision NOT NULL,
        direction integer NOT NULL,
        CONSTRAINT weather_wind_pkey PRIMARY KEY (datetime)
    )

I'm issuing the POST via Postman just as a test environment
![wind_post_test](https://user-images.githubusercontent.com/2024649/94714006-22511a80-0311-11eb-86fd-c6b9b2061a6c.JPG)

**Comment by impala454** [comment]
Also note I have tried varying combinations of quoted/non-quoted epoch values entered in for the value.

**Comment by steve-chavez** [comment]
Hey @impala454. Arbitrary functions cannot be called in a POST value. I'm actually impressed by the `now` value working. This seems to happen because it's a special value that converts to timestamp.
```sql
-- You can add parentheses to any of these
select 'now'::timestamp;
         timestamp
----------------------------
 2020-09-30 12:10:49.724978

-- Some other values that work
select 'tomorrow'::timestamp;
      timestamp
---------------------
 2020-10-01 00:00:00
select 'yesterday'::timestamp;
      timestamp
---------------------
 2020-09-29 00:00:00
```
For calling `to_timestamp`, one option could be to create a [stored procedure](http://postgrest.org/en/v7.0.0/api.html#stored-procedures) that does the INSERT.

**Comment by impala454** [comment]
@steve-chavez ok thanks, and I can call a stored procedure via the POST command?

**Comment by steve-chavez** [comment]
Yes, check here: http://postgrest.org/en/v7.0.0/api.html#stored-procedures.

**Comment by impala454** [comment]
Got it, awesome.  I'll do that and comment with the solution here just for later googlers sake.  Thanks!

**Comment by impala454** [comment]
Just for the sake of anyone watching along, creating the function below and then calling it with a POST via `http://myinstance/rpc/wind_insert` and JSON key/values that match the parameters did the trick.  Minor note, since this is an insert, I had to mark it as `VOLATILE`

    CREATE OR REPLACE FUNCTION public.wind_insert(_epoch bigint, _speed double precision, _direction integer)
        RETURNS void
        LANGUAGE 'sql'
        VOLATILE 
    AS $BODY$
        INSERT INTO weather_wind(datetime, speed, direction)
        VALUES (TO_TIMESTAMP(_epoch), _speed, _direction)
    $BODY$;
