### ISSUE TITLE
Suggestion: Rollback transaction by setting HTTP header

### ISSUE THREAD

**Issue by wolfgangwalther** [PostgREST/postgrest#1598]
I'm doing some automated testing in my projects, where I send requests through PostgREST to my database layer. Some of them are `POST`, `PATCH` and `DELETE` requests. It would be cool, if I was able to set a http header for those requests to make them rollback the transaction after execution. So the requests would execute just the same and also return the same response - but only at the end the transaction is rolled back. This would make it easier to write tests that depend on a clean database and are executed multiple times.

This could also make some of the postgrest internal unit tests easier to write. I think quite a few of them "depend" on each other in a sense that each test must be careful what PK values to insert into tables, because those might already be used by other tests.

I couldn't find any standard header that would be suitable for this, so it would probably be something like `X-PGRST-TX: commit|rollback`, where `commit` would be the default if the header was omitted?

Thoughts?

**Comment by steve-chavez** [comment]
I actually did something like this sometime ago in an attempt to speed our tests. I can't remember exactly but code-wise it was very simple. As you mention some tests depend on each other, so I ended up not including it because of test failures.

> X-PGRST-TX: commit|rollback, where commit would be the default if the header was omitted?

I also don't know of any standard header. I recall seeing that using X- headers are not recommended([RFC 6648](https://tools.ietf.org/html/rfc6648)) so perhaps we could use `PGRST-TX`? Or maybe a `Prefer: tx=rollback`?

> Thoughts?

Is there any misuse potential?

**Comment by wolfgangwalther** [comment]
> As you mention some tests depend on each other, [...]

Yes, that's two kind of dependencies. For some tests the result of a previous request needs to stay put. But for some it's actually an obstacle. I thought about putting the whole thing in a config-option, to rollback every request by default for tests - but that would not allow exactly what you mention here. With the header-based approach those requests would just not set the header - done.

> I also don't know of any standard header. I recall seeing that using X- headers are not recommended([RFC 6648](https://tools.ietf.org/html/rfc6648)) so perhaps we could use `PGRST-TX`?

Oh, didn't know about that - thanks for the hint. I am reading the RFC in a way, that we should not even use a PGRST prefix here:
> [...] against the use of "X-" **and similar constructs** in the names of such parameters."

> Or maybe a `Prefer: tx=rollback`?

Or even just `Prefer: rollback` - since "commit" will never have to be used anyways?

There is also the "Preference-Applied Response Header Field" described in [RFC 7240](https://tools.ietf.org/html/rfc7240). It would make a lot of sense to set `Preference-Applied: rollback` on the response, to make the receiver aware of that.

> Is there any misuse potential?

I can't think of any - but maybe I am not creative enough here.

The feature could also be hidden behind a config-option, if needed.

**Comment by steve-chavez** [comment]
>  It would make a lot of sense to set Preference-Applied: rollback on the response, to make the receiver aware of that.

Absolutely. We should respond with a `Preference-Applied` for all `Prefer` reqs.
(We're missing this in some cases: https://github.com/PostgREST/postgrest/issues/740)

> The feature could also be hidden behind a config-option, if needed.

I think this would be the safest option. How about an `allow-rollback = false/true` config option?
