### ISSUE TITLE
Discard columns with null values

### ISSUE THREAD

**Issue by jsommr** [PostgREST/postgrest#1601]
Say I have a polymorphic table `contact` that can be either `person` or `company` (each in their own table):

```sql
create type contact_type as enum (
  'company',
  'person'
);

create table contact (
  contact_id   uuid         primary key default uuid_time_nextval(),
  contact_type contact_type not null
);

create table company (
  company_id   uuid primary key references contact,
  company_name text not null
);

create table person (
  person_id      uuid primary key references contact,
  preferred_name text not null,
  email          text not null
);
```

With insert triggers on company and person ensuring a contact with the same id is inserted as well.

We create a view that combines them:

```sql
create view v1.contact as
  select 
    contact.*,
    c.company_name,
    p.preferred_name,
    p.email
  from contact
  left join company c on contact_id = company_id
  left join person p on contact_id = person_id;
```

With a little sample data, requesting this via `/contact?select=*` returns:

```json
[
  {
    "contact_id": "546137e0-cda5-4e24-b684-94d030bfcf42",
    "contact_type": "company",
    "company_name": "Nerfpops Incorporated",
    "preferred_name": null,
    "email": null
  },
  {
    "contact_id": "54772635-7feb-438a-b4ee-251e23684e51",
    "contact_type": "person",
    "company_name": null,
    "preferred_name": "Nerfpops",
    "email": "email@example.com"
  }
]
```

Is there any way to tell PostgREST not to include fields that are null in the JSON response? Even if I explicitly asked for the field, I'd still prefer not to have it in the response.

**Comment by steve-chavez** [comment]
Hey @nerfpops. Looks like this might be possible with [json_strip_nulls](https://www.postgresql.org/docs/current/functions-json.html#id-1.5.8.22.5.11.2.2.16.1.1.1).

Right now we use a query similar to:
```sql
WITH
pgrst_source AS (SELECT "test"."projects".* FROM "test"."projects"    )
SELECT coalesce(json_agg(_postgrest_t), '[]')::character varying AS body
FROM ( SELECT * FROM pgrst_source) _postgrest_t;

-- and this gives
[{"id":1,"name":"Windows 7","client_id":1},
 {"id":2,"name":"Windows 10","client_id":1},
 {"id":3,"name":"IOS","client_id":2},
 {"id":4,"name":"OSX","client_id":2},
 {"id":103,"name":"hey","client_id":null},
 {"id":104,"name":"hey","client_id":null},
 {"id":105,"name":"hello","client_id":null},
 {"id":106,"name":"hello","client_id":null},
 {"id":107,"name":"hello","client_id":null}]
```

Adding `json_strip_nulls` would lead to:

```sql
WITH
pgrst_source AS (SELECT "test"."projects".* FROM "test"."projects"    )
SELECT coalesce(json_strip_nulls(json_agg(_postgrest_t)), '[]')::character varying AS body
FROM ( SELECT * FROM pgrst_source) _postgrest_t;

-- and this gives
[{"id":1,"name":"Windows 7","client_id":1},
 {"id":2,"name":"Windows 10","client_id":1},
 {"id":3,"name":"IOS","client_id":2},
 {"id":4,"name":"OSX","client_id":2},
 {"id":103,"name":"hey"},
 {"id":104,"name":"hey"},
 {"id":105,"name":"hello"},
 {"id":106,"name":"hello"},
 {"id":107,"name":"hello"}]
```

Maybe we could add a `Prefer: nullfields=false`(not sure about the name) for using the latter query.

**Comment by nerfpops** [comment]
That makes sense. It would help in the other issue I created, which I closed because I think it would make better sense to use the tables below, which would still return null for one of the columns:

```sql
create table company (
  company_id   uuid primary key default uuid_time_nextval(),
  company_name text not null
);

create table person (
  person_id      uuid primary default uuid_time_nextval(),
  preferred_name text not null,
  email          text not null
);

-- union table
create table contact (
  contact_id uuid primary key default uuid_time_nextval(),
  company_id uuid references company,
  person_id  uuid references person
  -- some check constraint ensuring either company_id or person_id i set
);

create table invoice (
  invoice_id uuid primary key default uuid_time_nextval(),
  contact_id uuid not null references contact
);
```

Which allows one to request `/invoice?select=*,contact(company(*),person(*))` and the result would be

```json
[
  {
    "invoice_id": "573dcb44-da9f-41c5-8a51-22c22cd077b6",
    "contact_id": "546137e0-cda5-4e24-b684-94d030bfcf42",
    "contact": {
      "company": {
        "company_id": "546137e0-cda5-4e24-b684-94d030bfcf42",
        "company_name": "Nerfpops Incorporated"
      },
      "person": null
    }
  }
]
```

Where `Prefer: nullfields=false` would eliminate nulls, and with bigger union tables, a lot of nulls can be avoided.

**Comment by wolfgangwalther** [comment]
> Maybe we could add a `Prefer: nullfields=false`(not sure about the name) for using the latter query.

Maybe `Prefer: strip-nulls`?

Because it only affects the json returns and not csv or others, it could also be a parameter of the accept header: `Accept: application/json;strip-nulls` and `Accept: application/vnd.pgrst.object+json;strip-nulls`. That would also match the "I want a JSON object instead of an array, so I have to set a different accept header." philosophy.

**Comment by nerfpops** [comment]
I like the thought about using the accept header and not polluting prefer with more settings. Personally I just avoid null like the plague and would have strip-nulls in all requests.

**Comment by steve-chavez** [comment]
I also like the idea of using an Accept instead of a Prefer. 
However, according to [RFC 6838](https://tools.ietf.org/html/rfc6838#section-4.3) we shouldn't add parameters to standard media types.

> the names, values, and meanings of any parameters MUST be fully specified when a media type is registered in the standards tree, and SHOULD be specified as completely as possible when media types are registered in the vendor or personal trees.

How about using an `application/vnd.pgrst.json;strip-nulls` type?

**Comment by wolfgangwalther** [comment]
I stumbled on this in the RFC as well. Probably makes sense to use another type here. I suggest to rename it slightly (`application/vnd.pgrst.array+json`), to fit the other custom type we have. Or list instead of array?

Also, I think `strip-nulls` was not chosen very well by me, because it is an imperative. That did make sense for `Prefer`, however when describing a mime type, it would be better of in a passive form like `;nulls=stripped` or just `;stripped`, describing the "state" the document is in - because we should also set this as `Content-Type` on the response. An imperative on the response makes no sense.

So I suggest:
- add `application/vnd.pgrst.array+json` as an accepted mimetype
- add `;stripped` to both `application/vnd.pgrst.array+json` and `application/vnd.pgrst.object+json`
- make `application/json` an alias of `application/vnd.pgrst.array+json` (without any parameters)

**Comment by steve-chavez** [comment]
> application/vnd.pgrst.array+json

For `application/vnd.pgrst.object` we validate that the result should contain 1 row only, otherwise we err.
So for the `vnd.pgrst.array+json` type, should we validate that the rows are greater than 1?
(The naming kind of suggests we should)

If we do the above then we'd need another type that can hold both the array and the object.

**Comment by wolfgangwalther** [comment]
> So for the `vnd.pgrst.array+json` type, should we validate that the rows are greater than 1?
> (The naming kind of suggests we should)

No, I think an empty array is perfectly valid. Also an array of length 1 is just that - an array.

However, an object always represents one row - you can't make it represent more than 1 or 0 rows. That's why there's an error.

**Comment by steve-chavez** [comment]
> No, I think an empty array is perfectly valid. Also an array of length 1 is just that - an array.

Right, I forgot about that.

> ;nulls=stripped or just ;stripped

Is it possible to just call it `;stripped`? I've looked at [RFC2231](https://tools.ietf.org/html/rfc2231#section-7) and it doesn't seem so. It says the parameter must have an `=`.
In that case we should use `;nulls=stripped`, it also looks more descriptive.

**Comment by wolfgangwalther** [comment]
Yes, you're right. I remember reading something about how an empty value and no value are the same thing, but I must have mixed that up with the `Prefer` stuff. `;nulls=stripped` sounds good!

I also looked around for some mime type parameter examples and the closest one to a boolean/2-state parameter that I could find was [text/csv](https://www.iana.org/assignments/media-types/text/csv), which has `;header=present|absent`. This might actually be something that we could easily implement as well, I think? At least we could be sending `Content-Type: text/csv; header=present` for a start.

**Comment by steve-chavez** [comment]
> This might actually be something that we could easily implement as well, I think? At least we could be sending Content-Type: text/csv; header=present for a start.

Yes, that would be good. I recall that `present|absent` was asked on an issue(or gitter) before, but I can't seem to find it.

**Comment by Sjoerd82** [comment]
I have a similar requirement (392) that turned out to be a dup of this issue. Last activity was half a year ago. Any updates/progress since then?

An important benefit of removing null fields is the download size of which field names may take up a large portion!

**Comment by wolfgangwalther** [comment]
> Last activity was half a year ago. Any updates/progress since then?

I think design-wise this feature is pretty much done. But we have a lot more ideas than we can implement at any time.

If you'd like to give this a shot, feel free! PR would be very much welcome!

**Comment by Sjoerd82** [comment]
I had a look at the code, but I'm not a Haskell developer, and fear I may accidentally break something.  If I summarize this thread so far, the solution is:

- add `application/vnd.pgrst.array+json` as an accepted mimetype
- add `;nulls=stripped` to both `application/vnd.pgrst.array+json` and `application/vnd.pgrst.object+json`
- make `application/json` an alias of `application/vnd.pgrst.array+json` (without any parameters)
