### ISSUE TITLE
Using of custom functions in WHERE clause

### ISSUE THREAD

**Issue by saranhada** [PostgREST/postgrest#1613]
We constantly face necessities to preprocess table fields before using them in WHERE conditions.
Preprocessing sometimes include sophisticated actions.

```
For instance we might have a table:
user {
  id serial,
  logins text[]
}
and the data:

- 0, [admin, administrator, superAdmin]
- 1, [user, regularUser]
- 2, [regularUser]
```

The current status of postgrest doesnt provide any feature to find a user whose login include 'admin' word in any case.

But it would be possible if there were a feature to construct request similar to the:

```
select *
from users 
where  array_text_to_text(logins) @> array['ADMIN']

create or replace function array_text_to_text(v text[])
   returns text[]
as
$$
begin
    return (upper(v::text))::text[];
end;
$$
language plpgsql;
```

it would be nice to construct a rest query similar to the:

....?**array_text_to_text**.users=cs.{ADMIN}

Would it be possible to estimate such a feature?

**Comment by saranhada** [comment]
> enhancement

**Comment by steve-chavez** [comment]
Try turning your `array_text_to_text` function to a [computed column](http://postgrest.org/en/v7.0.0/api.html#computed-columns).

Then you'll be able to call it like `/users?array_text_to_text=cs.{ADMIN}`.

**Comment by wolfgangwalther** [comment]
You can already achieve what you're trying to do in one of the following ways:
- As for this specific case, using `citext` instead of `text` might already be all you need: https://www.postgresql.org/docs/current/citext.html
- If that doesn't work you can always do the pre-processing in a view - even though that changes output columns as well:
```sql
CREATE VIEW api.user AS
SELECT id,
       your_function(logins) AS logins
  FROM data.user
```
- If you want to keep your output columns the same, you can also create a virtual column like this:
```sql
CREATE FUNCTION logins_upper (u user) RETURNS text[]
LANGUAGE SQL AS $$
  SELECT your_code_around_this(u.logins)
$$;
You can then query it like this: `GET /users?logins_upper=cs.{ADMIN}`

**Comment by saranhada** [comment]
Indeed, the documentation mentions the calculated columns could be used in SELECTs, but it is not clear they could be used for filtering. 

Thank you!
