### ISSUE TITLE
Does `postgrest` have a "fail fast" mode?

### ISSUE THREAD

**Issue by yaobinwen-mvs** [PostgREST/postgrest#1614]
(I'm a new user of PostgREST so I may not have learned all the possible options/features but have tried my best.)

### Environment

* PostgreSQL version: Docker image [`postgres` 13](https://github.com/docker-library/postgres/blob/8d281112a872380578e37a92a698ce59d66473d7/13/Dockerfile)
* PostgREST version: 7.0.1, downloaded at [this link](https://github.com/PostgREST/postgrest/releases/download/v7.0.1/postgrest-v7.0.1-linux-x64-static.tar.xz).
* Operating system: Ubuntu 18.04

### Description of question

**Does `postgrest` have a _"fail fast"_ mode instead of retrying by itself?** Specifically, I'm hoping that if `postgrest` cannot connect to the database with the `db-uri`, it would exit with an error code instead of retrying to connect over and over again.

Here is **more context**:

- In my project environment, our PostgreSQL database is a Docker container that does **not** publish its service at a pre-determined port. Instead, it publishes the service at a **random port** and `Registrator` registers the service to `Consul`.
- When the machine is restarted thus the PostgreSQL container is restarted, the published port is changed, too. But with the help of `Consul`, we don't have to hard-code any specific host address or port in our code.

However, it seems that `postgres` only reads the configuration `db-uri` once and keeps using it for connection. The PR ["Enable config file re-reading with SIGUSR2" (and the related issues)](https://github.com/PostgREST/postgrest/pull/1544) says the change to `db-uri` requires a restart of `postgrest`.

Besides, it seems that `postgrest` automatically keeps retrying to connect to the database at `db-uri` but doesn't have an option to exit with an error code.

**But what I want to implement is**:

- I want to start `postgrest` as a `systemd` service.
- It is possible that, when `postgrest` service is started due to restarting the machine, the PostgreSQL container is not fully up yet (or at least not re-registered to `Consul` so `Consul` may still have the out-dated address and port of the previous PostgreSQL container).
- So, if `postgrest` fails to connect the database using whatever is in its current configuration file, **I hope `postgrest` could exit with an error code that can be captured by `systemd` so `systemd` would automatically restart it.**
- Unlike what is documented in [Daemonizing](http://postgrest.org/en/v7.0.0/admin.html#daemonizing), I will wrap up the call of `postgrest` with a shell script that obtains from `Consul` the latest address and port of the PostgreSQL container, updates the `postgrest` configuration file, and then starts it.

So I'm wondering if `postgrest` already implements this "fail fast" behavior or not. Any help/suggestions/thoughts would be appreciated!

**Comment by steve-chavez** [comment]
> So I'm wondering if postgrest already implements this "fail fast" behavior or not. Any help/suggestions/thoughts would be appreciated!

@yaobinwen-mvs No, right now the connection recovery is not optional.

I don't see any other way of supporting your use case than to have a config option to disable the recovery. It could be named `disable-recovery`, false by default.

Not sure of the implications of such a config. A PR would be welcomed though.

**Comment by yaobinwen-mvs** [comment]
@taimoorzaeem Thank you for your follow-up work! I'll surely check it out! (Somehow I overlooked the notification from @steve-chavez 's comment about 3 years ago.. But last night I got the notification about the PR merging.)
