### ISSUE TITLE
SUGGESTION - api "signal handler" to reset cache - SIGUSR1

### ISSUE THREAD

**Issue by mpasquini** [PostgREST/postgrest#1622]
It is possible to have an api call to the signal handler ? 

> Before reporting a bug:
> If your database schema has changed while the PostgREST server is running,
> send the server a SIGUSR1 signal or restart it(http://postgrest.org/en/stable/admin.html#schema-reloading)
> to ensure the schema cache is not stale. This sometimes fixes apparent bugs.

From GNU: 

> These signals are used for various other purposes. In general, they will not affect your program unless it explicitly uses them for something.
> 
> Macro: int SIGUSR1
> Macro: int SIGUSR2
> 
>     The SIGUSR1 and SIGUSR2 signals are set aside for you to use any way you want. They’re useful for simple interprocess communication, if you write a signal handler for them in the program that receives the signal.
>

**Comment by wolfgangwalther** [comment]
> It is possible to have an api call to the signal handler ?

I'm not sure I undestand what you mean - but are you maybe looking for #1542 ? (not released yet)

**Comment by steve-chavez** [comment]
I think @mpasquini might be referring to calling SIGUSR1 through an endpoint, like `/internal/sigusr1`.

It kind of reminds to https://github.com/PostgREST/postgrest/issues/1526 in this regard.

**Comment by wolfgangwalther** [comment]
Ah, ok. That could be done with something like the following already?

```sql
CREATE FUNCTION sigusr1() RETURNS void
LANGUAGE plpgsql AS $$
BEGIN
  NOTIFY pgrst;
END$$;
```

And then call it via `POST /rpc/sigusr1`.

Of course `db-channel-enabled=true` needs to be set.

**Comment by wolfgangwalther** [comment]
Can this be closed?

**Comment by steve-chavez** [comment]
> Of course db-channel-enabled=true needs to be set.

Maybe we should default `db-channel-enabled` to true. We disabled it because of connection poolers https://github.com/PostgREST/postgrest/pull/1542#issuecomment-643767295. However dwagin told us(https://github.com/PostgREST/postgrest/pull/1633#issuecomment-718911934) that hasql-transaction still needs to be patched for poolers to work. We can put a warning about disabling `db-prepared-statements` and `db-channel-enabled` for poolers to work later on, when we're sure we work with them.

**Comment by wolfgangwalther** [comment]
Yes, I agree. In general, we should have a default config that works well for "basic" cases and does not need beginners to set up that much. I'd rather have to tell advanced users that they need to adjust their settings to support connection poolers, than beginners missing out on things like prepared statements for good performance. The same goes for `db-channel-enabled` - it does no harm in a regular setup.
