### ISSUE TITLE
Feature request: Session settings

### ISSUE THREAD

**Issue by LorenzHenk** [PostgREST/postgrest#1623]
## Description

At the moment there's no way to set arbitrary session settings through the PostgREST config.

As far as I know this can be done in the `pre-request` function, though this approach seems a bit overkill for my use-case. I'd rather not create a DB function that's called every time just to set static session settings.

### Use case

I want all values of type `interval` to be formatted as `iso_8601` opposed to the default format `postgres` (where the output is db server language dependent). This makes working with the data in the frontend easier (as it's a normed format and there exist libraries to parse it).
To do this, I need to set the session setting `intervalstyle` to `iso_8601`. It's not possible to set the setting globally on the database.

**Comment by dwagin** [comment]
Use [ALTER ROLE](https://www.postgresql.org/docs/13/sql-alterrole.html)

for example: `ALTER ROLE role_name SET bytea_output = 'escape';`

**Comment by LorenzHenk** [comment]
That should be sufficient, thanks :grin:
