### ISSUE TITLE
Suggestion: choose transaction isolation level for HTTP GET verb basing upon pre_request function's VOLATILE setting.

### ISSUE THREAD

**Issue by ofcaah** [PostgREST/postgrest#1629]
One of possible uses for pre-request function is session handling and request logging. Operations like inserting log entries, or updating user's last activity will obviously fail in read only transaction. Perhaps PostgREST should choose whether transaction should be READ ONLY by checking if pre-request function is defined as VOLATILE?

I also tried doing a SET TRANSACTION as a very first instruction in my pre-request function, but PostgREST already did something in this transaction, so enabling read write is no longer possible. Perhaps those operations could be performed outside of final transaction?

**Comment by wolfgangwalther** [comment]
> One of possible uses for pre-request function is session handling and request logging.

If you do request logging with a pre-request function, you would most likely like log failed requests as well, right? In this case you would need to "bail out" of the transaction via some async process (e.g. pg_background) to be able to log aborted transactions. If you do it this way, the transaction isolation level would not matter.

This is not to say, that your suggestion doesn't have valid use-cases - I can very well imagine it still does.

Technically it should be no problem to get this information with the schema cache and set the isolation level accordingly. Not sure what kind of impact that would have on read replicas - but in a setup like that, you would probably just need to set the volatility to stable.

**Comment by drTr0jan** [comment]
@ofcaah you can use pq_ampq for request logging and dblink/FDW for session handling.

There's a problem while using volatile pre-request function. These requests/transactions could not to be sent to hot standby replicas.

**Comment by ofcaah** [comment]
@drTr0jan thank you for the reply; could you elaborate on using dblink for session handling?

**Comment by wolfgangwalther** [comment]
When using dblink or postgres_fdw, you are creating a new connection to the same (or another) database from within your read only transaction. This new connection runs a different transaction. And this transaction level can be different from the transaction that postgrest runs. So yes, this would allow you to modify the database you connected to. Note, that this is not atomic anymore, so when your outer transaction is rolled back, the changes you made through dblink/fdw are still persisted. But that's exactly what you're looking for.

I fail to see any use case right now, that would benefit from changing the transaction level for volatile pre request functions. If any of those come up in the future, feel free to reopen again.
