### ISSUE TITLE
invalid 'returning' argument python Client

### ISSUE THREAD

**Issue by PsychicSimp** [PostgREST/postgrest#1634]
### Environment

* PostgreSQL version: (11.9)
* PostgREST version: (latest- 7 point something)
* Operating system:

### Description of issue

So I am using the python client [py-postgrest](https://github.com/Kong/py-postgrest/blob/master/example/main.py]
and when performing an insert query with it I get the error:
```python
invalid 'returning' argument
```
Here is what I did:
```python
 async def create_user(self, first_name, last_name, username, email, password):
        """Adds a user to the StockTools database"""
        print('receiver end')
        async with postgrest.Client(self.host, default_headers={"role": "stocktools"}) as client:
            try:
                print('inside try block')
                user_insert = await client.insert("users", {'last_name': last_name, 'first_name': first_name,
                                                            'user_name': username, 'email': email},
                                                  returning='user_id')
```
I basically want to insert into the database and the insertion process must return a user_id column

(Steps to reproduce: Include a minimal SQL definition plus how you make the request to PostgREST and the response body)
I think I already mentioned it above
thanks!

**Comment by wolfgangwalther** [comment]
I guess this question would fit better in the py-postgrest repo as this is entirely about the python client.

A quick look to the source reveals this:
https://github.com/Kong/py-postgrest/blob/54ce4abf5464e5a303bb20cf2e349c1da0b0b155/postgrest/client.py#L167-L170

```
        returning: pass:
            `"minimal"` to return nothing (required if you don't have read permissions)
            `"url"` returns the url of the created object
            `"representation"` to return the inserted row(s)
```

You probably want to make it `select='user_id'` instead.

**Comment by steve-chavez** [comment]
@PsychicSimp I think Wolfgang's answer should solve your problem.

Also, the issue definitely belongs to https://github.com/Kong/py-postgrest/issues.

Closing here :)
