### ISSUE TITLE
Foreign key not detected in view with COAELSCE + subselect

### ISSUE THREAD

**Issue by benny-medflyt** [PostgREST/postgrest#1635]
### Environment

* PostgreSQL version: 10.11 (AWS RDS)
* PostgREST version: 7.0.1
* Operating system: Linux

### Description of issue

I have a `person` view with an `addressId` column that is a foreign key to the `address_tbl` table.

And now I have an `address` view like this:

```sql
-- (WORKS)
CREATE VIEW address AS
SELECT
    id,
    (SELECT ARRAY_AGG(foo) FROM address_foo WHERE address_foo."addressId" = address_tbl.id) AS foos
FROM
    address_tbl
```

Now I use the request to PostgREST, which **WORKS**:

    GET /person?select=*,addressId(*)

However, when I change the view to:

```sql
-- (BUGGY!)
CREATE VIEW address AS
SELECT
    id,
    COALESCE((SELECT ARRAY_AGG(foo) FROM address_foo WHERE address_foo."addressId" = address_tbl.id), '{}') AS foos
FROM
    address_tbl
```

Then it appears there is a bug, and when I issue the same PostgREST query as above I get the error:

    "Could not find foreign keys between these entities. No relationship found between person and addressId"

No amount of hints is able to help.

I have found a curious workaround: wrap everything in `SELECT * FROM (...)`, like this:

```sql
-- (WORKS!)
CREATE VIEW address AS
SELECT * FROM (
SELECT
    id,
    COALESCE((SELECT ARRAY_AGG(foo) FROM address_foo WHERE address_foo."addressId" = address_tbl.id), '{}') AS foos
FROM
    address_tbl
) z
```

**Comment by wolfgangwalther** [comment]
See #1608.

**Comment by benny-medflyt** [comment]
Thank you, this does indeed appear to be a duplicate of #1608.

What was not mentioned there though, is the workaround of simply wrapping the entire view with `SELECT * FROM (...)`

**Comment by wolfgangwalther** [comment]
Citing myself from the other thread:

> My current solution is to wrap another SELECT around the COALESCE - that works fine.

So as a workaround you can put another SELECT around the COALESCE as well, instead of the whole query.

**Comment by benny-medflyt** [comment]
I see. In any case, I see that a robust fix is in the pipeline so I will patiently be waiting for it :+1:
