### ISSUE TITLE
Permission Denied for POST request always | Client side library

### ISSUE THREAD

**Issue by PsychicSimp** [PostgREST/postgrest#1637]
### Environment

* PostgreSQL version: (11.9)
* PostgREST version: (latest)
* Operating system: Windows

### Permission denied for post requests although the role has permissions [Checked in psql]
So Ive got a role called web_anon for anonymous requests
and a role called todo_user as a trusted user

This is how I've defined my schema:
```python
CREATE SCHEMA api;

CREATE TABLE api.users(
    last_name TEXT,
    first_name TEXT,
    user_name TEXT UNIQUE,
    email TEXT UNIQUE,
    has_premium BOOLEAN DEFAULT FALSE,
    date_created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT GENERATED ALWAYS AS IDENTITY 
    (START WITH 10000000 INCREMENT BY 1) PRIMARY KEY
    );

CREATE TABLE api.passwords(
    encrypted_password TEXT,
    ref_user_id BIGINT,
    FOREIGN KEY(ref_user_id) REFERENCES api.users(user_id) ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE INDEX idx_user_id ON api.users(user_id);
CREATE INDEX idx_user_name ON api.users(user_name);

CREATE ROLE web_anon NOLOGIN;
GRANT web_anon TO postgres;

GRANT USAGE ON schema api TO web_anon;
GRANT SELECT ON api.users TO web_anon;

CREATE ROLE todo_user NOLOGIN;
GRANT todo_user TO postgres;
GRANT USAGE ON schema api To todo_user;
GRANT ALL ON api.users TO todo_user;
GRANT ALL ON api.passwords TO todo_user;
```
This is the role information from the psql:
```python
stocktools=# SELECT table_catalog, table_schema, table_name, privilege_type
stocktools-# FROM   information_schema.table_privileges
stocktools-# WHERE  grantee = 'todo_user';
 table_catalog | table_schema | table_name | privilege_type
---------------+--------------+------------+----------------
 stocktools    | api          | users      | INSERT
 stocktools    | api          | users      | SELECT
 stocktools    | api          | users      | UPDATE
 stocktools    | api          | users      | DELETE
 stocktools    | api          | users      | TRUNCATE
 stocktools    | api          | users      | REFERENCES
 stocktools    | api          | users      | TRIGGER

Role name |                         Attributes                         |      Member of
-----------+------------------------------------------------------------+----------------------
 alfred    |                                                            | {}
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {web_anon,todo_user}
 todo_user | Cannot login                                               | {}
 web_anon  | Cannot login                                               | {}
```

`Expected behaviour vs resultant behaviour`
So I basically am using a [python client](https://github.com/Kong/py-postgrest) for interaction with postgREST
this is how I execute my insert request into the database:
```python
 async def create_user(self, first_name, last_name, username, email, password):
        """Adds a user to the StockTools database"""
        print('receiver end')
        async with postgrest.Client(self.host, default_headers={"role": "todo_user"}) as client:
            try:
                user_insert = await client.insert("users", {'last_name': last_name, 'first_name': first_name,
                                                            'user_name': username, 'email': email},
                                                  returning='representation')
```
according to the library passing the data `{"role": role_name}` changes the role before the request
So I want to change into todo_user before the request because only that role has permission to insert into the table

But I get the following error:
```python
401, message='permission denied for table users', url=URL('http://localhost:3000/users')
```

So I am suspecting that the role isnt even changing before the POST request, but why?
Please help me, thanks

`Steps to reproduce`
- Create the schema inside a database as mentioned above with the above roles
- try to insert data as mentioned above with the coroutine

P.S I have been with this issue for a really long time
a solution will help a lot

**Comment by wolfgangwalther** [comment]
> according to the library passing the data `{"role": role_name}` changes the role before the request
> So I want to change into todo_user before the request because only that role has permission to insert into the table

This is wrong. You are setting a header `ROLE`. That header does not do anything and is just ignored. You need to set a proper authorization header with a JWT, which then includes the role. Please refer to the postgrest docs to see how this can be done:
http://postgrest.org/en/latest/auth.html#client-auth

**Comment by PsychicSimp** [comment]
> > according to the library passing the data `{"role": role_name}` changes the role before the request
> > So I want to change into todo_user before the request because only that role has permission to insert into the table
> 
> This is wrong. You are setting a header `ROLE`. That header does not do anything and is just ignored. You need to set a proper authorization header with a JWT, which then includes the role. Please refer to the postgrest docs to see how this can be done:
> http://postgrest.org/en/latest/auth.html#client-auth

actually in the example given in the py-client github page this was written
```python
--- Set up permissions

-- For demo purposes, we make it so you just specify your role via the HTTP header "role"
create function api_user_role() returns name as $$
	select nullif(current_setting('request.header.role', true), '')::name
	$$ language sql;

-- Special function called by PostgREST before each request
create function pre_request() returns void as $$
	declare
		role name;
	begin
		role := api_user_role();
		if role is not null then
			raise notice 'setting role to %', role;
			perform set_config('role', role, false);
		end if;
	end
	$$ language plpgsql;

create policy api_users_can_do_everything on core.foo to api
	using(true)
	with check(true);


--- Finish up
revoke api from current_user;
```
in the file
https://github.com/Kong/py-postgrest/blob/master/example/api.psql

does it have to do anything with this?

**Comment by wolfgangwalther** [comment]
This seems to be a question that would be much better suited for https://github.com/Kong/py-postgrest/issues.

That being said, note this comment in the example you posted:
```
-- For demo purposes, we make it so you just specify your role via the HTTP header "role"
```

The http header `role` is just used for demo purposes there - but it is non-functional.

**Comment by PsychicSimp** [comment]
Yeah, I got this
I added the pre-request varible inside my config file and that solved the issue

this is my config file:
```python
db-uri = "postgres://authenticatorpwd@localhost/dbname"
db-schema = "api"
db-anon-role = "authenticator"
jwt-secret = "secret"

pre-request = "pre_request"
```
