### ISSUE TITLE
Stored Procedure returning a table type only returns one single row if another function has the same name

### ISSUE THREAD

**Issue by Pigeo** [PostgREST/postgrest#1638]
### Environment

PostgreSQL version: PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
PostgREST version: PostgREST 7.0.1
Operating system: Debian 10 (buster) / Linux LABO-BDD-dev 4.15.18-27-pve #1 SMP PVE 4.15.18-55 (Tue, 17 Mar 2020 15:32:02 +0100) x86_64 GNU/Linux

### Description of issue & steps to reproduce

Let's say you have a view:
```
CREATE OR REPLACE VIEW "films" AS
SELECT * FROM ( VALUES ('2001 Space Odissey'::text), ('Interstellar'::text), ('Gone with the Wind'::text)) film_titles;
```

And you create a Stored Procedure that returns this table type:
```
CREATE FUNCTION my_films() RETURNS SETOF films AS $$
BEGIN
  RETURN query SELECT * FROM films;
END;
$$ LANGUAGE plpgsql IMMUTABLE STRICT;
```

Expected behaviour (and working) is that if you ask `/rpc/my_films` (without any parameters) you'll get all the rows from this view.

Now, you create another Function with completely different signature, but same name:
```
CREATE FUNCTION my_films(int, date, text) RETURNS date
AS $$
BEGIN
RETURN null;
END;
$$ LANGUAGE plpgsql IMMUTABLE STRICT;
```

And here the bug comes: now `/rpc/my_films` will only give you the first row of the view.

The workaround I found is to give names to all parameters of this second function:
```
DROP FUNCTION my_films(int,date,text);
CREATE FUNCTION my_films(foo int, bar date, something text) RETURNS date
AS $$
BEGIN
RETURN null;
END;
$$ LANGUAGE plpgsql IMMUTABLE STRICT;
```

And then it's working normally again.

**Comment by wolfgangwalther** [comment]
The wrong return you have will be fixed with #1615.

However there is still the underlying issue, that in this specific case you are describing the detection of the overloaded function in haskell is broken. This might lead to other issues, e.g. if you declare different volatility between those functions etc. or when you are trying to embed something on the result of the function call. So even with #1615 fixed, this would still be another bug we have to solve.

> The workaround I found is to give names to all parameters of this second function:

This is actually not a workaround, but how you have to do it to be able to call this function at all. Unnamed arguments are not supported (with the exception of a single json argument with `Prefer: params=single-object`).

**Comment by wolfgangwalther** [comment]
> And you create a Stored Procedure that returns this table type:

Just another hint: You should probably not declare the my_films function `IMMUTABLE`, when you have a query returning data from tables inside. Between calls of this function the table could have changed and then you could get wrong results. `STABLE` would fit better here. See https://www.postgresql.org/docs/current/xfunc-volatility.html.

**Comment by Pigeo** [comment]
> This is actually not a workaround, but how you have to do it to be able to call this function at all. Unnamed arguments are not supported (with the exception of a single json argument with `Prefer: params=single-object`).

In my database, the second function (the one with 3 parameters) is not intended to be accessible as a /rpc/ endpoint : it's only for internal use (in views or in other functions). Therefore it needed no named parameters at first. But I had to put some arbitrary names as a work around just to escape this bug.

**Comment by wolfgangwalther** [comment]
Ok, so summarizing: The bug we have to fix here is, that functions with unnamed arguments (except for exactly 1 unnamed json argument) should be completely ignored when parsing the db schema, because we can't do anything with those anyway.
