### ISSUE TITLE
Rest API to drop and create a table

### ISSUE THREAD

**Issue by shogv48** [PostgREST/postgrest#1641]
### Environment

* PostgREST version: using docker image 
* Operating system:

### Description of issue

what the rest API to drop and create a table?

**Comment by wolfgangwalther** [comment]
This is not supported out of the box.

If you need to do this, this could be possible with [Stored Procedures](http://postgrest.org/en/latest/api.html#stored-procedures), though.

If you just want to create your initial database schema, you should not do that through the REST api, but directly in SQL.

**Comment by steve-chavez** [comment]
Additionally, you might want to take a look at [aquameta's meta extension](https://github.com/aquameta/meta).

**Comment by wolfgangwalther** [comment]
Can this be closed?
