### ISSUE TITLE
Unable to disambiguate select of embedded table in presence of view(self-reference)

### ISSUE THREAD

**Issue by dvalentiate** [PostgREST/postgrest#1643]
### Environment

* PostgreSQL version: postgres 11
* PostgREST version: postgrest/postgrest:v7.0.1
* Operating system: MacOS

### Description of issue

It seems having a view disrupts the ability to do a recursive embedded view on table.

The following is the minimal for our recursive table:

```sql
CREATE TABLE api.test (
  id BIGINT NOT NULL PRIMARY KEY,
  parent_id BIGINT CONSTRAINT parent_test REFERENCES api.test(id)
);
GRANT SELECT ON api.test TO api_anon;

INSERT INTO api.test (id, parent_id) VALUES (1, null);
INSERT INTO api.test (id, parent_id) VALUES (2, 1);
```

And `curl -s 'http://bluedrop.test:3000/test?select=id,parent_id,parent_test:parent_id!parent_test(id)' | jq .` gets:

> ```[
>   {
>     "id": 1,
>     "parent_id": null,
>     "parent_test": null
>   },
>   {
>     "id": 2,
>     "parent_id": 1,
>     "parent_test": {
>       "id": 1
>     }
>   }
> ]

Which is fine and the output we are hoping for, **but** then if we add this view:

```sql
CREATE OR REPLACE VIEW api.view_test AS
  SELECT api.test.id FROM api.test
;
```

The same query is now deemed ambiguous:

> ```{
>   "hint": "By following the 'details' key, disambiguate the request by changing the url to /origin?select=relationship(*) or /origin?select=target!relationship(*)",
>   "details": [
>     {
>       "relationship": "parent_test[parent_id][id]",
>       "origin": "api.test",
>       "cardinality": "m2o",
>       "target": "api.test"
>     },
>     {
>       "relationship": "parent_test[parent_id][id]",
>       "origin": "api.test",
>       "cardinality": "m2o",
>       "target": "api.view_test"
>     }
>   ],
>   "message": "More than one relationship was found for test and parent_id"
> }

I can't figure out a valid target and hint that allows for an embed m2o nested object like is returned when the view doesn't exist. I'm not sure if this is a bug or just something I haven't figured out yet.

**Comment by wolfgangwalther** [comment]
The hint says: `disambiguate the request by changing the url to [...] /origin?select=target!relationship(*)`

This leads me to the following two URLs:

- `/test?select=*,test!parent_test(id)`
- `/test?select=*,view_test!parent_test(id)`

Do those work as expected?

**Comment by dvalentiate** [comment]
Thanks for looking into this for me @wolfgangwalther, unfortunately the examples provided don't work as expected.

`/test?select=*,test!parent_test(id)` doesn't work because it picks the o2m relationship of parent with embedded children, see output below, whereas it is desired to have the m2o relationship of child with embedded parent, see example above in the description.

> ```[
>   {
>     "id": 1,
>     "parent_id": null,
>     "test": [
>       {
>         "id": 2
>       }
>     ]
>   },
>   {
>     "id": 2,
>     "parent_id": 1,
>     "test": []
>   }
> ]
> 

The view_test relationship `/test?select=*,view_test!parent_test(id)` does work to create a child with embedded parent, but the embedded view isn't desired. It is just that the presence of the view does cause the problems with self referencing the table for m2o.

**Comment by wolfgangwalther** [comment]
> The view_test relationship `/test?select=*,view_test!parent_test(id)` does work to create a child with embedded parent, but the embedded view isn't desired. It is just that the presence of the view does cause the problems with self referencing the table for m2o.

Yes, I understood that this is not the result you want. Just wanted to check whether this gives the expected result.


> `/test?select=*,test!parent_test(id)` doesn't work because it picks the o2m relationship of parent with embedded children, see output below, whereas it is desired to have the m2o relationship of child with embedded parent, see example above in the description.

Ok, that clears it up for me, thanks. Well not the solution, but the problem that is... ;)

Although I can't find it in the docs, to get parents you would have to name the column

A couple of points, I notice here:

- I can't find anything in the docs on the difference between embedding on the column name and on the table name (parents vs children or m2o vs o2m). Although the tests clearly expect it to work that way:
https://github.com/PostgREST/postgrest/blob/122fea1507116d165717730c6424a3390de7f0ce/test/Feature/EmbedDisambiguationSpec.hs#L317-L334

- If this makes a difference, then whole ambiguous error is just... ambiguous itself. Those 2 items in the list in fact represent 4 possible ways to embed here. What would really help in that case would be to have a list of possible requests (like e.g. `/test?select=*,view_test!parent_test(id)`) and maybe even an explanation what kind of embed that would be.

Looking at your request again: `/test?select=id,parent_id,parent_test:parent_id!parent_test(id)`. So `parent_id` seems to be the one that chooses the kind of relationship you get. We should keep that. But `!parent_test` is indeed ambiguous, because the same foreign key is used when embedding either the table or the view. But the docs say you can also put a table name as a hint. So maybe this works?

```
/test?select=id,parent_id,parent_test:parent_id!test(id)
```

**Comment by steve-chavez** [comment]
@dvalentiate Reproduced :heavy_check_mark:. It's definitely a bug(or current limitation).

## Explanation

The self-referencing embed is kind of tricky and we've been treating it as an special case:

https://github.com/PostgREST/postgrest/blob/122fea1507116d165717730c6424a3390de7f0ce/src/PostgREST/DbRequestBuilder.hs#L134-L140

Basically, a self-reference case has two possible relationships - a **one-to-many(o2m)** to itself and a **many-to-one(m2o)** to itself.
Getting the `m2o` only works when a column from the origin table is specified as a target. In this case:

```http
GET /test?select=id,parent_id,parent_test:parent_id(id)
```
The additional fk hint `!parent_test` is not necessary here.

Getting the `o2m` can be done with:
```http
GET /test?select=id,parent_id,test(id)
```

If we don't treat self-ref as a special case the above would not work and it would always give an ambiguous error.

> So maybe this works?
> /test?select=id,parent_id,parent_test:parent_id!test(id)

@wolfgangwalther Tried that one and it doesn't work. I didn't consider the case of having a VIEW in addition to the self reference. I think we need additional logic for that.

> I can't find anything in the docs on the difference between embedding on the column name and on the table name

That's true. The self reference embed is not yet documented.

## Possible solutions

### Enable the hint on the origin table column workaround

Add the ability to specify the hint `!view` for the self-reference case and document this on [embedding disambiguation](http://postgrest.org/en/v7.0.0/api.html#embedding-disambiguation) as a special case.

### Add the possibility to specify the cardinality as hint

I think this would be the clearer way to solve the self-reference.

Add the possibility to get the **m2o** like:

```http
GET /test?select=id,parent_id,parent_test:test!m2o(id)

[
  {
    "id": 1,
    "parent_id": null,
    "parent_test": null
  },
  {
    "id": 2,
    "parent_id": 1,
    "parent_test": {
      "id": 1
    }
  }
]
```

Or the **o2m** like:

```http
GET /test?select=id,parent_id,child_tests:test!o2m(id)

[
  {
    "id": 1,
    "parent_id": null,
    "child_tests": [
      {
        "id": 2
      }
    ]
  },
  {
    "id": 2,
    "parent_id": 1,
    "child_tests": []
  }
]
```

I've discussed this possibility before on https://github.com/PostgREST/postgrest/pull/1419. It would be easier for users to understand, I think.

---

Thoughts?

**Comment by wolfgangwalther** [comment]
> Add the ability to specify the hint `!view` for the self-reference case and document this on [embedding disambiguation](http://postgrest.org/en/v7.0.0/api.html#embedding-disambiguation) as a special case.

In addition to the column, it should be possible to use the foreign key name as the target to get the m2o relationship. This would allow multi-column self-referencing fks as well.

While I really like the idea of "target=table->array in my output" and "target=column->object in my output" (it feels kind of intuitive for me), I'm not sure this will allow to handle all cases that are theoretically possible. But I am failing right now to come up with some examples.


> Add the possibility to specify the cardinality as hint

If done like this, I suggest to remove the "table vs column as target" approach completely and throw an ambiguous error whenever a self-reference is used without cardinality. This is a breaking change, but will avoid a lot of confusion, I think.

This approach would only work in all cases, however, if it was possible to have multiple hints. Having a combination of multiple self-references and views will quickly bring this to it's limit with only 1 hint.

**Comment by yyqgituser** [comment]
@wolfgangwalther Is there a plan to implement 'specify the cardinality as hint' in future release? Self reference are commonly used in our database and we are evaluating to use PostgREST as REST server.

**Comment by steve-chavez** [comment]
> If done like this, I suggest to remove the "table vs column as target" approach completely and throw an ambiguous error whenever a self-reference is used without cardinality. This is a breaking change, but will avoid a lot of confusion, I think.

Yeah, it'd be a breaking change but I think is the correct way to do it. We could provide a clear error message when there's a `o2m/m2o` to the same table saying that this is a self-reference case and it needs to be disambiguated.

> Is there a plan to implement 'specify the cardinality as hint' in future release?

@yyqgituser Yes, but not soon(we have other stuff pending). Design-wise this is done, you could give it a shot if you'd like. We'll help in reviewing.

**Comment by steve-chavez** [comment]
Hm, nowadays this seems resolvable:

```bash
http 'localhost:3000/test?select=id,parent_id,parent_test:parent_id!parent_test(id)'

{
    "code": "PGRST201",
    "details": [
        {
            "cardinality": "many-to-one",
            "embedding": "test with test",
            "relationship": "parent_test[parent_id][id]"
        },
        {
            "cardinality": "many-to-one",
            "embedding": "test with view_test",
            "relationship": "parent_test[parent_id][id]"
        }
    ],
    "hint": "Try changing 'parent_id' to one of the following: 'test!parent_test', 'view_test!parent_test'. Find the desired relationship in the 'details' key.",
    "message": "Could not embed because more than one relationship was found for 'test' and 'parent_id'"
}

```

The hint is now more helpful and it leads to doing:

```bash
http 'localhost:3000/test?select=id,parent_id,parent_test:view_test!parent_test(id)'

[
    {
        "id": 1,
        "parent_id": null,
        "parent_test": null
    },
    {
        "id": 2,
        "parent_id": 1,
        "parent_test": {
            "id": 1
        }
    }
]

http 'localhost:3000/test?select=id,parent_id,parent_test:test!parent_test(id)'

[
    {
        "id": 1,
        "parent_id": null,
        "parent_test": [
            {
                "id": 2
            }
        ]
    },
    {
        "id": 2,
        "parent_id": 1,
        "parent_test": []
    }
]
```

That being said, I think the main problem here is not the self-reference embedding limitations but how the view suddenly breaks a request. This is also the issue with https://github.com/PostgREST/postgrest/issues/2238.

**Comment by steve-chavez** [comment]
We have another reproducible test here https://github.com/PostgREST/postgrest/issues/2251#issuecomment-1107518757.
