### ISSUE TITLE
Does not connect to PostgreSQL on Azure

### ISSUE THREAD

**Issue by sreealagani** [PostgREST/postgrest#1646]
Azure requires usernames to be provided in the format username@hotname.

The Postgrest's DB_URI is not parsing the connection string if the username is in the above format.

Here is an example of what azure expects: 
postgres://herouser@dbhost:pass123@dbhost.postgres.database.azure.com/dbname

Here is the error when running from Heroku

2020-11-04T18:33:48.762073+00:00 app[web.1]: Attempting to reconnect to the database in 0 seconds...
2020-11-04T18:33:48.975880+00:00 heroku[web.1]: State changed from starting to up
**2020-11-04T18:33:49.764599+00:00 app[web.1]: {"details":"invalid integer value \"pass123@dhost.postgres.database.azure.com\" for connection option \"port\"\n","code":"","message":"Database connection error"}**
Is there a workaround for this?

**Comment by wolfgangwalther** [comment]
According to the [postgres docs](https://www.postgresql.org/docs/12/libpq-connect.html#LIBPQ-CONNSTRING) for a connection string:

> Percent-encoding may be used to include symbols with special meaning in any of the URI parts, e.g. replace = with %3D.

So maybe `postgres://herouser%40dbhost:pass123@dbhost.postgres.database.azure.com/dbname` works?

**Comment by sreealagani** [comment]
That worked , thank you !

**Comment by steve-chavez** [comment]
Closing since it's solved.

Btw, we had this one before: https://github.com/PostgREST/postgrest/issues/1244.
