### ISSUE TITLE
Monitoring endpoint

### ISSUE THREAD

**Issue by adberger** [PostgREST/postgrest#1649]
### Environment

* PostgreSQL version: -
* PostgREST version: v7.0.1
* Operating system: Docker / Kubernetes

### Description of issue

Are there any endpoints for monitoring the running PostgREST instance?
For a monitoring tool and/or for the [probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) of Kubernetes.

**Comment by wolfgangwalther** [comment]
Does #1565 help? Head request on the root endpoint.

**Comment by adberger** [comment]
Thanks, I missed this one.
/closed
