### ISSUE TITLE
Add explicit Prefer return=headers

### ISSUE THREAD

**Issue by wolfgangwalther** [PostgREST/postgrest#1656]
Currently, a POST request returns either:
- both a body and a location header, with `return=representation`
- no body and no location header, with `return=minimal`
- only a location header, without Prefer `return`

It's not possible to explicitly make a request for `return=headers`.

My use-case is that I default to `return=representation` in my library, but want the user to be able to override this to only return the header. Allowing something like `return=headers` explicitly is much easier to handle and understand.

I think this would need to be extended here:

https://github.com/PostgREST/postgrest/blob/8618ffa5fc51ba43c8998f1acda013cc05ff5dc0/src/PostgREST/Types.hs#L87-L90

Is it possible to add some kind of alias here, so that `'return=headers'` and `mempty` both result in `HeadersOnly`?

**Comment by steve-chavez** [comment]
> My use-case is that I default to return=representation in my library, but want the user to be able to override this to only return the header. Allowing something like return=headers explicitly is much easier to handle and understand.

I agree. With this logic we could say that PATCH/DELETE default to `return=minimal` while `POST` defaults to `return=headers-only`.

**Comment by steve-chavez** [comment]
I wonder if we should change the POST default to `return=minimal`.

I've noticed that when newcomers are learning about postgres privileges(RLS, grants), they always have to jump through this hoop. It's always a head-scratcher, and makes postgrest not transparent to PostgreSQL.

I think most users are using `Prefer: return=representation` instead of the `Location` header anyway. Should we change the default and perhaps offer a config for backwards compatibility?

**Comment by wolfgangwalther** [comment]
> I wonder if we should change the POST default to `return=minimal`.
> 
> I've noticed that when newcomers are learning about postgres privileges(RLS, grants), they always have to jump through this hoop. It's always a head-scratcher, and makes postgrest not transparent to PostgreSQL.

I can see your point from the SQL perspective. However from the HTTP perspective, we should definitely default to returning a `Location` header for `POST`, given that the RFC asks for it: https://tools.ietf.org/html/rfc7231#section-4.3.3

> I think most users are using `Prefer: return=representation` instead of the `Location` header anyway. Should we change the default and perhaps offer a config for backwards compatibility?

If we were to change the default, I'd suggest to just change and document it - but I don't think we'd need a config option.

**Comment by steve-chavez** [comment]
> given that the RFC asks for it: https://tools.ietf.org/html/rfc7231#section-4.3.3

Note that the RFC uses the word **SHOULD** though:

> If one or more resources has been created on the origin server as a
result of successfully processing a POST request, the origin server
**SHOULD** send a 201 (Created) response containing a Location header
field that provides an identifier for the primary resource created

Which means **"RECOMMENDED"**, according to [RFC2119](https://www.ietf.org/rfc/rfc2119.txt):

> **SHOULD** This word, or the adjective "RECOMMENDED", mean that there
may exist valid reasons in particular circumstances to ignore a
particular item, but the full implications must be understood and
carefully weighed before choosing a different course.

So we'd still be HTTP compliant despite removing `Location`?
