### ISSUE TITLE
Standard Heroku deploy not available for v7.0.1

### ISSUE THREAD

**Issue by christiaanwesterbeek** [PostgREST/postgrest#1660]
### Environment

* PostgreSQL version: 11
* PostgREST version: 7.0.1
* Operating system: Heroku / Ubuntu

### Description of issue

When following the standard deployment procedure voor PostgREST v7.0.1 to Heroku, the following error occurs during the build fase:

> Could not find prebuilt postgrest-7.0.1

This is because the following line is trying to download the 7.0.1 release for ubuntu

https://github.com/PostgREST/postgrest-heroku/blob/e98f520de3318877191558928e5188b8cdbb7e31/bin/compile#L80

But the Ubuntu executable what not published for v7.0.1. Compare the assets released for v7.0.1 vs v7.0.0 on https://github.com/PostgREST/postgrest/releases

**v7.0.1**
Assets 6
postgrest-v7.0.1-freebsd.tar.xz - 8.64 MB
postgrest-v7.0.1-linux-x64-static.tar.xz - 2.87 MB
postgrest-v7.0.1-osx.tar.xz - 1.69 MB
postgrest-v7.0.1-windows-x64.zip - 8.65 MB
Source code (zip)
Source code (tar.gz)

**v7.0.0**
Assets 7
postgrest-v7.0.0-centos7.tar.xz - 5.52 MB
postgrest-v7.0.0-osx.tar.xz - 1.8 MB
postgrest-v7.0.0-ubuntu.tar.xz - 5.52 MB
postgrest-v7.0.0-ubuntui386.tar.xz - 5.69 MB
postgrest-v7.0.0-windows-x64.zip - 11.1 MB
Source code (zip)
Source code (tar.gz)

**Comment by wolfgangwalther** [comment]
See http://postgrest.org/en/v7.0.0/releases/v7.0.1.html under "Changed":

> From this version onwards, the release page will include a single Linux static executable that can be run on any Linux distribution.

So this needs to be changed in `postgrest-heroku`.

This PR is already tackling this:
https://github.com/PostgREST/postgrest-heroku/pull/29

Apart from some changes, it looks like this PR needs some testing as well. Maybe you can help there, @christiaanwesterbeek?

**Comment by wolfgangwalther** [comment]
As this is tracked in the other repo, I'm closing here.
