### ISSUE TITLE
Stored Procedure that returns a table type is colliding with another homonym stored procedure though having different parameters signature, resulting in unexpected errors

### ISSUE THREAD

**Issue by Pigeo** [PostgREST/postgrest#1672]
### Environment

* PostgreSQL version: PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
* PostgREST version: PostgREST 7.0.1
* Operating system: Debian 10 (buster) / Linux LABO-BDD-dev 4.15.18-27-pve #1 SMP PVE 4.15.18-55 (Tue, 17 Mar 2020 15:32:02 +0100) x86_64 GNU/Linux

### Steps to reproduce:

1. In your public schema, create a function with an optional TEXT param, and returning some rows of a table:

```
create function foobar(optional_param TEXT DEFAULT '') RETURNS SETOF films AS
$$
BEGIN
  RETURN QUERY SELECT * from films;
END;
$$ LANGUAGE plpgsql STABLE;
```

2. A query like `/rpc/foobar?select=id,title,actors!characters(name)` works as expected.

3. Now in the same schema, add another function, with same name, but different signature (e.g. mandatory param of row type + returning a JSONB):

```
create function foobar(mandatory_param "REST_API_v1_0".lemmas) RETURNS JSONB
AS $$
BEGIN
   RETURN '{"foo":"bar"}'::jsonb;
END;
$$ LANGUAGE plpgsql STABLE;
```

3. Here comes the bug: the same query `/rpc/foobar?select=id,title,actors!characters(name)` (as above) doesn't work anymore: 

```
{"message": "Could not find foreign keys between these entities. No relationship found between pgrst_source and actors"}
```

Even a simpler query like `/rpc/foobar?select=id,title` doesn't work anymore :

```
{
    "hint": null,
    "details": null,
    "code": "42703",
    "message": "column pgrst_source.id does not exist"
}
```

(Whereas simplest query `/rpc/foobar?select=*` still works)

=> The bug seems related to the process of verifying existence of given column names (and/or existence of relationship through join tables), which fails to correctly select the function which is returning a SETOF rather than the other homonym function.

4. Work-around: even if they are optional, specify at least one optional parameter (with its default value) in the query, thus giving PostgREST a supplemental hint to identify the proper function.

```
{{ThesocUrl}}/rpc/foobar?select=id,title,actors!characters(name)&optional_param=
```

**Comment by Pigeo** [comment]
I wonder if this bug might be related with #1638 because it has the same side effect, i.e. `/rpc/foobar` only returning one row instead of several as soon as the second foobar() function is created.
However, as you may have noticed above, I took extra care to name all the arguments of my functions, in the hope that this would help to get around the bug, but it is not the case (so basically, the work-around tip given in #1638 is not working here).

**Comment by wolfgangwalther** [comment]
Yes, you're right in assuming that this is caused by wrong identification of overloaded functions. We have recently fixed #1469 and #1638 with #1654. There is a good chance that this will fix your issue as well - but maybe not.

I have just triggered a new nightly build to include that change. It should soon show up [here](https://github.com/PostgREST/postgrest/releases/tag/nightly) and on Dockerhub. Could you try with this build to see if this was fixed already?

**Comment by Pigeo** [comment]
> I have just triggered a new nightly build to include that change. It should soon show up [here](https://github.com/PostgREST/postgrest/releases/tag/nightly) and on Dockerhub. Could you try with this build to see if this was fixed already?

I'm assuming I should try with a build named postgrest-nightly-2020-11-30-… (or even postgrest-nightly-2020-12-…), but I still don't see it [here](https://github.com/PostgREST/postgrest/releases/tag/nightly). Are you sure you triggered a new build correctly? Or perhaps could the build have failed??

**Comment by wolfgangwalther** [comment]
No, the build was successful. We are tagging our nightly images with the date of the last commit, because this is reproducible across different CI environments. `now` is not. The last commit was a couple of days earlier, so the latest (and correct) nightly is: `2020-11-23-19-00-9adec12`.

**Comment by Pigeo** [comment]
Thanks for the clarification. So I tried with the latest nightly build `2020-11-23-19-00-9adec12`, as you suggested, and unfortunately I confirm you that #1638 is now fixed but problems listed above are still there, totally unchanged. So it seems that #1672 is another bug that has not been fixed yet, although in appearance it shares very similar symptoms and context with the #1638 (i.e. `/rpc/foobar?select=*` returning only one row if another homonym function is present).

**Comment by wolfgangwalther** [comment]
Ok, thanks for checking on that. This seems to be related to the `DEFAULT` then, which seems to break `find_proc` still a little bit.

**Comment by laurenceisla** [comment]
> 3. Now in the same schema, add another function, with same name, but different signature (e.g. mandatory param of row type + returning a JSONB):

I could reproduce this issue using a mandatory `int` param on version 7.1 and 8.0, but in the [v8.0.0.20211102](https://github.com/PostgREST/postgrest/releases/tag/v8.0.0.20211102) pre-release, PostgREST differentiates the functions correctly.

Maybe a change made in https://github.com/PostgREST/postgrest/pull/1927 solved this issue?

**Comment by wolfgangwalther** [comment]
Maybe we can add a test-case to confirm?

**Comment by wolfgangwalther** [comment]
> Edit: I was testing on partitioned tables for v8.0 which doesn't support embedding. With normal tables v8.0 can't reproduce this error either. So, now I'm thinking it may be due to the changes in the `findProc` function from #1841.

Yes, I can confirm with the test-cases you posted in #2029. I ran them on the commit before merging #1841 and on the commit after - this makes the test pass.
