### ISSUE TITLE
Nightly build / release date

### ISSUE THREAD

**Issue by wolfgangwalther** [PostgREST/postgrest#1677]
Currently the nightly release is showing "@postgrest-bot postgrest-bot released this 24 days ago", although the last nightly was created a couple of days ago, the commit from ~14 days ago. It would be good, if we could show the commit date or alternatively the date when the nightly tag was updated, because it shows at https://github.com/PostgREST/postgrest like this:

```
Releases 43
Nightly builds Latest
24 days ago
```

I also wonder whether we can show both the nightly and the latest stable release there at the same time? Maybe we have to make the nightly a pre-release.

**Comment by steve-chavez** [comment]
> Releases 43
Nightly builds Latest
24 days ago

Noticed that as well but I thought that it is good because then the new stable release will always appear first. We can refer to the nightly builds on docs, or maybe in the README.

**Comment by wolfgangwalther** [comment]
Yeah good point. I just checked the "This is a pre-release" box on the nightly release - and now this is already happening with the `7.0.1` release. So the pre-release will never be shown there, but always the latest stable.

With this out of the way, the nightly release date will probably only affect sort order on: https://github.com/PostgREST/postgrest/releases. So if we keep that up2date, the nightly will always show first in the list - and I think that makes sense?

**Comment by steve-chavez** [comment]
> and I think that makes sense?

Yeah, keeping the nightly as pre-release is good then.

**Comment by steve-chavez** [comment]
The pre-release has been working good. This one is solved, I think.
