### ISSUE TITLE
question: how to detect on conflict if an UPDATE or an INSERT occurred?

### ISSUE THREAD

**Issue by andykais** [PostgREST/postgrest#1683]
I need to perform an upsert (`on_conflict`) on a table and I need to know afterwards if an update or an insert occurred. I found this SO question which gives a number of solutions using `xmax` https://stackoverflow.com/questions/34762732/how-to-find-out-if-an-upsert-was-an-update-with-postgresql-9-5-upsert:
```sql
INSERT 0 2
VALUES (3, 'c'), (4, 'd'), (1,'aaaa')
ON CONFLICT (id) DO UPDATE SET col = EXCLUDED.col
returning *,case when xmax::text::int > 0 then 'updated' else 'inserted' end,ctid;
```
is it possible to do something this complex using the postgrest's query syntax?

**Comment by wolfgangwalther** [comment]
I just tested this:

```
POST http://<postgrest-testdb>/items?select=id,xmax
Content-Type: application/json
Prefer: return=representation
Prefer: resolution=merge-duplicates

{"id":100}
```

First request I got:

```
[
    {
        "id": 100,
        "xmax": "0"
    }
]
```

Repeated it:

```
[
    {
        "id": 100,
        "xmax": "3402"
    }
]
```

There is no way to add the `CASE` - but you could just parse that on the client side.

I don't think a computed column would help here, because I assume the `xmax` column is not available on the row passed into a computed column's function.

I just tried this as well:

```
POST http://<postgrest-testdb>/items?select=id,updated:xmax::boolean
[...]
```

But this tells me:

```
{
    "hint": null,
    "details": null,
    "code": "42846",
    "message": "cannot cast type xid to boolean"
}
```

Unfortunately, we can't add multiple casts to a single column. Maybe you can add a custom cast for xid -> boolean. Then you would have a nice `updated: true|false` column.

**Comment by steve-chavez** [comment]
See also https://github.com/PostgREST/postgrest/issues/1070.

**Comment by wolfgangwalther** [comment]
> Maybe you can add a custom cast for xid -> boolean. Then you would have a nice `updated: true|false` column.

Would love to hear whether that worked. If not, just selecting `xmax` as mentioned previously is your best solution right now.

A more generic implementation of that is tracked in #1070.

**Comment by andykais** [comment]
so I can spend a bit of time testing this, but in reality I cannot get that fancy with queries. I am using supabase-js on top of postgrest. They do not currently provide a mechanism for selecting columns on an insert. So, unless I can push all this logic into the database, I dont have a way to do this. FWIW my current solution is to do an client side application level upsert check, then perform an explicit insert or update. Because there should only ever be one process updating this table, this is acceptable

**Comment by wolfgangwalther** [comment]
I'm really not an expert on supabase-js (I use [vue-postgrest](https://technowledgy.github.io/vue-postgrest/) - it's my own ;)), but the docs seem to support `.select()`?

https://supabase.io/docs/client/select

**Comment by wolfgangwalther** [comment]
> So, unless I can push all this logic into the database, I dont have a way to do this.

In that case your best bet would probably be a RPC that has the UPSERT statement inside. You can then return whatever you like.
