### ISSUE TITLE
Allow auth to be turned off in the configuration

### ISSUE THREAD

**Issue by dleyland-ovo** [PostgREST/postgrest#1684]
I've deployed postgREST with a proxy as a sidecar which handles checking the auth header provided on the request. I don't have access to the client secret as the proxy uses the public key of the authorisation server to check the access token. Unfortunately the proxy still passes through the auth header on the request so postgREST fails the request with message ```"Server lacks JWT secret"```. 

Would it be possible to provide a config option to turn off the auth handling in postgREST?

**Comment by wolfgangwalther** [comment]
I am not too deep into the auth stuff, but I think you can use the public key to verify the JWT in PostgREST as well: https://postgrest.org/en/latest/auth.html#asymmetric-keys

> However you can also specify a literal JSON Web Key (JWK) or set. For example, you can use an RSA-256 public key encoded as a JWK:

So it seems to me that you should really just make PostgREST use the public key and verify the JWT itself (again).

**Comment by steve-chavez** [comment]
Also, you could void the Authorization header before it reaches postgrest. On nginx, it can be done like:

```
proxy_set_header Authorization  "";
```

That one would prevent the `"Server lacks JWT secret"` error.

**Comment by dleyland-ovo** [comment]
I tried rewriting the Authorization header but I couldn't get that to work with the proxy being used. Luckily thanks to the steer on asymmetric key support I've been able to get postgREST validating the JWT. Thanks for the help!
