### ISSUE TITLE
truncate

### ISSUE THREAD

**Issue by pixie79** [PostgREST/postgrest#1686]
Hi,

Is there an API call that could if given the correct role allow for a table to be truncated or even better truncate casscade?

I am looking to use the API to re-upload CSV seed files to our postgres instance, but it would be ideal to truncate first if that is an option?

Thanks

Mark

**Comment by wolfgangwalther** [comment]
There is no built-in mapping of any http method to `TRUNCATE`. We have `DELETE` for `DELETE` - so I don't really know which http method this should be. Also, this is a pretty destructive operation. Most of the time users of PostgREST are / should be more concerned about **not** accidently deleting all the rows in a table via an unconditional `DELETE /table` (https://postgrest.org/en/latest/admin.html#block-full-table-operations).

With that out of the way... you could create a RPC for the job:

```sql
CREATE FUNCTION truncate_the_world () RETURNS void
LANGUAGE SQL AS $$
  TRUNCATE world CASCADE;
$$;
```

And then call it via `POST /rpc/truncate_the_world`.

**Comment by wolfgangwalther** [comment]
Did that work for you?
