### ISSUE TITLE
Question: Endpoint Behavior with filtering URIs and PATCH/DELETE operations.

### ISSUE THREAD

**Issue by dday1058** [PostgREST/postgrest#1695]
### Environment

* Postgres 11.6 
* PostgREST 7.0
* FreeBSD 11.4

### Description of issue

The endpoint content as operated on by the DELETE or PATCH appears to fire repeatedly on content that would initially be outside the scope of the URI filter.

I have a complex endpoint ( multiple underlying tables  ) VIEW operated on by INSTEAD of triggers.
The endpoint  represents the concept of folders containing rules which are composed of steps.  

Given the view represent a folder with 3 rules, each with multiple steps. 
Each  step will end up being one row in the view.  

If I do a GET against the view with a URI filter of rule_sequnce=.eq1  I get  rule 1  as  4 rows/steps returned.

If I do a DELETE with the same URI qualification,  My code behavior  is to delete the underlying table content .  When a rule is deleted the subsequent sequences will be adjusted.   i.e rule 2 now becomes rule 1 etc.  Apparently the endpoint sees that.
I suppose one would say that the GET is not Stable/Immutable between GET-DELETE-GET given the same filter.

I was not expecting the endpoint content to be repopulated and the DELETE to re-fire.  So if I delete the first rule all rules are deleted, If I delete the last rule in the folder all is well.  Apparently it acts against each endpoint row result and then re-populates the view before reapplying the DELETE criteria.

Any suggestions for only acting  on the the initially populated view prior to the  UPDATE/DELETE action and preventing firing again as the results of my delete trigger actions ?

If needed I can attempt putting together the underlying code.  I am hoping the description suggests a resolvable oversight

Regards

Dave

**Comment by steve-chavez** [comment]
Hey @dday1058,

> If needed I can attempt putting together the underlying code

Yes, a minimal example with the INSTEAD OF triggers would help in seeing the problem.

**Comment by dday1058** [comment]
After seeing that the DELETE behavior appears to reload the endpoint which caused it to see the resequencing side effect of the initial DELTETE ( and that sequence value  was in my URI filter ).   I  recalled that each rule regardless of folder association has a unique "rule_id" value.  If I use rule_id rather then rule sequence as my uri scoping filter then the  DELETE acts as I would  want.   I thought the DELETE actions would only be performed against the initial GET snapshot rendered by the VIEW which is why I thought the "rule_sequence" was a valid way to go about it.   So I am happy at the moment. But now appreciate that the processing of the PATCH/DELETE filter may involve sampling the endpoint at more then one point in time.  Each sampling sees a rule_sequence of "1" but with different rule_id's.   

I consider the matter closed from my perspective.  Thanks for the Assist,
