### ISSUE TITLE
more then one row returned.

### ISSUE THREAD

**Issue by dday1058** [PostgREST/postgrest#1728]
Environment
Postgres 11.6
PostgREST 7.0
FreeBSD 11.4

### Description of issue

I started an issue #1695 that I subsequently closed because I had a work around that I now think is not reasonable.
Ultimately I am receiving this error I believe is in the postgrest logic. Perhaps  some faulty modeling assumption on my part.

```
  DELETE       ../rule_example?rule_head=eq.10

 [13-1] user=postgrest, db=ace_db, app=[unknown], client=127.0.0.1 ERROR:  21000: more than one row returned by a subquery used as an expression
[13-2] user=postgrest, db=ace_db, app=[unknown], client=127.0.0.1 LOCATION:  ExecScanSubPlan, nodeSubplan.c:347
[13-3] user=postgrest, db=ace_db, app=[unknown], client=127.0.0.1 STATEMENT:
[13-4] #011      WITH
 [13-5] #011      pg_source AS (WITH pgrst_ignored_body AS **(SELECT $1::text)**  DELETE FROM  "api"."rule_example" WHERE  "api"."rule_example"."rule_head" = '10'::unknown  RETURNING "api"."rule_example".*)
 [13-6] #011      SELECT
 [13-7] #011        '' AS total_result_set,
 [13-8] #011        pg_catalog.count(_postgrest_t) AS page_total,
[13-9] #011        array[]::text[] AS header,
 [13-10] #011        coalesce(json_agg(_postgrest_t), '[]')::character varying AS body,
 [13-11] #011        coalesce(nullif(current_setting('response.headers', true), ''), '[]') AS response_headers
 [13-12] #011      FROM (SELECT "pg_source".* FROM "pg_source"    ) _postgrest_t
```

I suspect the error has something to do with the `(SELECT $1::text)`,  which I have not been able to expose it's run time value.

The endpoint is modeling a table of translation "steps" in a phone switch application.  "steps" are the components of "rules" and rules are components of "folders".
The views columns of step, rule_seq, and a rule  number are relative and  derived from column content.  Our other endpoints that expose rules do not expose the rules to the step level and our POST/PATCH/DELETE operations are all good.

If I perform a GET against the endpoint with a URI filter based on step_seq,rule_seq, or folder criteria I receive the expected content.

When I perform a DELETE at the "step" level  the result is as expected. ( ../api/rule_exampe/step_id=eq.1 )
 if I DELETE with the URI filter/scope set a the broader rule_seq, rule_header or folder level against this table  I get the above error. THis is true even if the rule was only composed of a single step.  (../api/rule_example/rule_header=10)
Something about the lack of a direct 1:1 corresondence to the underlying table I suspect

My assumption is that the DELETE would initially load the endpoint/view,  reducing the content per the URI filter and  and then running the DELETE operation against each of those "steps" remaining in the endpoint.  

**What am I missing ?**

Thanks for taking a look at this.

Best Dave.

Sample invocation of getting a rule

```
GET  ../rule_example?rule_header=eq.10
[
    {
        "folder_id": 1,
        "rule_head": 10,
        "rule_seq": 1,
        "rule_step": 1,
        "step_id": 10,
        "opta": 0,
        "optb": 0
    },
    {
        "folder_id": 1,
        "rule_head": 10,
        "rule_seq": 1,
        "rule_step": 2,
        "step_id": 20,
        "opta": 0,
        "optb": 0
    }
]
```

---Sample CODE
Adjust schema GRANTS as needed.

```sql
--CREATE SCHEMA IF NOT EXISTS api;

DROP TABLE IF EXISTS api.my_translator CASCADE;

CREATE TABLE  api.my_translator (
    folder_id int not null,
    folder_seq int not null,     -- 1-n, each rule in folder has unique value.
    entry_type int default 0,    -- 0 rule start, 6 rule append
    optA int default 0,
    optB int default 0,
    step_id  int primary key
 );

--Add sample date to my_translator table.

INSERT INTO api.my_translator
 (folder_id, folder_seq, entry_type, step_id )
VALUES   -- insert three 2 step rules into folder 1
 ( 1,1,0,10),       -- folder one, folder seq 1,  rule 1 step 1
 ( 1,2,6,20),       -- folder one, folder seq 2,  rule 1 step 2
 ( 1,3,0,30),       -- folder one, folder seq 3,  rule 2 step 1
 ( 1,4,6,40),       -- folder one, folder seq 4,  rule 2 step 2
 ( 1,5,0,50),       -- folder one, folder seq 5,  rule 3 step 1
 ( 1,6,6,60);       -- folder one, folder seq 6,  rule 3 step 2

-- A function that determnine a rules order withi a folder.
CREATE OR REPLACE FUNCTION api.get_rule_seq( _fid int, _fseq int )
RETURNS integer
LANGUAGE plpgsql
AS $function$
DECLARE _rule_seq int := 1;
BEGIN
   -- given a folder and step within that folder determince what
   -- the conceptual rule sequence is for the step.
   WITH rules AS (
      SELECT folder_seq, row_number() over ( ORDER by folder_seq ASC)
            FROM api.my_translator tx
            WHERE tx.folder_id = _fid AND
                  entry_type = 0
  )

  SELECT MAX (row_number) FROM rules
    WHERE folder_seq <= _fseq INTO _rule_seq;

  RETURN _rule_seq;
END
$function$;

-- The view that breaks down the details of a rule.
-- Shows the folder, the rule  and individual steps of a rule.

CREATE OR REPLACE VIEW api.rule_example AS
    SELECT
      tum.folder_id,
      ( WITH rule_heads AS (
            -- Find rule heads for each rule in folder.
            SELECT api.get_rule_seq( tx.folder_id, tx.folder_seq) AS rule_seq, tx.step_id
               FROM api.my_translator tx
               WHERE  tx.folder_id = tum.folder_id
                 AND entry_type = 0
           )
           -- Find the rule head for the current row. (tum.folder_seq),
           SELECT step_id FROM rule_heads rh
              WHERE rh.rule_seq = api.get_rule_seq(tum.folder_id, folder_seq)
      ) AS rule_head, -- every step of same rule has the same head.
      -- The rule sequence, 1-n,  is determined by the rules in same folder.
      api.get_rule_seq( tum.folder_id, folder_seq) AS rule_seq,
       -- Make sure steps always begin with 1 for each of its rules.
      ( SELECT ((tum.folder_seq - MAX(folder_seq)) + 1)
           FROM api.my_translator
           WHERE folder_id = tum.folder_id
            AND folder_seq <= tum.folder_seq
            AND entry_type = 0 ) AS rule_step,
      tum.step_id,
      tum.optA,
      tum.optB
   FROM api.my_translator tum
    ORDER BY tum.folder_id, tum.folder_seq asc;


GRANT ALL ON api.rule_example TO REST_USER_MAX;
GRANT ALL ON api.my_translator TO REST_USER_MAX;



CREATE OR REPLACE FUNCTION api.rule_delete_and_decrement(
        _step_id  INTEGER
    )
    RETURNS VOID
    LANGUAGE plpgsql VOLATILE
    AS $BODY$
DECLARE
    _del_count INT;
    _dec_count INT;
    _obj_seq INT;
    _next_obj_seq INT;
    _max_obj_seq INT;
    _del_ids INTEGER[];
    _dec_ids INTEGER[];
    _mbr INT;
    _tu_id INT;

BEGIN
    -- Get the obj_seq for the start of the rule being deleted,
    -- the start of the next rule, and the end of the list.
    SELECT folder_seq, folder_id INTO _obj_seq, _tu_id
        FROM api.my_translator
        WHERE step_id = _step_id;

    SELECT MIN(folder_seq) INTO _next_obj_seq
        FROM api.my_translator
        WHERE folder_id = _tu_id
        AND folder_seq > _obj_seq
        AND entry_type = 0;

    SELECT MAX(folder_seq)+1 INTO _max_obj_seq
        FROM api.my_translator
        WHERE folder_id = _tu_id;

    -- _next_obj_seq is the end of the list if it is null (meaning
    -- that this is deleteing the last rule in the sequence)
    IF _next_obj_seq IS NULL THEN
        _next_obj_seq = _max_obj_seq;
    END IF;

    -- Set del_count = amount of rows being deleted,
    -- Set dec_count = amount of rows that must be decremented.
    _del_count = _next_obj_seq - _obj_seq;
    _dec_count = _max_obj_seq - _next_obj_seq;

    -- Get the ids of the rows that need to be decremented
    -- in the order that they need to be decremented
    SELECT ARRAY_AGG(step_id ORDER BY folder_seq ASC ) INTO _dec_ids
        FROM api.my_translator
        WHERE folder_id = _tu_id
          AND folder_seq >= _next_obj_seq;

    -- Get the ids of the rows that need to be deleted
    SELECT ARRAY_AGG(step_id ORDER BY folder_seq ASC ) INTO _del_ids
        FROM api.my_translator
        WHERE folder_id = _tu_id
        AND folder_seq  >= _obj_seq AND folder_seq < _next_obj_seq;

    -- Delete the necessary rows
    DELETE FROM api.my_translator
        WHERE step_id = ANY(_del_ids);

    -- Decrement the necessary rows in the correct order
    IF ARRAY_LENGTH(_dec_ids,1) > 0 THEN
        FOREACH _mbr IN ARRAY _dec_ids
        LOOP
            UPDATE api.my_translator
                SET folder_seq = folder_seq - _del_count
                WHERE step_id = _mbr;
        END LOOP;
    END IF;

    RETURN;

END
$BODY$;

GRANT EXECUTE ON FUNCTION api.rule_delete_and_decrement(INT)
    TO rest_user_max;

COMMENT ON FUNCTION api.rule_delete_and_decrement(INT)
    IS $TEXT$
This function will delete a rule and all of its appended steps from the database
and decrement the rows above it by the amount of rows deleted.
$TEXT$;



CREATE OR REPLACE FUNCTION api.rule_delete()
    RETURNS TRIGGER AS
$BODY$
BEGIN

    IF OLD.rule_step = 1 THEN
       -- Remove entire rule and Reassign obj_seq of succeeding rules.
       PERFORM api.rule_delete_and_decrement( OLD.step_id);
    ELSE
       -- Only remove the single step.
       DELETE FROM api.my_translator
           WHERE step_id = OLD.step_id;
    END IF;

    RETURN OLD;
END;
$BODY$
    LANGUAGE plpgsql VOLATILE;

GRANT EXECUTE ON FUNCTION api.rule_delete() TO rest_user_max;

CREATE TRIGGER rule_advanced_delete_trigger
    INSTEAD OF DELETE ON api.rule_example
        FOR EACH ROW
            EXECUTE PROCEDURE api.rule_delete();
```

**Comment by steve-chavez** [comment]
Hey @dday1058,

Can you try the latest nightly?

https://github.com/PostgREST/postgrest/releases/download/nightly/postgrest-nightly-2020-12-09-14-20-ebd474a-freebsd.tar.xz

The `SELECT $1::text` won't be present there.

**Comment by dday1058** [comment]
Hi Steve

Thanks for the suggestion.
We will try that and get back to you next week.

Dave

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wolfgangwalther** [comment]
Dumping a huge chunk of SQL is not really a nice way to report something like that. You should really limit your code to a minimum example that shows this behaviour. This would also help you to pin down the issue yourself.

This is not a problem with the PostgREST query, but a problem with the triggers you created. 

> I suspect the error has something to do with the `(SELECT $1::text)`, which I have not been able to expose it's run time value.

Certainly not, because this is part of the `pgrst_ignored_body` CTE. This CTE is not used in the query at all and is just there because it's easier to create the query like that. It serves no function and is not executed at all.

> When I perform a DELETE at the "step" level the result is as expected. ( ../api/rule_exampe/step_id=eq.1 )

If you do that with the sample data you provide, that is easy to explain: The `step_id`s are `10,20,...` according to the `INSERT` statement, so this will delete **no rows**. This will not call the trigger -> no error.

> if I DELETE with the URI filter/scope set a the broader rule_seq, rule_header or folder level against this table I get the above error. THis is true even if the rule was only composed of a single step. (../api/rule_example/rule_header=10)

You should really try your queries directly in SQL as `DELETE FROM rule_example WHERE ...`. I'm quite certain that those queries would already throw the same error - with PostgREST involvement at all.

**Comment by dday1058** [comment]
https://github.com/PostgREST/postgrest/issues/1728#issuecomment-757478173

Thank You Wofgangalther for your comments.

My commenting was sloppy about the DELETE step_id should have been 10 rather then 1 so I do get a proper deletion of 1 step in that case.

Your suggestion of doing the DELETE without the rest API.  ( I'm chagrined I did not think of that. ) 
The real definition has some dependencies that make this difficult that the simplified case does not.

Definitely rules out Postgrest as being a player.   I'm still puzzled about why when the error is thrown I do not get a better stack trace from postgres about the offending logic.

 [8-1] user=redcom, db=ace_db, app=OmniDB, client=192.168.84.42 ERROR:  21000: more than one row returned by a subquery used as an expression
 [8-2] user=redcom, db=ace_db, app=OmniDB, client=192.168.84.42 LOCATION:  ExecScanSubPlan, nodeSubplan.c:347
 [8-3] user=redcom, db=ace_db, app=OmniDB, client=192.168.84.42 STATEMENT:  DELETE FROM  api.rule_example where rule_head = 10

This of course is a rule with 2 steps which the DELETE WHERE clause would see.,   I expected the trigger  to fire 2  separate times against the underlying table.  I think I have missed something in the VIEW and instead OF trigger  modelling requirements.

Thanks Again
Closable.

Dave

**Comment by dday1058** [comment]
Turned out I was using a function inside the VIEW that was marked VOLATILE.  Changing it to STABLE resolved my problem.
