### ISSUE TITLE
Allow a function with single unnamed parameter to be called with POST

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#1735]
### Use case

Some external services have webhooks that allow to POST json to an URL. This json doesn't come with a top level key, so our [Prefer: params=single-object](https://postgrest.org/en/v7.0.0/api.html#calling-functions-with-a-single-json-parameter) header is ideal here.

However, some services(like Postmark) don't allow setting HTTP headers for these webhooks. The workaround here is to use the proxy to map an URL query parameter to the header, but this is not convenient.

(Also, I can't find it right now, but there was an issue/gitter comment about an embedded device having the same limitation - crippled http client)

### Proposal

Allow a function with single unnamed parameter to be called with POST, without specifying `params=single-object`:

```sql
create or replace function bulk_email_processing(json) returns void as $_$
-- ...
$_$ language sql;
```

```http
POST /rpc/bulk_email_processing

{"any": "json"}
```

This wouldn't work for GET, since the parameter is unnamed it can't be specified in the URL.

---

Right now we don't allow calling unnamed parameters on functions, so this wouldn't cause a breaking change.

**Comment by wolfgangwalther** [comment]
Sounds good. `jsonb` should be supported as well, I think. How about generalizing this to `text` and `bytea`, too? This would allow us to post any type of body.

**Comment by steve-chavez** [comment]
>  Sounds good. jsonb should be supported as well, I think. How about generalizing this to text and bytea, too? 

Yes, great idea! This would also allow us to upload raw binary(https://github.com/PostgREST/postgrest/issues/922). I think the lack of multipart could be worked around by adding data on the headers.

**Comment by nerfpops** [comment]
Great use of named vs unnamed parameters!
