### ISSUE TITLE
Unable to connect to the remote server

### ISSUE THREAD

**Issue by yellowkazoo** [PostgREST/postgrest#1738]
### Environment

* PostgreSQL version: 9.6
* PostgREST version: 7.0.1
* Operating system: CentOS 7

### Description of issue

I have setup a table as described in the tutorial, when I query it from the localhost (curl http://localhost:3000/todos or curl http://servername:3000/todos) everything works find and I get the expected response.  If I query it from another computer on the local network using curl http://servername:3000/todos, I get the response "Unable to connect".  It seems like the only control of the bind address is in the config file and I think I have it open to all.  Why can I not access from other computers?  Thanks to anyone for their expertise.

Here is my config file contents:

```
db-uri       = "postgres://authenticator:mysecretpassword@localhost:5432/DBNAME"
db-schema    = "api"
db-anon-role = "web_anon"
server-host = "*"
server-port = "3000" 
```

**Comment by wolfgangwalther** [comment]
This sounds like a firewall issue or something like that?

**Comment by wolfgangwalther** [comment]
Maybe this helps: https://serverfault.com/a/309058

**Comment by yellowkazoo** [comment]
Thank you very much for the reply, I will check that.  I had assumed that
it wasn't a firewall issue because I can access the PostrgreSQL server on
that machine just fine and when I tested it with the name of the server
(from the same machine) instead of localhost it seemed to work fine.  I
will investigate this further, thanks again.

**Comment by wolfgangwalther** [comment]
Were you able to solve this?

**Comment by yellowkazoo** [comment]
Yes, I believe you were right that port 3000 is being blocked. I shut down
the httpd service and moved postgrest to port 80 and everything worked. Now
I just need to get another port opened up to put postgrest on. Thanks again
for following up and all your help.
