### ISSUE TITLE
Hardcoded postgrest_test_authenticator in latest nightly

### ISSUE THREAD

**Issue by LorenzHenk** [PostgREST/postgrest#1740]
### Environment

* PostgreSQL version: 13.1
* PostgREST version: nightly-2021-01-22-15-56-6557f1f

### Description of issue

In the latest nightly, when trying to run `postgrest --dump-config`, I get the following error:

```
$ postgrest --dump-config

An error ocurred when trying to query database settings for the config parameters:
SessionError (QueryError "\n      with\n      role_setting as (\n        select unnest(setconfig) as setting from pg_catalog.pg_db_role_setting where setrole = 'postgrest_test_authenticator'::regrole::oid\n      ),\n      kv_settings as (\n        select split_part(setting, '=', 1) as key, split_part(setting, '=', 2) as value from role_setting\n      )\n      select replace(key, 'pgrst.', '') as key, value from kv_settings where key like 'pgrst.%';\n    " [] (ResultError (ServerError "42704" "role \"postgrest_test_authenticator\" does not exist" Nothing Nothing)))
```

Seems like the role "postgrest_test_authenticator" was hardcoded here: https://github.com/PostgREST/postgrest/blob/125ea8f6d9ecfe40ed4a1c5a9291ae23bb695972/src/PostgREST/Statements.hs#L205
Related: #1729

The same error also appears on `postgrest --dump-schema`, but the schema JSON is still printed.

**Comment by wolfgangwalther** [comment]
Wow. I wonder how I missed that in my review of that PR :D.

Should be enough to replace `'postgrest_test_authenticator'` with `current_user`.

**Comment by steve-chavez** [comment]
@LorenzHenk Set `db-load-guc-config = false` to fix this error.

**Comment by LorenzHenk** [comment]
Thanks for the quick answers!

**Comment by steve-chavez** [comment]
@LorenzHenk The latest `postgrest-nightly-2021-01-25-18-38-c93e8f9` on [Nightly builds](https://github.com/PostgREST/postgrest/releases/tag/nightly) should have this one fixed!
