### ISSUE TITLE
SIGUSR2 killing PostgREST process

### ISSUE THREAD

**Issue by edmundpf** [PostgREST/postgrest#1744]
### Environment

* PostgreSQL version: 12.5
* PostgREST version: v7.0.1
* Operating system: (Ubuntu 12.5-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit

### Config
```
db-uri = "postgres://MY_CONNECTION_STRING"
db-schema = "api"
db-anon-role = "api_anon"
server-port = 1069
jwt-secret = "@/root/.json_config/postgrest_jwks.json"
```

### Description of issue

According to some issues on this repo, it appears sending a SIGUSR2 signal should be adequate to reload all the JWT configuration fields. I'm mostly interested in reloading the jwt-secret field, as I am pointing to a file which is generated from a process that rotates JWK's every X days. Ideally, I'd like to send a SIGUSR2 signal after rotating the JWK's in this file and immediately have the up to date JWK's being used by PostgREST. What actually happens though is when I send a SIGUSR2 signal with `kill -SIGUSR2 x_process_id` the program does output `User defined signal 2` but then it immediately stops. Is there any way to send this signal without killing the program?

**Comment by wolfgangwalther** [comment]
This was implemented in #1119, which is not part of v7.0.1 you're using. This is part of the current nightly, but otherwise yet unreleased.
