### ISSUE TITLE
Error - cannot execute INSERT in a read-only transaction when executing through GET and Failed to parse when executing through POST

### ISSUE THREAD

**Issue by girishvenkata14** [PostgREST/postgrest#1745]
### Description of issue

I am trying to insert a record from postman into a table using a function, below is the code:
<img width="507" alt="Issue1" src="https://user-images.githubusercontent.com/77968207/106109936-1a46a180-6170-11eb-97b9-a4f4ada793df.PNG">

below is the error screenshot from postman when using GET:
<img width="636" alt="Issue2" src="https://user-images.githubusercontent.com/77968207/106110090-45c98c00-6170-11eb-962f-471b7479818d.PNG">

below is the error screenshot from postman when using POST:
<img width="622" alt="Issue" src="https://user-images.githubusercontent.com/77968207/106110222-727da380-6170-11eb-8eae-55cf1e0669df.PNG">

**Comment by girishvenkata14** [comment]
Could you please help

**Comment by wolfgangwalther** [comment]
It would be really helpful, if you didn't post screenshots, but text instead. SQL statements that create the objects (function) in question and then the requested URIs, bodies and responses.

The error for `GET` is described at https://postgrest.org/en/latest/api.html#immutable-and-stable-functions:

> Procedures that do not modify the database can be called with the HTTP GET verb as well, if desired. PostgREST executes all GET requests in a read-only transaction. Modifying the database inside read-only transactions is not possible and calling volatile functions with GET will fail.

For POST you need to pass the arguments to the function in the body and **not** via query string. See https://postgrest.org/en/latest/api.html#stored-procedures:

> To supply arguments in an API call, include a JSON object in the request payload and each key/value of the object will become an argument.

**Comment by girishvenkata14** [comment]
This is my function:

CREATE OR REPLACE FUNCTION public.add_num(IN inta integer DEFAULT 1,IN intb integer DEFAULT  1)
    RETURNS integer
    LANGUAGE 'sql'
    VOLATILE
    PARALLEL UNSAFE
    COST 100
    
AS $BODY$
SELECT intA + intB;
$BODY$;


It is giving below error when calling from postman:
<img width="596" alt="Issue" src="https://user-images.githubusercontent.com/77968207/106557917-eb05ab00-6548-11eb-88c1-ee5a68d57ca4.PNG">

**Comment by wolfgangwalther** [comment]
`HTTP/1.1` should not be part of the URL. Remove that and it should work.

**Comment by girishvenkata14** [comment]
tried that and it is giving below error:

<img width="648" alt="issue" src="https://user-images.githubusercontent.com/77968207/106569096-25c40f00-655a-11eb-81b3-3e481e9b859c.PNG">


I checked the link which you provided for this error and tried to clear the cache in postgre. 
Facing below issue:
<img width="270" alt="issue1" src="https://user-images.githubusercontent.com/77968207/106569315-5e63e880-655a-11eb-8ee4-6c57d6a35d69.PNG">

**Comment by wolfgangwalther** [comment]
`killall -SIGUSR1 postgrest` is not a SQL command, but a linux shell command. You can just restart postgrest instead, too.

**Comment by girishvenkata14** [comment]
It helped.. thank you so much!!
