### ISSUE TITLE
Asynchronous Notifications in Postgres

### ISSUE THREAD

**Issue by girishvenkata14** [PostgREST/postgrest#1749]
I created a table:

CREATE TABLE public."postionHistory"
(
    "deviceId" character varying COLLATE pg_catalog."default",
    "localX" double precision,
    "localY" double precision,
    location point,
    "positionTimeStamp" bigint,
    "assetId" character varying COLLATE pg_catalog."default"
)

Created a trigger using below code:

CREATE OR REPLACE FUNCTION notify_event() RETURNS TRIGGER AS $$
  DECLARE
    record RECORD;
    payload JSON;
  BEGIN
    IF (TG_OP = 'DELETE') THEN
      record = OLD;
    ELSE
      record = NEW;
    END IF;

    payload = json_build_object('table', TG_TABLE_NAME,
                                'action', TG_OP,
                                'data', row_to_json(record));

    PERFORM pg_notify('events', payload::text);

    RETURN NULL;
  END;
$$ LANGUAGE plpgsql;

After that tried to create a trigger using below code: 

CREATE TRIGGER notify_order_event
AFTER INSERT OR UPDATE OR DELETE ON positionHistory
  FOR EACH ROW EXECUTE PROCEDURE notify_event();

but getting the error:

ERROR:  relation "positionhistory" does not exist
SQL state: 42P01

I used the reference of this document : https://citizen428.net/blog/asynchronous-notifications-in-postgres/

Could you please help me with this.

**Comment by dwagin** [comment]
"postionHistory" and positionHistory its different  relation name.

**Comment by dwagin** [comment]
This question is not about PostgREST.
