### ISSUE TITLE
Issue with insert in a function

### ISSUE THREAD

**Issue by girishvenkata14** [PostgREST/postgrest#1752]
Below is the table i created:

CREATE TABLE public.testg
(
    "assetType" character varying COLLATE pg_catalog."default",
    "deviceId" character varying COLLATE pg_catalog."default"
)
TABLESPACE pg_default;

Below is the function:
IF op = 'insert' THEN
	INSERT INTO public.testg("assetType", "deviceId")
	VALUES (assettype, deviceid);
END IF

<img width="517" alt="issue" src="https://user-images.githubusercontent.com/77968207/107139156-11f42080-693f-11eb-9e61-4339d2a465fa.PNG">

Below is the error it is giving:

ERROR: syntax error at or near "IF"
LINE 6: IF op = 'insert' THEN

Could you please help with this

**Comment by wolfgangwalther** [comment]
Your question is about PostgreSQL, not about PostgREST. This is **not** a PostgreSQL support forum. Please stop asking PostgreSQL questions here.
