### ISSUE TITLE
ERROR:  function string_agg(integer, unknown) does not exist

### ISSUE THREAD

**Issue by anirudh-ramesh** [PostgREST/postgrest#1755]
### Environment

* PostgreSQL version: 11
* PostgREST version: 7.0.1 (d6050c8)
* Operating system: Ubuntu 20.04.2 LTS

### Description of issue

I am calling a function via the RPC endpoint having all arguments as TEXT of varying length. However, the PostgreSQL logs indicate that the query being executed by PostgREST calls the function `string_agg(integer, unknown)`, which does not exist.

The portion of the query that is buggy is as follows.
`	      SELECT
	        null::bigint AS total_result_set,
	        pg_catalog.count(_postgrest_t) AS page_total,
	        coalesce(string_agg(_postgrest_t."pgrst_scalar", ''), '') AS body,
	        coalesce(nullif(current_setting('response.headers', true), ''), '[]') AS response_headers
	      FROM (SELECT "pg_source".* FROM "pg_source"    ) _postgrest_t;`

Over here, the call to `string_agg` throws the error: `ERROR:  function string_agg(integer, unknown) does not exist at character `...

The hint provided by the PostgreSQL server is: `HINT:  No function matches the given name and argument types. You might need to add explicit type casts.`

The offending line of code is:
`asBinaryF fieldName = "coalesce(string_agg(_postgrest_t." <> pgFmtIdent fieldName <> ", ''), '')"` in the file `src/PostgREST/Private/QueryFragment.hs`

**Comment by wolfgangwalther** [comment]
Can you please post the `CREATE FUNCTION` statement you are using and also the exact request (with headers) you are making?

This looks to me like you have a function that `RETURNS integer` and you are requesting this with a custom mimetype - is that correct?

The docs say that binary/text output is only supported for `TEXT` and `BYTEA` columns/return types (https://postgrest.org/en/latest/api.html#binary-output). Try changing the return type of your RPC to `TEXT` and do the int->text cast inside it.

**Comment by wolfgangwalther** [comment]
Feel free to re-open, if my suggestion did not work.
