### ISSUE TITLE
Feature request: Limit the number of rows that can be inserted with a single POST request

### ISSUE THREAD

**Issue by dimattiami** [PostgREST/postgrest#1757]
Desired behavior: POST request only succeeds/inserts when the amount of rows in request payload is below a defined threshold

Limiting the maximum number of rows with a single POST request will help prevent a malicious user from creating large amounts of spam rows. Rate limiting requests with a reverse-proxy helps, but doesn't prevent a user from sending a single POST with a large array of elements.

Ideas:
Only GRANT anonymous users SELECT, however, this isn't feasible for use-cases that don't require authentication
Add a before-insert trigger on tables, performing the insert only when the amount of rows in the request is below a threshold
Enforce `max-rows` on INSERT queries

**Comment by steve-chavez** [comment]
How about limiting the body size by configuring a [client_max_body_size](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) in Nginx?

I thought about the `max-rows` option, but that would only LIMIT the INSERT rows and wouldn't give an error. And counting the rows and erring somehow would be too much work for pg, I think.

It's a malicious request anyway, so it should not reach the db. It'd be better to filter it at the proxy level.

@dimattiami What do you think?

(Btw, I remember our warp server had a similar setting to client_max_body_size, but I can't find it).

**Comment by dimattiami** [comment]
Thank you again for your thoughts, @steve-chavez 

I've considered `client_max_body_size` in Nginx; it would certainly be a good solution for limiting the total volume of data allowed in a single request, though this configuration wouldn't limit the actual number of rows to insert. For example, if `client_max_body_size` was configured at 1kB, in a single request a legitimate user could send 10 rows @ 100Bytes per row, or a malicious user could send 100 spam rows @ 10Bytes per row.

It sounds like `max-rows` behavior isn't feasible for INSERT, and counting the rows then erring would be unnecessary overhead for pg. I'm with you that malicious requests shouldn't reach the DB to begin with.

Another idea I have is adding a lightweight server between nginx and postgrest that would check the amount of elements in each requests payload, only forwarding requests to postgrest if the number of elements in the payloads JSON array (rows to insert) is below a defined threshold. Perhaps Nginx can do this count check on the payload; I'll have to look into it more and will report back if I find a solution.

If Nginx can't do this, do you think there would be enough value to make this feature worth adding to postgrest? I know postgrest has a focused scope, and don't want to stretch that if not appropriate.

**Comment by dimattiami** [comment]
Update: Using njs with nginx, I am able to deny requests with payloads that exceed a certain # of elements, as requested in this issue. I believe this issue can now be closed. Reference: https://www.nginx.com/blog/deploying-nginx-plus-as-an-api-gateway-part-2-protecting-backend-services/#request-bodies
Thank you for your collaboration @steve-chavez

**Comment by steve-chavez** [comment]
Glad you could solve it @dimattiami. I do believe this is better done in the proxy. Though now we do parse the json payload before it reaches pg, we're trying to move away from it because it can consume a lot of memory.

Personally I've only used Lua on nginx, but njs looks much more convenient.
