### ISSUE TITLE
Duplicate Jump Sequence ID

### ISSUE THREAD

**Issue by q4Zar** [PostgREST/postgrest#1759]
### Environment

* PostgreSQL version: docker image postgres:alpine
* PostgREST version: docker image postgrest/postgrest
* Operating system: centOs

---

### Description of issue

EveryTime there is a Duplicate Error code : 23505
The Sequence of ID jumps

---

### SQL Table Definition

```sql
CREATE TABLE "GTMA_Event_Date" (
  "id" SERIAL PRIMARY KEY,
  "date" DATE,
  "created_at" timestamp DEFAULT (now())
);
CREATE UNIQUE INDEX ON "GTMA_Event_Date" ("date");
```

---

### SQL Table Data

|id|date|created_at|
|--|----|----------|
|1|2021-01-28|2021-02-16 18:20:12|
|212|2021-01-29|2021-02-16 18:20:31|
|285|2021-02-01|2021-02-16 18:20:35|
|383|2021-02-02|2021-02-16 18:20:42|
|512|2021-02-03|2021-02-16 18:20:53|
|518|2021-02-04|2021-02-16 18:20:53|
|573|2021-02-08|2021-02-16 18:20:58|
|596|2021-02-09|2021-02-16 18:21:00|
|612|2021-02-10|2021-02-16 18:21:01|
|618|2021-02-11|2021-02-16 18:21:02|
|646|2021-02-12|2021-02-16 18:21:04|
|658|2021-02-13|2021-02-16 18:21:05|
|661|2021-02-15|2021-02-16 18:21:05|
|667|2021-02-16|2021-02-16 18:21:06|

How can i fix that ?
Is there is builtin options, or should i make a function and call it te reorganise sequences ids ?

Thanks for your future help )

**Comment by wolfgangwalther** [comment]
This is not a PostgREST issue, but a PostgreSQL one. Have a look at https://www.postgresql.org/message-id/flat/501B1494.9040502%40ringerc.id.au#d61f10d9a3533853d98a9ee4143ebf7b, that should give you the background and a few ways to deal with it.

**Comment by q4Zar** [comment]
thanks a lot
