### ISSUE TITLE
Rows with attribute value as null are returned even with filter "not.is.null"

### ISSUE THREAD

**Issue by devesh23** [PostgREST/postgrest#1761]
### Environment

* PostgreSQL version: 11
* PostgREST version: 0.7
* Operating system: Centos

### Description of issue

Not able to query null value using API call
/api/flower?deleted_at=not.is.null

(Expected behavior vs actual behavior)

Expected Behaviour = Above API should not pickup rows where deleted_at is NULL. 
Actual Behaviour = Above API is picking up rows where deleated_at is NULL. 

(Steps to reproduce: Include a minimal SQL definition plus how you make the request to PostgREST and the response body)

Corresponding SQL Statement: select * from flower where deleted_at is not null

**Comment by steve-chavez** [comment]
Can't reproduce. `not.is.null` works good for me.

Try enabling database logs: https://postgrest.org/en/v7.0.0/admin.html#database-logs. Then see the generated query - it should include a `NOT deleted_at IS null`.

**Comment by wolfgangwalther** [comment]
If the problem is still there and you can provide a reproducible test-case, feel free to re-open.
