### ISSUE TITLE
void functions return an empty body, which is invalid json

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#1762]
### Environment

* PostgREST version: nightly

### Description of issue

The nightly version returns an empty body for a function like:

```sql
create function test.ret_void() returns void as '' language sql;
```

This breaks libraries that use `JSON.parse`: https://github.com/supabase/supabase/issues/762 (try doing `JSON.parse("")` on the browser console).
It also doesn't seem right from the [RFC](https://tools.ietf.org/html/rfc7159#section-1) standpoint:

> JSON can represent four primitive types (strings, numbers, booleans, and null) and two structured types (objects and arrays)

Since we're asking for `application/json`, we should return a `null` or an empty string `""` at worst.

I've also noted this happens when you want to return a `null` explicit:

```sql
create or replace function ret_null() returns int as $$
  select null::int;
$$ language sql;
```

```bash
curl localhost:3000/rpc/ret_null
## no body
```

**Comment by steve-chavez** [comment]
Previous versions did return the null. This was changed on https://github.com/PostgREST/postgrest/pull/1615#issuecomment-742341943 

cc @wolfgangwalther

**Comment by wolfgangwalther** [comment]
> This breaks libraries that use `JSON.parse`: [supabase/supabase#762](https://github.com/supabase/supabase/issues/762) (try doing `JSON.parse("")` on the browser console).

In Javascript there is a difference between `undefined` and `null`. `returns void` matches `undefined` a lot more semantically. I suggest you just do something like:

```javascript
if (body === '') return undefined
return JSON.parse(body)
```

> It also doesn't seem right from the [RFC](https://tools.ietf.org/html/rfc7159#section-1) standpoint:
> 
> > JSON can represent four primitive types (strings, numbers, booleans, and null) and two structured types (objects and arrays)
> 
> Since we're asking for `application/json`, we should return a `null` or an empty string `""` at worst.

Returning an empty body seems fine (even better!) to me. We're doing the same thing when `Prefer: return=minimal` is used, right?

In PostgreSQL there is a difference between returning no result from a statement (think `INSERT` without `RETURNING` or `PERFORM` in plpgsql) and returning one or more rows. A function that is defined with `RETURNS VOID` never returns a result. It's just that `SELECT` will always return a result, so void is mapped to a single `NULL` here. However, this seems to be more about the inability to properly do a "SELECT without result" in plain SQL than about that `NULL` is actually the best representation for "no result".

Now we could debate whether we should send a `Content-Type` header at all. And what kind of status code are we sending? Probably not `204 No Content`, yet - although that would be the best, I guess. Would also allow you to do the javascript `if` above on the status code - much better.

> I've also noted this happens when you want to return a `null` explicit:
> 
> ```sql
> create or replace function ret_null() returns int as $$
>   select null::int;
> $$ language sql;
> ```
> 
> ```shell
> curl localhost:3000/rpc/ret_null
> ## no body
> ```

This is certainly something different that we should fix. Here a value is requested/supposed to be returned and we should not silently ignore it.

**Comment by steve-chavez** [comment]
> We're doing the same thing when Prefer: return=minimal is used, right?

True, I forgot about that. A 204 with no content type would be better here, as you mention.

> In PostgreSQL there is a difference between returning no result from a statement..

Yes, but that's pg default behavior, which doesn't give the result that most clients would expect. This is a bit like the previous behavior of returning an array of objects(https://github.com/PostgREST/postgrest/pull/1615#issuecomment-709409972) for SETOF, which you fixed and now returns an array of values(better for clients).

I think it'd be better if we could fix both return null and return void the same, instead of treating `return void` as a special case in code.

I've noted that changing this line:

https://github.com/PostgREST/postgrest/blob/0ddd676ef04a72d89c0fa734aeca0596841874e4/src/PostgREST/Private/QueryFragment.hs#L98-L100

To:

```haskell
  | returnsScalar = "coalesce(string_agg(to_json(_postgrest_t.pgrst_scalar)::text, ','), 'null')::character varying"
```

Is enough for getting the previous `null` behavior. All the tests go green except the ones that check for an empty body.

@wolfgangwalther WDYT? Do you see any issues with that change?

**Comment by wolfgangwalther** [comment]
> > We're doing the same thing when Prefer: return=minimal is used, right?
> 
> True, I forgot about that. A 204 with no content type would be better here, as you mention.

Ok, that's not really what I meant - but nonetheless I agree. But, I want 204 for `VOID`, too...

> Yes, but that's pg default behavior, which doesn't give the result that most clients would expect. This is a bit like the previous behavior of returning an array of objects([#1615 (comment)](https://github.com/PostgREST/postgrest/pull/1615#issuecomment-709409972)) for SETOF, which you fixed and now returns an array of values(diverts from pg default behavior but it's better for clients).
> 
> I think it'd be better if we could fix both return null and return void the same, instead of treating `return void` as a special case in code.

... but we don't agree on that, yet :). I can understand your reasoning to match what (Postgre)SQL does - however I think the semantics of HTTP/REST are more important here. And "returning nothing" is clearly well defined with `204` and no body. Returning `200` with `null`-body is not "returning nothing" in the HTTP sense. For me it does not matter that `SELECT void_func()` does return `NULL` as some kind of a SQL-crutch.

> Is enough for getting the previous `null` behavior. All the tests go green except the ones that check for an empty body.
> 
> @wolfgangwalther WDYT? Do you see any issues with that change?

I still think we should change the behaviour for void, but we don't need to do that now. I am ok with the change, because it's not released yet and it just reverts to previous behaviour. The `RETURNS INT`+ `SELECT NULL::INT` case is more important to get right and would be a regression - even though we don't have any tests for that, yet, if I understand correctly. The empty-body tests are all for `VOID` functions right? If that's indeed true, I suggest to add another test for `SELECT NULL::INT` to make sure we're not changing that unintendedly again in the future.

**Comment by steve-chavez** [comment]
> however I think the semantics of HTTP/REST are more important here. Returning 200 with null-body is not "returning nothing" in the HTTP sense. For me it does not matter that SELECT void_func() does return NULL as some kind of a SQL-crutch.

HTTP has more weight for us, agree. But we'd be letting our HTTP design be influenced by a pg `return nothing(void)` semantic that doesn't really hold his ground. I think we should treat it as a `return null` for now. Until pg somehow changes `select void_func()` to return an empty `''` unknown type(seems unlikely).

>  The RETURNS INT+ SELECT NULL::INT case is more important to get right and would be a regression - even though we don't have any tests for that, yet, if I understand correctly. The empty-body tests are all for VOID functions right? If that's indeed true, I suggest to add another test for SELECT NULL::INT to make sure we're not changing that unintendedly again in the future.

Cool. Yes, I'll definitely add a new test for this case.

**Comment by wolfgangwalther** [comment]
> Until pg somehow changes `select void_func()` to return an empty `''` unknown type(seems unlikely).

You're missing the point here. `''::unknown` is not in any way a better representation for `void` - in fact it's worse.

The difference is between:
- `INSERT` / `UPDATE` / `DELETE` without `RETURNING` or
- plpgsql's `PERFORM`
- `CALL` for procedures

and

- `SELECT`

Select does return a result - every time. The other statements return no result at all (not `NULL`, not `''::unknown`, nothing).

It's just because we're calling those void functions with `SELECT` that we're getting a `NULL` result. We could instead just call a void function with:

```sql
DO $$
BEGIN
  PERFORM void_func();
END$$;
```

And wouldn't get a result either. So there is a PG way of "getting no result" (=void). However this would not be useful for us at all, so we still call it with `SELECT`. But that doesn't make the `NULL` return any better.

**Comment by steve-chavez** [comment]
> INSERT / UPDATE / DELETE without RETURNING or
> plpgsql's PERFORM
> CALL for procedures

Note that CALL can return a row via INOUT params:

```sql
CREATE OR REPLACE PROCEDURE add(INOUT a int, INOUT b int, INOUT c int)
LANGUAGE plpgsql AS
$proc$
BEGIN
   SELECT a + b INTO c;
END
$proc$;

call add(3,4,null);
┌───┬───┬───┐
│ a │ b │ c │
├───┼───┼───┤
│ 3 │ 4 │ 7 │
└───┴───┴───┘
(1 row)
```

All the rest true though.

> You're missing the point here. 

I think I'm missing how void->empty would mean an improvement. It just seems it would be a breaking change for all clients that use something like `JSON.parse`(or equivalent in other languages).

From our side, it'd be an additional condition for mapping void to 204 with no Content-Type.

So we'd gain an special case in both backend and frontend, which seems like a net loss.

**Comment by wolfgangwalther** [comment]
> Note that CALL can return a row via INOUT params:

True. In that sense "calling a procedure" would be a lot closer to that http `POST` request - it can return 200 with a body or 204 without. But I remember there were other problems with procedures.

> I think I'm missing how void->empty would mean an improvement.

I think there is value in providing the best semantic match between the PG object definitions and our http response. And I think there's value in avoiding useless response data. A void function will not only return nothing - but always the same "nothing", too. It will never change - so parsing the `null` response on the client is really not needed at all. It's just wasted.

> It just seems it would be a breaking change for all clients that use something like `JSON.parse`(or equivalent in other languages).

We do have quite a few breaking changes lined up anyway, so I don't think it'd be that big of a challenge to make that change, too.

> From our side, it'd be an additional condition for mapping void to 204 with no Content-Type.

I really don't see this. How would you handle `Prefer: return=minimal`, then? Although I just realized that this is currently not even possible to do with RPCs.
