### ISSUE TITLE
Default `db-schemas` to `public`

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#1769]
Currently the in-database configuration doesn't work unless `db-schemas` and `db-anon-role` are added to the config file. This is because we validate both to be present and we can't override them with the in-db config at a later stage.

If we default `db-schemas` to `public` and also solve https://github.com/PostgREST/postgrest/issues/1689, the config can be totally inside the database if the user wants to. The `db-uri` would be the only mandatory config option.

`db-schemas=public` should work in most databases, it also seems like a nice default for quickstarting.

We can put a message on stdout to make it clear when the default `public` is used and maybe also point to our [schema isolation doc](https://postgrest.org/en/v7.0.0/schema_structure.html#schema-isolation).

**Comment by gautam1168** [comment]
@steve-chavez is this issue just as simple as adding a change in `Config.hs` to make the parser not throw an error when parsing `db-schema(s)`? i.e. if neither is present then set the value to "public" instead of throwing an error?

I haven't fully unraveled what the applicative and functor applies are doing in this line, but I guess the change would be somewhere around this line?
```
<*> (fromList . splitOnCommas <$> reqWithAlias (optValue "db-schemas")
                                                   (optValue "db-schema")
                                                   "missing key: either db-schemas or db-schema must be set")
 ```

**Comment by steve-chavez** [comment]
@gautam1168 Yes, that's basically it. Ideally we'd also show a warning saying that we're defaulting to the public schema and this might not be fit for production(with a link to our [Schema Isolation docs](https://postgrest.org/en/v8.0/schema_structure.html#schema-isolation)).

**Comment by gautam1168** [comment]
Ok Ill try to open a PR for this then. Maybe not today though.
