### ISSUE TITLE
New Release ?

### ISSUE THREAD

**Issue by aadrian** [PostgREST/postgrest#1779]
Hi,

Is there any chance getting a new release? (8.0.0 or 7.1.0 or 7.0.2 ?)
_( there are many fixes since May 2020 )_

Thank you.

**Comment by bitlab-code** [comment]
I waiting for the new version.
There are some fix, like #1592 that is blocking

**Comment by wolfgangwalther** [comment]
Before we can make a new release, we need to update the docs to include all the new features. We don't want them to be released undocumented. We have been burried in other work lately and have not been able to do that, yet. @steve-chavez will be able to say more about the plan going forward.

In the meantime, it's possible to use the nightly builds:
https://github.com/PostgREST/postgrest/releases/tag/nightly

**Comment by steve-chavez** [comment]
Yes, as Wolfgang said, we need to finish up docs before making a new stable release. But nightlies are available for now.

Besides that, there are some breaking changes that I think we should do to take advantage of the new major version.

1) https://github.com/PostgREST/postgrest/issues/1643 - embedding of self references
2) https://github.com/PostgREST/postgrest/issues/1762 - empty bodies for void functions(actually a fix to prevent a breaking change)
3) https://github.com/PostgREST/postgrest/issues/1656 - make POST not do SELECT by default.

**Comment by aadrian** [comment]
> But nightlies are available for now.

@steve-chavez "latest" nightlies are from 05 of March :(  . There seems to be many commits since that too.

**Comment by steve-chavez** [comment]
@aadrian Sorry for the delay :disappointed: . I've just released a new [nightly](https://github.com/PostgREST/postgrest/releases/tag/nightly) -`postgrest-nightly-2021-06-19-15-55-2944cf9`.
