### ISSUE TITLE
Star'ing this repository signed me up for mailing list - in violation of GDPR

### ISSUE THREAD

**Issue by yamatt** [PostgREST/postgrest#1789]
### Environment
N/A

### Description of issue

Star'ing a repository caused the e-mail address I use for GitHub to be signed up for the PostgREST mailing list.

Star'ing a repository does not constitute consent to have your personal information to be provided to PostgREST or a 3rd party.

### Steps to reproduce:

Using an account that has not star'd the PostgREST repo, and has an e-mail address assigned to it. Visit the [PostgREST repo](https://github.com/PostgREST/postgrest/) and click on the Star button.

**Comment by wolfgangwalther** [comment]
I'd really like to know, how this is supposed to work. I don't think GitHub will ever give us access to email addresses of users giving us stars. And I'm really curious: What is this PostgREST mailing list? I have never heard of it.

I must admit, I had not starred PostgREST before (shame on me :D). I now did... and nothing happenend. Well PostgREST has 1 more star now!

Are you sure you didn't just hit the "watch" button and are now notified of any related activity on this repo?

**Comment by yamatt** [comment]
I'm not certain to be honest, but the only interaction I have had is to star this repo and I'm now signed up to the mailing list.

I would imagine the workflow is something like:

Poll for users who star'd a repo -> find their public e-mail address (mine is public for GitHub users) -> add them to mailing list

**Comment by wolfgangwalther** [comment]
> I'm not certain to be honest

you can easily check on the repo's header, right to the left of the star button. Is the button called "Unwatch"? Yeah, then you have enabled notifications.

> I'm now signed up to the mailing list.

What kind of emails did you receive, that make you believe you are signed up to a mailing list?

**Comment by yamatt** [comment]
oh, right. No, I'm not watching. Just star.

I then received this e-mail a few days ago
https://imgur.com/a/UGsCmvV

**Comment by wolfgangwalther** [comment]
Wow. This is indeed not appropriate, I agree with you.

However, this is not "us" (PostgREST), but subzero-cloud, a commercial fork of PostgREST. @ruslantalpa must be able to say more about it. Also: https://subzero.cloud/contact.html.

**Comment by yamatt** [comment]
Thanks for your help @wolfgangwalther

**Comment by steve-chavez** [comment]
Really sorry about this incident @yamatt, this is definitely not us and we don't endorse this behavior.

Right now we're discussing internally on how to proceed and prevent this from happening again.

**Comment by steve-chavez** [comment]
@yamatt Thank you again for bringing this to our attention. We, the PostgREST core development team, have investigated this case and want to make the following clear:

* Ruslan Talpa and subZero are acting on their own behalf
* No one from the core team had knowledge of these activities
* PostgREST is not in any way affiliated with what Ruslan Talpa is doing under the name "PostgREST+"

We expressly distance ourselves from Ruslan Talpa's activities. We have taken the following measures to do what is in our power to make this clear and mitigate future infractions:

* Even though we think it is self-evident, that this kind of behaviour is not ok, we have added an explicit [Code of Conduct](https://github.com/PostgREST/postgrest/blob/main/CODE_OF_CONDUCT.md) to avoid any doubt in the future. We will handle this and any future cases in accordance with this new code of conduct.

* We have asked Ruslan Talpa to stop this practice immediately.

* We have asked Ruslan Talpa to not use the name PostgREST+ anymore to avoid any confusion with PostgREST.

* We have removed the link to subZero from all versions of our docs (Ecosystem/Commercial) to avoid any confusion about affiliation.

Until this matter is completely resolved, we have issued, in accordance with our code of conduct, a temporary ban for Ruslan Talpa from the PostgREST community.

We hope that through this clear positioning and action, we can avoid any further confusion and inconveniences to the PostgREST community and its stargazers. We want this project to remain helpful and enjoyable.

**Comment by yamatt** [comment]
Thanks for taking it seriously and putting all this effort in to this. I really feel like I've set the cat amongst the pigeons.

I guess this all supposes that subZero are doing it themselves and isn't some other 3rd party. I don't know if there is any confirmation of that either way?

Have you been able to replicate my findings?

Also, I wonder what GitHub's Terms of Use say about this. I had considered raising a spam report to them, but given everything in this issue I'm not really sure how to define the subject, and the process seemed so obtuse anyway that I couldn't really figure out how.

**Comment by swuecho** [comment]
> Thanks for taking it seriously and putting all this effort in to this. I really feel like I've set the cat amongst the pigeons.
> 
> I guess this all supposes that subZero are doing it themselves and isn't some other 3rd party. I don't know if there is any confirmation of that either way?
> 
> Have you been able to replicate my findings?
> 
> Also, I wonder what GitHub's Terms of Use say about this. I had considered raising a spam report to them, but given everything in this issue I'm not really sure how to define the subject, and the process seemed so obtuse anyway that I couldn't really figure out how.

@yamatt 

1.  In your github homepage, your email is public. 
2. the stargazers is also public

It is obvious anyone can use that information without the permission from anyone. You could set your email to private in github setting.

**Comment by yamatt** [comment]
I wondered how long it would be before someone would write an inconsiderate response like that.

Please familiarise yourself with GDPR.

**Comment by wolfgangwalther** [comment]
> I guess this all supposes that subZero are doing it themselves and isn't some other 3rd party. I don't know if there is any confirmation of that either way?

I don't think that matters in the end. The email is sent out by subZero and the GitHub Terms of Service have [this](https://docs.github.com/en/github/site-policy/github-terms-of-service#h-api-terms):

> ### H. API Terms
> 
> Short version: You agree to these Terms of Service, plus this Section H, when using any of GitHub's APIs (Application Provider Interface), including use of the API through a third party product that accesses GitHub.

Even if they were to use a third party, they'd still be responsible.

---

> Also, I wonder what GitHub's Terms of Use say about this. I had considered raising a spam report to them, but given everything in this issue I'm not really sure how to define the subject, and the process seemed so obtuse anyway that I couldn't really figure out how.

I think it'd absolutely the right thing to raise this with GitHub, too.

The GitHub's Terms of Service explicitly include the GitHub Privacy Statement [here](https://docs.github.com/en/github/site-policy/github-terms-of-service#a-definitions):

> The “Agreement” refers, collectively, to all the terms, conditions, notices contained or referenced in this document (the “Terms of Service” or the "Terms") and all other operating rules, policies (including the GitHub Privacy Statement, available at github.com/site/privacy) and procedures that we may publish from time to time on the Website. Most of our site policies are available at docs.github.com/categories/site-policy.

The [GitHub Privacy Statement](https://docs.github.com/en/github/site-policy/github-privacy-statement#other-important-information) has this:
 > If you would like to compile GitHub data, you must comply with our Terms of Service regarding information usage and privacy, and you may only use any public-facing User Personal Information you gather for the purpose for which our user authorized it. **For example, where a GitHub user has made an email address public-facing for the purpose of identification and attribution, do not use that email address for the purposes of sending unsolicited emails to users** or selling User Personal Information, such as to recruiters, headhunters, and job boards, or for commercial advertising. We expect you to reasonably secure any User Personal Information you have gathered from GitHub, and to respond promptly to complaints, removal requests, and "do not contact" requests from GitHub or GitHub users.

You can go on his [profile](https://github.com/ruslantalpa) page and right next to the "Follow" button there is a button "..." for me. This opens a menu with "Block or report user". And then go from there.

**Comment by wolfgangwalther** [comment]
yamatt:
> Have you been able to replicate my findings?

swuecho:
> PS: I also got the spam email, but I did not care that much.

Thanks for confirming!

**Comment by yamatt** [comment]
> You can go on his profile page and right next to the "Follow" button there is a button "..." for me. This opens a menu with "Block or report user". And then go from there.

Thanks again @wolfgangwalther I shall do that

**Comment by yamatt** [comment]
Just an update. This is progressing with GitHub's Trust & Safety Team

**Comment by yamatt** [comment]
They will be raising it with @ruslantalpa. I assume as an isolated occurrence there is not a great deal that they can do.

I'll leave it to you to decide @wolfgangwalther but I expect we can close this and hopefully others will find it in future and raise their own report to GitHub as per the previous response.
