### ISSUE TITLE
`postgrest-watch postgrest-test-spec` failures related to coverage

### ISSUE THREAD

**Issue by monacoremo** [PostgREST/postgrest#1807]
When using `postgrest-watch postgrest-test-spec`, I somtimes get the output below instead of a proper spec test run. I think it happens when I aborted a previous test run by saving another change. To get it back to work, I need to ctrl-c out of postgrest-watch and restart it. @wolfgangwalther, that seems to be hpc/coverage related, one of your areas of expertise! Any ideas?

```
Build profile: -w ghc-8.8.4 -O1                                              
In order, the following will be built (use -v for more details):              - postgrest-7.0.1 (test:spec) (first run)                                    - 
postgrest-7.0.1 (test:spec-querycost) (first run)                         Preprocessing test suite 'spec' for postgrest-7.0.1..                        Preprocessing test suite 'spec-querycost' for postgrest-7.0.1..              
Building test suite 'spec-querycost' for postgrest-7.0.1..                   Building test suite 'spec' for postgrest-7.0.1..                             
Running 1 test suites...                                                     
Test suite spec-querycost: RUNNING...                                        in module 'postgrest-7.0.1-inplace/PostgREST.Config'                         Hpc 
failure: module mismatch with .tix/.mix file hash number                 (perhaps remove /run/user/1001/tmp.wcBkOZL4y1/postgrest.tix file?)           Test suite spec-querycost: FAIL                                              
Test suite logged to:                                                        
/home/remo/Projects/postgrest/dist-newstyle/build/x86_64-linux/ghc-8.8.4/postgrest-7.0.1/t/spec-querycost/test/postgrest-7.0.1-spec-querycost.log         0 of 1 test suites (0 of 1 test cases) passed.                               Running 1 test suites...                                                     Test 
suite spec: RUNNING...                                                  in module 'postgrest-7.0.1-inplace/PostgREST.Config'                         Hpc failure: module mismatch with .tix/.mix file hash number                 (perhaps remove /run/user/1001/tmp.wcBkOZL4y1/postgrest.tix file?)           Test suite spec: FAIL                                                        Test suite logged to:                                                        /home/remo/Projects/postgrest/dist-newstyle/build/x86_64-linux/ghc-8.8.4/postgrest-7.0.1/t/spec/test/postgrest-7.0.1-spec.log                             0 of 1 test suites (0 of 1 test cases) passed.                               cabal: Tests failed for test:spec from postgrest-7.0.1.                      Tests failed for test:spec-querycost from postgrest-7.0.1.
```

**Comment by wolfgangwalther** [comment]
The error is this:
> failure: module mismatch with .tix/.mix file hash number                 (perhaps remove /run/user/1001/tmp.wcBkOZL4y1/postgrest.tix file?)

This happens when there is an old `.tix` file laying around.

First guess: We have enabled the `hpc` flag for all development builds - even those without `postgrest-coverage` - to avoid rebuilds between different commands. But only in `postgrest-coverage`, we take care to redirect the tix files to a proper location.

You could try to change `devCabalOptions` in `default.nix` to the following for the time being:

```nix
  devCabalOptions =
    "-f dev -f-hpc --test-show-detail=direct";
```

(added the `-f-hpc`).

This will prevent `postgrest-coverage` from working, but should at least work around the error you're getting for now.

**Comment by wolfgangwalther** [comment]
We have this, that is supposed to take care of it already:

https://github.com/PostgREST/postgrest/blob/f99fd6cbad23763e3dad788b7a08d38fe2f659db/nix/overlays/checked-shell-script/checked-shell-script.nix#L26-L32

However, that runs for every shell script - so it runs for `postgrest-watch`, too. That means when using `postgrest-watch`, the directory is only cleaned up after `postgrest-watch` exits - not when the sub command exits.

Not sure how to solve this, yet.
