### ISSUE TITLE
Update `app.json`

### ISSUE THREAD

**Issue by wolfgangwalther** [PostgREST/postgrest#1809]
I don't know what it actually does, but [app.json](https://github.com/PostgREST/postgrest/blob/main/app.json) looks heavily out-of-date.

I assume we need to bring this up-to-date for the next release?

**Comment by steve-chavez** [comment]
The "Deploy to Heroku" button needs that file, not sure if this is being actively used though.

> I assume we need to bring this up-to-date for the next release?

Yep, it would need a version bump(ref: [Release Checklist](https://github.com/PostgREST/postgrest/wiki/Release-Checklist))

**Comment by wolfgangwalther** [comment]
> Yep, it would need a version bump(ref: [Release Checklist](https://github.com/PostgREST/postgrest/wiki/Release-Checklist))

Version bump is one thing... but that file looks like it has our config options listed. Shouldn't we add all the new config options, too?

**Comment by steve-chavez** [comment]
> Shouldn't we add all the new config options, too?

True, forgot about that. 

Maybe we can move the `app.json` to `postgrest-heroku`.

One of our users wrote this: https://postgrest.org/en/stable/install.html#deploying-to-heroku.

If that's the commonly used workflow, then perhaps we don't need to have the `app.json` here.

**Comment by wolfgangwalther** [comment]
Not sure if removing `app.json` wouldn't break that workflow, too. I just had a quick glance at the [heroku docs](https://devcenter.heroku.com/articles/setting-up-apps-using-the-heroku-platform-api) and it seems like the file is expected in the source repo:

> This article describes how to use the app-setups resource of the Platform API. The resource, together with an app.json manifest file embedded in the source code, can be used to programmatically setup an app.
