### ISSUE TITLE
Regression: Nightly throws 500 "Unexpected NULL"

### ISSUE THREAD

**Issue by dwagin** [PostgREST/postgrest#1832]
### Environment

* PostgreSQL version: 13.2
* PostgREST version: nightly (d3a8b5f6e1f541c5c6cde9398a7ba6a95cdbdb88)
* Operating system: FreeBSD 13

### Description of issue

There's a regression after 343e41c51d6cad33383043abb4ef15dc54a32245

PostgREST throws 500 "Unexpected NULL" instead 201 "Created".

@wolfgangwalther, why had you removed null PK value processing on this? https://github.com/PostgREST/postgrest/blob/6670a3214bc2f74eac10ff32eb69a38db3807eaf/src/PostgREST/Query/SqlFragment.hs#L174

### Testcase
```PLpgSQL
DROP VIEW IF EXISTS test_bug;
DROP TABLE IF EXISTS test_a;
DROP TABLE IF EXISTS test_b;

CREATE TABLE test_b
(
    id int,

    PRIMARY KEY (id)
);

CREATE TABLE test_a
(
    id   int,
    b_id int,

    PRIMARY KEY (id),
    FOREIGN KEY (b_id) REFERENCES test_b
);

CREATE OR REPLACE VIEW test_bug AS
SELECT a.id, b.id AS b_id
FROM test_a AS a
     LEFT JOIN test_b AS b ON a.b_id = b.id;

CREATE RULE test_bug_insert AS ON INSERT TO test_bug DO INSTEAD
    INSERT INTO test_a(id, b_id) VALUES (new.id, new.b_id) RETURNING id, b_id;
```

```HTTP
POST http://postgrest/test_bug
Content-Type: application/json

{"id": 1}

HTTP/1.1 500 Internal Server Error
...

{
  "message": "Row error: Wrong value parser used",
  "details": "Unexpected NULL"
}
```

**Comment by wolfgangwalther** [comment]
Thanks for reporting that - very helpful testcase!

> @wolfgangwalther, why had you removed null PK value processing on this?

Looking at the commit, I assume my thought process was:
- The problem was in returning location headers for non-pk columns (could be too long, could not have an index, etc.)
- We removed any non-pk-columns from the location header output. We did have some tests with `NULL` values - but those were all non-pk-columns.
- My assumption was: PK columns are by definition `NOT NULL` - we don't need the `NULL` handling anymore. This assumption was wrong.

**Comment by drTr0jan** [comment]
@wolfgangwalther, what about fix it?

**Comment by wolfgangwalther** [comment]
We will certainly fix it before the next release. Not sure who will be able to get to it and when, though.

It should not be difficult at all. @dwagin already referenced the relevant commit and line, so it will be as simple as adding a test and changing that line, I guess.

@drTr0jan would you like to give it a go? Happy to review a PR!

**Comment by drTr0jan** [comment]
@wolfgangwalther, I've prepared the PR. Unfortunately I'm not good at Haskell for preparing tests, but I've tested the PR in my environment.

**Comment by laurenceisla** [comment]
We discussed how could a PK column be null in https://github.com/PostgREST/postgrest/pull/1875#discussion_r654595446
