### ISSUE TITLE
Requests to volatile RPC with a single json parameter and which fires multiple triggers taking a very long time to complete

### ISSUE THREAD

**Issue by maxwst** [PostgREST/postgrest#1836]
### Environment

* PostgreSQL version: 10.15
* PostgREST version: 7.0.1
* Operating system: Amazon Linux 2
* nginx: 1:1.12.2-2.amzn2.0.2 

our postgrest conf contains:

db-uri = "postgres://authenticator:<password>@<server>:5432/<dbname>"
db-schema = "api"
db-anon-role = "web_anon"
db-pool = 10
db-pool-timeout = 1
server-port = 40001

our nginx conf contains:

       upstream postgrest_hhdb 
       {
            server localhost:40001;
        }

        location /hhdb_api/
        {
                if      ( $request_method = 'OPTIONS')
                {
                        set $options N;
                }

                if      (  $request_uri ~ '/rpc/' )
                {
                        set $options "${options}O";
                }

                if      ( $options = "NO" )
                {
                        add_header      'Access-Control-Allow-Origin' '*' always;

                        add_header 'Access-Control-Allow-Methods' 'GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD';
                         Modified-Since,Cache-Control,Content-Type';
                        add_header 'Access-Control-Allow-Headers' ' Authentication, authorization, content-type, prefer, Accept, Accept-Language, Content-Language';
                        add_header 'Access-Control-Max-Age' 86400;
                        add_header 'Content-location' '/api/rpc/';
                        return 200;
                }

                default_type                    application/json;
                proxy_hide_header               Content-Location;
                add_header                      Content-Location        /api/$upstream_http_content_location;
                proxy_set_header                Connection "";
                proxy_http_version              1.1;
                proxy_pass                      http://postgrest_hhdb/;
                proxy_read_timeout              3600;

                # The following tests are to emulate the pg_safeupdate PostgreSQL extension. That extension is not available on Amazon RDS Postgres.
                # https://github.com/PostgREST/postgrest/issues/1132
                if      ( $request_method ~ ^(DELETE|PATCH)$ )
                {
                        set $allowed N;
                }

                if      ( $is_args = "" )
                {
                        set $allowed "${allowed}O";
                }

                if      ( $allowed = "NO" )
                {
                        return 405;
                }
        }

### Description of issue

I am experiencing major perform when calling a stored procedure via postgrest
compared with calling it from psql. There are many statement level and a few row level triggers fired as a result of this procedure.

This procedure updates the database, another update procedure has the same issues, 

 Calling from psql
as

    set role myrole;
    start transaction;

    WITH pgrst_source AS (WITH pgrst_args AS (SELECT NULL) SELECT "api"."docket_creation"('{"dockets":[{"docket":{},"transactions":[{"transaction":{"batch_id":null,"best_before_date":null,"docket_id":1417,"minimum_price":1.5,"note":"","price":3,"product_code":"TL12","product_cost":1,"product_description":"","product_group_id":null,"product_id":217,"product_name":"12 Tray Large","quantity":1,"vat_rate_id":4,"vat_rate_percentage":0,"return_reason_id":null,"transaction_type_id":2},"transaction_discounts":[{"discount_percentage":5,"discount_type_id":10,"discount_value_per_unit":null,"minimum_quantity":null,"note":""}],"transaction_returns":[],"transaction_commissions":[{"commission_id":null,"commission_percentage":0,"commission_type_id":2,"customer_id":1,"delivery_agent_id":0,"effective_from":null,"effective_to":null,"is_cumulative":true,"owner":2,"product_id":217}]}],"docket_buy_x_get_y_discounts":[]}]}'::json) AS pgrst_scalar)
      
      SELECT
        null::bigint AS total_result_set,
        pg_catalog.count(_postgrest_t) AS page_total,
        (json_agg(_postgrest_t.pgrst_scalar)->0)::character varying AS body,
        coalesce(nullif(current_setting('response.headers', true), ''), '[]') AS response_headers
      FROM (SELECT "pgrst_source".* FROM "pgrst_source"    ) _postgrest_t;

or 

simply

     SELECT "api"."docket_creation"('{"dockets":[{"docket":{},"transactions":[{"transaction":{"batch_id":null,"best_before_date":null,"docket_id":1417,"minimum_price":1.5,"note":"","price":3,"product_code":"TL12","product_cost":1,"product_description":"","product_group_id":null,"product_id":217,"product_name":"12 Tray Large","quantity":1,"vat_rate_id":4,"vat_rate_percentage":0,"return_reason_id":null,"transaction_type_id":2},"transaction_discounts":[{"discount_percentage":5,"discount_type_id":10,"discount_value_per_unit":null,"minimum_quantity":null,"note":""}],"transaction_returns":[],"transaction_commissions":[{"commission_id":null,"commission_percentage":0,"commission_type_id":2,"customer_id":1,"delivery_agent_id":0,"effective_from":null,"effective_to":null,"is_cumulative":true,"owner":2,"product_id":217}]}],"docket_buy_x_get_y_discounts":[]}]}')

takes about 2 secs

when calling from a webapp or via curl with the call

    curl 'https://<server>/hhdb_api/rpc/docket_creation' \
       -X 'POST' \
       -H 'Connection: keep-alive' \
       -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"' \
       -H 'Prefer: params=single-object' \
       -H 'sec-ch-ua-mobile: ?0' \
       -H 'Authorization: Bearer $bearer_token' \
       -H 'Content-Type: application/json' \
       -H 'Accept: application/json, text/plain, */*' \
       -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36' \
       -H 'DNT: 1' \
       -H 'Origin: https://hh-tincan-dev.srv.handheld.ie' \
       -H 'Sec-Fetch-Site: same-site' \
       -H 'Sec-Fetch-Mode: cors' \
       -H 'Sec-Fetch-Dest: empty' \
       -H 'Referer: https://hh-tincan-dev.srv.handheld.ie/' \
       -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
       --data-raw '{"dockets":[{"docket":{},"transactions":[{"transaction":{"batch_id":null,"best_before_date":null,"docket_id":1428,"minimum_price":1.5,"note":"","price":3,"product_code":"TL12","product_cost":1,"product_description":"","product_group_id":null,"product_id":217,"product_name":"12 Tray Large","quantity":1,"vat_rate_id":4,"vat_rate_percentage":0,"return_reason_id":null,"transaction_type_id":2},"transaction_discounts":[{"discount_percentage":5,"discount_type_id":10,"discount_value_per_unit":null,"minimum_quantity":null,"note":""}],"transaction_returns":[],"transaction_commissions":[{"commission_id":null,"commission_percentage":0,"commission_type_id":2,"customer_id":1,"delivery_agent_id":0,"effective_from":null,"effective_to":null,"is_cumulative":true,"owner":2,"product_id":217}]}],"docket_buy_x_get_y_discounts":[]}]}' \
       --compressed

this is taking over a minute. 

I would expect both of these invocations to take a similar time

I have enable extensive logging to try to track this down the difference between the two methods seems to be delays when entering a nested trigger
~                     
Both methods complete successfully.

**Comment by wolfgangwalther** [comment]
> Calling from psql
> as
> 
> ```
> set role myrole;
> start transaction;
> 
> WITH pgrst_source AS (WITH pgrst_args AS (SELECT NULL) SELECT "api"."docket_creation"('{"dockets":[{"docket":{},"transactions":[{"transaction":{"batch_id":null,"best_before_date":null,"docket_id":1417,"minimum_price":1.5,"note":"","price":3,"product_code":"TL12","product_cost":1,"product_description":"","product_group_id":null,"product_id":217,"product_name":"12 Tray Large","quantity":1,"vat_rate_id":4,"vat_rate_percentage":0,"return_reason_id":null,"transaction_type_id":2},"transaction_discounts":[{"discount_percentage":5,"discount_type_id":10,"discount_value_per_unit":null,"minimum_quantity":null,"note":""}],"transaction_returns":[],"transaction_commissions":[{"commission_id":null,"commission_percentage":0,"commission_type_id":2,"customer_id":1,"delivery_agent_id":0,"effective_from":null,"effective_to":null,"is_cumulative":true,"owner":2,"product_id":217}]}],"docket_buy_x_get_y_discounts":[]}]}'::json) AS pgrst_scalar)
>   
>   SELECT
>     null::bigint AS total_result_set,
>     pg_catalog.count(_postgrest_t) AS page_total,
>     (json_agg(_postgrest_t.pgrst_scalar)->0)::character varying AS body,
>     coalesce(nullif(current_setting('response.headers', true), ''), '[]') AS response_headers
>   FROM (SELECT "pgrst_source".* FROM "pgrst_source"    ) _postgrest_t;
> ```

Is this the exact query that you get from the statement log when PostgREST runs it? Or is this already simplified a bit?

I'm surprised to see the the json body placed right in the argument list of your RPC. The query should look a bit more like the query in here: https://github.com/PostgREST/postgrest/issues/1652#issue-744663055.

Could you show the `CREATE FUNCTION` statement, too?

**Comment by maxwst** [comment]
I have updated the issue with some details I inadvertently left of in my rush to get an issue up and a copy of the initial Function.

The major omission being that it is on RDS.

The call is like your example, I just expanded my json into that call so I could call it from sql.
I also have called the function directly in sql in both instance it takes about 2 secs.

The Function is really big with lots of calls to functions within it and finally it fires a lot of triggers. I regard it more as a Stored Procedure than a function.
It is designed to be set based and where possible the triggers are statement level so that they too are set based.

I am attacking this from a few angles

I have a centos7 Virtualbox VM with a local PostgresSQL DB, postgrest  and nginx  and calling it there via a curl is also 2 secs.

I am also creating a standalone EC2 server with a local PostgresSQL DB, postgrest  and nginx  , that should be complete shortly.

When I call it anonymously ( with an admin user rather than the authenticator user) it also takes 2 secs.

I’m doing some more experimenting to try to pin this down I’ll update the issue as I get more info.

**Comment by wolfgangwalther** [comment]
> When I call it anonymously ( with an admin user rather than the authenticator user) it also takes 2 secs.

Two ideas to debug this further:
- Do any of your triggers depend on any of the `request.*` GUCs that PostgREST sets? Did you set those in your psql session, too?
- Did you login with the authenticator user and then use `set role` in your psql session? Maybe that triggers the longer execution time?

**Comment by maxwst** [comment]
I don’t use the request.* GUCs but I did retrieve some at one point thinking I might, I’ll remove that.
Postgrest runs with the authenticator but we logon with a Auth0 and postgrest sets the role from data in the Auth0 payload. I’m going to do some more experimentation in this area.

**Comment by maxwst** [comment]
In order to remove any RDS issues from the frame I've created a stand-alone postgresql DB on the same EC2 server that postgrest is running.

The test_postgrest function is an attempt to model as close as possible the call that postgrest makes at the start
The start of the postgrest_timings.txt file is basically my attempt to mimic the main postgrest call. That executes with the correct role in approx 2 Secs.

All the other successful tests bar two take approximately between 50 seecs and 60 secs. The two that succeed in a timely manner are both anonymous and but have a superuser as the db-anon-role. 

set role tracydemohandheldie_datapool;
start transaction isolation level read committed;
select  api.test_postgrest();
commit;

As you can see the only time the curl gets as fast as the sql function is when the a JWT header is missing and the db-anon-role is a superuser. Also the fact that it was on RDS doesn't seem to have affected it.

Our database is multi-tenancy with a column for tenant identification (owner)and row level security policies. However, these policies are ignored for superusers. So I expect that the row level security policies are giving postgrest a problem. These don't cause a problem when the I make a similar call from SQL for a non-superuser client so it must be postgrest specific.

I will delve into the postgres logs to see if I can spot anything, as a last try I mage the authenticator a superuser ( it may already have been one) but I was clutching at straws by this time. I've never dealt with Haskell so any pointers on where to start would be usefule and then I can delve into the code too.

The postgrest_timings.txt and db.log file can be viewed in parallel. 

postgrest_timings.txt:
[postgrest_timings.txt](https://github.com/PostgREST/postgrest/files/6403010/postgrest_timings.txt)

 
postgres log:
[db.log](https://github.com/PostgREST/postgrest/files/6402605/db.log)


Functions:
[test_postgrest.txt](https://github.com/PostgREST/postgrest/files/6402575/test_postgrest.txt)
[postgrest_authorisation.txt](https://github.com/PostgREST/postgrest/files/6402580/postgrest_authorisation.txt)
[docket_creation.txt](https://github.com/PostgREST/postgrest/files/6402581/docket_creation.txt)

**Comment by wolfgangwalther** [comment]
> The test_postgrest function is an attempt to model as close as possible the call that postgrest makes at the start.
> The start of the postgrest_timings.txt file is basically my attempt to mimic the main postgrest call. That executes with the correct role in approx 2 Secs.
> 
> set role tracydemohandheldie_datapool;
> start transaction isolation level read committed;
> select api.test_postgrest();
> commit;

The big difference between this test and the code that is executed in a real PostgREST request is the following taken from your `db.log`:

```
2021-04-29 22:56:16.433 UTC [23562] LOG:  statement:
SET LOCAL search_path = 'api', 'public';
SET LOCAL "role" = 'tracydemohandheldie_datapool';
SET LOCAL "request.jwt.claim.email" = 'tracydemo@handheld.ie';
SET LOCAL "request.jwt.claim.sub" = 'auth0|5c546f9675eb02096fdc3933';
SET LOCAL "request.jwt.claim.email_verified" = 'True';
SET LOCAL "request.jwt.claim.exp" = '1619785618';
SET LOCAL "request.jwt.claim.at_hash" = 'zUL-ZiAXeeeSYdlSGb-gcA';
SET LOCAL "request.jwt.claim.https://api.hhsalestrack.com/user_metadata" = '{"username":"tracydemohandheldie_datapool","organisation_id":10,"user_id":101}';
SET LOCAL "request.jwt.claim.iss" = 'https://handheld.eu.auth0.com/';
SET LOCAL "request.jwt.claim.role" = 'tracydemohandheldie_datapool';
SET LOCAL "request.jwt.claim.iat" = '1619699218';
SET LOCAL "request.jwt.claim.aud" = 'RMoSkFQrF5Y3FMBeKZ8kKNG2rGHoYYew';
SET LOCAL "request.jwt.claim.nonce" = 'AjXUaM7hKidDRERV7K3TvXb7j-FYpzUo';
SET LOCAL "request.method" = 'POST';
SET LOCAL "request.path" = '/rpc/docket_creation';
SET LOCAL "request.header.host" = 'postgrest_hhdb';
SET LOCAL "request.header.content-length" = '822';
SET LOCAL "request.header.accept-encoding" = 'deflate, gzip';
SET LOCAL "request.header.sec-ch-ua" = '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"';
SET LOCAL "request.header.prefer" = 'params=single-object';
SET LOCAL "request.header.sec-ch-ua-mobile" = '?0';
SET LOCAL "request.header.content-type" = 'application/json';
SET LOCAL "request.header.accept" = 'application/json, text/plain, */*';
SET LOCAL "request.header.user-agent" = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36';
SET LOCAL "request.header.dnt" = '1';
SET LOCAL "request.header.origin" = 'https://hh-tincan-dev.srv.handheld.ie';
SET LOCAL "request.header.sec-fetch-site" = 'same-site';
SET LOCAL "request.header.sec-fetch-mode" = 'cors';
SET LOCAL "request.header.sec-fetch-dest" = 'empty';
SET LOCAL "request.header.referer" = 'https://hh-tincan-dev.srv.handheld.ie/';
SET LOCAL "request.header.authorization" = 'Bearer [...]';SET LOCAL "request.header.accept-language" = 'en-GB,en-US;q=0.9,en;q=0.8';
2021-04-29 22:56:16.436 UTC [23562] LOG:  statement:
select auth.postgrest_authorisation();
```

I reformatted that a bit for readability. 

> All the other successful tests bar two take approximately between 50 seecs and 60 secs. The two that succeed in a timely manner are both anonymous and but have a superuser as the db-anon-role.
> [...]
> Our database is multi-tenancy with a column for tenant identification (owner)and row level security policies. However, these policies are ignored for superusers.

This is most certainly the problem. I'm pretty sure you are not hitting the right code path for your RLS when you do your `psql` tests. It's a bit tricky to get RLS right.

Can you show your RLS definitions? Are those created per user or `TO PUBLIC`?

Most importantly: What exactly do you compare your tenant identification / owner column to? I would expect this to be based on any of:
- `CURRENT_USER` (potentially problematic when you use views)
- `SESSION_USER` (big problem in general)
- any `request.jwt.claims.xxx` GUC (not reproduced in psql, yet)

> So I expect that the row level security policies are giving postgrest a problem. These don't cause a problem when the I make a similar call from SQL for a non-superuser client so it must be postgrest specific. These are only a problem for writable functions , read only functions are very fast although they also are affected by the row level security policies.
> 
> I will delve into the postgres logs to see if I can spot anything, as a last try I made the authenticator a superuser ( it may already have been one) but I was clutching at straws by this time. I've never dealt with Haskell so any pointers on where to start would be useful and then I can delve into the code too.

I don't think this is a problem with PostgREST at all. I'm sure it's possible to reproduce this with `psql` when:
- logging in as the correct user
- setting the environment (Role, GUCs etc.) correctly
- executing the query correctly

At least one of that will still be slightly off.

**Comment by maxwst** [comment]
I had just created that function for some tests, but it wasn’t any use and isn’t used now, It was just added to this issue for completeness

**Comment by maxwst** [comment]
Well that was hard to find

I added in the SET LOCAL's one at a time into my test function and identified that
SET LOCAL search_path = 'api', 'public';
was causing the problem if I reversed the order
SET LOCAL search_path = 'public', 'api';
it was back to the speed I expected
My solution is to explicitly set the search_path in the definition of the two functions that are causing me problems.
This solved it for me.

**Comment by wolfgangwalther** [comment]
> I added in the SET LOCAL's one at a time into my test function and identified that
> SET LOCAL search_path = 'api', 'public';
> was causing the problem if I reversed the order
> SET LOCAL search_path = 'public', 'api';
> it was back to the speed I expected

This means you were accessing some objects that you didn't mean to access. To me, this sounds like the underlying problem is related to RLS and the difference of accessing views vs tables. I'd be very careful here not to accidently avoid RLS alltogether somewhere...

**Comment by maxwst** [comment]
Wolfgang,

Now my urgent issue is resolved I have had a chance to reflect on this, for what it's worth here are my thoughts.

Firstly can I state that I find postgrest to be an excellent tool and would recommend it to any postgreSQL user.

I have used the api schema to limit the exposure to my public schema, as I'm sure all serious postgrest users have, but of course all the actual work is done in the public schema.

When I initially wrote these larger functions I noticed performance issues when they referred to tables that were also exposed as views ( most of them in my case ) and I changed the functions to explicitly refer to the public schema.
This dramatically improved performance. At this time I wasn't aware that postgrest was setting a local search_path.

The RLS in our database has been working perfectly for over a year and the policies are automatically generated and maintained and I don't think is related to the underlying issue but just helped expose it.

The real issue for me was that the optimiser wasn't using indexes properly hence my explicit references to schema.tablename in these exposed functions. This was obvious in these much larger functions but not in smaller functions. What wasn't obvious to me was that the trigger functions ( and we have a lot of these ) which didn't have explicit references and were using the local search_path. I have now set an explicit search_path in these larger functions which the triggers respect and hence the vast improvement in performance. I'm sure most postgresSQL/postgrest users don't have explicit references and will be caught with this but if their functions are much simpler it probably isn't noticeable.

I am now considering if this is causing us many smaller performance issues that aren't instantly noticeable but overall do affect our performance. And could this be a silent issue with the standard RESTful api calls ? 

Another use case in our database is to expose another postgrest api service which really should be through a different exposed schema. And in some cases this will mean some exposed functions are share between both schemas, therefore my search_path could be different. Rather than duplicate code I may have to create some wrapper functions which will cause a tiny context change performance hit. 

The simplest solution from my point of view is if the LOCAL serach_path was re-ordered this would help users who just implement the postgrest API against their database and require no changes to existing code or failing that the ability in the configuration to override it.

Many thanks for your time and help in investigating this issue I couldn't have solved it without having someone to bounce ideas off.

Thanks and regards

Steve

**Comment by wolfgangwalther** [comment]
> I have used the api schema to limit the exposure to my public schema, as I'm sure all serious postgrest users have, but of course all the actual work is done in the public schema.
> 
> When I initially wrote these larger functions I noticed performance issues when they referred to tables that were also exposed as views ( most of them in my case ) and I changed the functions to explicitly refer to the public schema.
> This dramatically improved performance. At this time I wasn't aware that postgrest was setting a local search_path.
> 
> The RLS in our database has been working perfectly for over a year and the policies are automatically generated and maintained and I don't think is related to the underlying issue but just helped expose it.
> 
> The real issue for me was that the optimiser wasn't using indexes properly hence my explicit references to schema.tablename in these exposed functions. This was obvious in these much larger functions but not in smaller functions. What wasn't obvious to me was that the trigger functions ( and we have a lot of these ) which didn't have explicit references and were using the local search_path. I have now set an explicit search_path in these larger functions which the triggers respect and hence the vast improvement in performance. I'm sure most postgresSQL/postgrest users don't have explicit references and will be caught with this but if their functions are much simpler it probably isn't noticeable.

The problem with index usage here is caused by RLS. You have policies, that "have been working perfectly for over a year". That's a strong indication that those policies are using the `CURRENT_USER` either explicitly or implicitly - because this is how to normally set those up, when not working with views.

Once you create a `VIEW`, the `CURRENT_USER` when checking the policies will be the **view owner**. Views are essentially created `SECURITY DEFINER`. So all RLS policies that are based on `CURRENT_USER` are **useless** when accessing them through a view.

This is the key difference between accessing your tables directly in the public schema and accessing them indirectly via views in the api schema.

The performance issue regarding index usage then follows from the "security barrier" those RLS create. Since the user running the query **on** the view (the real current_user as in your jwt) is different from the `CURRENT_USER` **"after""** the view (accessing the tables, this is the view owner), the conditions for those queries can't be merged. This way your basically losing all your indexes other than the one that uses the tenant column and have to do "full scans" on the all the tenant's data without index.

**Most importantly: Your current RLS paired with the api views are a security issue! They render the RLS ineffective!** This is the message that I am trying to sell here - the way your api schema is currently set up, you are losing the separation between tenants!

You need to either **repeat the RLS in the view definitions** or **change your RLS to not work with `CURRENT_USER` anymore**.

> I am now considering if this is causing us many smaller performance issues that aren't instantly noticeable but overall do affect our performance. And could this be a silent issue with the standard RESTful api calls ?
> 
> Another use case in our database is to expose another postgrest api service which really should be through a different exposed schema. And in some cases this will mean some exposed functions are share between both schemas, therefore my search_path could be different. Rather than duplicate code I may have to create some wrapper functions which will cause a tiny context change performance hit.
> 
> The simplest solution from my point of view is if the LOCAL serach_path was re-ordered this would help users who just implement the postgrest API against their database and require no changes to existing code or failing that the ability in the configuration to override it.

This is not a problem with PostgREST. You have `api` as your `db-schema` and `public` is the default `extra-search-path`. The order of the search path is absolutely correct and should not be changed at all.

The bigger issue is, that PostgreSQL is lacking some sort of `SECURITY INVOKER` views. This would really help solve the case.

**Comment by maxwst** [comment]
Actually you are very wrong here.

You are correct PostgreSQL views are normally owned by the definer who is a superuser and RLS rules are ignored. All my api views are altered so that they are owned by a special user who is not the definer to avoid these issues, this situation is enforced by a script that checks and sets this ownership , this ensures that the RLS is effective when using the views.

My RLS function runs as the actual current_user not as the definer this ensures that the RLS function works as I want.

This counteracts the fact that PostgreSQL doesn't have a SECURITY INVOKER.

I can assure you if this didn't work our application wouldn't work.

**Comment by wolfgangwalther** [comment]
> Actually you are very wrong here.

I'm glad I am! Good to know that you seem to be aware of the pitfalls here. :)

> My RLS function runs as the actual current_user not as the definer this ensures that the RLS function works as I want.

I'm curious: How do you do that?

**Comment by maxwst** [comment]
Can I have an email and I'll send you some scripts

**Comment by wolfgangwalther** [comment]
> Can I have an email and I'll send you some scripts

Don't really want to dig through a whole script. A small example in public would be really valuable, as that would be something that a lot of PostgREST users could use.

btw: you don't need to re-open and close this issue everytime you write a comment. If the issue is solved for you, keeping it closed is fine.

**Comment by maxwst** [comment]
A little bit of background

Our multi-tenancy is by organisational unit we use the column 'owner' to identify which organisation or part of the organisational structure owns that row.
i.e. a user can see everything equal to him or below on the organisation, we also have some global tables, but that would just complicate this example.
I have removed the organisational structure tests for simplicity, they are not required to illustrate a simple multi-organisational multi-tenancy.

Our users and roles table are sync'd with PostgreSQL roles via triggers, if you want to try this just put a manual entry in.

I hope this is clear enough, don't hesitate to ask , it took me a long time to work this out but I assure you it does work. I may have left something critical out of this it's been a long time since I needed to delve this deeply into it.


A simplified version of our organisations table
```
CREATE TABLE  organisations
(       id                      BIGSERIAL
,       name                    text                    NOT NULL
,       organisation_id         bigint          NOT NULL
-- Standard Columns
,       owner                   bigint          DEFAULT GET_ORGANISATION()      NOT NULL
,       CONSTRAINT organisations_pk PRIMARY KEY (id)
);
```
A simplified version of our users table 
```
CREATE TABLE  users
(       id                      BIGSERIAL
,       name                    text            NOT NULL
,       owner                   bigint          DEFAULT GET_ORGANISATION()      NOT NULL
,       CONSTRAINT users_pk PRIMARY KEY (id)
,       CONSTRAINT users_uk UNIQUE (name, owner)
);
```
A simplified version of our users table
```
CREATE TABLE  roles
(       id                      BIGSERIAL
,       name                    text            NOT NULL
,       owner                   bigint          DEFAULT GET_ORGANISATION()      NOT NULL
,       CONSTRAINT roles_pk PRIMARY KEY (id)
,       CONSTRAINT roles_uk UNIQUE (name, owner)
);
```
A simplified version of our transactions table
```
CREATE TABLE  transactions
(       id                      BIGSERIAL
,       quantity                numeric(36,12)                                  NULL
-- Standard Columns
,       owner                   bigint          DEFAULT GET_ORGANISATION()      NOT NULL
,       CONSTRAINT transactions_pk PRIMARY KEY (id)
);
```
Our script to create policies on our transactions table (all other tables are the same pattern)

```
 --
 --      GENERATED CODE
 --      GENERATED CODE
 --      GENERATED BY hhdevdbadmin ON 2021-04-30 18:27:52.509867+00
 --      GENERATED CODE
 --      GENERATED CODE
 --
 ALTER TABLE transactions enable row level security;
 DROP POLICY IF EXISTS transactions_policy on transactions ;
 DROP POLICY IF EXISTS transactions_insert_policy on transactions ;
 DROP POLICY IF EXISTS transactions_select_policy on transactions ;
 DROP POLICY IF EXISTS transactions_update_policy on transactions ;
 DROP POLICY IF EXISTS transactions_delete_policy on transactions ;
 CREATE POLICY transactions_insert_policy on transactions FOR INSERT WITH CHECK (true) ;
 CREATE POLICY transactions_select_policy on transactions FOR SELECT TO PUBLIC USING ( HAS_RIGHTS( owner, 'SELECT', 'transactions', 'hhdevdb', 'public' ));
 CREATE POLICY transactions_update_policy on transactions FOR UPDATE TO PUBLIC USING ( HAS_RIGHTS( owner, 'UPDATE', 'transactions', 'hhdevdb', 'public' ));
 CREATE POLICY transactions_delete_policy on transactions FOR DELETE TO PUBLIC USING ( HAS_RIGHTS( owner, 'DELETE', 'transactions', 'hhdevdb', 'public' ));
```

a sample select policy on our transactions table an underlying table looks like this:
```
POLICY "transactions_select_policy" FOR SELECT
      USING (has_rights(owner, 'SELECT'::character varying, 'transactions'::character varying, 'hhdevdb'::character varying, 'public'::character varying))
```
we generate views like this: 
```
--
 --      GENERATED CODE
 --      GENERATED CODE
 --      GENERATED BY hhdevdbadmin ON 2021-04-29 02:41:12.66685+01
 --      GENERATED CODE
 --      GENERATED CODE
 --
 DROP VIEW IF EXISTS api.transactions
         ;
 CREATE OR REPLACE VIEW api.transactions AS
         SELECT *
         FROM public.transactions
         WHERE owner IN ( select id from public.organisations) -- **added for performance**
         ;

 ALTER VIEW api.transactions OWNER TO writer ; -- **This is critical for RLS**
```
The has_rights() function looks like this
```
CREATE OR REPLACE FUNCTION HAS_RIGHTS
(       P_OWNER                 bigint
,       P_ACTION                VARCHAR default null
,       P_OBJECT_NAME           VARCHAR default null
,       P_OBJECT_CATALOG        VARCHAR default null
,       P_OBJECT_SCHEMA         VARCHAR default null
)
RETURNS boolean
AS
$$

DECLARE

V_HAS_RIGHTS            boolean         default false;


BEGIN
        P_ACTION                :=      COALESCE(P_ACTION,'%');
        P_OBJECT_NAME           :=      COALESCE(P_OBJECT_NAME,'%');
        P_OBJECT_CATALOG        :=      COALESCE(P_OBJECT_CATALOG,current_database() );
        P_OBJECT_SCHEMA         :=      COALESCE(P_OBJECT_SCHEMA,'public');

        <<main>>
        LOOP

/*
 *      Always let anyone write to a table, if all other permissions allow, shouldn't even get here
 */
                -- true if inserting ?
                IF      ( COALESCE(P_ACTION,'') = 'INSERT' )
                THEN
                        V_HAS_RIGHTS    :=      true;
                        exit    main;
                END IF;

                -- true if has superuser role or has special rds role rds_superuser
                IF      ( IS_SUPERUSER() )
                THEN
                        V_HAS_RIGHTS    :=      true;
                        exit    main;
                END IF;


                IF      ( GET_USER_TYPE() = GET_USER_TYPE('sysadmin'))
                THEN
                        V_HAS_RIGHTS    :=      true;
                        exit    main;
                END IF;

                -- true if organisations match
                IF      ( COALESCE(P_OWNER,0) = get_organisation()  )
                THEN
                        V_HAS_RIGHTS    :=      true;
                        exit    main;
                END IF;

        END LOOP main;

        return  V_HAS_RIGHTS;

END
$$
LANGUAGE        PLPGSQL
-- SECURITY     DEFINER     -- NB: runs as current_user
;
```
This function is critical to get the users organisation the wrapper function allows it to get the current_users organisation and passes it to superuser function which has full access to the data.
```
CREATE OR REPLACE FUNCTION GET_ORGANISATION
 (
 )
 RETURNS  bigint
 AS $$

 DECLARE

 v_id bigint ;
 BEGIN

        return  get_organisation(user);

  END
  $$
  LANGUAGE        PLPGSQL
 ;

 CREATE OR REPLACE FUNCTION GET_ORGANISATION
 (
   p_name                        text
 )
 RETURNS  bigint
 AS $$

 DECLARE

 v_id bigint ;
 BEGIN

 SELECT  organisation_id
 INTO  v_id
         FROM    users
 WHERE  name = p_name
 UNION
 SELECT  owner
         FROM    roles
 WHERE  name = p_name
         LIMIT 1
         ;
 RETURN  v_id ;

  END
  $$
  LANGUAGE        PLPGSQL
  SECURITY      DEFINER
 ;
```
Our script to enforce ownership of the views , this can be run on the application DB changes, as a notification, or periodically
```
do $$
declare
    myrow record;
begin
for myrow in
select
     'ALTER VIEW '||quote_ident(v.schemaname)||'.'||quote_ident(v.viewname)||' OWNER TO "writer";' as viewq
from
    (select
      viewname
,       schemaname
-- ,    viewowner
from
      pg_catalog.pg_views
where
      schemaname NOT IN ('pg_catalog', 'information_schema')
and
      viewowner != 'writer'
    ) v
loop
execute myrow.viewq;
end loop;
end;
```

**Comment by wolfgangwalther** [comment]
Talking "small example"... :D.

The code you posted is essentially exactly what I thought it was. I came here to show the problem with using `current_user` - but failed to do so: It works in my example, too.

This is very confusing, because I'm sure I had problems with the correct `current_user` in the past, we've had other people report the same and recommendations are to use `request.jwt.claims.role` GUCs instead.

My minimal example to reproduce your setup:
```sql
create table t (
  owner text
);

insert into t (owner) values ('alice'), ('bob');

create role alice;
create role bob;
grant all privileges on table t to alice;

create function has_rights (owner text) returns boolean
language plpgsql as $$
begin
  raise notice 'current_user is %', current_user;
  return owner = current_user::text;
end$$;

alter table t enable row level security;
create policy s on t for select to public using (has_rights(owner));

create view v as select * from t;
alter view v owner to alice;
grant all privileges on table v to bob;

set role bob;
select * from v;
```

The returned result is correct: Only the row for bob. The notice also shows that `current_user` is bob, not alice, when querying the view.

As expected, when the view owner is the superuser, all RLS are by-passed. When the view owner is alice, the RLS kick in. The privileges show, that table `t` is in fact accessed via user alice, because bob doesn't even have privileges to do that.

Am I missing anything here or did I really just have a big misconception about `CURRENT_USER` with views + RLS?

**Comment by maxwst** [comment]
And if you remove the line that sets the view ownership it stops working
