### ISSUE TITLE
ARM Support 

### ISSUE THREAD

**Issue by quinwoods** [PostgREST/postgrest#1842]
### Environment

* Operating system: MacOS 

### Description of issue
Unable to run the executable `./postgrest` 
(Expected behavior vs actual behavior)
getting information about configuration 

(Steps to reproduce: Include a minimal SQL definition plus how you make the request to PostgREST and the response body)

**Comment by steve-chavez** [comment]
@quinwoods This one is already reported on https://github.com/PostgREST/postgrest/issues/1785. Let's continue there.
