### ISSUE TITLE
It is clear that there is a foreign key from departments to locations. Why does it return such information without a foreign key

### ISSUE THREAD

**Issue by edcjian** [PostgREST/postgrest#1845]
![8G{3A$YC2D( F6}PM)60CF8](https://user-images.githubusercontent.com/48635933/117278221-276fdc80-ae93-11eb-9005-a46766e4d328.png)
![}PJMB2P(1W4@~L7L7M{V%(5](https://user-images.githubusercontent.com/48635933/117278322-3d7d9d00-ae93-11eb-9317-d96fd1c9f805.png)

### Environment

* PostgreSQL version: docker latest version
* PostgREST version: docker latest version
* Operating system:ubuntu 20

### Description of issue
this is my request :

http://111.229.235.215:3000/employees?select=departments(*)

this is  sql structure

-- ----------------------------
-- Table structure for employees
-- ----------------------------
DROP TABLE IF EXISTS "public"."employees";
CREATE TABLE "public"."employees" (
  "employee_id" int4 NOT NULL,
  "first_name" varchar(20) COLLATE "pg_catalog"."default",
  "last_name" varchar(25) COLLATE "pg_catalog"."default",
  "email" varchar(25) COLLATE "pg_catalog"."default",
  "phone_number" varchar(20) COLLATE "pg_catalog"."default",
  "job_id" varchar(10) COLLATE "pg_catalog"."default",
  "salary" float8,
  "commission_pct" float8,
  "manager_id" int4,
  "department_id" int4,
  "hiredate" timestamp(6)
)
;

-- ----------------------------
-- Indexes structure for table employees
-- ----------------------------
CREATE INDEX "dept_id_fk" ON "public"."employees" USING btree (
  "department_id" "pg_catalog"."int4_ops" ASC NULLS LAST
);
CREATE INDEX "job_id_fk" ON "public"."employees" USING btree (
  "job_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table employees
-- ----------------------------
ALTER TABLE "public"."employees" ADD CONSTRAINT "employees_pkey" PRIMARY KEY ("employee_id");

-- ----------------------------
-- Foreign Keys structure for table employees
-- ----------------------------
ALTER TABLE "public"."employees" ADD CONSTRAINT "dept_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."departments" ("department_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."employees" ADD CONSTRAINT "job_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."jobs" ("job_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Table structure for departments
-- ----------------------------
DROP TABLE IF EXISTS "public"."departments";
CREATE TABLE "public"."departments" (
  "department_id" int4 NOT NULL,
  "department_name" varchar(3) COLLATE "pg_catalog"."default",
  "manager_id" int4,
  "location_id" int4,
  "employees_ids" int4
)
;

-- ----------------------------
-- Indexes structure for table departments
-- ----------------------------
CREATE INDEX "loc_id_fk" ON "public"."departments" USING btree (
  "location_id" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table departments
-- ----------------------------
ALTER TABLE "public"."departments" ADD CONSTRAINT "departments_pkey" PRIMARY KEY ("department_id");

-- ----------------------------
-- Foreign Keys structure for table departments
-- ----------------------------
ALTER TABLE "public"."departments" ADD CONSTRAINT "ad" FOREIGN KEY ("employees_ids") REFERENCES "public"."employees" ("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."departments" ADD CONSTRAINT "loc_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations" ("location_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

**Comment by wolfgangwalther** [comment]
Please provide all the necessary info in text form - not as a screenshot. See this hint in the issue template:

> (Steps to reproduce: Include a minimal SQL definition plus how you make the request to PostgREST and the response body)

- `CREATE TABLE` statements for both tables
- the request you make
- the response you get

Please also note the following comment in the issue template:

> Before reporting a bug:
> If your database schema has changed while the PostgREST server is running,
> send the server a SIGUSR1 signal or restart it(http://postgrest.org/en/stable/admin.html#schema-reloading)
> to ensure the schema cache is not stale. This sometimes fixes apparent bugs.

Ensure you have a reloaded schema cache.

**Comment by steve-chavez** [comment]
:thinking: I think @edcjian might have a point. The error is not precise enough. It leads into thinking there could be something wrong with pg, and not PostgREST.

https://github.com/PostgREST/postgrest/blob/082c91c85518d4b2ea97b848bba6e2981d962743/src/PostgREST/Error.hs#L88-L89

It should be like:

> Could not find foreign keys between these entities **in PostgREST schema cache**. No relationship found between parent and child.

Or perhaps "**in our schema cache**". Additionally, a `hint` might be useful, similar to what @laurenceisla is doing on https://github.com/PostgREST/postgrest/pull/1841.

**Comment by edcjian** [comment]
Why is it OK after restart

**Comment by edcjian** [comment]
Why is it OK after restart ，don't get it

**Comment by steve-chavez** [comment]
@edcjian Because PostgREST has a [schema cache](https://postgrest.org/en/stable/admin.html#schema-reloading), and it can get stale if you don't reload it.
