### ISSUE TITLE
POST request with Content-Type: application/x-www-form-urlencoded header hangs when targeting an overloaded function

### ISSUE THREAD

**Issue by laurenceisla** [PostgREST/postgrest#1846]
### Environment

* PostgreSQL version: 12.6
* PostgREST version: nightly
* Operating system: WSL - Ubuntu 20

### Description of issue

When a POST request is made with the `Content-Type: application/x-www-form-urlencoded` header to an overloaded function, the process hangs instead of returning the function result.

Steps to reproduce:

```sql
create or replace function test.textparam(texto text, otrotexto text) returns text as $textparam$
begin
    return concat(texto, ' - ' , otrotexto);
end
$textparam$ language plpgsql stable;

create or replace function test.textparam(texto text) returns text as $textparam$
begin
    return texto;
end
$textparam$ language plpgsql stable;
```
Then doing a POST request after reloading the schema with a `Content-Type: application/x-www-form-urlencoded` header

```bash
curl -d "texto=test" -X POST http://localhost:3000/rpc/textparam
```

It should respond with `"test"` but the process hangs.

**Comment by laurenceisla** [comment]
Working on #1841 I noticed that in this case, the `payloadKeys` passed to the `findProc` function are these:

https://github.com/PostgREST/postgrest/blob/082c91c85518d4b2ea97b848bba6e2981d962743/src/PostgREST/Request/ApiRequest.hs#L248

When an overloaded function is found, it reaches this part of the code.

https://github.com/PostgREST/postgrest/blob/082c91c85518d4b2ea97b848bba6e2981d962743/src/PostgREST/DbStructure/Proc.hs#L95

That's where I think the issue is, need some help debugging it.

**Comment by wolfgangwalther** [comment]
I have not tried to reproduce this, yet, but looking at the code I observe the following:

> https://github.com/PostgREST/postgrest/blob/082c91c85518d4b2ea97b848bba6e2981d962743/src/PostgREST/Request/ApiRequest.hs#L248

Are you sure this line is even hit?

A few lines down we have:
https://github.com/PostgREST/postgrest/blob/082c91c85518d4b2ea97b848bba6e2981d962743/src/PostgREST/Request/ApiRequest.hs#L264

That means we have `CTUrlEncoded` - and `application/x-www-form-urlencoded` will never become `CTOther`. So I assume the line is actually **not** hit and that causes the problem with finding the right overloaded function - we just don't have the correct `payloadKeys` to work with.

I suggest you try to change the `CTOther` to `CTUrlEncoded` and see where that leads.

---

In any case the "process hangs" should probably be examined further. If my observation is correct, then we just try to parse the body as json, even though it is not correct json. So even if we fix the bug above, what will happen when sending the same body (actual form-urlencoded) with a json header? Will we be able to hit that case, too?

**Comment by wolfgangwalther** [comment]
> It should respond with `"test"` but the process hangs.

Just to confirm: Hangs for me, too!

**Comment by wolfgangwalther** [comment]
It does not hang in `v7.0.1`. Looks like this was introduced in 302d4e15ad9d4689caa132b0ad5cdab828de19da - so it's still unreleased (not counting nightlies).

**Comment by steve-chavez** [comment]
> It should respond with "test" but the process hangs.

:open_mouth: Can reproduce as well. Great find Laurence!

I do note that other requests succeed though. So the request hangs but not postgrest in its entirety(it can still respond to other requests).

**Comment by wolfgangwalther** [comment]
> In any case the "process hangs" should probably be examined further. If my observation is correct, then we just try to parse the body as json, even though it is not correct json. So even if we fix the bug above, what will happen when sending the same body (actual form-urlencoded) with a json header? Will we be able to hit that case, too?

So that seems to be no problem, it throws a parsing error for the json body.

The wrong `CTOther` seems to introduce an infinite loop. I can't see it, but it does make sense. I remember that the order of execution of `payloadKeys` vs `payload` was different between different content-types, so that will probably just jump between the two indefinitely.

**Comment by laurenceisla** [comment]
> I suggest you try to change the CTOther to CTUrlEncoded and see where that leads.

Yup, that did it! It no longer hangs.

> The wrong CTOther seems to introduce an infinite loop. I can't see it, but it does make sense. I remember that the order of execution of payloadKeys vs payload was different between different content-types, so that will probably just jump between the two indefinitely.

Yes, looks like it goes to the `payload` with the wrong CTOther, there it calls `target` which again calls `payloadColumns` thus making the infinite loop.

**Comment by wolfgangwalther** [comment]
> It doesn't seem to break any test, I'll change that line in #1841, that should fix this issue.

If you include it in #1841, it would be good to make it a separate commit. We should not merge it together with other changes. In any case, you should add a test-case - you already have everything you need for it.
