### ISSUE TITLE
Can't set both HTTP Header and Status

### ISSUE THREAD

**Issue by fjf2002** [PostgREST/postgrest#1856]
### Environment

* PostgreSQL version: 13
* PostgREST version: 7
* Operating system: Ubuntu 20.04

### Description of issue
I'm writing a function that tries to set an http header and a status code. The Header won't be sent.

The Function:
```sql
CREATE OR REPLACE FUNCTION test()
 RETURNS text
 LANGUAGE plpgsql
AS $function$
BEGIN
	PERFORM set_config('response.headers', '[{"Foo": "bar"}]', true);
	RAISE SQLSTATE 'PT401';
END
$function$;
```

The response does not contain the Foo Header (as I would expect).

**Comment by steve-chavez** [comment]
There's a way to set a status without raising on latest: https://postgrest.org/en/latest/api.html#setting-response-status-code

You'll have to use the latest [nightly](https://github.com/PostgREST/postgrest/releases/tag/nightly) for this.

**Comment by fjf2002** [comment]
OK, thanks!
