### ISSUE TITLE
OpenAPI description is missing the default value of postgres columns(?)

### ISSUE THREAD

**Issue by fjf2002** [PostgREST/postgrest#1871]
Hello, great work! I'm currently getting to know postgrest, and considering it for my project as a slim "application server" replacement.

### Environment

* PostgreSQL version: docker image 13
* PostgREST version: docker image v7.0.1

* Operating system: ubuntu 20.04 on WSL2

#### Expected behavior vs actual behavior
When a postgres column has a default value, I would wish that the OpenAPI description reflects that (which currently does not seem to be the case?).

#### Steps to reproduce
CREATE TABLE t (i int DEFAULT 42)

See https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md : I would have expected the following:

> default - The default value represents what would be assumed by the consumer of the input as the value of the schema if one is not provided. Unlike JSON Schema, the value MUST conform to the defined type for the Schema Object defined at the same level. For example, if type is string, then default can be "foo" but cannot be 1.

**Comment by laurenceisla** [comment]
Hello! I've checked, and the default value is in the definitions section:

``` javascript
{
  "definitions": {
    "t": {
      "properties": {
        "i": {
          "default": 42,
          "format": "integer",
          "type": "integer"
        }
      },
      "type": "object"
    }
  }
}
```

Is this what you're looking for? If so, maybe the [schema needed a reload](https://postgrest.org/en/stable/admin.html#schema-reloading) before making the request again.

**Comment by fjf2002** [comment]
Thanks. Sorry, that was my fault.

**Comment by fjf2002** [comment]
Wait a second... 
defaults still seem to be missing for data types text, date and time:

```sql
CREATE TABLE pvz.newtable (
	name text NOT NULL DEFAULT 'Sepp'::text,
	anzahl int4 NULL DEFAULT 42,
	rate float4 NULL DEFAULT 1.34,
	isvalid bool NOT NULL DEFAULT true,
	datum date NULL DEFAULT '1900-01-01'::date,
	zeit time NULL DEFAULT '13:37:00'::time without time zone,
	famstand text NOT NULL,
	CONSTRAINT newtable_pk PRIMARY KEY (name),
	CONSTRAINT newtable_famstand_fkey FOREIGN KEY (famstand) REFERENCES peri_viva_wl.familienstand(schluessel) DEFERRABLE
);

```

... yields the following spec:
```
"definitions": {
    "newtable": {
      "required": [
        "name",
        "isvalid",
        "famstand"
      ],
      "properties": {
        "name": {
          "format": "text",
          "type": "string",
          "description": "Note:\nThis is a Primary Key.<pk/>"
        },
        "anzahl": {
          "default": 42,
          "format": "integer",
          "type": "integer"
        },
        "rate": {
          "default": 1.34,
          "format": "real",
          "type": "number"
        },
        "isvalid": {
          "default": true,
          "format": "boolean",
          "type": "boolean"
        },
        "datum": {
          "format": "date",
          "type": "string"
        },
        "zeit": {
          "format": "time without time zone",
          "type": "string"
        },
        "famstand": {
          "format": "text",
          "type": "string",
          "description": "Note:\nThis is a Foreign Key to `familienstand.schluessel`.<fk table='familienstand' column='schluessel'/>"
        }
      },
      "type": "object"
    },
```

**Comment by fjf2002** [comment]
Any fixes or aat least a confirmation of the problem here?
Thank You.

**Comment by laurenceisla** [comment]
@fjf2002 I was checking, and the schema cache shows the default value as: `'Sepp'::text` for the `name` column, for instance. 

https://github.com/PostgREST/postgrest/blob/9568c4605a04c291ab76756bcc0ea373ff4e98cf/src/PostgREST/OpenAPI.hs#L108-L110

Here, it's decoded, but it looks like it returns `Nothing` for that kind of default values (the ones with explicit casting), that's why it shows null when accessing the OpenApi endpoint.

That would be a starting point to solve the issue, but for now we are mostly concentrating our efforts on the next v8 release.

**Comment by fjf2002** [comment]
@laurenceisla thank you for your investigation. I'm afraid my haskell knowledge probably does not suffice to solve it on my own. Good luck on v8 release.

**Comment by wolfgangwalther** [comment]
> Here, it's decoded, but it looks like it returns `Nothing` for that kind of default values (the ones with explicit casting), that's why it doesn't show when accessing the OpenApi endpoint.

I understand this is a bug then?
