### ISSUE TITLE
prepared statement already exists while connecting to DB or executing requests

### ISSUE THREAD

**Issue by Uhta** [PostgREST/postgrest#1873]
### Environment

* PostgreSQL version: 11
* PostgREST version: latest for 06/21
* Operating system: Windows 10

### Description of issue

Expected behaviour: no errors while connecting or executing a request

Actual behaviour: Error 42P05 "prepared statement \"0\" already exists"

### Steps to reproduce:
Install postgREST as docs say
Try to connect from cmd

**Comment by steve-chavez** [comment]
Hey @Uhta,

Try adding `db-prepared-statements=false` to the config. If that doesn't work please try a previous version: https://github.com/PostgREST/postgrest/releases/tag/v7.0.1

Also, are you using a connection pooler? This looks similar to the error in https://github.com/PostgREST/postgrest/issues/1011.

**Comment by Uhta** [comment]
Hello. I don't use a connection pooler.

Is it possible to use db-prepared-statment as an environmental variable? I want to use it in docker. 

I also added the line ```PREPARED_THRESHOLD = "0" ``` to config file and it seems to work. Any chance to use this as an environmental variable as well?

**Comment by steve-chavez** [comment]
> Is it possible to use db-prepared-statment as an environmental variable? I want to use it in docker.

Yes, use it like `PGRST_DB_PREPARED_STATEMENTS=true`.

> I also added the line PREPARED_THRESHOLD = "0" to config file and it seems to work

:thinking: Weird, we don't have such a config option.

**Comment by laurenceisla** [comment]
Transaction pooling is now compatible after commit db95bd1c3733eb979f4a65b3df0eaa16cadb4df2.
