### ISSUE TITLE
Add Retry-After hint when in recovery mode

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#1878]
If PostgREST loses the postgresql connection, it retries it with exponential backoff. If it's retrying the connection after 32 seconds, it wouldn't make sense for the client to retry a request in 1 or 2 seconds.

[Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) would be a nice hint for this case, clients can use its value for how much should they wait before retrying.

**Comment by gautam1168** [comment]
Hello, I'm completely new to Haskell. So, I want to make sure I'm moving in the right direction to make a PR for this issue.

Am I right in the following:

1. The exponential retry is implemented in `Workers.hs` in the `connectionStatus` function. 
2. This is called through the `postgrest` function in the file `App.hs` 
3. The `postgrest` function responds to the http requests. It checks if the statuscode is 503 and if it is, then it starts the connection worker in 1.

In this PR we should look at the line in `postgrest` function that starts/restarts the connection worker to obtain the worker's current state (as in how long until it will retry next). Once we have this information inside the `postgrest` function, we have to add a header to the response before responding to the client that gives the `Retry-After` hint.

So, I have to:
1. Figure out how long till next retry
2. Add hint to response

Am I right in assuming the above?

**Comment by gautam1168** [comment]
Im thinking I can add something in the `AppState` to keep track of how long till the next retry and update it from the line in `postgrest` function that starts/restarts the `connWorker`. Then I can get use that value to show the hint. Please tell me if I'm thinking non-sense here. It feels like I'm talking about creating a side effect and haskell is supposed to be free.

Basically I'm saying, Ill make a state in `AppState` which will be updated by retrying. Frankly I don't know if this is even possible.

**Comment by monacoremo** [comment]
Your intuition is exactly right! 💯

The issue here is that the AppState is not modeled very well, making this much more difficult than it should be.

Currently we track separate values for `statePgVersion`, `stateDbStructure`, `stateIsWorkerOn` etc., when it would be much clearer to model it somewhat like this:

```haskell
data AppStateConnection
  = NotConnected
  | Connecting { retryDelay :: Int }
  | ConnectionSucceeded PgVersion
  | ...
```

With this in place, it would be pretty straight forward to set the header. It's a pretty fundamental refactor, however, and it will be tricky to not change the behavior.

If you'd like to dive into this together, very happy to! Fully understand if you don't, though - In that case, I'd take a stab at remodeling the state and you could take care of the header afterwards!

**Comment by gautam1168** [comment]
Yes I'd like to make a PR for this. I was trying to modify the `AppState` by adding just a single `Int` like this:
```
data AppState = AppState
  { statePool         :: P.Pool -- | Connection pool, either a 'Connection' or a 'ConnectionError'
  , statePgVersion    :: IORef PgVersion
  -- | No schema cache at the start. Will be filled in by the connectionWorker
  , stateDbStructure  :: IORef (Maybe DbStructure)
  -- | Cached DbStructure in json
  , stateJsonDbS      :: IORef ByteString
  -- | Helper ref to make sure just one connectionWorker can run at a time
  , stateIsWorkerOn   :: IORef Bool
  -- | Binary semaphore used to sync the listener(NOTIFY reload) with the connectionWorker.
  , stateListener     :: MVar ()
  -- | Config that can change at runtime
  , stateConf         :: IORef AppConfig
  -- | Time used for verifying JWT expiration
  , stateGetTime      :: IO UTCTime
  -- | Time with time zone used for worker logs
  , stateGetZTime     :: IO ZonedTime
  -- | Used for killing the main thread in case a subthread fails
  , stateMainThreadId :: ThreadId
  -- | Keeps track of when the next retry for connecting to database is scheduled
  , stateRetryNextIn  :: IORef Int
  }
  ```
  
 And I was going to just set this in `Workers.hs` inside `shouldRetry` just before it returned `itShould`. But, your `AppStateConnection` is much nicer. Would you say I should try to add my version above first as it seems to be a fairly small change and then another PR can be made for this refactor with `AppStateConnection` data type? Alternatively I can make an attempt to make this refactor first.

**Comment by monacoremo** [comment]
> Would you say I should try to add my version above first?

Go for it! We’ll sort the rest out later :-)

**Comment by wolfgangwalther** [comment]
> I'd take a stab at remodeling the state and you could take care of the header afterwards!

I'm sure I will find time to review... :D

**Comment by monacoremo** [comment]
> I'm sure I will find time to review... :D

Yay, welcome back! 🥳

**Comment by monacoremo** [comment]
@gautam1168 if you want to discuss anything or need help, let us know!

**Comment by gautam1168** [comment]
I have setup nix on my system and got the unit tests running. Ill try to make a PR today, but Im new to haskell so it might take me a few days to actually get my changes to compile 😛. Ill keep you guys posted.

**Comment by gautam1168** [comment]
I have gotten the code to compile 😄. Although I have not actually run them yet. 

But I see that pull requests have to come from forks and I just made my changes in the clone. Ill transfer my changes to a fork, run some tests and open a PR, maybe tomorrow.

**Comment by gautam1168** [comment]
Hey so I have opened the PR and I have checked that lint and spec tests are passing. However, I have still not tested that the header is actually getting added to the responses. To be honest this would be my first time running postgrest. If you want to review the PR please do so, but I'm still working on it. I was just trying out the PR opening process or I would have waited before I opened it.

**Comment by gautam1168** [comment]
@steve-chavez how do I go about getting this PR reviewed/merged?

**Comment by steve-chavez** [comment]
@gautam1168 Check the comments I've left you on https://github.com/PostgREST/postgrest/pull/1916.

> postgrest-style-check has failed for some reason

Btw, that job didn't fail on our CI. Looks ok.
