### ISSUE TITLE
Error of custom variable name when having character '-' 

### ISSUE THREAD

**Issue by namnguyen1405** [PostgREST/postgrest#1898]
### Environment

* PostgreSQL version: 14beta2
* PostgREST version: 7.0.1
* Operating system: Centos 7

### Description of issue

I have tested my current setup with latest PostgreSQL ver 14beta2. This issue is limitation which does not allow to use the latest PostgreSQL as is.

The root cause can be explained with this snippet:

> postgres=# SET LOCAL "request.header.content-type" = 'text/csv';
> WARNING:  SET LOCAL can only be used in transaction blocks
> ERROR:  invalid configuration parameter name "request.header.content-type"
> DETAIL:  Custom parameter names must be two or more simple identifiers separated by dots.

In the PostgreSQL v14 beta2, it has function valid_custom_variable_name() for checking characters. Because it does not check character '-' in the content-type so this function will be return false. The above error message will be sent from function find_opt().

I'm posting this here so everyone know that this will be an issue when supporting PostgreSQL v14.

**Comment by steve-chavez** [comment]
Thanks for the heads up @namnguyen1405.

Yes, we're already discussing this on https://github.com/PostgREST/postgrest/issues/1857 - we even got the pg team to reconsider allowing many dots(.) in the GUCs, but the dash(-) is still a problem.

Let's follow up on that issue.
