### ISSUE TITLE
Error "could not look up local user..." on docker container for v8.0

### ISSUE THREAD

**Issue by laurenceisla** [PostgREST/postgrest#1921]
### Environment

* PostgreSQL version: Docker tag `postgres:14beta3`
* PostgREST version: using Docker image v8.0
* Operating system: Arch

### Description of issue

User reports that the following error is thrown when running the v.8.0 docker image.

```json
{
  "details": "could not look up local user ID 1000: No such file or directory\n",
  "code": "",
  "message": "Database connection error. Retrying the connection."
}
```

It all works well with the v7.0.1 docker image. Here's the [reference to the issue](https://gitter.im/begriffs/postgrest?at=611e2d4e025d436054da5ad2)

**Comment by monacoremo** [comment]
You need to explicitly set the user you are connecting to Postgres as.

With no user specified in the db-ui (`postgres://localhost:1234/dbname`):

```
$ docker run -e PGRST_DB_URI="postgres://localhost:1234/dbname" -e PGRST_DB_ANON_ROLE=anon -e PGRST_DB_SCHEMA=public -it postgrest/postgrest:v8.0.0
21/Aug/2021:08:27:21 +0000: An error ocurred when trying to query database settings for the config parameters
21/Aug/2021:08:27:21 +0000: ConnectionError (Just "could not look up local user ID 1000: No such file or directory\n")
21/Aug/2021:08:27:21 +0000: Attempting to connect to the database...
```

With user specified in the db-ui (`postgres://pgrstuser:password@localhost:1234/dbname`):

```
docker run -e PGRST_DB_URI="postgres://pgrstuser:password@localhost:1234/dbname" -e PGRST_DB_ANON_ROLE=anon -e PGRST_DB_SCHEMA=public -it postgrest/postgrest:v8.0.0                                                                      
21/Aug/2021:08:27:54 +0000: An error ocurred when trying to query database settings for the config parameters
21/Aug/2021:08:27:54 +0000: ConnectionError (Just "could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP/IP connections on port 1234?\ncould not connect to server: Address not available\n\tIs the server running on host \"localhost\" (::1) and accepting\n\tTCP/IP connections on port 1234?\n")
21/Aug/2021:08:27:54 +0000: Attempting to connect to the database...
```

Note: The db does not exist in either of those two examples.

If you don't specify the user name explicitly, you are relying on an undocumented user name that the docker image happens to use (or in the case of the newer image: simply does not set).

**Comment by laurenceisla** [comment]
Perfect! Issue [was solved.](https://gitter.im/begriffs/postgrest?at=6123704d3d8b825fab3309ae).

**Comment by gsdiniz** [comment]
I'm trying to use postgrest with tooljet v2 in a openshift installation.

Postgres is already set but postgrest always fails in connect.

The PGRST_DB_URI value is 

`
postgres://<<USER>:<<PASSWORD>>@postgres-svc.app.svc.local/lowcode
`

And the error message is 

```
26/Jan/2023:18:54:59 +0000: {"code":"PGRST000","details":"could not look up local user ID 1002610000: No such file or directory\n","hint":null,"message":"Database connection error. Retrying the connection."}
26/Jan/2023:18:54:59 +0000: Attempting to reconnect to the database in 32 seconds..
```

**Comment by MauryanKansara** [comment]
> I'm trying to use postgrest with tooljet v2 in a openshift installation.
> 
> Postgres is already set but postgrest always fails in connect.
> 
> The PGRST_DB_URI value is
> 
> `postgres://<<USER>:<<PASSWORD>>@postgres-svc.app.svc.local/lowcode`
> 
> And the error message is
> 
> ```
> 26/Jan/2023:18:54:59 +0000: {"code":"PGRST000","details":"could not look up local user ID 1002610000: No such file or directory\n","hint":null,"message":"Database connection error. Retrying the connection."}
> 26/Jan/2023:18:54:59 +0000: Attempting to reconnect to the database in 32 seconds..
> ```

hey did you solved this issue? if you did, can you please tell me how did you do that? I'm also facing the same error while setting up tooljet locally

**Comment by faria-karim-porna** [comment]
@gsdiniz @MauryanKansara Hey, have your issue been solved? If yes, then would you please explain your solution?

**Comment by laurenceisla** [comment]
@faria-karim-porna According to the linked Issue/Discussion: https://github.com/PostgREST/postgrest/discussions/2669#discussioncomment-5105850, the problem was a password with special characters. After URL encoding it, the connection worked.

**Comment by faria-karim-porna** [comment]
Thank you for the reply @laurenceisla. I have not find anything like PGRST_DB_URI in the .env file. Would you please tell me the path of file where I have to do the modification?

**Comment by gsdiniz** [comment]
In this [page](https://docs.tooljet.com/docs/setup/env-vars) has all env vars available on tooljet.

In this other [page](https://postgrest.org/en/stable/references/configuration.html#environment-variables) are the configuration of postgrest itself.

In my scenario, the password has special chars and it must be ASCII encoded. 

Example: @ must be %40 in password string.

**Comment by faria-karim-porna** [comment]
@gsdiniz Thank you very much for your reply. I have followed [this page](https://docs.tooljet.com/docs/contributing-guide/setup/docker/) to run  tooljet in my local machine using docker. 

I just want to work on client side of the project. I have not done any kind of set up for PostgreSQL in my local machine. Do I need to set it up locally or docker will create the environment for my local machine?

My .env contains this piece of text:
```
TOOLJET_HOST=http://localhost:8082
 LOCKBOX_MASTER_KEY=13c9b8364ae71f714774c82498ba328813069e48d80029bb29f49d0ada5a8e40
 SECRET_KEY_BASE=ea85064ed42ad02cfc022e66d8bccf452e3fa1142421cbd7a13592d91a2cbb866d6001060b73a98a65be57e65524357d445efae00a218461088a706decd62dcb
 NODE_ENV=development
 # DATABASE CONFIG
 PG_HOST=postgres
 PG_PORT=5432
 PG_USER=postgres
 PG_PASS=postgres
 PG_DB=tooljet_development
 ORM_LOGGING=all
```
I just changed the key and everything else is the same. Do I need to do any kind of change in the .env file or any file other than this?

Sorry for the long reply. Actually I have no experience with postrest and postgreSQL. I am extremely sorry to bother you.
