### ISSUE TITLE
Postgrest V8.0.0 package for Ubuntu does not execute afte extraction

### ISSUE THREAD

**Issue by jamesrascal** [PostgREST/postgrest#1925]
### Environment

* PostgreSQL version: n/a
* PostgREST version: v8.0.0
* Operating system: Ubuntu 20.04 (tested on multiple systems with the same results)

### Description of issue
Downloading the latest V8.0.0 Ubuntu release from the release page on Github results in an error, using the Generic Linux package resolves the error.

V8.0.0 release page includes "postgrest-v8.0.0-ubuntu-aarch64.tar.xz"

When using this package on Ubuntu 20.04 based machines results in the following error:

`-bash: ./postgrest: cannot execute binary file: Exec format error`

Using the V8.0.0 package "postgrest-v8.0.0-linux-x64-static.tar.xz" on a Ubuntu 20.04 system results in a running PostgREST application.

**Comment by monacoremo** [comment]
`aarch64` is for ARM machines, you  should use `postgrest-v8.0.0-linux-x64-static.tar.xz` on Intel x64/amd64 machines.
