### ISSUE TITLE
Simple objects returned from functions are converted to strings

### ISSUE THREAD

**Issue by mrussell16** [PostgREST/postgrest#1930]
### Environment

* PostgreSQL version: postgres:11 (docker image)
* PostgREST version: postgrest/postgrest:v8.0.0 (docker image)
* Operating system: Ubuntu 20.04

### Description of issue

The return type changed from version 7.0.1 to version 8.0.0 for functions that return simple object arrays.  In version 7.0.1 this returns the object with its original keys, but in version 8.0.0 the objects are converted to strings.

Defining a test function with permissions for anonymous users to run:

```sql
CREATE FUNCTION public_api.test() RETURNS TABLE(test TEXT) AS $$
    WITH series AS (
        SELECT generate_series(0, 10) AS gen
    )
    SELECT
        'Test ' || series.gen as test
    FROM series;
$$ LANGUAGE sql;

GRANT EXECUTE ON FUNCTION public_api.test() TO anon_user;
```

Using curl to post to this function:

```bash
curl -X POST http://127.0.0.1:3000/rpc/test -H "Accept: application/json"
```

With the PostgREST 7.0.1 image this returns (expected behavior):

```json
[{"test":"Test 0"}, 
 {"test":"Test 1"}, 
 {"test":"Test 2"}, 
 {"test":"Test 3"}, 
 {"test":"Test 4"}, 
 {"test":"Test 5"}, 
 {"test":"Test 6"}, 
 {"test":"Test 7"}, 
 {"test":"Test 8"}, 
 {"test":"Test 9"}, 
 {"test":"Test 10"}]
```

Taking this image down and replacing with the PostgREST 8.0.0 image the same command returns:

```json
["Test 0", "Test 1", "Test 2", "Test 3", "Test 4", "Test 5", "Test 6", "Test 7", "Test 8", "Test 9", "Test 10"]
```

**Comment by wolfgangwalther** [comment]
Thanks for the report. It seems like we introduced that change in #1654. Seems to be easy to fix, too - I just created #1931.
