### ISSUE TITLE
PATCH column with name longer than NAMEDATALEN will cause data loss in column

### ISSUE THREAD

**Issue by drmnk** [PostgREST/postgrest#1937]
### Environment

* PostgreSQL version: 13
* PostgREST version: Ubuntu
* Operating system: 20.04

### Description of issue

Because postgresql have 64 bytes fixed length of table and column names, postgresql truncates long names.
Although in Latin-based languages 64 bytes is enough for column name, when we name column in other language (such as Cyrillic) we will have only 32 symbols instead of 64 because Unicode.

So, if we name some column in Russian like "НаименованиеПлательщикаПриПеречисленииНалогов" (what means name of tax payer when he pays taxes) it will truncate to "НаименованиеПлательщикаПриПереч".

Anyway, PostgreSQL works fine with truncated names. Inserting, Updating - all good. It will autotruncate long names in sql-scripts and properly CRUD data.

But when we try to PATCH view with long column name in PostGREST by it's full name - it will cause to data loss (value will be null)

(Steps to reproduce: Include a minimal SQL definition plus how you make the request to PostgREST and the response body)

1. Create table "test" with only one column - "VeryLongNameVeryLongNameVeryLongNameVeryLongNameVeryLongNameVeryLongName" (72 chars)

It will be shrinked to "VeryLongNameVeryLongNameVeryLongNameVeryLongNameVeryLongNameVer" (63 chars)

2. Insert any data into it.
3. Try to update data via SQL.
4. Then try to PATCH data via PostGREST by full name:
{
 "VeryLongNameVeryLongNameVeryLongNameVeryLongNameVeryLongNameVeryLongName": true
}
5. Value will become null

**Comment by steve-chavez** [comment]
Reproduced :heavy_check_mark:

We use `json_populate_recordset` to do UPDATE
https://github.com/PostgREST/postgrest/blob/b05898d17f8e33c8c82fc1d05a30eb3044999668/src/PostgREST/Query/QueryBuilder.hs#L102-L104

And that function just ignores unknown keys

```sql
create table wow("VeryLongNameVeryLongNameVeryLongNameVeryLongNameVeryLongNameVeryLongName" text);

select * from json_populate_recordset(null::wow,'[{"VeryLongNameVeryLongNameVeryLongNameVeryLongNameVeryLongNameVeryLongName": "haha"}]');
┌─────────────────────────────────────────────────────────────────┐
│ VeryLongNameVeryLongNameVeryLongNameVeryLongNameVeryLongNameVer │
├─────────────────────────────────────────────────────────────────┤
│ [NULL]                                                          │
└─────────────────────────────────────────────────────────────────┘
```
Manually truncating the identifier works
```sql
select * from json_populate_recordset(null::wow,'[{"VeryLongNameVeryLongNameVeryLongNameVeryLongNameVeryLongNameVer": "haha"}]');
┌─────────────────────────────────────────────────────────────────┐
│ VeryLongNameVeryLongNameVeryLongNameVeryLongNameVeryLongNameVer │
├─────────────────────────────────────────────────────────────────┤
│ haha                                                            │
└─────────────────────────────────────────────────────────────────┘
```

---

To fix this, we'd have to transform the json before updating, with a query like https://github.com/PostgREST/postgrest/issues/1567#issuecomment-739478169.

Or perhaps this could be fixed in pg itself.

**Comment by drmnk** [comment]
Ah, I see, so the real problem is in PostgreSQL json function.
I do not think that you should do anything about this in PostgREST codebase.

I will try to ask in pg_hackers mailing list what they think about this situation.
Thank you for fast answer.

P.S. I just think that if we choose way of json transformation, it should be also configurable, because NAMEDATALEN can be different (for people who compile it from source) and also maybe it will be increased in future PostgreSQL releases, cause even Oracle already have 128 bytes. For now it's very rare situation to insert changes like this I think.

**Comment by drmnk** [comment]
If someone interested: https://www.postgresql.org/message-id/flat/CALSd-cppwDQ5%2BAmvrZ7a%2BXKQBCE9amS1uRK3X60%3Dq1iL7x0SaQ%40mail.gmail.com

(Steve, I use your SQL scripts in mail, thank you very much)

**Comment by drmnk** [comment]
As for now I just create a little php helper like this that works nice for me:

```
foreach($array as $key => $value) {
  unset($array[$key]);
  $array[mb_strcut($key,0,63)] = $value;
}
```

**Comment by drmnk** [comment]
Well, It looks like this issue won't be addressed before Postgres team find a way to increase or unfix NAMEDATALEN and when they do, it will disappear. But it can take long time.

@steve-chavez maybe it wont bother to you to do some json transforming accrodingly to PG NAMEDATALEN config?
I'm absolutely zero at Haskell and sorry that I can't suggest a patch by myself.

One can get information about current NAMEDATALEN by `show max_identifier_length;`
https://pgpedia.info/m/max_identifier_length.html

And it will solve problems with self-compiled versions of Postgresql and possible fixed increasing of NAMEDATALEN.

**Comment by wolfgangwalther** [comment]
As discussed in #2059, we think this is an issue that should be fixed in PostgreSQL itself. We are not supporting column names longer than NAMEDATALEN.
