### ISSUE TITLE
Cannot escape `"` for values in `in.`

### ISSUE THREAD

**Issue by soedirgo** [PostgREST/postgrest#1938]
### Environment

* PostgreSQL version: n/a
* PostgREST version: v8.0.0
* Operating system: n/a

### Description of issue

Repro steps:

```sql
CREATE TABLE t(data text);
INSERT INTO t(data) VALUES ('"');
```
```sh
> curl '.../t?data=in.(%22)'
```
```json
{
  "hint": null,
  "message": "malformed array literal: \"{\"\"\"}\"",
  "code": "22P02",
  "details": "Unexpected array element."
}
```
```sh
> curl '.../t?data=in.(%22%22%22)'
```
```json
{
  "hint": null,
  "message": "malformed array literal: \"{\"\"\"\"\"}\"",
  "code": "22P02",
  "details": "Unexpected array element."
}
```

Related:
- https://github.com/PostgREST/postgrest/issues/701
- https://github.com/supabase/postgrest-js/issues/164#issuecomment-796765843

**Comment by wolfgangwalther** [comment]
Related discussion:
https://github.com/PostgREST/postgrest/discussions/1591#discussioncomment-248604

**Comment by steve-chavez** [comment]
This happens because we build the array manually due to a Hasql limitation

https://github.com/PostgREST/postgrest/blob/0ba133a0bd1e41efa1c914e50d80b3270d52db29/src/PostgREST/Query/SqlFragment.hs#L226-L228

The solution would be to escape the double quote `"`, though ideally we'd patch Hasql.
