### ISSUE TITLE
Custom parameter names must be two or more simple identifiers separated by dots.","code":"42602"

### ISSUE THREAD

**Issue by lduguid** [PostgREST/postgrest#1971]
### Environment

* PostgreSQL version: 14.0
* PostgREST version: 8.0
* Operating system: Windows 10 Pro

### Description of issue

followed instructions on https://postgrest.org/en/v8.0/tutorials/tut0.html . Not using docker image but previuosly installed PostgreSQL 14.0 server, which runs as intended in all other respects as far as I can tell. After starting PostgREST with this conf.

```
db-uri			= "postgres://authenticator:mysecretpassword@localhost:5433/postgres"
db-schema		= "api"
db-anon-role	= "web_anon"
server-host		= "!4"
server-port		= 43000
log-level		= "info"
```

I have applied the various db-anon-roll and schema etc. as outlined in tutorial.  It all appears OK. However when I navigate to the URI -> http://192.168.50.140:43000/ (also used localhost and 127.0.0.1 etc.) I get these  responses;

`{"hint":null,"details":"Custom parameter names must be two or more simple identifiers separated by dots.","code":"42602","message":"invalid configuration parameter name \"request.header.upgrade-insecure-requests\""}`

[Refresh]

`{"hint":null,"details":"Custom parameter names must be two or more simple identifiers separated by dots.","code":"42602","message":"invalid configuration parameter name \"request.header.cache-control\""}`

Client does not appear to matter, Chrome, Firefox, CURL, PostWoman etc.

I am not sure if it is a bug per se or some misconfiguration on my side but some guidance on what to do next would be 

![image](https://user-images.githubusercontent.com/105060/135674296-a4b562c3-1b89-4aa4-833e-494b522b2c4c.png)

![image](https://user-images.githubusercontent.com/105060/135674342-261854fe-1b5a-449a-ac9f-fc5f7cef4d49.png)

![image](https://user-images.githubusercontent.com/105060/135674399-9e5307ec-f998-45ec-a795-40d6987a1683.png)

![image](https://user-images.githubusercontent.com/105060/135674434-e2149f97-e7bb-4d9d-9291-1c4230ec5926.png)

![image](https://user-images.githubusercontent.com/105060/135674544-fe2ebaf5-bcb2-40f6-9fb4-6c2f02ff87b5.png)
appreciated.

**Comment by bnjmnt4n** [comment]
This is a breaking change that Postgres v14 introduced, and PostgREST is not compatible with v14 yet. See https://github.com/PostgREST/postgrest/issues/1857.

**Comment by lduguid** [comment]
thanks for the heads up.  Did you want me to close this issue as it has been recorded and commented appropriately else where?

**Comment by steve-chavez** [comment]
@lduguid Yeah, let's continue on https://github.com/PostgREST/postgrest/issues/1857. Btw, there's also a fix in progress https://github.com/PostgREST/postgrest/pull/1968. We'll make a new release when that's merged.
