### ISSUE TITLE
rpc call with variable

### ISSUE THREAD

**Issue by omeradoni** [PostgREST/postgrest#1974]
**Environment**
PostgreSQL version: PostgreSQL 11.8 
PostgREST version: 7.0.1
Operating system: Centos7 compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit

**Description of issue**

I have created a function as follows in DB:
begin
    
	return query 

	
	select
		    customer_id,
			first_name::varchar,
			last_name::varchar
		from
			xxrad_customers
	where
		   create_date >= NOW() - (interval '1 day' * x);

end;

Where x is IN argument type integer 

The function select by sql query will display the correct output while sending different x variables  (e,g, SELECT apigetcustomeridlist1(9);)

But when running the same call from postgREST api, i'll get an error:
curl http://a.b.c.d:3000/rpc/apigetcustomeridlist2?(9)

{"hint":"No function matches the given name and argument types. You might need to add explicit type casts.","details":null,"code":"42883","message":"function radius.apigetcustomeridlist2() does not exist"}

The rpc call from Api will return value only if x argument is configured with default value, but i need the ability to get different outputs according to x which represents how many days from today.

Any ideas what may be the problem?

**Comment by steve-chavez** [comment]
> curl http://a.b.c.d:3000/rpc/apigetcustomeridlist2?(9)

That's not how arguments are passed to the function, it should be done like:

```bash
curl http://a.b.c.d:3000/rpc/apigetcustomeridlist2?x=9
```

Check this section of the docs: https://postgrest.org/en/v8.0/api.html#stored-procedures
