### ISSUE TITLE
RPC function calls not working in v8.0.0

### ISSUE THREAD

**Issue by sgnoyke** [PostgREST/postgrest#1981]
### Environment

* PostgreSQL version: postgres:12.1 (docker)
* PostgREST version: postgrest/postgrest:v8.0.0 (docker)
* Operating system: MacOS (Big Sur) 

### Description of issue

After using postgrest/postgrest:v8.0.0 (docker image) it was not possible to call a stored function in public schema. The following error was shown:

{
  "hint": "If a new function was created in the database with this name and arguments, try reloading the schema cache.",
  "message": "Could not find the public.fnc_nextval_as_json(p_seq_name) function in the schema cache"
}

Reloading schema cache did not solve the problem, i tried:

NOTIFY pgrst, 'reload schema'
 AND
Restart containers with docker-compose.

After downgrading to postgrest/postgrest:v7.0.0 the error was gone and the RPC call worked as expected without further changes.

**Comment by sgnoyke** [comment]
No DEFAULT value in FNC_NEXTVAL_AS_JSON:

```sql
CREATE OR REPLACE
FUNCTION FNC_NEXTVAL_AS_JSON
    (p_seq_name		VarChar)
RETURNS TABLE(SEQ_VAL JSON)
```

**Comment by wolfgangwalther** [comment]
Using the exact same example code you are, it's working fine for me.

Can you show your PostgREST config? Easiest would be to use `postgrest --dump-config`.

**Comment by sgnoyke** [comment]
Yes thank you, `docker-compose restart postgrest` worked now, i was able to execute my function. But should schema cache reload also work with the SQL command `NOTIFY pgrst, 'reload schema';`? I tried this and this had no effect. 
With version v7.0.0 it was not necessary to restart the postgrest container after a database update. Is there a way to bypass the container restart? We have a kubernetes cluster with a database. This database will upgrade frequently with new data and DDL changes etc. Now i have to restart the postgrest container with every database change? Can we do something better in this scenario?
