### ISSUE TITLE
v.6 and v.8 dont run on uberspace centOS7

### ISSUE THREAD

**Issue by Thorgrimson** [PostgREST/postgrest#1987]
### Environment
* PostgREST version: v.6 and v.8
* Operating system: uberspace7 centOS 7

### Description of issue
I try to build postgrest from source because uberspace is a shared webspace. run out of memory so I build it on my local machine and moved the binary to the webspace.
When I try to use the command there is this error:
For v.8
[aula@betelgeuse ~]$ postgrest
postgrest: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by postgrest)
postgrest: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by postgrest)
postgrest: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by postgrest)
For v.6
[aula@betelgeuse ~]$ postgrest
postgrest: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by postgrest)
postgrest: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by postgrest)

are there binarys for this wich I could use? so without sudo or package installation?

**Comment by steve-chavez** [comment]
Have you tried running the statically linked binary(`postgrest-v8.0.0-linux-x64-static.tar.xz`) on https://github.com/PostgREST/postgrest/releases/tag/v8.0.0?
