### ISSUE TITLE
Use libpq PG* environment variables if present, instead of requiring db-uri

### ISSUE THREAD

**Issue by ruckc** [PostgREST/postgrest#1991]
### Environment

* PostgreSQL version: docker.io/library/postgres:14
* PostgREST version: docker.io/postgrest/postgrest:v8.0.0
* Operating system: kubernetes 1.22.2

### Description of issue
I'd like to use `libpq` PG* environment variables instead of the PGRST_DB_URI variable.  My database username/password are generated by another container, and stored in a kubernetes secret.  I would like to leverage these secret values as pod/container environment variables directly, instead of having to overwrite the `postgrest/postgrest` container command to generate the db-uri value from them.  Given that postgrest is based on `libpq` this should be as simple as not making db-uri required and letting the environment variables get pulled in by `libpq` automatically.

**Comment by wolfgangwalther** [comment]
This turns out to be quite simple to do - and can already be done right now:

Just set db-uri to `postgresql://` only. This will read everything else from libpq environment variables.

We can use this as a default, too.
