### ISSUE TITLE
`is` operator not fully parametrized?

### ISSUE THREAD

**Issue by wolfgangwalther** [PostgREST/postgrest#1998]
As mentioned in https://github.com/PostgREST/postgrest/issues/1992#issuecomment-953535851, tracking here for better visibility:

> We are still depending on pgFmtLit in the fallback case for the is. operator. That means that this part of the query is not parametrized and in theory still up for sql injection attacks. @steve-chavez should we just disallow other values than NULL, FALSE and TRUE for is. altogether, instead of falling back to passing the value as ::unknown?

**Comment by steve-chavez** [comment]
`IS` cannot be prepared:

```sql
PREPARE boolplan AS SELECT * FROM projects where id IS $1

ERROR:  42601: syntax error at or near "$1"
LINE 1: PREPARE boolplan AS SELECT * FROM projects where id IS $1;
```
This is commented here:

https://github.com/PostgREST/postgrest/blob/a15f988c33b067c283b1e7fa36d9a7add0fa7439/src/PostgREST/Query/SqlFragment.hs#L245-L251

> should we just disallow other values than NULL, FALSE and TRUE for is

Hm, I don't recall if `pgFmtLit` was needed(maybe a test failed) but if not, only allowing NULL, FALSE, TRUE sounds good.

**Comment by wolfgangwalther** [comment]
> only allowing NULL, FALSE, TRUE sounds good.

For completeness, we could also add `UNKNOWN`: https://www.postgresql.org/docs/current/functions-comparison.html#FUNCTIONS-COMPARISON-PRED-TABLE

Although that might be cosmetic only:

> Notice that IS UNKNOWN and IS NOT UNKNOWN are effectively the same as IS NULL and IS NOT NULL, respectively, except that the input expression must be of Boolean type.

**Comment by steve-chavez** [comment]
> For completeness, we could also add UNKNOWN

That one seems nice for expressing three-valued logic(true, false, unknown). I'll add it.
