### ISSUE TITLE
Inconsistent return values for functions returning void

### ISSUE THREAD

**Issue by burrscurr** [PostgREST/postgrest#2001]
### Environment

* PostgreSQL version: 12.8
* PostgREST version: 8.0.0
* Operating system: Ubuntu 20.04

### Description of issue

Expected behavior: When calling functions declared returning void, postgrest returns a consistent value reflecting this (preferrably `204 No Content`).

Actual behavior: postgrest returns a empty string or null, depending on the language of the function.

### Example

```
CREATE FUNCTION x() RETURNS VOID AS $$ BEGIN
END $$ LANGUAGE plpgsql;
CREATE FUNCTION z() RETURNS VOID AS $$ $$ LANGUAGE sql;
```

For the first function, postgrest returns `""`:

```
GET /rpc/x HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:3000
User-Agent: HTTPie/1.0.3



HTTP/1.1 200 OK
Content-Range: 0-0/*
Content-Type: application/json; charset=utf-8
Date: Fri, 29 Oct 2021 19:48:17 GMT
Server: postgrest/8.0.0
Transfer-Encoding: chunked

""
```

For the sql function, postgrest returns `null`:

```
GET /rpc/z HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:3000
User-Agent: HTTPie/1.0.3



HTTP/1.1 200 OK
Content-Range: 0-0/*
Content-Type: application/json; charset=utf-8
Date: Fri, 29 Oct 2021 19:49:38 GMT
Server: postgrest/8.0.0
Transfer-Encoding: chunked

null
```

### Proposal

Postgrest should return `204 No Content` as result for functions that return void. (This also was suggested in #1762, but not implemented.)

**Comment by wolfgangwalther** [comment]
I tested things a bit. PostgreSQL returns `NULL` only for for `LANGUAGE SQL` (both new style in PG14 and old style). For procedural languages (tested `plpgsql` and `plpython3u`), it returns an empty string.

Let me cite @steve-chavez from #1762:
> HTTP has more weight for us, agree. But we'd be letting our HTTP design be influenced by a pg return nothing(void) semantic that doesn't really hold his ground. I think we should treat it as a return null for now. Until pg somehow changes select void_func() to return an empty '' unknown type(seems unlikely).

Well, I think that's the case. We just didn't know about it.

In any case, the empty body response with a `200` code we get now for plpgsql RPCs is something we should fix - it would throw the same error as reported in #1762 on the client-side.

I'm still very much in favor of returning `204 No Content` without a response body in all cases of `void`. Of course, without a `Content-Type` header, too. If a client tries to parse a response as json and fails, when there is no `Content-Type: application/json` header - then that's really their fault, not ours.

**Comment by steve-chavez** [comment]
If the client specifies `Accept: application/json`(as in #1762), then I still think the right response body would be `null` for both `sql`/`plpgsql` returning void, otherwise it would be invalid json.

> I'm still very much in favor of returning 204 No Content without a response body in all cases of void

If we go that route then if the client specifies `Accept: application/json` we would have to respond with `406 Not Acceptable`, otherwise we'd be doing content negotiation wrongly. I don't think it's useful to behave in this way though.

> Accept: */*

If the client specifies `Accept: */*` then yeah, I agree that 204 + no `Content-Type` is a valid response, although this would require extra logic/code on our side. Another option could be responding with the `Content-Type: application/json` plus `null` and reuse the above logic.

**Comment by wolfgangwalther** [comment]
> If the client specifies `Accept: application/json`(as in #1762), then I still think the right response body would be `null` for both `sql`/`plpgsql` returning void, otherwise it would be invalid json.
> 
> > I'm still very much in favor of returning 204 No Content without a response body in all cases of void
> 
> If we go that route then if the client specifies `Accept: application/json` we would have to respond with `406 Not Acceptable`, otherwise we'd be doing content negotiation wrongly. I don't think it's useful to behave in this way though.

I disagree.

Making an arbitrary HTTP request, the client does not know whether there will be a response body or not. So they have to include an `Accept` header to let the server know in which format they'd want that body to be in case there is one. Responding with `204 No Content` to that is perfectly fine.

And I'm sure we already do so. Whenever we have a `PATCH` or `DELETE` request with `Prefer: return=minimal`, the response is `204 No Content` - even when the request has an `Accept: application/json` header.

**Comment by steve-chavez** [comment]
> So they have to include an Accept header to let the server know in which format they'd want that body to be in case there is one. Responding with 204 No Content to that is perfectly fine.

@wolfgangwalther The [RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) says:

**If an Accept header field is present, and if the server cannot send a response which is acceptable according to the combined Accept field value, then the server SHOULD send a 406 (not acceptable) response.**

If the client would specify `Accept: application/json, */*` then that would have the interpretation you suggest: "I prefer json, but give me anything".

I'd be glad to be proven wrong, I'm just sticking to what the RFC says.

> And I'm sure we already do so. Whenever we have a PATCH or DELETE request with Prefer: return=minimal, the response is 204 No Content - even when the request has an Accept: application/json header.

Right. I guess we're wrong there too, if we want to stick to the RFC. It should be `null` for `Accept: application/json`.

**Comment by wolfgangwalther** [comment]
> I'd be glad to be proven wrong, I'm just sticking to what the RFC says.

The [RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.7) also says:

> Note: HTTP/1.1 servers are allowed to return responses which are
> not acceptable according to the accept headers sent in the
> request. In some cases, this may even be preferable to sending a
> 406 response. User agents are encouraged to inspect the headers of
> an incoming response to determine if it is acceptable.

---

But all of that is not really relevant, imho. If there is no response body - [there is no content negotiation](https://www.w3.org/Protocols/rfc2616/rfc2616-sec12.html#sec12):

> Any response containing an entity-body MAY be subject to negotiation, including error responses.

Turn that around: A response **not** containing an entity-body... may not be subject to content negotiation. And that makes a lot of sense: No Content = No Content Negotiation...

So, in fact, the server should decide about whether there is any response body to return - and if so, then start content negotiation. But when there is nothing to return.... it's just `204 No Content`.

Now, let's assume we're really negotiating. A little bit further down on the same page:

> However, an origin server is not limited to these dimensions and MAY vary the response based on any aspect of the request, including information outside the request-header fields or within extension header fields not defined by this specification.

**Comment by steve-chavez** [comment]
Cool. Thanks for citing the RFC as well.

> Note: HTTP/1.1 servers are allowed to return responses which are
not acceptable according to the accept headers sent in the
request. In some cases, this **may** even be preferable to sending a
406 response. User agents are encouraged to inspect the headers of
an incoming response to determine if it is acceptable.

> Any response containing an entity-body **MAY** be subject to negotiation, including error responses.

> However, an origin server is not limited to these dimensions and **MAY** vary the response based on any aspect of the request, including information outside the request-header fields or within extension header fields not defined by this specification.

Note that all these sections use the word **MAY**, which means **optional**.

At this point, it seems to me that both approaches are valid. Both being strict about complying the `Accept: application/json` and returning `null`(1) or not being strict on `Accept` and returning `204 No content`(2).

Doing (1) would require less work on the clients but historically we've been doing (2) for inserts, so it makes sense to stick to that. Also as mentioned in the RFC:

>  User agents are encouraged to inspect the headers of an incoming response to determine if it is acceptable.

Which I think is an acceptable constraint for any client.

So I agree with changing the `return void` to a `204 No Content` with no `Content-Type`.
