### ISSUE TITLE
AWS / EC2 - arm64 linux centos image - /lib64/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by johndpope** [PostgREST/postgrest#2004]
### Environment

* PostgreSQL version: (if using docker, specify the image)
* latest
* PostgREST version: (if using docker, specify the image)
* latest
* Operating system:

### Description of issue
can't run any of the released images on arm64 hardware. 
I tried many variations and previous builds from users but not working. 

./postgrest: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./postgrest)

UPDATE - it says it has 2.26 

```shell

➜  ~ sudo yum install glibc-devel
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
amzn2-core                                                                                                 | 3.7 kB  00:00:00
200 packages excluded due to repository priority protections
Package glibc-devel-2.26-55.amzn2.aarch64 already installed and latest version
Nothing to do
```

https://aws.amazon.com/amazon-linux-2/release-notes/

**glibc-2.26-55.amzn2.aarch64
glibc-2.26-55.amzn2.x86_64
glibc-all-langpacks-2.26-55.amzn2.aarch64
glibc-all-langpacks-2.26-55.amzn2.x86_64
glibc-common-2.26-55.amzn2.aarch64
glibc-common-2.26-55.amzn2.x86_64
glibc-devel-2.26-55.amzn2.x86_64
glibc-headers-2.26-55.amzn2.x86_64
glibc-langpack-en-2.26-55.amzn2.aarch64
glibc-langpack-en-2.26-55.amzn2.x86_64
glibc-locale-source-2.26-55.amzn2.aarch64
glibc-locale-source-2.26-55.amzn2.x86_64
glibc-minimal-langpack-2.26-55.amzn2.aarch64
glibc-minimal-langpack-2.26-55.amzn2.x86_64**

**Comment by steve-chavez** [comment]
Have you tried using the binary compiled for Ubuntu ARM64? 

[postgrest-v8.0.0-ubuntu-aarch64.tar.xz](https://github.com/PostgREST/postgrest/releases/download/v8.0.0/postgrest-v8.0.0-ubuntu-aarch64.tar.xz)

Likely you'll need to install some packages for it to work.

---

Otherwise you'd need to compile from source. Basically:

```
git clone https://github.com/PostgREST/postgrest
cd postgrest
cabal update
cabal v2-install exe:postgrest --overwrite-policy=always
```

Then you can get the binary from `~/.cabal`.

**Comment by johndpope** [comment]
```
    __|  __|_  )
       _|  (     /   Amazon Linux 2 AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-2/
4 package(s) needed for security, out of 19 available
Run "sudo yum update" to apply all updates.

➜  ~ cd postgrest
➜  postgrest git:(main) cabal update
Downloading the latest package list from hackage.haskell.org
➜  postgrest git:(main) cabal v2-install exe:postgrest --overwrite-policy=always
cabal: unrecognised command: v2-install (try --help)
```
