### ISSUE TITLE
Integrate Github Actions with self-hosted runner for ARM64

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#2010]
### Problem

Currently I have to manually compile PostgREST for ARM64 on an AWS Ubuntu instance - this has gotten too distracting and tedious.

And the same would have to be done for Docker https://github.com/PostgREST/postgrest/issues/1117#issuecomment-949260970.

### Proposal

Use Github Actions [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) to automate building on ARM64.

There's a list of examples in [jonico/awesome-runners](https://github.com/jonico/awesome-runners) from where https://github.com/machulav/ec2-github-runner looks exactly what we need.

**Comment by steve-chavez** [comment]
I was using a custom build for cabal, but looks that nowadays they do offer a [binary for aarch64](https://downloads.haskell.org/~cabal/cabal-install-3.6.0.0/cabal-install-3.6.0.0-aarch64-linux-deb10.tar.xz)(from https://www.haskell.org/cabal/download.html)

**Comment by laurenceisla** [comment]
Adapting the commands I used to upload to my repository (`latest` and `v9.0.0` were already in there), the manual process to add the arm64 architecture to the docker repo would be:

Create the dockerfile.

```dockerfile
# Dockerfile

FROM arm64v8/ubuntu:focal AS postgrest-arm64

RUN apt-get update -y
RUN apt install libpq-dev zlib1g-dev jq gcc libnuma-dev -y

COPY postgrest /usr/bin/postgrest

EXPOSE 3000

USER 1000

CMD postgrest
```

Execute the commands.

```sh
# Supposing the postgrest arm64 binary and Dockerfile exist in ~/postgrest-bin

cd ~/postgrest-bin

# Build and add to manifest

sudo docker build -t postgrest/postgrest:latest-arm64 .
sudo docker push postgrest/postgrest:latest-arm64
sudo docker manifest create \
postgrest/postgrest:latest \
--amend postgrest/postgrest:latest \
--amend postgrest/postgrest:latest-arm64
sudo docker manifest push postgrest/postgrest:latest

sudo docker build -t postgrest/postgrest:v9.0.0-arm64 .
sudo docker push postgrest/postgrest:v9.0.0-arm64
sudo docker manifest create \
postgrest/postgrest:v9.0.0 \
--amend postgrest/postgrest:v9.0.0 \
--amend postgrest/postgrest:v9.0.0-arm64
sudo docker manifest push postgrest/postgrest:v9.0.0
```

Maybe using `docker buildx build ...` is better, but couldn't make it work. 

Then delete the `v9.0.0-arm64` and `latest-arm64` tags from the repo.
