### ISSUE TITLE
Config param for not scanning the full schemata of a database

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#2013]
### Problem

Right now we scan the whole database - with all its schemas - to populate the [schema cache](https://postgrest.org/en/latest/schema_cache.html).

Although our DbStructure queries are fast, seems these still can cause problems when having too many schemas as reported on [gitter](https://gitter.im/begriffs/postgrest?at=6166f518d3ae402e474751a6).

### Proposal

Add a config param like:

```bash
db-scanned-schemas = "all" # default
db-scanned-schemas = "private,public,api" # custom
```

**Comment by wolfgangwalther** [comment]
> Right now we scan the whole database - with all its schemas - to populate the [schema cache](https://postgrest.org/en/latest/schema_cache.html).

This is not entirely true:

https://github.com/PostgREST/postgrest/blob/5cd7d35966b8e8481215ca181c7629191e7e470e/src/PostgREST/DbStructure.hs#L230

https://github.com/PostgREST/postgrest/blob/5cd7d35966b8e8481215ca181c7629191e7e470e/src/PostgREST/DbStructure.hs#L313

https://github.com/PostgREST/postgrest/blob/5cd7d35966b8e8481215ca181c7629191e7e470e/src/PostgREST/DbStructure.hs#L527

https://github.com/PostgREST/postgrest/blob/5cd7d35966b8e8481215ca181c7629191e7e470e/src/PostgREST/DbStructure.hs#L583-L584

https://github.com/PostgREST/postgrest/blob/5cd7d35966b8e8481215ca181c7629191e7e470e/src/PostgREST/DbStructure.hs#L776

---

There are some queries that are not filtering enough, yet:
- `allTables`:

https://github.com/PostgREST/postgrest/blob/5cd7d35966b8e8481215ca181c7629191e7e470e/src/PostgREST/DbStructure.hs#L488

- `allM2ORels`

- `allPrimaryKeys`:
 
https://github.com/PostgREST/postgrest/blob/5cd7d35966b8e8481215ca181c7629191e7e470e/src/PostgREST/DbStructure.hs#L736

---

> Add a config param like:

I don't understand the purpose of that. A user could completely break the schema cache, by specifying the wrong schemas here. In #1625 / [docs](https://postgrest.org/en/latest/api.html#embedding-chains-of-views) we already settled on searching `db-schemas` and `db-extra-search-path` only. I think we should just make that a general pattern.

**Comment by steve-chavez** [comment]
> This is not entirely true:

Right, I forgot about those :man_facepalming:

> A user could completely break the schema cache, by specifying the wrong schemas here.
> I think we should just make that a general pattern.

Fully agree. I've opened https://github.com/PostgREST/postgrest/issues/2015 for that.
