### ISSUE TITLE
Distributed Transaction Error when calling GreenPlum Function 

### ISSUE THREAD

**Issue by Zupit-Director** [PostgREST/postgrest#2021]
### Environment

* PostgreSQL version: Green Plum 6.X
* PostgREST version: 7.0.1
* Operating system: N/A

### Description of issue

When calling an fucntion it logs this WARINNG , 10 times :

`WARNING: the distributed transaction 'Commit Prepared' broadcast failed to one or more segments. Retrying ... try 10 DETAIL: gid=1636477463-0000006666, state=Retry Commit Prepared`

then it return 500 with error message "multiple updates to a row by the same query is not allowed"

Calling same function in pgAdmin does not raise warnings or errors. 

Any clues of what could be ? 

Thnx

**Comment by steve-chavez** [comment]
> When calling an fucntion it 

How are you calling the function? Can you share the curl request?

**Comment by victorvelasquezbinetwork** [comment]
> How are you calling the function? Can you share the curl request?

{"hint":null,"details":"gid=1636730167-0000000467, state=Retry Commit Prepared","code":"XX000","message":"unable to complete 'Commit Prepared' broadcast (cdbtm.c:655)"}

**Comment by Zupit-Director** [comment]
> > How are you calling the function? Can you share the curl request?
> 
> {"hint":null,"details":"gid=1636730167-0000000467, state=Retry Commit Prepared","code":"XX000","message":"unable to complete 'Commit Prepared' broadcast (cdbtm.c:655)"}

This is response , ca

**Comment by steve-chavez** [comment]
> curl -k -X POST http://server.example.com/rpc/ct12supplydesigntoolinptaccostwei -H "accept: application/json" -H "Content-Type: application/json" -d "{}"

I don't know Greenplum, but maybe it has problems with read/write transactions. Try calling your function with GET, that will be executed in a read-only transaction.

See https://postgrest.org/en/v8.0/api.html#immutable-and-stable-functions

**Comment by victorvelasquezbinetwork** [comment]
> 
> 
> > curl -k -X POST http://server.example.com/rpc/ct12supplydesigntoolinptaccostwei -H "accept: application/json" -H "Content-Type: application/json" -d "{}"
> 
> I don't know Greenplum, but maybe it has problems with read/write transactions. Try calling your function with GET, that will be executed in a read-only transaction.
> 
> See https://postgrest.org/en/v8.0/api.html#immutable-and-stable-functions

Hi, tried with this write function: 

curl -k -X GET http://server.example.com/rpc/ct12supplydesigntoolinptaccostwei -H "accept: application/json" -H "Content-Type: application/json" -d "{}"

Result:

"cannot execute UPDATE in a read-only transaction"

**Comment by steve-chavez** [comment]
> "cannot execute UPDATE in a read-only transaction"

If the function does an UPDATE(or other DML) then that error makes sense, you won't be able to call it with GET.

> Calling same function in pgAdmin does not raise warnings or errors.

Hm, at this point I'd suggest to enable database logging(https://postgrest.org/en/v8.0/admin.html#database-logs), repeat the request and get the exact query that PostgREST executes from the logs. Then run this query on pgAdmin and see if it gives the same error. 

> WARNING: the distributed transaction 'Commit Prepared' broadcast failed to one or more segments. Retrying ... try 10 DETAIL: gid=1636477463-0000006666, state=Retry Commit Prepared

Seems this is a generic error from Greenplum that can hide details coming from PostgreSQL https://github.com/greenplum-db/gpdb/issues/4530

**Comment by wolfgangwalther** [comment]
Did you confirm the same error happens with postgrest v8 or the latest pre-release?

**Comment by victorvelasquezbinetwork** [comment]
> 
> 
> > "cannot execute UPDATE in a read-only transaction"
> 
> If the function does an UPDATE(or other DML) then that error makes sense, you won't be able to call it with GET.
> 
> > Calling same function in pgAdmin does not raise warnings or errors.
> 
> Hm, at this point I'd suggest to enable database logging(https://postgrest.org/en/v8.0/admin.html#database-logs), repeat the request and get the exact query that PostgREST executes from the logs. Then run this query on pgAdmin and see if it gives the same error.
> 
> > WARNING: the distributed transaction 'Commit Prepared' broadcast failed to one or more segments. Retrying ... try 10 DETAIL: gid=1636477463-0000006666, state=Retry Commit Prepared
> 
> Seems this is a generic error from Greenplum that can hide details coming from PostgreSQL [greenplum-db/gpdb#4530](https://github.com/greenplum-db/gpdb/issues/4530)

Hi, in the Database Log it appears this error:

PANIC	XX000	unable to complete 'Commit Prepared' broadcast (cdbtm.c:655)	gid=1637055356-0000000002, state=Retry Commit Prepared

Stack trace:
1    0xbe3fbc postgres errstart (elog.c:557)
2    0xccdec0 postgres <symbol not found> (cdbtm.c:653)
3    0xcce356 postgres notifyCommittedDtxTransaction (cdbtm.c:328)
4    0x7270fd postgres <symbol not found> (xact.c:2759)
5    0x728555 postgres CommitTransactionCommand (xact.c:3748)
6    0xa814d5 postgres PostgresMain (postgres.c:3244)
7    0x6b3625 postgres <symbol not found> (postmaster.c:0)
8    0xa06d82 postgres PostmasterMain (postmaster.c:1523)
9    0x931021 postgres main + 0x421
10   0x3914c1ed1d libc.so.6 __libc_start_main + 0xfd
11   0x6b6ff1 postgres <symbol not found> + 0x6b6ff1

I'll try to get the query from the logs too see the differences.

**Comment by Zupit-Director** [comment]
We found the problem : GreenPlum "reacts bad" with SET LOCAL ROLE <rolename>  where <rolename> is a role without login , using an account with same grants but with login it works.

**Comment by wolfgangwalther** [comment]
Since we're suggesting to create those roles `NOLOGIN`, should we add a hint about this special case for GreenPlum in the docs?
