### ISSUE TITLE
Parsing pg_node_tree via JSON fails

### ISSUE THREAD

**Issue by wolfgangwalther** [PostgREST/postgrest#2024]
As mentioned in https://github.com/PostgREST/postgrest/issues/1992#issuecomment-970213836.

We'll need to get a reproduction of this first. @rinshadka could you help here, as mentioned in https://github.com/PostgREST/postgrest/issues/1992#issuecomment-970220037?

**Comment by wolfgangwalther** [comment]
@rinshadka bump - would really be helpful to get a reproduction of the problem, if possible, as I'd like to get that fixed asap.

**Comment by rinshadka** [comment]
@wolfgangwalther, We are actually using XMLTABLE for creating views in this schema.

**Comment by wolfgangwalther** [comment]
Thanks for the hint, I am able to reproduce with a stripped down example from the [docs](https://www.postgresql.org/docs/current/functions-xml.html#FUNCTIONS-XML-PROCESSING-XMLTABLE):

```sql
CREATE VIEW test.xml AS
SELECT *
  FROM (SELECT ''::xml AS data) _,
       XMLTABLE(
         ''
         PASSING data
         COLUMNS id int PATH '@id',
                 premier_name text PATH 'PREMIER_NAME' DEFAULT 'not specified'
       );
```

This fails when trying to `postgrest --dump-schema` with:

```
SessionError (QueryError "[... recursive view query ...]" ["[\"test\", \"tenant1\", \"tenant2\"]","[\"public\", \"extensions\", \"private\"]"] (ResultError (ServerError "22P02" "invalid input syntax for type json" (Just "Expected \",\" or \"}\", but found \"]\".") Nothing)))
parse error: Invalid numeric literal at line 1, column 10
```

Will investigate further.
