### ISSUE TITLE
Access information inside an array data type

### ISSUE THREAD

**Issue by laurenceisla** [PostgREST/postgrest#2075]
### Environment

* PostgreSQL version: v14
* PostgREST version: v9.0.0
* Operating system: EndeavourOS Linux

### Description of issue

Maybe we need a way to access information inside arrays. For instance, it looks like there's no way to translate these queries to PostgREST directly:

```sql
create table api.test (
  id int primary key ,
  numbers int[],
  numbers_mult int[][]
);

select numbers[1] from api.test;
select numbers_mult[1][1] from api.test;
```

From https://gitter.im/begriffs/postgrest?at=61b218526104ea63b6db6aea

**Comment by wolfgangwalther** [comment]
A few notes:

Seems like we can't use `[` and `]` in the URI directly, i.e. unencoded. [RFC 3986 Uniform Resource Identifier (URI): Generic Syntax](https://datatracker.ietf.org/doc/html/rfc3986):

>  A host identified by an Internet Protocol literal address, version 6
>   [RFC3513] or later, is distinguished by enclosing the IP literal
>   within square brackets ("[" and "]").  This is the only place where
>   square bracket characters are allowed in the URI syntax.

---

[PostgreSQL 14](https://www.postgresql.org/docs/14/release-14.html) added the ability to use this subscripting syntax not just on arrays, but also on jsonb and hstore types:

> Subscripting can now be applied to any data type for which it is a useful notation, not only arrays. In this release, the jsonb and hstore types have gained subscripting operators.

Supporting this syntax might become even more relevant in the future.

**Comment by wolfgangwalther** [comment]
For better visibility:

In https://github.com/PostgREST/postgrest/issues/1414#issuecomment-1003562226 I suggested to use the following:

Make a request with

```http
GET /test?select=numbers->0,numbers_mult->0->0
```

and turn that into

```sql
SELECT to_json(numbers)->0,
       to_json(numbers_mult)->0->0
  FROM test
```

This would make `[...]` unnecessary.

**Comment by steve-chavez** [comment]
Also linking a comment explaining the minimal change required https://github.com/PostgREST/postgrest/issues/1543#issuecomment-1028162880
