### ISSUE TITLE
[Feature request] Exclude empty attributes

### ISSUE THREAD

**Issue by Sjoerd82** [PostgREST/postgrest#2080]
Would it be possible to add an option to exclude NULL-values from the output?
This would be helpful to reduce bandwidth use and improve throughput times.

I for one would surely enable that option if it were to exist :-)

**Comment by steve-chavez** [comment]
@Sjoerd82 Hm, this is the same as feature request as https://github.com/PostgREST/postgrest/issues/1601 right?

**Comment by Sjoerd82** [comment]
Haha, yes it is, I had a deja-vu feeling, but could'nt find it. I will close this one. Suffice to say, this is still a desirable feature ;-)
