### ISSUE TITLE
PostgREST finds one function but not the other 

### ISSUE THREAD

**Issue by Jwrede** [PostgREST/postgrest#2097]
### Environment

* PostgreSQL version: docker image = `timescale/timescaledb:latest-pg12`
* PostgREST version: `postgrest/postgrest:v7.0.1`
* Operating system: Ubuntu 20.04.3 LTS

### Description of issue

(I used the recommended `docker-compose kill -s SIGUSR1 ...` and it didn't help) 

I have 2 `plpgsql` functions, the first one:
```sql
CREATE OR REPLACE FUNCTION logschema.lastupdates("pseudoIds" bigint[])
    RETURNS SETOF logschema."lastUpdates" 
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$
BEGIN
RETURN  QUERY (SELECT * FROM logschema."lastUpdates" WHERE "pseudoId" = ANY ("pseudoIds"));
END;
$BODY$;

ALTER FUNCTION logschema.lastupdates(bigint[]) OWNER TO logschema_user;
GRANT EXECUTE ON FUNCTION logschema.lastupdates(bigint[]) TO PUBLIC;
GRANT EXECUTE ON FUNCTION logschema.lastupdates(bigint[]) TO logschema_read_user;
GRANT EXECUTE ON FUNCTION logschema.lastupdates(bigint[]) TO logschema_user;
```

and the second one:
```sql
CREATE OR REPLACE FUNCTION logschema.valvemovementdaily("pseudoIds" bigint[])
    RETURNS SETOF logschema."valveMovement_daily" 
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$
BEGIN
RETURN  QUERY (SELECT * FROM logschema."valveMovement_daily" WHERE "pseudoId" = ANY ("pseudoIds"));
END;
$BODY$;

ALTER FUNCTION logschema.valvemovementdaily(bigint[]) OWNER TO logschema_user;
GRANT EXECUTE ON FUNCTION logschema.valvemovementdaily(bigint[]) TO PUBLIC;
GRANT EXECUTE ON FUNCTION logschema.valvemovementdaily(bigint[]) TO logschema_read_user;
GRANT EXECUTE ON FUNCTION logschema.valvemovementdaily(bigint[]) TO logschema_user;
```

As far as I can see these functions are almost exactly equivalent, both of them query a materialized view which uses a `bigint` as `pseudoId`. 
The top one works if I query it like this: `curl -X POST --header "Content-Type:application/json" 127.0.0.1:3019/rpc/lastupdates -d '{"pseudoIds": [1123123,2123123]}'` the other one returns the following error with the exact same query only with `.../rpc/valvemovementdaily`: `{"hint":"No function matches the given name and argument types. You might need to add explicit type casts.","details":null,"code":"42883","message":"function logschema.valvemovementdaily(pseudoIds => text) does not exist"}`.
Whats funny is that if I use the lower one with `pseudoIds text` it works if I cast `pseudoIds::bigint[]` later.

**Comment by laurenceisla** [comment]
This error: `function logschema.valvemovementdaily(pseudoIds => text) does not exist` leads me to believe that the schema cache was not reloaded (in v7.0 it defaulted the parameters to `text` when no function was found in the schema cache). Try restarting the whole docker container to see if it works that way, maybe the `docker-compose -kill ...` didn't work.

I also suggest using later versions of PostgREST due to the improvements made on detecting functions (disambiguation, improved error messages, etc.)

**Comment by Jwrede** [comment]
Yes this was the issue, I start PostgREST in my `docker-compose` file with the command `/bin/bash -c "sleep 10; exec postgrest /etc/postgrest.conf"` which is definitly a hacky implementation which resulted in postgrest starting before the database migration was finished (I thought `depends_on` in the docker-compose would let the migration finish but it doesn't). Could you give me advice on how to modify this command to wait for the migration to finish?

**Comment by laurenceisla** [comment]
If you're still using the v7.0 you could implement the [automatic schema cache reloading](https://postgrest.org/en/v7.0.0/admin.html?highlight=docker#schema-reloading) (see below the `docker` snippet); or, if you're using version 8.0.0 or up, you could send a `NOTIFY pgrst, 'reload schema'` command at the end of your migration. See  [Reloading with NOTIFY](https://postgrest.org/en/v9.0/schema_cache.html#reloading-with-notify) in the docs.

**Comment by Jwrede** [comment]
Thanks alot for your help!
