### ISSUE TITLE
Connecting to the postgresSQL DB via SSL from postgrest

### ISSUE THREAD

**Issue by pralow** [PostgREST/postgrest#2098]
i was trying to connect to the PostgreSQL which is SSL enabled, it was not able to pick the root CA. following are the environment variable that was passed. Any suggestion/solution? 

i tried passing the cert & key, in the connection string also again which resulted in the same issue only. 

Error Message is : root certificate file not found. 

         - name: PGRST_DB_URI
            value: "postgres://user:password@host:3010/dbname?sslmode=verify-ca"
          - name: PGRST_DB_SCHEMA
            value: "public"
          - name: PGRST_DB_ANON_ROLE
            value: "postgres"
          - name: PGSSLROOTCERT
            value: "@/Users/user/work/postgrest/ca.crt"
          - name: PGSSLKEY
            value: "@/Users/user/work/postgrest/tls.key"
          - name: PGSSLCERT
            value:  "@/Users/user/work/postgrest/tls.crt"

**Comment by pralow** [comment]
is there any option to pass sslcert, sslkey and sslrootcert to the connection String? any example to refer?  Thanks, Prakash

**Comment by wolfgangwalther** [comment]
Have a look at the [postgres docs](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS) - there are quite a few options to put into the connection string regarding SSL.

**Comment by wolfgangwalther** [comment]
To be more explicit, taking your example above, I would try something like:
```
     - name: PGRST_DB_URI
        value: "postgres://user:password@host:3010/dbname?sslmode=verify-ca&sslrootcert=/Users/user/work/postgrest/ca.crt&sslkey=/Users/user/work/postgrest/tls.key&sslcert=/Users/user/work/postgrest/tls.crt"
      - name: PGRST_DB_SCHEMA
        value: "public"
      - name: PGRST_DB_ANON_ROLE
        value: "postgres"
```
