### ISSUE TITLE
Get enum type from database

### ISSUE THREAD

**Issue by pintariching** [PostgREST/postgrest#2105]
### Environment

Is it possible to query the database for an enum type?
I have a table that uses them and I would like, if possible, to get the options from the database to display them in a form?

**Comment by dwagin** [comment]
SELECT unnest(enum_range(NULL::myenum))https://www.postgresql.org/docs/current/functions-enum.html

**Comment by pintariching** [comment]
So I guess I have to make functions query that? I hoped there was a built in way to get them out with postgrest like there is with views and functions.

**Comment by dwagin** [comment]
Just create a view for this. Closed #2105.
