### ISSUE TITLE
Raise exception returns 400 via rpc 

### ISSUE THREAD

**Issue by owais9211** [PostgREST/postgrest#2134]
Hello,
I have defined custom error codes in postgresql function having following syntax:

raise exception  sqlstate '99930' using message = 'Person not found';

i call my function via postman and i get the proper respone in the json body but the http error code is 400 (bad request).
But my requirement is to get a 200 OK response code on this. is it possible?.
I have also tried different log levels like debug, info, notice etc, they give me a 200 response code but the json body remains empty, without my custom error msg in it,

**Comment by wolfgangwalther** [comment]
> Hello, I have defined custom error codes in postgresql function having following syntax:
> 
> raise exception sqlstate '99930' using message = 'Person not found';
> 
> i call my function via postman and i get the proper respone in the json body but the http error code is 400 (bad request).

That's expected. We map all custom error codes to 400:

https://github.com/PostgREST/postgrest/blob/d9e016be8b841d992f0684fc9366ae6be781d5ef/src/PostgREST/Error.hs#L239

> But my requirement is to get a 200 OK response code on this. is it possible?.

We assume that every exception that is thrown, is indeed an error and we never return 200 on those. The example you gave also looks like an error, where you should not return 200, but rather 404.

If this is an error that you can handle server side, you could trap it in plpgsql: https://www.postgresql.org/docs/current/plpgsql-control-structures.html#PLPGSQL-ERROR-TRAPPING

If you really want to return 200 on a thrown exception, you try to use `PT200` as your error code, as described here: 
https://postgrest.org/en/stable/api.html#raise-errors-with-http-status-codes

> I have also tried different log levels like debug, info, notice etc, they give me a 200 response code but the json body remains empty, without my custom error msg in it,

Different log levels will not result in a different request. They will just change the output on stdout of the postgrest process. Not sure what you're looking at here.

**Comment by owais9211** [comment]
Thanks for the clarification. It really helped.
