### ISSUE TITLE
Too many informations for unauthenticated user

### ISSUE THREAD

**Issue by wiwwo** [PostgREST/postgrest#2136]
Hi!
I am using postgREST with JWT.
Calling the "root" user `curl http://localhost:3000` gives un-authenticated user a big bunch of information; not just the pgr version (which might tell an attacker that server runs a vulnerable version), but also the `paths` which exposes the structure of the database.
IMHO, an un-authenticated user should receive a 401 whatever they try to do, or at least hide some sensible server information.

**Comment by wolfgangwalther** [comment]
You can disable the OpenAPI output, if you want to. See https://postgrest.org/en/stable/configuration.html#openapi-mode.

The default is `follow-privileges`. That means that the paths you see in the anonymous output are probably accessible by your anonymous role (`db-anon-role`). You might need to adjust the permissions of that user.

> IMHO, an un-authenticated user should receive a 401 whatever they try to do, or at least hide some sensible server information.

An anonymous user should be able to see the openapi output to tell which resources they **can** use. There are many valid use-cases for anonymous access - and for those the anonymous openapi output makes a lot of sense.

However, we have recently added the ability to disable anonymous access completely in #2112. It's not released, yet, but once it is, you can disable anonymous access by omitting the `db-anon-role` setting.

**Comment by wiwwo** [comment]
Capito.
Thanks, that answered my question!

As a side note if I may, i noticed that revoking usage grant privilege on web_anon to api, un-authenticated users will not be able to see other sensitive information:

```
revoke usage on schema api from web_anon;
```

Have a nice one!

**Comment by wiwwo** [comment]
Capito.
Thanks, that answered my question!

As a side note if I may, i noticed that revoking usage grant privilege on web_anon to api, un-authenticated users will not be able to see other sensitive information:

revoke usage on schema api from web_anon;

Have a nice one!
