### ISSUE TITLE
Don't convert to JSON when calling a function which returns text and sets Content-Type as non-json

### ISSUE THREAD

**Issue by nileshtrivedi** [PostgREST/postgrest#2138]
### Environment

* PostgreSQL version: 14
* PostgREST version: 9.0.0
* Operating system: Mac OS (Apple Silicon)

### Description of issue

I wanted to serve the base HTML page directly from postgrest. So, I created a postgresql function that returns text and sets `Content-Type` header to `text/html` like this:

```
CREATE OR REPLACE FUNCTION todo.homepage() RETURNS varchar AS $$
BEGIN
  PERFORM set_config('response.headers','[{"Content-Type": "text/html"}]', true);
  RETURN '<html><body>Hello</body></html>';
END;
$$ LANGUAGE plpgsql IMMUTABLE;
```
And then I expected, the HTML to be returned at `/rpc/homepage`:

```
$ curl -v http://localhost:3000/rpc/homepage
*   Trying ::1:3000...
* connect to ::1 port 3000 failed: Connection refused
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /rpc/homepage HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.77.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Date: Mon, 24 Jan 2022 23:46:47 GMT
< Server: postgrest/9.0.0
< Content-Range: 0-0/*
< Content-Type: text/html
< 
* Connection #0 to host localhost left intact
"<html><body>Hello</body></html>"%
```

As you can see, the function's returned value was string which was converted to JSON and hence it includes double-quotes. This was not expected, as I head set the content-type to be `text/html` instead of `application/json`.

Another unexpected behavior was the trailing `%` in the response body. 

Possibly related issues:
- #1548 
- #1582 
- #136

### What am I trying to achieve and what are my constraints:

I'm trying to ship an on-premise webapp with SQL+JS stack. Essentially, we will give users an SQL script to run which defines the models and functions, postgREST would both provide CRUD apis  as well as serve the base HTML page. The page would then load JS/CSS files from CDN which are published and maintained by developers.

### Workaround

@laurenceisla [suggested in Gitter chat](https://gitter.im/begriffs/postgrest?at=61ef3aaed143b14f83334e5f) that I inject an `Accept: text/plain` header using nginx rewrite rules like this:

```
location ~ ^/html/(.*) {
    proxy_set_header Accept 'text/plain';
    proxy_pass http://localhost:3000/rpc/$1;
}
```
And then `http://localhost/html/homepage` should return the HTML ready for browser's consumption.

But IMHO, it still seems wrong for postgrest to force a conversion to JSON when the function explicitly sets a content-type as non-JSON.

**Comment by wolfgangwalther** [comment]
You might want to look into the `raw-media-types` config option: https://postgrest.org/en/stable/configuration.html#raw-media-types.

You should be able to set it to `raw-media-types="text/html"` to achieve this.

This is even covered in a test-case:

https://github.com/PostgREST/postgrest/blob/c7cadcd7761f5cffd7902782382bac748f30a061/test/spec/Feature/HtmlRawOutputSpec.hs#L14-L30

**Comment by nileshtrivedi** [comment]
@wolfgangwalther This is perfect! Thank you.
