### ISSUE TITLE
Docker ARM releases are not consistent

### ISSUE THREAD

**Issue by kyle-johnson** [PostgREST/postgrest#2143]
https://hub.docker.com/r/postgrest/postgrest/tags

Not all releases include ARM builds:
- v9.0.0.20220130 amd64
- v9.0.0.20220107 amd64 *and arm*
- v9.0.0.20211220 amd64
- v9.0.0 amd64 *and arm*

The arm builds are also ~100mb vs the amd64 which are ~4mb which I suspect hints that they are built differently? I'm happy to help contribute here if pointed in the right direction.

**Comment by steve-chavez** [comment]
Yes, this is because the ARM builds have been manual until now and not built with Nix(which makes the amd64 images minimal).

Related:

- https://github.com/PostgREST/postgrest/issues/2010
- https://github.com/PostgREST/postgrest/pull/2127 (draft that should automate ARM builds)

**Comment by wolfgangwalther** [comment]
As we are tracking this in those other issues, I'll close this here.
