### ISSUE TITLE
Docker hub broken repo link

### ISSUE THREAD

**Issue by osaxma** [PostgREST/postgrest#2148]
The link highlighted below is broken. 

<img width="828" alt="Screen Shot 2022-02-04 at 1 51 18 AM" src="https://user-images.githubusercontent.com/46427323/152442525-71000fb1-24a7-4bd2-a4dd-5ec405ada8fd.png">

**Comment by wolfgangwalther** [comment]
Pushed a fix for it, thanks for reporting!

**Comment by wolfgangwalther** [comment]
I forgot we have currently disabled updating the docker hub description in CI:

https://github.com/PostgREST/postgrest/blob/9ca9a54d21e68c8c1b8e922d773903ddebb59e26/.github/workflows/ci.yaml#L379-L390

@steve-chavez could you update it manually with the content of https://github.com/PostgREST/postgrest/blob/main/nix/tools/release/docker-hub-full-description.md? I lack permissions to do so.

**Comment by steve-chavez** [comment]
> could you update it manually with the content of https://github.com/PostgREST/postgrest/blob/main/nix/tools/release/docker-hub-full-description.md? I

Done :heavy_check_mark:
