### ISSUE TITLE
`max-rows` affects bulk insert

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#2155]
If `max-rows=1000`, [bulk inserting](https://postgrest.org/en/stable/api.html#bulk-insert) 1500 rows with `Prefer: return=representation` will only return 1000 rows, which is misleading.

I think the correct behavior should be ignoring `max-rows` for POST, maybe for PATCH/DELETE as well.

**Edit 1**: Should POST, PATCH and DELETE have their own `max-rows` as a way to limit inserted, updated and deleted rows?

**Edit 2**: We could have a `max-rows-read` and `max-rows-mutated`.

**Comment by steve-chavez** [comment]
Yes. Let's use this issue to disallow `?limit/offset` on POST/PATCH/DELETe as we agreed on https://github.com/PostgREST/postgrest/issues/2156#issuecomment-1034004013.

**Comment by aranibatta** [comment]
This a trip

Ron Bhattacharyay
EECS UC Berkeley Regent's and Chancellor's Scholar '18
***@***.*** | 3104916828

**Comment by wolfgangwalther** [comment]
> Yes. Let's use this issue to disallow `?limit/offset` on POST/PATCH/DELETe as we agreed on [#2156 (comment)](https://github.com/PostgREST/postgrest/issues/2156#issuecomment-1034004013).

Does that still include the following?

> I think the correct behavior should be ignoring `max-rows` for POST, maybe for PATCH/DELETE as well.

So the suggestion would be to apply both `db-max-rows` (server-side limit) and `?limit`+`Range` headers (client-side limit) **only** to `GET` requests, correct?

**Comment by steve-chavez** [comment]
> So the suggestion would be to apply both db-max-rows (server-side limit) and ?limit+Range headers (client-side limit) only to GET requests, correct?
> Does that mean that db-max-rows is essentially an upper limit on ?limit? So kind of a db-max-limit in that sense?

Yes, yes and yes. Though `db-max-limit` doesn't really convey that it is the maximum number of rows returned.

**Comment by steve-chavez** [comment]
Will just not apply `max-rows` to POST/PATCH/DELETE to solve this. Users haven't asked for a `max-mutations` config so that's still not needed.
