### ISSUE TITLE
Allow configuration name of Authorization Header

### ISSUE THREAD

**Issue by PranavSathy** [PostgREST/postgrest#2159]
### Environment

* PostgreSQL version: PostgreSQL 13
* PostgREST version: postgrest/postgrest:latest (digest: `sha256:67de565f0ad9ef7f1558734fd39d335d69a4fcfe36de86deda658f21069a9872`)
* Operating system: GCP Cloud Run (`linux/amd64`)

### Description of issue

So we leverage `Authorization: Bearer <token>` headers in our HTTP(s) communication between services deployed on GCP's `Cloud Run` (serverless compute). This allows all of our services to communicate with each other securely and we know that they are authorized to invoke HTTP endpoints within our ecosystem (not malicious traffic over the internet). Unfortunately; these are the exact same headers leveraged by PostgREST to authenticate "trusted users", which results in our HTTP API calls returning `JWSError JWSInvalidSignature` errors for all API calls.

(Expected behavior vs actual behavior)

Would it be possible to allow end users to "configure" which header is read as part of trusted user verification. I presume it's a rather obscure (probably a bad?) design need, but this is making it impossible (AFAICT) to leverage GCP's built in inter-service authorization headers while deploying PostgREST to our production services set.

(Steps to reproduce: Include a minimal SQL definition plus how you make the request to PostgREST and the response body)

1. Ensure `gcloud` CLI is installed and configured along with a GCP project.
2. Provision a PostgreSQL v13 database on Cloud SQL.
3. Deploy PostgREST (using `linux/amd64` image) to Cloud Run.
4. Configure the Cloud Run service to connect to Cloud SQL, and connect to the database. It should have an `ingress` setting of `all`, with an `Authentication` setting of `Require Authentication`.
5. Run the following command:

```
curl -v https://<cloud-run-instance-url>/<table> --header "Authorization: Bearer $(gcloud auth print-identity-token <my-service-account>@<project-id>.iam.gserviceaccount.com --audiences=https://<cloud-run-instance-url>)"
```

**Comment by steve-chavez** [comment]
Seems it's possible to add multiple JWTs in the Authorization header([SO link](https://stackoverflow.com/a/38515091/4692662)), like:

> Authorization: Bearer mF_9.B5f-4.1JqM, Basic YXNkZnNhZGZzYWRmOlZLdDVOMVhk

With that, maybe we can catch the postgrest JWT based on the "aud" claim?

WDYT? Would GCP work with that? 

Related:

- https://github.com/PostgREST/postgrest/issues/773 (passing the JWT in the Cookie header)

**Comment by PranavSathy** [comment]
Thanks for the quick response here! So the other half of this issue is that (as this is not a production use case) I wanted to simply NOT have a trusted user in my PostgREST instance, but rather simply rely on GCP's inbuilt authentication/authorization to ensure that communication to my application were from a legitimate source. 

Hence, just the existence of the token is causing issues.

**Comment by wolfgangwalther** [comment]
> So we leverage Authorization: Bearer <token> headers in our HTTP(s) communication between services deployed on GCP's Cloud Run (serverless compute).

Could you use the [`Proxy-Authorization`](https://datatracker.ietf.org/doc/html/rfc7235#section-4.4) instead of the `Authorization` headers for that?

> So the other half of this issue is that (as this is not a production use case) I wanted to simply NOT have a trusted user in my PostgREST instance, but rather simply rely on GCP's inbuilt authentication/authorization to ensure that communication to my application were from a legitimate source.

Could you add nginx as a reverse proxy right before your postgrest instance to remove the authorization header?

---

All those seem hacky, though. I think you should just **use** the token you get.

You can add asymmetric keys as `jwt-secret` - so just using the public key should be enough for verification.

And you can set `jwt-role-claim-key` to extract the role from the token.

And then you set up a postgres role for each service that can access the postgrest instance. They can all inherit the same underlying role at first - until you need different privileges.

**Comment by PranavSathy** [comment]
@wolfgangwalther ; thanks for the thoughts here:

1. `Proxy-Authorization` is unfortunately not honored by the "inbuilt" Cloud Run authorization (which seems like a bug in GCP to me). Fortunately, it is honored by Cloud IAP though.
2. Absolutely, `nginx` seems like an alternate here that would give us versatility moving forward.

I actually managed to get this working Google Cloud IAP; the structure is as follows:

1. A PostgREST deployment via Cloud Run , with the `ingress` setting to `Internal and Load Balanced`, `Authorization` to `allUsers`.
2. A GCP Load Balancer w/ Serverless Network-Endpoint-Group over the Cloud Run Instance w/ HTTP & HTTPS. Caveat here is that I had to register the IP of the load balancer against my DNS config w/ a subdomain (A record) to ensure the SSL cert went active (Google Managed SSL).
3. Now, my internal services can simply communicate with PostgREST w/ no authn required. External communication can now leverage IAP "Programmatic Access" to mint a JWT that IAP recognizes and consumes (it doesn't relay the `Authorization` header.

**Comment by CharlesWinter** [comment]
Hello! I'm facing exactly the same issue as OP unforuntately, I want to run postgrest in cloud run. It's configured via cloudrun to only accept internal traffic from our VPC, and I'm using the google cloud IAM policies to decide who gets to call postgrest. It's a pretty standard pattern, and just as I don't check auth headers in the code I deploy to cloud run, I don't want to postgrest to check the auth header either! 

Is there any hack at all I can use to get postgrest to ignore the Authentication header? I don't want to setup all the infrastructure that OP has done for such a simple service. Some ideas I've had.

- have the anonymous role be the actual role I'll use to make the queries and rely on postgrest falling back to it on failed authentication? This didn't work as postgrest always balked with "JWSInvalidSignature"
- add a custom trigger function in postgrest to override the JWT validation and always return true. 

I'd really appreciate any help on the matter with this. Thanks!
