### ISSUE TITLE
JSONB column should not have type "string" but "{}"

### ISSUE THREAD

**Issue by Brunni** [PostgREST/postgrest#2165]
Issue:
I have a table with a jsonb column and I would expect the swagger editor to work correctly and allow sending a nested json object of any kind.

To reproduce:
Create a table with jsonb column, e.g.
```
create table sample (
                        id serial primary key,
                        data jsonb,
                        insertDate timestamptz
);
```

The swagger editor provides a sample data like this for the POST endpoint:
```
{
  "id": 0,
  "data": "string",
  "insertdate": "string"
}
```
Changing it to something like this, makes the swagger editor not send the request anymore:
```
{
  "data": {"a":"1"},
  "insertdate": "2022-02-07T13:49:51.141+00:00"
}
```

When I change the type of data from
```
  data:
        format: jsonb
        type: string
```
to
```
  data:
        format: jsonb
        type: {}
```

everything works fine!

**Comment by wolfgangwalther** [comment]
Adding `type: string` to a json/jsonb column which can take anything doesn't really make sense. I found this: https://github.com/OAI/OpenAPI-Specification/issues/1388#issuecomment-339061316. So basically, we should just omit `type:` for those columns completely.
