### ISSUE TITLE
Notify cache invalidation not working, doubt 

### ISSUE THREAD

**Issue by yevon** [PostgREST/postgrest#2167]
Does the pgsql notify method work if postgREST is installed in one docker, and postgres db in another docker? Or in kubernetes in different nodes? I tried both and it didn't work. Is dbchannel enabled by default isn't it? Thanks!

**Comment by steve-chavez** [comment]
> Is dbchannel enabled by default isn't it?
> Does the pgsql notify method work if postgREST is installed in one docker, and postgres db in another docker?

Yes and yes, it should. If you can get a successful response from an endpoint(`GET /tbl`), then NOTIFY should work as well.
>  I tried both and it didn't work.

Did you check the postgrest logs when doing the NOTIFY? What did you get?

**Comment by yevon** [comment]
What I see is following logs from the postgrest schema:

![image](https://user-images.githubusercontent.com/121157/154554306-7dcb897b-ed8b-4c14-86e4-1e3e9b9e3b61.png)

And executing the command notify always seems to be succesful, but the schema is not reloaded:

![image](https://user-images.githubusercontent.com/121157/154554473-481b4ddc-7d1d-4940-8519-adb972d597cb.png)

How can I really check that the dbchannel is enabled and listening for events?

Thanks!

**Comment by yevon** [comment]
Solved, I had set up the openApiServerProxyUri and the dbChannel values. I just set them empty as default and is now working. Thanks!
