### ISSUE TITLE
Calling functions with parameter types declared in a protected schema returns permission error in PostgREST, while it does not in PSQL

### ISSUE THREAD

**Issue by laurenceisla** [PostgREST/postgrest#2169]
### Environment

* PostgreSQL version: v13.5
* PostgREST version: v9.0.0
* Operating system: EndeavourOS

### Description of issue

From a [conversation in Gitter](https://gitter.im/begriffs/postgrest?at=620c236fced11857f9b0b399), we found out that declaring a function with a parameter that has a type from a protected schema (where no usage was granted to the anonymous user) can be called in PSQL by the impersonated anonymous user without giving any permission error. 

This behavior does not replicate for PostgREST though. Calling the same function from PostgREST will return an error with the message: `permission denied for schema <schema>`; this is because the parameter is explicitly cast to the type declared in the protected schema. Here's the line of code:

https://github.com/PostgREST/postgrest/blob/dcf7ade5bc70a31fe0e083e1527b74125a94aeda/src/PostgREST/Query/QueryBuilder.hs#L143

And here's a snippet to reproduce it:

```sql
create schema api;
create schema private;
create role web_anon nologin;
grant usage on schema api to web_anon; -- note that web_anon doesn't have usage on the private schema
--
create type private.thing as enum('a','b','c');
create or replace function
  api.checkallowed(t private.thing) returns text as $$
begin
  return (select t);
end;
$$ language plpgsql;
--
select api.checkallowed('a'); -- works
begin;
set local role web_anon;
select api.checkallowed('b'); -- I expected it not to work for web_anon, but it does
end;
--
select 'a'::private.thing as thing; -- works
begin;
set local role web_anon;
select 'a'::private.thing as thing; -- as expected, it does not work (PostgREST does a similar casting when building the query, thus giving the error)
-- ERROR:  permission denied for schema private
-- LINE 1: select 'a'::private.thing as thing;
end;
```

Using PostgREST:

```bash
curl "http://localhost:3000/rpc/checkallowed?t=a"
```
```json
{
    "hint": null,
    "details": null,
    "code": "42501",
    "message": "permission denied for schema private"
}
```

-----

Although I'm reporting this as an issue, I'm not sure if PostgREST should reflect the same behavior as PostgreSQL in this case.

**Comment by steve-chavez** [comment]
A domain alias can be used as a workaround for this one: https://stackoverflow.com/questions/72218800/is-it-possible-to-copy-an-enum-type-from-one-schema-to-another
