### ISSUE TITLE
Postgrest 7.0.1 stops responding after Cannot decode byte '\xc1': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream Error

### ISSUE THREAD

**Issue by devesh23** [PostgREST/postgrest#2198]
- Database schema has not changed
### Environment

* PostgreSQL version: (if using docker, specify the image): 10
* PostgREST version: (if using docker, specify the image): 7.0.1
* Operating system: Linux

### Description of issue
Upon sending multiple curl calls to postgrest for querying a table using the below mentioned query, postgrest stops responding after 10-15 responses with error `Cannot decode byte '\xc1': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream Error`

`/customer?select=customer_uuid%2c%20time_spentcabpjmjpzt%c1%81e6fmxezn6a&order_uuid=in.%282c1f15f8-64b3-4805-93ad-9d74b448d487%2C588d6479-016f-4563-9401-678b821e16e7%29&order=time_spent.desc&limit=5`

Additional Information: 
Postgrest is started as a standalone process using the postgrest binary inside a docker container.

This issue does not occur in postgrest 8.0.0. We use postgrest docker container for 8.0.0 version.

**Comment by steve-chavez** [comment]
Hm, this was already discussed/solved [here](https://github.com/PostgREST/postgrest/issues/1585) and released on v8.0.0.

> This issue does not occur in postgrest 8.0.0. We use postgrest docker container for 8.0.0 version.

If you already upgraded, then what's the issue? :thinking:

**Comment by devesh23** [comment]
We use postgrest 7.0.1 in older version of our product which is currently being tested for security concerns by one of our clients. Unfortunately, We cannot deploy the newer version of our product as that would cause the entire testing cycle to start from scratch. 

#1585 resolves the error but the problem that this issue raises is that postgrest stops responding after 10-15 calls that cause encoding error thus leading the user to assume that postgrest has stopped working.

**Comment by steve-chavez** [comment]
> postgrest stops responding after 10-15 calls that cause encoding error thus leading the user to assume that postgrest has stopped working

Yeah that wasn't reported before, I guess the fix already solves it though.

> Unfortunately, We cannot deploy the newer version of our product as that would cause the entire testing cycle to start from scratch.

Hm, sounds like you're in need of **backporting** but that's not something we currently do.

@wolfgangwalther Might have more thoughts on this one.

**Comment by wolfgangwalther** [comment]
Yeah, I agree. We don't have the resources to backpatch stuff.
