### ISSUE TITLE
Schema Cache - seems to be some type of limit on # of functions

### ISSUE THREAD

**Issue by NickEmpetvee** [PostgREST/postgrest#2210]
* PostgreSQL version: 11.15.1
* PostgREST version: 9
* Operating system: Windows 10

### Description of issue

**Expected Behavior:** When adding a function to the PostgREST schema, it is loaded into the schema cache by restarting PostgREST.

**Actual Behavior:** I successfully added several functions to schema cache in the expected way. Now however I can't add any more. The previous ones still work but the new ones don't. Error from Postman: `If a new function was created in the database with this name and parameters, try reloading the schema cache. error`.

If I query the PostgREST root (e.g. `http://localhost:3002/`), the function (`test_function_1`) is in the returned JSON:

```
"/rpc/test_function_1": {
...
}
```

I've rebooted the machine and restarted PostgREST multiple time and still get this. I'm on version 9. Thanks in advance!

### Function:

```
CREATE OR REPLACE FUNCTION api.test_function_1(supplied_user_id INTEGER)
    RETURNS boolean
    LANGUAGE 'sql'
    COST 100
    VOLATILE SECURITY DEFINER PARALLEL UNSAFE
AS $BODY$
	SELECT u.user_id, u.user_name
	FROM basic_auth.users u
	WHERE u.user_id = supplied_user_id 
	AND NOT u.disabled;
$BODY$;

ALTER FUNCTION api.at_least_two_admin_users()
    OWNER TO provisioner;

```
Postman - GET call

**Comment by wolfgangwalther** [comment]
Please add the exact http request you're making.

**Comment by wolfgangwalther** [comment]
The functions in those requests are not the same as in your SQL snippet. The request descriptions misses headers and method (POST, GET, ...). It would be best to include a raw copy of the request.

---

> `URL: localhost:14300/rpc/test_clone_of_login`

> PostgREST root (e.g. http://localhost:3002/)

Are you sure you are looking at the same postgrest instance in both cases? The ports differ.
