### ISSUE TITLE
Unable to disambiguate in presence of a view when column name is equal to table name

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#2238]
### Problem

Having:

```sql
CREATE TABLE series (
    id bigint PRIMARY KEY,
    title text NOT NULL
);

CREATE TABLE adaptation_notifications (
    id bigint PRIMARY KEY,
    series bigint REFERENCES series(id),
    status text
);

CREATE VIEW series_popularity AS
SELECT id, random() AS popularity_score
FROM series;
```

It's impossible to get the `series` table from `adaptation_notifications`:

```http
GET /adaptation_notifications?select=id,status,series(*)

300 Multiple Choices
```

```json
{
    "code": "PGRST201",
    "details": [
        {
            "cardinality": "many-to-one",
            "embedding": "adaptation_notifications with series",
            "relationship": "adaptation_notifications_series_fkey[series][id]"
        },
        {
            "cardinality": "many-to-one",
            "embedding": "adaptation_notifications with series_popularity",
            "relationship": "adaptation_notifications_series_fkey[series][id]"
        }
    ],
    "hint": "Try changing 'series' to one of the following: 'series!adaptation_notifications_series_fkey', 'series_popularity!adaptation_notifications_series_fkey'. Find the desired relationship in the 'details' key.",
    "message": "Could not embed because more than one relationship was found for 'adaptation_notifications' and 'series'"
}
```

Doing the following will result in the same error message:

```http
GET /adaptation_notifications?select=id,status,series!adaptation_notifications_series_fkey(*)
GET /adaptation_notifications?select=id,status,series!series(*)

300 Multiple Choices
```

The view can be obtained though:

```http
GET /adaptation_notifications?select=id,status,series_popularity(*)

200 OK
```

If the `series` column is renamed, then the embedding can be resolved:

```sql
ALTER TABLE adaptation_notifications RENAME COLUMN series TO target_series;
```

```http
GET /adaptation_notifications?select=id,status,series(*)

200 OK
```

**Comment by steve-chavez** [comment]
I think the solution here is to be explicit about embedding views and not auto-detect them when using a column or fk:

```bash
## will only embed tables
/tbl?select=col(*)
/tbl?select=fk(*)

## will embed views
/tbl?select=view(*)

## views can still use hints in case there's more than one way to embed on them
/tbl?select=view!fk(*)
```

Otherwise we're too likely to break APIs when adding views, I think this is the right way. This would also solve https://github.com/PostgREST/postgrest/issues/1643.

There might be APIs relying on this behavior, to let them upgrade we could add a config like:

```ini
embedding-detection=columns-follow-views
```

That would also go in line with the other idea about restricting m2m embeds to strict junctions, we can add an option to the same config for backcompat.

**Comment by wolfgangwalther** [comment]
Interesting. I hit the same bug a few weeks ago, but didn't find the time to report it, yet.

> I think the solution here is to be explicit about embedding views and not auto-detect them when using a column or fk:
> 
> ```shell
> ## will only embed tables
> /tbl?select=col(*)
> /tbl?select=fk(*)
> 
> ## will embed views
> /tbl?select=view(*)
> ```

Wait.. how is this going to solve the problem at hand here?

Suppose you only have `tbl` with `col`. The first request will work fine. Now you add a view named `col`. The same query will not work anymore. Isn't this exactly what we're trying to prevent?

I think the solution should be something like:
Only allow table/view names as the embedding **target**. No more columns or FKs for that. Allow only column names, FKs or strict M2M junctions as **hints**. No more regular table/view names.

This will be breaking. But it would simplify a lot and reduce the number of potential collisions.

**Comment by wolfgangwalther** [comment]
Additionally, we can think about never embedding a strict m2m junction without hint. So given `A <-> J <-> B`, we would only allow `/A?select=B!J(*)`, but not `/A?select=B(*)`. This would further reduce the likeliness of breaking existing queries when introducing a new view / junction.

**Comment by steve-chavez** [comment]
> Only allow table/view names as the embedding target. No more columns or FKs for that. Allow only column names, FKs or strict M2M junctions as hints. No more regular table/view names.

I would have definitely liked that if we were designing resource embedding from scratch.

However, I've seen many users doing the column-as-target to disambiguate between two FKs to the same table([also our example in the docs](https://postgrest.org/en/stable/api.html#target-disambiguation)). I've noticed that this somehow comes "natural" for users. So I think we should keep column-as-target, otherwise it would be too breaking and without a way out(later on, https://github.com/PostgREST/postgrest/issues/2144 could help)

> Additionally, we can think about never embedding a strict m2m junction without hint.

I believe https://github.com/PostgREST/postgrest/pull/2262 will drastically reduce collision for m2ms(the numbers on the PR also back that up). I'm considering that a bug fix(without a config for turning it off) since the combinatorial explosion from generated m2m is just bad for every project.

> Suppose you only have tbl with col. The first request will work fine. Now you add a view named col. The same query will not 
work anymore. Isn't this exactly what we're trying to prevent?

Yes, that's true. My thinking was just to reduce the possibility of collision. That being said, if you add a view named col, changing the view's name to resolve the embedding is not a hard change compared to ALTERing a table column name - recommending the former to the users would be somewhat fine while the latter is unnaceptable.

**Comment by steve-chavez** [comment]
> I think the solution here is to be explicit about embedding views and not auto-detect them when using a column or fk:
> 
> ```shell
> ## will only embed tables
> /tbl?select=col(*)
> /tbl?select=fk(*)
> 
> ## will embed views
> /tbl?select=view(*)
> ```

This proposal would likely break the projects that followed [schema isolation](https://postgrest.org/en/stable/schema_structure.html#schema-isolation) down to a T.

A less disruptive solution to the issue might be just considering the "inferred relationships on views" being 2nd class when in presence of "table relationships". So if we detect 3 relationships and two of them are on views then the table relationship will prevail and be picked. If all 3 relationships are on views then we'd raise the usual error.

**Comment by steve-chavez** [comment]
>A less disruptive solution to the issue might be just considering the "inferred relationships on views" being 2nd class when in presence of "table relationships"

On second thought, I don't like this one. It makes the `findRel` logic more complicated and also harder to make the operation fast - currently the relationships detected are a [big search space](https://github.com/PostgREST/postgrest/pull/2262#issuecomment-1107360058). It'd be better to just stop detecting views on column-as-target and introduce a new legacy config for users that want to keep the previous logic.

**Comment by steve-chavez** [comment]
> Only allow table/view names as the embedding target. No more columns or FKs for that. Allow only column names, FKs or strict M2M junctions as hints. No more regular table/view name

I've just noted that the above will be possible whenever the **hint** form is used given that the col-as-target for views is removed.

This is because the disambiguation documented here will no longer be necessary https://postgrest.org/en/latest/api.html#hint-disambiguation

**Comment by wolfgangwalther** [comment]
> However, I've seen many users doing the column-as-target to disambiguate between two FKs to the same table([also our example in the docs](https://postgrest.org/en/stable/api.html#target-disambiguation)). I've noticed that this somehow comes "natural" for users. So I think we should keep column-as-target, otherwise it would be too breaking and without a way out(later on, #2144 could help)

Maybe we can allow "column name as the embedding target" **only** for this very special case of self-embedding, to avoid a breakage with no way out - and otherwise do as mentioned in https://github.com/PostgREST/postgrest/issues/2238#issuecomment-1094611081?

**Comment by steve-chavez** [comment]
> Disambiguating between two FKs to the same table can be done by using the FK names, no?

Yes, but I guess most users prefer to just use the column name. Changing the name of the FK to make it readable is one step more.
