### ISSUE TITLE
Unable to read jwt parameters / setup help

### ISSUE THREAD

**Issue by yevon** [PostgREST/postgrest#2240]
I've followed the guide for applying security and row level security, and I have got everything working but I'm unable to read the jwt atributes:
My jwt is:

```
{
  "role": "rolename",
  "username": "username",
  "code": "usercode",
  "exp": 1649458757
}
```

If I do:
current_setting('request.jwt.claim.code', true)

It is unable to find it:

```
{
  "hint": null,
  "details": null,
  "code": "42704",
  "message": "unrecognized configuration parameter \"request.jwt.claim.code\""
}
```

 Does postgrest fill this value? How can I change the request.jwt.claim path in the install settings? I think I have something wrong with my install settings.

**Comment by steve-chavez** [comment]
Which PostgREST version are you using? If it's v9.0, then you need to use the setting differently:

```sql
SELECT current_setting('request.jwt.claims', true)::json->>'code';
```

See: https://postgrest.org/en/stable/api.html#accessing-request-headers-cookies-and-jwt-claims

**Comment by yevon** [comment]
Yes it is 9.0, then I was reading something outdated, I will give it a try tomorrow and comment results! I will try to find out where I found the outdated info in the docs. Thanks!

**Comment by yevon** [comment]
I tried it as suggested by still not working, if I use:

SELECT current_setting('request.jwt.claims', true)::json->>'code';

It doesn't matter if I put true or false or changing the name of the parameter, it is always returning null to me.

**Comment by steve-chavez** [comment]
I forgot, you need to check your PostgreSQL version as well. This new access style is only applied for PG >= 14 by default, see https://postgrest.org/en/stable/configuration.html#db-use-legacy-gucs

**Comment by yevon** [comment]
I said nothing, now is working thanks! It seems that Thunder client in vscode was caching a prior token. Is there a limit for the jwt Secret lenght? Minimum 32 chars

**Comment by steve-chavez** [comment]
> Is there a limit for the jwt Secret lenght? Minimum 32 chars

No, only the min length. See https://postgrest.org/en/stable/configuration.html#jwt-secret

**Comment by yevon** [comment]
Thanks!
