### ISSUE TITLE
How to use the Postgres comparison with row()

### ISSUE THREAD

**Issue by bpasserat** [PostgREST/postgrest#2276]
### Environment

* PostgreSQL version: 13.0
* PostgREST version: 7.0
* Operating system: Linux

### Description of issue

For performance reason I am trying to remove requests with offset and use the seek method based on where clause on multiple columns. 

To do so, I would like to use the the postgresql row() function to compare rows. How could I use it within postgrest ?

As an example I would like to implement the following request 

```
select 
   t.id,
   t.name,
   t.created_at
from table t 
where
    row(t.created_at,t.name) > row('2022-05-03','Test')
order by
   t.created_at desc,
   t.name desc
limit 10;
```

**Comment by steve-chavez** [comment]
Ah, keyset pagination was discussed before: https://github.com/PostgREST/postgrest/issues/1431. There's no support for doing it directly currently - but you could use a function for this.

---

Was going to suggest a computed column but that doesn't work unfortunately:

```sql
CREATE FUNCTION test.blo(test.projects) RETURNS RECORD
    LANGUAGE sql IMMUTABLE
    AS $$ SELECT (id,name) FROM test.projects; $$;
```

```sql
postgres=# select t.blo from test.projects t where t.blo = '(1,sdf)';
ERROR:  input of anonymous composite types is not implemented
```

```bash
curl 'localhost:3000/projects?select=blo&blo=eq.(3,adsf)'
{"hint":null,"details":null,"code":"0A000","message":"input of anonymous composite types is not implemented"}
```

**Comment by bpasserat** [comment]
@steve-chavez Thanks for your great answer and your links 

From my understanding it will not be done soon, with #1431 I have the answer on how to do it.

You can close this issue if you want !
