### ISSUE TITLE
Worse throughput when having more than 16 cores

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#2294]
PostgREST throughput scales on the [AWS m5a series](https://aws.amazon.com/ec2/instance-types/m5/), up until the `m5a.4x.large`(16 vCPUs). From there on, the `m5a.8xlarge`(32 vCPUs) and `m5a.16xlarge`(48 vCPUs) give worse throughput.

The numbers can be seen on https://github.com/supabase/benchmarks/pull/34, which shows a comparison between:

- `k6` RPS: on a different machine than postgREST and postgreSQL. 
- `pgbench` TPS: on a different machine than postgreSQL. Using the same query as the one generated by postgREST on the k6 load test.

It's proven that `pgbench` TPS does scale with the bigger `m5a` instances, while `k6` RPS is worse.

**Comment by steve-chavez** [comment]
My first suspicion is the hasql Pool, which uses [resource-pool](https://hackage.haskell.org/package/resource-pool) with a [single stripe](https://github.com/nikita-volkov/hasql-pool/blob/master/library/Hasql/Pool.hs#L51-L52) . According to https://github.com/bos/pool/issues/38, this will give bad performance. Also the [resource-pool docs](https://hackage.haskell.org/package/resource-pool-0.2.3.2/docs/Data-Pool.html) mention that:

> "Striped" means that a single [Pool](https://hackage.haskell.org/package/resource-pool-0.2.3.2/docs/Data-Pool.html#t:Pool) consists of several sub-pools, each managed independently. A single stripe is fine for many applications, and probably what you should choose by default. More stripes will lead to reduced contention in high-performance multicore applications, at a trade-off of causing the maximum number of simultaneous resources in use to grow.

According to the discussion on https://github.com/bos/pool/issues/39, the [scrive/pool fork](https://github.com/scrive/pool) solves this issue. Looking at its source code, it does seem to calculate the [number of stripes automatically](https://github.com/scrive/pool/blob/b0cfae3591106e93752a8712a8ec8bc397dba820/Data/Pool/Internal.hs#L83) - based on [getNumCapabilities](https://hackage.haskell.org/package/base-4.16.1.0/docs/GHC-Conc.html#v:getNumCapabilities)(numbers of threads that can run, based on the number of cores).

**Comment by steve-chavez** [comment]
[Using scrive/pool](https://github.com/steve-chavez/postgrest/tree/scrive-pool) does improve things a bit as shown on  https://github.com/supabase/benchmarks/pull/34#issuecomment-1138174912, the `m5a.8xlarge`(32 cores) gets better numbers(modest improvement though) but the throughput still falls down on `m5a.12xlarge` and `m5a.16xlarge`.

At this point, I'll try using an external pooler such as pgbouncer to see if it improves things.

(pgbouncer might have low throughput as mentioned in this [so question](https://stackoverflow.com/questions/63877991/pgbouncer-performance-drops-when-connection-count-increases/63878139#63878139), so I'll also look at other alternatives like odissey)

**Comment by dwagin** [comment]
it is possible to run multiple instances of pgbouncer with the so_reuseport option

**Comment by steve-chavez** [comment]
Thanks for the hint @dwagin. I didn't know pgbouncer was single thread:

> (PgBouncer is single-threaded and uses one CPU core per instance.)

From https://www.pgbouncer.org/config.html#so_reuseport.

**Comment by steve-chavez** [comment]
So with a patched postgrest that uses a direct connection instead of the pool(https://github.com/steve-chavez/postgrest/commit/05d1ea0cf01f13abe76ff9ad740d0fa673782545), I've tried a setup with:

- A 2 core pg instance(t3a.nano, with 2 pgbouncer instances + pg)
- A 2 core postgREST instance(t3a.nano)
- A client machine for the bench tests

And unfortunately I get like a third of the RPS of what I get using the postgrest pool:

<details>
 <summary>800.676889/s for 2 pgbouncers</summary>
<pre>
    data_received..............: 7.6 MB 251 kB/s
    data_sent..................: 2.5 MB 82 kB/s
  ✓ failed requests............: 0.00%  ✓ 0    ✗ 24065
    http_req_blocked...........: avg=4.6µs   min=980ns   med=1.64µs  max=977.32µs p(90)=2.16µs  p(95)=2.6µs
    http_req_connecting........: avg=2.2µs   min=0s      med=0s      max=560.34µs p(90)=0s      p(95)=0s
  ✓ http_req_duration..........: avg=12.4ms  min=2.7ms   med=9.9ms   max=73.99ms  p(90)=23.61ms p(95)=28.51ms
    http_req_receiving.........: avg=36.52µs min=14.19µs med=35.28µs max=899.71µs p(90)=43.92µs p(95)=50.58µs
    http_req_sending...........: avg=9.37µs  min=6.04µs  med=8.23µs  max=416.24µs p(90)=10.49µs p(95)=12.5µs
    http_req_tls_handshaking...: avg=0s      min=0s      med=0s      max=0s       p(90)=0s      p(95)=0s
    http_req_waiting...........: avg=12.35ms min=2.64ms  med=9.86ms  max=73.95ms  p(90)=23.56ms p(95)=28.47ms
    http_reqs..................: 24065  800.676889/s
    iteration_duration.........: avg=12.46ms min=2.76ms  med=9.96ms  max=74.04ms  p(90)=23.68ms p(95)=28.58ms
    iterations.................: 24065  800.676889/s
    vus........................: 10     min=10 max=10
    vus_max....................: 10     min=10 max=10
</pre>
</details>

<details>
 <summary>2643.760356/s for postgREST pool</summary>
<pre>
    data_received..............: 25 MB  830 kB/s
    data_sent..................: 8.2 MB 271 kB/s
  ✓ failed requests............: 0.00%  ✓ 0    ✗ 79437
    http_req_blocked...........: avg=4.42µs  min=1µs     med=1.64µs  max=733.23µs p(90)=2.28µs  p(95)=2.78µs
    http_req_connecting........: avg=2.12µs  min=0s      med=0s      max=491.13µs p(90)=0s      p(95)=0s
  ✓ http_req_duration..........: avg=3.71ms  min=1.26ms  med=3.36ms  max=34.64ms  p(90)=5.68ms  p(95)=6.67ms
    http_req_receiving.........: avg=35.64µs min=12.69µs med=35.02µs max=2.68ms   p(90)=44.45µs p(95)=50.61µs
    http_req_sending...........: avg=9.77µs  min=5.62µs  med=8.33µs  max=4.69ms   p(90)=11.3µs  p(95)=13.52µs
    http_req_tls_handshaking...: avg=0s      min=0s      med=0s      max=0s       p(90)=0s      p(95)=0s
    http_req_waiting...........: avg=3.66ms  min=1.21ms  med=3.31ms  max=34.5ms   p(90)=5.63ms  p(95)=6.62ms
    http_reqs..................: 79437  2643.760356/s
    iteration_duration.........: avg=3.77ms  min=1.33ms  med=3.42ms  max=35.49ms  p(90)=5.75ms  p(95)=6.73ms
    iterations.................: 79437  2643.760356/s
    vus........................: 10     min=10 max=10
    vus_max....................: 10     min=10 max=10
</pre>
</details>

I can confirm that running 2 pgbouncers do increase the RPS.

This was the `pgbouncer.ini` I used:

```ini
[databases]
postgres = host=/run/postgresql dbname=postgres pool_mode=transaction pool_size=20
                                                                                                                   
[pgbouncer]
listen_addr = *
listen_port = 6543
auth_type = trust
auth_file = ${pgbouncerAuthFile}
unix_socket_dir = /run/postgresql
log_connections = 0
log_disconnections = 0
                                                                                                                   
so_reuseport = 1
```

---

Hmm, will try pgbouncer on the same instance that postgREST is running instead.

**Comment by steve-chavez** [comment]
> Hmm, will try pgbouncer on the same instance that postgREST is running instead.

Did that and the numbers almost doubled:

<details>
 <summary>1587.418643/s for postgREST + pgbouncer on the same instance</summary>
<pre>
    data_received..............: 15 MB  498 kB/s
    data_sent..................: 4.9 MB 163 kB/s
  ✓ failed requests............: 0.00%  ✓ 0    ✗ 47701
    http_req_blocked...........: avg=4.5µs   min=980ns   med=1.64µs  max=965.88µs p(90)=2.25µs  p(95)=2.68µs
    http_req_connecting........: avg=2.16µs  min=0s      med=0s      max=932.75µs p(90)=0s      p(95)=0s
  ✓ http_req_duration..........: avg=6.22ms  min=2.26ms  med=5.66ms  max=25.12ms  p(90)=9.34ms  p(95)=10.92ms
    http_req_receiving.........: avg=36.18µs min=14.83µs med=35.15µs max=4.75ms   p(90)=43.73µs p(95)=49.19µs
    http_req_sending...........: avg=9.53µs  min=6.01µs  med=8.32µs  max=396.71µs p(90)=11µs    p(95)=12.88µs
    http_req_tls_handshaking...: avg=0s      min=0s      med=0s      max=0s       p(90)=0s      p(95)=0s
    http_req_waiting...........: avg=6.17ms  min=2.22ms  med=5.61ms  max=25.08ms  p(90)=9.3ms   p(95)=10.87ms
    http_reqs..................: 47701  1587.418643/s
    iteration_duration.........: avg=6.28ms  min=2.31ms  med=5.72ms  max=25.67ms  p(90)=9.41ms  p(95)=10.98ms
    iterations.................: 47701  1587.418643/s
    vus........................: 10     min=10 max=10
    vus_max....................: 10     min=10 max=10
</pre>
</details>

The numbers are still noticeable lower than our pool, even with `db-prepared-statements=false` I get `2281.820766/s`.

**Comment by dwagin** [comment]
Please test also for compare postgREST pool + multiple pgbouncer on same instance

**Comment by steve-chavez** [comment]
@dwagin Sure, numbers are slightly worse. I guess since it's a 2 core instance there's more CPU contention:
 
<details>
 <summary>1449.334363/s for postgREST + 2 pgbouncer on the same instance</summary>
<pre>
   data_received..............: 14 MB  455 kB/s
    data_sent..................: 4.5 MB 149 kB/s
  ✓ failed requests............: 0.00%  ✓ 0    ✗ 43553
    http_req_blocked...........: avg=4.93µs  min=1.05µs  med=1.64µs  max=1.08ms   p(90)=2.23µs  p(95)=2.71µs
    http_req_connecting........: avg=2.57µs  min=0s      med=0s      max=593.08µs p(90)=0s      p(95)=0s
  ✓ http_req_duration..........: avg=6.82ms  min=2.4ms   med=6.22ms  max=39.46ms  p(90)=10.27ms p(95)=11.97ms
    http_req_receiving.........: avg=36.54µs min=15.99µs med=35.43µs max=8.35ms   p(90)=43.51µs p(95)=49.14µs
    http_req_sending...........: avg=9.77µs  min=6.09µs  med=8.5µs   max=2.7ms    p(90)=11.04µs p(95)=13.04µs
    http_req_tls_handshaking...: avg=0s      min=0s      med=0s      max=0s       p(90)=0s      p(95)=0s
    http_req_waiting...........: avg=6.77ms  min=2.34ms  med=6.17ms  max=39.42ms  p(90)=10.22ms p(95)=11.93ms
    http_reqs..................: 43553  1449.334363/s
    iteration_duration.........: avg=6.88ms  min=2.45ms  med=6.29ms  max=39.52ms  p(90)=10.33ms p(95)=12.04ms
    iterations.................: 43553  1449.334363/s
    vus........................: 10     min=10 max=10
    vus_max....................: 10     min=10 max=10
</pre>
</details>

One more interesting data point. I'm using unix socket(`db-uri = "host=/tmp dbname=postgres port=6543 user=postgres`) from pgREST to pgbouncer in the above load test, with TCP(`db-uri = "postgres://postgres@localhost:6543/postgres"`)  there's a noticeable decrease:

<details>
 <summary>1074.046954/s for postgREST + 2 pgbouncer on the same instance through TCP</summary>
<pre>
    data_received..............: 10 MB  337 kB/s
    data_sent..................: 3.3 MB 110 kB/s
  ✓ failed requests............: 0.00%  ✓ 0    ✗ 32277
    http_req_blocked...........: avg=5µs     min=1.1µs   med=1.62µs  max=935.86µs p(90)=2.23µs  p(95)=2.66µs
    http_req_connecting........: avg=2.59µs  min=0s      med=0s      max=515.83µs p(90)=0s      p(95)=0s
  ✓ http_req_duration..........: avg=9.22ms  min=2.81ms  med=8.01ms  max=50.3ms   p(90)=15.22ms p(95)=18.3ms
    http_req_receiving.........: avg=36.74µs min=13.41µs med=35.44µs max=8.16ms   p(90)=43.39µs p(95)=48.66µs
    http_req_sending...........: avg=9.65µs  min=6.03µs  med=8.49µs  max=396.39µs p(90)=10.91µs p(95)=12.64µs
    http_req_tls_handshaking...: avg=0s      min=0s      med=0s      max=0s       p(90)=0s      p(95)=0s
    http_req_waiting...........: avg=9.18ms  min=2.77ms  med=7.96ms  max=50.27ms  p(90)=15.18ms p(95)=18.25ms
    http_reqs..................: 32277  1074.046954/s
    iteration_duration.........: avg=9.29ms  min=2.87ms  med=8.07ms  max=50.35ms  p(90)=15.29ms p(95)=18.37ms
    iterations.................: 32277  1074.046954/s
    vus........................: 10     min=10 max=10
    vus_max....................: 10     min=10 max=10
</pre>
</details>

**Comment by steve-chavez** [comment]
I went back to trying to improve our pool instead. I got a hint from a [NoRedInk blog post](https://blog.noredink.com/post/666654908557180928/tuning-haskell-rts-for-kubernetes-part-2). So by default all cores participate in GC, using the [-qn](https://downloads.haskell.org/~ghc/8.10.7/docs/html/users_guide/runtime_control.html#rts-flag--qn%20%E2%9F%A8x%E2%9F%A9) flag lets us control that. I've tried the bench tests with `-qn 2` and that solves the issue of getting worse results in higher number of cores and we get a throughput bonus of around 57% :tada:

Also it reduces the CPU consumption to almost half. More details at https://github.com/supabase/benchmarks/pull/34#issuecomment-1140183052

The numbers still don't improve on 32, 48, 64 cores but now they maintain. Also not sure if there's something else wrong with my benchmark setup in those.

**Comment by steve-chavez** [comment]
@dwagin Btw, you have a patched postgREST for using pgbouncer(similar to https://github.com/steve-chavez/postgrest/commit/05d1ea0cf01f13abe76ff9ad740d0fa673782545) right? I thought doing `db-pool=1` would work but it doesn't because only one pgbouncer connection is used, so a direct connection is needed.

**Comment by steve-chavez** [comment]
Didn't end up using scrive-pool because the patch was messy: https://github.com/steve-chavez/postgrest/tree/scrive-pool. Also I think hasq-pool will be updated soon to solve this: https://github.com/nikita-volkov/hasql-pool/commit/e7843bff2647ee5e015549c16325d44983f9b8fc

Also, regarding using an external pool. As I commented above, currently it cannot be done unless a direct connection is used(as in https://github.com/steve-chavez/postgrest/commit/05d1ea0cf01f13abe76ff9ad740d0fa673782545). If we would like to allow this, maybe we can have it working for a `db-pool = 0`, which would be a backwards compatible change. db-pool = 0 now is illegal.
