### ISSUE TITLE
Computed columns not working anymore when the SCHEMA name contains uppercase characters

### ISSUE THREAD

**Issue by Pigeo** [PostgREST/postgrest#2341]
### Environment

* PostgreSQL version: 12.10 (Debian 12.10-1.pgdg100+1)
* PostgREST version: both 8.0 and 9.0.1 are impacted (linux-static-x64)
* Operating system: Debian Buster (10.12)

### Description of issue

Trying to use a computed column: `/my_film?select=*,thumbnail` (where thumbnail(my_film) is a computed column)

When the SCHEMA name contains any uppercase characters, PostgREST will raise an error:

 `column my_film.thumbnail does not exist`

However if I rename the SCHEMA name in order to remove any uppercase characters, it then works normally.

Note this is a regression bug: I'm using PostgREST version 7 in production with a SCHEMA name "REST_API_v1_0" and it is working properly. Only when I try to upgrade to PostgREST 8 or 9 then the problem arises.

### Steps to reproduce

```sql
CREATE SCHEMA "REST_api_v2_0" AUTHORIZATION anonymous;

CREATE TABLE "REST_api_v2_0".film  (
    film_id integer NOT NULL,
    title character varying(255) NOT NULL
);

CREATE VIEW "REST_api_v2_0".my_film AS
    SELECT film.film_id AS id,
    film.title AS titre
   FROM "REST_api_v2_0".film
  WHERE film_id<100;

GRANT SELECT ON TABLE "REST_api_v2_0".film TO public;
GRANT SELECT ON TABLE "REST_api_v2_0".my_film TO public;

CREATE FUNCTION "REST_api_v2_0".thumbnail(c "REST_api_v2_0".my_film) RETURNS text AS $$
BEGIN
  RETURN 'REST_API_v2_0 bar';
END;
$$ LANGUAGE plpgsql IMMUTABLE    RETURNS NULL ON NULL INPUT   PARALLEL SAFE;

GRANT EXECUTE ON FUNCTION "REST_api_v2_0".thumbnail TO public;
```

=> Trying `/my_film?select=*,thumbnail` won't work (error "column does not exist").

Now execute the following SQL line:

```sql
ALTER SCHEMA "REST_api_v2_0" RENAME TO "rest_api_v2_0";
```

(And don't forget to update your `db-schema` param in the `postgrest.conf` file)

=> Now it works properly (no more error)

**Comment by Pigeo** [comment]
As an improvement measure to ensure that this does not happen anymore again, may I suggest you to use in your unit tests a SCHEMA name containing spaces, uppercase letters, accented letters, digits, underscores, and a lot of other weird characters, so that any such regression would eventually trigger a failure when performing the unit tests in the context of a new version release.

**Comment by laurenceisla** [comment]
Can reproduce. Looks like it's a problem with setting the `search_path` in this line:

https://github.com/PostgREST/postgrest/blob/d87b622d64d993a240be9a28b7e6f515a489c161/src/PostgREST/Middleware.hs#L67

The executed SQL statement to set the `search_path` on PostgREST v8.0 onwards is:

```sql
SELECT set_config('search_path', 'REST_api_v2_0, public', true);
```

But the schemas should be inside quotation marks in order to accept uppercase/special characters, like so:

```sql
SELECT set_config('search_path', '"REST_api_v2_0", "public"', true)
```
