### ISSUE TITLE
Total record count returned depends on order of items within the select= (and thus sometimes becomes inaccurate), when top-level filtering with embedded resource filters

### ISSUE THREAD

**Issue by Pigeo** [PostgREST/postgrest#2342]
It seems that [issue #2009](https://github.com/PostgREST/postgrest/issues/2009) is still there in PostgREST 9.0.1 (linux-static-x64, downloaded yesterday from GitHub / running on PostgreSQL 12 / Debian Buster), but it only triggers in some special circumstances...

Let's take again the [same sample database](https://www.postgresqltutorial.com/postgresql-sample-database/), but suppose we now have a lot of films that don't have any category:

```sql
DELETE FROM film_category WHERE category_id > 1; -- only 64 films will keep their category after that
```

and let's add another table (film_actor) into play :

```httpspec
GET http://127.0.0.1:3000/film?select=*,film_category!inner(*),film_actor(*) HTTP/1.1
```

=> here, `Content-Range` correctly says `'0-63/64'`.

Now let's just change the order of the parameters inside the query string:

```httpspec
GET http://127.0.0.1:3000/film?select=*,film_actor(*),film_category!inner(*) HTTP/1.1
```

=> it should not change anything to the results / behavior, right? But now, `Content-Range` incorrectly says `'0-63/1000'` (whereas the very same 64 rows are still returned in the body)

It's not clear to me why we have to put another table in play in order to trigger the bug, but without it the bug doesn't happen:

```httpspec
GET http://127.0.0.1:3000/film?select=*,film_category!inner(*) HTTP/1.1
```

=> correctly says `Content-Range '0-63/64'`.

While waiting for a fix to be included in a next release, I think I found a work-around that seems to work (other than reordering the content of the select=, which may be not a viable solution in some contexts) : just add a dummy filter that says that the FK of the embedded table which references the main table should not be null (of course it can't be null, because we are performing an `INNER JOIN`):

```httpspec
GET http://127.0.0.1:3000/film?select=*,film_actor(*),film_category!inner(*)&film_category.film_id=not.is.null HTTP/1.1
```

=> now correctly says again `Content-Range '0-63/64'`.

Adding this useless dummy filter seems to change the order in which all the parameters of the `select=` are processed, as you can see on the result body (the content of the body is then "sorted" as if we had asked for `/film?select=*,film_category!inner(*),film_actor(*)` as you can see it with any diff/merge tool).

**Comment by laurenceisla** [comment]
Can reproduce in the current main branch too. The generated queries in the examples differ in the order of the selected queries (not a problem), but the `pgrst_source_count` CTE are different for both. Looks like the `COUNT` stops when it doesn't find a subquery with an inner join.

The line is here:

https://github.com/PostgREST/postgrest/blob/8230128ff6cf193b39f8778d48512a2baf8aafa4/src/PostgREST/Query/QueryBuilder.hs#L247-L251

This change seems to generate the `CTE` correctly (quickfix for testing) :

```haskell
     then ("EXISTS (" <> readRequestToCountQuery readReq <> " )"):rest 
     else "TRUE":rest -- here it's missing array to keep verifying
```
