### ISSUE TITLE
Resource embedding across different schemas

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#2346]
[Resource Embedding](https://postgrest.org/en/latest/api.html#resource-embedding) only supports embedding across a single schema.

According to the [profile negotiation spec](https://profilenegotiation.github.io/I-D-Accept--Schema/I-D-accept-schema#rfc.figure.10):

> A client requests an XML document where the elements in namespace urn:example:namespaces:ns1 must conform to XML schema http://example.com/schema/schema-1 and the elements in namespace urn:example:namespaces:ns2 must conform to XML schema http://example.com/schema/schema-2. The server answers that it can supply the document as requested.

> Request:
GET /some-resource HTTP/1.1
Accept-Profile: 	<urn:example:namespaces:ns1
				http://example.com/schema/schema-1
				urn:example:namespaces:ns2
				http://example.com/schema/schema-2>

> Response:
HTTP/1.1 200 OK
Content-Type: application/xml
Profile: <urn:example:namespaces:ns1
		http://example.com/schema/schema-1
		urn:example:namespaces:ns2
		http://example.com/schema/schema-2>

The spec is more XML focused but I believe we can extend the same concept of "elements in namespace must conform to XML schema" to "relations must conform to schema". So this would allow us to do:

```http
GET /projects?select=*,clients(*)

Accept-Profile: <projects:api_v1 clients:api_v2>
```

Where `projects` comes from the `api_v1` schema and `clients` comes from the `api_v2` schema.

I'm still unclear on how to structure the absolute URLs for our case, but in theory it seems possible.

---

The resource embedding code is actually ready for handling different schemas, we just need code for mapping the header.

---

Related https://github.com/PostgREST/postgrest/discussions/2769

**Comment by wolfgangwalther** [comment]
I don't see why we would want to allow resource embedding across different profiles. When I remember correctly, you tried hard to make sure that schemas accessed through profiles are isolated from each other - there's a few test cases for that, too, right?

**Comment by steve-chavez** [comment]
Ditching this idea. No longer think is good for an API schema to allow cross resource embedding.

We'll likely move from the `Accept-Profile` header too https://github.com/PostgREST/postgrest/issues/2927
