### ISSUE TITLE
Get the EXPLAIN output of a request

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#2354]
Sometimes it's difficult to understand why a simple request like `/tbl?id=eq.1` can be slow while it's equivalent in SQL is fast. This is usually due to a bad RLS policy that only applies to a postgREST role.

We could support an `Accept: application/vnd.pgrst.explain+json` media type that gets the `EXPLAIN (FORMAT JSON)` output into a response. That would clarify that the query is expensive and is not because of us doing some extra processing.

An `EXPLAIN ANALYZE` could also be supported with `Accept: application/vnd.pgrst.explain-analyze+json`, coupled with `Prefer: tx=rollback` it would be safe to do. We might also consider applying `tx=rollback` by default for it.

---

References: 
- https://www.postgresql.org/docs/current/sql-explain.html
- [Previous discussion of using the http TRACE method for debugging](https://github.com/PostgREST/postgrest/issues/1573#issuecomment-677899436)
- [Previous discussion of using `Accept: application/sql` to obtain the generated query](https://github.com/PostgREST/postgrest/issues/1573#issuecomment-677865905)

**Comment by steve-chavez** [comment]
Actually `EXPLAIN (FORMAT JSON) ANALYZE` is not allowed in pg(gives syntax error). So we only need a single media type.

Searching [IANA types](https://www.iana.org/assignments/media-types/media-types.xhtml), I found some related to cost(`alto-endpointcost+json`, `alto-costmap+json`, etc) but those doesn't map to our use case.

So we should go with our own vendor media type: `application/vnd.pgrst.plan`. Taking advantage of the different formats in EXPLAIN, we can do `application/vnd.pgrst.plan+{text,xml,json,yaml}`.

**Comment by steve-chavez** [comment]
> [Previous discussion of using the http TRACE method for debugging](https://github.com/PostgREST/postgrest/issues/1573#issuecomment-677899436)

Mentioned before, but repeating it here: 

>  [A client MUST NOT send a message body in a TRACE request.](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.8)

So unfortunately that leaves TRACE out. Still, because of the different formats supported, the media type seems like the right interface.

**Comment by steve-chavez** [comment]
Getting the [pg 14 Query ID](https://blog.rustprooflabs.com/2021/10/postgres-14-query-id) would be good for debugging too. That way a request can be easily mapped to a query in the logs.

Seems it's possible to get it with `EXPLAIN VERBOSE` as mentioned in the blog post but I wonder if we could get it for every query somehow, then we could expose it in a header(`Query-Identifier: 1382294904069104546`).

**Comment by wolfgangwalther** [comment]
> Actually `EXPLAIN (FORMAT JSON) ANALYZE` is not allowed in pg(gives syntax error). So we only need a single media type.

It's `EXPLAIN (ANALYZE, FORMAT JSON)`.

**Comment by steve-chavez** [comment]
Oh, thanks for clarifying that Wolfgang.

I guess we should have two media types then. Hm, I think it'd be cleaner to just have one. Maybe we can just do the EXPLAIN ANALYZE with the ROLLBACK.

**Comment by steve-chavez** [comment]
There's a problem with using a media type for this. We generate different queries for each of our [supported media types](https://postgrest.org/en/latest/api.html#response-format). If we use `application/vnd.pgrst.plan+{text,xml,json,yaml}` for the different outputs of the `EXPLAIN`, how would we control the generated query..

I guess we could match the `application/vnd.pgrst.plan+json` to the generated `json_agg` query plus the `EXPLAIN FORMAT JSON` and `application/vnd.pgrst.plan+text` to the generated `string_agg` plus `EXPLAIN FORMAT TEXT`. In that case a new media type doesn't help that much, so I think a `Prefer` header would be more suitable.

We could reuse our `return` for this:

- EXPLAIN: `Prefer: return=plan`
- EXPLAIN ANALYZE: `Prefer: return=analysis`

**Comment by steve-chavez** [comment]
Since it leaks internal details of the table, we can enable the above preference with a config. In the same way is done for the `Prefer: tx=rollback` header with [db-tx-end](https://postgrest.org/en/stable/configuration.html#db-tx-end). It could be `db-allow-plan` or `db-allow-explain`.

**Comment by steve-chavez** [comment]
Settling on a media type with parameters plus suffixes for this. This has the advantage of being able to generate the different queries plus obtain the EXPLAIN in different formats.

```bash
# By default get the Accept: application/json generated query plus EXPLAIN FORMAT JSON
application/vnd.pgrst.plan

# Get the Accept: application/json generated query explicitly plus EXPLAIN FORMAT TEXT
application/vnd.pgrst.plan+text;for=application/json 

# Get the Accept: text/plain generated query explicitly plus EXPLAIN output in XML
application/vnd.pgrst.plan+xml;for=text/plain 

# Get the Accept: text/xml generated query SQL
application/vnd.pgrst.plan+sql;for=text/xml 
```

Since the `for` parameter has the media type, it could later be extended to support custom `Accept` types too(https://github.com/PostgREST/postgrest/pull/1582).

**Comment by steve-chavez** [comment]
This library already has more complete(subtypes, parameters) parsing of media types than the functions we have in core: https://hackage.haskell.org/package/http-media-0.8.0.0/docs/Network-HTTP-Media-MediaType.html#g:2
