### ISSUE TITLE
Performing full text search on multiple columns

### ISSUE THREAD

**Issue by dshukertjr** [PostgREST/postgrest#2374]
This might be a long shot, but I still wanted to post it to get some feedbacks. 

It is pretty common for app developers to want to perform full text search across multiple columns, for example search though blog posts where either title or the content contains a certain search term. Could we bring this capability in Postgrest? It certainly is possible using rpc, but I thought it would be awesome if we were able to provide this via rest api.

**Comment by steve-chavez** [comment]
> either title or the content contains a certain search term

@dshukertjr IIUC, the above should already be possible with `or`. Like:

```http
GET /blog_posts?or=(title.fts.searchTerm,content.fts.searchTerm)
```

Or what other interface do you have in mind?

**Comment by dshukertjr** [comment]
@steve-chavez
Ah, I didn't think of that! That is amazing! Thank you for enlightening me Steve! I will close this one!
