### ISSUE TITLE
PostgreSQL 13 - Custom parameter names must be two or more simple identifiers separated by dots.

### ISSUE THREAD

**Issue by sabatale** [PostgREST/postgrest#2384]
### Environment

* PostgreSQL version: Google CloudSQL - PostgreSQL 13.7
* PostgREST version: Latest (no docker)
* Operating system: Ubuntu

### Description of issue

I haven't been able to pinpoint exactly when it stopped working but our API went down and we get the following error in the logs: "**db=....,user=... ERROR: invalid configuration parameter name "request.header.accept-encoding"**" and "**Custom parameter names must be two or more simple identifiers separated by dots.**".

This is similar to [https://github.com/PostgREST/postgrest/issues/1857](https://github.com/PostgREST/postgrest/issues/1857), except we are NOT running Pg14 and are using PostgREST 9.0.1.

Google CloudSQL change log is [maintained here](https://cloud.google.com/sql/docs/postgres/maintenance-changelog/postgres-13).

Are there any others logs we can take a look at?

Thanks!

**Comment by steve-chavez** [comment]
> except we are NOT running Pg14
> Google CloudSQL change log is [maintained here](https://cloud.google.com/sql/docs/postgres/maintenance-changelog/postgres-13).

That's strange, maybe they applied a breaking change on their pg13.

Try turning the [db-use-legacy-gucs](https://postgrest.org/en/latest/configuration.html#db-use-legacy-gucs) config to false.

**Comment by sabatale** [comment]
This works! In the end, we took the opportunity to stage an upgrade to Pg14.

Not sure what happened but I guess Google CloudSQL had something to do with it.

Thanks!

**Comment by steve-chavez** [comment]
Cool.

> That's strange, maybe they applied a breaking change on their pg13.

Btw, the above seems like it. I've just made a test on the official PostgreSQL 13.7(which is the one we run on our CI tests):

```python
psql (13.7)
Type "help" for help.

postgres=# select version();
                                   version
------------------------------------------------------------------------------
 PostgreSQL 13.7 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 11.3.0, 64-bit
(1 row)

postgres=# set request.header."accept-encoding" to 'test';
SET
```

While PostgreSQL 14:

```python
psql (14.4)
Type "help" for help.

postgres=# select version();
                                   version
------------------------------------------------------------------------------
 PostgreSQL 14.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 11.3.0, 64-bit
(1 row)

postgres=# set request.header."accept-encoding" to 'test';
ERROR:  invalid configuration parameter name "request.header.accept-encoding"
DETAIL:  Custom parameter names must be two or more simple identifiers separated by dots.
```

**Comment by robert-pang** [comment]
This issue happens due to the most recent maintenance applied to Google Cloud SQL PostgreSQL instances. The maintenance includes a behavior change for configuration parameters in PostgreSQL major versions 9.6 to 13. We apologize for this issue.

Apart from updating PostgREST to version 9 and setting [db-use-legacy-gucs](https://postgrest.org/en/latest/configuration.html#db-use-legacy-gucs) to false as workaround described above, please also see Google Cloud SQL PostgreSQL's [release notes](https://cloud.google.com/sql/docs/postgres/release-notes#July_29_2022) for the way to update your Google Cloud SQL PostgreSQL instances to resolve the issue.
