### ISSUE TITLE
403 http status code

### ISSUE THREAD

**Issue by csakaszamok** [PostgREST/postgrest#2385]
### Environment
* PostgreSQL version: 14
* PostgREST version: postgrest/postgrest:v9.0.0

### Description of issue
Expected behavior:
Throw http response code 403 when user is logged on but he has no role to access the database object

Actual behavior:
It throws same 401 error code for anonymous users and logged users too

(Steps to reproduce: Include a minimal SQL definition plus how you make the request to PostgREST and the response body)
create table A (name text);
insert into A values ('catch me');
grant select on A to webuser;
-> now we can get table A data with curl by webuser token, because it is logged in

revoke select on A from webuser;
-> PostgREST throws 401 http error code (but it should throw 403, it is still logged in and can get others tables)

**Comment by laurenceisla** [comment]
I could not reproduce the issue.

After creating the table and granting select to a non-anonymous user:

```console
$ curl "http://localhost:3000/a" -I -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidG9kb191c2VyIn0.YhVX9eNb-mnCdzZAOCB12XxqXcnWNpq5Go8kVyipTH0"
HTTP/1.1 200 OK
Date: Mon, 25 Jul 2022 15:54:41 GMT
Server: postgrest/9.0.0
Content-Range: 0-0/*
Content-Location: /a
Content-Type: application/json; charset=utf-8
```

After revoking select from the non-anonymous user:

```console
$ curl "http://localhost:3000/a" -I -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidG9kb191c2VyIn0.YhVX9eNb-mnCdzZAOCB12XxqXcnWNpq5Go8kVyipTH0"
HTTP/1.1 403 Forbidden
Date: Mon, 25 Jul 2022 15:52:04 GMT
Server: postgrest/9.0.0
Content-Type: application/json; charset=utf-8
```

Are these the correct steps? If not please provide the exact steps with the curl requests that give you the result you mention.

**Comment by wolfgangwalther** [comment]
@csakaszamok can you provide a reproducible example?

**Comment by steve-chavez** [comment]
Will close for now. Please reopen if you have a reproducible example.
