### ISSUE TITLE
Less strict junctions for m2m relationships

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#2425]
On https://github.com/PostgREST/postgrest/pull/2262 we added a restriction for junctions:

- A table has FKs to two other tables
- **These FK columns are part of the table's PK columns.**

This might not work out of the box for many cases. Many junctions with surrogate keys don't include the FKs as part of the PK.

### Proposal

We can add a fallback pattern for junction detection to cover these cases.

If the table name is composed of the combination of `table_foreigntable`(camelCase too) and both FKs are present(to `table` and `foreigntable`) we detect the m2m.

**Comment by wolfgangwalther** [comment]
That'd be too much magic for me personally. I think we should instead provide a clear migration guide, showing how to either:
- add a PK to those tables or
- write the same as a computed relationship

**Comment by steve-chavez** [comment]
Yeah, agree. I thought changing the PK would be too invasive for all cases and forgot about computed relationships.
