### ISSUE TITLE
Embedding the same table multiple times causes different error messages

### ISSUE THREAD

**Issue by bolerodan** [PostgREST/postgrest#2455]
### Environment

* PostgreSQL version: v14
* PostgREST version: v10
* Operating system: Ubuntu 20

### Prelude

I'm testing the exciting new release of version 10 of Postgrest (mainly excited about those computed rels) against our highly complicated and nested embedded database design. Currently, I am using a temporary build from issue #2070, build located here https://github.com/PostgREST/postgrest/issues/2070#issuecomment-1110233394

As I believe that build added in the junction table fix, ignores tables that are not pure junction tables, which solved our problems.

Unfortunately my query is complicated and long, so I'm sorry if I'm missing important details. (I will try to put together the schema required for this, but the schema is large)

### Description of issue

Attempting to embed the same table, related to different nested embeds has provided me with 2 separate errors.

query  one
I know i know, why are you embedding BACK to container (there is a good reason and we use a limit and avoid potential recursion issues from this and works well in the version linked above)

```
/container?select=sample(*,container(*))
```
Error
```
table name \"sample_container\" specified more than once
```

However providing an alias fixes this. Again, dont need to do this in the version linked above

```
select=sample(*,sc:container(*))
```

Query two

This query has multiple embeds to the table `well` at different nested levels

```
select=*,largescale_daughter(*,container(*,container_process(*,container_process_condition(*)))),container(*,well(*,plate(*,well(*))),container_process(*,container_transfer(to_container:to_container_id(well(*)))))
```

error

```
aggregate functions are not allowed in FROM clause of their own query level
```

To fix this, all I need to do is alias at least ONE `well` embed, infact it doesnt seem to matter which `well` i alias. The fix is the same in both instances, however different error messages.
```
select=*,largescale_daughter(*,container(*,container_process(*,container_process_condition(*)))),container(*,well(*,plate(*,well(well_id,row,col))),container_process(*,container_transfer(to_container:to_container_id(WELLALIAS:well(*)))))
```

notice `WELLALIAS:well` at the end.

This functionality works correctly in the old build I linked above.

I will try to put together a schema for reproducibility , although I may share this over a PM.

Thanks a lot guys.

**Comment by steve-chavez** [comment]
Looks like we need to refine our aliasing for the embedding tree.

> I will try to put together a schema for reproducibility , although I may share this over a PM.

Cool, that would be great.

**Comment by steve-chavez** [comment]
@bolerodan You can send it to me through email(it's on my github profile).

**Comment by bolerodan** [comment]
Just a follow up on the internal aliasing of generated queries. I tried an example computed relationship, latest feature in v10 which I think is the coolest thing and such a cool feature.

It seems because of aliasing, nested embeds into a compute rel function break.

Example schema

```
create table foo (
  foo_id int primary key
);
create table bar (
  bar_id int primary key
);

create table janedoe (
  janedoe_id int primary key,
  bar_id int references bar(bar_id)
);

create table johnsmith (
  johnsmith_id int primary key,
  foo_id int references foo(foo_id),
  bar_id int references bar(bar_id)
);

create or replace function jsbar(foo) returns setof bar as $$
    select b.*
    from bar b
    join johnsmith js on js.bar_id = b.bar_id
    where js.foo_id = $1.foo_id
$$ stable language sql;
```

Example call

```
/foo?select=*,jsbar(*,janedoe(*))
```

response

```
{
  "code": "42P01",
  "details": null,
  "hint": null,
  "message": "missing FROM-clause entry for table \"bar\""
}
```

So here is the generated query sent to Postgresql from Postgrest

```
SELECT "public"."foo".*, COALESCE( "foo_jsbar"."_foo_jsbar", '[]') AS "jsbar" 
FROM "public"."foo" 
LEFT JOIN LATERAL ( 
  SELECT json_agg("_foo_jsbar") AS "_foo_jsbar"
  FROM (
    SELECT "jsbar".*, COALESCE( "bar_janedoe"."_bar_janedoe", '[]') AS "janedoe" 
    FROM "public"."jsbar"("foo") 
    LEFT JOIN LATERAL ( 
      SELECT json_agg("_bar_janedoe") AS "_bar_janedoe"
      FROM (
        SELECT "public"."janedoe".* 
        FROM "public"."janedoe"  
        WHERE "public"."janedoe"."bar_id" = "public"."bar"."bar_id"   
      ) AS "_bar_janedoe" 
    ) AS "bar_janedoe" ON TRUE    
  ) AS "_foo_jsbar" 
) AS "foo_jsbar" ON TRUE   
```

The issue here, is the function call from clause `FROM "public"."jsbar"("foo")`. Since this function returns `bar` in its definition, I assume this is confusing Postgrest causing the join to be `WHERE "public"."janedoe"."bar_id" = "public"."bar"."bar_id" `
when really it should be joined from `FROM "public"."jsbar"("foo")`

so ideally an alias should be made
`FROM "public"."jsbar"("foo") AS jsbar_alias`

and thus the inner lateral join query, can reference the outer query through the alias

`WHERE "public"."janedoe"."bar_id" = "jsbar_alias"."bar_id" `


I assume at some point this alias issue is kinda all related. Just dropping some more findings here
