### ISSUE TITLE
tests: option no_pool_connection_available in IO tests is broken

### ISSUE THREAD

**Issue by robx** [PostgREST/postgrest#2456]
The fixture essentially does this:

```
        process = subprocess.Popen("postgrest")
        yield process

        if no_pool_connection_available:
            sleep_pool_connection(baseurl, 10)

        process.terminate()
```

so the pool is only blocked *after* the test is done.

**Comment by steve-chavez** [comment]
Oh, I see it now. Pool connections were actually available in these tests: 

https://github.com/PostgREST/postgrest/blob/e2aa2275974e00006b11e99c5bec8b32c2b58851/test/io/test_io.py#L1193-L1206

Doing a `postgrest.session.head("/projects")` inside succeeded with 200.
