### ISSUE TITLE
Embedding with computed relationships breaks when the schema name has special characters

### ISSUE THREAD

**Issue by Iced-Sun** [PostgREST/postgrest#2473]
### Environment

* PostgreSQL version: 13.4, 13.8, 14.5
* PostgREST version: v10.0.0
* Operating system: Ubuntu 22.04

### Description of issue

With the snippet of
```sql
create schema "api";
create table "api".premieres (
  id integer primary key,
  location text,
  "date" date,
  film_id integer
);

insert into "api".premieres values(2001, 'loc 1', '2022-01-01', 1);
insert into "api".premieres values(2002, 'loc 2', '2022-02-01', 2);
insert into "api".premieres values(2003, 'loc 3', '2022-03-01', 3);
insert into "api".premieres values(2004, 'loc 4', '2022-04-01', 4);
insert into "api".premieres values(2005, 'loc 5', '2022-05-01', 5);

create table "api".films(
    id integer  primary key,
    director_id integer,
    title text,
    year integer,
    rating decimal(3,2),
    language text
);

insert into "api".films values(1, 1, 'film 1', 2010, 4.3, 'EN');
insert into "api".films values(2, 1, 'film 2', 2011, 4.9, 'EN');
insert into "api".films values(4, 3, 'film 4', 2012, 4.1, 'CN');
insert into "api".films values(5, 3, 'film 5', 2013, 4.6, 'CN');

create function "api".computed_films("api".premieres) returns setof "api".films rows 1 as $$
  select * from "api".films where id = $1.film_id
$$ stable language sql;
```
a query of `curl -H 'Accept-Profile: api' 'localhost:3000/premieres?select=*,computed_films(*)'` just works as expected.

If we change the schema name from `api` to `api-v1`, the query `curl -H 'Accept-Profile: api-v1' 'localhost:3000/premieres?select=*,computed_films(*)'` suddenly breaks with the `PGRST200` message.

A schema name of `api+v2` breaks the rel detection as well.

**Comment by laurenceisla** [comment]
Could reproduce. The error only happens when doing an embed with computed columns and the schema name has special characters. Embedding with foreign keys works without problem. 

I think it's this part of the query that causes the problem:

https://github.com/PostgREST/postgrest/blob/bb52fb9b0e0c40c3cf235f6851fdaae9c1b35129/src/PostgREST/DbStructure.hs#L713

The schema cache returns `"\"api-v2\""` instead of `"api-v2"` as the schema name.
