### ISSUE TITLE
[Feature Request] Response times & GC metrics

### ISSUE THREAD

**Issue by bhupixb** [PostgREST/postgrest#2477]
### Description of the issue
It would be great if we can get 
1. GC
2. Query response times 
3. Requests queued, DB connection pool usage count etc
metrics on the Admin Server port at maybe /metrics.

We are using v9.0.0 since Jan 2022, and were observing a lot of CPU usage, on digging we found that after disabling parallel & idle(already disabled in v9.0.1 I guess) GC reduced our CPU usage by ~50%. If postgrest had exposed GC metrics, we could have easily figured this out.

Thank you!

**Comment by steve-chavez** [comment]
For 2, you can already get the query timing with https://postgrest.org/en/stable/api.html#execution-plan, specifically `Accept: application/vnd.pgrst.plan;options=analyze`.

Agree on 1 and 3, those can fit in `/metrics`. We're tracking this on https://github.com/PostgREST/postgrest/issues/1526, let's continue there.

**Comment by bhupixb** [comment]
For 2, I was actually referring to time taken for a request for round trip from postgrest to DB.
It's helpful in scenarios when we are observing high latencies from postgrest but DB takes only few milli seconds. Such issues could be due to high load on postgrest pods, cpu throttling, connection pool crunch etc (in k8s world).
