### ISSUE TITLE
Allow full reponse control when raising exceptions (HTTP body + HTTP return headers)

### ISSUE THREAD

**Issue by yevon** [PostgREST/postgrest#2492]
Now when you raise exceptions you can just control HTTP reponse code and exception details, but you cannot have control about the body response or returned HTTP headers, as all previous set_config calls are not persisted after raising an exception. This limits the possibilities of the pre-request procedure as it can only control http code in case of an exception.

@wolfgangwalther solution to this would be:

Add support for a custom PGRST SQLSTATE error, where both message and detail take JSON. message would contain the response body for this error (i.e. message, detail, hint etc. all in there) and detail would contain a list of headers to set.

### Discussed in https://github.com/PostgREST/postgrest/discussions/2486

<div type='discussions-op-text'>

<sup>Originally posted by **yevon** September 24, 2022</sup>
I'm trying to implement a pre-request procedure that performs an exception with a 302, how can this be achieved? I don't see a mapped postgres error for 302 responses in the docs:

<html>
<body>

08* | 503 | pg connection err
09* | 500 | triggered action exception
0L* | 403 | invalid grantor
0P* | 403 | invalid role specification
23503 | 409 | foreign key violation
23505 | 409 | uniqueness violation
25006 | 405 | read only sql transaction
25* | 500 | invalid transaction state
28* | 403 | invalid auth specification
2D* | 500 | invalid transaction termination
38* | 500 | external routine exception
39* | 500 | external routine invocation
3B* | 500 | savepoint exception
40* | 500 | transaction rollback
53* | 503 | insufficient resources
54* | 413 | too complex
55* | 500 | obj not in prerequisite state
57* | 500 | operator intervention
58* | 500 | system error
F0* | 500 | config file error
HV* | 500 | foreign data wrapper error
P0001 | 400 | default code for “raise”
P0* | 500 | PL/pgSQL error
XX* | 500 | internal error
42883 | 404 | undefined function
42P01 | 404 | undefined table
42501 | if authenticated 403,else 401 | insufficient privileges
other | 400

<br class="Apple-interchange-newline">
</body>
</html></div>

**Comment by steve-chavez** [comment]
Just to give some details on the implementation.

RAISE errors with PT([ref](https://postgrest.org/en/stable/api.html#raise-errors-with-http-status-codes)) is done here

https://github.com/PostgREST/postgrest/blob/f54dc2e20ef03db4697de1e1716729848c51718b/src/PostgREST/Error.hs#L303-L304

Adding headers should be here

https://github.com/PostgREST/postgrest/blob/f54dc2e20ef03db4697de1e1716729848c51718b/src/PostgREST/Error.hs#L220-L226

**Comment by yevon** [comment]
Might I help with this? This will be quite powerful, as would allow me to perform additional things, like custom validations etc and is quite a big stopper right now. Is there somewhere some minimum guide on how to get started in postgrest development? I would just need to know how to create the docker image and how to perform minimum validations locally.

**Comment by steve-chavez** [comment]
Sure. I suggest to start with the Nix guide: https://github.com/PostgREST/postgrest/blob/main/nix/README.md

**Comment by yevon** [comment]
> Sure. I suggest to start with the Nix guide: https://github.com/PostgREST/postgrest/blob/main/nix/README.md

I'm having some problems when trying to start the nix-shell:

[Discussion](https://github.com/PostgREST/postgrest/discussions/2499)

**Comment by yevon** [comment]
Haskell is quite different of anything I've tried before, It's quite difficult to understandfor me, I don't think that I'm able to implement this properly right now 😂

**Comment by yevon** [comment]
Hi! Could somebody have a look at this please?

**Comment by yevon** [comment]
Hi, I read the docs yesterday and seems to be fixed already isn't it? It states how to put custom http errors and headers in the pre-request.

**Comment by steve-chavez** [comment]
@yevon I think you can do it with `pre-request` but bear in mind it will run for every request.

This feature still seems useful though.

**Comment by taimoorzaeem** [comment]
> Add support for a custom PGRST SQLSTATE error, where both message and detail take JSON. message would contain the response body for this error (i.e. message, detail, hint etc. all in there) and detail would contain a list of headers to set.

@steve-chavez What exactly does the `custom PGRST SQLSTATE error` mean here? Would the client raise something else instead of `SQLSTATE error`? It's kind of confusing because all `SQLSTATE` errors are captured in `(SQL.ServerError c m d h _)`, so why create a new error type?

**Comment by steve-chavez** [comment]
@taimoorzaeem It means an interface similar to the one documented in https://postgrest.org/en/stable/references/errors.html#raise-errors-with-http-status-codes.

> RAISE sqlstate 'PT402' using
  message = 'Payment Required',
  detail = 'Quota exceeded',
  hint = 'Upgrade your plan';

Currently we lack the ability to set headers on RAISE. So this new interface would allow it:

```sql
RAISE 'PGRST' using
  message = '{"code": 123, "message": "foo", "hint": "bar", "details": "baz"}'
  details = '{"status": 302, "headers": [{"Prefer": "foobar"}]}'
```
