### ISSUE TITLE
Add support for other comparison predicates such as `IS DISTINCT FROM`

### ISSUE THREAD

**Issue by laurence-isla** [PostgREST/postgrest#2501]
### Environment

* PostgreSQL version: v14.0
* PostgREST version: v10.0

### Description of issue

For completion, it would be nice to have the other [comparison predicates](https://www.postgresql.org/docs/current/functions-comparison.html) such as ~~`BETWEEN` and~~ `IS DISTINCT FROM`.  Based on [this SO question](https://stackoverflow.com/q/73941708/17265105).

**Comment by jacktose** [comment]
As the SO asker, I second this. I'm querying records with a field that might have values a, b, c, d, or null, and I want everything but the cs. Unfortunately for me, `not.eq.c` also excludes nulls, so `isdistinctfrom.c` would be a big help.

**Comment by magick93** [comment]
`Between` would be very useful and appreciated.

**Comment by steve-chavez** [comment]
I think BETWEEN shouldn't be added as the PostgreSQL wiki recommends not using it:

https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_BETWEEN_.28especially_with_timestamps.29

`isdistinctfrom` does seem useful. It's a long name for an operator though.. maybe we can find a shorter name.
