### ISSUE TITLE
Using HTTP Range headers for pagination makes gzip compression of response bodies impossible even with nginx proxy?

### ISSUE THREAD

**Issue by brandonros** [PostgREST/postgrest#2573]
Just want to confirm I'm not crazy. I've tried multiple nginx configs, Safari + Chrome.

`fetch()` from the browser will send `Accept-Encoding: identity` instead of `Accept-Encoding: gzip, deflate, br` by default because there's nothing that can be done apparently?

**Comment by brandonros** [comment]
Don't use `Range`, use `Content-Range`.

**Comment by steve-chavez** [comment]
Hm, this seems related to https://github.com/PostgREST/postgrest/pull/2204
