### ISSUE TITLE
Can't use JSONB indexes in `where` clause due to `to_jsonb` call

### ISSUE THREAD

**Issue by mqp** [PostgREST/postgrest#2594]
### Environment

Running on Supabase.

* PostgreSQL version: 14
* PostgREST version: 10
* Operating system: Linux

### Description of issue

I have a table `bets` with an `id` `text` primary key and a `data` `jsonb` column containing JSON objects with a `contractId` string property. After creating this index:
```sql
create index bets_contract_id on bets ((data->>'contractId'));
```
normal queries can use it:
```sql
select id from bets where data->>'contractId' = 'foo' limit 1; /* is fast */
```

However, if I try to perform the same query through PostgREST, e.g. `/bets?select=id&data->>contractId=eq.foo`, this SQL is generated:

```sql
WITH pgrst_source AS (
  SELECT "public"."bets"."id" FROM "public"."bets" WHERE to_jsonb("public"."bets"."data")->>$1 = $2
  LIMIT $3 OFFSET $4
)
SELECT
  null::bigint AS total_result_set,
  pg_catalog.count(_postgrest_t) AS page_total,
  array[]::text[] AS header,
  coalesce(json_agg(_postgrest_t), '[]')::character varying AS body,
  nullif(current_setting('response.headers', true), '') AS response_headers,
  nullif(current_setting('response.status', true), '') AS response_status
FROM (SELECT * FROM pgrst_source) _postgrest_t
```

This doesn't use my index, because it calls the `to_jsonb` function on the `data` column. If I remove that call, it works great and uses my index as expected.

I don't understand the cases this call is trying to handle, so I'm not sure what to suggest, but it's too bad this doesn't work well.

**Comment by mqp** [comment]
Thanks for the workaround, I didn't realize that I could get it to use my own `to_jsonb`. Happy holidays!

**Comment by bnjmnt4n** [comment]
> But I guess we failed to realize that `to_jsonb` is `STABLE`, not `IMMUTABLE`.

Hey @wolfgangwalther, I'm interested to find out why this would matter, if you're free to explain. Would the `STABLE` function be non-indexable?

**Comment by isaacharrisholt** [comment]
> Uh. This is mentioned in the [docs](https://postgrest.org/en/stable/api.html#composite-array-columns):
> 
> > When using the -> and ->> operators, PostgREST uses a query like to_jsonb()->'field'. To make filtering and ordering on those nested fields use an index, the index needs to be created on the same expression, including the to_jsonb(...) call
> 
> But I guess we failed to realize that `to_jsonb` is `STABLE`, not `IMMUTABLE`.
> 
> We might be able to tell whether a column is already `JSONB` and remove the `to_jsonb` in that case, when #2542 is done, because we'd have all the columns types in the schema cache already.

How likely is it that the fix mentioned here can be implemented soonish?
