### ISSUE TITLE
NOTIFY doesn't reload the catalog cache

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#2620]
This is a problem for [Automatic Schema Cache Reloading](https://postgrest.org/en/stable/schema_cache.html#automatic-schema-cache-reloading). Having:

```sql
-- add on test/spec/fixtures/schema.sql

create table test.cats(
  id uuid primary key,
  name text
);
grant all on table test.cats to postgrest_test_anonymous;

CREATE FUNCTION test.drop_change_cats() RETURNS void
LANGUAGE sql SECURITY DEFINER
AS $$
  drop table test.cats;
  create table test.cats(
    id bigint primary key,
    name text
  );
  grant all on table test.cats to postgrest_test_anonymous;
  notify pgrst, 'reload schema';
$$;
```

When dropping the table and then changing the `id` column type from `uuid` to `bigint`, the previous `uuid` type gets cached.

```bash
# $ PGRST_DB_POOL=1 PGRST_DB_ANON_ROLE='postgrest_test_anonymous' postgrest-with-postgresql-14 postgrest-run

curl 'localhost:3000/cats?id=eq.dea27321-f988-4a57-93e4-8eeb38f3cf1e'
[]

curl -X POST 'localhost:3000/rpc/drop_change_cats'

curl 'localhost:3000/cats?id=eq.1'

{"hint":null,"details":null,"code":"22P02","message":"invalid input syntax for type uuid: \"1\""}
```

When reestablishing the pg connections, the correct `bigint` type is now used.

```bash
kill -s SIGUSR1 $(pgrep -n postgrest) # SIGUSR1 reloads the schema cache + reloads the connections to pg

curl 'localhost:3000/cats?id=eq.1'
[]
```

According to [so link](https://dba.stackexchange.com/questions/232870/are-cataloge-and-relation-cache-in-postgresql-per-connection-or-global-to-the-se), the catalog gets cached per connection. So it makes sense that after a reconnection the cache gets cleared.

---

This has been happening since [v9.0.1](https://github.com/PostgREST/postgrest/releases/tag/v9.0.1), on [v9.0.0](https://github.com/PostgREST/postgrest/releases/tag/v9.0.0) the NOTIFY somehow reloads the catalog cache too.

On v9.0.1 and v10.0.0 the catalog cache gets reloaded if the connections reach the [db-pool-timeout](https://postgrest.org/en/stable/configuration.html#db-pool-timeout), which makes the issue less severe.

Since [v10.1.0](https://github.com/PostgREST/postgrest/releases/tag/v10.1.0) the issue worsens because the connections don't have a timeout. The catalog stays cached until a SIGUSR1 or a restart is done.

**Comment by nmauersberg** [comment]
I am experienting the same issue. Is there any way to restart the managed Supabase instance?

Thx for raising the issue.

**Comment by laurenceisla** [comment]
> This has been happening since [v9.0.1](https://github.com/PostgREST/postgrest/releases/tag/v9.0.1), on [v9.0.0](https://github.com/PostgREST/postgrest/releases/tag/v9.0.0) the NOTIFY somehow reloads the catalog cache too.

I tested this and found out that the v9.0.0 example works because it has the `db-prepared-statements` configuration set to `false`. After doing the same test in my local environment for version [v10.1.0](https://github.com/PostgREST/postgrest/releases/tag/v10.1.0) with that configuration, the request worked without throwing any error.

Looks like the nix environment has config set to true starting from v9.0.1.
