### ISSUE TITLE
DELETE with eq is deleting other entries as well?

### ISSUE THREAD

**Issue by nik736** [PostgREST/postgrest#2696]
### Environment
* PostgreSQL version: 14.5
* PostgREST version: 10.1.1
* Operating system: Ubuntu 22.04

### Description of issue
Data is being added to a table and when using GET to `?name=eq.xyz&order=time.desc&offset=2500` it returns for example 200 entries (there are 2700 overall). When using the same query params with a DELETE it deletes those 200 entries. Everything as expected... my issue now is that it also deletes entries from other names, apart from `xyz`. Even for names that don't even have 2500 entries yet, it feels completely random, sometimes it deletes 12, sometimes 40 entries, sometimes none. There is nothing else deleting those entries and I am super confused. Is there anything wrong with my equals statement? 

Please let me know if I can provide more details, I only receive the regular 204 status code from the DELETE response and an empty body, so I have a hard time debugging.

Thanks a lot for your help and work! :)

**Comment by steve-chavez** [comment]
`time` is not unique right? Can you share the table DDL?

So you're using limited deletions as documented here https://postgrest.org/en/stable/api.html#limited-updates-deletions, but for this you need to `order` on a unique column(s). IIRC, we had a safeguard for disallowing ordering on a non-unique column to prevent unexpected deletes.. but maybe that's not working in this case.

> my issue now is that it also deletes entries from other names, apart from xyz

Hm, this should definitely not happen. Perhaps you can check your [database logs](https://postgrest.org/en/stable/admin.html#database-logs) and share the generated query?

**Comment by nik736** [comment]
The time not unique, correct. For my use-case it's not super important if some entries more or less will be deleted.

DDL is:
```
CREATE TABLE logs (
    tag character varying,
    time timestamp without time zone,
    data jsonb
);
```

And the real requests are:
GET `/logs?tag=eq.xyz&order=time.desc&offset=2500`
DELETE `/logs?tag=eq.xyz&order=time.desc&offset=2500`

Thanks for the link to the database logs docs, I will check that out now and get back to you.

**Comment by nik736** [comment]
This is the log entry:
```
2023-03-06 18:26:35.539 UTC [2987761] pg@pg LOG:  execute 7: WITH pgrst_source AS (WITH pgrst_affected_rows AS (SELECT "public"."logs"."time" FROM "public"."logs" WHERE  "public"."logs"."tag" = $1 ORDER BY "public"."logs"."time" DESC  LIMIT ALL OFFSET $2) DELETE FROM "public"."logs" USING pgrst_affected_rows WHERE "public"."logs"."time" = "pgrst_affected_rows"."time" RETURNING 1) SELECT '' AS total_result_set, pg_catalog.count(_postgrest_t) AS page_total, array[]::text[] AS header, '' AS body, nullif(current_setting('response.headers', true), '') AS response_headers, nullif(current_setting('response.status', true), '') AS response_status FROM (SELECT * FROM pgrst_source) _postgrest_t
2023-03-06 18:26:35.539 UTC [2987761] pg@pg DETAIL:  parameters: $1 = 'xyz', $2 = '2500'
```

Is there anything looking unusual to you?

Thanks a lot :)
