### ISSUE TITLE
geojson structure: crs inside each feature instead on level type and features

### ISSUE THREAD

**Issue by BirGie123** [PostgREST/postgrest#2699]
Hello, 
we are using postgREST for crud functions on our ai-geodata.  

we saw that the geo+json header responses a featurecollection with coordinate reference systems (crs). 

the crs is in each feature instead outside the features. 

can you reproduce this behavior and if yes is it possible that the structure of the response is adjusted by you?

### Environment

* PostgreSQL version: 12
* PostgREST version: 10
* PostGIS version: 3.1 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
* Operating system: Kubernetes/Ubuntu20

#### request: 
`curl -X GET https://url.com//result_frame_field?run_uuid=eq.11341ed6-4713-c28c-0d70-d290032abd73 -H "Accept: application/geo+json"`

#### response:

`{"type" : "FeatureCollection", 
"features" : [{
"type": "Feature", 
"geometry": {"type":"Polygon",
"crs":{"type":"name","properties":{"name":"EPSG:25832"}},"coordinates":[[[489633.9,5888000],[489634.042248535,5887995.982175827],[489636.885974121,5887995.468318176],[489637.14420166,5887997.19841671],[489637.2,5888000],[489633.9,5888000]]]}, "properties": {"id": 321386, "run_uuid": "11341ed6-4713-c28c-0d70-d290032abd73", "confidence": 0.8387449445279349, "date": "2023-03-03T13:58:01+00:00", "path": null}}, {"type": "Feature", "geometry": {"type":"Polygon","crs":{"type":"name","properties":{"name":"EPSG:25832"}},"coordinates":[[[489999.9,5887952.3],[489998.616845703,5887949.44701233],[489998.868896484,5887949.294552612],[489997.822460938,5887946.764746094],[489998.847167969,5887945.881781006],[489999.085253906,5887944.549810791],[489999.283007812,5887946.699108886],[489999.9,5887949.4],[489999.9,5887952.3]]]}, "properties": {"id": 321387, "run_uuid": "11341ed6-4713-c28c-0d70-d290032abd73", "confidence": 0.5394721098729639, "date": "2023-03-03T13:58:01+00:00", "path": null}}]}`

#### request: 
`curl -X GET https://url.com//result_frame_field?run_uuid=eq.11341ed6-4713-c28c-0d70-d290032abd73 -H "Accept: application/geo+json"`

#### response:

`{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::25832" } },
"features": [
{ "type": "Feature", "properties": { "confidence": 0.53121434123160771, "date": "2023-02-23 13:55:18" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 484484.773486328136642, 5837965.500375365838408 ], [ 484484.663623046886642, 5837966.349154663272202 ], [ 484482.207666015601717, 5837966.085598754696548 ], [ 484482.021044921886642, 5837959.033425902947783 ], [ 484484.096777343773283, 5837959.141726684756577 ], [ 484484.203466796898283, 5837963.549407958984375 ], [ 484485.374707031238358, 5837963.609646606259048 ], [ 484485.315039062523283, 5837965.550259399227798 ], [ 484484.773486328136642, 5837965.500375365838408 ] ] ] }
 ]
}
`

in our own postgresql functions,  we do it with the json_build_object

`
json_build_object(
        'type',      'name', 
        'properties', json_build_object(
            'name', CONCAT('urn:ogc:def:crs:EPSG::',Find_SRID('SCHEMA', 'TABLE_NAME', 'GEOMETRY_COLUMN')) 
        )
    ) as crs
`

**Comment by laurenceisla** [comment]
PostgREST uses the output given by PostGIS's [ST_AsGeoJSON](https://postgis.net/docs/ST_AsGeoJSON.html),  as seen in these lines:

https://github.com/PostgREST/postgrest/blob/b05ea14122298d2b00c4f00b28efa0c36091966f/src/PostgREST/Query/SqlFragment.hs#L184-L185

This cannot be modified by the client, the only solution is to create a [custom function](https://postgrest.org/en/stable/api.html#stored-procedures) according to your needs that adds the `crs` example that you gave to the `FeatureCollection` object. Maybe you already use one, but if not, there's an [example in the docs](https://postgrest.org/en/stable/how-tos/working-with-postgresql-data-types.html#postgis) that could help, something like this (not tested):

```sql
create or replace function coverage_geo_collection() returns json as $$
  select
    json_build_object(
      'type', 'FeatureCollection',
      -- Adds the crs :
      'crs', json_build_object( 'type',      'name',  'properties', json_build_object( 'name', CONCAT('urn:ogc:def:crs:EPSG::',Find_SRID('SCHEMA', 'TABLE_NAME', 'GEOMETRY_COLUMN'))  ) ) ,
      'features', json_agg(
        -- You should modify this according to what you need
        json_build_object(
          'type', 'Feature',
          'geometry', st_AsGeoJSON(c.area)::json,
          'properties', json_build_object('id', c.id, 'name', c.name)
        )
      )
    )
  -- Your table:
  from coverage c;
$$ language sql;
```

**Comment by BirGie123** [comment]
hi, 
thank you for your reply. 

this is already integrated in our functions. 

When we use **table endpoints** and specify Accept: application/geo+json this structure is not delivered.

Currently postgREST sets crs in each feature and not on the top level of the featurecollection by postgREST in all table responses. 

[https://gist.github.com/sgillies/1233327](https://gist.github.com/sgillies/1233327)

_* The crs member should be on the top-level GeoJSON object in a hierarchy (in
  feature collection, feature, geometry order) and should not be repeated or
  overridden on children or grandchildren of the object._

### actual behavior

#### request:
`
curl -X GET https://url.com//TABLENAME?run_uuid=eq.11341ed6-4713-c28c-0d70-d290032abd73 -H "Accept: application/geo+json"`

#### response:

{"type" : "FeatureCollection",  
**INSIDE HERE**
"features" : [
{ "type": "Feature",  
"geometry": {"type":"Polygon", **INSTEAD OF "crs":{"type":"name","properties" :{"name":"EPSG:25832"}}**
,"coordinates":[[[489633.9,5888000],[489634.042248535,5887995.982175827],[489636.885974121,5887995.468318176],[489637.14420166,5887997.19841671],[489637.2,5888000],[489633.9,5888000]]]}, "properties": {"id": 321386, "run_uuid": "11341ed6-4713-c28c-0d70-d290032abd73", "confidence": 0.8387449445279349, "date": "2023-03-03T13:58:01+00:00", "path": null}},......
