### ISSUE TITLE
Sort by foreign column in 10.1.2

### ISSUE THREAD

**Issue by barbinbrad** [PostgREST/postgrest#2702]
### Environment

* PostgreSQL version: 14.1
* PostgREST version: 10.1.2
* Operating system: MacOS
* Supabase JS version: 2.10.0

### Description of issue

Hey! I believe there was an enhancement in 10.1.1 where we could sort columns by a foreign field like this: 

```tsx
// supabase js client query
query = query.order(`${table}(${column})`, {
   ascending,
});
```

After upgrading to 10.1.2, I get the following error:

```
error: {
  code: 'PGRST100',
  details: `unexpected '(' expecting letter, digit, "-", "->>", "->", delimiter (.), "," or end of input`,
  hint: null,
  message: '"failed to parse order (user(lastName).asc)" (line 1, column 5)'
}
```

Was there a breaking change? I know this was somewhat experimental when I heard about it.

**Comment by laurenceisla** [comment]
I think that feature was not launched on a stable release yet, only on pre-releases. The Changelog mentions that it's still Unreleased here: https://github.com/PostgREST/postgrest/blob/cae1c67b00d48f52b4273191d7661f3bc06bab0c/CHANGELOG.md?plain=1#L6-L11

**Comment by barbinbrad** [comment]
Thanks Laurence. I'll stick with my current version for now (that somehow supports it). The feature is excellent. Looking forward to the official release.
