### ISSUE TITLE
Allow reading configuration indirectly using SQL provided as configuration parameter(`pre-config` hook)

### ISSUE THREAD

**Issue by mkleczek** [PostgREST/postgrest#2703]
Currently configuration is read from authenticator role attributes. CREATEROLE privilege is needed to modify them.

It would be much more flexible to be able to configure an SQL query that PostgREST would use to retrieve configuration from the database.
That way some dynamic configuration scenarios might be supported (for example a list of schemas might be read from a table/view implementing a specific policy)

**Comment by steve-chavez** [comment]
Hmm, one issue is that the `authenticator` role would need privilege over tables and that would go against the design of our role system, see [here](https://postgrest.org/en/stable/auth.html).

I get the disadvantage of the CREATEROLE privilege though. What other alternatives do we have?

**Comment by mkleczek** [comment]
Maybe another configuration property with a role name to read the settings?

**Comment by steve-chavez** [comment]
Hmm, another option could be a SECURITY DEFINER function. That way the `authenticator` wouldn't need any privilege on a table, only the privilege to execute the function. By default the EXECUTE priv is public too.

**Comment by mkleczek** [comment]
Ok, so that goes back to the original idea: have a configuration parameter with a query to read configuration from the db and let the user configure the database roles with appropriate privileges (a query might be a SELECT from a SECURITY DEFINER function in particular). The feature is for advanced users and use cases anyway.

Some documentation with best practices would be a good idea.

**Comment by steve-chavez** [comment]
It'd be better to be restrictive in this case, so I was thinking just a function name on the configuration.

Another alternative could be that the function only does a bunch of 

```sql
SET LOCAL pgrst.db_anon_role TO ..
SET LOCAL pgrst.jwt_secret TO .. 
```

That way we don't need to agree upon a RETURN type on the function, plus we don't need any privilege on a table.

We also keep the code for the config more or less the same.

**Comment by mkleczek** [comment]
I am not really sure if it changes anything in terms of required privileges as the values of configuration parameters have to be read from somewhere so all necessary privileges to do that are required anyway.

I am not sure if restricting it to a function name is a good idea as it requires creating this function in the database (making it somewhat cumbersome).

I can imagine scenarios where one might want to perform a select on catalog views to expose schemas based on some criteria (ie. naming conventions and filtered by USAGE privileges).

**Comment by mkleczek** [comment]
I am not sure but I don't think you need any special privileges to execute for example:

`WITH RECURSIVE cte AS (
    SELECT oid FROM pg_roles WHERE rolname = CURRENT_USER
 
    UNION ALL
    SELECT m.roleid
    FROM  cte
               JOIN   pg_auth_members m ON m.member = cte.oid
),
roles AS (
    SELECT oid
          FROM cte -- oid & name
)
SELECT 'pgrst.db-schemas' as key, string_agg(nspname, ', ') as value FROM pg_namespace n where exists (select 1 from roles JOIN aclexplode(n.nspacl) a ON oid = a.grantee ) group by nspname;`

**Comment by mkleczek** [comment]
My main goal is really to be able to flexibly expose schemas as APIs. We have a shared database with fine grained ROLE structure.
We want to enable users to expose new APIs (schemas) via a single PostgREST instance.
Right now it requires SUPERUSER privilege to change db-schemas value. Changing via the file system is a no-go for us since PostgREST is deployed and managed in k8s cluster managed by the organisation.

So any solution that works only during start-up is not satisfactory for us: we need to be able to re-load the list of schemas and do it without SUPERUSER privileges.

**Comment by steve-chavez** [comment]
> I can imagine scenarios where one might want to perform a select on catalog views to expose schemas based on some criteria (ie. naming conventions and filtered by USAGE privileges).

That would still work with the function approach though. You can do your `SELECT * FROM pg_catalog... + SET LOCAL` inside.

> I am not sure but I don't think you need any special privileges to execute for example:

Yes, pg_catalog tables are public by default.

> So any solution that works only during start-up is not satisfactory for us: we need to be able to re-load the list of schemas and do it without SUPERUSER privileges.

Besides from start-up, re-reading from the `pre-config` function would be possible with a `NOTIFY pgrst, 'reload config'`.

> Requirement to create a dedicated database object for this purpose makes it unnecessarily complicated to deploy the solution in different environments.
> I think we can expect PostgREST users to create a function to return stuff like this. After all... they are required to create a lot of database objects to get any api in the first place.

Yeah, as Wolfgang said, you'd still need to create the API roles right? Creating a function is not that different from that.

---

Additionally, I want to point out that the SUPERUSER requirement for ROLE/DB gucs will be lifted on PostgreSQL 16: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=096dd80f3ccc103c8e078fca05e6ccfb2071aa91.

---

> Agreed, that sounds good to me. Kind of like a pre-config hook, similar to regular pre-request hooks.

Yeah, I like it as well and it actually solves the SUPERUSER thing for GUCs. Also agree on the `pre-config` name.

> This also reminds me of https://github.com/PostgREST/postgrest/issues/1727#issuecomment-755956423. It's kind of a more generic version of the suggested db-password-command there, but for in-database config.

Interesting, and if the db has [pgsql-http](https://github.com/pramsey/pgsql-http/) that work could even be plain SQL I believe.

**Comment by steve-chavez** [comment]
> We could potentially have something like a more generic config-command equivalent, too, to run an arbitrary shell command returning a dynamic configuration on each reload.

That also seems like it could solve the issue here. Sounds like a good idea.

**Comment by mkleczek** [comment]
> > I can imagine scenarios where one might want to perform a select on catalog views to expose schemas based on some criteria (ie. naming conventions and filtered by USAGE privileges).
> 
> That would still work with the function approach though. You can do your `SELECT * FROM pg_catalog... + SET LOCAL` inside.
> 

But it would require setting up the database (ie. creating the function) to deploy PostgREST. I would like to avoid that as it opens a can of worms (ie. managing the db setup scripts / migrations etc.)

The goal is to treat PostgREST as infrastructure component that is deployed once and "just works". Application/schema maintainers would deploy whatever changes to the db they want (they are responsible for setting up roles and access rights) and expose schemas by just sending the reload config notification.

> > I am not sure but I don't think you need any special privileges to execute for example:
> 
> Yes, pg_catalog tables are public by default.
> 
> > So any solution that works only during start-up is not satisfactory for us: we need to be able to re-load the list of schemas and do it without SUPERUSER privileges.
> 
> Besides from start-up, re-reading from the `pre-config` function would be possible with a `NOTIFY pgrst, 'reload config'`.
> 
> > Requirement to create a dedicated database object for this purpose makes it unnecessarily complicated to deploy the solution in different environments.
> > I think we can expect PostgREST users to create a function to return stuff like this. After all... they are required to create a lot of database objects to get any api in the first place.
> 
> Yeah, as Wolfgang said, you'd still need to create the API roles right? Creating a function is not that different from that.

See above: there are application maintainers that are responsible for setting up their own application specific roles and granting them to PostgREST user.

So no: there is no PostgREST specific roles setup step.

**Comment by mkleczek** [comment]
> > See above: there are application maintainers that are responsible for setting up their own application specific roles and granting them to PostgREST user.
> 
> This might be true for the roles that the authenticator role will finally `SET ROLE` to - but it's not true for the authenticator role itself. You, who deploys PostgREST, need to set up this role, because you need it to configure the PostgREST instance properly to connect to the database in the first place.

Well obviously there is some unavoidable setup necessary (you have to install PostgreSQL, create the database, create an account for the application to use etc.) - the point is
* to have the compulsory and non-reloadable part of the configuration as minimal as possible and requiring as few PostgREST specific steps as possible (ie. creating a db and an application user is fairly common for all db applications)
* to make it possible to flexibly delegate management of other parts of configuration

**Comment by steve-chavez** [comment]
> My main goal is really to be able to flexibly expose schemas as APIs. We have a shared database with fine grained ROLE structure. We want to enable users to expose new APIs (schemas) via a single PostgREST instance.

@mkleczek I think #2783 might solve your original issue. Let me know what you think there.

---

Will proceed here with the `pre-config` hook. It will also allow for better testing(on https://github.com/PostgREST/postgrest/issues/2791 I need to introduce a delay on the schema cache process).
