### ISSUE TITLE
Can't embed with materialized view on the way

### ISSUE THREAD

**Issue by coyoteazul** [PostgREST/postgrest#2712]
### Environment

* PostgreSQL version: 15.2-1.pgdg110+1. Docker postgres:latest. 3b6645d2c145
* PostgREST version: 10.0.0. Docker postgrest/postgrest:latest. f7c1ab38195f
* Operating system: Win 10

### Description of issue

I expected to be able to embed a materialized view that's reached through a view that's used to apply RLS. However the response is

```json
{
	"code": "PGRST200",
	"details": "Searched for a foreign key relationship between 'sales' and 'users' in the schema 'api', but no matches were found.",
	"hint": null,
	"message": "Could not find a relationship between 'sales' and 'users' in the schema cache"
}
```

If I replace the view's definition with the materialized view's definition then I can embed the view correctly, but I lose the performance from using materialized views

Steps to reproduce: 

```sql
create schema back;
create schema api;

create table back.global_user (
    id_global_user int primary key generated always as identity,
    username text
);
create table back.tenant (
    id_tenant int primary key generated always as identity,
    descr text
);
create table back.internal_user (
    id_tenant int references back.tenant(id_tenant),
    id_user int generated always as identity,
    id_global_user int references back.global_user(id_global_user),
    primary key (id_tenant, id_user),
    unique (id_tenant, id_global_user)
);
create materialized view back.int_usr_w_name as
    select *
    from back.internal_user
    inner join back.global_user
    using (id_global_user);
create or replace view api.users as
    select *
    from back.int_usr_w_name
    where id_tenant = 1; /*in reality this value is read from JWT*/
create table api.sales (
    id_tenant int references back.tenant(id_tenant),
    id_sale int generated always as identity,
    amount decimal,
    id_user int,
    primary key (id_tenant, id_sale),
    foreign key (id_tenant, id_user) references back.internal_user(id_tenant, id_user)
);

insert into back.global_user(username)
values ('Homer'), ('Marge');
insert into back.tenant(descr)
values ('T1'), ('T2');
insert into back.internal_user (id_tenant, id_global_user)
values (1,1),(1,2),(2,1),(2,2);
refresh materialized view back.int_usr_w_name;
insert into api.sales(id_tenant, amount, id_user)
values (1,100, 1);

grant usage on schema api to web_anon;
grant select on table api.sales to web_anon;
grant select on api.users to web_anon;
```

the request is 

```http
GET /sales?select=*,users(*)
```

**Comment by laurence-isla** [comment]
Verify that the schema is added to the [`db-extra-search-path`](https://postgrest.org/en/latest/configuration.html#db-extra-search-path) configuration setting. In docker, add the env variable `PGRST_DB_EXTRA_SEARCH_PATH="back"`.

**Comment by coyoteazul** [comment]
I didn't expect this to work, but it did.
It's strange. Since I was qualifying my schemas it should work without needing to add "back" to search-path. In fact my sql client doesn't need me to.

select * from sales inner join users using (id_tenant, id_user); 
works perfectly with only "api" on search-path

I guess it's a quirk with postgrest that I'll have to remember.
Thanks!
