### ISSUE TITLE
Order by random()

### ISSUE THREAD

**Issue by mitjans** [PostgREST/postgrest#2721]
### Description of issue

Why is it not possible to retreive data randomly using PosgtREST? What are the limitations?

```bash
/documents?select=*&order=random()&limit=1'

{
  "code": "PGRST100",
  "details": "unexpected '(' expecting letter, digit, \"-\", \"->>\", \"->\", delimiter (.), \",\" or end of input",
  "hint": null,
  "message": "\"failed to parse order (random())\" (line 1, column 7)"
}
```

**Comment by TomasHubelbauer** [comment]
@steve-chavez I landed here from the original issue. That repository is now archived. Perhaps this one should be re-opened? Unless it is clear that ordering by random won't be supported in a special way and users should provide their own views/RPCs. However I think random is special enough to have pure PostgREST support without having to do anything on the DB level. WDYT?
