### ISSUE TITLE
v11: Cannot start PostgREST: throws "permission denied for schema <schema>" repeatedly

### ISSUE THREAD

**Issue by laurenceisla** [PostgREST/postgrest#2762]
### Environment

* PostgreSQL version: v14.0
* PostgREST version: v11.0
* Operating system: NixOS

### Description of issue

Using the basic configuration in the docs:

```sql
create schema api;

create role web_anon nologin;
grant usage on schema api to web_anon;

create role authenticator noinherit login password 'mysecretpassword';
grant web_anon to authenticator;
```

```yaml
db-uri = "postgres://authenticator:mysecretpassword@localhost:5432/postgres"
db-schemas = "api"
db-anon-role = "web_anon"
```

Running the binary for version 11.0.0 returns an error that repeats in a loop:

```log
20/Apr/2023:11:59:37 -0500: Attempting to connect to the database...
20/Apr/2023:11:59:37 -0500: Connection successful
20/Apr/2023:11:59:37 -0500: Config reloaded
20/Apr/2023:11:59:37 -0500: An error ocurred when loading the schema cache
20/Apr/2023:11:59:37 -0500: {"code":"42501","details":null,"hint":null,"message":"permission denied for schema api"}
...
```

Doing a

```sql
grant usage on schema api to authenticator;
```

makes it run, but this permission mustn't be given.

The configuration works OK for older releases and breaks since this commit: https://github.com/PostgREST/postgrest/commit/3e53796120513d5fa560c59f1f4d393d957f108e

---

~~To test it in an development environment, save the SQL script mentioned above in a file e.g. `schema.sql`, then run:~~

```bash
PGRST_DB_SCHEMAS='api' PGRST_DB_URI='postgres://authenticator:mysecretpassword@localhost:5432/postgres' PGRST_DB_ANON_ROLE='web_anon' postgrest-with-postgresql-14 -f schema.sql postgrest-run
```

**Comment by steve-chavez** [comment]
> PGRST_DB_SCHEMAS='api' PGRST_DB_URI='postgres://authenticator:mysecretpassword@localhost:5432/postgres' PGRST_DB_ANON_ROLE='web_anon' postgrest-with-postgresql-14 -f schema.sql postgrest-run

When trying the above I get:

```
24/Apr/2023:17:37:45 -0500: Attempting to connect to the database...
24/Apr/2023:17:37:45 -0500: {"code":"PGRST000","details":"connection to server at \"localhost\" (::1), port 5432 failed: FATAL:  password authentication failed for user \"authenticator\"\nconn
ection to server at \"localhost\" (::1), port 5432 failed: FATAL:  password authentication failed for user \"authenticator\"\n","hint":null,"message":"Database connection error. Retrying the c
onnection."}
24/Apr/2023:17:37:45 -0500: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "authenticator"
connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "authenticator"
```

**Comment by laurenceisla** [comment]
> That must be connecting to your local database.

True.  I cannot find a way to reproduce it in the development environment. Starting a new PostgREST 11.0 using the socket and the `authenticator` user works, but it does not throw the error.

**Comment by steve-chavez** [comment]
Can't reproduce this even on a local database. I'm not sure if there's any bug here.

**Comment by steve-chavez** [comment]
Wait.. I was testing this on the `public` schema, which is special. I can reproduce on another schema.

The problem is the `pg_get_serial_sequence` func(introduced on https://github.com/PostgREST/postgrest/commit/3e53796120513d5fa560c59f1f4d393d957f108e):

```sql
create schema api;
create table foos(id bigint generated by default as identity);
select pg_get_serial_sequence('foos', 'id');

 pg_get_serial_sequence
------------------------
 api.foos_id_seq

create role authenticator noinherit;

begin;
set local role authenticator;
select pg_get_serial_sequence('api.foos', 'id');
ERROR:  permission denied for schema api
```

https://www.postgresql.org/docs/current/functions-info.html

> (This function probably should have been called pg_get_owned_sequence; its current name reflects the fact that it has historically been used with serial-type columns.) 

Seems the function requires ownership for it to run?

**Comment by steve-chavez** [comment]
I built this query to not depend on `pg_get_serial_sequence`:

```sql
select
  seqclass.relname
from pg_attribute a
join pg_depend dep
  on dep.refobjid = a.attrelid and dep.refobjsubid = a.attnum
join pg_sequence seq
  on seq.seqrelid = dep.objid
join pg_class seqclass
  on seqclass.oid = seq.seqrelid
where
  a.attrelid = 'test.channels'::regclass;

     relname
-----------------
 channels_id_seq
```

However when executing it under `authenticator`, it failed the same:

```sql
select
  seqclass.relname
from pg_attribute a
join pg_depend dep
  on dep.refobjid = a.attrelid and dep.refobjsubid = a.attnum
join pg_sequence seq
  on seq.seqrelid = dep.objid
join pg_class seqclass
  on seqclass.oid = seq.seqrelid
where
  a.attrelid = 'test.channels'::regclass;
ERROR:  permission denied for schema test
LINE 11:   a.attrelid = 'test.channels'::regclass;
```

So looks like the regclass casting is the issue, as it requires privileges:

```sql
select 'test.channels'::regclass;
ERROR:  permission denied for schema test
LINE 1: select 'test.channels'::regclass;
```
