### ISSUE TITLE
Add a HTML table response type

### ISSUE THREAD

**Issue by saolof** [PostgREST/postgrest#2763]
With [HTMX](https://htmx.org/) making HATEOAS RESTful endpoints that return data as HTML a bit more mainstream, I personally often wish that postgrest had a way to make lists return a sequence of lines with each line wrapped in a <tr> and each field in a <td> tag. It is a fairly simple string substitution, but it would be a nice quality of life improvement to have postgrest do it.

This is mainly useful for implementing something like [this example](https://htmx.org/examples/active-search/) without any need to write any actual code outside of the database and the HTML, without needing any CRUD backend other than postgrest. With that said, this is something that already can be done now from a JSON response by pulling in the htmx client-side-templates extension and using a mustache template that iterates over a top level array, so this would be more of a quality of life improvement.

**Comment by steve-chavez** [comment]
Yes, we're working on returning different media types(like HTML) on https://github.com/PostgREST/postgrest/pull/1582. I'm making this a priority for the next release.

I've also long wanted to use HTMX and in general want to simplify the frontend stack.

**Comment by steve-chavez** [comment]
@saolof There's now a how-to for HTMX! https://postgrest.org/en/latest/how-tos/providing-html-content-using-htmx.html

Let us know if you have any feedback on how to improve the integration.
