### ISSUE TITLE
`Server-Timing` response header

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#2771]
## Problem

Currently there's no way to debug the time we take to parse the request and the time we take to receive the query response. The [EXPLAIN execution plan](https://postgrest.org/en/stable/api.html#execution-plan), only obtains the query time, but not the aforementioned two.

## Solution

Add the standard `Server-Timing` header. This can communicate all types of metrics for a given request-response cycle. 

An example response would be like:

```http
GET /projects?id=eq.3

Server-Timing: jwt;dur=34, app;dur=47.2, db;dur=53, render;dur=15
```

Which would mean the jwt ("jwt") decoding time was 34 ms, the parsing + planning("app") took 47.2ms, the database ("db") query time was 53 ms, and we took 15 ms to obtain the query response("render", this is relevant to https://github.com/PostgREST/postgrest/issues/2770).

To avoid doing this work for all the requests:

- We can add `Server-Timing` whenever the `Prefer: server-timing=include` header is specified.
- Or enable it whenever [db-plan-enabled](https://postgrest.org/en/stable/configuration.html#db-plan-enabled) is turned on.

References:

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing
- https://www.w3.org/TR/server-timing/

**Comment by steve-chavez** [comment]
Seems this might be simple with the timeit package: https://hackage.haskell.org/package/timeit-1.0.0.0/docs/System-TimeIt.html. Since the functions are [so small](https://hackage.haskell.org/package/timeit-1.0.0.0/docs/src/System-TimeIt.html#timeItT) we could also vendor the functionality.

Got that from this blog post: https://chrisdone.com/posts/measuring-duration-in-haskell/

**Comment by steve-chavez** [comment]
If parsing(parsec) time is high, we can look into switching to https://github.com/AndrasKovacs/flatparse

**Comment by steve-chavez** [comment]
Though the implementation might be simple with [timeit](https://hackage.haskell.org/package/timeit-1.0.0.0/docs/System-TimeIt.html), doing this in the current codebase would be repetitive:

```hs
     (ActionRead headersOnly, TargetIdent identifier) -> do 
       wrPlan <- liftEither $ Plan.wrappedReadPlan identifier conf sCache apiReq 
       -- timeit
       resultSet <- runQuery roleIsoLvl (Plan.wrTxMode wrPlan) $ Query.readQuery wrPlan conf apiReq 
      -- timeit
       return $ Response.readResponse headersOnly identifier apiReq resultSet 
  
     (ActionMutate MutationCreate, TargetIdent identifier) -> do 
       mrPlan <- liftEither $ Plan.mutateReadPlan MutationCreate apiReq identifier conf sCache
       -- timeit 
       resultSet <- runQuery roleIsoLvl (Plan.mrTxMode mrPlan) $ Query.createQuery mrPlan apiReq conf 
       -- timeit
       return $ Response.createResponse identifier mrPlan apiReq resultSet 
```

([ref](https://github.com/PostgREST/postgrest/blob/531a183b44b36614224fda432335cdaa356b4a0a/src/PostgREST/App.hs#L168-L226))

So this would require refactoring. Basically have a single function exposed on the Plan and Query modules.

**Comment by taimoorzaeem** [comment]
@steve-chavez @laurenceisla  I have sort of implemented the `Server-Timing` but I am not sure how to test it. FYI, to test this feature I need to enable configurations like `db-plan-enabled` and `jwt-caching`. Would the test belong to spec-tests or io-tests? I am confused because matching headers seems to belong to spec tests but setting up configurations seem to belong to io-tests.

**Comment by steve-chavez** [comment]
@taimoorzaeem I think it should be fine as a spec test, there are some examples here where we use different configs for each spec:

https://github.com/PostgREST/postgrest/blob/531a183b44b36614224fda432335cdaa356b4a0a/test/spec/Main.hs#L91-L265

**Comment by taimoorzaeem** [comment]
@steve-chavez Hmm, how exactly is it going to work with `render`. If the response is generated, how could I add the `render;dur=` to the already generated response?
```haskell
(dur, resp) <- timeItT $ Response.createResponse identifier mrPlan apiReq resultSet
-- How do I add this "dur" back to "resp"?
```

**Comment by taimoorzaeem** [comment]
> the database ("db") query time was 53 ms, and we took 15 ms to obtain the query response("render", this is relevant to https://github.com/PostgREST/postgrest/issues/2770.

@steve-chavez What exactly is the difference between `db` and `render`. If I understand correctly, `db` time refers to time it took to run the query and `render` refers to the time it took `hasql decoders` to represent the query result into JSON?

**Comment by steve-chavez** [comment]
@taimoorzaeem Yes, that was the idea. To be clear maybe we can name that duration `decode` instead of `render`.

Btw, since you need this for the jwt caching feat, adding only the jwt duration to `server-timing` would be fine. We can add other durations later.

**Comment by steve-chavez** [comment]
According to the following blog post, there is a nice browser integration for server timing.

https://www.smashingmagazine.com/2018/10/performance-server-timing/

A couple of things caught my attention.

> Server Timing itself adds very minimal overhead to the HTTP response sent back over the wire. The header is very minimal and is generally safe to be sending without worrying about targeting to only internal users
https://www.smashingmagazine.com/2018/10/performance-server-timing/#considerations

TBD We could enable server timing without `db-plan-enabled` but only for authenticated users.

> The only property that is required is name. Both dur and desc are optional, and can be used optionally where required. For example, if you needed to debug a timing problem that was happening on one server or data center and not another, it might be useful to add that information into the response without an associated timing.
> Server-Timing: datacenter;desc="East coast data center", db;dur=123;desc="Database", tmpl;dur=56;desc="Template processing”

TBD We could have an initial description like `server;desc="PostgREST'`. This in case our durations conflict with another server that also exposes `Server-Timing`. I'm assuming this `desc` allows us to namespace the durations, haven't tried it.

---

There's also a JS integration: https://developer.mozilla.org/en-US/docs/Web/API/PerformanceServerTiming

Also note:

> The Server-Timing header may expose potentially sensitive application and infrastructure information. Consider to control which metrics are returned when and to whom on the server side. For example, you could only show metrics to authenticated users and nothing to the public.
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing

**Comment by develop7** [comment]
> TBD We could have an initial description like `server;desc="PostgREST'`. This in case our durations conflict with another server that also exposes `Server-Timing`. I'm assuming this `desc` allows us to namespace the durations, haven't tried it.

Doesn't look that way — the `desc` seems to be consumed by client verbatim. Moreover, it seems like we could have as many equally-named timings as we please, hence it's likely our job to make them stand out.

**Comment by develop7** [comment]
> Doing this for `app`, `db`, `render` in the current codebase would be repetitive:
 
_[…skip…]_
 
Right now, after #2971 got merged, the code looks bit better:

https://github.com/PostgREST/postgrest/blob/4c44782d15c66917af3a108693cd725a4a01dcef/src/PostgREST/App.hs#L175-L229

Still repetitive, but, uh, more uniform. All I can think of factoring out without introducing extra indirection is `return $ pgrstResponse pgrst`, which isn't making it awful lot better.

On the other hand, actually delivering metrics for  `plan`, `query`, `render` and `jwt` right now seems to be the matter of wrapping respective calls with `timeItT`, like this:

```haskell
-- ...skip...
handleRequest AuthResult{..} conf appState authenticated prepared pgVer apiReq@ApiRequest{..} sCache serverTimingParams =
  case (iAction, iTarget) of
    (ActionRead headersOnly, TargetIdent identifier) -> do
      (planTime, wrPlan) <- timeItT $ liftEither $ Plan.wrappedReadPlan identifier conf sCache apiReq
      (rsTime, resultSet) <- timeItT $ runQuery roleIsoLvl (Plan.wrTxMode wrPlan) $ Query.readQuery wrPlan conf apiReq
      (renderTime, pgrst) <- timeItT $ liftEither $ Response.readResponse wrPlan headersOnly identifier apiReq resultSet serverTimingParams
     -- ...skip...
```

Well, there's rendering timings, but the goal at hand is still close.

**Comment by steve-chavez** [comment]
> Still repetitive, but, uh, more uniform.

On a previous discussion we had the idea to have App do the IO and make the other modules pure, then have a single entrypoint for each module instead of having `handleRequest` in App.

Note: previous discussion was [here](https://github.com/PostgREST/postgrest/pull/1831#pullrequestreview-649406561) and is part of this [big issue](https://github.com/PostgREST/postgrest/issues/1804).

> On the other hand, actually delivering metrics for plan, query, render and jwt right now seems to be the matter of wrapping respective calls with timeItT, like this:

Yeah, so it can be done with some duplication but it'd be cleaner with the refactor. That being said, implementing without being DRY should be fine. We can refactor it later.
