### ISSUE TITLE
spread embeds for m2m queries

### ISSUE THREAD

**Issue by sroboubi** [PostgREST/postgrest#2775]
### Environment

* PostgreSQL version: 14 (not relevant)
* PostgREST version: https://github.com/PostgREST/postgrest/releases/tag/v10.1.2
* Operating system: windows (not relevant)

### Description of issue

I basically have the problem described in https://github.com/PostgREST/postgrest/issues/1907
I tried using the spread operator as per https://github.com/PostgREST/postgrest/pull/2564 and that _seems_ to work well but:

1. it's not documented so I'm not really sure what I'm doing other than following the example. Will there be any documentation describing how it works?
2. can I do queries that filter posters using attributes of their subscribers and/or subscriptions, or sort by those attributes, etc. 
3. can I use the spread operator for non-recursive m2m relations?

**Comment by steve-chavez** [comment]
@sroboubi There are docs now.

1) https://postgrest.org/en/latest/references/api/resource_embedding.html#recursive-many-to-many-disambiguation
3) Yes, https://postgrest.org/en/latest/references/api/resource_embedding.html#spread-embed
