### ISSUE TITLE
Not able to use role via JWT token for GET call

### ISSUE THREAD

**Issue by krishnaglodha** [PostgREST/postgrest#2779]
### Environment

* PostgreSQL version: (if using docker, specify the image)
PostgreSQL 14.7 (Homebrew) on x86_64-apple-darwin22.1.0, compiled by Apple clang version 14.0.0 (clang-1400.0.29.202), 64-bit

* PostgREST version: (if using docker, specify the image)
v11.0.1
* Operating system:
MacOS Ventura 13.3.1 (a) 

### Description of issue

I have create one public_role which is working fine when I have assigned it as `db-anon-role` , now I have created one more public user `second_role`  with only few table access. 

```
create role second_role nologin;
grant usage on schema public to second_role;
grant select on cars to second_role;
```

I have created JWT token by using this role and `jwt-secret` which I have also added in config file. 
<img width="942" alt="Screenshot 2023-05-10 at 10 15 08 AM" src="https://github.com/PostgREST/postgrest/assets/47075664/84bc106f-7442-4ddc-8c20-3687e9845d2a">

When I hit GET call with table name and this token in header, I'm getting following error
 
```
{
    "code": "42501",
    "details": null,
    "hint": null,
    "message": "permission denied to set role \"second_role\""
}
```

(Expected behavior vs actual behavior)

After passing token, it should use that role to make decision whether the data of that table is accessible to the role or not.

**Comment by steve-chavez** [comment]
You need to do

```sql
grant second_role to authenticator
```

See https://postgrest.org/en/stable/references/auth.html#jwt-based-user-impersonation
