### ISSUE TITLE
Add messagepack return type

### ISSUE THREAD

**Issue by saolof** [PostgREST/postgrest#2787]
Messagepack is a json-isomorphic binary serialization format that is becoming fairly widely supported and which supports fast streaming serialization/deserialization. It would be neat to have it as a return format. Both in JSON like form, and in a header + stream of tuples form for returning large numerical data sets like timeseries.

**Comment by steve-chavez** [comment]
msgpack was discussed here before: https://github.com/PostgREST/postgrest/issues/1548

https://github.com/PostgREST/postgrest/pull/1582 is still looking like the way forward

**Comment by steve-chavez** [comment]
Yes, there's https://github.com/patriksimek/msgpack-postgres

**Comment by steve-chavez** [comment]
Yeah, should be possible like:

```sql
create domain "application/x-msgpack" as bytea;

create or replace function hello() returns "application/x-msgpack" as $$
  select msgpack_encode('{"hello": "world"}'::jsonb);
$$ language sql;
```

Using the extension https://github.com/patriksimek/msgpack-postgres.
