### ISSUE TITLE
`Prefer: timezone` header

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#2799]
## Problem

No current easy way to change the timezone unless you create new roles:

```sql
alter role la_customers set time zone 'America/Los_Angeles';
```

([Ref](https://github.com/orgs/supabase/discussions/14363))

## Solution

**Edit**: `Prefer: timezone` would be better as mentioned on https://github.com/PostgREST/postgrest/issues/2799#issuecomment-1745835316

Use the `Accept-Timezone: America/Los_Angeles` to change the timezone. 

The implementation is easy as pg does all the work. Just get the header and:

```sql
begin;
set local time zone 'America/Los_Angeles';
```

Reject with a `406 Not Acceptable` if the timezone is not applicable.

## Notes

The `Accept-Timezone` is not standard. Its inclusion has been debated for a long time:

> You are suggesting that this be sent on every HTTP request? Is that correct?
> If you multiply 46 bytes (the line above) up by the number of HTTP
> requests issued across the web every day (billions? trillions?), you can
> imagine how much more data transfer this proposal would require.

https://groups.google.com/g/mozilla.dev.platform/c/hyQQbC3OC-I

That might not be a concern for us...

Alternatively we can use a custom `X-Timezone`  header.

**Comment by steve-chavez** [comment]
This is similar to Accept-Charset: https://github.com/PostgREST/postgrest/issues/1371

Would these prevent the implementation of https://github.com/PostgREST/postgrest/issues/2816? Hm, maybe not if we cache the `set locals` query differently.

Also, I'm not sure if every user would want this. So I'm thinking we should enable both these features with a config option.

**Comment by michelp** [comment]
Agreed this could be useful, not setting the header would default to the system default timezone as specified in postgresql.conf.  Note that this is usually set at the session level, so agree that it should be `SET LOCAL` to avoid session based connection pooler issues.

**Comment by steve-chavez** [comment]
I'm still wary about the non-determinism this feature would introduce. So it should be optional.

If the `authenticator` is explicitly set to a default timezone:

```sql
alter role authenticator
set timezone to 'default';
```

Only then we should apply the header timezone. If there's no explicit default timezone set then the header timezone is a noop.

This way we'll not override a system default timezone like `utc` and the user can still set a custom timezone like `Europe/Berlin` on the `authenticator` which will be left untouched.

**Comment by taimoorzaeem** [comment]
@steve-chavez I would like to summarize this feature as far as I understand it:

- Add new request header `X-Timezone`
- Only apply this header if `current_setting("timezone", true)` is not null, i.e it is set to some default timezone.
- Add a boolean config to enable this feature, say `allow-timezone-change`?
- Reject with `406 Not Acceptable` if not a valid timezone.

Some concerns with this feature:

- Checking the allowed time zones would be a lookup on `pg_timezone_names` (**1196 rows**) and `pg_timezone_abbrevs` (**196 rows**) which might affect performance (both abbrevs and names can be used to set timezone (see [pg_timezone_names](https://www.postgresql.org/docs/15/view-pg-timezone-names.html))
-  It is mentioned [here](https://stackoverflow.com/questions/6663765/postgres-default-timezone#comment67631116_32009497) that `SELECT pg_reload_conf()` is required to change the timezone. Would that be needed here too?

**Comment by steve-chavez** [comment]
> Only apply this header if current_setting("timezone", true) is not null, i.e it is set to some default timezone.
> Add a boolean config to enable this feature, say allow-timezone-change?

@taimoorzaeem Let's only use a config for this, seems easier to understand. I think `db-allow-timezone-change`, true by default.

> Add new request header X-Timezone

`Accept-Timezone` looks clearer.

> It is mentioned [here](https://stackoverflow.com/questions/6663765/postgres-default-timezone#comment67631116_32009497) that SELECT pg_reload_conf() is required to change the timezone. Would that be needed here too?

Shouldn't be necessary, look:

```sql
postgres=# begin;
postgres=# select now();
             now              
------------------------------
 2023-09-12 22:18:48.06979-03
(1 row)

postgres=# set local time zone 'America/Los_Angeles';
SET
postgres=# select now();
              now              
-------------------------------
 2023-09-12 18:18:50.203043-07
```
The setting applies immediately.

> Checking the allowed time zones would be a lookup on pg_timezone_names (1196 rows) and pg_timezone_abbrevs (196 rows) which might affect performance (both abbrevs and names can be used to set timezone (see [pg_timezone_names](https://www.postgresql.org/docs/15/view-pg-timezone-names.html))

Hm, to keep it simple we can fail at runtime:

```sql
postgres=*#              
set local time zone 'America/XXX';
ERROR:  invalid value for parameter "TimeZone": "America/XXX"
```

Then we would need to catch the error and respond with `406`. No need to query all the timezones.

**Comment by steve-chavez** [comment]
How about if we use a strict preference (recently added on https://github.com/PostgREST/postgrest/pull/2969) for this. So instead this header would have to be specified:

```http
Prefer: handling=strict, timezone=America/Los_Angeles`
```

This way we can give an error to the client.

Implementing a `lenient` alternative, is a bit harder but can be done.

> Checking the allowed time zones would be a lookup on pg_timezone_names (1196 rows) and pg_timezone_abbrevs (196 rows) which might affect performance (both abbrevs and names can be used to set timezone (see [pg_timezone_names](https://www.postgresql.org/docs/15/view-pg-timezone-names.html))

We would have to cache the `pg_timezone_names`, `pg_timezone_abbrevs` shouldn't be necessary (you can't do `set local timezone to 'Z'`). If a timezone doesn't exist, we don't err but use the default timezone (by querying `select current_setting('timezone', false);`).

This would give the following advantages:

- We don't introduce a non-standard header.
- We don't need a special config for this case, no `db-allow-timezone-change`. Instead we can resort to a single preferences config (https://github.com/PostgREST/postgrest/issues/2987)
- We don't use pg connections in case of client errors.

---

@taimoorzaeem If you're already working on this, the config can be left out for now. Only the header + logic would need to be added.

Also, we already have some cached settings. We do this for [impersonated role settings](https://postgrest.org/en/stable/references/auth.html#impersonated-role-settings).

https://github.com/PostgREST/postgrest/blob/55e43bf6c83892ff7d4dad4c3c8c03e5ad2fa797/src/PostgREST/Config/Database.hs#L30

**Comment by taimoorzaeem** [comment]
> Also, we already have some cached settings. We do this for [impersonated role settings](https://postgrest.org/en/stable/references/auth.html#impersonated-role-settings).

The `RoleSettings` and `DbSettings` are cached and stored in the `AppConfig`. Should I do the same with timezone names as `:: [Text]`?
