### ISSUE TITLE
Null filtering on Embedded Resources bug

### ISSUE THREAD

**Issue by Etwenn** [PostgREST/postgrest#2800]
### Environment

* PostgreSQL version: 14
* PostgREST version: [11.0.1](https://github.com/PostgREST/postgrest/releases/tag/v11.0.1)
* Operating system: Windows

### Description of issue

Trying to use new feature : [Null filtering on Embedded Resources](https://postgrest.org/en/stable/references/api/resource_embedding.html#null-filtering-on-embedded-resources)

Table & Data : 

Table1 : 
| row | FieldA  | Table2(FieldB) -> foreign key to Table2 |
|-|--------|--------|
|1| valueA1 | valueB1 |
|2| valueA2 | valueB2| 

Table2
| row| FieldB | FieldC | FieldD|
|-|--------|--------|--------|
|1| valueB1 | valueC1 | valueD1|
|2| valueB2 | ValueC2 | NULL| 

doing : 
`GET /table1?select=*,table2(*)&table2=not.is.null`

Result : 

```json
[
    {
        "FieldA": "valueA1",
        "Table2": {
            "FieldB": "valueB1",
            "FieldC": "valueC1",
            "FieldD": "valueD1"
        }
    }
]
```

expected : 

```json
[
    {
        "FieldA": "valueA1",
        "Table2": {
            "FieldB": "valueB1",
            "FieldC": "valueC1",
            "FieldD": "valueD1"
        }
    },
    {
        "FieldA": "valueA2",
        "Table2": {
            "FieldB": "valueB2",
            "FieldC": "valueC2",
            "FieldD": NULL
        }
    }
]
```

I'm not getting the second row because FieldD is null 

it seems to be a problem from the postgresql's request,
 here the one i got through the log : (simplified)

```sql
select * table1
left join lateral (
	select * from table2
	where id = table1.table2_id ) as "table1_table2_id" on true
where "table1_table2_id" is not null

```

Any idea how i could get a workaround ? 

any idea how i could bypass this problem ?

**Comment by laurenceisla** [comment]
It looks like a bug. Here's a reproducible example:

```sql
create table api.table2 (
  field_b text primary key,
  field_c text,
  field_d text
);

create table api.table1 (
  field_a text primary key ,
  field_b text references api.table2(field_b)
);

insert into api.table2(field_b, field_c, field_d)
VALUES ('b1', 'c1', 'd1'),
       ('b2', 'c2', null);

insert into api.table1(field_a, field_b)
VALUES ('a1', 'b1'),
       ('a2', 'b2');
```

```
 GET /table1?select=*,table2(*)&table2=not.is.null
```

And here's the problem:

https://github.com/PostgREST/postgrest/blob/009250006ebc8cf67c485c88dbea6ac32be9dfe2/src/PostgREST/Query/QueryBuilder.hs#L81

From your log:

```sql
where "table1_table2_id" is not null
```

looks like it's the same as doing:

```
where table1_table2_id.* is not null
``` 

That's why it does not show rows that have null values in any column.

---

This is equivalent to an [inner join](https://postgrest.org/en/stable/references/api/resource_embedding.html#top-level-filtering), so, for now, keep using  `!inner` as a workaround:

```
 GET /table1?select=*,table2!inner(*)
```

**Comment by Etwenn** [comment]
@laurenceisla Thanks for the answer,
actually i wanted to use the not.is.null with the OR to perform some tricky request between different field from related table or not
I came to the problem i described in #2563 
And you figured out the exact same conclusion i've got 😞

https://github.com/PostgREST/postgrest/issues/2563#issuecomment-1562129208

**Comment by steve-chavez** [comment]
> For example, doing actors=not.is.null returns the same result as actors!inner(*)
> If that's the goal, then actors=not.is.null must be rewritten to NOT (actors IS NULL)

Yeah, I think we should do it like that. It's more intuitive for the API client and not much work for us too.

**Comment by laurenceisla** [comment]
After doing some tests, I checked that the `NOT (table IS NULL)` does not work as expected either. Using the previous example https://github.com/PostgREST/postgrest/issues/2800#issuecomment-1561692064, this query works correctly after the change:

```bash
curl "http://localhost:3000/table1?select=*,table2(*)&table2=not.is.null
```

But if we select only one column that has a `null` value, that is:

```bash
curl "http://localhost:3000/table1?select=*,table2(field_c)&table2=not.is.null
```

Then the result will be the same as `table IS NOT NULL`. The only option that gives us the expected result seems to be `IS DISTINCT FROM NULL` instead, as [per the docs](https://www.postgresql.org/docs/current/functions-comparison.html):

> In some cases, it may be preferable to write row IS DISTINCT FROM NULL or row IS NOT DISTINCT FROM NULL, which will simply check whether the overall row value is null without any additional tests on the row fields.

This would be in conflict with the `?table=not.is.null` syntax... maybe needs to be changed to `?table=isdistinct.null`?
