### ISSUE TITLE
Should P0002 result in HTTP status code 404?

### ISSUE THREAD

**Issue by brn-hyn** [PostgREST/postgrest#2806]
Should P0002 result in HTTP status code 404?

<html>
<body>

Class P0 — PL/pgSQL Error
P0002 | no_data_found

</body>
</html>

**Comment by steve-chavez** [comment]
Currently `P0002` results in 500 according to: https://postgrest.org/en/stable/references/errors.html#http-status-codes

You're suggesting to make it return 404 instead right?

Can you provide a function that throws the `P0002`?

**Comment by brnhynh** [comment]
Hi @steve-chavez, right. Sure, here's a function:
```
CREATE OR REPLACE FUNCTION public.decode_content(p_file_name text)
RETURNS text
LANGUAGE plpgsql
AS $function$
DECLARE
  cleaned_file_name text;
  decoded_text text;
  extension text;
BEGIN
  -- Clean up the file name by removing extra spaces
  cleaned_file_name := trim(both ' ' from p_file_name);

  -- Check if the cleaned file name has the allowed extensions
  IF cleaned_file_name ~* '\.(txt|doc)$' THEN
    -- Extract the extension from the cleaned file name
    extension := substring(cleaned_file_name from '\.(txt|doc)$');

    -- Attempt to find the encoded content based on the cleaned file name
    SELECT secret_content INTO decoded_text
    FROM public.encoded_content
    WHERE file_name = cleaned_file_name;

    -- If a row is found, decode the content
    IF found THEN
      decoded_text := decode(decoded_text, 'base64');
    ELSE
      -- If no row is found, raise an exception with status code 'p0002'
      RAISE EXCEPTION
        USING MESSAGE = 'P0002',
        DETAIL = FORMAT('Cannot find file with the name %s', cleaned_file_name),
        ERRCODE = 'P0002';
    END IF;
  ELSE
    -- If the file name has an invalid extension, raise an exception with status code '400'
    RAISE EXCEPTION
      USING MESSAGE = '22023',
      DETAIL = FORMAT('File name %s either has no extension or has invalid extension.', cleaned_file_name),
      HINT = 'Allowed extensions are .txt and .doc',
      ERRCODE = '22023';
  END IF;

  RETURN decoded_text;
END;
$function$;
```

Thank you for your consideration!

**Comment by steve-chavez** [comment]
> When you explicitly raise an error, you can also just raise status code PT404 , which will result in the 404 error you expect. This should be documented, too, but I can't find it right now after the docs have been restructured.

It's now on https://postgrest.org/en/stable/references/transactions.html#raise-errors-with-http-status-codes. Will link it on the stored procedures page.

**Comment by steve-chavez** [comment]
> I think 500 + "PL/pgSQL error" like we do right now, is perfectly fine.

Yeah, since the error is raised manually I think using `PTxyz` is the way to go.

@brnhynh Will close here but feel free to reopen.
