### ISSUE TITLE
Proposal: Optionally respond to application/vnd.pgrst.object+json with application/json

### ISSUE THREAD

**Issue by dbaynard** [PostgREST/postgrest#2809]
### Environment

* PostgreSQL version: 15.2
* PostgREST version: 10.1.1 — though I did check release notes for 10.2 and 11 and saw no mention of this.
* Operating system: macOS

### Description of ~~issue~~ feature request

I _think_ I would like to configure postgrest to reply to `Accept: application/vnd.pgrst.object+json` requests with `Content-Type: application/json`. If `application/vnd.pgrst.array+json` is added, following #2676, I would like the option to vary the `Content-Type` for that, too.

If this is of interest, I'd be happy to work on it. I'd imagine something like a `Prefers: content-type=application/json` header might work, as might a configuration option (to apply this to _all_ such responses), but I'm not familiar with the postgrest code.

I did search the issue tracker, and the closest things I found were #2188, and (via that) #1582.

I'm working with a frontend client that checks a response is json by checking the start of the `Content-Type` is `application/json`. This seems like a bug on this client's part — it ought to check that the start is `application/` and there's a `+json` before either the end or a `;`. Alas, that isn't the case, and I've had a horrible time debugging (it was compounded by another bug where if it _doesn't_ match the header, it returns the `Response` object rather than the result of calling the`.text()` method… don't ask). The right solution for my issue is to fix the frontend code (for various reasons I can't do that now, but it's fine, I'm altering the headers in the reverse proxy).

Anyway, thanks, team, for all your work on this.

**Comment by steve-chavez** [comment]
Hm, I think the Prefer approach is too ad hoc. #1582 looks it might solve your issue in a generic way.

> I'm working with a frontend client that checks a response is json by checking the start of the Content-Type is application/json. This seems like a bug on this client's part — 

Q: Why is the client using `vnd.pgrst.object+json`?

If you're only using it to validate that the response contains 1 row and you can convert the json to an object client-side, then https://github.com/PostgREST/postgrest/pull/2164 might be a much easier solution to implement.

**Comment by dbaynard** [comment]
Thanks. Feel free to close and if #1582 _doesn't_ support this I can reopen.

> Q: Why is the client using `vnd.pgrst.object+json`?

To clarify: the frontend expects single objects for every endpoint, so I changed `Accept` to `a/vpo+j`before requests hit postgrest. I didn't realize I'd need to change the response back.

I was thinking: if you're _sending_ `json`, call it `application/json`. Hence raising the issue, rather than just fixing the reverse proxy.

**Comment by steve-chavez** [comment]
> I was thinking: if you're sending json, call it application/json. Hence raising the issue, rather than just fixing the reverse proxy.

That seems sensible. Unfortunately at this stage it would a breaking change since there are many client libraries out there.

> Actually, would you welcome a docs PR that points out that Accept: application/vnd.pgrst.object+json results in a Content-Type that starts similarly, 

Sure. Please go ahead.

**Comment by dbaynard** [comment]
I agree that's the right approach; my impression was that `Accept` is a preference, but from further reading that doesn't appear to be the case. The right fix in my case is then to do what I've done, and convert the header in the reverse proxy.
