### ISSUE TITLE
Spread embedded resource

### ISSUE THREAD

**Issue by putheng** [PostgREST/postgrest#2812]
### Postgres: 15.1.0.87
`
"info": {
        "description": "This is a dynamic API generated by PostgREST",
        "title": "PostgREST API",
        "version": "10.2.0 (e07807d)"
    },
`

`
"externalDocs": {
        "description": "PostgREST Documentation",
        "url": "https://postgrest.org/en/v10.2/api.html"
    }
`

### Description of issue

`
/payment_methods?select=bank_name,...image:payment_methods_object(url:name)
`

`
{
    "code": "PGRST100",
    "details": "unexpected \".\" expecting field name (* or [a..z0..9_$]) or \"*\"",
    "hint": null,
    "message": "\"failed to parse select parameter (bank_name,...image:payment_methods_object(url:name))\" (line 1, column 11)"
}
`

1. create table `payment_methods_object` that has column object_id that is foreign to storage.objects
2. create a function 
`
CREATE OR REPLACE FUNCTION "public".payment_methods_object(payment_methods) 
RETURNS setof "storage".objects ROWS 1 
AS $$
  SELECT * FROM "storage".objects WHERE objects.id = $1.object_id
$$ STABLE LANGUAGE sql SECURITY DEFINER;
`

Anyway how to update PostgREST version at Supabase?

**Comment by steve-chavez** [comment]
This is not related to PostgREST so closing. But see https://github.com/supabase/postgres/pull/628.
