### ISSUE TITLE
Perf drop in latest releases - unstable `postgrest-loadtest` results

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#2842]
## Problem

On https://github.com/PostgREST/postgrest/pull/2523, the [loadtest](https://github.com/PostgREST/postgrest/runs/11196257698) reported `420.02257774518125` throughput.

On main, the [loadtest](https://github.com/PostgREST/postgrest/runs/14667945163) reports a `338.6473662241433` throughput.

## Proposal

We need to check on which commit(s) the regression happened and then find a solution.

---

@wolfgangwalther I recall you ran the `postgrest-loadtest` on a commit range before. Perhaps you could share the script so I can check? (the script would be useful as one of our nix commands too).

**Comment by develop7** [comment]
I've tried to reproduce the issue with `postgrest-loadtest-against `[`0a1564ba5aaa8175dcb738271967944652cf4ce9`](https://github.com/PostgREST/postgrest/commit/0a1564ba5aaa8175dcb738271967944652cf4ce9) locally

According to the report, requests throughput _does_ drop, along with request rate, but not 25% down: 

<table>
<tr>
 <td>
 <th>Rate
 <th>Throughput
<tr>
 <th>0a1564
 <td>710.57
 <td>645.97
<tr>
 <th>main
 <td>687.80
 <td>625.27
<tr>
	<th>diff
	<td>-4%
	<td>-4%
</table>

While there is a slowdown, it's not awful lot. Might be a fluke; worst case is the slowdown is amplified by the environment Github actions are running in. I'd suggest we'd try running loadtest in a dedicated VM (in AWS for now) and see if we could reproduce the issue.

<details>
<summary>Reproduction attempt</summary>

```text
❯  postgrest-loadtest-against 0a1564ba5aaa8175dcb738271967944652cf4ce9

Running loadtest on "0a1564ba5aaa8175dcb738271967944652cf4ce9"...

Preparing worktree (detached HEAD 0a1564ba)
postgrest-with-postgresql-15: You can connect with: psql 'postgres:///postgres?host=/run/user/1000/postgrest/postgrest-with-postgresql-15-qzo/socket' -U postgres
postgrest-with-postgresql-15: You can tail the logs with: tail -f /run/user/1000/postgrest/postgrest-with-postgresql-15-qzo/db.log
delaying data to/from postgres by 0ms
Building postgrest (nix)... done.
Starting postgrest... done.
delaying data to/from PostgREST by 0ms
2023/09/11 16:59:39 accept unix /run/user/1000/postgrest/postgrest-with-slow-postgrest-y1R/postgrest.socket: use of closed network connection
2023/09/11 16:59:39 accept unix /run/user/1000/postgrest/postgrest-with-slow-pg-SlF/socket/.s.PGSQL.5432: use of closed network connection
Requests      [total, rate, throughput]         42638, 710.57, 645.97
Duration      [total, attack, wait]             1m0s, 1m0s, 438.81µs
Latencies     [min, mean, 50, 90, 95, 99, max]  72.607µs, 1.406ms, 467.721µs, 1.413ms, 10.105ms, 10.945ms, 19.807ms
Bytes In      [total, mean]                     43138986, 1011.75
Bytes Out     [total, mean]                     164090460, 3848.46
Success       [ratio]                           90.91%
Status Codes  [code:count]                      200:23258  201:3876  204:11628  400:3876  
Error Set:
400 Bad Request

Done running on "0a1564ba5aaa8175dcb738271967944652cf4ce9".


Running loadtest on HEAD...

postgrest-with-postgresql-15: You can connect with: psql 'postgres:///postgres?host=/run/user/1000/postgrest/postgrest-with-postgresql-15-sOm/socket' -U postgres
postgrest-with-postgresql-15: You can tail the logs with: tail -f /run/user/1000/postgrest/postgrest-with-postgresql-15-sOm/db.log
delaying data to/from postgres by 0ms
Building postgrest (nix)... done.
Starting postgrest... done.
delaying data to/from PostgREST by 0ms
2023/09/11 17:04:39 accept unix /run/user/1000/postgrest/postgrest-with-slow-postgrest-ojG/postgrest.socket: use of closed network connection
2023/09/11 17:04:39 accept unix /run/user/1000/postgrest/postgrest-with-slow-pg-ktm/socket/.s.PGSQL.5432: use of closed network connection
Requests      [total, rate, throughput]         41274, 687.80, 625.27
Duration      [total, attack, wait]             1m0s, 1m0s, 595.107µs
Latencies     [min, mean, 50, 90, 95, 99, max]  69.772µs, 1.452ms, 465.196µs, 1.469ms, 10.637ms, 11.475ms, 19.373ms
Bytes In      [total, mean]                     42521098, 1030.22
Bytes Out     [total, mean]                     158840920, 3848.45
Success       [ratio]                           90.91%
Status Codes  [code:count]                      200:22514  201:3752  204:11256  400:3752  
Error Set:
400 Bad Request

Done running on HEAD.
```

</details>

**Comment by develop7** [comment]
On the other hand, the loadtest against the commit before the v11.2.0 [reports throughput = 261.92](https://github.com/PostgREST/postgrest/runs/15784639467), while the one before the v11.1.0 [does 323.83](https://github.com/PostgREST/postgrest/runs/14090926341) which results in 20% drop.

**Comment by steve-chavez** [comment]
> While there is a slowdown, it's not awful lot. Might be a fluke; worst case is the slowdown is amplified by the environment Github actions are running in. 

@develop7 Those are great news! Thanks for reporting!

> I'd suggest we'd try running loadtest in a dedicated VM (in AWS for now) and see if we could reproduce the issue.

That would be great. Having a dedicated AWS instance where `postgrest-loadtest` runs on every CI run would give the most stable results.

**Comment by steve-chavez** [comment]
> Having a dedicated AWS instance where postgrest-loadtest runs on every CI run

@laurenceisla Just told me that the above is not possible, the github secrets required for the AWS instance to run are not exposed to PRs, only for the `main` branch. This is why our ARM build only runs on `main`.

**Comment by steve-chavez** [comment]
Closing this as it was already clarified there was no noticeable perf loss.
