### ISSUE TITLE
The SQL syntax of this'case when' does not match the return result of http

### ISSUE THREAD

**Issue by cagy520** [PostgREST/postgrest#2845]
CASE
            WHEN a.temperature IS NOT NULL AND a.cl IS NULL THEN '00FFFF'::text
            WHEN a.temperature IS NOT NULL AND a.cl = '#FB2DAB'::text THEN 'f55baa'::text
            WHEN a.temperature IS NULL AND a.cl IS NULL THEN 'FFFFE0'::text
            ELSE NULL::text

SQL  result :
All three are available

BUT HTTP result ：
There are only two types

**Comment by steve-chavez** [comment]
Please show the `curl` call and the HTTP response.
