### ISSUE TITLE
Null filtering on embedded resources throws `column does not exist` error when using `Prefer: count=exact`

### ISSUE THREAD

**Issue by zachblume** [PostgREST/postgrest#2846]
### Environment

* PostgreSQL version: (if using docker, specify the image)
* Docker image: supabase/postgres:15.1.0.90
* PostgREST version: (if using docker, specify the image)
* image: postgrest/postgrest:latest (A little tricky here, I'm selfhosting supabase with the latest postgREST!)
* Operating system: Mac

### Description of issue

Ex.
```
-- Create the "people" table
CREATE TABLE people (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255),
  -- Add other columns as needed
);

-- Create the "donations" table
CREATE TABLE donations (
  id SERIAL PRIMARY KEY,
  person_id INTEGER REFERENCES people(id),
  amount NUMERIC,
  -- Add other columns as needed
);

```

```
curl 'http://localhost:8000/rest/v1/people?select=*%2Cdonations%28*%29&or=%28and%28donations.not.is.null%29%29&donations.or=(and%28amount.eq.1%29)'
```

...responds with the correct items.

```
curl 'http://localhost:8000/rest/v1/people?select=*%2Cdonations%28*%29&or=%28and%28donations.not.is.null%29%29&donations.or=(and%28amount.eq.1%29)'
-H "Prefer: count=exact"
```

Responds:

`{code: "42703", details: null, hint: null, message: "column "people_donations_1" does not exist"}`

This seems to hold for count estimated or exact and other combinations or filtering against related tables.

So in effect we cannot count the rows alongside a filter against a joined table.

**Comment by laurenceisla** [comment]
To simplify the error reproduction, a minimal example that causes this to fail is:

```bash
curl 'http://localhost:3000/people?select=*,donations(*)&donations=not.is.null' \
  -H "Prefer: count=exact"
```

Removing the null filtering from your example works OK, so the bug happens only in the case mentioned above:

```bash
curl 'http://localhost:3000/people?select=*,donations(*)&donations.or=(and(amount.eq.1))' \
  -H "Prefer: count=exact"
```

**Comment by steve-chavez** [comment]
Note: here the behavior should be the same as https://github.com/PostgREST/postgrest/issues/2009. We need to add an EXISTS to the count query.
