### ISSUE TITLE
`value too long for type character(1)` after update to `11.1.0`

### ISSUE THREAD

**Issue by psteinroe** [PostgREST/postgrest#2861]
### Environment

* Supabase CLI 1.77.9 (latest at the time of writing)

### Description of issue

I have table `contact` that refers to a table `country` via a foreign key of type `char(2)`.

since updating to latest cli, an 

`.insert({country: 'DE'})`

returns
```
    {
      code: '22001',
      details: null,
      hint: null,
      message: 'value too long for type character(1)'
    }
```

Executing the sql statement directly does work as expected.

```sql
insert into contact (country) values (
  'DE'
  );
```

Based on my findings, PostgREST must be causing this, but feel free to move this issue if required.

You can find a full repro in https://github.com/psteinroe/supabase-cache-helpers

The daily tests started failing at the same time the cli updated the postgrest version.

failing ci: https://github.com/psteinroe/supabase-cache-helpers/actions/workflows/ci.yml?query=branch%3Amain

commit that updated pgrst version from 10.1.2 to 11.1.0: https://github.com/supabase/cli/commit/ada5272b001375667bb0c269e5c2899f21e7b567

**Comment by steve-chavez** [comment]
@psteinroe Please share the tables definition, I'm a bit lost on those repos.

Maybe related to https://github.com/PostgREST/postgrest/issues/1586

**Comment by psteinroe** [comment]
> @psteinroe Please share the tables definition, I'm a bit lost on those repos.

sure!

```sql
create table public.country (
    code char(2) primary key not null,
    name varchar(255) not null,
);
```

```sql
create table public.contact (
    id uuid primary key not null default gen_random_uuid (),
    country char(2) references public.country on delete set null
);
```

maybe the foreign key ref is not required, did not test it yet.

the linked issue seems pretty close to mine. let me know if I should try to repro it in a more enclosed environment.

**Comment by steve-chavez** [comment]
:heavy_check_mark: Reproduced:

```sql
create table country1 (
    code char(2) primary key not null,
    name varchar(255) not null
);

create table contact1 (
    id uuid primary key not null default gen_random_uuid (),
    country char(2) references country1 on delete set null
);

insert into country1 values ('DE', 'Germany');
```

```
http POST 'localhost:3000/contact1' <<JSON
> {"country": "DE"}
> JSON
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
Date: Thu, 13 Jul 2023 13:53:49 GMT
Server: postgrest/11.1.0 (5a04ec7)
Transfer-Encoding: chunked

{
    "code": "22001",
    "details": null,
    "hint": null,
    "message": "value too long for type character(1)"
}
```

Same underlying reason as https://github.com/PostgREST/postgrest/issues/1586#issuecomment-696345442

I think this might have happened for inserts on https://github.com/PostgREST/postgrest/pull/2542. Back in [10.1.1](https://github.com/PostgREST/postgrest/blob/main/CHANGELOG.md#1011---2022-11-08).

**Comment by steve-chavez** [comment]
I've noticed it's possible to cast using the length in the char.

```sql
select * from json_to_record('{"c":"bar"}') as x(c char(2));
ERROR:  value too long for type character(2)

select * from json_to_record('{"c":"bar"}') as x(c char(3));
  c  
-----
 bar
```

But pg loses the length of the type in some cases (this is happening on our schema cache).

```sql
select pg_typeof('ab'::char(2));

 pg_typeof 
-----------
 character
```

Although I do see it on some psql builtins.

```sql
\d+ country1
                                                 Table "test.country1"
 Column |          Type          | Collation | Nullable | Default | Storage  | Compression | Stats target | Description 
--------+------------------------+-----------+----------+---------+----------+-------------+--------------+-------------
 code   | character(2)           |           | not null |         | extended |             |              | 
```

So it must be possible to obtain it from the catalogs.

**Comment by alexStrickner00** [comment]
we observed the same issue for a table containing a char(3) column
