### ISSUE TITLE
Update Nix development and build guide

### ISSUE THREAD

**Issue by taimoorzaeem** [PostgREST/postgrest#2870]
### Nix build guide

[Ref](https://github.com/PostgREST/postgrest/blob/main/nix/README.md)

The Nix development and build guide does not mention the type of nix installation to be done. As it stands, nix package manager comes in two types of installations, single-user and multi-user. Not mentioning this in the guide could be an impediment for new contributors of this project.

Issue priority: low

**Comment by steve-chavez** [comment]
Hm, perhaps we should remove the "Getting started with Nix" section? We could link the [official download page](https://nixos.org/download.html) in "Nix development and build environment".

I recall that when we started the guide there wasn't a Windows section in the official page and now there is [one](https://nixos.org/download.html#nix-install-windows). The docker container guide is also on the official page so it's unneeded now too.

>  As it stands, nix package manager comes in two types of installations, single-user and multi-user.

The official guide also mentions that the Multi-user installation is recommended. It would be better (also easier to maintain for us) to leave the recommendations to the official page.

@taimoorzaeem WDYT?

**Comment by taimoorzaeem** [comment]
Yes, I think this would be much better for us. If in future, nix decides to changes install paths, we would need to change that on our guide as well. Let's just link the official download page in the "Getting started with Nix" section and remove other details such as install paths etc as they are subject to change in the future.

**Comment by taimoorzaeem** [comment]
Resolved in #2873.
