### ISSUE TITLE
Multiple roles in JWT

### ISSUE THREAD

**Issue by diaznet** [PostgREST/postgrest#2877]
Just like in #1536 I have the issue that my JWT token contains many roles. I cannot have this changed.
I have tried to play with jspath but cannot find a simple way to filter on a string in a list.

Say I have the following roles in my JWT:

`
{
    "roles": [
        "postgrest_role",
        "other_role",
    ]
}
`

I want to filter on postgrest* roles (user should only have one postgrest_* role)

Does PostgREST still not support jspath filtering?

**Comment by steve-chavez** [comment]
To solve this we need jspath predicates (as mentioned on https://github.com/PostgREST/postgrest/issues/1536#issuecomment-633652494) which are still not supported.

Let's move the discussion to #1536.
