### ISSUE TITLE
The Preference return=headers-only exists in our code but is not present in RFC 7240

### ISSUE THREAD

**Issue by taimoorzaeem** [PostgREST/postgrest#2878]
```haskell
data PreferRepresentation
  = Full        -- ^ Return the body.
  | HeadersOnly -- ^ Return the Location header(in case of POST). This needs a SELECT privilege on the pk.
  | None        -- ^ Return nothing from the mutated data.
  deriving Eq
   
instance ToHeaderValue PreferRepresentation where
  toHeaderValue Full        = "return=representation"
  toHeaderValue None        = "return=minimal"
  toHeaderValue HeadersOnly = "return=headers-only"
```

The prefer value `Prefer: return=headers-only` does not seem to be present in the RFC 7240 standard. Maybe we should remove it? If it is valid, do we be return it with response in `Preference-Applied: ...` ? Related to issue #740.

**Comment by steve-chavez** [comment]
RFC 7240  does mention we can add custom preferences [here](https://datatracker.ietf.org/doc/html/rfc7240#section-2).

Right now `headers-only` is only for returning `Location` ([ref](https://postgrest.org/en/stable/references/api/tables_views.html#insert)), but maybe it could have other uses later. So I think we should keep it.

> If it is valid, do we be return it with response in Preference-Applied: ... ? Related to issue https://github.com/PostgREST/postgrest/issues/740.

Yes, in fact we do return `Preference-Applied` for some preferences, like:

https://github.com/PostgREST/postgrest/blob/28d5278d624ae262fc78345560e269be2ef99777/test/spec/Feature/Query/UpsertSpec.hs#L30-L33

It would be good to keep consistency for the others (`Prefer: return=representation/headers-only/minimal`).
