### ISSUE TITLE
Upsert with primary key null should insert data rather than throwing error

### ISSUE THREAD

**Issue by softwarehut-io** [PostgREST/postgrest#2886]
Upserting with id column set to null throws an error

> Exception has occurred.
> PostgrestException (PostgrestException(message: null value in column "id" of relation "object_table" violates not-null constraint, code: 23502,)

The solution I'd like:
The SDK should perform insert operation when primary key is set to null or does not conflict (in case of id not generated by db)

I understand that the sdk should be able to insert null values to nullable fields.

My request was regarding primary key and primary key usually are non nullable.

The same way the SDK considers primary key when onConflict is mentioned, would be helpful if null primary inserts the record

**Comment by steve-chavez** [comment]
I suggest moving this to https://github.com/supabase/postgrest-js (assuming you refer to it), since PostgREST itself has no concept of SDK.

**Comment by softwarehut-io** [comment]
@steve-chavez, This issue was originally posted with supabase and they suggested moving it here
https://github.com/supabase/supabase-flutter/issues/574#issuecomment-1657942760

**Comment by steve-chavez** [comment]
Hm, so by reading that issue, do you:

1) Expect to insert a `null` on a primary key? That's not allowed by definition.
2) Expect your request to auto generate a pk value considering an identity column?

If it's 2 then PostgREST already does it:

- Automatically when inserting/upserting a single object without the `?columns` parameter 
- When using `?columns` (bulk or single object) a header has to be specified ([ref](https://postgrest.org/en/stable/references/api/tables_views.html#bulk-insert-with-default-values)).

**Comment by steve-chavez** [comment]
Replied on https://github.com/supabase/supabase-flutter/issues/574#issuecomment-1659656811.
