### ISSUE TITLE
Refactor module MediaType.hs to use Network.HTTP.Media

### ISSUE THREAD

**Issue by taimoorzaeem** [PostgREST/postgrest#2901]
### Description of issue

The [MediaType.hs](https://github.com/PostgREST/postgrest/blob/main/src/PostgREST/MediaType.hs) module is quite verbose and the code looks kind of ugly. For instance:

https://github.com/PostgREST/postgrest/blob/87d6a0d0feaab6a85aaa5ba7ec6c0e9f97855fe4/src/PostgREST/MediaType.hs#L36-L50

### Solution

The module could be refactored to use [Network.HTTP.Media](https://hackage.haskell.org/package/http-media-0.8.0.0/docs/Network-HTTP-Media.html). This would let us remove the above mentioned part.

**Comment by steve-chavez** [comment]
Maybe we're being too strict with the types for media type parsing. For example https://httpbin.org/ behaves like:

```bash
$ curl -H "Content-Type: application/json; any=44; thing=33" 'https://httpbin.org/post' -d @- <<JSON
{"a": 3}
JSON

{
  "args": {}, 
  "data": "{\"a\": 3}", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "8", 
    "Content-Type": "application/json; any=44; thing=33", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.81.0", 
    "X-Amzn-Trace-Id": "Root=1-64de9754-6ca0259374ed248d769677e9"
  }, 
  "json": {
    "a": 3
  }, 
  "origin": "179.6.5.245", 
  "url": "https://httpbin.org/post"
}
```

Meaning it ignores unknown media type parameters.

**Comment by taimoorzaeem** [comment]
Well, the [RFC 6838](https://datatracker.ietf.org/doc/html/rfc6838#section-4.3) states that we shouldn't add parameters to standard media types. However, yes I think we are being a little bit too strict for discarding the parameters for our custom media types. However parsing these parameters do complicate things. For example, the way `MTPlan` media type is handled.
