### ISSUE TITLE
Add support for `WITH` queries

### ISSUE THREAD

**Issue by imageck** [PostgREST/postgrest#2902]
Currently, the only way to insert into multiple relations is to create a function and execute it with an RPC. `WITH` queries provide a more convenient, idiomatic and affordable (i.e. it requires less maintenance) way of performing such operations.

I don't think a full implementation is going to be feasible or even doable. However, support for inserts (with the ability to specify which columns will be inserted into which query) at least would be phenomenal.

**Comment by steve-chavez** [comment]
@imageck Seems related to https://github.com/PostgREST/postgrest/issues/818, let's continue there.

If not, please reopen.
