### ISSUE TITLE
Audit for SQL injections

### ISSUE THREAD

**Issue by begriffs** [PostgREST/postgrest#294]
All user input should be going through either `pgFmtIdent` or `pgFmtLit`. These functions were [tested](https://github.com/begriffs/postgrest/blob/master/test/Unit/PgQuerySpec.hx#L88-L99) with QuickCheck to ensure they act like the build in postgres `format` command, but it would be smart to use deliberately malicious strings rather than gibberish. (The official postgres escaping code is available to [browse](http://doxygen.postgresql.org/fe-exec_8c.html#a01c75d019597e76bc041716f27caf564) for comparison.)

Ideally we can create a new feature test file like `InjectionSpec.hs` and fill it with lots of evil attempts. For good measure we should try a [vulnerability scanner](http://resources.infosecinstitute.com/14-popular-web-application-vulnerability-scanners/) as well.

**Comment by ruslantalpa** [comment]
I tried running this
```
python sqlmap.py -u 'http://localhost:3000/projects?name=eq.*' --dbms=PostgreSQL --level=5 --risk=3 -f --banner --dbs -v 1
python sqlmap.py -u 'http://localhost:3000/projects?name=eq.OSX' --dbms=PostgreSQL --level=5 --risk=3 -f --banner --dbs -v 1

```
So far so good

**Comment by ruslantalpa** [comment]
Whenever someone is trying a tool like this he is bound to get a lot of 400 bad request back.
The new documentation cookbook should contain a few examples how to rate-limit/block bad actors using nginx/firewall.
Maybe make it a sample nginx config file with lots of options/feature that can be used in "nginx in front of postgrest" configuration.

**Comment by begriffs** [comment]
This audit was pretty long ago, we should do it again and add it to CI. In particular might want to include a check that headers and jwt claims cannot create an injection.

Talked with @elimisteve tonight who brought this up.

**Comment by wolfgangwalther** [comment]
Now that we're using server-side parametrized statements everywhere, I don't think we need to do this anymore.
