### ISSUE TITLE
BUG patch boolean column

### ISSUE THREAD

**Issue by npltr62** [PostgREST/postgrest#2941]
### Environment

* PostgreSQL version: kartoza/postgis:14-3.2
* PostgREST version: v11.0.0

### Description of issue
I used patch method to update a boolean column of single row, this request worked perfectly with previous version 9 but now there is a bug.
the request returning 
`{
    "code": "21000",
    "details": null,
    "hint": null,
    "message": "more than one row returned by a subquery used as an expression"
}`
If I make a patch request with anaother column (text) , it's working ...

**Comment by steve-chavez** [comment]
@npltr62 Hm, did you solve the issue? It might have been fixed in the latest v11.

**Comment by npltr62** [comment]
> @npltr62 Hm, did you solve the issue? It might have been fixed in the latest v11.

yes I solved it, it was a problem with a trigger ...
