### ISSUE TITLE
Support `handling=strict` for `Prefer` header

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#2943]
## Problem

Currently any unrecognized `Prefer` value will be accepted and ignored:

```
$ curl 'localhost:3000/projects' -H "Prefer: anything" -D -
HTTP/1.1 200 OK

[{"id":1,"name":"Windows 7","client_id":1}, 
 {"id":2,"name":"Windows 10","client_id":1}, 
 {"id":3,"name":"IOS","client_id":2}, 
 {"id":4,"name":"OSX","client_id":2}, 
 {"id":5,"name":"Orphan","client_id":null}]
```

This can give issues when you don't know what `Prefer` values a deployed PostgREST accepts (discussed on https://github.com/PostgREST/postgrest/pull/2940#discussion_r1322445343).

## Solution

Support `Prefer: handling=strict` according https://www.rfc-editor.org/rfc/rfc7240.html#section-4.4. This would allow the client to check what `Prefer` values are accepted:

```
$ curl 'localhost:3000/projects' -H "Prefer: handling=strict; anything" -D -
HTTP/1.1 400 Bad Request
```

Using `Prefer: handling=lenient` would just accept and ignore the `Prefer`, as we've always done.

## Details

The logic that filters the accepted Prefers is currently on the Response module.

https://github.com/PostgREST/postgrest/blob/8d3c9f84358e132d1248ed3d5738dde835526c77/src/PostgREST/Response.hs#L73

https://github.com/PostgREST/postgrest/blob/8d3c9f84358e132d1248ed3d5738dde835526c77/src/PostgREST/Response.hs#L101

It'd be better centralized at the Plan module. There we can fail and respond with an error.

**Comment by taimoorzaeem** [comment]
@steve-chavez In which module should I write tests for this feature? Or maybe should I create a new test module for this feature?

**Comment by steve-chavez** [comment]
@taimoorzaeem A new test module seems fine, maybe `PreferencesSpec`
