### ISSUE TITLE
`TIMESTAMP WITH TIMEZONE` column is always converted to server time zone

### ISSUE THREAD

**Issue by dantheman2865** [PostgREST/postgrest#2979]
### Environment

* PostgreSQL version: v14 for this repro, also seen on v15
* PostgREST version: Docker Tag `v11.2.0`
* Operating system: Ubuntu 22.04

### Description of issue
Saving information to TIMESTAMP WITH TIMEZONE column always uses the server's timezone rather than preserving the input timezone. The date is converted to the server's timezone correctly, but timezone information is lost.

Note: Server is set to UTC timezone.

**Given this table:**
```
CREATE TABLE IF NOT EXISTS public.date_testing
(
    id bigint NOT NULL DEFAULT nextval('date_testing_id_seq'::regclass),
    ts TIMESTAMP WITHOUT TIME ZONE,
    ts_with_tz TIMESTAMP WITH TIME ZONE,
    t_with_tz TIME WITH TIME ZONE,
    CONSTRAINT date_testing_pkey PRIMARY KEY (id)
);
```
**and this input:**
```
POST http://localhost:3000/date_testing
{
    "ts": "2023-09-30 12:00:00-04",
    "ts_with_tz": "2023-09-30 12:00:00-04",
    "t_with_tz": "12:00:00-04"
}
```
**I expect:**
```
SELECT * FROM public.date_testing;
 id |         ts          |       ts_with_tz       |  t_with_tz
----+---------------------+------------------------+-------------
  1 | 2023-09-30 12:00:00 | 2023-09-30 12:00:00-04 | 12:00:00-04
(1 row)
```
**but I actually receive:**
```
SELECT * FROM public.date_testing;
 id |         ts          |       ts_with_tz       |  t_with_tz
----+---------------------+------------------------+-------------
  1 | 2023-09-30 12:00:00 | 2023-09-30 16:00:00+00 | 12:00:00-04
(1 row)
```

I have been looking for a reason to learn some Haskell, so I would be happy to put up a PR for this. I wanted to check first to be sure this isn't expected behavior.

Thanks for making such a great tool!

**Comment by dantheman2865** [comment]
If implemented, #2799 would provide an option to set the timezone to match expectations.

**Comment by steve-chavez** [comment]
> ALTER DATABASE testing SET TIMEZONE TO 'UTC';

Hm, so the queries through the API do not have the timezone set to UTC?

Strange, this should be default behavior when connecting. For example:

```sql
postgres=# select now();
              now              
-------------------------------
 2023-10-02 19:02:57.754824+00

postgres=# show timezone;
 TimeZone 
----------
 UTC
(1 row)

postgres=# alter database postgres set timezone to 'Europe/Berlin';

-- note that the setting is still not applied
postgres=# show timezone;
 TimeZone 
----------
 UTC
```

Reconnecting to the db:

```sql
postgres=# select now();
              now              
-------------------------------
 2023-10-02 21:04:45.634313+02
(1 row)

postgres=# show timezone;
   TimeZone    
---------------
 Europe/Berlin
(1 row)
```

Now has the timezone applied.

@dantheman2865 Can you try restarting postgREST?

**Comment by dantheman2865** [comment]
Hi @steve-chavez , the `ALTER DATABASE testing SET TIMEZONE TO 'UTC';` line was intended to communicate that the server timezone is set to UTC. I've updated the original issue to make this more clear.

The actual problem I'm seeing is that the timezone is always set to UTC regardless of the input's timezone.

**Comment by steve-chavez** [comment]
Hm, I'm still not clear on the issue. Say you do a plain INSERT instead of doing POST through the API:

```sql
INSERT INTO date_testing(ts, ts_with_tz, t_with_tz)
VALUES ('2023-09-30 12:00:00-04', '2023-09-30 12:00:00-04', '12:00:00-04');
```

Do you get the result you expect in that case?

**Comment by dantheman2865** [comment]
Oh, I do not get the expected results! I had thought this was a PostgREST issue, but it's actually an unexpected behavior from PostgreSQL...

Thanks for your patience!

**Comment by steve-chavez** [comment]
@dantheman2865 No problem! Let us know if #2799 would help here.

**Comment by dantheman2865** [comment]
> @dantheman2865 No problem! Let us know if #2799 would help here.

I don't think it would help in my situation. If the timestamptz needs to be converted to the right timezone, I think it's easier to do that in the browser than in the service.
