### ISSUE TITLE
Leverage GitHub Actions' own cache

### ISSUE THREAD

**Issue by develop7** [PostgREST/postgrest#2990]
Right now the "setup nix environment" step takes whopping 3 minutes in CI, see https://github.com/PostgREST/postgrest/actions/runs/6418699702/job/17427023445?pr=2983#step:3:415. Which is no wonder, because every time it is making 800-something HTTP(S) requests, downloading 771 MB of data. 

Since the Nix environment isn't changing very often, we probably could benefit from caching it.

I suggest trying https://github.com/DeterminateSystems/magic-nix-cache-action first (since it's advertised as automagic solution) and see if it helps

**Comment by steve-chavez** [comment]
@develop7 Can the magic-nix-cache coexist with Cachix? Or would it have to be a replacement?

**Comment by develop7** [comment]
@steve-chavez they must be able to coexist for sure. I've created   https://github.com/PostgREST/postgrest/pull/2992 to play with

**Comment by steve-chavez** [comment]
Magic nix cache is EOL:
https://determinate.systems/posts/magic-nix-cache-free-tier-eol/

Looks like we never introduced here. Sharing just in case.
