### ISSUE TITLE
Cabal builds in CI are failing

### ISSUE THREAD

**Issue by develop7** [PostgREST/postgrest#3000]
### Description of issue

https://github.com/PostgREST/postgrest/actions/runs/6482755722/job/17602892437#step:7:1503, https://github.com/PostgREST/postgrest/actions/runs/6472292459/job/17572620592#step:7:1503

Also confirming the issue is reproduced locally:

![image](https://github.com/PostgREST/postgrest/assets/89889/3afded09-85c6-40ce-8224-4d07e3d088b7)

Suggestions for remediation: 

1. ship `cabal.freeze` with deferred-bounds working for us (from previous `cabal update`)
2. limit `deferred-folds`' bounds?
3. um, upgrade what, `hasql-something` that depends on offending package?

**Comment by steve-chavez** [comment]
> ship cabal.freeze with deferred-bounds working for us (from previous cabal update)

That sounds good :+1:

> limit deferred-folds' bounds?

I think we can't because it's a transitive dependency?

> um, upgrade what, hasql-something that depends on offending package?

Previously discussed on https://github.com/PostgREST/postgrest/pull/2991#issuecomment-1756149876
