### ISSUE TITLE
Apply functions `statement_timeout` for RPC

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#3001]
## Problem

Pg itself doesn't apply a `statement_timeout` set on a function.

```sql
create or replace function my_func() returns void as $$
  select pg_sleep(3);
$$ language sql set statement_timeout to '1s';

begin;
select my_func();
 my_func 
---------
 
(1 row)
commit;

-- vs

begin;
set local statement_timeout to '2s';
select pg_sleep(3);
ERROR:  canceling statement due to statement timeout
```

It only does it for LOGIN roles plus we do it for [impersonated roles](https://postgrest.org/en/stable/references/auth.html#impersonated-role-settings). 

## Solution

Apply the function `statement_timeout` at the start of the transaction on RPC. This would override the role `statement_timeout`.

We already have similar logic for `default_transaction_isolation`: https://postgrest.org/en/stable/references/transactions.html#isolation-level.

**Comment by taimoorzaeem** [comment]
> ```sql
> create or replace function my_func() returns void as $$
>   select pg_sleep(3);
> $$ language sql set statement_timeout to '1s';
> ```

Where would we get the value `1s` from? Do we need to add a config for that?

**Comment by steve-chavez** [comment]
@taimoorzaeem No extra config. It should come from this query:

https://github.com/PostgREST/postgrest/blob/964da646b0c3633594b200a415929b33c1c24981/src/PostgREST/SchemaCache.hs#L365-L444

(You can copy/paste the SQL and try it under `postgrest-with-postgresql-15 psql -U postgres`)

This part is the most relevant:

```sql
  LEFT JOIN LATERAL unnest(proconfig) config ON config like 'default_transaction_isolation%'
```

Main idea is to obtain the statement timeout from there and add a field here:

https://github.com/PostgREST/postgrest/blob/964da646b0c3633594b200a415929b33c1c24981/src/PostgREST/SchemaCache/Routine.hs#L51-L61

Check https://github.com/PostgREST/postgrest/pull/2755 for more details on how this was implemented for `default_transaction_isolation`.
