### ISSUE TITLE
Cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by peterfutaro** [PostgREST/postgrest#3011]
Hi there,

I am trying to install PostgREST version 11.2.0 to my ubuntu by following the steps in: https://postgrest.org/en/stable/tutorials/tut0.html

But when reaching step#3 (running ./postgrest -h), it returns
-bash: ./postgrest: cannot execute binary file: Exec format error

Can anyone help me ?

**Comment by develop7** [comment]
Could you post here a link you've downloaded the binary from? What does `file ./postgrest` say?

**Comment by peterfutaro** [comment]
Hi @develop7 

I downloaded from: https://github.com/PostgREST/postgrest/releases

Here is the message I got when running ./postgrest

**_-bash: ./postgrest: cannot execute binary file: Exec format error_**

FYI, I also tried with the latest version there (version 11.2.1) but also resulting the same

**Comment by develop7** [comment]
Can you please run `file ./postgrest` command and post the result here?

Can you please specify which asset did you download from under "Assets"?

**Comment by peterfutaro** [comment]
Oh sorry, I misunderstood it. Here it is:

root@srv429891:~# file ./postgrest
./postgrest: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=eab8757ce6584cba90c566826846b325f4c3be2c, with debug_info, not stripped


![image](https://github.com/PostgREST/postgrest/assets/76289958/29090880-a134-454d-9165-f1a3577e09de)

I downloaded this:
![image](https://github.com/PostgREST/postgrest/assets/76289958/fa19b8cd-31af-4fb7-85ef-57769a676b09)

**Comment by develop7** [comment]
> ![image](https://user-images.githubusercontent.com/76289958/275479665-37e16d26-8a94-48f2-8423-f99f5c82a841.png)

You seem to try to run an `aarch64` executable on an `amd64` (or `x64`) machine. Try `…-linux-static-x64.tar.xz` instead.

**Comment by peterfutaro** [comment]
Hi @develop7 

Got it. 
Sorry, I am new to Linux. I thought I should select " postgrest-v11.2.1-ubuntu-aarch64.tar.xz " since I am using UBUNTU here.

It is okay now

**Comment by develop7** [comment]
@steve-chavez should we add a sentence on choosing which release to download to the manual?

> Got it. Sorry, I am new to Linux. I thought I should select " postgrest-v11.2.1-ubuntu-aarch64.tar.xz " since I am using UBUNTU here.

No worries, everybody was a newcomer once. Welcome :)
 
> It is okay now

Beautiful, good luck on your further journey then :) Closing the issue.
