### ISSUE TITLE
Transaction-Scoped Settings are unclear on the logs

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#3019]
## Problem

[Transaction-Scoped Settings](https://postgrest.org/en/stable/references/transactions.html#transaction-scoped-settings) show on the logs as:

```sql
select set_config($1, $2, true), set_config($3, $4, true), set_config($5, $6, true), set_config($7, $8, true), set_config($9, $10, true), set_config($11, $12, true), set_config($13, $14, true);
```

Details do show the parameters:

```
2023-10-21 13:40:10.955 -05 [498923] DETAIL:  parameters: $1 = 'search_path', $2 = '"test", "public"', $3 = 'role', $4 = 'postgrest_test_anonymous', $5 = 'request.jwt.claims', $6 = '{"role":"p
ostgrest_test_anonymous"}', $7 = 'request.method', $8 = 'GET', $9 = 'request.path', $10 = '/projects', $11 = 'request.headers', $12 = '{"host":"localhost:3000","accept":"*/*","user-agent":"cur
l/7.81.0"}', $13 = 'request.cookies', $14 = '{}'
```

But this level of verbosity is not always enabled. Also they're not clear in `pg_stat_statements`.

## Solution

The first parameter of the `set_config` doesn't need to be parametrized, as it's always defined by us.

So we can convert them to:

```sql
select set_config('search_path', $1, true), set_config('role', $2, true), set_config('request.jwt.claims', $3, true), set_config('request.method', $4, true) ...
```

**Comment by laurenceisla** [comment]
I've been working in this  and noticed these cases:

- There are values [that can be set by the user in a request](https://postgrest.org/en/v8.0/api.html#accessing-request-headers-cookies-and-jwt-claims) when `db-use-legacy-gucs` is enabled for Postgres 13 and below.
- Also, these settings are done by the user in the DB and the config file/env vars:
https://github.com/PostgREST/postgrest/blob/5c9c7f4ff4dd0ef659206f1cb17502bb126d8f25/src/PostgREST/Query.hs#L259-L260

E.g. `app-settings-anysetting = ...`

Aside from those the rest are hardcoded directly. Not sure about the second case but the first is a no-go. 

Would it be OK to leave those parameterized while the others are not? The problem of unclear logs may persist/aggravate that way. Or maybe do not apply this if there's legacy GUCs? Still not convinced about the second case, though.

**Comment by steve-chavez** [comment]
@laurenceisla Re `db-use-legacy-gucs`, this might be a good opportunity (since we're going to do a major version) to drop the config altogether and only use the new JSON gucs.

**Comment by gmichalec-pandora** [comment]
In case anyone else stumbles on this - this change breaks support for the old 'request.jwt.claim.jti'. The new syntax can be seen here: https://postgrest.org/en/v12/references/auth.html#custom-validation
I wish there had been a clearer note in the changelog - it took me quite a while to figure out why weren't logging user transactions.  `Removed db-use-legacy-gucs` doesn't tell you much if you don't have the context . I appreciate the work done here, but clearly documenting breaking changes helps us be more confident in performing upgrades.

**Comment by steve-chavez** [comment]
@gmichalec-pandora You're right, thank you. We made the clarification on https://github.com/PostgREST/postgrest/pull/3287
