### ISSUE TITLE
Apply all function settings as transaction-scoped settings

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#3061]
## Problem

Currently, only `statement_timeout` is applied https://postgrest.org/en/latest/references/transactions.html#function-settings.

Applying other settings like `plan_filter.statement_cost_limit` is not possible.

```sql
CREATE OR REPLACE FUNCTION myfunc()
RETURNS void as $$
  SELECT pg_sleep(3); -- simulating some long-running process
$$
LANGUAGE SQL
SET plan_filter.statement_cost_limit TO 1300;
```  

## Solution

Apply all function settings.

## Notes

Not necessary to test with `plan_filter.statement_cost_limit`, we can use some others like:
https://github.com/PostgREST/postgrest/blob/91d53852370f5bf5ef1ecaa69b9ee7b8435b63a1/test/io/fixtures.sql#L19-L20

Also consider that applying some settings require privileges, see https://github.com/PostgREST/postgrest/pull/3058

**Comment by taimoorzaeem** [comment]
@steve-chavez Thoughts on implementing this? This would involve looking up and parsing all settings for each function which would mean that we have to keep a table for these settings and apply it. For `statement_timeout`, we did parsing in `SchemeCache.hs` like:
https://github.com/PostgREST/postgrest/blob/cbfff2804d81b19e19aa948c5b9e8030b5195a13/src/PostgREST/SchemaCache.hs#L433-L436

and also added this new setting to `data Routine = ...`. Parsing `352` different settings for all functions seems like a lot. WDYT??
