### ISSUE TITLE
Post-request hook possible?

### ISSUE THREAD

**Issue by dvv** [PostgREST/postgrest#3084]
Hi!

I wonder if we could have a post-request db hook in addition to pre-request one?
The rationale is to sanitize errors or to reconcile just in-place.
It could be given all available info from `get stacked diagnostics` and raise more meaningful messages or just rewrite the json data.

TIA

**Comment by steve-chavez** [comment]
Hey @dvv,

Yes, this is a good idea. There was a similar discussion on https://github.com/PostgREST/postgrest/issues/2706#issuecomment-1484037839. Let's continue there.
