### ISSUE TITLE
create a mime handler for application/vnd.openxmlformats-officedocument.wordprocessingml.document

### ISSUE THREAD

**Issue by fjf2002** [PostgREST/postgrest#3089]
### Environment

* PostgreSQL version: 16
* PostgREST version: 12.0.0
* Operating system: Debian bookworm

### Description of issue

Hello @steve-chavez,

thanks a lot for reworking the media-type handlers.

Currently I'm trying to understand the docs at https://postgrest.org/en/v12.0/references/api/media_type_handlers.html#handler-function .

The first example does work for me; however when I replace everywhere `application/vnd.twkb` with `application/vnd.openxmlformats-officedocument.wordprocessingml.document`, I get the error `HTTP/1.1 415 Unsupported Media Type` with body
```json
{"code":"PGRST107","details":null,"hint":null,"message":"None of these media types are available: application/vnd.openxmlformats-officedocument.wordprocessingml.document"}
```

I checked that I indeed have created the domain:
```sql
CREATE DOMAIN "application/vnd.openxmlformats-officedocument.wordprocessingml.document" AS bytea
```

What am I doing wrong?

**Comment by steve-chavez** [comment]
Hey @fjf2002,

Looks like that media type surpasses PostgreSQL identifier length:

```sql
CREATE DOMAIN "application/vnd.openxmlformats-officedocument.wordprocessingml.document" AS bytea;
NOTICE:  identifier "application/vnd.openxmlformats-officedocument.wordprocessingml.document" will be truncated to "application/vnd.openxmlformats-officedocument.wordprocessingml."
```

As a workaround you could use the ["any" handler](https://postgrest.org/en/v12.0/references/api/media_type_handlers.html#the-any-handler), which also works on functions as mentioned on https://github.com/PostgREST/postgrest/issues/2188#issuecomment-1839485859

---

One solution for this could be allowing to return a wrapper composite type that has an `enum`:

```sql
CREATE TYPE spreadsheet_content AS (content bytea, mt excel_mt);

CREATE TYPE excel_mt AS ENUM (
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
,  'application/excel'
);

CREATE OR REPLACE FUNCTION .. RETURN excel_mt ..
```

I don't see other way to define the media statically on the function.

**Comment by steve-chavez** [comment]
>  * In case of `*/*` return type and `*/*` or missing `Accept` header, PostgREST will send `Content-Type: application/json`.
>  * In case of `*/*` return type and any concrete `Accept` header, PostgREST will send *that request header mime type* as Response `Content-Type`. (**Is this really what you want?**)

@fjf2002 Right, setting the `Content-Type` ourselves seemed convenient for the user but now is clear it's incorrect. How about if we instead make it always return `application/octet-stream`? That should be the most generic media type ([SO link](https://stackoverflow.com/questions/4405894/content-type-when-serving-a-file-in-a-generic-handler)).

https://github.com/PostgREST/postgrest/blob/0c65bf494d75fbb2b8650eba1385b8d2c5d042d2/src/PostgREST/Plan.hs#L1008-L1010


> I can modify the Content-Type of the response by setting PERFORM set_config('response.headers', '[{"Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document"}]', true); inside the function.

Yes, correct.

> I suppose this hinders me to use an "any handler" for any other function that would be based on any other data type in the whole database (for example, your example with the `*/*` xml handler at https://postgrest.org/en/v12.0/references/api/media_type_handlers.html#the-any-handler)?

Just fixed that section to use a `bytea` instead (https://github.com/PostgREST/postgrest-docs/pull/717).

**Comment by fjf2002** [comment]
@steve-chavez: Thanks very much for your quick fixes and clarification. That should quite make sense.

**Comment by steve-chavez** [comment]
> How about if we instead make it always return application/octet-stream? That should be the most generic media type 

Fixing this on https://github.com/PostgREST/postgrest/pull/3103

> As you said, unfortunately I cannot have a domain type application/vnd.openxmlformats-officedocument.wordprocessingml.document since this identifier is too long.

For now I'll document this is a limitation and recommend using the any handler as workaround. The `enum` approach ([proposed above](https://github.com/PostgREST/postgrest/issues/3089#issuecomment-1839503912)) looks too complicated.
