### ISSUE TITLE
Nested Empty Embed - Filter Embedded Resource without Selecting It

### ISSUE THREAD

**Issue by jdgamble555** [PostgREST/postgrest#3093]
We need a way to filter the embedded resources without selecting the embedded resource.  Currently, I can do something complex like this:

### Example

Assuming I have something like this:
```
posts
- post_id
- status
-...
tags
- tag_id
- post_id
- PK (post_id, tag_id)
- ...
post_tag
- post_id
- tag_id
```

And I want to select all tags from published posts:

```http
GET /tags?select=*,post_tag!inner(posts!inner())&post_tag.posts.status=published
```
This is **amazing** that I can do this, but I get extra selections I don't need:
```ts
{
  tag_id: '100b8d2b-10c2-48a5-959c-053cd08419c9',
  name: 'Hooks',
  created_at: '2023-12-06T03:27:39.647512+00:00',
  updated_at: '2023-12-06T03:27:39.647512+00:00',
  post_tag: [ {} ]
}
```
It's great I can filter on `post_tag`, but I don't actually want to select it.  To me it is odd that the filter is declared in the `select` in the first place, but I understand it was made this way for a reason.

Perhaps a way to fix this would be something like adding a marker before `$` or `%`:

```http
GET /tags?select=*,%post_tag!inner(posts!inner())&post_tag.posts.status=published
```

**SIde Note:** - In reality I want to sort by the number of tags, but that is different feature request.

J

**Comment by steve-chavez** [comment]
> We need a way to filter the embedded resources without selecting the embedded resource.

@jdgamble555  This is already possible https://postgrest.org/en/stable/references/api/resource_embedding.html#empty-embed

Will close but let me know if that doesn't solve it.

**Comment by laurenceisla** [comment]
To test this using our fixtures:

```bash
curl "localhost:3000/entities?select=name,child_entities(grandchild_entities())&child_entities.grandchild_entities=not.is.null&child_entities=not.is.null"
```

The response is:

```json
[{"name":"entity 1","child_entities":[{}, {}]}]
```

The expected one is:

```json
[{"name":"entity 1"}]
```

**Comment by steve-chavez** [comment]
> curl "localhost:3000/entities?select=name,child_entities(grandchild_entities())&child_entities.grandchild_entities=not.is.null&child_entities=not.is.null"

I see, we need to make the [empty embed](https://postgrest.org/en/stable/references/api/resource_embedding.html#empty-embed) nested then.
