### ISSUE TITLE
PGRST301 - JWT ES512 - JWK

### ISSUE THREAD

**Issue by nlenew** [PostgREST/postgrest#3116]
### Environment

* PostgreSQL version: 11
* PostgREST version: 12
* Operating system: Linux

### Description of issue

Hi,

I am trying to configure Postgrest to authenticate with a JWT token with EC512 algorithm.
i have generated the JWK and set it into my configuration like this : 

```yaml
jwt-secret = "@conf/jwk"
```

making reference to my file content (obfuscated) :

```
{\"kty\":\"EC\",\"d\":\"ACqvzPAj4vYFO5AfUPyNx2DvKyuz...\",\"use\":\"sig\",\"crv\":\"P-521\",\"key_ops\":[\"verify\"],\"x\":\"AXBPsxc8Jt6lGAVcTY7AZNiDIgwKegue57QjjINei...\",\"y\":\"AQnWb-CGpuxFqe9FsqungSolQ8PJPe3...\",\"alg\":\"EC512\"}
```

But I always have the response 401 :

```json
{
    "code": "PGRST301",
    "details": null,
    "hint": null,
    "message": "JWSError JWSInvalidSignature"
}
```

I have generated my JWK with com.nimbusds.jose dependency.
I am well sending the bearer in Authorization header and if I decode it on my side it is OK (with public key)

Can you help me making it work ? Am I wrong with some configurations ?

Thanks a lot

**Comment by laurenceisla** [comment]
Hi. I think the `alg` should be: `"alg": "ES512"`. Also I don't think you need to escape the quotation marks `"` if you're using an external file.

**Comment by nlenew** [comment]
Hi,

Thank you for spotting the wrong algorithm. I have updated it and used the unwrapped jwk but still having the same error.
Going on my investigation.
If you have any other ideas don't hesitate

Thank you

**Comment by nlenew** [comment]
Finally, I make it works. My configuration file location was wrong and it didn't use the external jwk file

Thanks for the support

**Comment by laurenceisla** [comment]
Great!

>  Is there a way to add debug logs to have access to a clearer message ?

Not for now. #1840 tracks this problem.
