### ISSUE TITLE
Upgrading from 10 to 12 has slowed RLS query down massively

### ISSUE THREAD

**Issue by volkandkaya** [PostgREST/postgrest#3143]
### Environment

* PostgreSQL version: 13
* PostgREST version: 12.0.2
* Operating system: Ubuntu

### Description of issue

**Expected**: Fast query for RLS, when using bypass queries are fast.

**Actual**: After upgrading queries on production are slow.

For example (but not limited to as it is the same for other tables and reading data)

Went from 200ms -> 1.3seconds

It is patching some json data 40kb to jsonb field

/rest/v1/page_versions?id=eq.f06559cc
Request Method:
PATCH

jwt;dur=401.9, parse;dur=408.2, plan;dur=42.1, transaction;dur=25191.8, response;dur=2.2

X-Kong-Upstream-Latency: 1052

Also upgraded to latest Supabase-js

Any tips would be much appreciated, I really wanted the benefit of JWT caching

**Extra notes:**

get request to same table

- jwt;dur=211.6, parse;dur=473.6, plan;dur=60.2, transaction;dur=676.9, response;dur=2.2
- X-Kong-Upstream-Latency: 527

Also

- Requests to supabase auth took 130ms 
- On supabase similar requests were fast so maybe it is to do with complex RLS, but they worked great on v10

**Comment by steve-chavez** [comment]
Please isolate the problem to just PostgREST. Ideally with plain `curl` calls, sample schema and no reverse proxy.

There are lots of details which are vendor specific.

**Comment by volkandkaya** [comment]
v12

Aggregate  (cost=21.09..21.11 rows=1 width=144) (actual time=512.451..512.452 rows=1 loops=1)
  CTE pgrst_source
    ->  Limit  (cost=13.04..21.06 rows=1 width=19) (actual time=512.401..512.403 rows=1 loops=1)
          ->  Index Scan using page_versions_pkey on page_versions  (cost=13.04..21.06 rows=1 width=19) (actual time=512.399..512.401 rows=1 loops=1)
                Index Cond: (id = '2033d9d1-c61c-4b0a-98d1-f18630c05b5b'::uuid)
                Filter: (hashed SubPlan 1)
                SubPlan 1
                  ->  Function Scan on page_ids_by_user  (cost=0.25..10.25 rows=1000 width=16) (actual time=512.188..512.222 rows=497 loops=1)
  ->  CTE Scan on pgrst_source  (cost=0.00..0.02 rows=1 width=32) (actual time=512.403..512.405 rows=1 loops=1)
Planning Time: 0.503 ms
Execution Time: 512.546 ms


v10


Aggregate  (cost=21.09..21.11 rows=1 width=112) (actual time=52.853..52.854 rows=1 loops=1)
  CTE pgrst_source
    ->  Limit  (cost=13.04..21.06 rows=1 width=19) (actual time=52.827..52.830 rows=1 loops=1)
          ->  Index Scan using page_versions_pkey on page_versions  (cost=13.04..21.06 rows=1 width=19) (actual time=52.825..52.828 rows=1 loops=1)
                Index Cond: (id = '2033d9d1-c61c-4b0a-98d1-f18630c05b5b'::uuid)
                Filter: (hashed SubPlan 1)
                SubPlan 1
                  ->  Function Scan on page_ids_by_user  (cost=0.25..10.25 rows=1000 width=16) (actual time=52.635..52.669 rows=497 loops=1)
  ->  CTE Scan on pgrst_source  (cost=0.00..0.02 rows=1 width=32) (actual time=52.829..52.833 rows=1 loops=1)
Planning Time: 0.357 ms
Execution Time: 52.915 ms

**Comment by volkandkaya** [comment]
Same server, same db, same query, all I did was change v12 -> v10 in docker file.

http:///0.0.0.0:8000/rest/v1/page_versions?select=name&id=eq.2033d9d1-c61c-4b0a-98d1-f18630c05b5b

**Comment by steve-chavez** [comment]
> same query,

So the query hasn't changed between versions. If you disable RLS, are the execution times the same on both versions?

If so, can you share your RLS policies?

**Comment by volkandkaya** [comment]
Nothing changed just docker verisons.

Service role is fast on both (bypass RLS).

```sql
CREATE FUNCTION public.page_ids_by_user() RETURNS SETOF uuid
    LANGUAGE plpgsql SECURITY DEFINER
    AS $_$
BEGIN
    RETURN QUERY EXECUTE format(
    $query$ 
        SELECT page.page_id
        FROM public.page
        FULL OUTER JOIN public.team_page
        ON page.page_id = team_page.page_id
        FULL OUTER JOIN public.team
        ON team.id = team_page.team_id
        FULL OUTER JOIN public.team_user
        ON team_user.team_id = team.id
        where team_user.user_id = auth.uid()
        or page.user_id = auth.uid()
    $query$ 
  );
END 
$_$;
```

This RLS can be optimised but on v10 it is fast enough for now.

**Comment by steve-chavez** [comment]
@volkandkaya Please share the definition of `auth.uid()`.

**Comment by volkandkaya** [comment]
@steve-chavez 

```sql
CREATE FUNCTION auth.uid() RETURNS uuid
    LANGUAGE sql STABLE
    AS $$
  select 
  	coalesce(
		nullif(current_setting('request.jwt.claim.sub', true), ''),
		(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub')
	)::uuid
$$;
```

**Comment by steve-chavez** [comment]
> public.page_ids_by_user()

Share how `public.page_ids_by_user()` is used in your RLS policies. Share full RLS policies.

**Comment by steve-chavez** [comment]
If both PostgREST v10 and v12 generated queries are fast (and same query/plan) without RLS then the problem lies somewhere in your RLS policies. 

At this point I cannot go further into your debugging your SQL. I suggest you try to isolate the problem and share a reproducible example which includes DDL with sample data. Otherwise I don't see anything to fix.

**Comment by volkandkaya** [comment]
Alright thanks, I will most likely optimise the RLS later and stick to v10 for now. I was hoping there was some weird edge case that could be fixed.

**Comment by steve-chavez** [comment]
> The difference between PostgREST 10 and PostgREST 12 is, that IIRC in PostgREST 11 we removed the request.jwt.claim.sub style to access JWT claims. This means that the following function now has a lot more work to do:

@wolfgangwalther Nice catch! Yes, this actually happened on v12: https://github.com/PostgREST/postgrest/pull/3032

> PostgreSQL version: 13

@volkandkaya The above change will happen anyway if you ever upgrade to PostgreSQL 14. The `request.jwt.claim.sub` will be null starting from that version (needed for compatibility with pg 14, see https://postgrest.org/en/v11.2/references/configuration.html#db-use-legacy-gucs).
