### ISSUE TITLE
Returning mimetypes via aggregates only works for select=*

### ISSUE THREAD

**Issue by wolfgangwalther** [PostgREST/postgrest#3160]
Using the query from https://github.com/PostgREST/postgrest/issues/2826#issuecomment-1889897084 as an example:

```sql
WITH pgrst_source AS ( SELECT "test"."lines".* FROM "test"."lines")
SELECT
    null::bigint AS total_result_set,
    pg_catalog.count(_postgrest_t) AS page_total,
    twkb_agg(_postgrest_t::"test"."lines") AS body,
    nullif(current_setting('response.headers', true), '') AS response_headers,
    nullif(current_setting('response.status', true), '') AS response_status,
    '' AS response_inserted
FROM ( SELECT * FROM pgrst_source ) _postgrest_t;
```

The cast to `::"test"."lines"` makes it impossible to use anything else than `select=*`.

I see why the cast is implemented: This allows the aggregate function to be matched on the argument type for different endpoints. But it does not allow selecting only a subset of columns or computed columns.

In my case, I just tried to implement a generic CSV handler like this:

```sql
CREATE DOMAIN "text/csv" AS text;

CREATE FUNCTION jsonb_state_transfn(state jsonb, elem anyelement) RETURNS jsonb
STABLE
PARALLEL SAFE
LANGUAGE plpgsql AS $$
BEGIN
  RETURN state || to_jsonb(elem);
END$$;

CREATE FUNCTION text_csv_agg_finalfn(state jsonb) RETURNS "text/csv"
TRANSFORM FOR TYPE jsonb
STABLE
PARALLEL SAFE
LANGUAGE plpython3u AS $$
  from pandas import DataFrame
  df = DataFrame(state)
  return df.to_csv()
$$;

CREATE AGGREGATE text_csv_agg(anyelement) (
  INITCOND  = '[]',
  STYPE     = jsonb,
  SFUNC     = jsonb_state_transfn,
  FINALFUNC = text_csv_agg_finalfn
);
```

But this quickly fails, because I want to select different columns, or just in a different order - and then the cast fails.

**Comment by steve-chavez** [comment]
> As a solution, we could apply the cast only when select=*. For all other select= values, we remove the cast, thus leaving us with twkb_agg(_postgrest_t) AS body,. This should make generic handlers work better.

It's a bit messy but seems it could work.

> I see why the cast is implemented: This allows the aggregate function to be matched on the argument type for different endpoints. But it does not allow selecting only a subset of columns or computed columns.

I'm wondering if we should support different arguments at all. If we have:

```sql
CREATE OR REPLACE FUNCTION twkb(anyelement) RETURNS "application/vnd.twkb" AS $$
  select twkb_agg(x);
$$ LANGUAGE SQL IMMUTABLE;
```

Then the user can do a `pg_typeof` inside that function and do a special case for a particular endpoint if needed (I believe this should be rare) or the user could also check `request.path`.

So how about dropping specific aggregates? It'd be breaking but it would solve `select`. This way we can also focus on creating pg extensions that solve this generically. Like `pg_csv`.

**Comment by steve-chavez** [comment]
> As a solution, we could apply the cast only when select=*. For all other select= values, we remove the cast, thus leaving us with twkb_agg(_postgrest_t) AS body,. This should make generic handlers work better.

So if user does `/lines?select=id,name Accept: application/vnd.twkb` that would fail because `function twkb_agg(lines)` wouldn't work (it needs the exact type). That would be confusing. 

I believe only using the `anyelement` would be the right choice.
