### ISSUE TITLE
Dump Schema Cache through Admin API

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#3210]
## Problem

No way to dump the schema cache of a running instance, it's only possible to do it at startup with:

```
postgrest-with-postgresql-16 postgrest-run --dump-schema
```

## Solution

Use the admin api ([ref](https://postgrest.org/en/stable/references/admin.html#health-check)) to output the schema cache of a running instance:

```bash
$ curl localhost:3001/schema_cache

200 OK
Content-Type: application/json

{..}
```

**Comment by SkyWriter** [comment]
Since I am in the context, I am hopping on this one next :+1:
