### ISSUE TITLE
Regression / breaking change for RPCs with SET

### ISSUE THREAD

**Issue by wolfgangwalther** [PostgREST/postgrest#3242]
### Environment

* PostgreSQL version: 15.x
* PostgREST version: 12.1-dev
* Operating system: Linux

### Description of issue

#3142 introduced quite a big breaking change - which I would consider a regression / bug. Applying **all** settings is never going to be correct / expected.

Take this for example:

```sql
create function do_something_dangerous() returns something
security definer
set search_path to pg_catalog, pg_temp
language plpgsql as $$
...
$$;
```

I have a few `SECURITY DEFINER` functions in my api. Best practice for security reasons is to add `pg_catalog, pg_temp` as a search_path for those kind of functions. After #3142, this suddenly changes the search_path for the **whole transaction**. This breaks, for example, computed fields on the returned value - and probably more.

I do have other cases of `SET`tings that I **don't want to have applied on the transaction level**. There is a reason I set them on the function and not for the authenticator role or so.

While I like the idea of hoisting some `SET`tings to the transaction level.. the current implementation is a problem. I don't even see a check for `role`, so will a `CREATE FUNCTION xxx SET ROLE TO y` be hoisted, too? Bad.

I think we should do at least one of, but possibly both of:
- Have an allowlist of explicitly named parameters instead of just setting all of them.
- Prefix those settings with `pgrst.xxx` or `tx.xxx` - and then set it without that prefix on the transaction level.

This needs to happen before we make the next release, otherwise we can't release a minor. In the current form, this is quite a breaking change.

**Comment by steve-chavez** [comment]
How about making it a deny list instead? The only settings we need to ensure are not modified are the `role` and the `search_path` because of impersonation + schema isolation. I can make a quick fix for this.

https://github.com/PostgREST/postgrest/blob/fac7acafa33d360da74894207299a7bbd51d2298/src/PostgREST/Query.hs#L252

> Have an allowlist of explicitly named parameters instead of just setting all of them.

This will be bad for maintenance because we can't list all extensions settings. For example `plan_filter.statement_cost_limit ` ([ref](https://github.com/pgexperts/pg_plan_filter)). If new extensions come or if the extension changes the setting name, we would have to patch PostgREST

> Prefix those settings with pgrst.xxx or tx.xxx - and then set it without that prefix on the transaction level.

This would be bad for DX. Specially since `statement_timeout` is standard. Increases users cognitive load plus some support burden.

I think the deny list for search_path and role should be enough.

**Comment by steve-chavez** [comment]
I see your point. Too bad we can't have this working transparently.

So how about a `db-hoisted-tx-settings`. For now I think the default will be:

- statement_timeout
- plan_filter.statement_cost_limit
- default_transaction_isolation
- ...

**Comment by steve-chavez** [comment]
@taimoorzaeem Could you take this one? It's pretty much a follow up of https://github.com/PostgREST/postgrest/pull/3142

**Comment by taimoorzaeem** [comment]
@steve-chavez @wolfgangwalther @laurenceisla 

Assigning list to config in `test_io.py` raises this type error. How do I assign the list to the config to test it?

```python
def test_multiple_func_settings(defaultenv):
        "check multiple function settings are applied"
    
        env = {
            **defaultenv,
            "PGRST_DB_HOISTED_TX_SETTINGS": ["work_mem", "statement_timeout"],
        }
    
>       with run(env=env) as postgrest:
.
.
.
filename = ['work_mem', 'statement_timeout']

>   ???
E   TypeError: expected str, bytes or os.PathLike object, not list

<frozen os>:812: TypeError

```

**Comment by laurenceisla** [comment]
> How do I assign the list to the config to test it?

Using a string doesn't work?

```
        env = {
            **defaultenv,
            "PGRST_DB_HOISTED_TX_SETTINGS": "work_mem,statement_timeout",
        }
```
