### ISSUE TITLE
Hard to upgrade from `v9.0.1`

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#3290]
## Problem

v10.0.0 introduced one-to-one relationship detection https://github.com/PostgREST/postgrest/pull/2439, which changed the json output of responses using resource embedding.  For upgrading, adding computed relationships was recommended but this is considerable work for projects that have many tables. For this reason some projects are stuck on `v9.0.1` .

## Proposal

The following config can be used to determine which relationships will be represented as json objects. By default it will be:

```
db-resource-embedding-single = "many-to-one, one-to-one"
```

So projects stuck on `9.0.1` can do:

```
db-resource-embedding-single = "many-to-one"
```

## Related

- https://github.com/PostgREST/postgrest/issues/2066

**Comment by steve-chavez** [comment]
Yeah, I don't like it either. It also provides an easy way to have incompatible outputs between postgREST APIs, that could cause trouble.

> We should provide better migration paths, instead: Docs, Tools, anything that helps the actual migration.
> Could this be (partly) automated with dynamic SQL to create the computed relationships?

I was thinking we could have a `postgrest --dump-relationships=one-to-one` command, its output could help with generating the dynamic SQL.

**Comment by steve-chavez** [comment]
Just using `jq` looks like a good idea.

Removing some unnecessary keys:

```bash
postgrest-with-postgresql-16 -f test/spec/fixtures/load.sql postgrest-run --dump-schema \
  | jq '.dbRelationships | .[] | .[1] | .[] | select(.relCardinality.tag == "O2O")' \
  | jq 'del(.relFTableIsView,.relTableIsView,.tag,.relIsSelf)'
```

We get an output like:

```json
{
  "relCardinality": {
    "relColumns": [
      [
        "id",
        "id"
      ],
      [
        "code",
        "code"
      ]
    ],
    "relCons": "students_info_id_code_fkey",
    "tag": "O2O"
  },
  "relForeignTable": {
    "qiName": "students",
    "qiSchema": "test"
  },
  "relTable": {
    "qiName": "students_info",
    "qiSchema": "test"
  }
}

{
  "relCardinality": {
    "relColumns": [
      [
        "id",
        "id"
      ],
      [
        "code",
        "code"
      ]
    ],
    "relCons": "students_info_id_code_fkey",
    "tag": "O2O"
  },
  "relForeignTable": {
    "qiName": "students_info",
    "qiSchema": "test"
  },
  "relTable": {
    "qiName": "students",
    "qiSchema": "test"
  }
}
```

The relevant information is there though it's cumbersome with a lot of o2o. And we need to define computed rels for both ends..

Next steps:

- [ ] Create a bash script to make this easier. It should parse the json output and then generate the SQL statements.
- [ ] Include the bash script on the v9.0.1 release artifacts.

**Comment by steve-chavez** [comment]
We need to create two computed rels, an `o2m` and a `m2o` for correcting the `o2o` rel. So the resulting computed rels from the `students`/`students_info` example [shown above](https://github.com/PostgREST/postgrest/issues/3290#issuecomment-1977273873) should be:


```sql
-- students -> students_info o2m
create function students_info(students) returns setof students_info rows 1000 as $$
  select * from students_info where id = $1.id and code = $1.code
$$ language sql;

-- students_info -> students m2o
create function students(students_info) returns setof students rows 1 as $$
  select * from students where id = $1.id and code = $1.code
$$ language sql;

```

But there's a problem with the schema cache json output. It doesn't show on which table is the foreign key defined. So we cannot know to which table the "many" end belongs to.

So the current output is insufficient for having this automated :disappointed:.

---

Maybe the problem is that we add the relationship and the inverse relationship. If we only had one then this should be solvable.

**Comment by laurenceisla** [comment]
> It doesn't show on which table is the foreign key defined

I was having a similar issue when working on #3226, since we need to know to which table to insert first in a `o2o` relationship.

> the simplest solution would be to add an attribute to Cardinality.

So I think this solution would be necessary anyways.

**Comment by steve-chavez** [comment]
For this issue it doesn't seem worth it changing the Relationship type. Will close with https://github.com/PostgREST/postgrest/pull/3312.
