### ISSUE TITLE
Range operators cannot be used inside `or` without quoting

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#3368]
## Problem

This works:

```bash
curl -g 'localhost:3000/ranges?range=adj.(3,10]&select=id'
[{"id":1}]
```

This doesn't:

```bash
curl -g 'localhost:3000/ranges?or=(range.adj.[3,10))&select=id'

{"code":"PGRST100","details":"unexpected \")\" expecting letter, digit, \"-\", \"->>\", \"->\" or delimiter(.)","hint":null,"message":"\"failed to parse logic tree ((range.adj.[3,10)))\" (line 1, column 19)"}

curl -g 'localhost:3000/ranges?or=(range.adj.(3,10])&select=id'

{"code":"PGRST100","details":"unexpected \"]\" expecting letter, digit, \"-\", \"->>\", \"->\" or delimiter (.)","hint":null,"message":"\"failed to parse logic tree ((range.adj.(3,10]))\" (line 1, column 19)"}
```

## Possible Solutions

- or syntax without values: https://github.com/PostgREST/postgrest/issues/1970#issuecomment-996175608
- the SEARCH method to parametrize the values https://github.com/PostgREST/postgrest/issues/2125#issuecomment-1046202010

**Comment by steve-chavez** [comment]
Works!

```bash
curl -g 'localhost:3000/ranges?or=(range.adj."(3,10]")&select=id'

[{"id":1}]
```

I guess still a bug though.

**Comment by steve-chavez** [comment]
Right, maybe this is just a matter of docs then. It would be nice to have a mention about this gotcha on https://postgrest.org/en/v12/references/api/tables_views.html#operators

**Comment by laurenceisla** [comment]
Maybe this is related and should be added to the docs too. From this discussion https://github.com/PostgREST/postgrest/discussions/3466#discussion-6588261:

> ```bash
> curl --globoff 'http://example.com/table?select=*&and=(column->jsonlist.cs.["foo=()"]'
> ```
> 
> results in
> 
> ```json
> {"code":"22P02","details":"Token \"\"foo=(\" is invalid.","hint":null,"message":"invalid input syntax for type json"}
> ```

The solution is to wrap **the whole** JSON array value inside quotations, (not just the items). That is:

```bash
curl --globoff 'http://example.com/table?select=*&and=(column->jsonlist.cs."[\"foo=()\"]"'
```
