### ISSUE TITLE
Misleading error PGRST121

### ISSUE THREAD

**Issue by bjornharrtell** [PostgREST/postgrest#3404]
### Environment

* PostgreSQL version: 16
* PostgREST version: 12.0.2

### Description of issue

Response on error is `The message and detail field of RAISE 'PGRST' error expects JSON` but it apparently requires a specific schema for that JSON, fx. the detail JSON must be an object with status and headers fields.

**Comment by bjornharrtell** [comment]
I now see this is clarified in the documentation, but I still think the error is misleading.

**Comment by laurenceisla** [comment]
Yes, I think the `"message"` could be clarified and perhaps add the failed raised error to the `"details"`. Something like this:

```json
{
"message": "Could not parse JSON in the \"RAISE SQLSTATE 'PGRST'\" error",
"details": "Invalid JSON value for MESSAGE: {<here goes the failed MESSAGE>} and DETAIL: {<here goes the failed DETAIL>}",
...
}
```
