### ISSUE TITLE
arm builds failing in CI

### ISSUE THREAD

**Issue by wolfgangwalther** [PostgREST/postgrest#3439]
The arm / cabal builds are currently failing in CI. I think it's because the disk of the runner is full somehow - maybe not all temporary / build files are cleaned up anymore?

@laurenceisla since you set that arm host up, I think, can you have a look?

**Comment by laurenceisla** [comment]
I removed the generated `postgrest-build-*` directories manually. The runs should stop failing right now. I'm thinking maybe some failed runs didn't trigger the cleaning step, I'm opening a PR to solve that.

**Comment by steve-chavez** [comment]
Unrelated to this issue, but CI is kinda weird right now.

For example on the last [commit](https://github.com/PostgREST/postgrest/commit/3eff4670f07bec5da0b2c47ea458b816d6e49e72),  the load test results do not show and the link check is skipped. I do not understand its behavior.

**Comment by laurenceisla** [comment]
@steve-chavez Don't know about Loadtests, but the link check was skipped in the `main` branch back when `postgrest-docs` was used: https://github.com/PostgREST/postgrest-docs/commit/43a92d4e6b78f18650fbaf111f9b2c28472b4ae2

**Comment by laurenceisla** [comment]
> Edit: still, I'll keep an eye on the server to see if the problem persists.

Just noticed that this is still happening. The binaries are for version `10.2.0`, so there was a problem with the CI cleaning job in the `v10` branch. This PR should fix this #3459
