### ISSUE TITLE
Write docs for v12.2.0 minor release

### ISSUE THREAD

**Issue by wolfgangwalther** [PostgREST/postgrest#3501]
This is already listed in https://github.com/PostgREST/postgrest/issues/3113#issuecomment-1948631330, but to give this more visibility I'll create an issue about it.

Ever since merging the postgrest-docs repo into the core repo, we are supposed to merge docs together in the same PR as the corresponding feature. This didn't always happen initially, but we are getting better at it. However, we still have some unreleased feature commits on the main branch, which happened before the docs merge and thus have no corresponding docs written, yet.

This is blocking the next minor release, so needs to be taken care of.

I went through the changelog on main again, and I think the following still need to be documented:
- [ ] #3171, Add an ability to dump config via admin API - @skywriter
- [ ] #3210, Dump schema cache through admin API - @taimoorzaeem
- [ ] Deprecated: `Prefer: params=single-object` is deprecated. Use [a function with a single unnamed JSON parameter](https://postgrest.org/en/latest/references/api/stored_procedures.html#s-proc-single-json) instead. - @steve-chavez

@steve-chavez since you merged the first two and wrote the last yourself - can you take care of the docs for those to unblock a release?

There is also #3061, which is still undocumented, but also blocking a new minor release is #3242 which will be fixed in #3358. This essentially contains the docs for #3061, too.

**Comment by laurenceisla** [comment]
>     * [ ]  Deprecated: `Prefer: params=single-object` is deprecated. Use [a function with a single unnamed JSON parameter](https://postgrest.org/en/latest/references/api/stored_procedures.html#s-proc-single-json) instead. - @steve-chavez
> 

I think this is already documented? I can see the deprecation notices in:
- https://postgrest.org/en/latest/references/api/functions.html#functions-with-a-single-unnamed-json-parameter, as a Warning at the end of the section.
- https://postgrest.org/en/latest/references/api/preferences.html#single-json-object-as-function-parameter, as a Warning at the start of the section

**Comment by laurenceisla** [comment]
> I think this is already documented? I can see the deprecation notices in:

Ah, the link from the changelog is not working anymore though. Fixing in #3552

**Comment by steve-chavez** [comment]
I think we can do a new minor release now. @wolfgangwalther Should just doing `postgrest-release` be enough?

I just executed it and got:

```
Current version is 12.1
Updating postgrest.cabal ...
Updating CHANGELOG.md ...
Committing ...
Current version is 12.2.0
Updating postgrest.cabal ...
Committing (devel bump)...
Remote not found. Please push manually ...
```

I wonder why it didn't find the remote, I have:

```
git remote -v | grep PostgREST/postgrest
upstream        git@github.com:PostgREST/postgrest (fetch)
upstream        git@github.com:PostgREST/postgrest (push)
```

**Comment by laurenceisla** [comment]
Also, I think the next minor should be `12.1.0`, since [the latest release](https://github.com/PostgREST/postgrest/releases/tag/v12.0.3) was `12.0.3` . Unless I'm missing something, `postgrest-release` should use the current version in `postgrest.cabal`  for a minor release.

**Comment by laurenceisla** [comment]
> No, we agreed that uneven minor releases are the on-going development version.
> 

Ah, got it, it seems that I missed that.

**Comment by steve-chavez** [comment]
> I still want to check [this TODO](https://github.com/PostgREST/postgrest/issues/3113#issuecomment-1948631330) here:

If we do https://github.com/PostgREST/postgrest/pull/2052, then the next version should be a major one right? Not opposed if that's the case.

**Comment by steve-chavez** [comment]
> Yes - I would that right after we released the next minor.

Ok cool. So then I think we can release the minor now right?

**Comment by steve-chavez** [comment]
> It depends. If you agree that I can do https://github.com/PostgREST/postgrest/pull/2052 afterwards - fine.

For sure, I agree with that.

> In https://github.com/PostgREST/postgrest/pull/2052#issuecomment-1937538032 we discussed about adding the "this PG version will not be supported in the next major version"-deprecation-style check. This is the TODO I referenced here:

Oh ok. So we need to add a deprecation plus update this section [here](https://postgrest.org/en/v12/explanations/install.html#supported-postgresql-versions)?

**Comment by steve-chavez** [comment]
When trying it now I get:

```
$ postgrest-release 
Current version is 12.1
Updating postgrest.cabal ...
Updating CHANGELOG.md ...
Committing ...
Current version is 12.2.0
Updating postgrest.cabal ...
Committing (devel bump)...
Remote not found. Please push manually ...
```

**Comment by steve-chavez** [comment]
The jump from 12.0 to 12.2 might be confusing for users. Hm, we need to document that versioning policy somewhere.

**Comment by steve-chavez** [comment]
One other thing. I think we should change the CHANGELOG entries format to:

```
- <description, link to docs if feature> by <author> in <issue>
```

Instead of

```
- <issue>, <description> - <author>
```

That format is much readable for end users. 

Currently I have to edit the entries manually, check https://github.com/PostgREST/postgrest/releases/tag/v12.2.0

Ideally we would have the release notes semi-automated. Not sure how to automate the subheading, maybe it should be a suggestion on a PR.
