### ISSUE TITLE
Statically compiling postgrest

### ISSUE THREAD

**Issue by ruslantalpa** [PostgREST/postgrest#365]
I think we should try and compile v3 like described here
http://begriffs.com/posts/2015-08-11-dev-deploy-haskell-docker.html
https://github.com/nilcons/ghc-musl

**Comment by PierreR** [comment]
Thanks for the pointers. I haven't watched the video yet but wouldn't be much better to have this issue fixed: http://bugs.alpinelinux.org/issues/4257

There is a risk here to get an complicated docker build process which might stop being maintained in the future. To me a much more ideal situation  would be to have native `alpine` ghc and `stack` packages. Then you have the leverage to build a nice small docker image.

**Comment by PierreR** [comment]
I am also waiting for `stack` to offer the possibility to build inside custom small docker image. Right now, only Ubuntu precise is supported (which is not option for a small image). This is a known issue and I read somewhere that it might be fixed in a couple of weeks/months.

**Comment by PierreR** [comment]
Another alternative that does not require docker is described here:
https://getpocket.com/a/read/1084317437

**Comment by ruslantalpa** [comment]
The idea is not the docker thing (that is just the build env)
I was sugesting building the binary so that it does not have dependencies and its compiled with ghc that itself was built against musl so that the resulting bin is as small as posible, i doubt we depend much on things from glibc

**Comment by begriffs** [comment]
I'm OK with building binaries for several platforms at each release. If you figure out how to make a portable statically linked binary then we can distribute that instead, but things are OK for now.

**Comment by steve-chavez** [comment]
This would be specially useful on Windows, users keep reporting problems there.

Currently we require a full PostgreSQL installation in Windows to use pgrst and when the db is in another server that dependency seems too big. I don't know a way of getting just `libpq` on Windows(haven't tried [msys2](https://www.msys2.org/)).

**Comment by steve-chavez** [comment]
Closing in favor of #1295.
