### ISSUE TITLE
404 on RPCs after upgrading to 12.2.2 when using the in-db config

### ISSUE THREAD

**Issue by MHC2000** [PostgREST/postgrest#3660]
### Environment

* PostgreSQL version: 13
* PostgREST version: 12.2.2
* Operating system: SLES 15

### Description of issue

I've upgraded from release 12.2.1 to 12.2.2. 
After restarting the server the functions (RPC) are not working anymore. 
Getting 404 from my web server.
Tables seam to work and are reachable.

Didn't change anything on the configuration or something else, just replaced the binary and restarted.

12.2.1 worked, functions and views were reachable

**Comment by steve-chavez** [comment]
How can we reproduce? Do you have a sample function?

**Comment by MHC2000** [comment]
I'll try to extract a function which works without additional data from the database.

**Comment by laurenceisla** [comment]
If it's not, activate the [admin server port](https://postgrest.org/en/latest/references/configuration.html#admin-server-port) for a while, like `admin-server-port=3001`. Then query `localhost:3001/config` and check if you get the same result from both versions.

**Comment by MHC2000** [comment]
Sorry that it took so long. Our Test-server is quite ocupied.
If created a test function which works with 12.2.1 and with 12.2.2 doesn't work anymore:
The error im getting from postgrest 

```
{
  "code": "PGRST202",
  "details": "Searched for the function api.test without parameters, but no matches were found in the schema cache.",
  "hint": null,
  "message": "Could not find the function api.test without parameters in the schema cache"
}
```

this is the function definition
```
-- FUNCTION: api.test()

-- DROP FUNCTION IF EXISTS api.test();

CREATE OR REPLACE FUNCTION api.test(
	)
    RETURNS jsonb
    LANGUAGE 'sql'
    COST 100
    VOLATILE PARALLEL SAFE 
AS $BODY$
SELECT null::jsonb;
$BODY$;

ALTER FUNCTION api.test()
    OWNER TO admin_users;

GRANT EXECUTE ON FUNCTION api.test() TO admin_users;

GRANT EXECUTE ON FUNCTION api.test() TO qqzcms2;

REVOKE ALL ON FUNCTION api.test() FROM PUBLIC;

```

and that's the log of postgrest
![image](https://github.com/user-attachments/assets/d8257ca6-479e-4851-ae3e-4662ef1040f0)

What makes me wonder, the log quotes 75 found functions but pg_admin says 402.
But there are a lot of computed relation functions in the api, so I'm not sure if the count includes them

![image](https://github.com/user-attachments/assets/b28512e9-9e47-4bac-89da-a3de575e7b7d)

**Comment by steve-chavez** [comment]
@MHC2000 Have you refreshed the schema cache after creating the function?

Try doing `curl "http://localhost:3001/schema_cache"` https://docs.postgrest.org/en/v12/references/admin_server.html#runtime-schema-cache

And grep for your function.

**Comment by MHC2000** [comment]
I've stopped the whole server and started it new after creating the function. 
As said it's just a test function. 
all the other already existing functions don't work as well. 
just wanted to show even a simple function doesn't work. 
After switching back to 12.2 1 the test function and all the others work with any problems

**Comment by laurenceisla** [comment]
> I assume v12.2.2 is falling back to reading this for the schema cache, because it hasn't loaded the `db-schemas` variable from the database, yet.

I'm pretty sure this is it. I can also reproduce this by setting `pgrst.db_schemas = 'api'` and only the `public` functions are loaded at startup (needs reloading to get the correct schema).

> Probably related to https://github.com/PostgREST/postgrest/commit/6be59066df9185e1e603ab6a4a9aa5c3b5d6d49a.

Can confirm. Using the `v12.2.2` tag, checking out to the parent commit 8715e426c0a63fbb41f36636a77157f157a0fad0 loads the `api` schema at startup.  Checking out to the commit with the change f09655b7a6f9961eda609b182e072e84472dcec9, it loads the `public` schema.

> In public there are 248 functions, so the numbers don't match either.

That depends, if those functions do not have named parameters, then they won't be included (unless it has a single unnamed parameter of certain types). This also applies to computed relationships, if the parameters are not named, then they're not included.

Try executing the following query that PostgREST uses to retrieve functions. It should return 75 from the `public` schema:

<details><summary>Functions Query</summary>
<p>

```sql
  WITH
  base_types AS (
    WITH RECURSIVE
    recurse AS (
      SELECT
        oid,
        typbasetype,
        COALESCE(NULLIF(typbasetype, 0), oid) AS base
      FROM pg_type
      UNION
      SELECT
        t.oid,
        b.typbasetype,
        COALESCE(NULLIF(b.typbasetype, 0), b.oid) AS base
      FROM recurse t
      JOIN pg_type b ON t.typbasetype = b.oid
    )
    SELECT
      oid,
      base
    FROM recurse
    WHERE typbasetype = 0
  ),
  arguments AS (
    SELECT
      oid,
      array_agg((
        COALESCE(name, ''), -- name
        type::regtype::text, -- type
        CASE type
          WHEN 'bit'::regtype THEN 'bit varying'
          WHEN 'bit[]'::regtype THEN 'bit varying[]'
          WHEN 'character'::regtype THEN 'character varying'
          WHEN 'character[]'::regtype THEN 'character varying[]'
          ELSE type::regtype::text
        END, -- convert types that ignore the length and accept any value till maximum size
        idx <= (pronargs - pronargdefaults), -- is_required
        COALESCE(mode = 'v', FALSE) -- is_variadic
      ) ORDER BY idx) AS args,
      CASE COUNT(*) - COUNT(name) -- number of unnamed arguments
        WHEN 0 THEN true
        WHEN 1 THEN (array_agg(type))[1] IN ('bytea'::regtype, 'json'::regtype, 'jsonb'::regtype, 'text'::regtype, 'xml'::regtype)
        ELSE false
      END AS callable
    FROM pg_proc,
         unnest(proargnames, proargtypes, proargmodes)
           WITH ORDINALITY AS _ (name, type, mode, idx)
    WHERE type IS NOT NULL -- only input arguments
    GROUP BY oid
  )
  SELECT
    pn.nspname AS proc_schema,
    p.proname AS proc_name,
    d.description AS proc_description,
    COALESCE(a.args, '{}') AS args,
    tn.nspname AS schema,
    COALESCE(comp.relname, t.typname) AS name,
    p.proretset AS rettype_is_setof,
    (t.typtype = 'c'
     -- if any TABLE, INOUT or OUT arguments present, treat as composite
     or COALESCE(proargmodes::text[] && '{t,b,o}', false)
    ) AS rettype_is_composite,
    bt.oid <> bt.base as rettype_is_composite_alias,
    p.provolatile,
    p.provariadic > 0 as hasvariadic,
    lower((regexp_split_to_array((regexp_split_to_array(iso_config, '='))[2], ','))[1]) AS transaction_isolation_level,
    coalesce(func_settings.kvs, '{}') as kvs
  FROM pg_proc p
  LEFT JOIN arguments a ON a.oid = p.oid
  JOIN pg_namespace pn ON pn.oid = p.pronamespace
  JOIN base_types bt ON bt.oid = p.prorettype
  JOIN pg_type t ON t.oid = bt.base
  JOIN pg_namespace tn ON tn.oid = t.typnamespace
  LEFT JOIN pg_class comp ON comp.oid = t.typrelid
  LEFT JOIN pg_description as d ON d.objoid = p.oid
  LEFT JOIN LATERAL unnest(proconfig) iso_config ON iso_config LIKE 'default_transaction_isolation%'
  LEFT JOIN LATERAL (
    SELECT
      array_agg(row(
        substr(setting, 1, strpos(setting, '=') - 1),
        substr(setting, strpos(setting, '=') + 1)
      )) as kvs
    FROM unnest(proconfig) setting
    WHERE setting ~ ANY('{}')
  ) func_settings ON TRUE
  WHERE t.oid <> 'trigger'::regtype AND COALESCE(a.callable, true)
  AND prokind = 'f'
  AND p.pronamespace = ANY('{public}'::regnamespace[]);
```

</p>
</details> 


> I also figured that in 12.2.1 the command `killall -SIGUSR2 postgrest` doesn't change the cache.

The `SIGUSR2` signal reloads only the config, `SIGUSR1` reloads the schema cache.  Try using it after starting `v12.2.2` to check if it loads the correct schema.

**Comment by MHC2000** [comment]
@laurenceisla 
Executing your query gives me the count of 86 for `public `schema, and 404 for `api `schema

> The SIGUSR2 signal reloads only the config, SIGUSR1 reloads the schema cache. Try using it after starting v12.2.2 to check if it loads the correct schema.
Thanks for the hint, will try that asap.

**Comment by steve-chavez** [comment]
Can reproduce by doing:

```bash
$ echo "alter role postgrest_test_authenticator set pgrst.db_schemas = 'test';" >> test/spec/fixtures/schema.sql 
$ PGRST_DB_SCHEMAS="public" postgrest-with-postgresql-16  -f test/spec/fixtures/load.sql postgrest-run

28/Jul/2024:19:54:31 -0500: Schema cache loaded 10 Relations, 9 Relationships, 8 Functions, 15 Domain Representations, 4 Media Type Handlers, 1194 Timezones
28/Jul/2024:19:54:31 -0500: Config reloaded
```
