### ISSUE TITLE
Migrate to readthedocs "addons"

### ISSUE THREAD

**Issue by wolfgangwalther** [PostgREST/postgrest#3672]
Readthedocs migrates the menu in the lower left to something else called "addons".

See:
- https://about.readthedocs.com/blog/2024/07/addons-by-default/
- https://about.readthedocs.com/blog/2024/04/enable-beta-addons/
- https://docs.readthedocs.io/en/stable/addons.html#enabling-read-the-docs-addons

I tried to enable addons and built the docs in a PR, but that didn't go too well. The readthedocs menu appeared as an overlay in the lower right, on top of the "switch to dark mode" button.

There is some mention of:

> We released a new version of our theme to keep the flyout menu at the bottom left integrated with the navbar that you can install it as sphinx-rtd-theme==2.1.0rc1.

and we currently have:

```
sphinx-rtd-theme>=0.5.1
```

So we might just need to update this and then see how it goes.

**Comment by laurenceisla** [comment]
Yes, I think it's OK with just the version selector. This should also fix #3240
