### ISSUE TITLE
Does postgrest not support "not null" as valud `is` value?

### ISSUE THREAD

**Issue by softmarshmallow** [PostgREST/postgrest#3747]
```
failed to parse filter (is.not null)
```

Forcing negate on quering `not null` value seems like a mistake, `not is null` and `is not null` are identical, but as I am building a dynamic query builder, having to transform (negating) the operator by its value is quite not straight forward.

This might seem like a nich-cased suggestion, but
supporting value `not+null` or `not_null` seems like a generally good idea (also for others)

: )

E.g.

<img width="266" alt="image" src="https://github.com/user-attachments/assets/18de965e-5807-4b01-bbfd-f5c100f48229">

**Comment by steve-chavez** [comment]
> supporting value not+null or not_null seems like a generally good idea

Not opposed, it seems convenient for dynamic filters as you mention but it would be low priority for us. A PR would be welcomed too.

**Comment by AchilleasTsiamoulis** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
