### ISSUE TITLE
Add (or document) response compression options

### ISSUE THREAD

**Issue by DpadamsX** [PostgREST/postgrest#3814]
## Problem

I cannot find any way to get PostgREST to compress responses. I cannot find any examples or discussion either. I have experimented with setting request headers to ask for compression, but all responses remain chunked uncompressed.

## Solution
Support compressed responses.

I expect that I'm missing something obvious. The Yesod and Warp projects both mention `gzip` as an obvious middleware component to hook in.

Thanks for help, or consideration of this request.

**Comment by mkleczek** [comment]
PostgREST philosophy is similar to Unix. Do one thing and do it well. So it does not compress responses at all.

Similar to TLS you should put PostgREST behind a reverse proxy (like NGNIX) and configure compression there.

**Comment by DpadamsX** [comment]
Thank you for the clarification.

**Comment by DpadamsX** [comment]
This took me some time to figure out, figured I'd add a minimal setup here for anyone else who is experimenting. For context, it's been a *long* time since I've done any Web server admin, and I've never used Nginx. However, that's what we use up on AWS, and my goal is to stand up PostgREST inside of our AWS VPC, connecting to an RDS instance. 

```
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include            mime.types;
    default_type       application/octet-stream;

    sendfile           on;

    keepalive_timeout  65;
	gzip               on;
	gzip_types         text/plain text/csv text/json;
	gzip_min_length    1024;
	gzip_comp_level    5;
	gzip_buffers       16 8k;
	gzip_proxied       any;
	gzip_vary          on;

    server {
        listen       8080;
        server_name  localhost;

        location / {
            root   html;
            index  index.html index.htm;
        }
        
       location /api/ {
            proxy_pass http://localhost:3000/;
        }


        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

    }

    include servers/*;
}
```

Gotta say, NGNIX is _way_ nicer to config than the nightmare that is Apache. 

For my narrow case, the goal here is to find out if the cost of compression/decompression pays for itself in our environment. I'm looking at PostgREST as a data feed for DuckDB, and other tools, within our AWS VPC. The network speeds up there are great. I'm requesting `text/csv`, and am pulling a response payout of 35.2 MB, or 4.6 MB compressed. On my local macOS machine, the response time is under 1 second one way, with a slide edge for *uncompressed* data. But, kind of a meaningless test, honestly.

I'll set it up PostgREST and NGNIX on an EC2 linux instance and see how it works there. 

Thanks for the direction.
