### ISSUE TITLE
customize log verbosity

### ISSUE THREAD

**Issue by ilkosta** [PostgREST/postgrest#540]
Hi,
Postgrest seems fantastic! 
It would be nice to see logged near the requests submitted to postgrest, also the pg response errors.
What do you think?

**Comment by begriffs** [comment]
We could add that, although the errors will be in your db logs as well depending on your logging settings.

**Comment by begriffs** [comment]
Note there is more documentation now about debugging server problems - https://postgrest.readthedocs.io/en/v0.4/admin.html#debugging

**Comment by begriffs** [comment]
Revisiting this, a log level would be nice in order to both reduce logging (since it might be duplicating the logs of a proxy server), or turn them up.

I propose we allow syslog style [log levels](https://en.wikipedia.org/wiki/Syslog#Severity_level).

**Comment by trourance** [comment]
Hi, are there any progress on that ? 
All other tickets end up here. I would like to have some verbose logging without having to modify the db side logs, for example for SSL connection:
`SSL established: TLSv1.2/ECDHE-RSA-AES256-GCM-SHA384/ECDH=prime256v1`

**Comment by steve-chavez** [comment]
When having several clients that access the database, it can be hard to pinpoint the log entries that belong to a particular pgrst instance.

I think we should recommend using [log_line_prefix](https://www.postgresql.org/docs/9.5/runtime-config-logging.html#GUC-LOG-LINE-PREFIX) and setting [application_name](https://www.postgresql.org/docs/12/runtime-config-logging.html#GUC-APPLICATION-NAME) in the connection uri(on `db-uri`). This would be like:
```
postgres://user@localhost/mydb?application_name=pgrst_mydb_myschema"
```
I was also thinking if we could somehow set the `application_name` ourselves. But in any case this should be documented.

**Comment by steve-chavez** [comment]
I have a counterpoint against doing more detailed logging in the syslog style.

Recently, I helped an user that was in need of an audit trail for PostgREST events, this was needed for compliance with a standard. The idea was to have detailed request information in JSON(payload body, headers, success/error codes, etc) and then send them to Kafka for later processing.

Naturally the first idea that comes to mind was to add more detailed logging in PostgREST itself and construct the required JSON.

However, this detailed logging would introduce code paths that can lead to performance degradation. In the past we have had problems such as #690 and #925(#1206 still open btw). Those were fixed basically by not messing with the payload body in Haskell code and instead rely on directly sending it to pg through parametrized queries.

So, why introduce these issues in PostgREST(we'd have to discuss what goes in a DEBUG level, which format, measure the memory consumption impact, go back to previous perf issues for certain settings, etc) when PostgreSQL logs can already be formatted in JSON(thanks to [jsonlog](https://github.com/michaelpq/pg_plugins/tree/master/jsonlog), this was the eventual solution we landed on) with much more detailed information than what we could output in pgrst(certain error messages will not be exposed through libpq, see https://github.com/nikita-volkov/hasql/issues/112).

[CSV logs](https://www.postgresql.org/docs/current/runtime-config-logging.html#RUNTIME-CONFIG-LOGGING-CSVLOG) are also already available in pg and `jsonlog` could soon be included in core(see [this discussion](https://www.postgresql.org/message-id/CAH6vsW%2Bx_UUkfb2AqUTKJDJxGjBCsD%3DUCkQHqGWErQtRPg0kPA%40mail.gmail.com)).

I think PostgREST has remained and should still be a transparent layer over PostgreSQL. We could leave the detailed logging to PostgreSQL. In a way this would also reinforce our "db as the source of truth" principle.

I propose we refrain from detailed logging and to always do minimal logging(not go to a higher level).  Instead we should add to the docs a good explanation on logging with these recommendations https://github.com/PostgREST/postgrest/issues/540#issuecomment-540649767 (we can include some log samples) and with a single `grep pgrst_mydb_myschema` one can get all the detailed logging pg already provides for your pgrst instance(to debug SSL issues, etc).

**Comment by steve-chavez** [comment]
For docs, we could also show how to set the [log_min_messages](https://www.postgresql.org/docs/9.5/runtime-config-logging.html#GUC-LOG-MIN-MESSAGES) per postgrest app. By recommending to set the setting per user(can also be done per db but probably not desired), like: `alter role authenticator set log_min_messages to fatal`.

**Comment by steve-chavez** [comment]
A lower level of logging - for failed requests(status >=400):

- Can be done by using https://hackage.haskell.org/package/wai-extra-3.0.29.2/docs/Network-Wai-Middleware-RequestLogger.html#t:RequestLoggerSettings in `Middleware.hs`.
- Example of how to use this: https://stackoverflow.com/a/25538767/4692662

**Comment by hivemall** [comment]
another to options for the record:
- if log is too verbose on clientside eat it in nginx: https://github.com/PostgREST/postgrest-docs/issues/326
- if systemd started postgrest is too verbose reroute it via `StandardOutput= etc `

**Comment by steve-chavez** [comment]
One more reason to offer a lower log level, the verbose output makes the log file grow quickly.

Also, one other thing I've noticed is that our connection retries messages go to `stdout`. They should go to `stderr`.

So, looks like we should have a `logging_level` config option that offers three levels:

- `info`: Our current logging level. Log all requests, successful or unsuccessful.
- `debug`: In addition to logging all requests. Show the main SQL query. No parameters from prepared statements will show.
- `error`: Only log unsuccessful requests.

Should `error` be the default level? Maybe we should make a breaking change now.

**Comment by trourance** [comment]
+1 to set `error` as the default level.

**Comment by steve-chavez** [comment]
`log-level` config added! https://github.com/PostgREST/postgrest/pull/1604

Also, the `error` level is now the default.

I'll close this general issue and continue to track the `debug` level on https://github.com/PostgREST/postgrest/issues/1578.
