### ISSUE TITLE
Large memory usage for bulk inserts

### ISSUE THREAD

**Issue by begriffs** [PostgREST/postgrest#690]
I measured that PostgREST 0.3.2.0 uses memory proportional to 20x the size of a JSON payload during bulk inserts. This doesn't seem reasonable.

**Comment by begriffs** [comment]
Note to self: try using [weigh](https://www.fpcomplete.com/blog/2016/05/weigh-package) in tests to measure the space used.

**Comment by ruslantalpa** [comment]
Is this still a thing?
I remember it being a thing in #360 but that thread says it was fixed in 3.0

**Comment by maximsch2** [comment]
I'm seeing similar problems with CSV uploads as well.

**Comment by begriffs** [comment]
@maximsch2 would you be interested in helping us track down the problem? The issue that Ruslan linked to includes information about running how to run the binary with profiling enabled. If you're feeling brave you could do a similar thing and include a graph of memory allocation.

**Comment by steve-chavez** [comment]
I have a proposal for avoiding the json payload processing in `INSERT` and clearing this out, I'll use the [articles table](https://github.com/begriffs/postgrest/blob/master/test/fixtures/schema.sql#L380-L384) as a reference.

Currently when receiving a payload like `[{"id": 11, "body": "uno"}, {"id": 12, "body": "dos"}]` we process this in Haskell to check if the json is an `array/object` to adequately use pg `json_populate_recordset/json_populate_record` functions.

This part can be done in pure SQL:
```sql
WITH payload AS(
-- This json would be replaced by $1
  SELECT '[{"id": 11, "body": "uno"}, {"id": 12, "body": "dos"}]'::json AS json_data 
),
vals AS(
  -- With this we make sure that the query works for json arrays or a single json object
  SELECT json_data AS val FROM payload WHERE json_typeof(json_data) = 'array'
  UNION ALL
  SELECT json_build_array(json_data) AS val FROM payload WHERE json_typeof(json_data) = 'object'
)
INSERT INTO articles(id, body) SELECT id, body from json_populate_recordset(null::articles, (select val from vals));
```

Now the other thing that the Haskell processing does is making sure the json has the same columns, not sure but I'm guessing the original purpose of this was to somehow protect against unintentional null values in a bulk insert? Anyway I think this would be better handled by the db not null contraints.

However this part also handles the `<cols>` specifying in  `ÌNSERT INTO table(<cols>) SELECT <cols> FROM ...` and that cannot be done in SQL, this is also necessary for handling column privileges.

My proposal is to have an additional `INSERT` mode that will be triggered when the `columns` querystring parameter is specified like this:
```http
POST /articles?columns=id,body
[{"id": 11, "body": "uno"}, {"id": 12, "body": "dos"}]
```
If there are additional columns in the json payload they will be ignored, this mode will guarantee minimum memory usage for big payloads from pgrst end.
