### ISSUE TITLE
Support manually indicated relations for foreign entity expansion

### ISSUE THREAD

**Issue by deinspanjer** [PostgREST/postgrest#709]
Currently, if you are serving a complex query, especially one that uses sbuqueries or CTEs, it is very possible that postgrest will not be able to determine the foreign key relations and hence there will be no foreign entity expansion available. See #546, #562, #568 for some recent examples.

While improvements to the auto-detection would always be great, at some point, I believe it makes sense to put the control back in the developer's hands and allow them to explicitly list the relations.

We've discussed two main approaches to providing this customization:
1. A configuration option that points to a table in the DB somewhere having a specific structure similar to the current return of the query that does foreign relation detection.  The detection function would perform a union of the detected relations with the records in this table and postgrest would use the combined results to provide foreign entity expansion.
2. A configuration option pointing to some external configuration file whose structure (json, csv, yaml, etc.) would provide the same information described above.

The biggest difference between the two is the current preference of the project to not rely on the database to have any particular objects or structure other than the schema to which postgrest is bound on startup.

**Comment by ruslantalpa** [comment]
@deinspanjer while your request is the goal, you can for now use a hardcoded table with relations.
I saw on gitter you mentioned something with this not working with rpc's, not sure why that would be. if you do it like i's explain below i don't see why it would not work.
a) have a table with custom relations.
b) have a view that does a union between the current query and the results from that table
c) change postgrest query to look for data from that view.

PS: you might need to use the same approach for both "relations" and "synonyms" query.

**Comment by deinspanjer** [comment]
I need to dig up the STR for the problem I ran into with rpcs, but the tl;dr version is that when I tried to create new entries in my hardcoded relations table, I found that all the functions had the same table alias name in postgrest so I couldn't distinguish between them.

**Comment by ruslantalpa** [comment]
i think if you union the query in postgrest with your custom table everything should work.
the embedding in rpcs work by inspecting the return type of the rpc, it was probably a table that you did not add in your custom table.

**Comment by steve-chavez** [comment]
We now have a faster and better query for detecting fk columns in VIEWs with CTE/subselect, see the views used for the tests [here](https://github.com/steve-chavez/postgrest/blob/allSynonyms-perf/test/fixtures/schema.sql#L1476-L1550) and the [tests](https://github.com/steve-chavez/postgrest/blob/allSynonyms-perf/test/Feature/QuerySpec.hs#L370-L393).

It should work as long as the columns come unmodified from the target, i.e. not doing an `upper(code_pk)` or having a `select x.id from (sel.. union sel.. union.. sel) x`, for these cases even PostgreSQL cannot tell the origin table.

I had an idea on https://github.com/PostgREST/postgrest/pull/1115#issuecomment-404032018 (approach 2) for manually specifying fk columns for the views, however all of the issues accumulated here are already solved and implementing that may not be necessary, so I'll close this issue once https://github.com/PostgREST/postgrest/pull/1115 is merged.
