### ISSUE TITLE
Postgrest does not respond with a Preference-Applied header

### ISSUE THREAD

**Issue by jackfirth** [PostgREST/postgrest#740]
HTTP Preferences are intended to be optional requests by clients that servers can choose to ignore at whim. Because of this, if a server chooses to honor a preference it may respond with a `Preference-Applied` header listing the preferences the server applied to the request. Postgrest does not return this header, meaning clients cannot tell immediately what preferences were applied without analyzing the response body.

This behavior is documented by [section 3 of RFC 7240](https://tools.ietf.org/html/rfc7240#section-3). Inclusion of the header is optional, but the RFC specifically points out this is a good idea for the "return=representation" preference since it can be difficult for clients to determine whether this was applied or not.

**Comment by ruslantalpa** [comment]
As things stand now there is not a single case of preference header that postgrest ignores so there is no practical reason for adding this response besides "respecting RFC". When a client sends a header, it's 100% applied, no need to look at the body.
Unless there is a specific problem this solves, it's just additional bytes in the response

**Comment by begriffs** [comment]
True, the RFC states

> Use of the Preference-Applied header is only necessary when it is not
   readily and obviously apparent that a server applied a given
   preference and such ambiguity might have an impact on the client's
   handling of the response.

The question is, is it readily apparent which Prefer headers are applied? As Ruslan pointed out, we always apply any Prefer header that we understand. Thus it's generally clear. There are two situations I can see where it might be unclear, but may not be worth the extra overhead on every response to address them:

1. Detecting when new versions of PostgREST drop support for Prefer headers. For instance `Prefer: count=none` is now default behavior so the server no longer "applies" that header. However if this is a confusion we could alternately return an error to the client and that would be an even more effective (albeit brash) way to let them know about use of an unsupported header.
2. Debugging requests. Sometimes people don't really know what they are sending, or a proxy strips out request information. Preference-Applied would reliably indicate which options made it to the server. However an alternative way to handle debugging is to allow verbose server logging, assuming the person debugging the client is also involved with the API server.

**Comment by jackfirth** [comment]
@ruslantalpa: You're correct that if a client *assumes* it's speaking to a Postgrest server (more specifically, a Postgrest server of a particular known version), than the Preference-Applied header isn't useful. Preferences are meant to be general enough that a client can use them without knowing details about the specific server requests are being sent to. When using a standard preference like "return=representation" which many different servers may implement special handling for, I think it's worthwhile to indicate that the preference was applied so clients without Postgrest-specific knowledge can take advantage.

@begriffs: Request debugging is my primary motivating use case. Server logs help, but often when I develop services that are Postgrest clients I point them at the Heroku example app to avoid needing to set up my own local postgrest just for prototyping and manual testing. So I think there's value in not assuming server logs are readily available in all use cases.

**Comment by ruslantalpa** [comment]
@jackfirth can you give a theoretical example of such a client (the purpose of it's existence) that would be accessing an api without being aware it's talking to a particular service?
I don't mean that it knows the api is implemented using postgrest but it knows it is talking to api `A` and it's specifically coded against that api, and in their docs, api `A` just as postgrest would say `if you want this then add that header`. I just don't see a specific case where client would end up accessing a particular api (like a crawler would) without knowing exactly to which api it is talking to and knowing exactly the format of a request, what each parameter does and what each header does.
I don't dispute that there might be value in having this info for debugging purpose (although i would always develop on my local host where i have control over every component) but adding this means it's only useful in a very few specific instances which happen only in development phase and detrimental 100% of the time in production.

**Comment by jackfirth** [comment]
Postgrest itself is such a client - it connects to any database without knowing the exact specifics of what tables are available and what the logical purpose of columns are. It's not specifically coded against anything in the database, merely the postgresql protocol.

Generally, this sort of thing comes up when you have generic services. Caches, for example, _definitely_ have reason to use the `return` preference for arbitrary APIs - without sending `return=representation` and knowing it's applied they can't know if it's safe to cache the response to a `PUT` request.

**Comment by ruslantalpa** [comment]
I don't understand the analogy to postgrest, it knows exactly to which database it talks to, the proper format of a request. For postgrest the database/schema/columns are the data it manipulates.
The caches example however makes a more sense, i can see how a middle-layer component might benefit from more descriptive headers.
However i would vote for this type of feature when there is a specific need/request/usecase in production driving it and not a theoretical one. For example if someone says something like "Hey, i am implementing a caching layer for my postgrest based system and some missing headers/info is preventing me form doing this and that, can we add this feature?". 
To me "RFC compliance/debugging support" are not particularly appealing reasons.

**Comment by jackfirth** [comment]
I am implementing that caching layer :) It's not used for anything commercial presently, but this is not a theoretical benefit for me.

**Comment by ruslantalpa** [comment]
Cool, in this case can you give a specific example?
The request being made, the response received, how this additional header is helping you make a decision that you otherwise could not make? 

PS: how exactly are you implementing this (if it's not a secret), where is the place of this component in the stack?

**Comment by jackfirth** [comment]
I'm writing some web libraries for Racket, one of which is for caching. I want to make it easy to add local in-memory in-process caching to requests made to an arbitrary API. This runs into the issue I described. If the request is a PUT, I'd like to tell the server to give me a response I can cache so I don't have to make a follow-up GET request. Since these are requests to any arbitrary API, I can't just assume the response is a cacheable representation so I add the `return=representation` header and assume the response if cacheable if the appropriate Preference-Applied is set. I can add options to allow library users to force this behavior without too much trouble, but it seems strange to do so when the Preference-Applied header's purpose matches my problem exactly. To me, this is a nice-to-have benefit (and it makes me appreciate how well thought out the spec for HTTP preferences is.)

**Comment by ruslantalpa** [comment]
Why didn't you start with that, this makes total sense :)
Will this lib be opensource (not asking for anything, just curious)

**Comment by jackfirth** [comment]
Hopefully once it's in a usable state :) I'm also working on a postgres cache channel service. A cache channel is basically an event feed that the Cache-Control header provides a standard way of referencing. If fifty resources all say they have the same cache channel, instead of polling all fifty resources you can poll just the channel to get a list of recently updated resources. This event list can be autogenerated for any table that has a "last_modified" timestamp column and trigger that updates it whenever the database changes, so it can be a generic component just like Postgrest.

**Comment by ruslantalpa** [comment]
I am not sure if this cache channel is the same thing or not but this https://vimeo.com/145847021 method seems like a very nice way of "populating" caching layers without the need for triggers/events in the db or a middle man watching the traffic.

PS: if it was not clear, i vote yes for this feature since it has a specific use case in production, it's trivial to implement and if it's not desired, the header can be suppressed by the proxy.

**Comment by taimoorzaeem** [comment]
> As things stand now there is not a single case of preference header that postgrest ignores so there is no practical reason for adding this response besides "respecting RFC". **When a client sends a header, it's 100% applied,** no need to look at the body. Unless there is a specific problem this solves, it's just additional bytes in the response

@steve-chavez does that mean whenever the client sends a `Prefer: return=representation` the postgrest server honors it every time on a successful response?

**Comment by steve-chavez** [comment]
@taimoorzaeem Yes, it does.

**Comment by taimoorzaeem** [comment]
@steve-chavez Also, is it allowed to respond with multiple Preference-Applied header?, for example

```
Content-Type: ...
Preference-Applied: return=representation
Preference-Applied: tx=rollback
```

**Comment by steve-chavez** [comment]
Yes, but it'd be clearer/shorter to have them as a single header with comma separated values, which is also valid.

```
Preference-Applied: return=representation, tx=rollback
```

See https://greenbytes.de/tech/webdav/rfc2616.html#rfc.section.4.2
