### ISSUE TITLE
No errors when desc/asc ordering modificators are misspelled

### ISSUE THREAD

**Issue by NikolayS** [PostgREST/postgrest#781]
By mistake, I made a typo and wrote `...?order=mycolumn.dec` in API call – so basically I wrote `dec` instead of `desc`.

PostgREST accepted it, producing no errors... It did ordering with `asc`. This time I was lucky enough to quickly find that typo. But it potentially would be very hard to catch.

I expect that it should report, that only either `asc` or `desc` are accepted in that place.

**Comment by begriffs** [comment]
Makes sense, could be annoying to track that sort of thing down otherwise.

**Comment by tedkornish** [comment]
I'd like to take a stab at this one. The request should probably respond with a `400 Bad Request` and maybe a plaintext payload like:

```
invalid ordering "dec" on column "mycolumn"
```

**Comment by begriffs** [comment]
Thank you, I'd appreciate your help with this one! If you run into problems feel free to open a pull request with what you've got and we can discuss it from there.

As for the error message, we usually try to return a json object with fields:

* message (required)
* details
* hint
* code

You could put the string you suggested into message, and maybe mention the correct possible values in the hint.

**Comment by steve-chavez** [comment]
Fixed in #1104.
