### ISSUE TITLE
JWT secret shall not be allowed to be empty

### ISSUE THREAD

**Issue by eric-brechemier** [PostgREST/postgrest#822]
I recently encountered this issue on PostgREST v0.3.0.3: while there is a check in place to ensure that the parameter `--jwt-secret` is present, there was no complaint when the provided value was `''` (the empty value being the result of an error, not a conscious choice).

The goal of this ticket is twofold:

1. warn users of older versions of PostgREST
2. kindly request a check (if not in place already) to ensure it does not happen with the latest version

**Comment by begriffs** [comment]
Thanks for the note. Can you check whether 0.4 is susceptible to the problem as well?

As an unrelated observation, 0.3.0.3 is really really old, have you considered using a newer 0.3.x version? Look at all the bugfixes for later releases: https://github.com/begriffs/postgrest/releases

**Comment by eric-brechemier** [comment]
No actually, we only considered migrating to 0.4, but I see now that upgrading to latest 0.3.x would be a good stepping stone. Do you keep a list of issues fixed in each new release? I have looked for additional details for several issues listed in the change log, but failed to identify the issue which matched the description, e.g. ("Prevent role from being changed twice" and "Prevent query error from infecting later connection").

**Comment by eric-brechemier** [comment]
> Can you check whether 0.4 is susceptible to the problem as well?

Yes, I confirm that the issue is present on `master`.

I left the `jwt-secret` empty:

```
## choose a secret to enable JWT auth   
## (use "@filename" to load from separate file)   
jwt-secret = ""        
# secret-is-base64 = true
```

and started the server without getting any complaint.

I generated a JWT using the empty secret `''` and checked that it was accepted by this instance of the server.

**Comment by begriffs** [comment]
> Prevent role from being changed twice

This one was a duplicate `SET ROLE ...` statement sent during authentication. It was harmless but just a little inefficient.

> Prevent query error from infecting later connection

This one happened after calling a stored proc that raised an exception. The next http request could sometimes end up using the previous postgresql connection and getting an error result.

___________

In the future I'll include issue numbers to the changelog so it's easier to get more details.

**Comment by eric-brechemier** [comment]
Thanks.

**Comment by steve-chavez** [comment]
Looks like this was already fixed in https://github.com/PostgREST/postgrest/commit/d6a848c8859f3ec7c37d5efab6bc02d5d60ec5cb but github somehow didn't close the issue.
