### ISSUE TITLE
conf file parsing error

### ISSUE THREAD

**Issue by pycal** [PostgREST/postgrest#909]
I'm new to postgrest, apologies in advance if I've just plain missed something, but I believe I've found a parsing error with the way conf files are handled.

I am getting an error at step 5 of the tutorial here: https://postgrest.com/en/v4.1/tutorials/tut0.html

This conf file doesn't work (note the $ in my password):
```
db-uri = "postgres://postgres:mysecretpassword$@localhost/postgres"
db-schema = "api"
db-anon-role = "web_anon"
```

It produces this error:
```
postgrest: ParseError "" "Failed reading: satisfy"
```

This conf file works as expected:
```
db-uri = "postgres://postgres:mysecretpassword@localhost/postgres"
db-schema = "api"
db-anon-role = "web_anon"
```

**Comment by zalmarge** [comment]
My guess is you have to escape $ with hex equivalent. From documentation:

**db-uri**
    The standard connection PostgreSQL URI format. Symbols and unusual characters in the 
    password or other fields should be percent encoded to avoid a parse error.

**Comment by begriffs** [comment]
@pycal did escaping help?

**Comment by gual** [comment]
> @pycal did escaping help?

@begriffs not OP but it worked for me. Thanks, @zalmarge.

**Comment by pycal** [comment]
Sorry to have left this hanging. Yes, this worked. Thanks!
