### ISSUE TITLE
Improve error message: "JWSError JWSInvalidSignature"

### ISSUE THREAD

**Issue by begriffs** [PostgREST/postgrest#991]
This is often caused by using sub-32 character jwt keys, but https://github.com/frasertweedale/hs-jose/issues/46#issuecomment-321754582 mentions a new `checkJWK` function we can use to get more specific errors for display.

**Comment by pycal** [comment]
This can also be caused by using a different secret key to sign the JWT

**Comment by wolfgangwalther** [comment]
Also tracked in #1840, with a bit more discussion.
